### ISSUE TITLE
perl not compiling

### ISSUE THREAD

**Issue by pplu** [Microsoft/BashOnWindows#532] opened 2016-06-15 06:59 UTC
Hi,

I'm trying to compile perl on 

```
wget http://www.cpan.org/src/5.0/perl-5.24.0.tar.gz
tar xvzf perl-5.24.0.tar.gz
cd perl-5.24.0/
./Configure -d
make
```

It fails at a step where it tries to load Pod::Simple::SimpleTree, but it seems to not be in miniperls' INC PATH. It would seem that some early stage in the build process fails due to someting in WSL not working as expected.

**Comment by lateau** [comment] 2016-06-16 15:27
```
PERL5LIB=/path/to/perl-5.24.0/cpan/Pod-Simple/lib make
```

**Comment by pplu** [comment] 2016-06-20 20:31
The strange thing is that it isn't picking it up automatically (on Linux it does).

This makes utilities like plenv and perlbrew not work correctly (they don't set the PERL5LIB, and they use a temporary directory for compiling perl).

Maybe @xsawyerx can help out or point to someone that can help find out what's going on

**Comment by benhillis** [comment] 2016-06-20 20:33
@pplu It depends where the environment variable is defined.  Could you check in your ~/.profile file for "PERL5LIB"?

If it's present in profile you'll have to launch bash.exe as a login shell to get it to load automatically:

`bash.exe --login`

**Comment by xsawyerx** [comment] 2016-07-21 15:23
I might be misunderstanding this problem, but you shouldn't have to set the `PERL5LIB` environment variable in order to compile `perl`.

For any perl + Windows debugging, I would personally refer to @bulk88. He's the expert.

**Comment by pplu** [comment] 2016-07-22 07:37
@benhillis I coincide with SawyerX. It looks like somewhere in the compilation chain, that PERL5LIB env variable gets lost. It doesn't on Linux.

@bulk88: I found specially helpful this GitHub bug https://github.com/kraih/mojo/issues/954 and where it links to, to get the the subsystem installed and working, and some Perl issues corrected

**Comment by erossetto** [comment] 2016-09-16 20:26
Anyone figured out how to get perl compilation working?

**Comment by pplu** [comment] 2016-09-18 19:53
@erossetto: I've got perl to compile manually (no plenv) from a source tarball by setting the PERL5LIB as @lateau suggests. It's an ugly workaround, but it works 😄

**Comment by mbeijen** [comment] 2016-09-27 19:16
The problem is that File::Find can't search recursively on the FUSE filesystem that is used by BashOnWindows. See also #186.

This will make the compilation work:

    echo "dont_use_nlink='define'" >> Policy.sh
    ./Configure -des
    make
    make install

**Comment by stehufntdev** [comment] 2017-01-10 16:58
#186 is marked as fixed and closed, so doing the same here.  Please reopen if you are still hitting issues and we can investigate.

**Closed by stehufntdev** 2017-01-10 16:58 UTC
Labels: perl

**Comment by pplu** [comment] 2017-01-10 17:22
@stehufntdev I've been able to compile Perl 5.24.0 😄
