### ISSUE TITLE
Not all data is send after shutdown/closing a socket

### ISSUE THREAD

**Issue by RobertFromBerlin** [Microsoft/BashOnWindows#1041] opened 2016-09-02 13:45 UTC
Hi,

I noticed a problem with sockets on version 10.0.14393. When a socket is shutdown'ed and closed sometimes not all data is flushed so the corresponding recv is failing. I attached example code. Start the server and then the client (give the ip address of the server as argument, I used localhost). Expected result is that the client should run till CTRL-C. What happens is that the client fails after some iteration (usually lower than 1000). Same code is running without any problem on native Ubuntu 14.04.

Robert

[client.txt](https://github.com/Microsoft/BashOnWindows/files/452137/client.txt)
[server.txt](https://github.com/Microsoft/BashOnWindows/files/452138/server.txt)

**Comment by iz0eyj** [comment] 2016-09-02 15:10
@RobertFromBerlin this using 14915 & Ubuntu Xenial

 Iter 1655
 Iter 1656
 Iter 1657
 Iter 1658
 Iter 1659
 Iter 1660
 Iter 1661
 Iter 1662
 Error : Peer shutdown 
federico@BESTIA:~/Sviluppo/Prove/CS$

**Comment by aseering** [comment] 2016-09-02 17:57
Thanks for reporting this!  It sounds similar to #616 ; possibly the same issue?

**Comment by RobertFromBerlin** [comment] 2016-09-02 18:36
Sounds similar, yes.

**Comment by elupus** [comment] 2016-09-06 14:29
i think that would be normal behavior if SO_LINGER is not enabled and not lingering on exit is not working. 

It could be that WSL don't let sockets linger after application exit() which linux normally does, Either explicit turn on of SO_LINGER or a sleep() on exit should make your test program work.

To work without linger, you'd need the following (mainly posted for reference)
server:
```
shutdown(SEND)
while( recv() > 0)
  ;
close()
```

client
```
x = recv()
if(x == 0) {
   shutdown(SEND) /* can be left out */
   close();
}
```

**Comment by sunilmut** [comment] 2016-09-07 22:18
Without full root cause, it's difficult to eliminate the possibility of the SO_LINGER option here, but just FYI, SO_LINGER has been supported in the WSL INET sockets for a while now.

**Comment by sunilmut** [comment] 2016-12-04 03:35
Marking this as duplicate of #616.

**Closed** 2017-03-09 21:32 UTC
Labels: duplicate, fixinbound, network
