### ISSUE TITLE
Unable to exit Windows processes in Creators Update

### ISSUE THREAD

**Issue by Xyene** [Microsoft/BashOnWindows#1870] opened 2017-04-10 03:01 UTC
I searched for similar issues before posting this and couldn't find anything like it; my apologies if this is a duplicate of a ticket I've missed. This seems similar to #1614, but I'm not entirely sure.

I'm running the Creators Update (`ver` reports 10.0.15063), and whenever I want to exit (by means of Ctrl+C) a Windows process I've started from bash, the process isn't closed but IO goes back to bash. Once I start a new Windows process, the IO connects to the old (supposedly killed) process instead of the new one.

### Example

```
$ python.exe
Unable to translate current working directory. Using C:\tools
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> print "This is Python!"
This is Python!
>>> ^C
$ cmd.exe
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\>ver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'er' is not defined
>>> print "This is still Python!"                        
This is still Python!
>>> ^C
$ echo "This is bash"
This is bash
```

At this point in time, Windows reports the `python.exe` process as still running:

```
C:\>tasklist | findstr python
python.exe                   13100 Console                    1      8,536 K
```

I expect `python.exe` isn't being closed by Ctrl+C, but directing the IO streams of subsequent commands to a previous "detached" one (as opposed to the newly-spawned one) is fairly unintuitive. Is this a limitation of the Windows interop implemented so far, or an error?

**Comment by benhillis** [comment] 2017-04-10 15:21
Marking as a duplicate of #1614.

**Closed by benhillis** 2017-04-10 15:21 UTC
