### ISSUE TITLE
Problem with Nodejs > npm install

### ISSUE THREAD

**Issue by jieverson** [Microsoft/BashOnWindows#96] opened 2016-04-10 00:32 UTC
![npm install](https://cloud.githubusercontent.com/assets/1031323/14407316/49b6deb4-fe9a-11e5-8705-beca8a036e4b.PNG)

Is anyone running nodejs at windows bash? I'm having lots of errors trying to run **npm install**
I cant even install **gulp** globally.

**Comment by filipeaguiar** [comment] 2016-04-10 01:43
This is a duplicate of #3 and #14, they're related to #9.

**Comment by russalex** [comment] 2016-04-11 17:27
Closing this one out since it is a dup.

**Closed by russalex** 2016-04-11 17:27 UTC
