### ISSUE TITLE
/etc/mtab is not symlinked to /proc/mounts

### ISSUE THREAD

**Issue by Edwin-Edward** [Microsoft/BashOnWindows#150] opened 2016-04-12 08:41 UTC
Some tools like df need this in order to work (see screenshot)
Can't think of other uses right now but it's a good practice to have it linked. 
(It's linked in all modern distros and since we do not have an init or init scripts, no one is going to populate a real text file in /etc/mtab)

![image](https://cloud.githubusercontent.com/assets/7404683/14454397/affe312a-009a-11e6-926f-6edf618bbd36.png)

**Comment by stehufntdev** [comment] 2016-04-15 15:03
On my native Ubuntu 14.04 machine /etc/mtab is a regular file, and it seems to be written out by init or one of the daemons (see below).  WSL uses the native Ubuntu binaries but we currently do not run the native init or daemons which probably why this file is not present.

Please give us feedback on the [uservoice ](https://wpdev.uservoice.com/forums/266908-command-prompt-console/category/161892-bash) page so we can prioritize df appropriately.

test@UBUNTU-SERVER:~$ stat /etc/mtab
  File: ‘/etc/mtab’
  Size: 809             Blocks: 8          IO Block: 4096   regular file
Device: 801h/2049d      Inode: 7621296     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-04-15 06:54:30.436743600 -0700
Modify: 2016-03-30 08:48:02.878940800 -0700
Change: 2016-04-14 12:03:42.928743600 -0700
 Birth: -
test@UBUNTU-SERVER:~$ uptime
 07:58:44 up 15 days, 23:10,  2 users,  load average: 0.00, 0.01, 0.05

**Comment by Edwin-Edward** [comment] 2016-04-21 08:02
Added uservoice feedback: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13514730-df-and-maybe-other-tools-not-working-because-of

**Comment by scottfweintraub** [comment] 2016-04-23 19:50
Not sure the link is an accurate solution.  root and /mnt/* are supposed to be using different file systems (https://blogs.msdn.microsoft.com/wsl/2016/04/22/windows-subsystem-for-linux-overview/) and we see only one.

**Comment by SvenGroot** [comment] 2016-04-23 20:24
The information reported in /proc/self/mounts is currently not accurate, unfortunately. We are investigating improving this in a future release.

**Comment by benhillis** [comment] 2016-06-17 18:49
Thank you for filing the user voice entry!  I'm going to close this issue out since on native Ubuntu /etc/mtab is not a symlink.

**Closed by benhillis** 2016-06-17 18:49 UTC

**Comment by piranna** [comment] 2016-10-06 06:53
I'm using Ubuntu and `/etc/mtab` is in fact a symlink...

```sh
ls -l /etc/mtab 
lrwxrwxrwx 1 root root 19 may 29 16:18 /etc/mtab -> ../proc/self/mounts
```

I think this would be the case since Ubuntu 15.04, but I would bet it was also on 14:04. Can you confirm that the previous statement of Ubuntu 14.04 NOT using a symlink was done on a clean install and NOT in an upgrade of a previous version?

**Comment by stehufntdev** [comment] 2016-10-06 13:50
Yes, I believe the 14.04 install was clean.  However on my clean install of 16.04 the file is now a symlink.

**Comment by piranna** [comment] 2016-10-06 14:29
> Yes, I believe the 14.04 install was clean. However on my clean install of 16.04 the file is now a symlink.

I asked so because the machine where I'm currently writting and from the previous snippet it was a clean install, but don't remember if it was of Ubuntu 13.10, 14.04 or 14.10, but definitely it was a clean install of one of that versions and it's using the symlink I put before. Good to know that in the current LTS is using a symlink too, so probably it should be done too on WSL...

**Comment by tylerl0706** [comment] 2016-10-06 15:09
+1 to adding a symlink for `/etc/mtab`.

**Comment by orinwalker** [comment] 2017-06-07 16:13
I see that this is marked as completed for new Win10 insider builds. If this is just building a symlink, then can someone provide the syntax for building the symlink as a workaround? I'm still a Linux noob.

**Comment by crcrewso** [comment] 2017-06-07 16:43
On a fresh WSL 16.04 system 
``ls -l /etc/mtab `` produces 
``ls: cannot access '/etc/mtab': No such file or directory``

On a fresh 16.04.02 VM 
``ls -l /etc/mtab `` produces 
lrwxrwxrwx 1 root root 19 may 29 16:18 /etc/mtab -> ../proc/self/mounts

Should this be reopened as it's a case of WSL Ubuntu not matching real Ubuntu?

**Comment by Meister-anon** [comment] 2023-07-31 02:15
...has this STILL not been fixed?

 sudo ln -s /proc/self/mounts /etc/mtab
ln: failed to create symbolic link '/etc/mtab': File exists

how?!

**Comment by AverageComet250** [comment] 2023-08-15 22:49
@Meister-anon that message is different from the error. In fact, that is the intended behaviour. 

if you run `ls -l /etc/mtab` you'll find the symlink already points to the correct place
