### ISSUE TITLE
'mv' hangs on partition in /mnt

### ISSUE THREAD

**Issue by ps** [Microsoft/BashOnWindows#1100] opened 2016-09-19 22:26 UTC
I just want to start with saying that I do like bash so far, great job!

* A brief description
I have two partitions C and D. I treat 'D' as a way to move files between Linux subsystem and Windows. So in 'D' I have a folder called cs519_papers (which I created via Windows). When I navigate to /mnt/d inside Linux and try to rename the folder via 'mv' the bash just hangs.

* Expected results
Folder is renamed properly via 'mv' command on Windows disk partition from Linux subsystem

* Actual results (with terminal output if applicable)
Terminal hangs with blinking cursor. Ctrl^C does not fix the issue. If I close Bash and reopen I get a black terminal window with blinking cursor. The only way that seems to fix issue is via hard restart (via button on tower) of PC (shutdown or restart inside Windows does not fix it). All other apps (such as Firefox) work fine while this is happening so system does not freeze.

* Your Windows build number
Microsoft Windows [Version 10.0.14393]

* Steps / All commands required to reproduce the error from a brand new installation 
1. Go to partition D and create new folder called folder1Test (I have another folder and pdfs inside all fetched via Windows gui)
2. cd /mnt/d
3. mv folder1Test folder1Test_test

* Strace of the failing command
mmap(0x7f32ea1a0000, 17088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f32ea1a0000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libpcre.so.3", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\27\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=252032, ...}) = 0
mmap(NULL, 2347200, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f32e9ba0000
mprotect(0x7f32e9bdd000, 2093056, PROT_NONE) = 0
mmap(0x7f32e9ddc000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3c000) = 0x7f32e9ddc000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\16\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=14664, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f32eaa80000
mmap(NULL, 2109744, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f32e9990000
mprotect(0x7f32e9993000, 2093056, PROT_NONE) = 0
mmap(0x7f32e9b92000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f32e9b92000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f32eaa70000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f32eaa60000
arch_prctl(ARCH_SET_FS, 0x7f32eaa60840) = 0
mprotect(0x7f32ea19a000, 16384, PROT_READ) = 0
mprotect(0x7f32e9b92000, 4096, PROT_READ) = 0
mprotect(0x7f32e9ddc000, 4096, PROT_READ) = 0
mprotect(0x7f32ea3b3000, 4096, PROT_READ) = 0
mprotect(0x7f32ea5c6000, 4096, PROT_READ) = 0
mprotect(0x7f32ea7ef000, 4096, PROT_READ) = 0
mprotect(0x61c000, 4096, PROT_READ)     = 0
mprotect(0x7f32eaa22000, 4096, PROT_READ) = 0
munmap(0x7f32eaaa4000, 21406)           = 0
statfs("/sys/fs/selinux", 0x7fffe5888850) = -1 ENOENT (No such file or directory)
statfs("/selinux", 0x7fffe5888850)      = -1 ENOENT (No such file or directory)
brk(0)                                  = 0x10f1000
brk(0x1112000)                          = 0x1112000
open("/proc/filesystems", O_RDONLY)     = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f32eaa50000
read(3, "nodev      sysfs\nnodev      root"..., 1024) = 367
read(3, "", 1024)                       = 0
close(3)                                = 0
munmap(0x7f32eaa50000, 4096)            = 0
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2919792, ...}) = 0
mmap(NULL, 2919792, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f32e96c7000
close(3)                                = 0
geteuid()                               = 1000
ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
stat("cs519_papers1", 0x7fffe5888820)   = -1 ENOENT (No such file or directory)
lstat("cs519_papers/", {st_mode=S_IFDIR|0777, st_size=0, ...}) = 0
lstat("cs519_papers1", 0x7fffe58884f0)  = -1 ENOENT (No such file or directory)
rename("cs519_papers/", "cs519_papers1"

**Comment by fpqc** [comment] 2016-09-19 23:43
I think maybe something like this was posted before and was also fixed in an insider build.  I know it's a little bit much to ask, but would you mind re-running the test on the latest fast-ring insider build (14926)? 

If you are using WSL, and you aren't on the insider builds, you probably will not be receiving any bugfixes or feature improvements for WSL until probably the Redstone 2 release (probably either in January or next August (depends if Redstone 2 is going to be next year's major release (August), or if it's going to be the winter refresh (December or January, if I had to guess based on last year's release schedule)).

**Comment by benhillis** [comment] 2016-09-20 00:25
This is a duplicate of #671.

**Closed by benhillis** 2016-09-20 00:25 UTC
