### ISSUE TITLE
Bugs when render multibyte chars 

### ISSUE THREAD

**Issue by powercode** [Microsoft/BashOnWindows#1876] opened 2017-04-11 08:01 UTC
With creators update, a new issue surfaced with rendering PowerLine multibyte chars.

Powerline works with customized fonts specifically created for prompts, with symbols for source control, etc. For example, they have the reverse separator, 0xE0B2, that is most often rendered as a backwards triangle.

The following is a sample of the text that does not work well any more.
here is '0xE0B2'
\esc[s\esc[79G\esc[45m\esc[90m\esc[100m\esc[30m0:00:00.0190\esc[100m\esc[37m\esc[47m\esc[30m08:59:47\esc[37m\esc[45m

https://github.com/powerline/fonts/tree/master/DroidSansMonoSlashed is a powerline font that can be used for testing.
Images displaying the issue can be found here: https://github.com/Jaykul/PowerLine/issues/13

![image](https://cloud.githubusercontent.com/assets/3505151/24898712/141f5aae-1e9e-11e7-91af-59a26885ed32.png)

Cheers!

**Comment by PhMajerus** [comment] 2017-04-13 15:34
It's not just with multibyte chars, I think this is related to an issue I found out about how the console renders chunks of texts with different colors. It regularly ends up being off by one characters when computing the starting column of a new chunk depending on characters and DPI scaling : https://github.com/Microsoft/BashOnWindows/issues/1907

**Comment by zadjii-msft** [comment] 2017-04-13 16:48
Yep, I can confirm that this is the same "ambiguous width characters" issue that @miniksa described in #1907. I'm gonna close this issue as a dupe of that one, to hopefully condense the discussion into one thread.

**Closed by zadjii-msft** 2017-04-13 16:48 UTC
Labels: console, duplicate
