### ISSUE TITLE
setcap command used not working with node application

### ISSUE THREAD

**Issue by alanosman** [Microsoft/BashOnWindows#871] opened 2016-08-11 21:07 UTC
Hi,

I am back to testing again on WindowsBash.  I am hopeful to get our application working. But I hit a stumbling block.  On my Ubuntu server, we grant permission to node running under a user account by using the following command:

`sudo setcap cap_net_bind_service=+ep `readlink -f \`which node\```

When I try to do this it, i get a failure message:

```
Failed to set capabilities on file `/home/aosman/.nvm/versions/node/v4.4.5/bin/node' (Invalid argument)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
```

I know that the path to node and the file inside the bin directory exist.  The file permissions are:

```
-rwxrwxr-x 1 aosman aosman 24878254 May 24 13:28 /home/aosman/.nvm/versions/node/v4.4.5/bin/node*
```

I have the latest fall production release of Windows 10 (1607 / 14393.51).

Do you guys know if this should work?  Also, is there another way to let node access port 80 that I am missing on WindowsBash?
thx.

**Comment by aseering** [comment] 2016-08-11 23:28
Hi @alanosman -- thanks for posting this!  Hopefully someone actually on the WSL team can respond, but I would guess that the `cap_net_bind_service` capability hasn't been implemented.

You could bind to a higher port and use a Linux program or Windows firewall rule to map the higher port to port 80.

The only way I know of to directly bind to port 80 right now is to run as root.  Which isn't ideal.  But it's much less scary than running as root on a real Linux system:  The WSL `root` user isn't a Windows administrator; it's still constrained by the regular-user permissions that your personal Windows user account has.  Also, the unprivileged WSL user account has access to the Windows filesystem, and there's a documented unprivileged flag (which I'm forgetting right now...) to the Windows `bash.exe` command that starts it with a root shell.  So, unlike on Linux, root and an unprivileged WSL account are not all that much different from a security perspective.

**Comment by alanosman** [comment] 2016-08-11 23:33
Hi @aseering  - thanks for the quick response.  Yes, I figured out about 2 hours ago that I could run it as root.  Not super optimal, but it is certainly a workaround.  I guess eventually, you should be able to do this kind of function so we avoid the sudo -i all the time to get node running.  But I will say this, I had a different problem where when I tried to execute node as sudo (i.e. sudo node server.js), it would report that the command was not found.  Yet when I sudo -i into the account, i could run node.  So something strange is going on there also.  I can open another issue for that if you think it's worthy. lmk

**Comment by aseering** [comment] 2016-08-11 23:41
Hm...  Where is node installed for you?  (`which node`)

`sudo` is supposed to run with a more bare-bones environment for security reasons.  (If a malicious attacker got access to your user account and inserted `$HOME/.hax0red/bin` at the front of `$PATH` and put hacked copies of lots of common tools there, it'd be bad for you, but it'd be much worse if you tried to do `sudo <some hacked command>` and it ran as root...)

`sudo -i` is supposed to start with the bare-bones environment but then run `bash --login`, which runs your systemwide bashrc and profile which may add more paths to `$PATH`.

**Comment by alanosman** [comment] 2016-08-11 23:55
@aseering normally we install our app under the user account and not as root.  But in this instance I was trying all kinds of things to get the application to complete it's npm install, and ended having to installing node as both root and user.  I believe (and I was documenting my steps) the reason why I installed as root was to get node-gyp and bcrypt to compile properly.  They were not compiling as user, so I cheated that way.  

When I run ```which node``` as me, I get ```/home/aosman/.nvm/versions/node/v4.4.5/bin/node```
When I run ```which node``` as root, I get ```/root/.nvm/versions/node/v4.4.5/bin/node```

btw, I cannot run "sudo which node".  I get nothing back when I try that.

**Comment by aseering** [comment] 2016-08-12 00:03
Ah, ok.  In this case I think the `sudo` vs `sudo -i` thing is expected behavior (on both WSL and Linux) -- neither of the above paths are in `sudo`'s minimal default `$PATH`.

Not the most friendly behavior, I know...  You could try talking to [the sudo maintainers](https://www.sudo.ws/), or looking around online.

If I'm wrong and regular Linux behaves differently in this scenario, incidentally, definitely post back here.

**Comment by alanosman** [comment] 2016-08-12 00:07
I checked the single line sudo operation on our stage server and it gave me the which results as expected.
![2016-08-11_2006](https://cloud.githubusercontent.com/assets/2914981/17609049/4683dde8-5fff-11e6-94a9-aed430a8270a.png)

**Comment by aseering** [comment] 2016-08-12 13:40
@alanosman -- yep, that looks consistent with this scenario.  Thanks for verifying!

**Comment by benhillis** [comment] 2017-07-11 15:33
Support for this has been added in Windows build 16226.  Marking as a duplicate of #574.

**Closed by benhillis** 2017-07-11 15:33 UTC
