### ISSUE TITLE
bazel hangs when ran

### ISSUE THREAD

**Issue by dtracers** [Microsoft/BashOnWindows#620] opened 2016-07-03 02:46 UTC
It also runs on java (so it may be related to the maven issue?) and performs no actions when you attempt to run it.

It does install perfectly fine

**Comment by misenesi** [comment] 2016-08-03 18:05
Could you provide repro steps along with strace log please?

More details here:
https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md

**Comment by slamphear** [comment] 2016-08-07 05:00
I'm seeing this as well. Here's the information requested in misenesi's link:

1-2: See original post.

3: Microsoft Windows [Version 10.0.14393]

4:
```
$ sudo apt-get update && sudo apt-get install bazel
$ sudo apt-get upgrade bazel
$ bazel help
```
Nothing ever happens after this. Here's a screenshot (you can see that I typed "bazel help" and the cursor moved down a line, but nothing ever happens after that):
![image](https://cloud.githubusercontent.com/assets/4347651/17460487/93383b36-5c2e-11e6-99d6-dbfbffb61e6a.png)

After waiting (I actually left this running overnight once just in case something was taking a long time), I'll eventually just Control+c to return to the prompt. All I see is this:

![image](https://cloud.githubusercontent.com/assets/4347651/17460545/4e1b46a8-5c31-11e6-9ec7-63421a68732d.png)

5: See 4 above.

6: Performing the same commands in a Bash shell in a an Ubuntu 16.04 VM, I am presented with the following information:
![image](https://cloud.githubusercontent.com/assets/4347651/17460501/37b1c538-5c2f-11e6-8bc8-9b07472a6405.png)
I would expect to see the same output within Bash for Windows.

7: [Here's the link to my strace output.](https://gist.github.com/slamphear/fc9b6b000e6ba5fdc25fd6334c51ee85)

Here's a screenshot of where the strace output hangs:
![image](https://cloud.githubusercontent.com/assets/4347651/17460528/6a8f25a8-5c30-11e6-9992-8bf3a4107ca8.png)

Let me know if you need any additional details. This seems to be the only thing preventing me from being able to stay in Windows for all of my Magenta experimentation, so I'm really hoping someone can help out here!

**Comment by slamphear** [comment] 2016-08-07 15:23
It looks like this has something to with Java, since the "java -version" command was hanging for me as well. I decided to switch to openjdk-7 and the Java 7-friendly version of Bazel, and now I'm hanging at "Extracting Bazel installation...". My updated strace output can be found [here](https://gist.github.com/slamphear/0c3cc222a260ab1698c9c43197562d38).

**Comment by pkonovalov-softheme** [comment] 2016-08-13 19:44
+1 The same problem,  @slamphear Also building Tensorflow from sources in Win10 bash? Let be in touch on this issue.

**Comment by dtracers** [comment] 2016-08-13 19:49
Tensor flow works on CPU version if you do not build it from scratch.  But
you can't do anything like custom operations

**Comment by misenesi** [comment] 2016-09-30 00:41
Hi guys,

I have just tried it and on my internal build it seems to be fixed:

![image](https://cloud.githubusercontent.com/assets/9508502/18977029/d31b90ba-866b-11e6-96aa-771908f285cc.png)

Thank you, closing for now.

**Closed by misenesi** 2016-09-30 00:41 UTC

**Comment by souptc** [comment] 2017-02-14 04:43
@misenesi, I meet this issue when trying play with tensorflow on my windows bash, could share which version of windows bash and bazel you are using to fix this issue?

**Comment by welnaseth** [comment] 2017-03-01 02:07
@misenesi are you using openJDK or Oracle's JDK? I found that if I use Oracle's JDK, I can run `bazel help` and `bazel version` fine, but when i try to build anything with bazel it hangs. The specific case I am currently hanging on is when I run ./configure during the process to build tensorflow from its source. It'll get through the setup, and then hang when bazel is supposed to run. Could you try to build tensorflow from source and see if it works for you? I can post repro steps if needed.

**Comment by benhillis** [comment] 2017-03-01 05:18
@welnaseth - some repro steps would be useful - I can give this a try on a recent build and make sure things are working.

What build are you running?

**Comment by welnaseth** [comment] 2017-03-02 01:49
Running the `ver` command in cmd outputs this:
Microsoft Windows [Version 10.0.14393]

Alright, so first I purged any openJDK packages and ran an `sudo apt-get autoremove` to remove any unneeded packages that were left over. The I installed Oracle's Java 8 JDK and made sure it was up to date. This works fine and I can run `java -help` and `java -version` just fine. Next I followed theses instructions to build tensorflow from sources: [https://www.tensorflow.org/versions/master/get_started/os_setup#installing_from_sources](url)

After I cloned the repository I followed these instructions to install Bazel:
[https://bazel.build/versions/master/docs/install.html#install-on-ubuntu](url)

After this I was able to run `bazel help` and `bazel version` successfully. Finally, I installed the needed python3 dependencies because I wanted to build for python 3. From there I run `./configure` and I configure it to find the correct python3 folder, select the default compile option, and have no additional options. It then says `Configuration Finished` and proceeds to hang after printing a single "." to the console. I _once_ got it to go a bit further, but it still hung during the build process.

Hopefully that's enough information to recreate the problem. Let me know if I should post an strace or need to be more detailed in any way.

**Comment by welnaseth** [comment] 2017-03-10 17:06
@benhillis Just checking in, any progress on this issue? I know it may not be a top priority since it's a closed issue, but I thought I'd ask for an update since it's been over a week. We're you able to recreate my issue on a recent build?

**Comment by benhillis** [comment] 2017-03-15 00:33
@welnaseth - I'm sorry I have not had time to try.  I will try to find some time this week to go through your repro instructions.

**Comment by welnaseth** [comment] 2017-03-15 19:27
@benhillis No rush! Just thought I'd check in.

**Comment by benhillis** [comment] 2017-03-17 00:11
@welnaseth - I was able to follow your instructions and build successfully.

**Comment by welnaseth** [comment] 2017-03-17 03:52
@benhillis was this on a newer build than the one I have? If so, I'll look forward to the next update to hopefully fix my issue :)

**Comment by benhillis** [comment] 2017-03-20 15:08
@welnaseth - Yes, you're running Anniversary Update (14393) and I'm running a build that will very closely resemble Creator's Update.

**Comment by davido** [comment] 2017-04-12 19:00
@welnaseth I'm running Creator's Update, since yetserday: (Version: 1703, build number: 15063.138). It look much better now, still trivial and non trivial projects hang during the build: [1].

```
$ bazel run printy
INFO: Found 1 target...
[8 / 9] Still waiting for 1 job to complete:
      Running (unknown):
        BazelWorkspaceStatusAction stable-status.txt, 286 s
<hung>
```

Now I can take stack dumps: [2],[3],[4],[5],[6]

* [1] https://github.com/davido/bazel_printy
* [2] http://paste.openstack.org/show/606336/
* [3] http://paste.openstack.org/show/606337/
* [4] http://paste.openstack.org/show/606338/
* [5] http://paste.openstack.org/show/606339/

**Comment by welnaseth** [comment] 2017-04-12 19:12
@davido I am running into similar issues. I can now run the configure script for tensorflow, which was my initial issue, so that's a plus. Now when I try to build the pip installation file for tensorflow, it hangs at various points. Currently installing the creators update on another computer to confirm the hanging issue, and then hopefully  I can get some helpful stack traces to post here as well.

**Comment by welnaseth** [comment] 2017-04-13 04:53
Update:
After running the build with then command `bazel build --config=opt --verbose_failures --local_resources 2048,.5,1.0 --jobs 1 //tensorflow/tools/pip_package:build_pip_package` it finally finished building without hanging. It took awhile, but it finally completed. you could try these extra flags and see if your builds work?

This command is no where near ideal, since it takes forever to run without concurrent jobs, but it accomplished the task I wanted.

**Comment by davido** [comment] 2017-04-14 07:16
Unfortunately, it didn't help either. It still hangs:

```
davido@wizball:~/projects/gerrit$ bazel build --verbose_failures --local_resources 2048,.5,1.0 --jobs 1 gerrit
.
INFO: Loading package: @webcomponentsjs//
```

**Comment by renanmontebelo** [comment] 2019-02-28 03:09
This happens to me once everyday. A complete Windows restart solves it. `wslconfig /terminate` does not help. OpenJDK 8 @ Ubuntu

**Comment by PovelikinRostislav** [comment] 2019-10-06 10:38
Have hangs with WSL Ubuntu 18.04 LTS.
Env:
`bazel 0.29.1`
`Windows Build 17763`
`openjdk 11.0.4 2019-07-16`

```
bazel --help
Killed non-responsive server process (pid=8754)
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
... still trying to connect to local Bazel server after 22 seconds ...
```
and so on until I cancel the command
Steps to reproduce: `bazel --help`
