### ISSUE TITLE
Swift language does not work in wsl

### ISSUE THREAD

**Issue by GERMANOCARELLA** [Microsoft/BashOnWindows#1341] opened 2016-11-09 21:36 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
I installed swift language downloaded from www.swift.org, for ubuntu 16.04.
I installed clang and libicu-dev.
So I ran 
swift

* Expected results
A swift shell

* Actual results (with terminal output if applicable)
Failed to run REPL process: a packet returned error: 8

* Your Windows build number
Last build
* Steps / All commands required to reproduce the error from a brand new installation 
download from www.swift.org
tar xzf swift-release.tar.gz
cd swift-directory
cp -R * /
apt install clang libicu-dev
swift

* Strace of the failing command

* Required packages and commands to install
clang
libicu-dev
See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by AndyDeany** [comment] 2016-11-10 09:56
You should probably be using the version of Swift for Ubuntu 14.04, as this is what Bash for Windows is based upon. I still get the same issue with the correct version however.

**Comment by GERMANOCARELLA** [comment] 2016-11-10 10:42
Hi,

Probably is because swift uses executable stack that is not supported in 
wsl.



Il 10/11/2016 10:56, Andrew Dean ha scritto:

**Comment by fpqc** [comment] 2016-11-10 19:52
@andydeany Nope, new official target is 16.04.

**Comment by AndyDeany** [comment] 2016-11-10 21:57
@fpqc Really? How do I update?

**Comment by jackchammons** [comment] 2016-11-10 22:50
`sudo do-release-upgrade`

**Comment by jackchammons** [comment] 2016-11-14 20:32
Marking this Swift issue as a duplicate of #286

**Closed by jackchammons** 2016-11-14 20:32 UTC
Labels: duplicate
