### ISSUE TITLE
Can't see files placed in user/AppData/Local/lxss/rootfs/var/www/vhosts by windows explorer when in wsl

### ISSUE THREAD

**Issue by nickweavers** [Microsoft/BashOnWindows#1271] opened 2016-10-25 16:22 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* Description of issue
I have set up a Linux webserver under wsl and have my vhost'ed sites under /var/www/vhosts.
I have a git client installed and am able  to clone/push/pull from my remote private gitlab server via ssh from within wsl. I can see my wsl files from windows in the lxss eg. 
`C:\Users\<user>\AppData\Local\lxss\rootfs\var\www\vhosts\dev.mydomain.co.uk`
but when create a file under this diectory from within windows, it is not seen inside wsl. This means I can't simply point my Windows based IDE at my source files under wsl via lxss and develop.
I am unsure if this is a bug or is working as designed. It seems that when files are created under my source directory (eg via a git clone) they show up in windows (eg with File Explorer) but not vice-versa.

* Expected results
I expected that any files placed in 
`C:\Users\<user>\AppData\Local\lxss\rootfs\var\www\vhosts\dev.mydomain.co.uk`
via an action under windows would show up in wsl under
`/var/www/vhosts/dev.mydomain.co.uk`

* Actual results (with terminal output if applicable)
They don't

* Your Windows build number
Version 1607, Build 14951.1000

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by nickweavers** [comment] 2016-10-25 17:27
Maybe setting it up the way I have was a bit dumb since I'm stuck on the system drive when confining myself in C:\Users\<user>\AppData\Local\lxss\rootfs\var\www\vhosts and it would be better doing it the other way around by having my source files in say /mnt/<drive>/var/www/vhosts. I'll try it this way around .

**Comment by nickweavers** [comment] 2016-10-25 17:46
This last approach seems to work fine.

**Comment by fpqc** [comment] 2016-10-25 18:11
Yeah, don't touch anything in the lxss folder tree from win32. Most Win32 applications are going to trample on the carefully created ntfs extended attributes that WSL uses to emulate permissions.

**Comment by nickweavers** [comment] 2016-10-26 07:52
So, when I create files or directories in /mnt/<drive> under wsl, they all appear to be owned by root tthere, although I created them as nickw. If I try to chown them to nickw:nickw it doesn't work (silently failing). They also get created with all the rwx filebits set on (u,g & o). I can't chmod them to say 755 or 644.

How should I understand the ownership/filebit side of things for /mnt files in the context of wsl? In particular the ones we create there via wsl and might want to restrict access to in wsl via the linux ownership/filebit settings?

**Comment by fpqc** [comment] 2016-10-26 09:55
@nickweavers It works exactly like the ntfs-3g driver on Linux, but with the UID being root and the permissions set to 777.

**Comment by stehufntdev** [comment] 2016-10-26 16:19
Closing this out since it is expected behavior.  The blog post and video linked above by fpqc has more details.

**Closed by stehufntdev** 2016-10-26 16:19 UTC
