### ISSUE TITLE
WSL reports environment session uptime, not system uptime

### ISSUE THREAD

**Issue by segin** [Microsoft/BashOnWindows#657] opened 2016-07-15 02:39 UTC
- A brief description

Function calls requesting system uptime return the uptime for the current environment session, and not the uptime for the system.
- Expected results

System uptime
- Actual results (with terminal output if applicable)

Uptime of current WSL environment session, for example from a newly-spawned WSL session:
![image](https://cloud.githubusercontent.com/assets/480709/16861940/09ae94a8-4a0b-11e6-916d-c21d9ef586de.png)
- Your Windows build number

14379
- Steps / commands required to reproduce the error:
1. Open a WSL environment session using `bash.exe` or similar.
2. Run `/bin/uptime`
3. Wait a few minutes
4. Run `/bin/uptime`
5. Kill all Linux processes and end the current WSL session.
6. Launch a new WSL session.
7. Immediately run `/bin/uptime`
- Required packages and commands to install

Nothing additional that isn't provided by running `LxRun /install` 

If this is actually the intended behaviour, then feel free to close this IR, but please document it as the intended behaviour (as it is currently undocumented.)

**Comment by benhillis** [comment] 2016-07-19 15:39
Out of curiosity, is there something that is broken due to this behavior?

**Comment by benhillis** [comment] 2016-07-25 15:26
From the subsystem's perspective we do not "boot" until you launch bash.exe for the first time.  Marking this as "by design."  If you have a scenario that is broken because of this please let us know.

**Comment by segin** [comment] 2016-07-25 21:00
No broken scenario (yet), but I'm glad to see this clarified as a design
decision.

**Comment by benhillis** [comment] 2016-11-02 15:19
Closing this out.

**Closed by benhillis** 2016-11-02 15:19 UTC
Labels: bydesign

**Comment by oninoshiko** [comment] 2019-07-23 17:46
I realized you closed this out, but this is an issue for me. I really want to use WSL, but am forced to go with cygwin because of this.

While I understand why it responds this way, it really is quite astonishing of a response. Is there no way we can expose the system uptime for this?

**Comment by benhillis** [comment] 2019-07-23 17:50
Can you describe your scenario in more detail? You should be able to use interop (running .exes) to query Windows state.

**Comment by oninoshiko** [comment] 2019-07-23 18:00
We have a handful of windows machines in a mostly linux environment. We have a system that remotely sshs in and checks a number of things, one of which is uptime. Rewriting the system to have a special code-path for the windows machines adds additional complexity incurring both immediate and future costs.

Not to mention, it's straight-up unexpected behavior to not have uptime show the time the system has been up. I don't think anyone who's used any linux or unix based system would ever expect that.

**Comment by iam8up** [comment] 2021-05-11 13:54
I'm not sure if this is the best place, please correct me if it is not.

Another use case I've found was having cron jobs execute during a particular time.  If we have a WSL on the machine, it seems to be entirely halted making it impossible for cron to work.  I'm running WSL version 2, on a CentOS 7 install.
