### ISSUE TITLE
BSOD when browsing for /mnt/c/Users/Charles in GIMP

### ISSUE THREAD

**Issue by charlesmilette** [Microsoft/BashOnWindows#479] opened 2016-06-06 15:50 UTC
Whenever I browse for /mnt/c/Users/Charles in GIMP ran from WSL, it BSODs my computer:

[Video](https://i.imgur.com/ciFrmJ1.webm)

[Minidump and event tracer](https://github.com/Microsoft/BashOnWindows/files/300459/BSOD.zip)

**Comment by stehufntdev** [comment] 2016-06-06 20:02
Thanks for reporting the issue and sharing the minidump.  This is a known issue in 14342, can you please upgrade to 14352+ where this is fixed?

**Comment by stehufntdev** [comment] 2016-06-06 20:05
Closing this out as a duplicate of #360 since that is the same issue.

**Closed by stehufntdev** 2016-06-06 20:05 UTC
Labels: duplicate, fixed

**Comment by charlesmilette** [comment] 2016-06-06 21:09
I'll update once the new build is available on slow, because I can't afford having a really unstable OS, so I stay on slow.
