### ISSUE TITLE
Graphic application support?

### ISSUE THREAD

**Issue by alexanderwhatley** [Microsoft/BashOnWindows#481] opened 2016-06-07 05:05 UTC
Right now, if I open Xming on windows and type "firefox &" into the terminal, I am sometimes able to get a firefox window to open outside the terminal, but other times it crashes. I am unable to get any of the text editors or IDEs I currently use, such as the jupyter notebook, to open at all. Are there any plans to allow bash on windows to open graphical applications outside of the terminal right now?

**Comment by sunilmut** [comment] 2016-06-07 06:05
@alexanderwhatley - Thanks for reporting this. There was a socket bug that was fixed recently, which allowed applications over Xserver to be more stable. Don't think that has made it to the release branch yet, but should soon. That doesn't mean "full support", but that we can treat issues on a case by case basis. Please do report issues as you encounter them and thanks for trying out WSL!

**Comment by therealkenc** [comment] 2016-06-07 21:23
For that it is worth, Xlib proper seems relatively stable as of 14352, so kudos to the team on that. Eyes/xedit/xman/xcalc all work, though you can get xeyes to freeze reliably with a fast resize. Is that the socket bug you're talking about? Editors and IDEs right now are mostly blocking on known issues that are not strictly X11 related, such as #216 and #376.

**Comment by russalex** [comment] 2016-06-08 21:17
The socket changes @sunilmut mentioned look to be in build 14361.  I was able to run xEmacs and modify a file in DrvFs.

Take a look a Jupytr or another editor that you use.  GUIs are not on our priority list, but a lot of our fixes expand support quite a bit.  It also help us to know the failures.

**Comment by therealkenc** [comment] 2016-06-09 08:56
@russalex, as you allude, it looks like WSL is going to get GUI apps as other stuff gets addressed even though they are out of scope for the project. Firefox runs in 14361, which is kind of blowing my mind at the moment. Sublime Text is also working. [looks...] LibreOffice even works.

Electron based editors, like VS Code and Atom fail on what appears to be #468.

**Comment by maxime-tournier** [comment] 2016-06-09 11:26
as of 14361 it seems that Qt (4 and 5) applications also seem to work, which is great news.

**Comment by therealkenc** [comment] 2016-06-11 02:35
Funny - youtube videos play on firefox on ubuntu on wsl on xming on windows. CPU at 8%, no lag no jitter. [No sound either, lol.] I wanted to be clever and post a screencap of the WSL [launch video](https://msdn.microsoft.com/en-us/commandline/wsl/about) playing, but the firefox flash plugin isn't working. Never fix that: blame the people managing the MSDN site for still using flash. :)

![yt-on-wsl](https://cloud.githubusercontent.com/assets/7049700/15982561/cc007634-2f3f-11e6-8f90-c5d0feb71b53.jpg)

**Comment by benhillis** [comment] 2016-06-11 04:25
Doom runs pretty well too :)
![image](https://cloud.githubusercontent.com/assets/17727402/15983097/5aac6404-2f51-11e6-8378-38b3387a6337.png)
sudo apt-get install doom-wad-shareware prboom

**Comment by o-g-o** [comment] 2016-06-11 08:01
Got Firefox running very well also on build 14361. But first time go a BSOD right after launch. Did work fine after. Could not repodruce the BSOD.

Also tried a comparison of octanejs on WSL and on native Windows. On many tests WSL is much faster, on a few tests much slower. Final score is similar on windows and wsl.

Amazing work guys :)

**Comment by S3curityPlu5** [comment] 2016-06-13 05:01
They arent using flash if u are on mobile device. Just change useragent to mobile

Sent via the Samsung Galaxy S®6 active, an AT&T 4G LTE smartphone-------- Original message --------From: therealkenc <notifications@github.com> Date: 6/10/2016  10:35 PM  (GMT-05:00) To: Microsoft/BashOnWindows <BashOnWindows@noreply.github.com> Subject: Re: [Microsoft/BashOnWindows] Graphic application support? (#481) 
Funny - youtube videos play on firefox on ubuntu on wsl on xming on windows. CPU at 8%, no lag no jitter. [No sound either, lol.] I wanted to be clever and post a screencap of the WSL launch video playing, but the firefox flash plugin isn't working. Never fix that: blame the people managing the MSDN site for still using flash. :)

**Comment by benhillis** [comment] 2016-06-17 19:13
Going to close this one out since X11 support seems to be working well in 14366.

**Closed by benhillis** 2016-06-17 19:13 UTC
Labels: fixed

**Comment by aseering** [comment] 2016-06-17 20:47
@benhillis -- for what it's worth, my experiences with X11+WSL would not lead me to say that it is "working well".  See #187 .

**Comment by benhillis** [comment] 2016-06-17 20:49
Which server are you using?  I'm using Xming and it's working great.

**Comment by aseering** [comment] 2016-06-17 20:50
I'm also using Xming.

**Comment by aseering** [comment] 2016-06-17 20:54
Have you tried launching emacs?  Do you experience either of the issues in the last two comments on #187 ?  If not, I'll take another look at my config.

**Comment by benhillis** [comment] 2016-06-17 20:55
I'll give it a shot, first I'll have to install emacs, all 24 gigs of it /sarcasm.

**Comment by aseering** [comment] 2016-06-17 20:57
What can I say?, I like Lisp-based operating systems :-)  Anyway, thanks!

**Comment by benhillis** [comment] 2016-06-17 21:02
I'm seeing the same issue you report in #187 locally.  Let me see if I can figure out what's going on with that infinite loop.

**Comment by alexanderwhatley** [comment] 2016-06-18 06:34
Hey sorry guys - I'm on 14366 now, and after opening Xming, I haven't been able to get either jupyter notebook or spyder (Qt based I believe) to work.

**Comment by aseering** [comment] 2016-06-18 07:24
Jupyter Notebook has issues because one of the libraries that it depends on has a bug to do with certain networking-related error conditions.  (Not related to graphics or X11.)  #185 includes instructions on how to install a fixed version of the relevant library.

With the fix, Jupyter Notebook works well for me; I've used it quite a bit.  (Though I always just start it with "--no-browser" and open up a regular Windows web browser to view the notebook.)

I can't speak to spyder -- does it have a command-line mode, so that you can test whether the issue is specific to X11?  It's possible for programs that happen to be graphical, to fail for reasons that don't have to do with graphics.  (emacs is interesting because, in addition to the graphical mode that's not working, it can also run as a text-mode application.  In text mode it exposes exactly the same interface and features as in graphical mode.  And its text mode works just fine.  Which implies to me that something about the graphics may be directly relevant.)

**Comment by ntklotz** [comment] 2017-10-23 17:04
Is support for DirectX 12 making it's way into WSL? Not to mention the latest OpenGL and features such as TressFX?
