### ISSUE TITLE
ctrl-c not working on 'Bash on Ubuntu for windows'

### ISSUE THREAD

**Issue by alexgyori** [Microsoft/BashOnWindows#1597] opened 2017-01-13 19:27 UTC
Ctrl-c does not produce the expected results in bash. It doesn't kill a process and it doesn't properly get transmitted to the underlying shell, e.g., in emacs Ctrl-X Ctrl-C should close emacs, but instead of Ctrl-c, emacs receives only c.

It seems that when pressing Ctrl-c the shell receives only c (it prints c when pressing Ctrl-C in bash).

My build number is 15007.

**Comment by benhillis** [comment] 2017-01-13 19:29
Duplicate of #1569.

**Closed by benhillis** 2017-01-13 19:29 UTC
