### ISSUE TITLE
No connectivity from Bash to internet?

### ISSUE THREAD

**Issue by Honey0cool** [Microsoft/BashOnWindows#887] opened 2016-08-13 18:18 UTC
No connectivity from Bash to internet?

root@xxxx:~# ifconfig
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.
root@xxxx:~# ping www.google.com
ping: icmp open socket: Permission denied
root@xxxx:~# ip r
SO_SNDBUF: Invalid argument
root@xxxx:~# cat /etc/hosts
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
root@xxxx:~# cat /etc/resolv.conf
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 192.168.1.1
nameserver 172.18.11.1
nameserver 192.168.1.1

----------------------------
After Reinstall Windows 10’s Ubuntu Bash Shell

lxrun /uninstall /full
lxrun /install /y

Now “root” Account as the default user account . What ?

----------------------------
Additional Information
Antivirus - Details

Norton Security 
Version: 22.7.0.76

**Comment by iz0eyj** [comment] 2016-08-13 20:30
To use ICMP you must run WSL as Administrator (Win side).
I suggest to create a link on your desktop with "Run as admin" flag checked.

**Comment by Honey0cool** [comment] 2016-08-13 20:35
@iz0eyj Tried With Admin now ping Working but ifconfig still not working.

**Comment by rodrymbo** [comment] 2016-08-13 21:33
The usual internet devices (e.g. eth0) don't exist yet, and ICMP doesn't work for normal users. But connecting to the Internet works just fine, because it uses the Windows settings and devices.

The [docs for lxrun](https://msdn.microsoft.com/en-us/commandline/wsl/reference?f=255&MSPPError=-2147217396) are fairly clear. If you use /install /y, it sets up without asking anything, assuming you want root as the default user. It's easy to set the defaultuser, and you can use passwd when the default user is root to change the password on another user, if /setdefaultuser doesn't let you do it.

**Comment by bitcrazed** [comment] 2016-08-25 18:18
Duplicate of #69 

In Win10AU, ifconfig doesn't work and ICMP commands like `ping` require the bash console to be run elevated.

The team are working hard to fix these issues in RS2.

**Closed by bitcrazed** 2016-08-25 18:18 UTC
Labels: duplicate

**Comment by haidescs** [comment] 2017-10-16 07:54
@bitcrazed Is this issue solved? I still meet this problem when I am using ping, ifconfig, ip link, 
ip addr show, ifconfig, whois, nslookup...... What should I do?
