### ISSUE TITLE
Unable to download from the Windows Store

### ISSUE THREAD

**Issue by itaysk** [Microsoft/BashOnWindows#524] opened 2016-06-14 12:24 UTC
When running "bash" for the first time, it downloads the Ubuntu image from the Windows Store. more often than not it fails with:
"Unable to download from the Windows Store. Please check your network connection."

This happened to me on different networks, at home and at work, and on different builds, including the recent one 14361.

It's not a big deal since eventually after multiple retries it will succeed, but it's not a great first time experience.

**Comment by aseering** [comment] 2016-06-14 13:09
interesting -- thanks @itaysk for reporting this.  I suspect it would be useful to get some more detail, as I haven't heard of this happening elsewhere and I haven't experienced it myself.  Do you ever have trouble with other large-ish downloads?  What (if any) antivirus and/or firewall programs are you running?

**Comment by benhillis** [comment] 2016-06-14 15:11
@itaysk If you can reliably reproduce this issue would you be able to take a trace for us so we can identify what's going wrong?

**Comment by itaysk** [comment] 2016-06-14 15:35
I can try. How can I take trace?

**Comment by benhillis** [comment] 2016-06-14 15:41
Instructions here: https://github.com/Microsoft/BashOnWindows/issues/410#issuecomment-225668318

**Comment by xrobau** [comment] 2016-06-18 23:06
This appears to be because it's trying to download via FTP, in Active mode. Active FTP requires your router/firewall to explicitly allow connections back from the Microsoft FTP server.

Microsoft need to switch their FTP server to Passive mode, or, do not serve downloads via FTP at all.

To Microsoft: Guys, we have HTTP now. It can be proxied and cached. Please stop breaking the internet.  I realise it's a habit you guys have grown into over the years, but you're meant to be NOT doing it these days.

To people having this problem:  Reboot your router.  If you're behind two layers of NAT, it will be hit or miss if it ever works.  I'm guessing that's what the OP is experiencing.

**Comment by gegenschall** [comment] 2016-07-18 09:03
I'm getting this error as well. No matter what I do (even connecting directly to the internet, no firewall, no nat) I cannot download BashOnWindows anymore. I removed %localappdata%\lxss, removed/added "Windows Subsystem for Linux" from Windows Features, LAN instead of Wifi, running wsreset.

Is there any workaround?

**Comment by kimiazhu** [comment] 2016-08-04 06:10
I have the problem too. it always complains the network failure... i have reboot for several times.

**Comment by grounzero** [comment] 2016-08-12 09:27
Same issue here.  Tried with a local account and a Microsoft one using the anniversary update.

>bash
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store...
Unable to download from the Windows Store. Please check your network connection.

**Comment by foxundermoon** [comment] 2016-08-13 20:50
i'm also meet the fuck issue. I try many times every method.
first i'm use the cmder to install it
``` bash
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store...
Unable to download from the Windows Store. Please check your network connection.
```
then i'm through the powershell, through  lxRun /install  
i'm try to use proxy by Proxifier ,set the rule for lxRun.exe
it just has sent data but 0 received.
then i'm use the charles try to analyze the net  traffic ,but thier is no any  respone from go.microsoft.com:443.

```
ping go.microsoft.com

Pinging go.microsoft.com [113.215.18.43] with 32 bytes of data:
Reply from 113.215.18.43: bytes=32 time=2ms TTL=58
```
i'm try to edit the hosts file to change the dns.
```
104.90.27.171               go.microsoft.com
```
but also is the result .
can not change the microsoft domain dns .
ipconfig /flushdns  & restart  `NNS client` service  .... but all is useless.

**Comment by foxundermoon** [comment] 2016-08-14 06:16
today,i am change the dns domain ,and then use the proxy,
it seems well.
![the snapshot](https://cloud.githubusercontent.com/assets/2764106/17647600/90018cbe-6229-11e6-945d-c857f59dfaa1.png)

**Comment by anderuso** [comment] 2016-08-21 19:35
Check your windows firewall options. I had the same problem, adding rule for C:\Windows\System32\LxRun.exe solve the problem and image was downloaded and installed.

**Comment by zidongtuili** [comment] 2016-09-05 13:31
I just solved it. I had similar problem and I think mine is not a network issue, so I tried to use cmd to remove lxss directory (with rd command).

**Comment by miked63017** [comment] 2016-09-30 19:11
If anybody is having this problem in virtualbox, switching to bridged adapter instead of NAT worked for me.

**Comment by RoboMWM** [comment] 2016-10-03 20:09
This is happening after I tried to reinstall bash after uninstalling it with `lxrun /uninstall /full` due to forgetting my sudo password

**Comment by iadaking** [comment] 2016-10-04 08:14
```
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 39%
Unable to download from the Windows Store. Please check your network connection.
```
I also suffer from this problem and have no idea to deal with it 
can anyone help me?

**Comment by sunilmut** [comment] 2016-10-04 18:30
@iadaking - That's unfortunate. Can you please follow the steps below to collect some traces and send them our way?

1. Download the below two .txt files and rename them .cmd
2. Run start_lxcore_trace.cmd from an admin command prompt
3. Start the install.
4. Wait until you see the error.
5. Run stop_lxcore_trace.cmd from an admin command prompt
6. You should now see three .etl files in the directory you ran the script from.
7. Email the logs to: InsiderSupport@microsoft.com. Include in the subject / message to forward to the WSL team. In the body of the email mention it is for russalex and sunilmut. Also, mention the GitHub post ID in the mail for reference.

https://github.com/Microsoft/BashOnWindows/files/288621/start_lxcore_trace.txt 
https://github.com/Microsoft/BashOnWindows/files/288622/stop_lxcore_trace.txt

**Comment by zidongtuili** [comment] 2016-10-05 09:40
I used to have this issue, then I realised that was because I tried to mount vhd files to this directory. For anyone has failure of dowload, see if this works: create a folder called lxss under C:\Users\<your username>\appdata\local\ and delete this folder. (if you already have this folder, you may want to cut it elsewhere)

**Comment by sujeethk** [comment] 2016-10-06 02:55
@zidongtuili Thanks, this worked for me!

**Comment by zidongtuili** [comment] 2016-10-09 01:12
@sujeethk I'm glad that it helps. Sometimes this is really not a network related issue.

**Comment by mikeshultz** [comment] 2016-10-31 04:50
Should be obvious, but in case it isn't, to anyone running Avast, kill that as well.  It tries to screen everything and makes reliable connections basically impossible.

**Comment by backstabbd88** [comment] 2016-12-25 16:40
took me days to finally figure this out, the problem i had was downloading from windows store wouldn't finish.  Glad i came across this solution.

https://www.varunagw.com/how-install-windows-subsystem-linux-bashonwindows-offline-windows/

In this method you will
1. predownload the file (180mb) from microsoft, 
2. host it in your local web server, ( i used XAMPP)
3. During bash installation process, use Fiddler to divert the request of the file to your localhost
4. Download will be instant since file is already in your localhost

**Comment by sqc1999** [comment] 2017-01-09 08:15
I created a simple project that can install BashOnWindows even **without Internet access**.
You just need to download some files before installation.
Hope it can help.
Project: https://github.com/sqc1999/LxRunOffline
Download: https://github.com/sqc1999/LxRunOffline/releases

**Comment by sqc1999** [comment] 2017-01-09 08:17
@backstabbd88 Your method seems to be too complex, Fiddler itself has AutoRespond feature that can automatically respond using a local file.

**Comment by backstabbd88** [comment] 2017-01-09 11:03
Nice work @sqc1999 . I wished i had found your method earlier. It was really frustating for someone like me who has no IT background, it was my first time to use fiddler and also first time  to setup a localhost.

**Comment by ahbusaidi** [comment] 2017-01-22 15:13
I had the same problem the solution was just to run the command prompt as Administrator.

**Comment by timothy** [comment] 2017-02-23 14:26
No matter how many times I try to download Bash it always fails at some point. I think the furthest I have got is 38% before receiving the error "Unable to download from the Windows Store. Please check your network connection." I have tried using PowerShell as Admin and CMD as Admin. Is there any current workaround of doing this online through PowerShell or CMD?

**Comment by backstabbd88** [comment] 2017-02-23 15:15
@timothy try sqc1999 's method. Offline install  lxrun.

**Comment by aslandevops** [comment] 2017-03-11 10:27
Hi. @sqc1999 how i run this "LxRunOffline /install" (point 3 from your how-to)?

**Comment by DDoSolitary** [comment] 2017-03-11 10:30
@aslandevops You can download the binary files from the GitHub Releases page, there is a `LxRunOffline.exe` included. Just open cmd in the same folder as the executable and run the command.

**Comment by aslandevops** [comment] 2017-03-11 10:37
@sqc1999 thx for your fast answer. I'm new on git and maybe do something wrong. I downloaded zip-file from "Clone or download" button, but don't see exe-file in it. What i do wrong?

**Comment by DDoSolitary** [comment] 2017-03-11 10:38
Err... You downloaded the source code.
Direct link to download: https://github.com/DDoSolitary/LxRunOffline/releases/download/v1.0.0/LxRunOffline-v1.0.0.zip

**Comment by aslandevops** [comment] 2017-03-11 10:47
After command `LxRunOffline /install` I have this error
`Error: Failed to launch LxRun.
System.ApplicationException: STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine. (Code: 15)
   at EasyHook.RemoteHooking.CreateAndInject(String InEXEPath, String InCommandLine, Int32 InProcessCreationFlags, InjectionOptions InOptions, String InLibraryPath_x86, String InLibraryPath_x64, Int32& OutProcessId, Object[] InPassThruArgs)
   at LxRunOffline.Program.Main(String[] args)`

**Comment by DDoSolitary** [comment] 2017-03-11 10:50
That's strange. I think it's better to discuss this here: DDoSolitary/LxRunOffline#1

**Comment by aslandevops** [comment] 2017-03-15 03:52
@backstabbd88 hi, what means "host it in your local web server"? how host disk image in server?

**Comment by aslandevops** [comment] 2017-03-15 15:18
A lot of people are complaining about this issue for more than six months. Why Microsoft still has not solved this problem?

**Comment by aseering** [comment] 2017-03-15 15:53
@aslandevops -- which of the many different issues that can cause this symptom are you referring to?

**Comment by aslandevops** [comment] 2017-03-18 10:35
@aseering sorry, my English is bad. I don't now what is a cause of this problem, and I don't see even explanations on possible causes from MS.

**Comment by aseering** [comment] 2017-03-21 03:35
@aslandevops -- a few issues have been noted on this ticket:

* Networks blocking active FTP (which is used to download WSL)
* Windows Firewall is blocking the download (due to blocked ports)
* If you're running Windows in a VM, the VM's network configuration may be causing problems (maybe related to Active FTP?)

Also, other issues have been noted on other tickets:

* Third-party firewalls blocking the download (due to blocked ports or due to bugs handling Linux processes -- many third-party firewalls initially had bugs that caused Linux processes to always be blocked on all ports)
* IPv6 networking issues:  If your computer has IPv6 configured incorrectly, in some cases WSL will try to connect using IPv6, fail, and not fall back to IPv4.  (This is actually a bug in Ubuntu's `apt-get`, which WSL uses during its own installation.  It will cause a different error message that doesn't involve the Windows Store.)
* WSL does not work correctly with VPNs in some cases, especially VPNs that require using special DNS servers.  (Also not your problem because it will cause a slightly different error message.)
* WSL may have trouble installing behind some proxy servers.  (Also not your problem because it will cause a slightly different error message.)
* Some companies block access to the entire Windows Store using company-wide firewall rules.  If Windows can't download bash, it can't install it.

There are probably more issues.  That's just all I can think of right now.

**Comment by DDoSolitary** [comment] 2017-03-24 09:48
@aseering And the network environment in China ><

**Comment by mishrsud** [comment] 2017-06-24 01:49
The Solution suggested by @anderuso worked like a charm for me. Here's the steps:
1. Open windows firewall settings (Windows key, then type firewall)
2. Click on "Allow an app or feature through Windows firewall"
3. Add C:\Windows\System32\lxrun.exe 
4. now from command prompt, lxrun /install

**Comment by damadden** [comment] 2017-07-24 17:09
At first, I wasn't even getting a download percentage and I would get the error:

> Downloading from the Windows Store...
> Unable to download from the Windows Store. Please check your network connection.

I did 2 things that worked:

1. Run the Command Prompt as Administrator
2. Disable Symantec Endpoint Protection (Firewall and Antivirus)

**Comment by sunilmut** [comment] 2017-07-24 20:48
If you are on a recent insider build, 16215+, the recommended way to install is through the Windows Store, where Ubuntu is available right now.

**Closed** 2017-08-03 17:33 UTC
Labels: fixedininsiderbuilds, need-repro
