### ISSUE TITLE
Files created in C:\Users\User\AppData\Local\lxss\ from Windows are ignored by bash

### ISSUE THREAD

**Issue by Akujin** [Microsoft/BashOnWindows#276] opened 2016-04-26 23:06 UTC
First I created a file in C:\Users\User\AppData\Local\lxss\root\.ssh\ called test

The file wasn't visible in bash with ls

I then opened nano and saved to the same location in bash and bash actually overwrote the file on the windows filesystem.

Trying to open the same file in Windows with notepad worked but saving did not because "The file is in use by another process".

I have attached this screenshot to help illustrate the situation.

![Example](http://i.imgur.com/oIOYpza.png)

I originally encountered this issue when I tried to copy my RSA keys within the windows but bash didn't even see them so I had to actually do it from within bash.

**Comment by russalex** [comment] 2016-04-26 23:32
This is actually has the same root cause as #87.  I have a small write-up there explaining.

**Comment by benhillis** [comment] 2016-05-27 00:53
Closing this out as a duplicate.

**Closed by benhillis** 2016-05-27 00:53 UTC
Labels: duplicate
