### ISSUE TITLE
Browser can't serve pages from local http server

### ISSUE THREAD

**Issue by EranShamir** [Microsoft/BashOnWindows#607] opened 2016-06-30 20:41 UTC
I'm running, through my Bash console, an HTTP server (specifically, I'm running Spark standalone cluster master which also run an HTTP server to provide a management portal). When I try accessing the portal (at address http://localhost:8080 or address http://[hostname]:8080) I get a "Page Not Found" message from the browser.

**Comment by benhillis** [comment] 2016-06-30 20:43
Can you verify that port 8080 is open in Windows Firewall on the machine you're running bash from?

**Comment by EranShamir** [comment] 2016-06-30 21:06
I opened the ports through the firewall - still does not work

**Comment by paladox** [comment] 2016-06-30 23:17
windows firewall does not work. I had to disable the internet firewall so I could use bash with the internet.

If you use Norton security it will work.

**Comment by sunilmut** [comment] 2016-11-21 19:38
@EranShamir Lot of changes have gone in the networking stack in WSL since this issue was posted. If you can verify in the latest Insider build whether the issue still persists, we can take this further. Otherwise, we would like to close this issue out.

**Comment by sunilmut** [comment] 2016-12-04 09:59
Closing the issue out. Please re-open if the issue persists and provide detailed repro steps for us to reproduce the issue.

**Closed by sunilmut** 2016-12-04 09:59 UTC
Labels: network
