### ISSUE TITLE
nmap not working

### ISSUE THREAD

**Issue by nlogozzo** [Microsoft/BashOnWindows#2039] opened 2017-05-01 00:18 UTC
- Windows Version Number: 10.0.15063
- Bash Version: Ubuntu 16.04

-After installing nmap, when I try running `sudo nmap -v -sn 192.168.0.0/16` to scan my network for devices I get the error:
`Couldn't open a raw socket. Error: Permission Denied (13)`

-When running `nmap -v -sn 192.168.0.0/16` without using sudo I get the error:
`Problem binding to interface , errno: 92`
 `socket_bindtodevice : protocol not available`

- The output I should be receiving is (example):
`Initiating Ping Scan at 20:14`
`Scanning 4096 hosts [2 ports/host]`
`Completed Ping Scan at 20:14, 33.00s elapsed (4096 total hosts)`
`Initiating Parallel DNS resolution of 4096 hosts. at 20:14`
`Completed Parallel DNS resolution of 4096 hosts. at 20:14, 0.01s elapsed`
`Nmap scan report for amazon-3c5740640.home (192.168.1.13)`
`Host is up (0.095s latency).`

**Comment by stehufntdev** [comment] 2017-05-04 16:38
Thanks for reporting the issue.  WSL currently has limited support for raw sockets.  Please give us feedback on UserVoice so we can prioritize the work - https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo

**Comment by therealkenc** [comment] 2017-05-05 22:21
#1349. User Voice is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar).

**Comment by tjwebb** [comment] 2017-06-29 23:35
+1

**Comment by bmelnik** [comment] 2017-07-11 09:23
+1 same behavior

**Comment by banaabraham** [comment] 2017-07-13 09:45
+1

**Comment by cptBuggy** [comment] 2017-07-14 21:52
+1

**Comment by Sndav** [comment] 2017-07-17 15:02
+1

**Comment by phlogistic** [comment] 2017-07-18 18:08
+1

**Comment by evertondornelas** [comment] 2017-07-19 21:24
+1

**Comment by sunilmut** [comment] 2017-07-25 17:42
Marking this duplicate of #1349

**Comment by chtapodi** [comment] 2017-08-19 17:47
+1

**Comment by raiyuza** [comment] 2017-08-20 22:07
+1

**Comment by mrcha0s** [comment] 2017-08-22 07:48
+1

**Comment by sstodd7532** [comment] 2017-08-25 14:10
+1

**Comment by WizardRyan** [comment] 2017-08-25 16:04
+1

**Comment by Oxicode** [comment] 2017-08-28 21:28
+1

**Comment by RiaanAspelingSage** [comment] 2017-08-30 04:49
+1

**Comment by mathisloge** [comment] 2017-09-02 13:46
+1

**Comment by danhanley** [comment] 2017-09-03 10:31
+1

**Comment by pitmacaloway** [comment] 2017-09-04 12:37
+1

**Comment by ChevalierToday** [comment] 2017-09-06 01:19
+1

**Comment by benhillis** [comment] 2017-09-06 01:52
Understood that this is a highly requested feature but please, enough of the +1 posts that add nothing to the discussion.

**Comment by ChevalierToday** [comment] 2017-09-06 02:07
Sorry mate, I just wanted express interest. If I could help in any way I would.

**Comment by Imamadmad** [comment] 2017-09-07 06:59
+100

**Comment by lacraig2** [comment] 2017-09-08 14:15
+1

**Comment by sunilmut** [comment] 2017-09-08 18:07
For everyone upvoting here, thanks, we understand that this is an important ask. I would also recommend heading down to the [user voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar) and upvoting there as well. We use that to prioritize.

**Comment by dezza** [comment] 2017-09-09 16:23
+1

**Comment by chriswood** [comment] 2017-09-12 00:02
This would be great.

**Comment by petman** [comment] 2017-09-12 11:58
+1

**Comment by WildCard1** [comment] 2017-09-19 14:12
+1

**Comment by christopherpugh** [comment] 2017-09-20 15:41
+1

**Comment by benhillis** [comment] 2017-09-20 15:59
I understand the desire for nmap functionality, but the "+1" comments on are not helpful.  Please use our [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar) to help us prioritize this work.

**Comment by chriswood** [comment] 2017-09-20 17:05
I apologize for a not helpful comment. I think a lot of people who "+1"'d or left a short "great" type comment, like myself, did indeed go to the User Voice site and vote. But since the initial post by nlogozzo was here on github, and the "thumbs up" type feedback option was probably not noticed, they felt like they just wanted to show how appreciative they would be of this feature without going into a wallop of detail on the intricacies of nmap :D

**Comment by ekevjn** [comment] 2017-09-25 08:56
+1

**Comment by ekevjn** [comment] 2017-09-25 09:13
Run as administrator and sudo worked for me

**Comment by nlogozzo** [comment] 2017-09-25 10:19
Tried that and it still didn't work

On Sep 25, 2017, at 5:14 AM, ekevjn <notifications@github.com<mailto:notifications@github.com>> wrote:


Run as administrator and sudo worked for me

**Comment by Skymit** [comment] 2017-10-05 15:03
sudo: Couldn't open a raw socket. Error: Permission denied (13)
WIndows 10 enterprise x64 1703

**Comment by guiedd** [comment] 2017-10-06 13:26
+

**Comment by WagoL** [comment] 2017-10-11 08:12
+1

**Comment by bitcrazed** [comment] 2017-10-12 19:12
Please don't +1 in comments - upvote in uservoice instead. +1's are difficult for us to measure and dilute discussions on issue threads.

Closing since this is a dup of  #1349

**Closed by bitcrazed** 2017-10-12 19:12 UTC
Labels: duplicate

**Comment by MaherJendoubi** [comment] 2017-10-26 16:34
+1

**Comment by OvermindDL1** [comment] 2017-10-26 16:42
> upvote in uservoice instead

The uservoice links just report "Forbidden" and nothing else?

**Comment by bitcrazed** [comment] 2017-10-27 01:38
@OvermindDL1 Please retry [the UserVoice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar) again and let me know if you can't see it.

**Comment by OvermindDL1** [comment] 2017-10-30 15:28
@bitcrazed

Same issue, 403 Forbidden, here is the header set:
```text
Request URL:https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar
Request Method:GET
Status Code:403 
Remote Address:104.16.96.65:443
Referrer Policy:no-referrer-when-downgrade

Response Headers
cache-control:private
cf-ray:3b5f5eac6c102234-LAX
content-encoding:gzip
content-type:text/html; charset=utf-8
date:Mon, 30 Oct 2017 15:22:24 GMT
server:cloudflare-nginx
status:403
vary:Accept-Encoding
vary:Accept-Encoding
x-rack-cache:miss
x-request-id:928c83d7-c885-4420-b8f1-c66e5c45aaee
x-runtime:0.088509

Request Headers
:authority:wpdev.uservoice.com
:method:GET
:path:/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar
:scheme:https
accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
accept-encoding:gzip, deflate, br
accept-language:en-US,en;q=0.9
cache-control:no-cache
cookie:<snip>
pragma:no-cache
referer:https://github.com/Microsoft/WSL/issues/2039
upgrade-insecure-requests:1
user-agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
```

Same thing in an Incognito window as well.

The only thing in the body is "Forbidden", not even a newline otherwise.  I'm in central USA and not seen cloudflare issues with any other site either so I doubt it is a cloudflare issue.

**Comment by abdilahrf** [comment] 2017-11-07 14:22
are this problem is not yet fixed ?

**Comment by bitcrazed** [comment] 2017-11-07 16:34
Are y'all still seeing this issue? Am unable to repro this issue: 

![image](https://user-images.githubusercontent.com/961950/32505224-832cbc3c-c396-11e7-8d98-fb9072eedf71.png)

**Comment by OvermindDL1** [comment] 2017-11-07 16:55
> Are y'all still seeing this issue? Am unable to repro this issue:

Nope, still 'forbidden' here in both normal and incognito mode in both Chrome latest and Firefox Quantum

**Comment by OvermindDL1** [comment] 2017-11-07 16:56
And in both a Windows 10 desktop computer and a Linux desktop computer, it is not computer specific for sure.

**Comment by OvermindDL1** [comment] 2017-11-07 17:10
> Sounds like a geo-block to me. Will report to UserVoice and ask them to explore.

I'm in the almost dead-center of the USA, no VPN or anything of the sort (though that is an idea to try...).

**Comment by OvermindDL1** [comment] 2017-11-07 17:17
Seems so, I SSH'd to a server in california and I was able to get a page when I `curl`'d the URL there and got actual HTML.  The site doesn't use cloudflare or something like that does it (cloudflare has so many issues in so many ways, this would be a new one but it would not surprise me).

**Comment by bitcrazed** [comment] 2017-11-07 17:19
Was just about to ask if you could try again after "changing location" by VPNing into EU or USA. I've reported to UserVoice - will ping this thread when I hear back from them.

Thanks for reporting.

**Comment by bitcrazed** [comment] 2017-11-07 17:47
Hey @OvermindDL1 - response from the folks at UserVoice:

> I asked the team to take a look at our logs for 403 errors, and we were able to identify the IP that was blacklisted and cleared it. Let me know if this resolves the user's issue and if you have any questions.

Could you retry and let me know if you're able to view the page?

**Comment by OvermindDL1** [comment] 2017-11-07 18:07
@bitcrazed Black-listed?  I would doubt it, this is a university (work)...  But nope, still just says 'forbidden' on two separate machines on this network.

Here, see if these headers help (like the cloudflare ray tag):

```
─➤  curl -I https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar
HTTP/1.1 403 Forbidden
Date: Tue, 07 Nov 2017 18:06:31 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: ...snip...
Vary: Accept-Encoding
Vary: Accept-Encoding
X-Rack-Cache: miss
Cache-Control: no-cache
X-Request-Id: 15704929-7395-46b9-96db-65cd8fdf5f66
X-Runtime: 0.057185
Server: cloudflare-nginx
CF-RAY: 3ba23a138a8d7868-LAX
```

**Comment by bitcrazed** [comment] 2017-11-07 18:26
Thanks for re-checking. Will ask UV to take another look.

University networks are often the source of various "creative" forms of traffic that trigger various content blocks ;)

**Comment by OvermindDL1** [comment] 2017-11-07 19:00
> University networks are often the source of various "creative" forms of traffic that trigger various content blocks ;)

Well I'm on the IT side of it, not the student side, so I have no creative filtering between me and the internet, only a NAT (we don't actually have filtering on the student side either, only a simple login captcha that registers their mac address for a short period).  :-)

**Comment by bitcrazed** [comment] 2017-11-07 19:16
Hey @OvermindDL1 - sorry to be a pain, but would you mind pinging UserVoice support:

![image](https://user-images.githubusercontent.com/961950/32512747-ed30b0dc-c3ac-11e7-87e2-19499953ad97.png)

Alternatively, if you can send me your email (richturn at you know where dotcom) I can add you to the thread.

Thanks.

**Comment by OvermindDL1** [comment] 2017-11-07 19:28
@bitcrazed All good, I'm confused as well, not seeing anything odd with the network traffic at all otherwise. Sent you the email as you'll be able to link the thread properly then.  ^.^

**Comment by OvermindDL1** [comment] 2017-11-07 19:30
Ahh, actually hold on, curl just worked this time, as are both browsers on both systems!  I'm guessing the fixing the blacklist part took a bit to replicate to the cache's or so?  Seems to work now though.  :-)

**Comment by bitcrazed** [comment] 2017-11-07 19:46
Lucky you! Can imagine you have your hands full keeping your students online 😉

Services like CloudFlare, Akami, etc. often keep a close eye on traffic from Uni’s, schools, etc. They’re often the source of a lot of torrent traffic, gaming, video download & upload, and requests for various kinds of questionable content. Though, of course, VPN’ed traffic is opaque so it’s v. difficult to sniff out and block.

Rich.

**Comment by LucidObscurity** [comment] 2017-11-20 05:54
So is this fixed? I'm seeing the same as OP on build 15063.726. I do have Hyper-V installed...would that be part of the problem. I'll try turning it off in the boot, but I don't think that gets rid of the virtual ethernet adapter. Would installing Fall Creators Update fix the problem? Thanks.

**Comment by bitcrazed** [comment] 2017-11-20 17:23
Please note - this issue is closed as a dupe of #1349.

**Comment by aegistudio** [comment] 2017-12-23 08:53
+1

**Comment by OvermindDL1** [comment] 2017-12-27 03:59
@bitcrazed Blocked while on the college's network again for note.

**Comment by bitcrazed** [comment] 2018-01-03 19:20
@OvermindDL1 Sorry to hear, but please let UserVoice know - we have no control over their site.

**Comment by OvermindDL1** [comment] 2018-01-03 19:35
> @OvermindDL1 Sorry to hear, but please let UserVoice know - we have no control over their site.

Any chance of using a decent site instead?  One that randomly seems to block campus networks, especially where people work, does not look very good upon it...  Never had such an issue with GitHub for example...

**Comment by bitcrazed** [comment] 2018-01-04 23:27
I hear ya. Please do give UV that feedback too: Ultimately though, they are likely blocking your campus network for a reason. Are you able to tunnel non-student traffic out via a separate static IP address?

FWIW, I have been pushing for Microsoft to offer a great community "forum" for a while. Let's see if I can be annoying enough that someone eventually says "fine, do it"! ;)

**Comment by OvermindDL1** [comment] 2018-01-04 23:58
> Are you able to tunnel non-student traffic out via a separate static IP address?

I can ssh tunnel out but that is via a terminal and a headless server, so I'd need to install X and firefox or something or use a text browser.  ^.^;

**Comment by bitcrazed** [comment] 2018-01-05 01:58
To email … 
![image](https://media.giphy.com/media/fQZX2aoRC1Tqw/giphy.gif)

**Comment by SecInfo007** [comment] 2018-01-26 02:40
Same problem here also... :-/

**Comment by Karasuni** [comment] 2018-02-24 15:57
+1

**Comment by wisetc** [comment] 2018-02-26 03:01
让我认为nmap有一个bug

**Comment by manishkumr** [comment] 2018-02-26 03:32
+1

**Comment by abdilahrf** [comment] 2018-02-26 03:40
+1

**Comment by bitcrazed** [comment] 2018-02-26 23:24
Please don't add +1* replies - they just dilute an issue's signal to noise ratio. Use reactions on the original post to signal your votes: 
![image](https://user-images.githubusercontent.com/961950/36701607-e571a618-1b08-11e8-9b08-165095097a8f.png)

**Comment by chenjiageng** [comment] 2018-03-30 15:34
+1

**Comment by angus-y** [comment] 2018-04-16 16:06
+1

**Comment by marcdubois71450** [comment] 2018-04-28 12:55
+1

**Comment by Retrospective0** [comment] 2018-05-05 03:10
1+

**Comment by ziseliu** [comment] 2018-05-16 10:09
+1

**Comment by c17abab** [comment] 2018-07-26 02:34
+1

**Comment by kartio** [comment] 2018-08-15 07:48
Even though this issue is already closed I would like to hint other that you can use windows installed nmap from you wsl. Solution is presented here: https://medium.com/@the4rchangel/nmap-in-the-windows-bash-shell-64cadff1a689

In short: Install nmap on windows and add `alias nmap='"/mnt/c/Program Files (x86)/Nmap/nmap.exe"'` to you `.bashrc`.

**Comment by artisticcheese** [comment] 2018-08-15 10:50
I think even better way to use nmap on windows is to just launch docker container with nmap. You don't even need to switch to linux containers if you use windows ones. 

```

**Comment by SecInfo007** [comment] 2018-08-15 12:31
Why not just download the nmap binary installer to windows, install it and run it in either Powershell or command prompt? Works fine... It's obvious that Kali and other WSL apps will not work using nmap. Hoping for next updates will fix this issue.

**Comment by danhanley** [comment] 2018-08-22 12:09
Mainly because nmap is a (one of many) precursor for many distributed
systems which won't run on WSL without proper network support. If we just
wanted nmap, as you suggest, then wouldn't bother running WSL :-)

**Comment by HendrikHaase** [comment] 2018-09-06 13:46
+1

**Comment by JAustinal** [comment] 2018-10-01 09:45
+86

**Comment by sgf** [comment] 2018-10-07 17:32
Why ppl like Linux because Linux has fewer restrictions, people can do more what they want to do.
Please don't bring the limit from windows to the WSL.if only can do the windows can do,why we should be use WSL?

Soo,when could be the problem soloved?

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar

that has 1426 votes now ?
 how many votes need ?

**Comment by mailinglists35** [comment] 2018-11-21 14:16
> that has 1426 votes now ?
> how many votes need ?

You don't understand. Our votes do not really count. The uservoice website is just a simulation so you think your opinion matters, but in fact it doesn't.

They [blatantly use the name Linux](https://github.com/Microsoft/WSL/issues/3662) but in fact they don't really want a full blown Linux distro, and instead they just needed a dev environment beucause they realized linux has everything and setting up a dev env on powershell is a painful experience.

**Comment by mitokomon** [comment] 2018-12-27 11:00
more than one year passed without solution :/

**Comment by sptramer** [comment] 2019-01-23 20:02
This super sucks. WSL has a large number of socket issues.

**Comment by findli** [comment] 2019-01-24 18:06
+1

**Comment by 8270647** [comment] 2019-02-01 03:42
+1

**Comment by matthewlewis91** [comment] 2019-02-11 14:34
+1

**Comment by AberSheeran** [comment] 2019-02-13 15:59
So the problem hasn't been solved yet?

**Comment by ThomasSquall** [comment] 2019-02-15 12:26
2 Years and still nothing

**Comment by symant233** [comment] 2019-02-22 04:12
Waiting for the solution...

**Comment by EbrahimMajdey** [comment] 2019-03-05 02:59
+1

**Comment by adotka** [comment] 2019-03-05 15:15
+1

**Comment by mailinglists35** [comment] 2019-03-06 10:53
@moderators, please lock the comments. it's annoying to receive notifications with "+1", when everyone could instead subscribe.

**Comment by x41x41x90** [comment] 2019-05-21 01:58
:-/ +1

**Comment by dinhluong** [comment] 2019-06-20 14:25
Still waiting ...

**Comment by alexverboon** [comment] 2019-06-24 22:14
just tried on the latest windows 10 insider fast ring and wsl 2 and this now seems to work.

**Comment by BlackRider97** [comment] 2019-07-02 15:57
+1

**Comment by dreamtale90** [comment] 2019-07-04 03:09
+1

**Comment by IandI187** [comment] 2019-07-13 00:56
Still no fix?

**Comment by nlogozzo** [comment] 2019-07-13 03:07
I think not

**Comment by rafaelgdp** [comment] 2019-07-29 03:07
Just came here to say that I'm suffering from with this issue right now while troubleshooting my currently limited internet connection.

**Comment by jmvalente** [comment] 2019-08-01 17:55
I'm also experiencing it. Happens even if using the workaround provided by @kartio 

What does seem to work is modifying the alias slightly to  `alias nmap='"cmd.exe /R /mnt/c/Program Files (x86)/Nmap/nmap.exe"'`

**Comment by dzhenway** [comment] 2019-10-03 11:25
+1

**Comment by Ampirical** [comment] 2019-10-31 13:58
+1

**Comment by Hebertl** [comment] 2019-10-31 14:01
+1
