### ISSUE TITLE
 [nodemon] Internal watch failed EPERM

### ISSUE THREAD

**Issue by PunkHaz4rd** [Microsoft/BashOnWindows#798] opened 2016-08-07 11:22 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
I made a gulpfile a while back, it's perfect. I use it for my mean stack projects.
I used it on fedora, ubuntu etc ... Now I've cloned a project to work on, on win10 bash and familiarise myself with this new feature.
When I launch my gulp watch-dev/prod there is an error linked to the watch part.

* Expected results
My application run normally like on every other system (including the commande console).

* Actual results (with terminal output if applicable)
[13:15:19] [nodemon] Internal watch failed: watch /home/romain/myproject/server.js EPERM

* Your Windows build number
14393

* Steps / commands required to reproduce the error
I don't really know, just have a project using Node being watched.

* Strace of the failing command

> inotify_init()                          = 15
ioctl(15, FIOCLEX)                      = 0
ioctl(15, FIONBIO, [1])                 = -1 EPERM (Operation not permitted)
close(15)                               = 0
clock_gettime(CLOCK_MONOTONIC, {1983, 723718000}) = 0
clock_gettime(CLOCK_MONOTONIC, {1983, 723931000}) = 0
gettimeofday({1470568667, 285820}, NULL) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=1073, ...}) = 0
write(9, "[\33[90m13:17:47\33[39m] \33[33m[nodem"..., 113[13:17:47] [nodemon] Internal watch failed: watch /home/romain/technolojesus/server.js EPERM
) = 113

* Required packages and commands to install

> NodeJS, npm, gulp

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment] 2016-08-07 13:00
Hi @PunkHaz4rd , thanks for reporting this!  Could you take a look at #216 ?  This sounds like it might be a duplicate of that ticket, at least the same underlying cause; if you agree that it is, I'd suggest following that ticket as there's a bunch of conversation on it.

**Comment by PunkHaz4rd** [comment] 2016-08-07 13:05
I guess it is a duplicate of #216.

**Closed** 2016-08-07 13:06 UTC
