### ISSUE TITLE
Oracle instant client and sqlplus failed to run

### ISSUE THREAD

**Issue by xychenmsn** [Microsoft/BashOnWindows#1026] opened 2016-08-31 13:21 UTC
I installed oracle instant client and oracle sqlplus but they fail to run. The installation process is from (https://help.ubuntu.com/community/Oracle%20Instant%20Client). I tested this on a real ubuntu 14.04 64bit machine which worked perfect. But when I run on bash for windows, I get: 
`sqlplus: error while loading shared libraries: libclntsh.so.12.1: cannot enable executable stack as shared object requires: Invalid argument`

OS Name	Microsoft Windows 10 Home
Version	10.0.14393 Build 14393

To reproduce the error, you have to following the installation guide and then run: sqlplus

**Comment by stehufntdev** [comment] 2016-08-31 15:59
Thanks for reporting the issue.  This is the same root cause as #286 so closing this out as a duplicate.  Please give us feedback on the [user voice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/filters/top) so we can prioritize.

**Closed by stehufntdev** 2016-08-31 15:59 UTC

**Comment by xychenmsn** [comment] 2016-09-01 12:56
which item on user voice page points to this issue?


________________________________
发件人: stehufntdev <notifications@github.com>
发送时间: 2016年8月31日 11:59
收件人: Microsoft/BashOnWindows
抄送: xychenmsn; Author
主题: Re: [Microsoft/BashOnWindows] Oracle instant client and sqlplus failed to run (#1026)


Thanks for reporting the issue. This is the same root cause as #286<https://github.com/Microsoft/BashOnWindows/issues/286> so closing this out as a duplicate. Please give us feedback on the user voice page<https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/filters/top> so we can prioritize.

―

**Comment by jacobrillema** [comment] 2016-09-03 03:57
I haven't fully tested this all the way through but I was able to get past the exec stack error with this.

sudo apt-get install prelink
sudo execstack -s /usr/lib/oracle/12.1/client64/bin/sqlplus
