### ISSUE TITLE
All subsequent text in terminal is garbled after exiting cat /dev/random

### ISSUE THREAD

**Issue by anohren** [Microsoft/BashOnWindows#1972] opened 2017-04-21 00:47 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.14393]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I tried running `cat /dev/random` and then exited with ctrl+c. After that my prompt was garbled, as well as anything I typed and the output of the commands as well. The command I tried after that did still run though.

My prompt that got horribly disfigured: 
```
⎼┰
⎺┬⎽/S≤⎽├EAS-COMPAQ:/└┰├//W┰
        └32$
```

...and the last few rows of `ls` in system32:

```
┌┌SSHHDR.
├┬≥▒⎼
.┬≥▒⎼
 │

┌┌≥▒⎼
│┬⎼
┌┌ ±.
┌┌.⎻
┌┌├⎻┬32.
≥
 -CN
≥
 -HK
≥
 -TW
≥⎻⎺┰├▒┰
┌┌        ⎼.
┌┌⎻°┌
≥├⎼▒
┌┌   _└▒⎻⎽.
```

* What's wrong / what should be happening instead:

Normal text.

**Comment by benhillis** [comment] 2017-04-21 01:15
This is by design: https://superuser.com/questions/637860/why-does-cat-dev-urandom-break-your-terminal

**Comment by benhillis** [comment] 2017-04-21 20:37
Closing this out - thanks for reporting.

**Closed by benhillis** 2017-04-21 20:37 UTC
Labels: bydesign

**Comment by anohren** [comment] 2017-04-22 11:42
Ah, I should have guessed. Thank you for the link.
