### ISSUE TITLE
timer_create not implemented!

### ISSUE THREAD

**Issue by MadcowD** [Microsoft/BashOnWindows#307] opened 2016-05-01 00:10 UTC
After installing pandoc using apt-get, I get the following error on build 14332:
`pandoc: timer_create: Function not implemented`.

Clearly this function is not implemented on the os-level. See http://man7.org/linux/man-pages/man2/timer_create.2.html 

Thanks,

**Comment by fredzannarbor** [comment] 2016-05-02 19:01
I have this issue too and it is on my critical path.

**Comment by stehufntdev** [comment] 2016-05-02 19:06
Thanks for reporting the issue, I confirmed WSL currently does not have time_create implemented.  Can you please add it to our [UserVoice ](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash%20page) page so we can prioritize?

**Comment by sunilmut** [comment] 2016-05-05 00:26
Just FYI that you can also view the list of implemented syscalls in the ["Release Notes"](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes) under the "Syscall" support section.

**Comment by fredzannarbor** [comment] 2016-05-05 01:05
Got it. As an FYI apparently this syscall is required for all Haskell
binaries.

Open source
https://github.com/fredzannarbor/pagekicker-community/wiki

**Comment by Eduardogbg** [comment] 2016-05-12 16:30
I'm having this problem too and need to run GHC and Cabal on Linux (they need the timer_create() syscall) . Besides installing Linux (VM, dualboot etc) how can I do this? Is there any way of implementing it myself or is it unfeasable?

**Comment by oscarvarto** [comment] 2016-05-25 17:31
I am also hit by this issue :(
Haskell Stack fails with this error:
```
$ stack
stack: timer_create: Function not implemented
```

**Comment by yarikoptic** [comment] 2016-06-13 12:08
Also hit this issue while trying to use git-annex (written in Haskell as well)

**Comment by Spaghet** [comment] 2016-06-24 19:08
Also got this using elm-lang (the compiler is written in haskell)

**Comment by fredzannarbor** [comment] 2016-06-24 19:32
Does anyone know why Haskell needs this timer_create function and other
languages don't necessarily?
ᐧ

Open source:
https://github.com/fredzannarbor/pagekicker-community/wiki
iOS : https://itunes.apple.com/us/app/pagekicker/id1079882706?ls=1&mt=8
Android:
https://play.google.com/store/apps/details?id=com.pagekicker.www&hl=en
Enterprise: https://www.PageKicker.com

**Comment by jdriordan** [comment] 2016-06-27 11:27
It may be that it doesn't necessarily need it. See: https://mail.haskell.org/pipermail/beginners/2009-June/001817.html

It may be that compiling with `-threaded` is a workaround, although I haven't tried it.

**Comment by michallepicki** [comment] 2016-06-27 14:08
1. Users should not be forced to recompile from source every haskell program with special compiler settings.
2. Users should be able to use closed-source haskell programs.

**Comment by benhillis** [comment] 2016-06-27 15:12
@jdriordan thank you for suggesting a workaround.  @michallepicki agreed on both points.  The timer_create system call is on our backlog and we plan to implement it.

**Comment by nh2** [comment] 2016-07-04 17:09
> Does anyone know why Haskell needs this timer_create function and other languages don't necessarily?

@fredzannarbor The GHC Haskell runtime supports _preemtive_ scheduling of cooperative threads ("green threads"). In non-preemtive cooperative threading, threads yield to each other. However, when a thread goes into a syscall, it no longer has the control to yield. The only way to wake up from a syscall (and thus to decide wether another thread should be scheduled, inside the runtime, and thus to get _preemtive_ scheduling), is to send a signal to the process that's blocked in the syscall; then the syscall gets interrupted with `EINTR` and the runtime can do its scheduling decision, and then resume the syscall if needed.

This signal sending is done by setting up a periodic "timer signal" that sends `SIGALRM` to the process every 10 ms (by default). My guess is that that's done using `timer_create`.

You may try running the Haskell program with `+RTS -V0` to disable the timer signal. See https://downloads.haskell.org/~ghc/7.10.3/docs/html/users_guide/runtime-control.html#rts-options-misc
But not sure if that's going to solve it, as there may be other things that need `timer_create`.

**Comment by profix898** [comment] 2016-07-21 08:23
Same problem here. Is there a UserVoice page (as suggested by @stehufntdev) to vote for priority?

**Comment by aseering** [comment] 2016-07-21 15:44
Looks like there's one here:

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13572504-add-support-for-timer-create

In general, you can find UserVoices by going to the main page and searching:

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo

**Comment by i2000s** [comment] 2016-08-03 06:16
I encountered this problem when I tried to use `pandoc` in Bash. I guess since `pandoc` is written in Haskell, it should be a haskell-implementation problem. Any updates?

**Comment by stehufntdev** [comment] 2016-08-03 14:52
Thanks for trying out WSL.  The timer_create system call is on our backlog and we plan to implement it.  We've been prioritizing our work based on the user voice page so please vote there: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13572504-add-support-for-timer-create.

**Comment by Qinka** [comment] 2016-08-05 13:13
so dose ghc

**Comment by EricGT** [comment] 2016-08-11 17:18
Same problem with [Agda](http://wiki.portal.chalmers.se/agda/pmwiki.php).

Details
-

After bash uninstall and reinstall

Using Windows command prompt

````
lxrun /uninstall /full
bash
````

then using WSL

````
sudo apt-get update
sudo apt-get upgrade
sudo rm /etc/hosts
exit
````
and then restarting WSL to build new /etc/hosts.

When installing [Agda](http://wiki.portal.chalmers.se/agda/pmwiki.php) 

`sudo apt-get install agda`

Error:

````
Setting up ghc (7.6.3-10) ...
ghc: timer_create: Function not implemented
````

Build version obtained using command prompt: `Microsoft Windows [Version 10.0.14393]`

**Comment by octetta** [comment] 2016-08-13 12:11
For those of you here because of the `timer_create` error when running `pandoc`, I've worked around this by setting the following alias:

````
alias pandoc='pandoc +RTS -V0 -RTS`
````

(thanks to @nh2 for the clues...)

**Comment by michaelkpate** [comment] 2016-08-13 14:56
Just to add in - just installed Pandoc and googled this when I tried to run it.

**Comment by i2000s** [comment] 2016-08-13 17:24
@octetta I think the trick was to turn off the `timer_create` (maybe not?), but do you know if there is a better way to make it work for the Pandoc markdown in Jekyll? Your trick doesn't work in Jekyll. I have tried using `export GHCRTS=-V0` to turn the timer off, but still got an error
```
jekyll 3.1.6 | Error: pandoc: Error running filter pandoc-citeproc 
pandoc-citeproc not found in path
```
But if I run `echo $PATH`, the pandoc-citeproc installation path is definitely on the list. Everything works in a real Ubuntu system, but not in WSL.

**Comment by octetta** [comment] 2016-08-13 17:43
@i2000s, I've never used `pandoc-citeproc` before, but I just `apt-get`'ed it when I ran it with either the `export` or by putting the options on the command-line, I see this message:
```
pandoc-citeproc: Most RTS options are disabled. Link with -rtsopts to enable them.
```
...this leads me to believe that `pandoc-citeproc` truly requires the pre-emptive thread capability that `timer_create` is being use for in the Haskell run-time.

Without looking at `pandoc` or Haskell run-time code, I suspect you're stuck until the WSL team adds this syscall.

**Comment by i2000s** [comment] 2016-08-13 18:57
@octetta Thank you for the comment. I agree with you, there are some fishy connections between packages and implementing `timer_create` would be the ultimate fix in WSL. Current workarounds as we have pointed out only work for cases where `timer_create` is not really needed.

**Comment by EricGT** [comment] 2016-08-14 21:22
Same problem (ghc-pkg: timer_create: Function not implemented) with [Maude System](http://maude.cs.illinois.edu/w/index.php?title=The_Maude_System)

`sudo apt-get install maude`

Currently there are  three programming languages (GHC, Agda, Maude) that I would like to use with WSL that can be resolved with the one issue.  The plus side about this is that Agda and Maude are using GHC so fixing it for GHC should hopefully resolve the same problem with Agda and Madue without any extra work. :-)

**Comment by nh2** [comment] 2016-08-15 01:51
> this leads me to believe that pandoc-citeproc truly requires the pre-emptive thread capability that timer_create is being use for in the Haskell run-time

@octetta I doubt it, I don't see a reason why `pandoc-citeproc` would require preemtive threading in order to function. More likely it was simply not built with the `-rtsopts` option, so that you can't override them, and if you built `pandoc-citeproc` yourself and used `-rtsopts` during compilation (or petitioned the maintainer to have that happen by default), it would probably work.

> BTW, I think Jekyll (or pandoc?) isn't properly interpreting the return code from when it tries to run pandoc-citeproc giving you a false error about the program not being in the path.

That sounds like a but that should be reported.

**Comment by DSigmund** [comment] 2016-09-06 07:49
Also not working for pandoc...

**Comment by ktor** [comment] 2016-09-06 08:15
As well not working for elm-language

**Comment by sunilmut** [comment] 2016-09-06 17:00
Thanks for the feedback, everyone. As you have already realized, `timer_create` syscall is currently not supported by WSL. If you would like to see better support for scenario\software such as pandoc, please help us prioritize that by voicing your opinion (up vote) in our [user voice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo)

**Comment by SRGOM** [comment] 2016-09-09 16:34
I just want to note that this is currently the 4th highest requested feature on the userdev page after inotify -> symlinks -> continue session on window close (Ignoring ConHost related requests or insane requests  like iptables or administering windows from Linux, of course).

**Comment by jeetparikh** [comment] 2016-09-21 01:13
I would like to this feature coming soon :).

**Comment by i2000s** [comment] 2016-09-21 01:25
@SRGOM The rank you were talking about may not be based on the voting number, rather it could be based on the latest update/comment time stamp. I checked the voting number rank, this feature is way behind. While there are whole bunch of other threads Microsoft people have claimed to work on them, Microsoft people haven't even commented on this small but profound function. 

In case anyone has missed the voting thread, please cast your vote [here](Microsoft people haven't even commented on it,).

**Comment by stehufntdev** [comment] 2016-09-21 18:59
Thanks for the feedback everyone.  Currently we're prioritizing new functionality like this with UserVoice so please make sure to vote.

**Comment by karljs** [comment] 2016-09-22 19:10
@stehufntdev Does that mean that massive feature requests like adding X11 or GPU support with lots of votes outweigh missing core POSIX features regardless of implementation complexity?  I don't mean to come across as entitled as this will probably sound, but this issue is already on the first page of the top UserVoice entries and one of the top three or so requests that don't seem to be big-time integration projects, and yet nobody has tagged or commented on it there yet.

**Comment by i2000s** [comment] 2016-09-22 19:36
@karljs  As I have observed in my earlier post, the ranking you pointed out is Not sorted based on the voting number. This issue only got 252 votes now, while issues which have comments from Microsoft people could only have 166 votes (the only on Add NETLINK Socket support, for example) on the first page. However, when you turn to the second page, there are two issues which got Microsoft's comment of "Working on it" having only 3 and 5 votes--they are about ["iproute2"](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/15592293-iproute2) and ["mouse support for curses applications"](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/15858907-mouse-support-for-curses-applications-not-working). I feel this game really depends on if any Microsoft people would like to work on a particular issue and hence the difficulty of the issue. Since this project is closed source, we can hardly do anything on solving them. The github repo here may be useless for solving problems, and could be a place to waste our time!

**Comment by karljs** [comment] 2016-09-22 19:47
@i2000s I'm inclined to agree with you, but I actually did sort the page by "top", which I can only assume is based on votes and not something else.  This `timer_create` issue is at the very bottom of the first page there.

**Comment by i2000s** [comment] 2016-09-22 19:56
@karljs Makes sense it's on page one, but when I read your comment with `one of the top three or so requests that don't seem to be big-time integration projects`, I thought you are looking at the default sorting page. Sorry about that. Anyway, more people should start using the [Microsoft User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13572504-add-support-for-timer-create) page. That's the take-away message of my conclusion.

**Comment by ztl8702** [comment] 2016-09-30 18:39
Encountered this issue when using `git annex`.

**Comment by radix** [comment] 2016-09-30 18:54
Does anyone know if `LD_PRELOAD` works on WSL? Maybe `timer_create` could be implemented as a preload hack...

**Comment by aseering** [comment] 2016-09-30 20:38
Yes it does!  I have used it to hack around other missing functionality in the past.

**Comment by ztl8702** [comment] 2016-10-01 05:36
@radix What value should I set `LD_PRELOAD` to?

**Comment by Sudha247** [comment] 2016-10-06 16:52
Although it's obvious, I got the same issue while installing ghc.

**Comment by brcolow** [comment] 2016-10-21 05:22
I encountered this issue when trying to run [shellcheck](http://www.shellcheck.net/) although since WSL is 14.04 the version of shellcheck is quite ancient...I will probably try compiling it from source and see if it still needs that syscall.

**Comment by benhillis** [comment] 2016-10-31 19:54
I'm happy to report that I've checked in support for the posix timer family of system calls (timer_create, timer_delete, timer_settime, timer_gettime, timer_getoverrun).  I have tried many of the applications in this thread to verify they are unblocked including: ghc, shellcheck, pandoc, and maude.  This will be coming in an upcoming Windows Insider build.

The implementation is mostly complete with two caveats (due to realtime signal functionality - which is on the backlog):
1. Overrun count (will always return 0).
2. If you create multiple timers that deliver the same signal number, you may miss some expirations. This is because currently we do not queue signals.

In practice it seems most applications do not rely on this functionality, and I'm looking at resolving those two issues.

**Comment by jmchapman** [comment] 2016-10-31 21:56
Great news!

**Comment by EricGT** [comment] 2016-11-02 13:27
@benhillis If you write a book about what you and the others learned and  howyou and the others managed to get these workarounds to work for WSL, I would surely buy it. One of my favorite books was Inside Windows NT and having something similar for WSL would be a win.

**Comment by dsouflis** [comment] 2016-11-02 14:16
Unsurprisingly, installing Purescript has the same 'timer_create' issue during `stack setup && stack install.` Looking forward for the resolution.

**Comment by EricGT** [comment] 2016-11-06 17:27
FYI

After seeing that this has been fixed I decided to see if it worked for [maude](http://maude.cs.illinois.edu/w/index.php?title=The_Maude_System) even though I am not using the [Windows Insider Program](https://insider.windows.com/). I obviously did an [update and upgrade](https://msdn.microsoft.com/en-us/commandline/wsl/faq#how-do-i-update-bash-on-ubuntu-on-windows). To my amazement I was able to get a successful install using <code>sudo apt-get install maude</code> and run the first example from the [manual](http://maude.cs.illinois.edu/w/images/e/e0/Maude-2.7.1-manual.pdf)

As of this writing 11/6/2016 I and using "Microsoft Windows [Version 10.0.14393]" which is from the banner of a command prompt and is not the latest release version of WSL which is at [14595](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14959).

**Comment by PowerSnail** [comment] 2016-11-08 17:22
Has this fix been released yet? I am at Insider Build 14959, and still not getting timer_create. Does it require reinstalling Bash on Windows, or should I simply wait for the next Insider Update? I have always been confused with how Bash on Windows itself updates.

Thank you.

**Comment by benhillis** [comment] 2016-11-08 17:57
@PowerSnail It is not yet publicly available - keep an eye on the release notes.  When timer_create reaches the Insider build you will not need to reinstall Bash on Windows.

**Comment by madskristiansen** [comment] 2016-11-11 10:30
Please release. :)

**Comment by PowerSnail** [comment] 2016-11-11 18:53
It's great to hear that I won't need to re-install WSL. Thank you guys for the awesome work.

**Comment by pletnes** [comment] 2016-11-15 19:14
I need this too, just to add to the choir.

**Comment by shockkolate** [comment] 2016-11-15 21:27
I'm looking forward to this release coming to the non-insider build as I'd really like to do some Haskell development in the Ubuntu environment.

**Comment by lilred** [comment] 2016-11-24 00:53
Has this shipped to insiders yet? I'm wondering when we're going to have a build number.

**Comment by Weznon** [comment] 2016-12-06 14:53
Has a fix for this been released yet?

**Comment by benhillis** [comment] 2016-12-06 14:58
This change will be in the next Wibdows Insider fast build which will be released soon.

**Comment by russalex** [comment] 2016-12-08 01:19
This should be fixed on build 14986 out today.

[14986 Release Notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14986)

**Comment by jmchapman** [comment] 2016-12-10 00:07
very happy to be able to install haskell-platform and then agda!

**Comment by jgrosso** [comment] 2016-12-11 22:05
The Linux subsystem now passes the one test that I care about :wink:

**Comment by i2000s** [comment] 2016-12-12 00:04
I believe I have the latest version of the Windows 10 Insider installed. But still got some errors while building a Jekyll website which builds fine on a real Ubuntu OS. The `time_creater` error didn't show up at my first glance, but I got 
```
Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_post/***.md':
Broken pipe
```
after running the command `bundle exec jekyll build`.
Since it's a markdown problem, I thought it should be related to the Pandoc I was using. So, I type
```
$ pandoc --version
pandoc: timer_create: Function not implemented
```
Clearly, I have pandoc 1.16 installed with `sudo apt install pandoc` earlier. 

For duplicating this error, you can follow the steps illustrated in the `README.md` file under my repo [here](https://github.com/i2000s/i2000s.github.io). I guess the `time_create` is still not fully implemented for the `pandoc` and `jekyll-pandoc` case.

**Comment by benhillis** [comment] 2016-12-12 00:14
@i2000s - I suspect you do not have the newest insider build. What is the output of the "very" command?

**Comment by i2000s** [comment] 2016-12-12 01:04
@benhillis You are absolutely right! Sorry, I was so excited to see an update coming to me. My last update didn't bring in the newest build to me. It was just an accumulated update. I double checked the version number, it's still on `Build 14965.rs_prerelease.161104-1700` which was released on or before Nov 17th. The `Windows Update` button doesn't bring me anything, and the latest build is not on the Window preview build download page either. How can I test the latest build sooner than later? I prefer to finish the task during this weekend. Thanks.

**Comment by lilred** [comment] 2016-12-13 02:45
I switched to the fast ring for this, fingers crossed now...

**Comment by benhillis** [comment] 2016-12-13 02:50
@i2000s - I think it takes about a day between switching Insider rings and being offered an update. I suspect it will be available for you if you check now.

@lilred - I hope this resolves the issues you were seeing. After implementing timer_create I was able to run a number of haskell binaries without issue.  Please let me know.

**Comment by i2000s** [comment] 2016-12-13 03:08
@benhillis I am always on the fast ring, but there is always a delay to me for some reason. I have changed the register table a while ago and then changed it back. There was a parameter I reset to `RS_PRERELEASE` from `RS1_PRERELEASE` which I read from some online instruction in order to receive the updates in time. I am not sure this is related. Anyway, I will wait for the update to come.

**Comment by i2000s** [comment] 2016-12-13 08:15
For those who still haven't received the Fast Ring update on the latest build 14986, I have tried changing the following reg keys and it's working:
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsUpdate]
"SupportsUUP"=dword:00000000

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows
\CurrentVersion\WindowsUpdate\Orchestrator]
"EnableUUPScan"=dword:00000000
```
Can anyone explain why is that? Anyway, I will report back regarding the `time_create` function once I finish everything at hand.

**Comment by Weznon** [comment] 2016-12-13 16:51
Those registry keys control whether the update will be recieved as an esd file or the new UUP format, which was just added in this update. Maybe changing the keys caused the computer to look for an update again?

**Comment by lilred** [comment] 2016-12-14 01:25
Any more info on .esd and UUP?

**Comment by gzh** [comment] 2016-12-17 16:48
@benhillis Got Linux GHC working on Windows Insider Preview build 14986. Thank you guys!

**Comment by i2000s** [comment] 2016-12-30 07:39
As promised earlier, I am reporting back regarding the pandoc issue in compiling a Jekyll site. It works now! Thanks for fixing the `time_create` function. I hope this can be delivered to normal Windows users soon. Happy New Year to everyone here!

PS: the 14986 is really unstable. I got a lot of BSOD--basically on every boot in VirtualBox--and make it hard to run bash until today by chance.

**Comment by benhillis** [comment] 2016-12-30 16:34
@i2000s - Thank you very much for letting me know!  I'm glad I was able to make all you Haskell enthusiasts happy :)

The BSOD you mention is likely a TTY ioctl locking issue that we've fixed internally. If you have a dump please send it to secure@microsoft.com and I'll be happy to confirm.

**Comment by benhillis** [comment] 2017-01-10 16:34
Closing this out since support for timer_create reached Insider builds in 14986.

**Closed by benhillis** 2017-01-10 16:34 UTC
Labels: fixed

**Comment by steveklabnik** [comment] 2017-01-23 18:34
@benhillis just hit this today; when does an "insider build" reach the rest of us?

**Comment by lilred** [comment] 2017-01-23 18:35
@steveklabnik Windows 10 Creators Update, scheduled for April 2017.

**Comment by steveklabnik** [comment] 2017-01-23 18:36
Thank you!
