### ISSUE TITLE
npm fails to install globally, cannot get uid/gid

### ISSUE THREAD

**Issue by kydan** [Microsoft/BashOnWindows#314] opened 2016-05-02 08:00 UTC
Tried to update npm with `sudo npm install npm -g` which fails. See SS for most of the log. 
![capture](https://cloud.githubusercontent.com/assets/2177320/14949749/0030c9a2-107f-11e6-8736-98968d59eccf.JPG)

**Comment by russalex** [comment] 2016-05-02 15:39
Thanks for filing this one.  We're tracking npm issues, including the -g option, in #3.

In this case, the fix is known and inbound on a future release (sorry, can't provide an ETA).

**Comment by phwb** [comment] 2016-05-02 21:01
may be this could help you
https://github.com/npm/npm/issues/9901#issuecomment-146585579

**Comment by etiago** [comment] 2016-05-03 20:01
I'm going to get a bit meta here... not sure if it's the right forum or not, but I'll just go on an offtopic rant.

@russalex I was talking about this issue with NPM the other day at work with a colleague of mine and now that I see your remark on ```"can't provide an ETA"``` I have some food for thought for you guys/girls at Microsoft.

This BashOnWindows project is something new and exciting, and understandably, as the huge undertaking that it is + fiddling that it requires, things aren't perfect. And that's fine. We expect that. We expect it because we're in the insider program, in the fast circle, so we **expect** things to not be perfect. But seeing as things *are* being fixed, I would also like the fixes asap. 

According to this repo's history, it's been close to a month since it's been out. Yet we've only last week gotten another insider preview in the fast circle. Wouldn't it make more sense to have regular releases of BoW via some other mechanism? I don't know... make it a separate installer or something along those lines if the Windows Update pipeline's guidelines really force you to go through hurdles to get a new version of BoW out. But let us test the bleeding edge.

My point? It is that because of this NPM issue, I'm not using BoW. I was excited like bananas when this came out, I literally couldn't sleep of how excited I was. And to be fair, the excitement was justified, you all did great work. But I want the latest news, I want yesterday's commits in my today's build :wink:  otherwise I'm stuck with a half-baked Ubuntu that I can't use for anything useful.

Just some food for thought... this type of project deserves, IMO, more frequent releases. At least weekly, *at least*.

**Comment by aseering** [comment] 2016-05-03 20:41
@etiago -- I definitely agree that the release process for this feature is hampering its testing and adoption.  I have bugs that I would like to report, but I first want to see if they've been fixed in the most-recent Fast Ring build (I suspect they might have been), and that build hasn't made it to my machine.

I created a UserVoice request [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13720371-faster-independent-bash-on-windows-releases) for this.

**Comment by nsvrana** [comment] 2016-05-04 18:33
@etiago They've mentioned it in more than one place that they're currently limited by the rest of the Windows release team because this is kernel level fixes, not something that can be quickly updated. They are internally discussing ways to accelerate the release of BoW but they're a cog in a very big Windows machine. If this wasn't an early beta, I'd agree, but this is supposed to be when we're finding these things for them so that when everyone else starts using it in the summer, they don't have a disappointing experience.

@aseering Why not post them and let them test? I've opened multiple issues that they then replied were good to go on new builds. If you don't post them and they aren't fixed, you've just extended your own wait time :+1:

**Comment by aseering** [comment] 2016-05-04 19:08
@nsvrana -- fair point.  I don't want to distract the MS devs to run some reproducer that I could in theory run; I'd rather that they spend that time building more cool stuff :-)  But I'll post something later today.

**Comment by russalex** [comment] 2016-05-06 17:49
@etiago First off, I want to say that the team and I have been overwhelmed by the amount of support from this community and the patience it has shown us.  We are very grateful and I personally believe that this type of involvement is essential for producing a quality product.  Just wanted to start this with a Thank You.

OK, onto the release schedule issue.  WSL is a very low level component on the Windows stack.  As such, our release schedule is tied to Windows as a whole.  There are larger conversations happening on how to get on a faster cadence, but that is something bigger than this team or initiative.  All I will really comment on is that we (the WSL team) would love to have everyone on our bits as soon as possible.

All that said, we're getting bits to you as quickly as we can so that WSL / Bash on Ubuntu on Windows can help make your lives a little easier.

**Comment by etiago** [comment] 2016-05-07 04:03
@russalex I understand, and it was probably a bit shortsighted of me to think that it could be bundled as a simple installer. In any case, (now) I do understand that you're bound to the release schedule of Windows itself and that your team's hands are pretty much tied... so I hope my post (and similar ones) can at least make the required noise for the powers that be to come up with a way of deploying WSL more frequently. The more people bring this up, the more it should ge noticed :smile: 

But again, let me emphasize: really really great work :+1:

**Comment by benhillis** [comment] 2016-05-27 18:50
I've verified this is fixed in build 14352, please reopen if you continue to see this bug. Thanks!

**Closed by benhillis** 2016-05-27 18:50 UTC
Labels: duplicate, fixed
