### ISSUE TITLE
Parallel Make halts, cannot be killed, in build 15025 for PC

### ISSUE THREAD

**Issue by Warblefly** [Microsoft/BashOnWindows#1661] opened 2017-02-03 18:25 UTC
I regularly build some software using `make -j 8` on my Ubuntu on Windows installation, because that is the number of CPUs on this system. My system always runs insider preview builds, and `bash` works properly. But after installing insider preview build 15025, the very first parallel `make` command fails.

The `make` and `cc1plus` processes halt. And the `bash` process completely vanishes from Process Explorer. None of the remaining processes invoked by `bash` can be killed from Process Explorer or from Task Manager. The bash shell window cannot be closed. Further invocations of bash cannot be started. `CTRL-C `does not work. I am forced to reboot the computer to remove the bash window.

In process explorer, the "Path:" for every halted process is listed as "[A device attached to the system is not functioning.]" Its state is reported as "Wait:WrPushLock". The CPU is not being used by the processes that have halted. 

If you'd like me to trace this problem, I'm very happy to help if given instructions.

**Comment by benhillis** [comment] 2017-02-03 20:59
Sounds like a deadlock. I know we fixed on internally recently (not yet in Insider builds).  Would you be able to take an strace of the build process to see what system call we're getting hung up on?

Is the project you are building open source? I can give it a shot and see if the issue is resolved.

**Comment by Warblefly** [comment] 2017-02-03 21:23
Thank you for offering such detailed help, Ben.

I've attached the last six thousand lines from a `strace -f` (Unix line endings). The whole file runs to 62MB. Unlike previous runs, although the compilation stops, I can kill the strace process from Process Explorer.

The project is my own, a cross-compilation using mingw-w64 gcc, but I've not compiled it from scratch for a couple of weeks so things might be broken; it doesn't recompile what it doesn't need to after upstream git sources change, but it stops during compilation of "taglib" which, if you compile from scratch, is actually a long way into the sequence. 

https://github.com/Warblefly/MultimediaTools-mingw-w64#readme

[strace-extract-6000.txt](https://github.com/Microsoft/BashOnWindows/files/751579/strace-extract-6000.txt)

**Comment by benhillis** [comment] 2017-02-03 21:37
@Warblefly - no problem.  Looking at the last line of the trace the syscall:

`chdir("/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/x86_64/taglib/taglib"`

Since the make process is multi-threaded the "follow forks" strace option would tell us more info (strace -ff -o outputfile). I suspect if you took another trace you'd see the other threads using that directory (or children within).  This is likely fixed the DrvFs deadlock fix @SvenGroot made this week.  ETA to reach Insider builds is probably ~2 weeks.

**Comment by Warblefly** [comment] 2017-02-03 21:54
OK, @benhillis -- Done that strace. Never used the -ff option before! So I've 303 files; attached here as a tarball of 306kbytes. Or is there something I should grep for in those files?

[JW-WIN10Bash-deadlock-strace-2151.tar.gz]

(https://github.com/Microsoft/BashOnWindows/files/751635/JW-WIN10Bash-deadlock-strace-2151.tar.gz)

**Comment by benhillis** [comment] 2017-02-03 22:04
I'm not seeing what I thought I would, I expected to see lots of threads using the same directory but looking at the last lines in the trace that's not what I'm seeing :

**After removing all threads that exited**
```
wait4(-1, rt_sigaction(SIGINT, {0x444900, [], SA_RESTORER, 0x7f1ec98254b0}, {SIG_DFL, [], SA_RESTORER, 0x7f1ec98254b0}, 8) = 0
wait4(-1, rt_sigaction(SIGINT, {0x444900, [], SA_RESTORER, 0x7ff41d8254b0}, {SIG_DFL, [], SA_RESTORER, 0x7ff41d8254b0}, 8) = 0
wait4(-1, rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
access("taglib/CMakeFiles/CMakeDirectoryInformation.cmake", R_OKaccess("CMakeFiles/CMakeDirectoryInformation.cmake", R_OK) = 0
```

Maybe you didn't run the trace for long enough?  Are you sure it was deadlocked? Maybe it was still chugging along (albeit very slowly because of all the file writes).

**Comment by Warblefly** [comment] 2017-02-03 22:08
Right. While trying to clear the directory where taglib was being compiled, using rm -rvf, THAT halted without exiting, too. I'll try to strace that. It might provide a clearer indication of what's going on?

**Comment by Warblefly** [comment] 2017-02-03 22:08
No, can't kill rm. Rebooting...

**Comment by benhillis** [comment] 2017-02-03 22:29
@Warblefly - Spoke with @SvenGroot and he's positive this is the same issue he just fixed.  Thanks again for reporting this issue.

**Comment by Warblefly** [comment] 2017-02-03 22:30
Good of you to check. I'll not worry, and will test the next build.

**Comment by benhillis** [comment] 2017-02-03 22:31
It will probably be in 2 weeks since the fix was made quite recently.

**Comment by Warblefly** [comment] 2017-02-04 11:24
Confirming. Reverting to build 15019 fixes the problem.

**Comment by aseering** [comment] 2017-02-04 13:56
I'm affected by what I assume is the same problem:  When I try compiling code, that window and all processes in it hang, and I can't get a new bash prompt.

Is there a good workaround?  Or is the suggestion "roll back and wait for a release that contains the fix"?  (Which I'm fine with doing, it just means I don't get to test the latest stuff :-) )

**Comment by mainnika** [comment] 2017-02-04 19:57
I have encountered the problem while running «npm install». Like a «make -j8», nodejs runs multiple instances while building dependency tree.

**Comment by saxonww** [comment] 2017-02-07 18:33
Does anyone see this where even after a reboot, stuck processes show up in task manager? I had a situation like this just opening vim today on 15025, and even after power cycling the two stuck processes are still showing up with the same PIDs and I still cannot start another bash session. I am trying to uninstall lxss (lxrun /uninstall /full) now and it's stuck as well. Not sure what to do now other than try to roll back to a previous build.

**Comment by aseering** [comment] 2017-02-09 16:00
For what it's worth, I'm still seeing failures on build 15031, but they're a little different:  I'm sometimes able to ctrl-C out of a program that seems to have hung.  Also, if I get the system into a hung state, then try to open a new Bash Console window, I eventually get:

```
Error: 0x800703e3
Press any key to continue...
```

**Comment by bmayen** [comment] 2017-02-15 11:37
@aseering, are you still seeing this? Should it be tracked as a separate issue?

**Comment by aseering** [comment] 2017-02-15 15:10
@bmayen -- yes I am still seeing this.  My understanding (?) is that everyone (outside of Microsoft) is still seeing this because the fix has not yet been released to the Fast Ring.

**Comment by aseering** [comment] 2017-02-26 18:37
This now works properly for me in build 15042.  I've done a whole bunch of parallel builds and it has consistently worked correctly.  Thanks!

**Comment by sunilmut** [comment] 2017-03-01 22:04
Thanks @aseering for validting. Closing the issue out as per @aseering's comment. Please let us know if the issue persists.

**Closed by sunilmut** 2017-03-01 22:04 UTC
Labels: fixinbound

**Comment by jaykrell** [comment] 2019-10-10 07:30
Did this come back?
