### ISSUE TITLE
32-bit apps (libraries) error

### ISSUE THREAD

**Issue by zpu63** [Microsoft/BashOnWindows#518] opened 2016-06-13 06:35 UTC
I'm trying to run the ARM cross-compiler (arm-none-eabi) which requires to install lib32z1, lib32ncurses5, lib32bz2-1.0 on Ubuntu 14.04 64-bit machines. This works fine on my Intel 64-bit machine with full Ubuntu 14.04 installed. When running Bash on Windows, after installing everything, I get the message:

The program 'arm-none-eabi-gcc' is currently not installed.

This is the expected error when trying to run a 32-bit app under 64-bit Ubuntu without installing the 32-bit libraries. I need some way to install/patch Bash on Windows in order to be able to run 32-bit apps as I've been doing.

**Comment by danbuche** [comment] 2016-06-13 08:30
Having a similar issue - it seems that 32-bit specific binaries will not run on Bash On Windows, only ELF-64 binaries seem to work.

**Comment by benhillis** [comment] 2016-06-13 15:33
Closing as a duplicate of #228.

**Closed by benhillis** 2016-06-13 15:33 UTC
Labels: duplicate, feature
