### ISSUE TITLE
Backspace key produces gibberish 

### ISSUE THREAD

**Issue by Codemaverick** [Microsoft/BashOnWindows#99] opened 2016-04-10 01:52 UTC
So far, this happens only when I'm using ssh-keygen.  I was able to reproduce this consistently.

At the bash console prompt:
- Type ssh-keygen
- Type some input and then attempt to backspace over it

Outputs gibberish instead of removing the characters.

**Comment by skang0601** [comment] 2016-04-11 01:34
I think it's related to the key code that bash.exe picks up. On emacs, backspace is being picked up as 'C-h'.

**Comment by EvNaverniouk** [comment] 2016-04-24 01:19
Can confirm this as well. Another way to reproduce:

- Install git via `apt-get install git`
- Run `git clone {any repository}`
- A `username` prompt will appear.
- Backspacing in that will result in gibberish

**Comment by bitcrazed** [comment] 2016-04-28 20:27
Investigating

**Comment by zadjii-msft** [comment] 2016-10-10 16:15
I'm closing this. There were a number of bugs similar to this due to the early, incomplete TTY layer and mismatched conhost support. That's been mainly fixed since AU.

**Closed by zadjii-msft** 2016-10-10 16:15 UTC
Labels: console
