### ISSUE TITLE
`tput reset` causes session to close

### ISSUE THREAD

**Issue by cgull** [Microsoft/BashOnWindows#400] opened 2016-05-19 17:16 UTC
On build 14342, the commands `tput reset` or `tput init` cause a Bash console to immediately close.  Possibly related to #399.

**Comment by zadjii-msft** [comment] 2016-05-19 20:23
This is definitely a dupe of #399, and goes all the way back to #100. Fix should be coming soon enough, thanks to @paulcam206!

**Comment by xilun** [comment] 2016-05-27 17:38
For information: still crashing on build 14352.

**Comment by benhillis** [comment] 2016-05-28 17:11
Closing out as a duplicate of #399.

**Closed by benhillis** 2016-05-28 17:11 UTC
Labels: console, duplicate, fixinbound
