### ISSUE TITLE
F1-F12 and arrow keys not functional

### ISSUE THREAD

**Issue by mzvast** [Microsoft/BashOnWindows#1496] opened 2016-12-12 17:07 UTC
## Problem Describe
F1-F12 not functional,Just print out "~" .

When I ssh into a remote machine,I can't get shift+arrow keys or alt+arrow keys working either.

On the remote machine I'm using byobu to manage tmux windows and sessions, which binds most functions to F1-F12 as well as shift/Alt/arrow keys.

## Reproduce&Env
1607 fresh install lxss 14.04

## My Thought On This
I think this may have something to do with the cmd new console.
But I toggle back to legacy version of console and launch bash, Boom, the bash just flash and exit.

**Comment by fpqc** [comment] 2016-12-12 17:31
mzvast are you using ConEMU or cmder?

**Comment by mzvast** [comment] 2016-12-12 17:49
@fpqc I'm using the native terminal.
I also try cmder, which not functional either.

**Comment by fpqc** [comment] 2016-12-12 17:58
Does it work from PuTTY?

**Comment by fpqc** [comment] 2016-12-12 18:09
Just so you know, mzvast, you're going down the rabbit-hole of "weird bugs that can be caused by terminfo and locale stuff", even on Linux natively.

**Comment by lilred** [comment] 2016-12-13 02:54
I have the same problem. Build 14965, Ubuntu 16.04, Surface Book keyboard.

**Comment by zadjii-msft** [comment] 2016-12-13 23:52
Ah. byobu. My nemesis.

@mzvast I've been investigating for many months (on and off) why the F keys don't work SPECIFICALLY in byobu.

As of about October, the F1-4 keys got better, and most keys will work occasionally, although modifiers+Fn rarely work. I have no idea as to why in byobu specifically, these keys don't work. I've bound the same commands to the same functions in tmux, and they work just fine. That's the part that gets me. 

I have a current email thread open with @dustinkirkland about this exact issue, hoping to figure out a solution.

**Comment by lilred** [comment] 2016-12-14 01:23
FWIW I'm not using Byobu and I have the same symptoms (though I am using TMUX).

**Comment by fpqc** [comment] 2016-12-14 03:25
@lilred doesn't happen for me on tmux with my config:

[tmuxconf.zip](https://github.com/Microsoft/BashOnWindows/files/650736/tmuxconf.zip)

I use the `xterm-keys` function in my conf.

**Comment by zadjii-msft** [comment] 2016-12-14 17:50
@fpqc See, I think it might be a readline thing too. I also noticed this same kind of incorrect behavior happens trying to use the mouse with byobu on WSL. You'll see much of the escape sequence echo'd to the input, as if it tried to read the first few bytes, then decided it was a noop sequence and echo'd the remainder. 

Again, these scenarios work fine in tmux, so I'm at a loss.

**Comment by lilred** [comment] 2016-12-14 18:13
@fpqc: I installed `tmux-sensible` and that fixed it. Thanks for the help.

**Comment by db2k** [comment] 2017-01-06 00:09
It also doesn't work with "Hyper" from zeit.

https://github.com/zeit/hyper/issues/1127

**Comment by zadjii-msft** [comment] 2017-01-10 23:57
@db2k That's probably more related to #111 than anything else. At this point in time, conhost consumes the input sequences and doesn't pass it up to any other terminal application that might be scraping the console. That thread has more info.

I've found at least internally that the function keys are suddenly working **much** better in byobu. I don't think I did anything that made it work better, maybe @Brian-Perkins can weigh in if the kernel folks changed anything to improve this.

Anywho, expect better behavior in a coming build :)

**Comment by t-anjan** [comment] 2017-02-06 13:35
I am on build 15025. I still have to press my F-keys and other Byobu shortcut keys (e.g. Shift+arrows, Alt+arrows) multiple times, repeatedly, in quick succession, before one of the keypresses gets recognized. It is really irritating, especially because it is unpredictable. Sometimes, the first keypress gets detected. Other times, when I am repeatedly and quickly bashing the keys, two or three successive keypresses get detected, when I wanted just one. 

Is there any solution in sight? Or should we switch to using tmux directly?

**Comment by dustinkirkland** [comment] 2017-02-06 14:43
The Windows terminal isn't catching the F-keys and passing through to tmux
correctly.


:-Dustin

**Comment by benhillis** [comment] 2017-02-06 15:16
@zadjii-msft - Should this be resolved by your recent checkin?

**Comment by zadjii** [comment] 2017-02-06 16:12
@benhillis I do believe you're right.

I can't say for sure, as I stopped noticing problems with byobu about a month or two ago, but I do know that byobu *still* works, so that's a good sign.

Long story short - I made a change to the lxss kernel last friday that should make input sequences that are generated by a single keypress all get injected into the subsystem at the same time, as opposed to character by character. This was in response to a number of issues, #425, #933, #980, and a reported issue with `ghci`. 

Ideally, this should be fixed in an insiders build soon<sup>tm</sup>. If it's not, then I have **NO** idea what's happening any more.

**Comment by zadjii-msft** [comment] 2017-02-06 16:17
@benhillis I do believe you're right.

I can't say for sure, as I stopped noticing problems with byobu about a month or two ago, but I do know that byobu *still* works, so that's a good sign.

Long story short - I made a change to the lxss kernel last friday that should make input sequences that are generated by a single keypress all get injected into the subsystem at the same time, as opposed to character by character. This was in response to a number of issues, #425, #933, #980, and a reported issue with `ghci`. 

Ideally, this should be fixed in an insiders build soon<sup>tm</sup>. If it's not, then I have **NO** idea what's happening any more.

**Comment by dustinkirkland** [comment] 2017-02-06 16:28
Fantastic!  Thanks!


:-Dustin

**Comment by t-anjan** [comment] 2017-03-22 12:04
@zadjii-msft - Do you know if your fix has shipped in any insider's build? I am guessing not, because even on 15063, the issue remains.

**Comment by zadjii-msft** [comment] 2017-05-19 22:10
@t-anjan I believe this should be in the creator's update. I'm certainly not seeing it repro anymore on creator's update.

If you're still seeing this, could you do the following for me?
In emacs, press the following keys:
`Ctrl+h`, `k`, `Ctrl+F12`

You should see the following in the status line:
![image](https://cloud.githubusercontent.com/assets/18356694/26268610/f196f3f0-3ca4-11e7-9d6a-7e47f2050900.png)
`<C-f12> is undefined` is the important part.
(it might be something else if you've mapped C-F12 to something in emacs)

**Closed** 2017-05-20 16:52 UTC
Labels: bug, console, fixedincreatorsupdate

**Comment by avimehenwal** [comment] 2022-10-05 11:59
I encountered the same problem today using byobu on WSL windows 11 terminal.
Suddently all function keys <F-..> stopped working ! after some-time
