### ISSUE TITLE
Directories appear as files bash.

### ISSUE THREAD

**Issue by matthewarkin** [Microsoft/BashOnWindows#2396] opened 2017-08-06 01:10 UTC
* Your Windows build number: 10.0.16257.1

* What you're doing and what's happening:  I somehow got one project directory in a weird state where some directories that Windows views as directories, bash views as files (its missing the directory flag). I did attempt uninstalling and reinstalling bash, as well as doing a chkdsk, the chkdsk seemed to make the issue worse.
I can seem to make the issue resolve it self by manually opening the folder in Explorer.exe but with a massive directory structure (like from composer or node_modules), its a pain to do.

* What's wrong / what should be happening instead: Directories are missing the directory flag and thus the linux file system thinks its a file.
![image](https://user-images.githubusercontent.com/1103529/28999728-a43fe59e-7a07-11e7-8e46-73aeb6b26058.png)

* Strace of the failing command, if applicable: https://gist.github.com/matthewarkin/70d26d01ff7af1845afe9aa0b6b57589

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by matthewarkin** [comment] 2017-08-06 01:54
Copying the directory to a new one did appear to "solve" the issue but the initial directory is still in a corrupt state.

**Comment by DDoSolitary** [comment] 2017-08-06 08:36
Same here. I even got a BSOD when running `cp -r` under such directory.

**Comment by Warblefly** [comment] 2017-08-06 10:12
Likewise here. Cannot complete a git checkout: the 'objects' directory within .git/ appears to `ls` as a file, when it is a directory. An absolute show-stopper I'm afraid.

**Comment by Warblefly** [comment] 2017-08-06 10:52
Reverted to build 16251. Issue does not occur on this build.

**Comment by Habitats** [comment] 2017-08-06 12:20
Definitely a major issue. Happened to me after cloning a git repo. Manually entering the folders in bash resolves it.

**Comment by benhillis** [comment] 2017-08-06 14:29
This has been fixed internally and will be in an insider build soon.  Marking as a duplicate of #2392.

**Closed by benhillis** 2017-08-06 14:29 UTC
