### ISSUE TITLE
After updating to 14361 getting error 0x80070057 when trying to use bash

### ISSUE THREAD

**Issue by ddaymn** [Microsoft/BashOnWindows#496] opened 2016-06-09 15:31 UTC
I have tried uninstalling and reinstalling bash.

**Comment by sunilmut** [comment] 2016-06-09 16:47
@ddaymn - Sorry to hear that. When are you seeing this error? Is it during bash installation or during bash launch?

**Comment by ddaymn** [comment] 2016-06-09 16:48
on bash launch.  The reinstall was successful.  Any logs to help troubleshoot?

**Comment by fheck** [comment] 2016-06-09 16:51
Hi, I've got the same error.
@sunilmut I've had it installed previously, running fine. Now starting it, results in `Error: 0x80070057`.
Re-installation is mostly successful but fails at setting up the user: `Creating UNIX user failed, this can be done later by running lxrun.exe /setdefaultuser`. But after installation, starting fails again with the same error.

**Comment by dethoma** [comment] 2016-06-09 17:19
Are you running this on a single processor VM?

**Comment by fheck** [comment] 2016-06-09 17:24
@dethoma I'm not, Windows is running bare metal on an Ivy Bridge i5 (dual core with HT).

**Comment by dethoma** [comment] 2016-06-09 17:54
The user creation issue is #410 that we are investigating. The invalid parameter error( 0x80070057)sounds different, can you please get us the ETL logs here?

1.Download the below two .txt files and rename them .cmd
2.Run start_lxcore_trace.cmd from an admin command prompt
3.Launch bash.exe
4.Wait until you see the error 0x80070057 error.
5.Run stop_lxcore_trace.cmd from an admin command prompt
6.You should now see three .etl files in the directory you ran the script from.
7.Email the logs to: InsiderSupport@microsoft.com. Include in the subject / message to forward to the WSL team. In the body of the email mention it is for russalex. Also kindly include the build number you're running.

https://github.com/Microsoft/BashOnWindows/files/288621/start_lxcore_trace.txt 
https://github.com/Microsoft/BashOnWindows/files/288622/stop_lxcore_trace.txt

**Comment by ddaymn** [comment] 2016-06-09 18:27
I have sent the requested files.  I also am running on bare metal hardware.  One thing is that I have tried to enable the Windows container support on this machine.  Sadly I did not try the bash support before then.

**Comment by sunilmut** [comment] 2016-06-09 20:22
@ddaymn - We don't have the traces in hand yet, but out of curiosity; is there anything specific about the characters that you are using for the user name, ex: non-English?

**Comment by fheck** [comment] 2016-06-09 20:33
I've also sent mine in earlier. 
But to answer the question, in my username (UNIX and Windows) consists only of normal characters, but my Windows username has a space in it, could that be the problem?

**Comment by ddaymn** [comment] 2016-06-09 20:35
nope just used ascii.  I did dump the etl files.

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	<System>
		<Provider Name="Microsoft.Windows.Subsystem.Lxss" Guid="{d90b9468-67f0-5b3b-42cc-82ac81ffd960}" />
		<EventID>17</EventID>
		<Version>0</Version>
		<Level>2</Level>
		<Task>0</Task>
		<Opcode>0</Opcode>
		<Keywords>0x400000000000</Keywords>
		<TimeCreated SystemTime="2016-06-09T13:22:05.479549600-0500" />
		<Correlation ActivityID="{00000000-0000-0000-0000-000000000000}" />
		<Execution ProcessID="10624" ThreadID="9872" ProcessorID="0" KernelTime="0" UserTime="0" />
		<Channel />
		<Computer />
	</System>
	<EventData>
		<Data Name="File">base\subsys\lxss\lxcmdlineshared\svccomm.cpp</Data>
		<Data Name="FunctionName"></Data>
		<Data Name="Line number">     222</Data>
		<Data Name="Type">       0</Data>
		<Data Name="HRESULT">0x80070057</Data>
		<Data Name="Message"></Data>
		<Data Name="Code"></Data>
	</EventData>
	<RenderingInfo Culture="en-US">
		<Task>LxssException</Task>
	</RenderingInfo>

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	<System>
		<Provider Name="Microsoft.Windows.Lxss.Manager" Guid="{b99cdb5a-039c-5046-e672-1a0de0a40211}" />
		<EventID>325</EventID>
		<Version>0</Version>
		<Level>2</Level>
		<Task>0</Task>
		<Opcode>0</Opcode>
		<Keywords>0x400000000000</Keywords>
		<TimeCreated SystemTime="2016-06-09T13:22:05.478773100-0500" />
		<Correlation ActivityID="{00000000-0000-0000-0000-000000000000}" />
		<Execution ProcessID="12040" ThreadID="12392" ProcessorID="0" KernelTime="15" UserTime="0" />
		<Channel />
		<Computer />
	</System>
	<EventData>
		<Data Name="file">base\subsys\lxss\service\lib\lxssinstance.cpp</Data>
		<Data Name="linenumber">     917</Data>
		<Data Name="type">       0</Data>
		<Data Name="failurecount">4</Data>
		<Data Name="threadid">   12392</Data>
		<Data Name="hr">0x80070057</Data>
		<Data Name="message"></Data>
		<Data Name="code"></Data>
		<Data Name="function"></Data>
	</EventData>
	<RenderingInfo Culture="en-US">
		<Task>Error</Task>
	</RenderingInfo>
</Event>

**Comment by benhillis** [comment] 2016-06-09 20:45
Something strange is going on here... Creating the Linux instance failing with STATUS_INVALID_PARAMETER (0x80070057).  Did you happen to have an Microsoft.Windows.Subsystem.LxCore events when you took the trace or only the ones above?

Can you think of anything out of the ordinary that you might have done?

**Comment by benhillis** [comment] 2016-06-09 20:56
Just got your logs, taking a look at them now.

**Comment by ddaymn** [comment] 2016-06-09 21:06
Nope it was working yesterday before I updated to the 14361 insider build.  The only other thing that I did this morning before using bash was to try out the windows containers using the info at https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10

**Comment by benhillis** [comment] 2016-06-09 21:08
@ddaymn Looking at the trace it looks like what's failing is querying some information about a volume on your machine.  Do you have any non-NTFS mounted volumes by chance?

**Comment by ddaymn** [comment] 2016-06-09 21:16
@benhillis  yes I appear to.

R:/Temp on /tmp type ntfs (binary,noacl,posix=0,usertemp)
C:/Program Files/Git on / type ntfs (binary,noacl,auto)
C:/Program Files/Git/usr/bin on /bin type ntfs (binary,noacl,auto)
C: on /c type ntfs (binary,noacl,posix=0,user,noumount,auto)
D: on /d type ntfs (binary,noacl,posix=0,user,noumount,auto)
R: on /r type ntfs (binary,noacl,posix=0,user,noumount,auto)

The last 3 were created by the native docker beta

**Comment by benhillis** [comment] 2016-06-09 21:20
I believe one of those is causing the issue.  When we are iterating drives for the /mnt/* DriveFs mounts we should skip these.  I've started a thread internally to discuss how we can do this.

Could you point me to the install link for the native docker beta you installed so I can try to repro this myself?

Thanks for all of your help, @ddaymn!

**Comment by ddaymn** [comment] 2016-06-09 21:22
They give you a individual access key to install it does take some time https://beta.docker.com/

**Comment by fheck** [comment] 2016-06-09 21:25
After I read @ddaymn post, I check at my system. (I gathered thas the output of mount in git bash since WSL is not starting?)
I did not install the Docker client, but have virtually the same output:
```
R:/Temp on /tmp type ntfs (binary,noacl,posix=0,usertemp)
C:/Program Files/Git on / type ntfs (binary,noacl,auto)
C:/Program Files/Git/usr/bin on /bin type ntfs (binary,noacl,auto)
C: on /c type ntfs (binary,noacl,posix=0,user,noumount,auto)
D: on /d type ntfs (binary,noacl,posix=0,user,noumount,auto)
R: on /r type ntfs (binary,noacl,posix=0,user,noumount,auto)
```
But what I have installed is a RamDisk on R: using the driver from [ImDisk](http://www.ltr-data.se/opencode.html/)

**Comment by benhillis** [comment] 2016-06-09 21:26
I suspect the RamDisk is what is causing the issues.

**Comment by fheck** [comment] 2016-06-09 21:29
Confirmed. Disabling the Ramdisk allows for WLS to start normally.

**Comment by ddaymn** [comment] 2016-06-09 21:30
Yes that solved it for me also.  I have been using this for the last year.  And it has been working before this build.

**Comment by fheck** [comment] 2016-06-09 22:15
Like @ddaymn I've be running the Ramdsik the whole tiem, and since WSL was released, it never had a problem. 
Interestingly, the aforementioned problem during the installation was also fixed when disabling the Ramdisk. I just dist a reinstall again to check, and now the user setup worked.

**Comment by benhillis** [comment] 2016-06-09 22:18
It looks like this was regressed with the fix for #270.  Another developer on the team is writing a fix for this now, thank you everybody for your help especially @ddaymn who provided the traces!

**Comment by ddaymn** [comment] 2016-06-10 13:08
@benhillis Thank you for finding the solution.  I really like the insider builds and specifically this forum for bugs.  I bet you really appreciate such close feedback from the end users!  Now this is agile.

**Comment by benhillis** [comment] 2016-06-10 15:11
@ddaymn You're absolutely right, we love the close engagement we've had with users on GitHub. There's no way we'd be finding and fixing issues half as fast as we are if it wasn't for this community!

**Comment by jkloth** [comment] 2016-06-20 11:01
Just to update, the issue with an ImDisk ramdisk still exists in build 14367.  Like @fheck, unmounting the disk allows WSL to run normally after the new build is installed.

**Comment by benhillis** [comment] 2016-06-20 15:17
@jkloth Keep an eye out in the release notes as new builds are released, we will call out when the fix is available.

**Comment by fheck** [comment] 2016-06-29 12:22
After updating to build 14376, it seams to be fixed. Bash starts with active RAM disk. 
Thanks to the guys Microsoft!

**Comment by benhillis** [comment] 2016-07-08 15:23
@fheck Great to hear, thank you for confirming.  I'm going to go ahead and close out this issue, if anybody else continues to have issues please let us know.

**Closed by benhillis** 2016-07-08 15:23 UTC
Labels: bug, fixed
