### ISSUE TITLE
javac not working 

### ISSUE THREAD

**Issue by fbergmann** [Microsoft/BashOnWindows#1070] opened 2016-09-09 12:33 UTC
* A brief description
  javac is not working in bash on windows. To reproduce try the following basic java snippet in a file called `test.java`: 

```
class test
{
  public static void main(String[] args)
  {
    System.out.println("Hello World");
    return;
  }
}
```
  Now run `javac test.java`. 

* Expected results
  the program should compile the javac file to a test.class

* Actual results (with terminal output if applicable)
  the console hangs, spinning on one core. and ultimately crashes. with something like 

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error[thread 139882015557376 also had an error] (safepoint.cpp:325)
, pid=29937, tid=139881684076288
#  guarantee(PageArmed == 0) failed: invariant
#
# JRE version: OpenJDK Runtime Environment (7.0_111-b01) (build 1.7.0_111-b01)
# Java VM: OpenJDK 64-Bit Server VM (24.111-b01 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 2.6.7
# Distribution: Ubuntu 14.04 LTS, package 7u111-2.6.7-0ubuntu0.14.04.3
# Core dump written. Default location: /mnt/e/Development/ubuntu/copasi-dependencies/tmp/libCombine/src/bindings/java/core or core.29937
#
```

* Your Windows build number
  10.0.14393

* Required packages and commands to install
  sudo aptitude -y install openjdk-7-jdk

**Comment by aseering** [comment] 2016-09-09 14:41
Thanks @fbergmann for reporting this!  There are a lot of existing issues about Java in this bug tracker, many (not all) of which have been fixed in more-recent Insider builds.  Could you take a look around and see if any issues you're having with Java have been addressed?

**Comment by benhillis** [comment] 2016-09-11 15:53
Marking as duplicate of #746.

**Closed by benhillis** 2016-09-11 15:53 UTC
