### ISSUE TITLE
julia 0.4 tests fail

### ISSUE THREAD

**Issue by davidanthoff** [Microsoft/BashOnWindows#536] opened 2016-06-15 20:26 UTC
This is a pretty simple repo case:

````
git clone https://github.com/JuliaLang/julia.git
cd julia
git checkout release-0.4
make
````

On my machine that ends with a failed test run in PCRE2. This is on build 14366. 

@Mike43110 in issue #446 indicated that julia does compile, but there were not many details, so not sure what was done differently there...

Also looping in @tkelman, the master of all julia builds.

**Comment by tkelman** [comment] 2016-06-15 20:35
It does, you probably just don't have all the build prereqs installed. If you re-run a few times (don't make the poor MSFT people sit through building all of llvm and openblas to reproduce this) you should see the actual error more prominently. Here I suspect you're missing m4. Or maybe cmake, or gfortran.

It doesn't pass all the tests though last I tried, so we could repurpose the issue once you figure out which build pre-req you're missing. Many should already be covered by other "missing syscall" issues though.

**Comment by davidanthoff** [comment] 2016-06-15 21:10
Yes, you are right, it compiles, both 0.4 and master. Running ``make`` on master finishes without any complaint. But for the release-0.4 branch I get those test errors related to PCRE2.

> don't make the poor MSFT people sit through building all of llvm and openblas to reproduce this

Well, I kind of think it would make a lot of sense if the MS people just tried to compile the beast with the repo steps above and figured out what the problem is. julia is a nice test case, it covers a lot of areas. The model of volunteers hunting down the root causes of failures as observed seems a bit unpractical with closed-source software. And with us getting new releases only very couple of weeks, there might just not be enough pre-release cycles left to fix all the problems. Would probably be much easier if the MS devs added this to the scenarios that they are trying to enable.

**Comment by tkelman** [comment] 2016-06-15 21:12
> test errors related to PCRE2

Oh, I may have not tried on the release-0.4 branch, so if it's just PCRE2 failing tests that's a much smaller test case and should be reproducible without involving Julia at all.

**Comment by davidanthoff** [comment] 2016-06-15 21:14
Btw., quite funny that julia starts noticeably faster on bash on windows in a VM than just the windows version on my main system (i.e. the VM host) ;)

**Comment by tkelman** [comment] 2016-06-15 21:19
https://github.com/JuliaLang/julia/pull/15956

**Comment by russalex** [comment] 2016-09-29 22:58
Reading through this and it looks like the julia issues is closed.  I'm going to close this out on our end to keep things a bit cleaner.  Please feel free to re-open with repro steps if we still have an issue.

**Closed by russalex** 2016-09-29 22:58 UTC

**Comment by tkelman** [comment] 2016-09-29 23:07
That issue 15956 was just in response to

> julia starts noticeably faster on bash on windows in a VM than just the windows version

so a change on our win32 build, not our linux build or WSL. Don't bother reopening this, but I suspect

> a failed test run in PCRE2

should be reproducible without involving Julia and is worth re-trying on its own.

**Comment by russalex** [comment] 2016-09-29 23:42
For completeness, I did follow the steps in the original post.  Some of the tests did pass.

```
pcre2-10.20 configuration summary:

    Install prefix .................. : /home/russ/tmp/julia/usr
    C preprocessor .................. : gcc -m64  -E
    C compiler ...................... : gcc -m64
    Linker .......................... : /usr/bin/ld -m elf_x86_64
    C preprocessor flags ............ :
    C compiler flags ................ : -pthread  -O3 -fvisibility=hidden
    Linker flags .................... :  -Wl,-rpath,/home/russ/tmp/julia/usr/lib
    Extra libraries ................. :

    Build 8-bit pcre2 library ....... : yes
    Build 16-bit pcre2 library ...... : no
    Build 32-bit pcre2 library ...... : no
    Include debugging code .......... : no
    Enable JIT compiling support .... : yes
    Enable Unicode support .......... : yes
    Newline char/sequence ........... : lf
    \R matches only ANYCRLF ......... : no
    EBCDIC coding ................... : no
    EBCDIC code for NL .............. : n/a
    Rebuild char tables ............. : no
    Use stack recursion ............. : yes
    Internal link size .............. : 2
    Nested parentheses limit ........ : 250
    Match limit ..................... : 10000000
    Match limit recursion ........... : MATCH_LIMIT
    Build shared libs ............... : yes
    Build static libs ............... : yes
    Use JIT in pcre2grep ............ : yes
    Buffer size for pcre2grep ....... : 20480
    Link pcre2grep with libz ........ : no
    Link pcre2grep with libbz2 ...... : no
    Link pcre2test with libedit ..... : no
    Link pcre2test with libreadline . : no
    Valgrind support ................ : no
    Code coverage ................... : no
```
...
```
PASS: pcre2_jit_test
FAIL: RunTest
PASS: RunGrepTest
============================================================================
Testsuite summary for PCRE2 10.20
============================================================================
# TOTAL: 3
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
============================================================================
make[5]: *** [test-suite.log] Error 1
make[4]: *** [check-TESTS] Error 2
make[3]: *** [check-am] Error 2
make[2]: *** [check] Error 2
make[1]: *** [pcre2-10.20/checked] Error 2
```

**Comment by davidanthoff** [comment] 2016-09-30 01:04
Given that these tests fail, it seems that there is still a problem in WSL, right? I believe this issue should be closed when the instructions at the top of this issue succeed without any error.

**Comment by tkelman** [comment] 2016-09-30 01:08
Run it in gdb or strace and see what differs between WSL and actual Linux. It'll likely be a missing or incorrect syscall implementation, the majority of which should have more targeted issues open by now. Worth identifying which it is though.
