### ISSUE TITLE
wsl is stuck on npm install

### ISSUE THREAD

**Issue by const-g** [Microsoft/BashOnWindows#1701] opened 2017-02-14 08:58 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

When using `npm install`, the command line freeze, but wsl still answers. Per example, Ctrl+C produce a `^C` on screen. `Enter` produce a new line.

* Expected results

The command is ran.

* Actual results (with terminal output if applicable)

![image](https://cloud.githubusercontent.com/assets/1284945/22921812/70b69158-f29b-11e6-98ed-20ba07b163e3.png)

It's not even possible for me to close the window, or to kill it from Task Manager (it doesn't show even in expanded view)

I can start a new wsl terminal, but it stays blank (but I can close this one), while it stays blank, a `Microsoft Bash Launcher` appears in Task Manager.

* Your Windows build number

Build 15031.rs2_release.170204-1546

* Steps / All commands required to reproduce the error from a brand new installation 

- Open terminal
- cd into project with package.json
- run `npm install`

**Comment by const-g** [comment] 2017-02-14 08:58
Note also that the window is responding, I can't close it, but I can minimize it.

**Comment by byronpolley** [comment] 2017-02-14 09:53
my exact same issue. when is next release?

**Comment by tucker973** [comment] 2017-02-14 15:14
It appears this and several other instability issues all come back to this core issue:
https://github.com/Microsoft/BashOnWindows/issues/1675
It's been tagged fix inbound, so hopefully the next release will resolve it. I've found only a full reboot gets WSL clean and running again after one of these crashes.

**Comment by benhillis** [comment] 2017-02-14 16:06
Marking as a duplicate of #1675.

**Closed by benhillis** 2017-02-14 16:06 UTC
