### ISSUE TITLE
npm install -g bower; shasum check failed

### ISSUE THREAD

**Issue by charlescho** [Microsoft/BashOnWindows#364] opened 2016-05-14 03:28 UTC
when installing bower using npm i get the following error:

shasum check failed for /tmp/npm-106-2788f33d/registry.npmjs.org/bower/-/bower-1.7.9.tgz
npm ERR! Expected: b7296c2393e0d75edaa6ca39648132dd255812b0
npm ERR! Actual:   916238d8c11453997137293c39f5555211927abb
npm ERR! From:     https://registry.npmjs.org/bower/-/bower-1.7.9.tgz

**Comment by jefbarn** [comment] 2016-05-14 04:44
All my npm installs are failing because of network connections being dropped randomly.

**Comment by vikas5914** [comment] 2016-05-14 07:59
i had some error when i was installing http-server  . just try again . and it will be installed . 

PS : using build 14342

**Comment by Xterm** [comment] 2016-05-14 09:38
(guessing) duplicate of #313 with #348 having a nice answer: https://github.com/Microsoft/BashOnWindows/issues/348#issuecomment-218837409

**Comment by benhillis** [comment] 2016-05-27 18:54
I've verified this is fixed in build 14352, please reopen if you continue to see this issue. Thanks!

**Closed by benhillis** 2016-05-27 18:54 UTC
Labels: duplicate, fixed
