### ISSUE TITLE
tcgetpgrp() behavior and tmux

### ISSUE THREAD

**Issue by whorfin** [Microsoft/BashOnWindows#1063] opened 2016-09-07 01:39 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!
- A brief description
  pane_current_path, in either the apt-get install version [1.8] or "download and build" [2.2] version of tmux is always NULL.  This is because tcgetpgrp(fd) in osdep-linux.c always returns -1 error.
  Using the code path from the sunos or aix versions instead, which uses ptsname(fd) to find the /dev/pts version of the tty, opens it, and then calls tcgetpgrp on that fd instead, works as expected.
- Expected results
  use tmux, enjoy {pane_current_path} behavior, such as the common
  bind c new-window -c "#{pane_current_path}"
  which opens a new window, in the current directory
- Actual results (with terminal output if applicable)
  use tmux, note that pane_current_path is not usable [always NULL]
- Your Windows build number
  Version 1607 (OS Build 14393.82)
- Steps / commands required to reproduce the error
  see above
- Strace of the failing command
- Required packages and commands to install
  tmux, and/or download latest tmux [2.2] and build from source

This patch to osdep-linux.c will fix it, and should clearly reveal the problem:

```
char *
osdep_get_cwd(int fd)
{
        static char      target[MAXPATHLEN + 1];
        char            *path;
        pid_t            pgrp, sid;
        ssize_t          n;

#define WIN10_PATCH
#ifdef WIN10_PATCH
        {
            const char      *ttypath;
            ssize_t          n;
            int              retval, ttyfd;

            if ((ttypath = ptsname(fd)) == NULL)
                    return (NULL);
            if ((ttyfd = open(ttypath, O_RDONLY|O_NOCTTY)) == -1)
                    return (NULL);

            fd = ttyfd;
        }
#endif
        if ((pgrp = tcgetpgrp(fd)) == 0)
                return (NULL);

        xasprintf(&path, "/proc/%lld/cwd", (long long) pgrp);
        n = readlink(path, target, MAXPATHLEN);
        free(path);

        if (n == -1 && ioctl(fd, TIOCGSID, &sid) != -1) {
                xasprintf(&path, "/proc/%lld/cwd", (long long) sid);
                n = readlink(path, target, MAXPATHLEN);
                free(path);
        }

        if (n > 0) {
                target[n] = '\0';
                return (target);
        }
        return (NULL);
}
```

**Comment by crzidea** [comment] 2016-09-25 08:23
+1 for this. I am tracking the exactly the same issue all the day. Now I am sure it is an issue of WSL.

**Comment by aspyrx** [comment] 2017-01-10 01:10
+1, still broken with tmux (from git, tag 2.3) on Ubuntu 16.04.1 LTS on Windows Version 1607 (OS Build 14986.1001).

The following patch works for me:
```diff
diff --git a/osdep-linux.c b/osdep-linux.c
index 42712de..6b31931 100644
--- a/osdep-linux.c
+++ b/osdep-linux.c
@@ -20,6 +20,12 @@
 #include <sys/stat.h>
 #include <sys/param.h>

+// https://github.com/Microsoft/BashOnWindows/issues/1063
+#define WIN10_PATCH
+#ifdef WIN10_PATCH
+#include <fcntl.h>
+#endif
+
 #include <event.h>
 #include <stdio.h>
 #include <stdlib.h>
@@ -69,9 +75,29 @@ osdep_get_cwd(int fd)
        pid_t            pgrp, sid;
        ssize_t          n;

+// https://github.com/Microsoft/BashOnWindows/issues/1063
+#ifdef WIN10_PATCH
+       char            ttypath[MAXPATHLEN + 1];
+       int                     ttyfd;
+
+       if (ptsname_r(fd, ttypath, sizeof(ttypath))) {
+               return (NULL);
+       }
+
+       if ((ttyfd = open(ttypath, O_RDONLY|O_NOCTTY)) == -1) {
+               return (NULL);
+       }
+
+       fd = ttyfd;
+#endif
+
        if ((pgrp = tcgetpgrp(fd)) == -1)
                return (NULL);

+#ifdef WIN10_PATCH
+       close(ttyfd);
+#endif
+
        xasprintf(&path, "/proc/%lld/cwd", (long long) pgrp);
        n = readlink(path, target, MAXPATHLEN);
        free(path);
```

**Comment by sunilmut** [comment] 2017-01-10 01:53
Can someone collect a strace of the failing command on WSL and share it out? There does not seem to be a syscall called 'tcgetpgrp`.
`strace -o <strace_file> -ff <failing_cmd>`

**Comment by sunilmut** [comment] 2017-01-10 01:54
Can someone collect a strace of the failing command on WSL and share it out? There does not seem to be a syscall called 'tcgetpgrp`

`strace -o <strace_file> -ff <failing_cmd>`

**Comment by nessss** [comment] 2017-03-29 17:38
Thanks @aspyrx, that patch fixed `#{pane_current_path}` for me as well. In addition, modifying `osdep_get_name` in the same way fixed another issue I was having, namely `#{pane_current_command}` always returning null.

Here's the updated patch:

```diff
diff --git a/osdep-linux.c b/osdep-linux.c
index 42712de..943490a 100644
--- a/osdep-linux.c
+++ b/osdep-linux.c
@@ -20,6 +20,12 @@
 #include <sys/stat.h>
 #include <sys/param.h>

+// https://github.com/Microsoft/BashOnWindows/issues/1063
+#define WIN10_PATCH
+#ifdef WIN10_PATCH
+#include <fcntl.h>
+#endif
+
 #include <event.h>
 #include <stdio.h>
 #include <stdlib.h>
@@ -36,9 +42,29 @@ osdep_get_name(int fd, __unused char *tty)
        int      ch;
        pid_t    pgrp;

+// https://github.com/Microsoft/BashOnWindows/issues/1063
+#ifdef WIN10_PATCH
+    char            ttypath[MAXPATHLEN + 1];
+    int                     ttyfd;
+
+    if (ptsname_r(fd, ttypath, sizeof(ttypath))) {
+        return (NULL);
+    }
+
+    if ((ttyfd = open(ttypath, O_RDONLY|O_NOCTTY)) == -1) {
+        return (NULL);
+    }
+
+    fd = ttyfd;
+#endif
+
        if ((pgrp = tcgetpgrp(fd)) == -1)
                return (NULL);

+#ifdef WIN10_PATCH
+    close(ttyfd);
+#endif
+
        xasprintf(&path, "/proc/%lld/cmdline", (long long) pgrp);
        if ((f = fopen(path, "r")) == NULL) {
                free(path);
@@ -69,9 +95,29 @@ osdep_get_cwd(int fd)
        pid_t            pgrp, sid;
        ssize_t          n;

+// https://github.com/Microsoft/BashOnWindows/issues/1063
+#ifdef WIN10_PATCH
+    char            ttypath[MAXPATHLEN + 1];
+    int                     ttyfd;
+
+    if (ptsname_r(fd, ttypath, sizeof(ttypath))) {
+        return (NULL);
+    }
+
+    if ((ttyfd = open(ttypath, O_RDONLY|O_NOCTTY)) == -1) {
+        return (NULL);
+    }
+
+    fd = ttyfd;
+#endif
+
        if ((pgrp = tcgetpgrp(fd)) == -1)
                return (NULL);

+#ifdef WIN10_PATCH
+       close(ttyfd);
+#endif
+
        xasprintf(&path, "/proc/%lld/cwd", (long long) pgrp);
        n = readlink(path, target, MAXPATHLEN);
        free(path);
```

**Comment by mmarchini** [comment] 2017-05-19 23:17
@sunilmut here is the [full stace file](https://gist.github.com/mmarchini/5a58d2f3365229f9867a8352ee563a2f)

The failing call to tcgetpgrp happens on line 41252:

```
[pid  3667] ioctl(16, TIOCGPGRP, 0x7fffc5c1409c) = -1 EINVAL (Invalid argument)
```

According to [this](https://linux.die.net/man/4/tty_ioctl), that call is equivalent to: `*argp tcgetpgrp(16)`, where argp points to `0x7fffc5c1409c`.

And as this call returned -1, it fails again on line 41282 and then fall back to chdir("/") on line 41283:

```
[pid  3844] fchdir(-1)                  = -1 EBADF (Bad file descriptor)
[pid  3844] chdir("/")                  = 0
```

If you need more information I'm glad to help.

**Comment by gpakosz** [comment] 2017-06-18 14:24
Reproduced with tmux `HEAD`

**Comment by sunilmut** [comment] 2017-06-22 00:27
@mmarchini - Thanks for the trace and the analysis, and sorry for the delayed response. I have marked it as a bug, which should automatically put it in our backlog of bugs.

**Comment by gpakosz** [comment] 2017-06-22 07:17
Yep too bad it went untagged for so long, could have been in creators update since a lot of focus was given to tmux etc

**Comment by benhillis** [comment] 2017-08-03 16:48
I believe this should be fixed in 16257.

**Comment by Victor-Savu** [comment] 2017-08-04 07:20
@benhillis could you provide a link to the PR you are referring to please? I'd really love to see this fix :)

**Comment by benhillis** [comment] 2017-08-04 14:20
Unfortunately it's on our internal Microsoft VSTS so I can't share it

**Comment by Victor-Savu** [comment] 2017-08-05 10:19
Oh, I see. Thanks anyway! I suppose the PR number from you comment will not match the PR number from GitHub so it will be a bit confusing for future readers.

**Comment by benhillis** [comment] 2017-08-05 14:54
That number is a Windows build number not PR number.

**Comment by gpakosz** [comment] 2017-08-07 16:16
@benhillis Just tried `16257.rs3_release.170728-1700` and I confirm `tmux display -p #{pane_current_path}` works now.

**Comment by benhillis** [comment] 2017-08-07 16:25
Awesome, thanks for confirming.

**Closed by benhillis** 2017-08-07 16:25 UTC
Labels: bug, fixedininsiderbuilds

**Comment by williscool** [comment] 2017-11-06 05:56
How / when do I get the version of windows this is fixed in?

**Comment by Brian-Perkins** [comment] 2017-11-06 17:04
This fix is available in the Fall Creators Update: https://binged.it/2zBdP2f

**Comment by crokobit** [comment] 2019-07-15 03:23
Hi all,
I am using win 10 pro 10.0.0.17763 Build 17763, but I still got this bug with Tumx. Any idea?
