### ISSUE TITLE
bash.exe executed in a powershell executed in a cmd executed in a wsl ssh session hangs

### ISSUE THREAD

**Issue by heldchen** [Microsoft/BashOnWindows#2426] opened 2017-08-15 20:19 UTC
```
me@devbox:/$ uname -a
Linux devbox 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
me@devbox:/$ /mnt/c/WINDOWS/System32/cmd.exe
Microsoft Windows [Version 10.0.16251.0]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\>ver
ver

Microsoft Windows [Version 10.0.16251.0]

C:\>powershell
powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\> bash
bash
^C
me@devbox:/$
```
killing it also kills the powershell and cmd process. 

not a serious complaint, honestly, just amazed that you can even use powershell and cmd *within* a ssh wsl session as if they were just any other linux shell! :-)

**Comment by benhillis** [comment] 2017-08-15 23:30
@heldchen - I like to call this feature request Inception.

**Comment by heldchen** [comment] 2017-08-16 10:02
![image](https://user-images.githubusercontent.com/299636/29357902-8667203a-8279-11e7-9de4-86e83cb3b221.png)

and with that I promise to not further ruin the github issue tracker with nonsense. really appreciate the work you guys did and to with WSL, made the devs in our company very happy.

**Comment by benhillis** [comment] 2017-08-16 16:46
Marking as a duplicate of #1228.

**Closed by benhillis** 2017-08-16 16:46 UTC
Labels: duplicate, interop
