### ISSUE TITLE
Feature Request: Support Custom Installation Path

### ISSUE THREAD

**Issue by tthsn** [Microsoft/BashOnWindows#1874] opened 2017-04-10 09:12 UTC
I have a 20 GBytes C: drive, and 200 GBytes E: drive, so I prefer to install "Ubuntu on Windows" to E:
Don't know how to install it to the drive other than C:

**Comment by benhillis** [comment] 2017-04-10 15:19
Marking as a duplicate of #449.

**Closed by benhillis** 2017-04-10 15:19 UTC
