### ISSUE TITLE
ssh tunnels returns bind adress already in use

### ISSUE THREAD

**Issue by geoffreysamper** [Microsoft/BashOnWindows#1165] opened 2016-10-05 11:36 UTC
When I try to make a ssh tunnel via the bash shell it always return **bind:address alreay in use**

```
ssh -f -L 6500:localhost:8080 -N housekeeper@xxxxmgmt.westeurope.cloudapp.azure.com -p 2200
```
- **Expected results**: Creates a ssh tunnel  
- **Actual results (with terminal output if applicable)**: bind:adress is already in use
- **Your Windows build number** Window10 enterprise, version1607, os build 14393.222

**Comment by stehufntdev** [comment] 2016-10-05 16:07
Thanks for reporting the issue.  Have you checked that the port is not already being used by another application by running netstat from Windows?

**Comment by sunilmut** [comment] 2016-10-05 18:43
This looks related to the IPV6_V6ONLY issue (see #157). The issue is fixed in the Windows Insider build 14936. 14393 is the Anniversary update build, which does not get the Insider updates until the next release. If joining the Insider program works for you, that's the best place to get updates for this feature, at the moment.

**Comment by xBytez** [comment] 2016-10-05 19:07
I do not recommend upgrading to 14936 right now, currently you will get a Blue Screen of Death (see #1138) when attempting this. I would say your best option is to wait for the next build and upgrade to that.

**Comment by geoffreysamper** [comment] 2016-10-06 07:03
I there a workarround the -4 command line parameter doesn't work for me. 
Then I get follow error message 

> bind: Address already in use
> channel_setup_fwd_listener: cannot listen to port: 6500
> Could not request local forwarding.

**Comment by sunilmut** [comment] 2016-10-06 17:02
@geoffreysamper Can you share a strace of the failing command? "strace -o \<trace_output> -ff \<failing command>". Also, if you do "netstat -a" from a Windows cmd prompt, you can see what ports are being used and if there is a collision.

**Comment by geoffreysamper** [comment] 2016-10-07 07:04
command that I executed 


```
strace -o stracessh.txt -ff ssh -f -L 3333:localhost:8080 -N housekeeper@xxxmgmt.westeurope.cloudapp.azure.com -p 2200
```


[stracessh.19.txt](https://github.com/Microsoft/BashOnWindows/files/515486/stracessh.19.txt)
[stracessh.20.txt](https://github.com/Microsoft/BashOnWindows/files/515488/stracessh.20.txt)
[ssh_netstat.txt](https://github.com/Microsoft/BashOnWindows/files/515489/ssh_netstat.txt)

**Comment by sunilmut** [comment] 2016-10-07 22:13
@geoffreysamper - Thanks for collecting and sharing the traces. You can see the problem in the strace (snippet below), that both IPV4 and IPV6 socket are trying to bind to the same port `3333` using the `IPV6_V6ONLY` socket option. This (IPV6_V6ONLY) issue and the bugcheck issue mentioned by @xBytez are both fixed in the Insider build 14942 (see [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes)), which just got released. If you can't subscribe to the Insider program, then the other option is to see if you can `ssh` to use different ports for IPV4 and IPV6.

`socket(PF_INET6, SOCK_STREAM, IPPROTO_TCP) = 4`
`setsockopt(4, SOL_IPV6, IPV6_V6ONLY, [1], 4) = 0`
`bind(4, {sa_family=AF_INET6, sin6_port=htons(3333), inet_pton(AF_INET6, "::1", &sin6_addr), `
`...`
`...`
`socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 5`
`bind(5, {sa_family=AF_INET, sin_port=htons(3333), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EADDRINUSE (Address already in use)`

**Comment by geoffreysamper** [comment] 2016-10-10 06:51
I will upgrade to the insider build :). THx for your help

**Comment by sunilmut** [comment] 2016-10-10 18:05
@geoffreysamper Thanks for trying out WSL! And, please do remember to close out the issue if it is resolved for you in the new build.

**Comment by sunilmut** [comment] 2016-11-11 16:53
Closing out the issue since it should be resolved for sometime now.

**Closed by sunilmut** 2016-11-11 16:53 UTC

**Comment by pksorensen** [comment] 2017-02-11 01:48
I also tried to connect to a ACS like the OP, and failing with samme error. Havent found a solution yet

**Comment by sunilmut** [comment] 2017-03-01 19:49
@pksorensen - Thanks for your post! Can you please open a new issue using the template [here](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md)? It will help serve the issue better.
