### ISSUE TITLE
Zsh script with pipes hang

### ISSUE THREAD

**Issue by wbkang** [Microsoft/BashOnWindows#1973] opened 2017-04-21 00:55 UTC
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number: Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  
Here's a sample script that causes an issue
```
#!/bin/zsh

find /mnt/c/Windows/ -type f -readable -print0 | while IFS= read -r -d "" file ; do
    while :; do
        stat "$file"
        checksum=$(cat "$file" | sha256sum -b - | awk '{print $1}')
    done
done
```
* What's wrong / what should be happening instead:
What's wrong: The script stops running in the middle. set -x to see where it gets stuck. CPU and disk are idle.
What should happen: The script should complete running and exit eventually.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)
If I run it with strace, it doesn't get stuck. Isn't that just evil?

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment] 2017-04-21 15:03
I wonder if this has to do with the way drvfs permissions work in the Windows directory.

**Comment by wbkang** [comment] 2017-04-21 15:17
It's random though. If you just read the single file that it gets stuck on, it works fine.

**Comment by benhillis** [comment] 2017-04-21 15:32
@wbkang - I'm not seeing the above script get stuck "stuck" as in hung, but I am seeing it constantly doing a stat on the same file (which happens to be the first file alphabetically in the Windows directory):

```
  File: '/mnt/c/Windows/addins/FXSEXT.ecf'
  Size: 802             Blocks: 4097       IO Block: 512    regular file
Device: 8h/8d   Inode: 5348024558192408  Links: 3
Access: (0555/-r-xr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-04-16 02:06:47.841589900 -0700
Modify: 2017-04-16 02:06:47.841589900 -0700
Change: 2017-04-17 19:11:47.435856800 -0700
 Birth: -
  File: '/mnt/c/Windows/addins/FXSEXT.ecf'
  Size: 802             Blocks: 4097       IO Block: 512    regular file
Device: 8h/8d   Inode: 5348024558192408  Links: 3
Access: (0555/-r-xr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-04-16 02:06:47.841589900 -0700
Modify: 2017-04-16 02:06:47.841589900 -0700
Change: 2017-04-17 19:11:47.435856800 -0700
 Birth: -
```

**Comment by wbkang** [comment] 2017-04-21 22:48
No, it just gets stuck. I actually recorded the session using the game bar https://www.youtube.com/watch?v=r_wUp96MeCc&feature=youtu.be

Sorry that snippet was just there to demonstrate the issue. You don't need the inner loop.

I can even make it happen by 
```
find /mnt/c/Windows/ -type f -readable -print0 | while IFS= read -r -d "" file ; do
        stat "$file"
        checksum=$(cat "$file" | sha256sum -b - | awk '{print $1}')
done
```
What's interesting is that, it does not get stuck if I reduce the number of pipes.

**Comment by benhillis** [comment] 2017-04-21 23:29
@wbkang  - Thanks for the additional information, I was able to reproduce this locally and will spend some time debugging what is going wrong.

**Comment by benhillis** [comment] 2017-04-25 23:56
I have checked in a fix for this issue, it should reach Windows Insider fast in a few weeks.

**Comment by wbkang** [comment] 2017-04-26 00:07
That was fast; thanks a lot. Do you mind sharing the description of the cause?

**Comment by benhillis** [comment] 2017-04-26 00:18
@wbkang - Thanks! We like to fix things quickly around here, our driver was built from the ground up for issues to be easy to identify and diagnose.

I'd be happy to share a little detail. I first thought this could be related to pipes since your scripts are piping a bunch of commands together, however when running your repro I hit an assertion in our code that was making sure that we aren't delivering signals to threadgroups that have already terminated.  Turns out there was a race condition where a kill system call could come in and end up delivering a SIGCONT signal to a threadgroup that has already terminated.  This would cause any caller waiting on the threadgroup to terminate to hang.

**Comment by rygwdn** [comment] 2017-04-28 13:42
@benhillis can you recommend any workarounds for those of us who can't switch to the Insider builds?

**Comment by benhillis** [comment] 2017-04-28 15:49
@rygwdn - Good question. Unfortunately I can't thinking of a workaround. Are you also running into a similar issue?

**Comment by rygwdn** [comment] 2017-04-28 16:36
yes, I had a zsh plugin which was executing a fairly long pipeline for every prompt (rather inefficient, I know):
```zsh
    git_aliases=$(git config --get-regexp "^alias\." | \
      sed 's/[ ]/ = /' | \
      sed 's/^alias\./git /' | \
      sed 's/ = \([^!]\)/ = git \1/' | \
      sed 's/ = !/ = /')
```
which would lead to my shell hanging after running a few commands. I ended up just removing the plugin under WSL. I have a friend who's having similar issues at startup when using [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh).

**Comment by benhillis** [comment] 2017-04-28 16:44
Thank you. If this is blocking some very common scenarios it may be a good candidate for servicing.  If you can provide as much detail as possible about different scenarios this is causing issue I can use that as an argument why my fix should be backported via Windows Update.

**Comment by wbkang** [comment] 2017-04-29 02:51
@rygwdn You can certainly make it shorter. See if this helps: 
```
git config --get-regexp "^alias\." |       sed 's/[ ]/ = /; s/^alias\./git /; s/ = \([^!]\)/ = git \1/; s/ = !/ = /'
```

You can chain sed commands either by `;` or newlines.

**Comment by mdentremont** [comment] 2017-05-05 13:40
@benhillis

I took a look into creating a new user, and seeing how minimal I could make my environment and still reproduce the startup hang (100% of the time).

This is the very minimal zplug setup:
```
cat > ~/.zshrc <<EOL
source /tmp/zplug/init.zsh
zplug "plugins/git",   from:oh-my-zsh
zplug "plugins/vi-mode",   from:oh-my-zsh

if ! zplug check --verbose; then
    zplug install
fi

zplug load --verbose
EOL

export ZPLUG_HOME=/tmp/zplug
git clone https://github.com/zplug/zplug $ZPLUG_HOME
zsh
```

**Comment by benhillis** [comment] 2017-06-03 17:30
This issue is fixed in 16193.

**Closed by benhillis** 2017-06-03 17:30 UTC
Labels: bug, fixedininsiderbuilds
