### ISSUE TITLE
The default x87 control word setting seems to be different on Linux and WSL

### ISSUE THREAD

**Issue by njsmith** [Microsoft/BashOnWindows#1748] opened 2017-03-04 00:51 UTC
Here's a Linux program to print the x87 FPU control word:
```c
#include <stdio.h>
#include <fpu_control.h>

int main(int argc, char** argv) {
    fpu_control_t cw;
    _FPU_GETCW(cw);
    printf("0x%x\n", cw);
}
```

On WSL it prints `0x27f`. On real Linux it prints `0x37f`. The difference is in the precision control field (bits 8-9): on Windows it's set to 0x2 = 64-bit double precision mode, and on Linux it's set to 0x3 = 80 bit extended precision mode.

This is not a very surprising bug; these are the standard settings for the control word in the Windows and Linux ABIs, respectively. But WSL should match the Linux ABI, not the Windows ABI :-). The effect is that Linux programs that use `long double` will produce incorrect results under WSL (and it'll cause small rounding differences in floating point code in general).

Originally discovered due to incorrect results when using numpy's `longdouble` type under WSL:
https://github.com/numpy/numpy/issues/8726

**Comment by aseering** [comment] 2017-03-04 01:36
I can confirm this bug on the latest Insider build (15046).  (@njsmith -- you didn't mention what build you're using?)

**Comment by njsmith** [comment] 2017-03-04 02:30
>  (@njsmith -- you didn't mention what build you're using?)

I don't have WSL installed at all... @eric-wieser?

**Comment by eric-wieser** [comment] 2017-03-04 02:32
I'm on the release build (14393)

**Comment by therealkenc** [comment] 2017-03-04 02:54
Probably same as #830 from back in August. Don't know whatever became of of that one.

**Comment by benhillis** [comment] 2017-03-07 16:23
Thanks for posting, agreed with @therealkenc that this is a duplicate of #830.  We have a task filed on our backlog to get this addressed.

**Closed by benhillis** 2017-03-07 16:23 UTC
