### ISSUE TITLE
"ps aux" works, but "ps faux" does not

### ISSUE THREAD

**Issue by tycho** [Microsoft/BashOnWindows#374] opened 2016-05-15 19:42 UTC
Something in procfs must not be fully implemented:
```
geryon ~
# ps faux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
geryon ~
# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0      0     0 ?        Ss    2431   0:00 /init
root         2  0.0  0.0      0     0 ?        Ss    2431   0:00 /bin/bash
root      3362  0.0  0.0      0     0 ?        R     2431   0:00 ps aux
```

**Comment by xilun** [comment] 2016-05-15 20:38
This is a duplicate of #246

**Comment by benhillis** [comment] 2016-05-15 20:56
Tracking this with #246, closing this out as a duplicate.

**Closed by benhillis** 2016-05-15 20:56 UTC
Labels: fixinbound
