### ISSUE TITLE
Directories on Windows sometimes don't resolve correctly

### ISSUE THREAD

**Issue by klauern** [Microsoft/BashOnWindows#2416] opened 2017-08-13 11:27 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

`Microsoft Windows [Version 10.0.16257.1]`

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Sometimes when navigating to the windows directory-side of the house, sub-directories don't resolve as anything at all.

```sh
06:20 $ ls -als
total 69
 0 drwxrwxrwx 0 root root   512 Aug  4 18:25 ./
 0 drwxrwxrwx 0 root root   512 Aug 11 20:29 ../
 0 -rwxrwxrwx 1 root root    54 Aug  4 17:50 ansible.cfg*
 4 -rwxrwxrwx 1 root root   942 Aug  4 17:50 b2_gogs.yml*
 4 -rwxrwxrwx 1 root root  2419 Aug  4 17:50 caddy.yml*
12 -rwxrwxrwx 1 root root 11122 Aug  4 17:50 ConfigureRemotingForAnsible.ps1*
 0 -rwxrwxrwx 1 root root     0 Mar 23 20:26 files*
 0 drwxrwxrwx 0 root root   512 Aug  4 18:32 .git/
 0 -rwxrwxrwx 1 root root    86 Aug  4 17:52 .gitattributes*
 0 -rwxrwxrwx 1 root root   108 Aug  4 17:50 gitea.yml*
 0 -rwxrwxrwx 1 root root    16 Aug  4 18:25 .gitignore*
 4 -rwxrwxrwx 1 root root  1126 Aug  4 17:50 gogs.yml*
 4 -rwxrwxrwx 1 root root   880 Aug  4 17:50 golang.yml*
 0 -rwxrwxrwx 1 root root    28 Aug  4 17:50 hosts.ini*
 0 -rwxrwxrwx 1 root root   385 Aug  4 17:50 init.sh*
 4 -rwxrwxrwx 1 root root  3844 Aug  4 17:50 klauer.yml*
 0 -rwxrwxrwx 1 root root   310 Aug  4 17:50 minecraft.yml*
 0 -rwxrwxrwx 1 root root   103 Aug  4 18:00 os-hardening.yml*
 4 -rwxrwxrwx 1 root root   763 Aug  4 17:50 philae.yml*
 4 -rwxrwxrwx 1 root root  1078 Aug  4 17:50 postgres-netgearlogs.yml*
 4 -rwxrwxrwx 1 root root  1022 Aug  4 17:50 postgres.yml*
 4 -rwxrwxrwx 1 root root  1046 Aug  4 17:50 README.md*
 0 -rwxrwxrwx 1 root root   222 Aug  4 17:50 remote-update.yml*
 0 -rwxrwxrwx 1 root root     0 Aug  4 17:56 roles*
 0 -rwxrwxrwx 1 root root   170 Aug  4 17:50 root.sh*
 4 -rwxrwxrwx 1 root root  3106 Aug  4 17:50 root.yml*
 1 -rwxrwxrwx 1 root root   565 Aug  4 17:50 site.yml*
 0 drwxrwxrwx 0 root root   512 Mar 23 20:26 tasks/
 0 drwxrwxrwx 0 root root   512 Aug  4 17:21 templates/
 4 -rwxrwxrwx 1 root root  1404 Aug  4 17:50 the_platinum_searcher.yml*
 4 -rwxrwxrwx 1 root root  1793 Aug  4 17:50 vault.yml*
 4 -rwxrwxrwx 1 root root  1123 Aug  4 17:50 vultr.yml*
 4 -rwxrwxrwx 1 root root  3240 Aug  4 17:50 wekan.yml*

```

* What's wrong / what should be happening instead:

All of `files`, `roles`, `tasks`, etc., should show as directories:

![image](https://user-images.githubusercontent.com/4735/29249135-d351483a-7fef-11e7-84cc-f018335b8375.png)

If I try to `cd` into them, I get an error:

![image](https://user-images.githubusercontent.com/4735/29249140-e2408766-7fef-11e7-95b7-603edf5d907e.png)

If I go to Windows Explorer and open the directory, however, and then go back, I can get the directory to be discovered by WSL:

![image](https://user-images.githubusercontent.com/4735/29249164-3ea013f0-7ff0-11e7-8dfb-5d9e2b67a9c6.png)

![image](https://user-images.githubusercontent.com/4735/29249166-49549884-7ff0-11e7-8986-b624ccf0e174.png)

![image](https://user-images.githubusercontent.com/4735/29249169-5ef89b9a-7ff0-11e7-9697-9b23cfac990e.png)

**Comment by benhillis** [comment] 2017-08-13 14:43
Duplicate of #2392. Thanks for reporting.

**Closed by benhillis** 2017-08-13 14:43 UTC
