### ISSUE TITLE
Arch Pacman broken (fails reading list of installed packages)

### ISSUE THREAD

**Issue by fpqc** [Microsoft/BashOnWindows#2310] opened 2017-07-11 02:15 UTC
Build 16237

Installing packages with pacman in an Arch userspace (manual setup instructions [here](https://wiki.archlinux.org/index.php/Install_on_WSL) ) now fails to see that installed packages are installed, so installing a new package will install all dependencies up to the very top of the dependency tree.  I think this also happened in the previous build (16236) (actually no longer sure), and I'm not sure if it happened due to a change in the code of Pacman or a change in WSL (I don't have a Win10 computer on hand running CU, just insider builds).  

The workaround is to delete the local database (/var/lib/pacman/local) before every manual installation of a package, but this completely breaks updating with -Su.

**Comment by sunilmut** [comment] 2017-07-11 05:11
@fpqc - Are you able to downgrade the pacman version to see if that changes anything? That will reduce one of the variable here.

**Comment by DDoSolitary** [comment] 2017-07-11 05:56
@sunilmut I also have this problem too after upgrading build 16237. I didn't upgrade the pacman.

**Comment by fpqc** [comment] 2017-07-11 06:15
@sunilmut let me grab from the cached packages on my server.

**Comment by fpqc** [comment] 2017-07-11 10:13
@sunilmut If you untar and chroot into the bootstrap environment, `pacman -Q` will show no output.

Previously (on earlier builds like 16215), `pacman -Q` while chrooted would output [this list for 05.01 bootstrap tarball](https://gist.github.com/fpqc/f8f4d5fa79810451bdd4d3232f58cbf5) and [this list for 07.01 bootstrap tarball](https://gist.github.com/fpqc/fcb89ebdc6f32efb5e69b3327e19ae3b)

**Comment by sunilmut** [comment] 2017-07-11 18:52
Looking into this now, starting with a repro.

**Comment by sunilmut** [comment] 2017-07-11 21:15
Looks like I have a repro. Will start digging.

**Comment by sunilmut** [comment] 2017-07-11 23:02
Found the culprit. 

syscall trace of `pacman -Q` on build 16215, where things are working:
```
GETDENTS - 3, {000000000154DD40}, 32768 = 3107
GETDENTS - 3, {000000000154DD40}, 32768 = 0
LSEEK - 3, 0, 0 = 0
GETDENTS - 3, {000000000154DD40}, 32768 = 3107
GETDENTS - 3, {000000000154DD40}, 32768 = 0
```
syscall trace of `pacman -Q` on build 16237, where things are broken:
```
GETDENTS - 3, {0000000001E13D40}, 32768 = 3424
GETDENTS - 3, {0000000001E13D40}, 32768 = 0
LSEEK - 3, 0, 0 = 0
GETDENTS - 3, {0000000001E13D40}, 32768 = 0
```

Note how after the LSEEK call, the cursor is not rewinding. We did some changes to the getdents syscall recently and regressed this. I tested some privates and the issue is resolved. I will get this in and try to get it fast tracked. Thanks @fpqc for reporting the issue. Also adding @SvenGroot as FYI.

**Comment by sunilmut** [comment] 2017-07-13 20:30
The fix has been checked in the dev branch and we will try to get it up as soon as possible.

Additionally, are there any other known blockers in getting strace to work on Arch, other than #555 ?

**Comment by therealkenc** [comment] 2017-07-13 22:10
> Additionally, are there any other known blockers in getting strace to work on Arch

Nah `PTRACE_O_TRACEEXIT` will make strace 4.15 happy AFAIK. The breakage was this change [here](https://github.com/strace/strace/commit/2f948b92316e30c5e19f413b863387dbb2de2451#diff-0dc24684ae01a4e0da25ca46c678ced4) per #1578.

**Comment by sunilmut** [comment] 2017-07-14 01:25
@SvenGroot recently added support for `PTRACE_O_TRACEEXIT`, which is making it's way to the Insider build.

**Comment by sunilmut** [comment] 2017-07-14 01:31
#555 is "fixinbound" :)

**Comment by mateuszlewko** [comment] 2017-08-01 10:13
In which build we can expect this fix?

**Comment by benhillis** [comment] 2017-08-01 14:52
Most recent Insider build has the fix.

**Comment by meltdown03** [comment] 2017-08-01 14:55
Do we have to uninstall / reinstall to see the chages? Running pacman -Q still shows nothing for me on latest build.

**Comment by benhillis** [comment] 2017-08-01 15:03
No you do not have to reinstall. Read over this tread again and it looks like there is one additional fix that will be coming soon.

**Comment by fpqc** [comment] 2017-08-01 15:12
@benhillis If you used my workaround it is highly recommended to reinstall because the database will be broken.

**Comment by benhillis** [comment] 2017-08-03 16:49
This is fixed in 16257.

**Closed** 2017-08-14 17:26 UTC
Labels: bug, fixed, fixedininsiderbuilds
