### ISSUE TITLE
Cmus

### ISSUE THREAD

**Issue by bramnet** [Microsoft/BashOnWindows#2076] opened 2017-05-08 08:12 UTC
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* [Version 10.0.15063]

* I installed cmus by entering "sudo apt-get install cmus" and then entering "cmus" to boot the program

* What ended up happening is that whenever I tried to play anything, it encountered an error during runtime stating "Error: opening audio device: No such device"

**Comment by sunjoong** [comment] 2017-05-08 09:47
@bramnet - WSL does not support audio yet. But, you could try https://github.com/kpocza/LoWe or like.

**Comment by therealkenc** [comment] 2017-05-08 10:34
#486. User Voice is [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/14017329-sound-card-support).

**Comment by stehufntdev** [comment] 2017-05-10 21:22
Thanks for reporting the issue.  Closing this out as a duplicate of the others so we can track it in one place.

**Closed by stehufntdev** 2017-05-10 21:22 UTC
