### ISSUE TITLE
nvm net.js error after 15031

### ISSUE THREAD

**Issue by ztrange** [Microsoft/BashOnWindows#1683] opened 2017-02-09 16:49 UTC
After updating Windows to 15031 I started seeing the following error when opening a new terminal, because of this line of .bashrc which loads nvm:

```bash
export NVM_DIR="/home/ztrange/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```

```bash
net.js:145
    this._handle.open(options.fd);
                 ^

Error: Unknown system error -25: Unknown system error -25, uv_pipe_open
    at Error (native)
    at new Socket (net.js:145:18)
    at createWritableStdioStream (internal/process/stdio.js:156:16)
    at process.getStdout [as stdout] (internal/process/stdio.js:10:14)
    at module.exports (/home/ztrange/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/npmlog/node_modules/set-blocking/index.js:2:11)
    at Object.<anonymous> (/home/ztrange/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/npmlog/log.js:11:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v6.9.5 --silent` to unset it.
```

The part about the config prefix disappeared after I ran the suggested option, but it again returned the same error without the `nvm is not compatible`

I already tried updating nvm to latest version and installing latest node with nvm but it's all the same. I also tried installing.

To reproduce I hope it's enough to install nvm and install node latest

FYI, node works (It was failing but I made it work by removing all installed node versions and reinstalling the latest one) but I haven't yet seen that node fails unexpectedly. I'm just reporting that it reports that error when loading nvm.

**Comment by sngeth** [comment] 2017-02-09 19:13
I'm seeing this as well. The error also occurs when installing new versions of Node.

```
/mnt/d/Code/mobile(develop) » nvm install --lts                                                                                          sid@DESKTOP-OETGQPP
Installing latest LTS version.
Downloading and installing node v6.9.5...
Local cache found: $NVM_DIR/.cache/bin/node-v6.9.5-linux-x64/node-v6.9.5-linux-x64.tar.xz
Checksums match! Using existing downloaded archive $NVM_DIR/.cache/bin/node-v6.9.5-linux-x64/node-v6.9.5-linux-x64.tar.xz
net.js:145
    this._handle.open(options.fd);
                 ^

Error: Unknown system error -25: Unknown system error -25, uv_pipe_open
    at Error (native)
    at new Socket (net.js:145:18)
    at createWritableStdioStream (internal/process/stdio.js:156:16)
    at process.getStdout [as stdout] (internal/process/stdio.js:10:14)
    at module.exports (/home/sid/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/npmlog/node_modules/set-blocking/index.js:2:11)
    at Object.<anonymous> (/home/sid/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/npmlog/log.js:11:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `npm config delete prefix` or `nvm use --delete-prefix v6.9.5` to unset it.
```

**Comment by rixrix** [comment] 2017-02-10 03:28
I encountered the same issue, this is after the last build release of Windows insider 15031.0. I'm using nvm due to that I maintain a bunch of backend that only requires a specific version of NodeJS, some were on IoT device which comes with an oldie release of Node going back as far v0.12.x

I'd be grateful if there's a workaround. thanks

Here's my log:

```
nvm use v4.3.2
net.js:129
    this._handle.open(options.fd);
                 ^

Error: Unknown system error -25: Unknown system error -25, uv_pipe_open
    at Error (native)
    at new Socket (net.js:129:18)
    at createWritableStdioStream (node.js:601:18)
    at process.stdout (node.js:627:16)
    at module.exports (/home/urix/.nvm/versions/node/v4.3.2/lib/node_modules/npm/node_modules/npmlog/node_modules/set-blocking/index.js:2:11)
    at Object.<anonymous> (/home/urix/.nvm/versions/node/v4.3.2/lib/node_modules/npm/node_modules/npmlog/log.js:11:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v4.3.2` to unset it.
```

**Comment by benhillis** [comment] 2017-02-10 16:13
Would it be possible for one of you to share an strace of the failing operation?  That would help us narrow down what is going wrong.

**Comment by soda0289** [comment] 2017-02-10 16:38
@benhillis 

I can reproduce this issue when I try to install an npm package globally.

For example: `npm install noop -g`

Here is the strace dump:
https://gist.github.com/soda0289/0b10aa24f728e5e9b43f79a88febca82

**Comment by benhillis** [comment] 2017-02-10 16:54
Thanks for sharing. The error is likely coming from one of these three operations:
[
ioctl(2, TCGETS, 0x7fffe5362030)        = -1 ENOTTY (Inappropriate ioctl for device)
ioctl(9, TCGETS, 0x7fffe5360e60)        = -1 ENOTTY (Inappropriate ioctl for device)
ioctl(1, TIOCGPTN, 0x7fffe53614fc)      = -1 ENOTTY (Inappropriate ioctl for device)](url)

**Comment by benhillis** [comment] 2017-02-10 19:17
We have identified the issue and the fix has been checked in.

**Comment by rixrix** [comment] 2017-02-10 23:54
@benhillis sorry for asking, do we know the timeline when are we going to get the update ? would it be via insider build or lxrun /update ? thank you

**Comment by benhillis** [comment] 2017-02-11 00:17
lxrun /update is only a wrapper for "apt update" and only updates the apt package cache. This is a bug in the driver which will be available in a Windows Insider build in a few weeks.

**Comment by rixrix** [comment] 2017-02-11 00:33
@benhillis thanks. I decided to revert to the previous Insider build - which only took at most 5mins. Thanks for all your hard work, will try out the fix once released.

**Comment by benhillis** [comment] 2017-02-11 01:32
No problem! The rollback feature really is great and doesn't get enough credit.  It's saved me a couple times as well.

**Comment by sebfindling** [comment] 2017-02-11 03:25
Same problem. @rixrix @benhillis if I roll back, can I avoid getting 15031 again and still get the next one?

**Comment by rixrix** [comment] 2017-02-11 04:22
@sebfindling re: avoid, there's a `pause updates` option in the advanced options settings, turn it on and you won't get 15031 build for a month I guess. Hope that helps you out. cheers

**Comment by XDTZ** [comment] 2017-02-12 14:22
Here's a minimalistic demonstration of the bug:
```
user@Machine:~/bug$ node -v
v7.5.0
user@Machine:~/bug$ cat lib/index.js
'use strict';

console.log('text');
user@Machine:~/bug$ node lib
text
user@Machine:~/bug$ node lib | grep text
net.js:148
    this._handle.open(options.fd);
                 ^

Error: Unknown system error -25: Unknown system error -25, uv_pipe_open
    at new Socket (net.js:148:18)
    at createWritableStdioStream (internal/process/stdio.js:156:16)
    at process.getStdout [as stdout] (internal/process/stdio.js:10:14)
    at console.js:100:37
    at NativeModule.compile (bootstrap_node.js:521:7)
    at Function.NativeModule.require (bootstrap_node.js:462:18)
    at get (bootstrap_node.js:250:34)
    at Object.<anonymous> (~/bug/lib/index.js:3:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

**Comment by reybango** [comment] 2017-02-23 16:10
@benhillis This is still occurring in 15040. Was the driver fix applied to this build or is it coming in a subsequent one?

**Comment by benhillis** [comment] 2017-02-23 17:45
@reybango - I just checked this and the fix made it to the prerelease branch for the 15041 build.

**Comment by Dj-jom2x** [comment] 2017-02-25 05:51
15042 fixed

**Closed** 2017-03-01 20:54 UTC
Labels: fixinbound
