### ISSUE TITLE
Failed to install node modules globally

### ISSUE THREAD

**Issue by anks333** [Microsoft/BashOnWindows#1702] opened 2017-02-14 19:57 UTC
I was trying to install Babel using npm, But it failed. Since I was installing it globally so the terminal suggested me to use sudo, I did but failed to install

Log

Error: could not get uid/gid
net.js:145
    this._handle.open(options.fd);
                 ^

Error: EINVAL: invalid argument, uv_pipe_open
    at Error (native)
    at new Socket (net.js:145:18)
    at createWritableStdioStream (internal/process/stdio.js:156:16)
    at process.getStdout [as stdout] (internal/process/stdio.js:10:14)
    at console.js:100:37
    at NativeModule.compile (bootstrap_node.js:497:7)
    at Function.NativeModule.require (bootstrap_node.js:438:18)
    at get (bootstrap_node.js:254:34)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/uid-number/get-uid-gid.js:16:1)
    at Module._compile (module.js:570:32)
    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

**Comment by jackchammons** [comment] 2017-02-14 23:20
@anks333 please check out our [contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) and modify your issue accordingly.

**Comment by benhillis** [comment] 2017-02-15 01:05
Marking as a duplicate of #1683

**Closed by benhillis** 2017-02-15 01:05 UTC

**Comment by marchaos** [comment] 2018-01-10 16:30
I'm still seeing this issue with os build 16299.

marchaos@DESKTOP-Q36F1A9:~$ node.exe node.js
net.js:214
    this._handle.open(options.fd);
                 ^
Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:214:18)
    at createWritableStdioStream (internal/process/stdio.js:164:16)
    at process.getStdout [as stdout] (internal/process/stdio.js:14:14)
    at console.js:251:38
    at NativeModule.compile (bootstrap_node.js:605:7)
    at Function.NativeModule.require (bootstrap_node.js:550:18)
    at setupGlobalConsole (bootstrap_node.js:320:41)
    at startup (bootstrap_node.js:76:7)
    at bootstrap_node.js:617:3
marchaos@DESKTOP-Q36F1A9:~$

**Comment by therealkenc** [comment] 2018-01-10 16:48
That is more like #2370 which is still open
