### ISSUE TITLE
UML on WSL complains about PTRACE_OLDSETOPTIONS

### ISSUE THREAD

**Issue by thomasmey** [Microsoft/BashOnWindows#2078] opened 2017-05-08 15:14 UTC
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.15063

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

* What's wrong / what should be happening instead:
Trying to start a user mode Linux kernel under WSL Fails with

thomas@...:/mnt/c/Users/thomas/Downloads$ ./linux
Core dump limits :
         soft - NONE
         hard - NONE
Checking that ptrace can change system call numbers...check_ptrace:  
PTRACE_OLDSETOPTIONS failed: Invalid Argument

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment] 2017-05-08 15:17
Duplicate of #1692.

**Closed by benhillis** 2017-05-08 15:17 UTC
