### ISSUE TITLE
Files in ~/ Cannot be opened by GUI editors(e.g. Npp/ST3).

### ISSUE THREAD

**Issue by QIEXXII** [Microsoft/BashOnWindows#1905] opened 2017-04-13 12:17 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
 Some plain text files is saved under ~ directory.I try to use Notepad++ and Sublime Text 3 to open them and failed.

* Expected results
  Just open the files.

* Actual results (with terminal output if applicable)
   `"Cannot convert current working directory.Using C:\Users\MY_USER_NAME"`.It makes the editor cannot find the files.
* Your Windows build number
  Windows 10.0.15063 version 15063

* Steps / All commands required to reproduce the error from a brand new installation 
  1. I saved some files under ~ directory, which means `C:\Users\MY_USER_NAME\AppData\Local\lxss\root`. (The files' permission are 777.)
  2. Then I made some alias: `# alias subl='/mnt/c/Program\ Files/Sublime\ Text\ 3/sublime_text.exe'` & `# alias npp='/mnt/c/Program\ Files/"Notepad++"/notepad++.exe' `.
  3. And I use `# subl THE_FILE` , `# npp THE_FILE` to open `THE_FILE`, and failed: `"Cannot convert current working directory.Using C:\Users\MY_USER_NAME"` .

* Strace of the failing command

* Required packages and commands to install

* My poor English

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment] 2017-04-13 12:41
yeah, you still cant do this yet. No news yet on how MS is going to deal with it, but it has to do with the way lxfs inode caching and permissions work.

**Comment by stehufntdev** [comment] 2017-04-13 16:44
Closing this out as a duplicate of #51.  There's a link to a blog post in there with more details.

**Closed by stehufntdev** 2017-04-13 16:44 UTC
