### ISSUE TITLE
Intel C++ compiler and performance library fail to install

### ISSUE THREAD

**Issue by aludin** [Microsoft/BashOnWindows#1402] opened 2016-11-21 15:06 UTC
* A brief description

I am trying to install the Intel Parallel Studio suite of compilers and tools (mostly the C++ compiler, MKL, Intel TBB and Intel Daal). However the setup fails as soon as it is launched using the install.sh script

* Expected results

Intel compilers installed under /opt/intel

* Actual results (with terminal output if applicable)

Setup fails immediately with the following output:

Initializing, please wait...
Something wrong with activation module. Please go to
http://www.intel.com/software/products/support/ for your support options.
Press "Enter" key to quit

* Your Windows build number

Windows 10 Pro version 1607 Build 144393.447

* Steps / All commands required to reproduce the error from a brand new installation 

1. Download Intel Parallel Studio for Linux.
2. Start Install

* Strace of the failing command

No traces available. Silent fail.

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment] 2016-11-21 15:50
Hi @aludin -- thanks for reporting this!  It sounds to me like a duplicate of #794 .  Could you take a look at that issue and comment on whether you think it's the same thing?

**Comment by aludin** [comment] 2016-11-21 16:20
Hi @aseering , yes indeed this is a duplicate of #794. ifort is also part of Intel Parallel Studio. Please note that I have also raised the issue on Intel forums. It seems however that in order to solve this specific issue, a concerted effort between MS and Intel would be required.

**Comment by Oeffner** [comment] 2016-11-21 18:08
I guess this is also related to https://github.com/Microsoft/BashOnWindows/issues/1373. Hopefully this will be addressed. The test binary built with Intel tools seems to run with more than twice the speed as when built with g++ so it would be good to have support for that.

**Comment by jackchammons** [comment] 2016-11-23 21:49
Marking this as a duplicate. @aludin please close this issue if you feel your concerns are addressed in the other issues mentioned above.

**Comment by aludin** [comment] 2016-11-24 13:46
closing this issue and updating issue #794 to include the Intel c/c++ compilers

**Closed** 2016-11-24 13:47 UTC
Labels: duplicate
