### ISSUE TITLE
java.net.SocketException: Cannot assign requested address (IOCTL SIOCGIFNETMASK failed)

### ISSUE THREAD

**Issue by jamisonrea** [Microsoft/BashOnWindows#1591] opened 2017-01-12 10:27 UTC
HI!
**EDITED:**
Our project(s)  is using these languages:

- Grails version: 3.1.0
- Groovy grails: 2.4.5
- JVM version: 1.8.0_111

C:\>ver 
Microsoft Windows [Version 10.0.14393] 

By running our apps, we use "grails run-app". 

And for the repos I am using, it's private repos. :(

I installed above languages on my ubuntu bash and clone necessary repos. After running the "grails run-app --stacktrace", below is the output on my terminal.

| Error Error initializing classpath: Cannot assign requested address (IOCTL SIOCGIFNETMASK failed) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.net.SocketException: Cannot assign requested address (IOCTL SIOCGIFNETMASK failed)
        at org.gradle.messaging.remote.internal.inet.InetAddressFactory.init(InetAddressFactory.java:146)
        at org.gradle.messaging.remote.internal.inet.InetAddressFactory.findLocalBindingAddress(InetAddressFactory.java:111)
        at org.gradle.cache.internal.FileLockCommunicator.<init>(FileLockCommunicator.java:38)
        at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.getCommunicator(DefaultFileLockContentionHandler.java:153)
        at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.reservePort(DefaultFileLockContentionHandler.java:145)
        at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:79)
        at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:67)
        at org.gradle.cache.internal.OnDemandFileAccess.readFile(OnDemandFileAccess.java:36)
        at org.gradle.cache.internal.SimpleStateCache.get(SimpleStateCache.java:40)
        at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator.get(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:31)
        at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.getAll(PersistentDaemonRegistry.java:62)
        at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.getIdle(PersistentDaemonRegistry.java:77)
        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:80)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:118)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:78)
        at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:52)
        at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:35)
        at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:63)
        at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:35)
        at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:124)
        at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:109)
        at org.gradle.tooling.internal.provider.DefaultConnection.run(DefaultConnection.java:189)
        at org.gradle.tooling.internal.consumer.connection.CancellableConsumerConnection$CancellableActionRunner.run(CancellableConsumerConnection.java:105)
        at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:62)
        at org.gradle.tooling.internal.consumer.DefaultBuildActionExecuter$1.run(DefaultBuildActionExecuter.java:58)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83)
        at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
        at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
        at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)

**Comment by sunilmut** [comment] 2017-01-12 21:40
@jamisonrea - Thanks for your post. For future reference, please follow the [template](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) to post issues. For this post, can you tell me which build you are using? And, also please post repro steps as well. Without that it's difficult to track down issues.

**Comment by jamisonrea** [comment] 2017-01-13 03:39
@sunilmut , I updated my ticket.

Kindly check it and let me know if I still miss something for you/others to proceed on helping/checking it.


Kind regards,
james

**Comment by sunilmut** [comment] 2017-01-13 03:55
@jamisonrea - Thanks for the update. Private repo's definitely make it difficult to repro. But, let's not get that in our way here. Can you please take an strace `strace -o <trace_file> -ff <failing_cmd>` and share the trace out? If you are not comfortable sharing the trace from a private repo, publicly, I can also give you an offline channel as well. If you are not comfortable with that either, then you can dissect the trace and let us know what functionality is missing or misbehaving.

Also, are you able to test your stuff on the [Windows Insider build](https://blogs.windows.com/blog/tag/windows-insider-program/#VZPJsO5z3Ch9bO1l.97)? We have made significant changes to WSL, but, currently these updates are only available to Windows Insider. Eventually, these changes will also be available in the [Creators Update](https://www.microsoft.com/en-us/windows/upcoming-features), which is not that far away. You can host a VM, if you are not comfortable putting Insider build on your main dev box.

**Comment by andreminelli** [comment] 2017-01-13 11:50
Just to record, I'm having the same issue trying to start Cassandra 3.9, using same JDK version (8 build 111):

ERROR [main] 2017-01-13 10:41:51,318 CassandraDaemon.java:747 - Exception encountered during startup
java.lang.AssertionError: java.net.SocketException: Cannot assign requested address (IOCTL SIOCGIFNETMASK failed)
        at org.apache.cassandra.utils.FBUtilities.getAllLocalAddresses(FBUtilities.java:180) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.utils.UUIDGen.makeNode(UUIDGen.java:362) ~[apache-cassandra-3.9.jar:3.9]
(continue....)

**Comment by sunilmut** [comment] 2017-01-13 13:42
@andreminelli - Thanks for your post.

1. Which Windows build are you using?
2. What are the repro steps?
3. Can you take a strace (steps above) and share it out?

**Comment by andreminelli** [comment] 2017-01-13 15:07
1. Windows 10 Pro Version 1607 build 14393.577

2. I just installed using [these steps](https://www.digitalocean.com/community/tutorials/how-to-install-cassandra-and-run-a-single-node-cluster-on-ubuntu-14-04), and used `sudo service cassandra start`. I got that message on `/var/log/cassandra/system.log`.

3. I capture the strace running on foreground, the files are tar/zipped and attached:
[cassandra.trace.tar.gz](https://github.com/Microsoft/BashOnWindows/files/704589/cassandra.trace.tar.gz)

Hope this helps :)

**Comment by therealkenc** [comment] 2017-01-13 16:00
```
socket(PF_INET, SOCK_DGRAM, IPPROTO_IP) = 70
ioctl(70, SIOCGIFCONF, {-856638424 -> 320, NULL}) = 0
ioctl(70, SIOCGIFCONF, {320, {{"eth0", {AF_INET, inet_addr("10.0.75.1")}}, 
   {"eth1", {AF_INET, inet_addr("192.168.4.144")}}, {"wifi0", {0xfac0 /* AF_??? */, 
   "\0\344\337\177\0\0(\274\360\314\337\177\0\0"}}, {"wifi1", {0x510 /* AF_??? */, 
   "\0\344\337\177\0\0\320\246\341\354\337\177\0\0"}}, {"eth2", {AF_INET6, 
   "\341\354\337\177\0\0000\315\360\314\337\177\0\0"}}, 
   {"lo", {AF_INET, inet_addr("127.0.0.1")}}, 
   {"und0", {AF_BRIDGE, "\341\354\337\177\0\0p\273\360\314\337\177\0\0"}}, {"und1", {AF_NETROM, 
   "\360\314\337\177\0\0\360\246\341\354\337\177\0\0"}}}}) = 0
ioctl(70, SIOCGIFFLAGS, {ifr_name="eth0", 
   ifr_flags=IFF_UP|IFF_BROADCAST|IFF_RUNNING|IFF_MULTICAST}) = 0
ioctl(70, SIOCGIFBRDADDR, {ifr_name="eth0", 
   ifr_broadaddr={AF_INET, inet_addr("10.0.75.255")}}) = 0
ioctl(70, SIOCGIFNETMASK, {ifr_name="eth0", 
   ifr_netmask={AF_INET, inet_addr("255.255.255.0")}}) = 0
ioctl(70, SIOCGIFINDEX, {ifr_name="eth0", ifr_index=17}) = 0
ioctl(70, SIOCGIFFLAGS, {ifr_name="eth1",
   ifr_flags=IFF_UP|IFF_BROADCAST|IFF_RUNNING|IFF_MULTICAST}) = 0
ioctl(70, SIOCGIFBRDADDR, {ifr_name="eth1", 
   ifr_broadaddr={AF_INET, inet_addr("192.168.7.255")}}) = 0
ioctl(70, SIOCGIFNETMASK, {ifr_name="eth1", 
   ifr_netmask={AF_INET, inet_addr("255.255.248.0")}}) = 0
ioctl(70, SIOCGIFINDEX, {ifr_name="eth1", ifr_index=6}) = 0
ioctl(70, SIOCGIFFLAGS, {ifr_name="wifi0", ifr_flags=IFF_RUNNING}) = 0
```
and finally...
```
ioctl(70, SIOCGIFNETMASK, {ifr_name="wifi0", ???}) = -1 
   EADDRNOTAVAIL (Cannot assign requested address)`
```
Looks like #763 didn't 100% take maybe.

**Comment by andreminelli** [comment] 2017-01-13 18:30
The wi-fi adapter on this machine is turned off. I will turn it on an try again, just in case

**Comment by therealkenc** [comment] 2017-01-13 18:47
If that doesn't work maybe try the opposite direction: disable it. `netsh interface "Wi-Fi 1" set state disabled`, or something along those lines. You can get the list of interfaces names with `netsh interface show interface`.

**Comment by sunilmut** [comment] 2017-01-13 20:45
@therealkenc 

> Looks like #763 didn't 100% take maybe.

Note that @andreminelli is running build `14393` (Anniversary Update) and not the Insider build.

@andreminelli - Is there any possibility you can try your repro on the latest Insider build?

**Comment by andreminelli** [comment] 2017-01-13 20:54
I don't think so: this is a corporate machine which I don't want to 'mess' that much....
Sorry :(

**Comment by sunilmut** [comment] 2017-01-13 21:15
@andreminelli - No problem. An alternative is to setup a VM hooked up to the Insider build. That way you can have a forward looking idea as to whether the [`Creators Update`](https://www.microsoft.com/en-us/windows/upcoming-features) release will address your issues or not. If not, then you have the opportunity to log issues and get them fixed, for the release. Without knowing whether these issues are fixed or not on the Insider build, there is really no way for us to address them.

**Comment by therealkenc** [comment] 2017-01-13 22:04
Ah. Duh on the version number. My bad.

**Comment by j-bennet** [comment] 2017-01-14 02:24
I get the same error trying to run pyspark in Bash on Windows.

Windows version: `Microsoft Windows [Version 10.0.14393]`

Pyspark command:

```
export JAVA_HOME="/usr/lib/jvm/java-8-oracle/"
export SPARK_HOME="$HOME/bin/spark-2.0.1-bin-hadoop2.7"
export PYTHONPATH="$SPARK_HOME/python/lib/pyspark.zip:$SPARK_HOME/python/lib/py4j-0.10.3-src.zip:$PYTHONPATH"

alias pyspark="PYSPARK_DRIVER_PYTHON=`which python` PYSPARK_PYTHON=`which python` $SPARK_HOME/bin/pyspark --master \"local[4]\""
```

Error gist:

https://gist.github.com/j-bennet/7cc430561c64de0a3b29f18e75ac797f

**Comment by sunilmut** [comment] 2017-01-14 02:50
@j-bennet - Thanks for your post. Below is the snipped from your error log. Looks like what you are running into is #468, which is fixed in [Insider builds](https://blogs.windows.com/blog/tag/windows-insider-program/#kLyQu3CoLWw4MjtZ.97). Are you able to give the Insider build a try and see if it repros for you?

```
: java.net.SocketException: Cannot assign requested address (IOCTL SIOCGIFNETMASK failed)
	at java.net.NetworkInterface.getAll(Native Method)
	at java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:343)
	at org.apache.spark.util.Utils$.findLocalInetAddress(Utils.scala:873)
```

**Comment by j-bennet** [comment] 2017-01-14 04:03
@sunilmut Thanks, just set my laptop up to receive Insider builds. I guess it'll take some time? Don't see any updates being downloaded just yet.

**Comment by benhillis** [comment] 2017-01-14 04:41
I think it takes 24 hours until you're machine will pick up a new build.

**Comment by j-bennet** [comment] 2017-01-16 06:23
The Insider build did fix the pyspark issue. Thanks.

**Comment by jamisonrea** [comment] 2017-01-16 06:31
@All,

I already changed my Operating System as everyone here in our company also do the same. The reason is we need to finish our tasks for this week.

Feel free to close this ticket as may others might still waiting for the fix.

Thank you guys for the help!

**Comment by andreminelli** [comment] 2017-01-16 10:01
Well, on Anniversary build I have tried both disabling and turning on wi-fi adapter but without success.
I don´t know if I will be able to get a VM up with Insider Build, and since everything points to a fix on that release I think this issue can be closed too.

Thanks a lot!

**Comment by sunilmut** [comment] 2017-01-16 19:13
@j-bennet - Thanks for the validation and the post.

@andreminelli - Thanks, will close out the issue.

**Comment by sunilmut** [comment] 2017-01-16 19:13
Root cause is #468

**Closed** 2017-01-19 01:53 UTC
Labels: duplicate, fixedininsiderbuilds, network

**Comment by MeenakshiParyani** [comment] 2017-03-08 02:54
i am facing the same issue on Bash on Ubuntu on Windows. Please help me here. I have installed the latest updates of Windows 10. Not sure about insider builds. Do i need to install one? If yes, how can i do that?

Regards

**Comment by aseering** [comment] 2017-03-08 05:13
Hi @MeenakshiParyani -- I don't know for sure that Insider Builds have a fix to your specific problem, but they do have a whole lot of fixes to many different problems.  You can sign up for the Insider program at https://insider.windows.com/ .

Note that it can take 24-48 hours for updates to start appearing in Windows Update, after you've completed the registration.  Also, make sure to read the documentation -- Insider Builds have cool new software, but they also have risks and downsides.  I use them all the time; others prefer to wait until the feature is released to a stable version of Windows.

**Comment by MeenakshiParyani** [comment] 2017-03-08 05:39
@aseering Thanks for the info.
