### ISSUE TITLE
Path issues when running windows programs on bash

### ISSUE THREAD

**Issue by mkarpoff** [Microsoft/BashOnWindows#1249] opened 2016-10-21 22:21 UTC
If you run a windows program on bash and that program takes a path as an argument. Using `/mnt/c` as the path base results in a file not found error. It is expectated that the relative bash path would be accessible to windows. This was run on insider build14951 with ubuntu 16.04

**Run from:**
`/mnt/c/Program Files (x86)/VMware/VMware Workstation`
**Command:**
`./vmrun.exe start /mnt/c/Users/Marcus/Documents/Virtual\ Machines/Cornix/Cornix.vmx`
**Output:**
`Error: Cannot open VM: C:\mnt\c\Users\Marcus\Documents\Virtual Machines\Cornix\Cornix.vmx, The virtual machine cannot be found`

This example was run using vmrun.exe from VMware Workstation installed on windows but the same problem occurs with any path provided to a windows program.

**Comment by benhillis** [comment] 2016-10-21 22:40
Duplicate of #1243. We do not do any translation of command line arguments when launching Windows binaries.

**Closed** 2016-10-23 05:58 UTC
Labels: duplicate
