### ISSUE TITLE
Some members of struct rusage are in wrong units

### ISSUE THREAD

**Issue by tkelman** [Microsoft/BashOnWindows#141] opened 2016-04-12 00:16 UTC
```
root@localhost:/home/tkelman# cat getrusage.c
#include <stdio.h>
#include <sys/resource.h>
int main() {
struct rusage usage;
getrusage(RUSAGE_SELF, &usage);
printf("usage.ru_maxrss = %ld\n", usage.ru_maxrss);
}
root@localhost:/home/tkelman# gcc -g -o getrusage getrusage.c
root@localhost:/home/tkelman# ./getrusage
usage.ru_maxrss = 1437696
```
According to http://linux.die.net/man/2/getrusage, `ru_maxrss` should be in kilobytes, not bytes. This is one of those annoying BSD-vs-Linux inconsistencies. On real Ubuntu I get 860, on Cygwin 2620.

**Comment by sunilmut** [comment] 2016-04-13 06:09
Confirmed that this is a bug in our reporting and we have opened a bug on our end. Thanks for catching and reporting it, and of course for trying out this stuff.

**Comment by tkelman** [comment] 2016-04-13 07:49
Thanks for making this. Aside from the lack of win32-WSL interop (yet), I've wanted something like this for a while. If it can eventually pass JuliaLang's test suite I'd consider that a serious triumph for your team. Several open blockers but it sounds like you've already fixed a few of them and I can't wait to get my hands on the next build. libuv's test suite will also be a really good verification, and quite a bit easier for your team to compile.

**Comment by sunilmut** [comment] 2016-04-13 12:13
Thanks for the information. Can you pass on the URL to both of these tests? 
Just FYI that we have been running [LTP](https://github.com/linux-test-project/ltp) nightly for sometime now and passing close to ~50% of the tests there. There are couple of blockers ('symlinkat' syscall) that are preventing anyone using the publicly released bits from downloading, compiling and running the LTP themselves, but these blockers have all been fixed in our dev branch. We should soon have some public blog post around this. Stay tuned!

**Comment by tkelman** [comment] 2016-04-13 13:17
https://github.com/Microsoft/BashOnWindows/issues/118#issuecomment-208249048 is one blocker for me. Libuv is at https://github.com/libuv/libuv, pretty simple matter of configure and make then make check. It's the underlying C library that node.js (and a few other languages and tools) uses for IO so will often be the low level path that node/npm issues go through when it comes to unimplemented syscalls.

**Comment by sunilmut** [comment] 2016-04-14 14:56
@tkelman Thanks for the information. I did download libuv on WSL and was able to get "make check" to run. Although, as you point out, the tests are failing on WSL(also see the image below). My current understanding is that running "make check" runs the tests (under the "test" dir?), which tests for dependencies and functionality needed by libuv. Is that correct?

![libuv_wsl](https://cloud.githubusercontent.com/assets/16765049/14532348/9ddb99d4-0215-11e6-8e83-5d780968ec1e.png)
.

**Comment by tkelman** [comment] 2016-04-14 15:31
That's my understanding, yes. I seem to get 3 failures and 2 skips on real ubuntu 14.04 so current master might not be in a perfect state, but hopefully some of the WSL specific failures would be useful to look at if the cause is not yet known.

**Comment by sunilmut** [comment] 2016-04-14 15:43
@tkelman Yes, thanks. This is useful information and we will make use of it!

**Comment by benhillis** [comment] 2016-05-28 16:48
Looks like this is fixed in 14352.

```
root@BENHILL-VM3:~# cat main.c
#include <stdio.h>
#include <sys/resource.h>
int main() {
struct rusage usage;
getrusage(RUSAGE_SELF, &usage);
printf("usage.ru_maxrss = %ld\n", usage.ru_maxrss);
}
root@BENHILL-VM3:~# gcc main.c
root@BENHILL-VM3:~# ./a.out
usage.ru_maxrss = 1400
```

**Closed by benhillis** 2016-05-28 16:48 UTC
Labels: fixed
