### ISSUE TITLE
Rendering failure with minicom

### ISSUE THREAD

**Issue by ChrisASnyder** [Microsoft/BashOnWindows#2166] opened 2017-05-27 19:07 UTC
## Version ##
Microsoft Windows [Version 10.0.15063]

## Setup ##
- Raspberry PI (can be any remote client)
- minicom installed on PI
- USB2Serial FTDI cable connected to PI
- working ssh setup from Bash on Windows to PI

## Reproducing behavior ##
- ssh to PI
- launch minicom   ie: minicom -D /dev/ttyUSB0
- resize bash window (resizing creates problem)

Alternative method:

- Running minicom directly in the bash shell also causes the same rendering issues.

## Issue Description ##
Minicom creates a bar at the bottom of the terminal displaying connection information. When the window is resized this bar is not getting positioned on the bottom of the window correctly. 

There is something with the window size and how minicom is trying to adjust it's display that isn't working correctly compared to Cygwin or linux terminals.

**Comment by sunjoong** [comment] 2017-05-28 01:23
@ChrisASnyder 
> Running minicom directly in the bash shell also causes the same rendering issues

* Before resizing
![1](https://cloud.githubusercontent.com/assets/2748000/26525292/864beb3c-438e-11e7-9b23-469087361480.png)

* After resizing
![2](https://cloud.githubusercontent.com/assets/2748000/26525293/890b761c-438e-11e7-9b62-00b3e9f7cefe.png)

* Maximizing - red circle of above screenshot
![3](https://cloud.githubusercontent.com/assets/2748000/26525295/8ecd212c-438e-11e7-9d7b-394fcc3e9cb7.png)

* Restoring - red circle of above screenshot
![4](https://cloud.githubusercontent.com/assets/2748000/26525297/9987d8aa-438e-11e7-9ea0-0a805b318c26.png)

* After pressing Ctrl+A key
![5](https://cloud.githubusercontent.com/assets/2748000/26525299/9eb25bd4-438e-11e7-821a-35d5c6f76323.png)

**Comment by zadjii-msft** [comment] 2017-05-30 16:07
@ChrisASnyder Does this only repro with the maximize/restore button, or does it also happen when resizing using the edges of the window?

**Comment by sunjoong** [comment] 2017-05-30 16:18
@zadjii-msft - @ChrisASnyder said about `resizing using the edges of the window`, I think. I told them using maximize/restore and then Ctrl+A to redraw status bar.

**Comment by zadjii-msft** [comment] 2017-05-30 16:30
Ooooh wait I think I see it. Did you resize only using the bottom of the window? 

Try changing the width of the window and see if that makes the status bar appear at the bottom.

**Comment by sunjoong** [comment] 2017-05-30 16:37
@zadjii-msft - Who raised this isssue was @ChrisASnyder, not me. But I saw bash console cannot do what wsl-terminal, i.e., Cygwin mintty, can do after to `resize only using the bottom of the window`.

**Comment by zadjii-msft** [comment] 2017-05-30 16:42
@sunjoong I don't really have the time to crawl through old issues looking for the old, longer explanation I gave, but basically there's a compat issue with the console API that prevents us from sending resize events when the height of the console window changes, but the dimensions of the screenbuffer (with a default height of 9001) don't change. This is most resizes where only the height of the window changes. 

And of course, because it's legacy behavior, we have to maintain it for legacy reasons -___-

**Comment by sunjoong** [comment] 2017-05-30 16:55
@zadjii-msft - Hmm... you look like to misunderstand my word, I think. I mean @ChrisASnyder seems to complain why bash console isn't working correctly compared to Cygwin or linux terminals, and wsl-terminal is basically Cygwin mintty. No one mentioned about legacy console.

BTW, I found old minicom resizing issue about gnome-terminal on other site but cannot sure that was similar to this.

**Comment by ChrisASnyder** [comment] 2017-05-30 18:56
@zadjii-msft After some more experimenting, moving only the height the bottom status doesn't update. If then resized right and left, will cause the bottom bar to refresh. Using the corner, as I tend to always do, results in a mixture of the other two behaviors. 

It also appears that minicom has a minimum vertical which effects rendering windows getting made small. Something I didn't notice at first.

Knowing now that if I adjust the width after adjusting the height at least lets this stay usable.
Less of an issue, there is also some weirdness when the scroll is used. The display only recovers when window width is adjusted. New text arriving in the terminal does snap the view, but doesn't redraw the bottom.

![image](https://cloud.githubusercontent.com/assets/19978542/26599706/8810130c-4547-11e7-8797-ec9634c9a96a.png)

**Comment by ChrisASnyder** [comment] 2017-05-30 19:03
I also wanted to clarify my point. I spend a lot of time in shells in Ubuntu and Debian, and Cygwin (mintty) with only the Bash on Windows having this inconsistent behavior. (that's probably a better label for the title now that I know a little more about it)

**Comment by zadjii-msft** [comment] 2017-05-30 19:45
Yep. This is a known issue with the console. It's not a `bash.exe` problem, it's a conhost problem. 

The `WINDOW_BUFFER_SIZE_EVENT` from [ReadConsoleInput](https://msdn.microsoft.com/en-us/library/windows/desktop/ms685035(v=vs.85).aspx) only fires when the _screen buffer_ size changes, not when the _window_ size changes. This is just how the API works unfortunately.

As you can see, resizing the width is a workaround. This is technically a dupe of #1001, so I'm gonna close it as such.

It may be worth pointing out that apps that use the alternate screen buffer (for term settings where `smcup=\E[?1049h`) won't have this problem - see tmux, emacs, vim, etc. These WILL get vertical resize events. Most full-screen terminal applications use this mode, it may be worthwhile for minicom to add support for that mode.

**Closed** 2017-05-30 19:46 UTC
Labels: console, duplicate, feature, workaround-available
