### ISSUE TITLE
Cannot launch bash because another instance is running un-elevated.

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/BashOnWindows#2200] opened 2017-06-08 15:02 UTC
When I try to run bash under Administrator I get this message:

```
Cannot launch bash because another instance is running un-elevated. Elevated and un-elevated instances are not permitted to run simultaneously.
```

![image](https://user-images.githubusercontent.com/736697/26935345-1e23f586-4c85-11e7-936e-d7cc1e29e939.png)

What can be the reason.

It started to happen after upgrade to Insiders Preview, currenlty build is 15063

**Comment by iamdevlinph** [comment] 2017-06-08 15:08
Did you try checking your task manager?

![image](https://user-images.githubusercontent.com/19337229/26935792-6e5e1ff8-4c9f-11e7-8d68-339f73d42dbf.png)

**Comment by whitecolor** [comment] 2017-06-08 15:17
There a  lot of bash processes I running. Will try later to remove all.

**Comment by sunjoong** [comment] 2017-06-08 15:46
@whitecolor - Quote from https://github.com/Microsoft/BashOnWindows/issues/1963#issuecomment-295775875;
> The workaround would be to launch all of you bash shells at the same integrity level (elevated vs unelevated). It seems in your above scenario one process is running elevated and the other is not.

**Comment by stehufntdev** [comment] 2017-06-08 18:31
Thanks for reporting the error, closing this out as a duplicate of #1963.

**Closed by stehufntdev** 2017-06-08 18:31 UTC
