### ISSUE TITLE
Cannot move '~/xyz' to a subdirectory of itself '/opt/xyz'

### ISSUE THREAD

**Issue by Coridyn** [Microsoft/BashOnWindows#221] opened 2016-04-18 00:41 UTC
Trying to move a directory from my home directory to `/opt` fails with an error saying the destination is a subdirectory of itself.

```bash
/$ cd ~/
~$ mkdir xyz
~$ mv xyz/ /opt
```

```bash
mv: cannot move ‘xyz/’ to a subdirectory of itself, ‘/opt/xyz’
```

The source and destination are in totally different locations so I don't know why it's saying the destination is a subdirectory of the source.

I can rename it within my home directory:

```
~/ mv xyz abc
```

But I get the same error trying to move it anywhere under `/`:

```
~$ mv xyz /usr/local
mv: cannot move ‘xyz’ to a subdirectory of itself, ‘/usr/local/xyz’

~$ mv xyz /
mv: cannot move ‘xyz’ to a subdirectory of itself, ‘/xyz’
```

**Comment by patryk9200** [comment] 2016-04-18 08:15
It's known issue, MS states that they have it fixed internally.

Related to #179 #83 #37 #104 etc.

**Comment by Coridyn** [comment] 2016-04-18 10:02
Sorry, I didn't see those other issues there.

Thanks for the answer, thought I was going crazy when it kept giving me that error message :)

**Closed** 2016-04-18 10:03 UTC

**Comment by yasirs** [comment] 2016-04-28 01:43
I am unable to reproduce this error on 14332.1001. Has the issue been fixed? Can someone confirm?
I tried
```
/$ cd ~/
~$ mkdir xyz
~$ mv xyz/ /opt
```
and there was no error.

**Comment by benhillis** [comment] 2016-04-28 02:06
@yasirs Yeah looks liks this one is fixed.
