### ISSUE TITLE
xterm works, but busy-waits

### ISSUE THREAD

**Issue by cgull** [Microsoft/BashOnWindows#504] opened 2016-06-09 23:56 UTC
xterm appears to run normally, but uses 100% CPU.  strace shows repeated calls to both `select()` and `poll()` and then `read()`/`recvmsg()` calls on file descriptors that fail with EAGAIN, it appears these are nonblocking.

I have no idea why xterm calls both `poll()` and `select()`, but xterm is full of horrible code in a maze of portability ifdefs, and so I'm not surprised.  (I am surprised that xterm works at all; I thought it would take quite a long time to work through the strange things it does.)

PuTTY's pterm, lxterminal, and stterm all seem OK so this seems to be something unique to xterm.

**Comment by DHowett** [comment] 2016-06-10 04:56
urxvt, however, _works awesomely._ It has to be launched via `urxvtdc`, its split-brain client/server version, however.

Is there a chance it's a bad interaction with the X server? Are you using Vcxsrv or Xming?

**Comment by therealkenc** [comment] 2016-06-10 06:42
Looks like it's ptmx related. Those socket EAGAINs on `recvmsg(3, ...)` are 'normal' believe it or not (for Xlib's definition of normal). Even if you launch xlogo you'll see a flood of them on native Ubuntu.

The problem is that `select(5, [3 4], [], NULL, NULL)` keeps saying there is data on fd 4, which is the pty -- but there isn't. Subsequent `read(4, ...)` returns EAGAIN and it loops forever. On native Ubuntu the `select()` blocks until a key is pressed in the xterm window.

The opening sequence is:
```
rt_sigaction(SIGTTOU, {SIG_IGN, [TTOU], SA_RESTORER|SA_RESTART, 0x7f030c7334a0}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGALRM, {0x42d730, [ALRM], SA_RESTORER|SA_RESTART, 0x7f030c7334a0}, {SIG_DFL, [], 0}, 8) = 0
alarm(2)                                = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
open("/dev/tty", O_RDWR)                = 4
alarm(0)                                = 2
rt_sigaction(SIGALRM, {SIG_DFL, [ALRM], SA_RESTORER|SA_RESTART, 0x7f030c7334a0}, {0x42d730, [ALRM], SA_RESTORER|SA_RESTART, 0x7f030c7334a0}, 8) = 0
ioctl(4, TCGETS, {B38400 opost isig icanon echo ...}) = 0
close(4)                                = 0
open("/dev/ptmx", O_RDWR)               = 4
statfs("/dev/pts", {f_type="DEVPTS_SUPER_MAGIC", f_bsize=4096, f_blocks=0, f_bfree=0, f_bavail=0, f_files=0, f_ffree=0, f_fsid={0, 0}, f_namelen=255, f_frsize=4096, f_flags=4138}) = 0
ioctl(4, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(4, TIOCGPTN, [18])                = 0
stat("/dev/pts/18", {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 18), ...}) = 0
ioctl(4, TCGETS, {B38400 opost isig icanon echo ...}) = 0
```

**Comment by cgull** [comment] 2016-06-10 14:37
I'm actually using Cygwin/X as the server.  I doubt the X11 server has anything to do with this issue, though.  I agree the issue is likely to be pty-related, my guess is that `select()` et al do not block on ptys opened non-blocking.

**Comment by sunilmut** [comment] 2016-06-10 21:51
Thanks for reporting this and providing detailed diagnosis. As you guys have figured, the issue was in the WSL PTY code where some epoll state was not getting reset. The fix should get checked in soon and make its way to the release branch.

**Comment by jbaribeault** [comment] 2016-06-15 17:31
Doesn't seem to be in 14366...ah well...soon soon.

**Comment by therealkenc** [comment] 2016-06-24 20:39
Its pretty academic because xterm is more or less obsolete anyway, but just a heads up this still spins in 14372, in case the fix didn't get merged or something.

**Comment by therealkenc** [comment] 2016-06-30 05:01
Joy in 14376 if you want to mark this as fixed.

**Comment by benhillis** [comment] 2016-06-30 18:47
Thank you for confirming.

**Closed by benhillis** 2016-06-30 18:47 UTC
Labels: bug, fixed
