### ISSUE TITLE
Cannot paste particular characters

### ISSUE THREAD

**Issue by sunjoong** [Microsoft/BashOnWindows#2149] opened 2017-05-24 05:24 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What's wrong / what should be happening instead:
I found some charcters (from U+FF5F to U+FF65 and U+FFE8 to U+FFEE) cannot be pasted in bash console, but can be in cmd window.

Like #2131, this is not a font issue. Of course, you need fonts like MS Gothic, NSimSun, SimSun-ExtB or other font that support that characters to display but that's whole another story; This is a paste issue. Unlike #2131, changing keyborad layout does not make any differences.

I don't know why `endd` was displied, not `end`. ~~Might be... similar cause of #2146.~~ __UPDATE__: `endd` looks like "garbage characters display" issue alike #2204 and not to be related to #2146. And... I deleted a screenshot having `endd` because main issue were reproduced "internally" by @miniksa and `endd` is not a main issue.

**Comment by sunjoong** [comment] 2017-05-24 05:27
@zadjii-msft ping

**Comment by fpqc** [comment] 2017-05-24 14:30
ping like sonar or radar.

you send a signal out, 
pong is the return signal.

Also, in submarines, you can audibly hear the ping of sonar, so if you're pinged, you know people are looking for you.

**Comment by sunjoong** [comment] 2017-05-24 14:42
@fpqc - Haha. Thanks. I saw you used ping a few days ago. So... that means... @zadjii-msft could know I'm looking for them.

**Comment by zadjii-msft** [comment] 2017-05-24 16:53
Yea this looks a lot like #2131.

I'll add it to MSFT:12077421 to make sure they're both resolved when I get to looking at it.

**Comment by therealkenc** [comment] 2017-05-24 19:12
> BTW, what's the meaning of ping in this culture? 

It is kind of like walking up to someone and poking them with a stick to make sure they know you're there.

**Comment by sunjoong** [comment] 2017-05-24 19:29
@therealkenc - Hmm... do you mean that could be a bad habbit? If so... I should be careful when using that.

**Comment by therealkenc** [comment] 2017-05-24 20:24
"Bad" is too strong a word. Submarines can't see you; that's why they have sonar. Everyone can see you on github, if they are inclined to look. So yeah, if your issue is buried, missed, ignored, or you want to bring someone you know into the loop (because you think they aren't looking), ping away. Or, you can be the guy the who announces their arrival at the party.

**Comment by fpqc** [comment] 2017-05-24 20:26
I usually just drop [console] in the titles of my issues so i don't need to ping anyone, but I'll ping console people if it's not clear from the title of someone else's topic?

**Comment by zadjii-msft** [comment] 2017-05-24 20:40
Also, for the record, I only ever triage issues on here a couple times a week from 9-5 PST, Monday-Friday. Definitely not every day. But if it's outside those hours, I'm not ignoring you, I just haven't gotten to it yet. I'm usually pretty good about figuring out which issues on here are actual console issues vs other WSL issues.

**Comment by therealkenc** [comment] 2017-05-24 20:42
@fpqc - To be fair console is a special (unfortunate) situation. It's like posting an xterm problem to LKML, which in the circumstance is necessary for lack of a different venue. I should have picked a different thread for the eyeroll; notably ones where I have seen multiple devs (and PMs) get name dropped for no constructive reason. On bigger github lists I've seen it get completely out of hand.

**Comment by miniksa** [comment] 2017-06-09 18:31
I have reproduced this issue internally. I'll keep looking to see what I can do about it. It's a bit different than the Russian text one that was linked and I've resolved.

**Comment by sunjoong** [comment] 2017-06-10 02:23
@miniksa - Thanks. I see.

**Comment by miniksa** [comment] 2017-06-13 18:22
I've made a fix for this issue in one of our development branches. It should be on the way to Insiders builds within a few weeks.

**Comment by miniksa** [comment] 2017-07-11 21:04
According to the source tracker, the fix I created for this issue should be in Insiders builds 16234+.

**Closed by miniksa** 2017-07-11 21:04 UTC
Labels: bug, console, fixinbound
