### ISSUE TITLE
Files created from Windows does not show up in bash

### ISSUE THREAD

**Issue by itaysk** [Microsoft/BashOnWindows#552] opened 2016-06-18 07:26 UTC
If you go to lxss folder, for example your home, and create a file via Windows File Explorer, it will be shown in File Explorer, but not in bash.
I have also experienced files disappearing from bash when edited in windows.

I'm on 14361. This is a possible regression.

**Comment by itaysk** [comment] 2016-06-18 09:09
Just updated to 14366 and it looks the same

**Comment by timfel** [comment] 2016-06-18 11:25
@itaysk pretty sure this expected behavior currently. See the explanation at https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/

**Comment by itaysk** [comment] 2016-06-18 12:11
Consider the following scenario:
In bash, I created a Ruby on Rails project.
I then want to edit the files using VS code.
Current behavior will break the project. Files will be present in Windows world, but missing from bash.

This was even a demonstrated use case in some of the early videos that was released.

**Comment by timfel** [comment] 2016-06-18 12:39
For this scenario you will have to use a folder outside the lxrss tree.
Just put the project in your Windows home directory and put a symlink to it
into your linux home if you want.This has some other drawbacks, but should
work for the use case you describe and was also suggested in the blogpost.
Am 18.06.2016 2:11 nachm. schrieb "Itay Shakury" <notifications@github.com>:

**Comment by itaysk** [comment] 2016-06-18 13:40
ok. thanks for clarifying (although a bit disappointing)
should I close the issue?

**Comment by therealkenc** [comment] 2016-06-19 19:43
There's a [user voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13341279-a-file-created-in-c-users-user-appdata-local-lx).

**Comment by benhillis** [comment] 2016-06-20 16:39
Closing as a duplicate of #45.

**Closed by benhillis** 2016-06-20 16:39 UTC
Labels: duplicate

**Comment by ibr123** [comment] 2017-04-12 13:54
Hi everyone,
any updates on copying a folder from the windows to the Bash?

**Comment by aseering** [comment] 2017-04-12 16:07
Hi @ibr123 -- you're posting to a ticket that has been closed as a duplicate.  So you're not going to get any updates here :-)  Please post on the original ticket instead (see the comments above).  Alternatively, you might want to post on the UserVoice that's also linked to above.

**Comment by drewstaylor** [comment] 2020-05-01 18:33
The problem with the thinking of https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/ is it makes it difficult to do things like download a file from your email and migrate it to WSL
