### ISSUE TITLE
Broken Symlink - Can't drill down to sub-directories

### ISSUE THREAD

**Issue by mysteryjeans** [Microsoft/BashOnWindows#824] opened 2016-08-08 21:41 UTC
Basically it just keep rotating in same directory.. I have Garagespace symlink and cd to symlink works but then I can't drill down to sub-directories.

```
faraz@MAC-PC:~$ ls
Garagespace
faraz@MAC-PC:~$ cd Garagespace
faraz@MAC-PC:~/Garagespace$ ls
doorsale  doorsale-demo  virtenv
faraz@MAC-PC:~/Garagespace$ cd doorsale
faraz@MAC-PC:~/Garagespace/doorsale$ ls
doorsale  doorsale-demo  virtenv
faraz@MAC-PC:~/Garagespace/doorsale$ cd doorsale
faraz@MAC-PC:~/Garagespace/doorsale/doorsale$ ls
doorsale  doorsale-demo  virtenv
faraz@MAC-PC:~/Garagespace/doorsale/doorsale$
```

**Comment by onomatopellan** [comment] 2016-08-08 22:46
Duplicate of https://github.com/Microsoft/BashOnWindows/issues/650
Fix incoming in next insider builds.

**Closed** 2016-08-09 00:27 UTC
Labels: duplicate
