### ISSUE TITLE
Broken colors when trying to display bold text

### ISSUE THREAD

**Issue by gpakosz** [Microsoft/BashOnWindows#1889] opened 2017-04-12 09:58 UTC
Steps to reproduce:
```
$ printf '\033[38;5;16m\033[48;5;226mtest\033[0m'
$ printf '\033[38;5;16m\033[48;5;226m\033[1mtest\033[0m'
```

Gives:
![image](https://cloud.githubusercontent.com/assets/553208/24952252/3b1e5e8c-1f77-11e7-9b50-44510820dc10.png)

**Comment by PhMajerus** [comment] 2017-04-13 15:27
This seems to be the same bug with the VT parser I documented here : https://github.com/Microsoft/BashOnWindows/issues/1681
If you use 256 or 24bit colors, changing another text attribute will reset the colors.

**Comment by zadjii-msft** [comment] 2017-04-13 16:32
I believe @PhMajerus is correct, this is a dupe of #1681.

Closing as such.

**Closed by zadjii-msft** 2017-04-13 16:32 UTC
Labels: console, duplicate
