### ISSUE TITLE
Problem with windows PATH being appended

### ISSUE THREAD

**Issue by ioweb-gr** [Microsoft/BashOnWindows#1453] opened 2016-12-03 19:33 UTC
Hi I noticed that the windows PATH is being appended after the linux PATH when bash starts. Also when they get appended any spaces are converted to `:` which doesn't seem right.
Also it can cause possible conflicts and presents an error during apt-get install
```
find: The relative path ‘Files’ is included in the PATH environment variable, which is insecure in combination with the -execdir action of find.  Please remove that entry from $PATH
```

PATH is: 

```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Python27:/mnt/c/Python27/Scripts:/mnt/c/bin/ruby23/bin:/mnt/c/Windows:/mnt/c/Windows/System32:/mnt/c/Windows/System32/wbem:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program:Files:(x86)/Notepad++:/mnt/c/tools:/mnt/c/Python34:/mnt/c/Program:Files/OpenSSL/bin:/mnt/c/Program:Files/Microsoft:SQL:Server/Client:SDK/ODBC/110/Tools/Binn:/mnt/c/ProgramData/Oracle/Java/javapath:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program:Files:(x86)/Windows:Kits/8.1/Windows:Performance:Toolkit:/mnt/c/Program:Files:(x86)/Universal:Extractor:/mnt/c/Program:Files:(x86)/Universal:Extractor/bin:/mnt/c/ProgramData/ComposerSetup/bin:/mnt/c/Program:Files:(x86)/GnuWin32/bin:/mnt/c/Program:Files:(x86)/NVIDIA:Corporation/PhysX/Common:/mnt/c/Program:Files:(x86)/vim/vim74:/mnt/c/Program:Files:(x86)/Livestreamer:/mnt/c/Program:Files/Microsoft:DNX/Dnvm:/mnt/c/Program:Files:(x86)/Windows:Kits/10/Windows:Performance:Toolkit:/mnt/c/Program:Files:(x86)/Microsoft:Emulator:Manager/1.0:/mnt/c/NuGet/bin:/mnt/c/Program:Files/Process:Lasso:/mnt/c/Program:Files/Samsung/AllShare:Framework:DMS/1.3.23:/mnt/c/Program:Files/Samsung/AllShare:Framework:DMS/1.3.23/64bit:/mnt/c/Users/User/AppData/Local/Android/android-sdk:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program:Files/Microsoft:SQL:Server/Client:SDK/ODBC/110/Tools/Binn:/mnt/c/Program:Files/Microsoft:SQL:Server/120/DTS/Binn:/mnt/c/Program:Files:(x86)/Microsoft:SQL:Server/120/Tools/Binn/ManagementStudio:/mnt/c/Program:Files:(x86)/Microsoft:SQL:Server/120/Tools/Binn:/mnt/c/Program:Files/Microsoft:SQL:Server/120/Tools/Binn:/mnt/c/Program:Files:(x86)/Microsoft:SQL:Server/120/DTS/Binn:/mnt/c/Users/User/AppData/Local/Android/android-sdk/tools:/mnt/c/Users/User/AppData/Local/Android/android-sdk/platform-tools:/mnt/c/Program:Files/FileBot:/mnt/c/Program:Files:(x86)/vim/vim80:/mnt/c/bin/NirLauncher/NirSoft:/mnt/c/Program:Files:(x86)/Skype/Phone:/mnt/c/Program:Files/Git/cmd:/mnt/c/HashiCorp/Vagrant/bin:/mnt/c/Program:Files/nodejs:/mnt/c/bin/ruby23/bin:/mnt/c/tools/cmder:/mnt/c/bin/cmder:/mnt/c/tools/sysinternals:/mnt/c/Program:Files/PostgreSQL/9.3/bin:/mnt/c/bin/sysinternals:/mnt/c/Program:Files/KDiff3:/mnt/c/Program:Files:(x86)/Nmap:/mnt/c/Program:Files/WindowsPowerShell/Modules/Pester/3.3.14/bin:/mnt/c/tools/mingw64/bin:/mnt/c/Users/User/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/User/.babun:/mnt/c/Program:Files/Oracle/VirtualBox:/mnt/c/Users/User/AppData/Roaming/np
```

Is there a way to completely remove the windows PATH or never append it in the first place?
I'm using 14965 build 

Thanks in advance.

**Comment by fpqc** [comment] 2016-12-04 11:29
You can manually override your PATH in your .bashrc in the mean time.

**Comment by ioweb-gr** [comment] 2016-12-04 14:48
Hi, thanks for the advice. That's what I did currently but I'm not sure if that's the proper solution. I'd also be interested in a way to switch it on/off before .bashrc is loaded so that it won't mess with applications that modify the PATH like rvm and phpbrew.

**Comment by fpqc** [comment] 2016-12-04 14:59
@ioweb it's not the right solution, but I was saying til they fix it.

**Comment by benhillis** [comment] 2016-12-05 16:35
@ioweb-gr - Something strange is going on. I have not seen this previously, could you share some additional information for me?

- Your Windows Locale
- The output of echo %PATH% from cmd
- Any interesting configuration options you can think of that you have enabled on Windows.

There is currently a registry key you can set to disable this behavior:
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss]
"AppendNtPath"=dword:00000000


```

**Comment by ioweb-gr** [comment] 2016-12-05 17:46
@benhillis  - Hi, this is the first time I saw it too. It happened as soon as I upgraded from 14931 to 14965 on the slow ring. I was assuming this feature was added in between to enable running cmd commands from wsl in the future tbh but was still experimental so I can pretty much I say I stumbled into this by accident.

 My original PATH from cmd.exe is 
`
C:\tools\cmder\bin;C:\tools\cmder\vendor\msysgit\bin;C:\tools\cmder\vendor\msysgit\mingw\bin;C:\tools\cmder\vendor\msysgit\cmd;C:\tools\cmder\vendor\msysgit\share\vim\vim74;C:\tools\cmder;C:\tools\cmder\vendor\conemu-maximus5\ConEmu;C:\tools\cmder\vendor\conemu-maximus5;C:\Python27\;C:\Python27\Scripts;C:\bin\ruby23\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\wbem;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Notepad++;C:\tools;C:\Python34\;C:\Program Files\OpenSSL\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\ProgramData\Oracle\Java\javapath;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Universal Extractor;C:\Program Files (x86)\Universal Extractor\bin;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\GnuWin32\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\vim\vim74;C:\Program Files (x86)\Livestreamer;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\NuGet\bin;C:\Program Files\Process Lasso;C:\Program Files\Samsung\AllShare Framework DMS\1.3.23\;C:\Program Files\Samsung\AllShare Framework DMS\1.3.23\64bit\;C:\Users\Gavriil\AppData\Local\Android\android-sdk;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;c:\Program Files\Microsoft SQL Server\120\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;c:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;c:\Program Files\Microsoft SQL Server\120\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Users\Gavriil\AppData\Local\Android\android-sdk\tools;C:\Users\Gavriil\AppData\Local\Android\android-sdk\platform-tools;C:\Program Files\FileBot\;C:\Program Files (x86)\vim\vim80;C:\bin\NirLauncher\Nirsoft;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\HashiCorp\Vagrant\bin;C:\tools\cmder;C:\bin\cmder;C:\tools\sysinternals;C:\Program Files\PostgreSQL\9.3\bin;C:\bin\sysinternals;C:\Program Files\kdiff3;C:\Program Files (x86)\Nmap;C:\Program Files\WindowsPowerShell\Modules\Pester\3.3.14\bin;C:\tools\mingw64\bin;C:\Users\Gavriil\AppData\Local\Microsoft\WindowsApps;C:\Users\Gavriil\.babun;C:\Program Files\Oracle\VirtualBox;C:\Users\Gavriil\AppData\Roaming\npm;C:\Program Files\MKVToolNix
`

As for my locale it's Greek (Greece)
```

PS C:\Users\Gavriil> get-winsystemlocale

LCID             Name             DisplayName
----             ----             -----------
1032             el-GR            Greek (Greece)


PS C:\Users\Gavriil>
```

About special configuration I can't really think of anything special I did other than install/uninstall a hunge number of software in the past throughout the first windows 10 build installation that I got on my hands. Pretty much everything is running in defaults.  WSL was a clean reinstall as well to update to Xenial. 

I also had cygwin installed and babun, but recently I uninstalled cygwin though before upgrading to this build. The windows PATH was appended to cygwin correctly before I uninstalled it though. I didn't even notice what the PATH was in WSL before this build and I only noticed it because of the error previously. 

If you're thinking about something more specific that might affect it, I'd be happy to provide any info you need.

**Comment by benhillis** [comment] 2016-12-06 16:40
I installed a Greek locale build of Windows and I'm not seeing this issue. I wonder if you maybe have something in your .bashrc file that's doing some processing on the $PATH variable... Could you create a new user via the "lxrun.exe /setdefaultuser" command and see if this problem reproduces for the new user?

**Comment by ioweb-gr** [comment] 2016-12-08 21:09
@benhillis Thanks, I just checked it out at length and indeed there was an entry in .bashrc created by phpbrew which caused this effect. Apparently it doesn't work well with spaces in PATH. 
It seems to be this line being executed that caused the `:` to appear instead of the spaces. 

```bash
export PATH_WITHOUT_PHPBREW=$(AR=(); for i in `echo $PATH|tr ':' ' '` ; do [[ `expr "$i" : "$PHPBREW_ROOT" 2>/dev/null` -eq 0 ]] && AR+=($i); done; echo "${AR[*]}"|tr ' ' ':';)
```

PS: The registry key you mentioned earlier worked great in my case.

**Comment by benhillis** [comment] 2016-12-08 21:27
@ioweb-gr Thanks for the info, that's what I suspected. I'm wondering if this is an issue with that path parsing command.  I've verified that bash correctly handles entries in the PATH variable that contain spaces.

**Comment by ioweb-gr** [comment] 2016-12-09 09:27
@benhillis Apparently it should be the reason causing it because `$PATH | tr ':' ' '` removes all `:` and replaces them with spaces. Then the for loop will use spaces (including spaces from folders like 'Program Files') to make the parts that make up the PATH. Then it seems it's being concatenated using `:` 

This is an error with phpbrew definitely. However since with my little experience I have never seen a linux path using spaces before in a standard distribution so I can't say if they're indeed handled correctly by every app. I'm guessing there could be a lot of apps that never even considered the possibility before so it's probably dangerous to assume everything will handle spaces correctly even though bash itself does.

**Comment by benhillis** [comment] 2016-12-09 17:59
I looked into this a bit this morning and unfortunately I don't think there's anything else we (the WSL team) can do about this.  Even if I add explicit escape characters (for example /mnt/c/Program\ Files) the above PHPBREW command still does the wrong thing. Paths with spaces are uncommon in Linux but they are allowed and this is not handling them correctly.

The best solution would be to either bug the brew folks to fix this, or disable the automatic NT path append feature via the above registry key.

Marking this as by design / workaround available.

**Closed by benhillis** 2016-12-09 17:59 UTC
Labels: bug, interop
