### ISSUE TITLE
bash hangs on mv ".."

### ISSUE THREAD

**Issue by mkiernan** [Microsoft/BashOnWindows#1901] opened 2017-04-13 03:26 UTC
Any mv command that involves a ".." in the path hangs bash every time: 

$ mv scripts_general/ ../scripts/azure

**Comment by Shadowys** [comment] 2017-04-13 03:52
I tried 
```bash
$ touch kek
$ mv kek ../ 
```
This does not hang in my system.

**Comment by fpqc** [comment] 2017-04-13 12:42
this bug is present in 1607 and fixed in 1703.

**Comment by stehufntdev** [comment] 2017-04-13 15:29
@mkiernan can you confirm your build number?  Also in the future please use the template since one of the items in the build number.

**Comment by mkiernan** [comment] 2017-04-13 17:51
Note sure if this is what you are looking for?: 
C:\Users\mkiernan>bash --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

**Comment by benhillis** [comment] 2017-04-13 17:56
@mkiernan - please run the 'ver' command from a windows command prompt.

**Comment by mkiernan** [comment] 2017-04-13 18:31
C:\Users\mkiernan>ver
Microsoft Windows [Version 10.0.14393]

**Comment by stehufntdev** [comment] 2017-04-13 20:31
Thanks for sharing out the build number.  Closing this out as a duplicate of #671 as @fpqc mentioned above.  If possible can you please update to the Creator's update where this is fixed?

**Closed by stehufntdev** 2017-04-13 20:31 UTC
