### ISSUE TITLE
setsockopt() does not support IP_MTU_DISCOVER / IP_PMTUDISC_DO.

### ISSUE THREAD

**Issue by baulig** [Microsoft/BashOnWindows#2205] opened 2017-06-09 17:01 UTC
Using Windows 10 Enterprise:
`Microsoft Windows [Version 10.0.15063]`

Ubuntu 16.04.02 LTE:
`Linux Argus 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux`

Using this test case:

    int sock, val, ret;

    sock = socket (AF_INET, SOCK_STREAM, IPPROTO_TCP);

    val = IP_PMTUDISC_DO;
    ret = setsockopt (sock, IPPROTO_IP, IP_MTU_DISCOVER, &val, sizeof (val));
    printf ("TEST: %d\n", ret);

This returns -1 in WSL, but 0 in a native Ubuntu (tested with the same 16.04).

This code is called by Mono's implementation of `Socket.DontFragment` (which is called via `Socket.SocketDefaults ()` from the constructor).

**Comment by sunilmut** [comment] 2017-06-09 17:42
@baulig - Thanks for your post and the details. This looks like a dupe of #2115. Fix is in-bound.

**Comment by sunilmut** [comment] 2017-06-22 18:23
This should be fixed in Insider build [16215(https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16215)

**Closed** 2017-07-14 18:59 UTC
Labels: duplicate, fixedininsiderbuilds, network
