### ISSUE TITLE
ulimit: error setting limit (Operation not permitted)

### ISSUE THREAD

**Issue by tucker973** [Microsoft/BashOnWindows#1686] opened 2017-02-10 14:04 UTC
Since moving from build 15019 to 15031, I receive the following error when starting Apache:

`/usr/sbin/apachectl: 87: ulimit: error setting limit (Operation not permitted)
Setting ulimit failed. See README.Debian for more information.`

It does not appear to affect Apache in any other ways, but started happening immediately after the update.

**Comment by benhillis** [comment] 2017-02-10 16:17
Adding lings to related work items: #1679 #1682 #1688

**Comment by stehufntdev** [comment] 2017-02-16 16:37
This is likely caused by an accidental regression where the RLIMIT_NOFILE checks were too strict, and that was fixed in early February. The fix should be out for insider builds soon though the rlimits are still not actually applied.

Should be straightforward to confirm if you have an strace of the failure.

**Comment by benhillis** [comment] 2017-07-12 16:59
Marking as a duplicate of #1688.

**Closed by benhillis** 2017-07-12 16:59 UTC
