### ISSUE TITLE
tail command giving me a filesystem error when tailing a directory that is on my Windows filesystem

### ISSUE THREAD

**Issue by alanosman** [Microsoft/BashOnWindows#2117] opened 2017-05-17 00:46 UTC
People of WSL - may I congratulate you on your awesome work.

I love using Ubuntu under Windows and have completely migrated all our engineering tools from Cygwin over to WSL. congrats.. it works really well.

Now, I have a small issue to report.

I have mounted linked several directories that are sitting out on my d drive to my /home/aosman/directory.

I was running one of our tools for the first time to check our database for data errors and tried to tail the log and got this error at the command line..  Tail managed to show me the end of the file (`tail -f <myfile>`) but couldn't stream the tail with the -f. 

`tail: unrecognized file system type 0x53464846 for ‘db_checkers.log.2017-05-16’. please report this to bug-coreutils@gnu.org. reverting to polling`

I'm running on production Windows 10 Pro on the latest Creators update from a month ago

**Comment by alanosman** [comment] 2017-05-17 03:19
@sunjoong is that something I have to patch manually?  I never did that before on ubuntu?  Do you know how?

**Comment by sunjoong** [comment] 2017-05-17 03:38
@alanosman - Well.... You could apply that patch to coreutil source code manually, of course; Or you could wait until your linux distribution, i.e., ununtu, maintainer will adapt that.

**Comment by benhillis** [comment] 2017-05-20 16:25
Marking as a duplicate of #925.

**Closed by benhillis** 2017-05-20 16:25 UTC

**Comment by alanosman** [comment] 2017-05-22 12:49
OK - thank's for your help.
