### ISSUE TITLE
the permissions of creating folder is strange

### ISSUE THREAD

**Issue by futureproperty** [Microsoft/BashOnWindows#1803] opened 2017-03-23 13:06 UTC
* A brief description
When I use "mkdir" in bash.exe  
![1](https://cloud.githubusercontent.com/assets/13601454/24248303/b989cc8e-1009-11e7-947f-9733959ed3e3.png)  
the permissions of tmp/ is 777,and is wrong. 
When I use "mkdir" through ssh itself  
![2](https://cloud.githubusercontent.com/assets/13601454/24248367/0b5cd60a-100a-11e7-976f-c3584aac04a9.png)  
the permissions of tmp/ is 755  

* Your Windows build number  
win10 15058.0 1703 Enterprise,and I reinstall my BUW yesterday  

* Btw,all the folder's permissions in windows partition are 777.Before I  notice this problem,i thought it is caused by mounting the windows partitions same as the share folder in virtualbox which can solved by add user to virtualbox group.  

* Sorry for my bad English

**Comment by hughbe** [comment] 2017-03-23 14:26
Dupe of #1801 :)

**Comment by jackchammons** [comment] 2017-03-23 20:07
closing as duplicate

**Closed by jackchammons** 2017-03-23 20:07 UTC
