### ISSUE TITLE
Unable to install Java JDK or Runtime

### ISSUE THREAD

**Issue by temalo** [Microsoft/BashOnWindows#49] opened 2016-04-07 22:47 UTC
Attempting to use apt-get install default-jdk (or the jre) results in several dependency failures and the package cannot be installed....

Selecting previously unselected package libx11-doc.
Preparing to unpack .../libx11-doc_2%3a1.6.2-1ubuntu2_all.deb ...
Unpacking libx11-doc (2:1.6.2-1ubuntu2) ...
Selecting previously unselected package libxt-dev:amd64.
Preparing to unpack .../libxt-dev_1%3a1.1.4-1_amd64.deb ...
Unpacking libxt-dev:amd64 (1:1.1.4-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up xorg-sgml-doctools (1:1.11-1) ...
Setting up x11proto-core-dev (7.0.26-1~ubuntu2) ...
Setting up libice-dev:amd64 (2:1.0.8-2) ...
Setting up libpthread-stubs0-dev:amd64 (0.3-4) ...
Setting up libsm-dev:amd64 (2:1.2.1-2) ...
Setting up libxau-dev:amd64 (1:1.0.8-1) ...
Setting up libxdmcp-dev:amd64 (1:1.1.1-1) ...
Setting up x11proto-input-dev (2.3-1) ...
Setting up x11proto-kb-dev (1.0.6-2) ...
Setting up xtrans-dev (1.3.5-1~ubuntu14.04.1) ...
Setting up libxcb1-dev:amd64 (1.10-2ubuntu1) ...
Setting up libx11-dev:amd64 (2:1.6.2-1ubuntu2) ...
Setting up libx11-doc (2:1.6.2-1ubuntu2) ...
Setting up libxt-dev:amd64 (1:1.1.4-1) ...
Setting up openjdk-7-jre-headless:amd64 (7u95-2.6.4-0ubuntu0.14.04.2) ...
the java command requires a mounted proc fs (/proc).
dpkg: error processing package openjdk-7-jre-headless:amd64 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of default-jre-headless:
 default-jre-headless depends on openjdk-7-jre-headless (>= 7~u3-2.1.1); however:
  Package openjdk-7-jre-headless:amd64 is not configured yet.

dpkg: error processing package default-jre-headless (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
dpkg: dependency problems prevent configuration of openjdk-7-jre:amd64:
 openjdk-7-jre:amd64 depends on openjdk-7-jre-headless (= 7u95-2.6.4-0ubuntu0.14.04.2); however:
  Package openjdk-7-jre-headless:amd64 is not configured yet.

dpkg: error processing package openjdk-7-jre:amd64 (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.dpkg: dependency problems prevent configuration of default-jre:
 default-jre depends on default-jre-headless (= 2:1.7-51); however:
  Package default-jre-headless is not configured yet.

dpkg: error processing package default-jre (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached alreadydpkg: dependency problems prevent configuration of openjdk-7-jdk:amd64:
 openjdk-7-jdk:amd64 depends on openjdk-7-jre (= 7u95-2.6.4-0ubuntu0.14.04.2); however:
  Package openjdk-7-jre:amd64 is not configured yet.

dpkg: error processing package openjdk-7-jdk:amd64 (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
dpkg: dependency problems prevent configuration of default-jdk:
 default-jdk depends on default-jre (= 2:1.7-51); however:
  Package default-jre is not configured yet.
 default-jdk depends on openjdk-7-jdk (>= 7~u3-2.1.1); however:
  Package openjdk-7-jdk:amd64 is not configured yet.

dpkg: error processing package default-jdk (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
dpkg: dependency problems prevent configuration of ca-certificates-java:
 ca-certificates-java depends on openjdk-7-jre-headless (>= 7~u3-2.1.1~pre1-1) | java6-runtime-headless; however:
  Package openjdk-7-jre-headless:amd64 is not configured yet.
  Package java6-runtime-headless is not installed.
  Package default-jre-headless which provides java6-runtime-headless is not configured yet.
  Package openjdk-7-jre-headless:amd64 which provides java6-runtime-headless is not configured yet.

dpkg: error processing package ca-certificates-java (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
Errors were encountered while processing:
 openjdk-7-jre-headless:amd64
 default-jre-headless
 openjdk-7-jre:amd64
 default-jre
 openjdk-7-jdk:amd64
 default-jdk
 ca-certificates-java
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by jznomoney** [comment] 2016-04-07 22:49
I myself have the same issue

**Comment by mphaney** [comment] 2016-04-07 22:52
I've had the same issue as well.  After spending way too long messing around with dpkg, and manual installations, I THINK this issue is ultimately being caused by tar's inability to handle symlinks correctly right now (Issue #9), as other packages suffer similar problems as Java.  I'm sure there's probably more too it than just that, though.

**Comment by wangweij** [comment] 2016-04-08 05:27
I am seeing the same problem in installation, and I also noticed:

1. This is not a symlink issue. ls -al inside /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/ shows the symlink is correctly created.

2. I can run /usr/lib/jvm/java-7-openjdk-amd64/bin/javac directly (yes, I installed jdk) and the help screen shows up.

3. However, running "/usr/lib/jvm/java-7-openjdk-amd64/bin/javac A.java" with a super-slim A.java hangs forever. Even Ctrl-C cannot kill it.

**Comment by carloshm** [comment] 2016-04-09 12:01
I see openjdk failing but through ca-certificates-java package and it seems due not seeing /proc as a mountpoint.

root@localhost:/# mountpoint /proc
/proc is not a mountpoint

**Comment by markgross** [comment] 2016-04-09 13:59
I get this issue as well while attempting to set up for building Android.  http://source.android.com/source/initializing.html#setting-up-a-linux-build-environment

**Comment by jznomoney** [comment] 2016-04-09 14:07
I tried manually installing java 7 from oracle mentioned on this page: http://xubuntugeek.blogspot.com/2012/09/how-to-install-oracle-jdk-7-manually-in.html
When I execute the command: sudo tar -zxvf jdk*.tar.gz -C /usr/lib/jvm/
I get this error:
tar: jdk1.7.0_80/jre/lib/amd64/server/libjsig.so: Cannot create symlink to ‘../libjsig.so’: Invalid argument
tar: Exiting with failure status due to previous errors

**Comment by jhl9092** [comment] 2016-04-10 08:29
I have the same issue as well. I tried to install openjdk-7-jdk, and the default-jdk, but get the error at the end. I can actually navigate to /usr/lib/jvm/ and see all folders, and also I can set the JAVA_HOME to check the java version and javac version. I tried the same thing as wangweij and ran javac, which showed help. But, again, javac test.java hangs. (You can kill it by Ctrl+z however.) Test file was a hello world.

**Comment by Esgariot** [comment] 2016-04-11 17:03
Did someone manage to install java from source and run
"java -version  "?
Unfortunately it just freezes in my case

**Comment by wangweij** [comment] 2016-04-12 04:16
@Esgariot what does it mean install from source? compile?
@jznomoney this is a known problem #9, but you can manually recreated it.

**Comment by zouyonghao** [comment] 2016-04-12 17:06
I installed oracle JDK 1.7 successfully. Just download and extract it on windows, put it in your Linux folder, then will be OK.


![capture](https://cloud.githubusercontent.com/assets/7647081/14468796/ed4869dc-0113-11e6-953e-3954d248d0f3.PNG)

**Comment by russalex** [comment] 2016-04-12 22:39
Thanks all.  I was able to follow these instructions and get java up and running:  [http://xubuntugeek.blogspot.com/2012/09/how-to-install-oracle-jdk-7-manually-in.html](http://xubuntugeek.blogspot.com/2012/09/how-to-install-oracle-jdk-7-manually-in.html).

To do this, I downloaded jdk-8u77-linux-x64.tar.gz to /mnt/c/temp and installed to /usr/lib/jvm/.  Successfully ran a very simple HelloWorld app.

```
russ@RUSSALEX-DESK:/mnt/d/dev/samples/java$ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
russ@RUSSALEX-DESK:/mnt/d/dev/samples/java$ java HelloWorldApp
Hello World!
russ@RUSSALEX-DESK:/mnt/d/dev/samples/java$
```

That said, we obviously have a bug against the install.  Writing that one now.

**Comment by nshanny** [comment] 2016-04-13 19:00
Russ - are you running a later version of the linux subsystem or what has been released publicly? I cannot get java to run no matter what I do.  It just hangs.

**Comment by russalex** [comment] 2016-04-13 21:13
This test was a developer build.  Can't give an ETA (simply because I don't have one to give) but fixes should be heading down the pipe soon.

**Comment by seancorfield** [comment] 2016-04-14 01:39
@russalex Good to hear there are fixes coming. If, in trying to resolve various `apt-get` failures on various packages, we've gotten Ubuntu into a bit of a mess, is there an easy way to uninstall & reinstall it or reset it to the pristine version that Windows 10 first installs?

**Comment by benhillis** [comment] 2016-04-14 01:42
Yep sure is. I think it's in our FAQ but I'm on my phone so I don't have a link. Do the following:

Lxrun.exe /uninstall /full

Then reinstall with Bash.exe

**Comment by sunilmut** [comment] 2016-04-14 02:40
@seancorfield Here are the instructions if you are still looking for them. [How do I fully uninstall WSL?](https://msdn.microsoft.com/en-us/commandline/wsl/faq)

**Comment by seancorfield** [comment] 2016-04-14 02:41
Thank you @sunilmut -- somehow I'd missed the FAQ completely.

**Comment by mphaney** [comment] 2016-04-14 15:17
@russalex Since you've got Java 8 up and running now, any chance you could test Gradle (gradle.org) that builds on top of it?  It's basically just a glorified wrapper, some fancy jar files...but still.  I managed to get Java 7 running on the current public build, but no dice for Gradle.  I use them both at work and would LOVE to have them both up and running without having to go through another release/report/fix/wait cycle.

Thank you all **so** very much for your hard work!

**Comment by russalex** [comment] 2016-04-22 20:48
Build 14328 is now public.  You should be able to get Java working using the manual commands under a non-mnt/drive directory.

Release notes are here: https://msdn.microsoft.com/en-us/commandline/wsl/release_notes and contain a link to the instructions I followed to get Java up and going.

**Comment by jhl9092** [comment] 2016-04-23 07:24
It is still not working for me on 14328. I reinstalled bash and tried again, but still no luck. It hangs at "java -version". I downloaded the jdk to c directory on windows, did the tar command to the /usr/lib/jvm/ from /mnt/c, then followed the instruction on the website.

**Comment by markgross** [comment] 2016-04-23 10:51
Can you strace the Java -version execution?  I wonder were it's hanging?

**Comment by amadib** [comment] 2016-04-23 16:53
I saw issue yesterday and updated to 14328.rs1_release.160418-1609 and tried reinstalling this morning first following these [instructions](http://tecadmin.net/install-oracle-java-8-jdk-8-ubuntu-via-ppa/) where it's spitting out a bunch of errors. http://www.pastebucket.com/313262

I then tried to use the [instructions]( http://xubuntugeek.blogspot.com/2012/09/how-to-install-oracle-jdk-7-manually-in.html) @russalex posted above and it hangs on `java -version`. 
I ran `strace java -version` and here's the output: http://www.pastebucket.com/313261

**Comment by cuzox** [comment] 2016-04-23 20:27
After uninstalling wsl and following this: 
https://www.digitalocean.com/community/tutorials/how-to-manually-install-oracle-java-on-a-debian-or-ubuntu-vps

with jdk 7 it worked. Mine would hang as well.

**Comment by markgross** [comment] 2016-04-23 21:08
is the strace complete?  the last line is not a full line:
"futex(0x7ff5ffe209d0, FUTEX_WAIT, 7295, NULL"

I would say futex's are buggy but, earlier in the trace shows a futex call
working.

Hmmm, the earlier call doesn't show a well functioning futext:
"futex(0x7ff5fffef690, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1,
NULL, 7ff5ffeb0740) = -1 EAGAIN (Resource temporarily unavailable)"

I am wondering if the futext sys call is not well implemented and hangs or
maybe java is deadlocking on the second attempt at calling futext...

If there are any dev's following this thread can we get a report out of
what sys-calls are tested / thought to be working in windows/linux
subsystem?  (I guess I can try to run part of the LTP to see a partial
list).

--mark



On Sat, Apr 23, 2016 at 1:27 PM, Caleb Viola <notifications@github.com>
wrote:

> After uninstalling wsl and following this:
>
> https://www.digitalocean.com/community/tutorials/how-to-manually-install-oracle-java-on-a-debian-or-ubuntu-vps
>
> with jdk 7 it worked. Mine would hang as well.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/BashOnWindows/issues/49#issuecomment-213825506>
>



-- 
create interesting things.

**Comment by amadib** [comment] 2016-04-23 21:48
I uninstalled and reinstalled wsl and followed @cuzox instructions only upping the version to 8u91 and still hangs when I run `java -version`
http://www.pastebucket.com/313830

**Comment by ianvieira** [comment] 2016-04-23 21:52
I'm having the same problem that @amadib installing java in the newest build (14328) following @russalex installation step-by-step. Here is the tracelog for `java -version`: http://www.pastebucket.com/313831

**Comment by amadib** [comment] 2016-04-23 22:24
@ianvieira I installed java 7 not sure if it works yet...@cuzox can you try to run./gradlew and see if works for you? I'm having a crash now with that...

**Comment by ianvieira** [comment] 2016-04-23 22:39
@amadib in fact the Java 7 works using @russalex installation. But I'm not sure if I can use Java 7 in my environment.

**Comment by jhl9092** [comment] 2016-04-24 03:35
Here is my strace, http://pastebucket.com/314592
I saw that futex was hanging, so I tried the strace with the -f option to trace the child, and it actually finished.. There's a SIGSEGV at the end, but I'm not sure the significance of this... but here it is: http://pastebucket.com/314613

**Comment by seancorfield** [comment] 2016-04-26 06:35
I tried JDK 8u92 and reproduced the `java -version` hang. I tried JDK 7u79 and that seems to work fine.

**Comment by benhillis** [comment] 2016-04-29 22:17
FYI: I've fixed the issue preventing default-jdk from installing (the java command requires a mounted proc fs (/proc)).  The fix will be making its way to the Windows Insider fast ring in the next few weeks.  Keep an eye out for our release notes.

**Comment by markgross** [comment] 2016-04-29 22:51
Excellent :)

**Comment by rs6g10** [comment] 2016-05-05 22:23
As per comment from @russalex , I managed to install it manually. Here are the steps for those who wants a full walkthrough:
# Installing Oracle JDK Java SE Development Kit 8 x64 bits
**Download Oracle JDK**
```
wget --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
```

Then...

```
sudo su
```
The /opt directory is reserved for all the software and add-on packages that are not part of the default installation. Create a directory for your JDK installation:
```
mkdir /opt/jdk
```
and extract java into the /opt/jdk directory:
```
tar -zxf jdk-8u5-linux-x64.tar.gz -C /opt/jdk
```
Verify that the file has been extracted into the /opt/jdk directory.
```
ls /opt/jdk
```
**## Setting Oracle JDK as the default JVM**
In our case, the java executable is located under /opt/jdk/jdk1.8.0_05/bin/java . To set it as the default JVM in your machine run:
```
update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_05/bin/java 100
```
and
```
update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_05/bin/javac 100
```

**Verify your installation**
Verify that java has been successfully configured by running:
```
update-alternatives --display java
```
Output should look like this:
```
java - auto mode
link currently points to /opt/jdk/jdk1.8.0_05/bin/java
/opt/jdk/jdk1.8.0_05/bin/java - priority 100
Current 'best' version is '/opt/jdk/jdk1.8.0_05/bin/java'.
```
and then run this
```
update-alternatives --display javac
```
Output should look like this:
```
javac - auto mode
link currently points to /opt/jdk/jdk1.8.0_05/bin/javac
/opt/jdk/jdk1.8.0_05/bin/javac - priority 100
Current 'best' version is '/opt/jdk/jdk1.8.0_05/bin/javac'.
```
And Finally!
```
java -version
```
Output should look like this:
```
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
```

![image](https://cloud.githubusercontent.com/assets/1889234/15058026/d4062706-1311-11e6-9035-cdcfd3a0009a.png)

**Comment by amadib** [comment] 2016-05-07 15:43
@rs6g10 does it work? can you run maven or gradle?

**Comment by sg4j** [comment] 2016-05-15 02:54
Java appears to work with steps mentioned above. When I say WORK, "java -version" returns the Java version but that's about it. When I tried executing a Sping boot JAR from command line (java -jar springboot.jar), the system just got STUCK with no output and I had to kill the bash shell. I am on build 14342.rs1_release.

![springboot_bash](https://cloud.githubusercontent.com/assets/19189254/15271756/c22d2bc6-1a26-11e6-87c1-24209f96e5ba.JPG)

**Comment by mphaney** [comment] 2016-05-16 16:11
@amadib I just tried it on mine (Insider build 14342). java/javac 8u5 _does_ seem to run alright, and I can compile and run the most basic Hello World program both as a bare class file AND as a jar file, but even so, Gradle does NOT work (tried versions 2.4, 2.5 and 2.12).  Just hangs like newer versions of Java do.  Really wish this ran, then I could actually start using Bash for my development :-)

**Comment by russalex** [comment] 2016-05-26 22:49
Everyone should be able to run apt-get install default-jre on build [14352](https://blogs.windows.com/windowsexperience/2016/05/26/announcing-windows-10-insider-preview-build-14352/).

This build fixes quite a few issues.  I have not tried Gradle but it's worth giving another shot.

**Comment by seancorfield** [comment] 2016-05-27 05:08
Confirmed: installed `default-jre` and `default-jdk` smoothly and I can now run Leiningen (Clojure build tool) for certain tasks, but _not_ `lein repl` to produce an interactive REPL unfortunately, and Boot (the other main Clojure build tool) still hangs on every action. But this is definitely a big improvement -- thank you!

**Comment by mphaney** [comment] 2016-05-27 15:44
@russalex Indeed, apt-get install default-jdk works beautifully!  This is a fantastic update and much smoother.

Gradle, unfortunately, still hangs :-/  Tried versions 2.4 up through 2.13 (the current version), all with the same behavior.  I would be happy to run any command or provide any further feedback that might help.  Thank you for everyone's extremely hard work!

**Comment by mphaney** [comment] 2016-05-27 17:09
Update: It's worth noting that I just tried `sudo apt-get install gradle` and it DID install without a hitch.  `gradle -v` correctly displays the version (painfully old 1.4).  Actually trying to use it on our project, however, just hangs like always.  It's for the old-version reason that I would really love for newer versions of Java/Gradle from the developer's sites to correctly run.

**Comment by seancorfield** [comment] 2016-05-27 17:35
@mphaney Since this issue is considered "fixed" as far as Java is concerned, maybe updating #196 and focusing on that for Gradle is worthwhile? I did the same thing for Leiningen / Boot (Clojure's build tools) in #277 (no response yet from @russalex et al -- hint, hint 😄 ).

**Comment by dtracers** [comment] 2016-05-30 15:29
I am installing open-jdk using these instructions
http://ubuntuhandbook.org/index.php/2015/01/install-openjdk-8-ubuntu-14-04-12-04-lts/

And it hanged updating alternatives:
```
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
```

(well I am going to let it sit to see if it ever times out or completes)

But it went much further than it has ever done before!

**Comment by russalex** [comment] 2016-05-31 19:03
This thread has forked a number of times.  Let's do the following:

- Closing this one as "fixed" since apt-get install jre/jdk default is working.
- Let's use #196 for Gradle support
- Oracle JDK SE is working following @rs6g10's instructions above but has issues installing from apt-get (instructions below).  #315 is tracking that one.

	$ sudo add-apt-repository ppa:webupd8team/java
	$ sudo apt-get update
	$ sudo apt-get install oracle-java8-installer

**Closed** 2016-06-08 18:49 UTC
Labels: bug, fixed, fixinbound

**Comment by amadib** [comment] 2016-06-22 21:37
Not sure if we should reopen this or create a new issue but trying to add the repository I get the following:
```
$ sudo add-apt-repository ppa:webupd8team/java
Cannot add PPA: 'ppa:webupd8team/java'.
Please check that the PPA name or format is correct.
```

**Comment by shuxin** [comment] 2016-08-20 15:58
me too.
I think this bug may like that one（#https://bugzilla.kernel.org/show_bug.cgi?id=32922#）

**Comment by jackchammons** [comment] 2016-12-14 23:34
Tracking Gradle errors in #851

**Comment by Triamus** [comment] 2017-09-13 18:39
@rs6g10 many thanks!!
