### ISSUE TITLE
Unable to type @ on a French keyboard

### ISSUE THREAD

**Issue by ILPlais** [Microsoft/BashOnWindows#140] opened 2016-04-11 22:58 UTC
Hello,
On an French AZERTY keyboard, each time I try to type `@` with the key combination `AltGr+à`, I only got a sound.

**Comment by russalex** [comment] 2016-04-12 01:07
Looks like a duplicate of #11.

We know about this one and have someone on it.

**Closed by russalex** 2016-04-12 01:07 UTC

**Comment by wpostma** [comment] 2016-04-12 10:46
What are the values of your LANG and TERM environment variables?  Try finding ones that work for French AZERTY keyboards.
