### ISSUE TITLE
Nano became unusable while scrolling inside a file

### ISSUE THREAD

**Issue by yupal** [Microsoft/BashOnWindows#72] opened 2016-04-08 15:29 UTC
When opening and scroll inside a file in nano the lines overlaps each other.

Here is a small video with the issue:

http://screencast.com/t/MibsLFMn7

**Comment by zadjii** [comment] 2016-04-08 17:35
This looks like a dupe of #27 to me.

**Comment by russalex** [comment] 2016-04-25 21:18
Closing out this one as a dup of #27.

**Closed by russalex** 2016-04-25 21:18 UTC
Labels: console, duplicate
