### ISSUE TITLE
MLton crashes and BSODs

### ISSUE THREAD

**Issue by gyf304** [Microsoft/BashOnWindows#847] opened 2016-08-10 03:46 UTC
MLton crashes on launch and causes BSOD (LXCORE.SYS)

Steps to reproduce:
install mlton
run mlton (multiple times)

Windows Version 1607 Build 14393.10

**Comment by iz0eyj** [comment] 2016-08-10 07:04
Same on 14393.67

**Comment by benhillis** [comment] 2016-08-10 15:32
I'll give this a try this morning to see what's goin on.  Are you just using the MLton package from apt?

Thanks,
Ben

**Comment by iz0eyj** [comment] 2016-08-10 16:04
@benhillis yes Ben, it install this and crashed at the first run.
If you need I have the memory.dmp (2.1 GB)
![cattura](https://cloud.githubusercontent.com/assets/6331284/17561094/d3ea0df0-5f24-11e6-9bc3-6e5f971cd0b4.JPG)

**Comment by benhillis** [comment] 2016-08-10 17:02
@iz0eyj Thanks, I have a repro locally and I'm debugging it.

**Comment by iz0eyj** [comment] 2016-08-10 17:11
Please fix right, and test test test... a BSOD from WSL is worrying :)

**Comment by benhillis** [comment] 2016-08-11 00:26
I've root caused the issue and the fix is in code review.  The issue is with the mmap system call when a base address was specified without the MAP_FIXED flag.  We handle MAP_FIXED correctly but were missing some validation if MAP_FIXED was not supplied.

Thanks a bunch for reporting this!

**Comment by gyf304** [comment] 2016-08-11 18:21
Thanks!

**Comment by gyf304** [comment] 2016-08-16 09:47
A quick follow up:
I found c0 compiler BSODing as well. 
http://c0.typesafety.net/downloads.html
Simply download the tarball and run 'cc0' in the bin directory.

It's likely that both BSODs share the same root cause.

**Comment by benhillis** [comment] 2016-08-16 21:06
@gyf304 yes you are correct.  I downloaded the tarball and ran ./cc0 and verified it was hitting the same issue.

**Comment by russalex** [comment] 2016-08-31 21:10
Looks to be fixed in build 14915 (next release Insider Fast).

I tested both Mlton and c0.  Everything looked good.

**Closed** 2016-09-07 21:27 UTC
Labels: bug, fixed, fixinbound
