### ISSUE TITLE
Anaconda's scipy.test() fails with "OMP: Error #100: Fatal system error detected

### ISSUE THREAD

**Issue by Evfro** [Microsoft/BashOnWindows#785] opened 2016-08-05 17:48 UTC
- A brief description

SciPy is a python package for scientific computing. Normally it's installed with Anaconda distribution, that also ships Intel's MKL library (with LAPACK and BLAS routines).
- Expected results

Executing `scipy.test()` from within python completes with the report on all errors and failures discovered.
- Actual results (with terminal output if applicable)

`scipy.test()` doesn't complete and terminates python with the following error:

```
OMP: Error #100: Fatal system error detected.
OMP: System error #22: Invalid argument
Aborted (core dumped)
```
- Your Windows build number

Microsoft Windows [Version 10.0.14393]
- Steps / commands required to reproduce the error

Run from terminal:

``` bash
python -c 'import scipy; scipy.test()'
```
- Strace of the failing command

https://gist.github.com/Evfro/2d0d83745a92d3f6e2f52ce3675a273d

The last thing before error there is the following line:
`sched_getaffinity(0, 4, 0x7fc7757a7e00) = -1 EINVAL (Invalid argument)`
- Required packages and commands to install

Install latest miniconda (Python 2.7):

``` bash
wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
bash Miniconda*.sh
```

Update apt-get (prevents some errors):

``` bash
sudo apt-get update -qq
```

Install scipy, numpy and nose (for running tests):

``` bash
conda install numpy scipy nose
```

This will additionally install MKL and libgfortran-3. 
**Note**: test doesn't fail if _nomkl_ versions of numpy and scipy are installed, however, MKL (especially its LAPACK and BLAS) is required for some other packages, so it's not really an option.

**Comment by deto** [comment] 2016-08-05 18:58
Which packages is MKL required for?  As far as I know, it was only added recently to their free-tier Linux installer so most things should work fine with nomkl.

**Comment by Evfro** [comment] 2016-08-05 19:09
For example, this ones fails at compilation time with exactly the same error (and it's not possible to install w/o MKL):
https://github.com/oseledets/ttpy
I guess, there could be many more scientific computing projects, that also rely on MKL's BLAS and LAPACK.

**Comment by Evfro** [comment] 2016-08-05 19:39
Sorry, my last comment was wrong. TTpy packages doesn't fail at compile time, but it fails when some functions are called (for example, tt.tensor).

What I've found is that setting environmental variable KMP_AFFINITY=disabled resolves the problem. However, I have no idea what implications it might have and not sure whether it's acceptable workaround.

**Comment by srinath29** [comment] 2016-08-06 02:48
Yeah.. And all the packages built on top of it. I was using statsmodels.api.GLSAR and it was also failing with the same problem. I opened a bug in statsmodels
https://github.com/statsmodels/statsmodels/issues/3142

**Comment by srinath29** [comment] 2016-08-07 07:29
Any solutions ? I am little anxious as one of my work depends on it.

**Comment by deto** [comment] 2016-08-07 07:56
If nobody has a fix and you really need it, you might want to just run
Ubuntu in a VM.  I've installed Anaconda with MKL doing this before.  Not
as optimal as Bash on Windows but it'll get you moving.

You can also run much of the data science stack in Windows (not Bash) just
fine using Anaconda.

**Comment by srinath29** [comment] 2016-08-07 12:18
Thanks for the suggestion. I am already doing that. Actually I am in final stages of development of a benchmark https://github.com/srinath29/UltimateAnalyticsBenchmark 
I want to test it on Bash on windows and I have score of running it natively on windows also. So I am bit curious.

**Comment by Evfro** [comment] 2016-08-07 12:29
Have you tried setting KMP_AFFINITY=disabled?  Does it really kills performance? I haven't tested yet, would be interesting to see.

**Comment by srinath29** [comment] 2016-08-07 13:38
@Evfro 
Hey... It is working!!!!! 
These are the results
![cmd]
(https://1drv.ms/i/s!AgSQkXl7QkxTguxt-A5-plKjEwV9dw)
![bash]
(https://1drv.ms/i/s!AgSQkXl7QkxTguxu0MgLTHYhGTzeqw)

See the score at the bottom. Bash is performing better than windows. Now I am not sure it is because making it disabled or it's bash's power. Can you do the same test on your system? I am very curious to see how it is working. 
I think this should be labeled as workaround .

**Comment by Evfro** [comment] 2016-08-09 07:24
@srinath29 
I haven't closely looked into your code, but the thing to keep in mind when measuring time is that some python time-measuring functions behave differently on Linux and Windows. The most reliable way I found is to use
```python
from timeit import default_timer
```

Now, that said, I can confirm that there are performance differences in certain types of operations.
For example, this simple code
```python
a = numpy.random.random((10000, 10000))
%timeit a.mean()
```
gives me on average 52ms on bash and 133ms on windows.

However, more involved calculations like computing sparse SVD (scipy.sparse.linalg.svds) give me roughly equal results: 151ms on bash against 156ms on windows (for 6040 by 3706 matrix with 99% sparsity).

And while this KMP_AFFINITY thing does the trick, I would really like to hear from core developers team of BashOnWindows whether this is an appropriate modification (and whether it can be made default without additional user actions). From [Intel's website](https://software.intel.com/en-us/node/522691): "Thread affinity is supported on Windows systems and **versions of Linux systems that have kernel support for thread affinity**..." So the problem can be either due to a bug or due to a kernel-level limitation.

**Comment by davidghiurco** [comment] 2016-10-18 23:32
does anyone know if there's a fix other than disabling MKL affinity? I'm using a numpy/scipy stack for one of my classes and i develop on Bash for windows and am wondering if there's any fix for this or if I still have to do it the hacky way (and can rest assured that unless professor runs BashOnWindows too, he won't get this error)

**Comment by scienceopen** [comment] 2016-11-19 22:23
suggest CLOSE this issue as it was resolved with Build 14936 and installing new default Ubuntu 16.04

**Comment by davidghiurco** [comment] 2016-11-19 22:37
how to get this build for Bash for Windows? or is it installed automatically with Windows update?

**Comment by scienceopen** [comment] 2016-11-19 22:42
You need Windows 14936 or newer, and no it will not autoupgrade, even when you get the latest build.
To upgrade WSL from Ubuntu 14.04 to Ubuntu 16.04, from **Windows Command Prompt**

    lxrun /uninstall
    lxrun /install

That erases everything but your home directory (in the Ubuntu lxss folder) so backup anything you might need.

**Comment by deto** [comment] 2016-11-19 23:33
Can't you also run do-release-upgrade?  So you don't lose all your files?

**Comment by scienceopen** [comment] 2016-11-19 23:59
Some people do that, I wanted a clean start.

**Comment by bklooste** [comment] 2016-11-20 09:51
Same with CNTK ., KMP_AFFINITY=disabled  made it work

**Comment by stehufntdev** [comment] 2017-01-06 18:08
Closing this per the comment above, please let us know if there are any regressions in this scenario:

"suggest CLOSE this issue as it was resolved with Build 14936 and installing new default Ubuntu 16.04"

**Closed by stehufntdev** 2017-01-06 18:08 UTC
Labels: fixed, python

**Comment by grayskripko** [comment] 2017-05-25 11:20
@scienceopen it is possible to upgrade Ubuntu 14 to 16
According to https://media.readthedocs.org/pdf/wsl-guide/latest/wsl-guide.pdf

> You can also upgrade to the latest version of Ubuntu with the following command (caution, this will take quite some time)!:
> $ sudo -S apt-mark hold procps strace sudo
> $ sudo -S env RELEASE_UPGRADER_NO_SCREEN=1 do-release-upgrade

I've got 16.04 on my machine after these steps
