### ISSUE TITLE
javac on BashOnWindows

### ISSUE THREAD

**Issue by ricardosantos9521** [Microsoft/BashOnWindows#566] opened 2016-06-22 20:17 UTC
After the update for the build 14367 the javac doesn't compile anymore. Please solve this.

**Comment by benhillis** [comment] 2016-06-22 20:35
@ricardosantos9521 Thank you for reporting this issue. Could you share some more information with me please?

1. What is the location of the javac source you are compiling?
2. What build command are you running?
3. What errors are you seeing?

**Comment by ricardosantos9521** [comment] 2016-06-22 21:15
First i instal the default-jdk
The file is c/dev
i run javac tree.java to compile as i do on "real" ubuntu
doesn't appear any error just do not compile

**Comment by therealkenc** [comment] 2016-06-22 21:46
Java compile requires the java runtime itself further down it's bootstrapping process. JRE is known to hang because one of the subprocesses goes into a loop and a futex blocks forever (#541). I complied IcedTea on native Ubuntu and copied the tree over to WSL to try and track down why, but I couldn't get gdb running (it's a tough enough slog in the best of circumstances) and gave up before long. JRE tortures pretty much every syscall under the sun so it seems premature to try tackling such a big a codebase while there remains known unimplemented syscall surface. I am pretty sure it is a shm/signal/lock/wait pthready thing, but that doesn't tell Ben much.

**Comment by mvallu** [comment] 2016-06-26 03:22
I tried the same with openjdk 7 with simple helloworld program, and it hangs. Had to close the terminal and restart again.

**Comment by therealkenc** [comment] 2016-06-26 05:23
If you don't want to close the terminal you can hit `Ctrl-Z` (SIGTSTP) and then kill the process with a SIGKILL. I don't know why it doesn't trap `Ctrl-C` (SIGINT).

**Comment by mvallu** [comment] 2016-06-26 05:30
Ctrl-Z did work, but not sure why Ctrl-C wasn't working. Probably its not implemented yet?

**Comment by therealkenc** [comment] 2016-06-26 23:36
Yeah I should have been more explicit. I was meaning it is on-topic because SIGINT works in general. Whatever is hosing JRE apps that use (as of this writing ) unknown constructs hoses it good. I tried to track it to a concrete test case but stracing all of the javac threads is a bear.

**Comment by gilzamir** [comment] 2016-06-29 14:21
I also can not run javac in bash for windows. Is there any solution to this problem?

**Comment by therealkenc** [comment] 2016-06-29 14:58
Workaround @leninalive posted in #541 seems to solve.

**Comment by mvallu** [comment] 2016-06-29 15:34
Yep. That worked as of now.

**Comment by philharmonikerzzy** [comment] 2016-07-06 20:26
Does this issue share the same cause as that of not being able to run maven for bash for windows? They seem to hang in the same way.

**Comment by benhillis** [comment] 2016-09-11 15:55
Marking as duplicate of #746.

**Closed by benhillis** 2016-09-11 15:55 UTC
Labels: bug
