### ISSUE TITLE
a bash console window can not be closed with the X button when others are open (build 14946)

### ISSUE THREAD

**Issue by xilun** [Microsoft/BashOnWindows#1208] opened 2016-10-15 13:31 UTC
* A brief description

When two (or more) "Bash on Windows" console windows are open, clicking on the X button of one has no immediate effect. (But if one clicks an the X button of all "Bash on Windows" console windows, they are all closed when the last X button has been clicked.)

* Expected results

The console windows closes as soon as its X button has been clicked, even if there are other open "Bash on Windows" console windows.

* Your Windows build number

14946

* Steps / All commands required to reproduce the error from a brand new installation 

Launch one "Bash on Windows" console window, click on X => it is closed (expected behavior)

Launch two new "Bash on Windows" console windows, click on X on one of those. It is not closed. Click on X on the second one. Both are closed on the second click.

**Comment by fpqc** [comment] 2016-10-15 15:01
Confirmed

**Comment by zadjii-msft** [comment] 2016-10-17 14:50
This is a dupe of #1187. Closing as such.

**Closed by zadjii-msft** 2016-10-17 14:50 UTC
Labels: duplicate
