### ISSUE TITLE
Blank Screen when Starting Up

### ISSUE THREAD

**Issue by Q-Mart** [Microsoft/BashOnWindows#2352] opened 2017-07-18 08:37 UTC
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Version 10.0.15063

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I've been using Bash On Ubuntu On Windows for about a month now with no issues. This morning I started my computer up and was greeted with a blank terminal that eternally hangs

![image](https://user-images.githubusercontent.com/9257129/28307918-75060caa-6b9c-11e7-9f8b-936001676f01.png)

I'm using wsltty but this is the same case in the Bash On Ubuntu On Windows program, or running bash from Powershell or cmd. I've restarted my PC but there is no change.

* What's wrong / what should be happening instead:

After I few seconds, I'm usually greeted by a prompt that asks for my ssh key passcode but this is not the case.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

Cannot run strace as I cannot run bash

See [our contributing instructions](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment] 2017-07-18 10:07
I once had this happen to me, and it was fixed by rebooting.  Have you tried that?

**Comment by Q-Mart** [comment] 2017-07-18 14:03
Yes I've tried restarting but no luck

**Comment by Q-Mart** [comment] 2017-07-18 16:17
I've managed to fix this by disabling WSL and then re-enabling it. Regardless, this is still a bug so can it please be looked into?

**Comment by fpqc** [comment] 2017-07-18 16:24
I'm sure it will be looked into, but it would have been better to leave it broken so you could generate traces for the team. I dunno how you'll be able to do it now.

**Comment by benhillis** [comment] 2017-07-18 19:04
As @fpqc said, without repro steps or traces this is going to be impossible to diagnose.  If you manage to get yourself into this situation again could you please collect logs?

https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md#8-detailed-logs

**Closed by benhillis** 2017-07-18 19:04 UTC

**Comment by Q-Mart** [comment] 2017-07-19 08:27
@benhillis how do you recommend I collect logs?

**Comment by fpqc** [comment] 2017-07-19 08:58
@Q-Mart it tells you precisely how to do it in his link

**Comment by tman540** [comment] 2018-08-23 20:15
I discovered that disabling windows subsystem for Linux, rebooting, re-enabling it, then rebooting once more solved the issue, for me at least.

**Comment by Kurgol** [comment] 2019-05-20 10:26
I am having exactly this issue with WSL and Ubuntu 18.04 image from the MS Store. Running Version 1809 (build 17763.503).

Attached logs as requested by @benhillis.

[blacnk-screen-when-starting-up-#2352.zip](https://github.com/microsoft/WSL/files/3197385/blacnk-screen-when-starting-up-.2352.zip)

**Comment by pmsanford** [comment] 2019-06-03 17:30
I have this problem intermittently as well - for a me a restart always fixes it. Only started happening for me after the first fast ring update since the last release (`Microsoft Windows [Version 10.0.18908.1000]`)

**Comment by sna-scourtney** [comment] 2019-07-17 19:13
I've used bash successfully since early 2017, but today I accidentally clicked the right mouse on the pinned Ubuntu icon on my taskbar and accidentally hit one of the context menu options -- but I didn't see which one. Now bash is a black screen that appears to be hung, for me. Obviously I somehow broke it, but I don't know how.

In any case, I figured out what's actually happening within my session, and I'm hoping that helps others.

The bash window is not actually hung at a black screen. It's functioning normally, but with black text against a black background! To test this, bring up one of those "hung" windows and focus it. Type "exit" and hit enter. If the window closes, you have the same issue I do.

I've found that I can override the text color and make the apparently-hung window visible and functional. What I cannot seem to do now is to get those settings to apply to either the shortcut or to the actual EXE file. I'm a Linux person by background, not a Windows sysadmin, so I am probably doing something wrong in the settings dialog. I'll figure that out.

In any case, I hope this tip helps others to see if they have the same situation. It may not be a bash or WSL bug, but simply a corrupted setting on the program shortcut.

**Comment by linuxandria** [comment] 2020-04-23 15:32
> I've used bash successfully since early 2017, but today I accidentally clicked the right mouse on the pinned Ubuntu icon on my taskbar and accidentally hit one of the context menu options -- but I didn't see which one. Now bash is a black screen that appears to be hung, for me. Obviously I somehow broke it, but I don't know how.
> 
> In any case, I figured out what's actually happening within my session, and I'm hoping that helps others.
> 
> The bash window is not actually hung at a black screen. It's functioning normally, but with black text against a black background! To test this, bring up one of those "hung" windows and focus it. Type "exit" and hit enter. If the window closes, you have the same issue I do.
> 
> I've found that I can override the text color and make the apparently-hung window visible and functional. What I cannot seem to do now is to get those settings to apply to either the shortcut or to the actual EXE file. I'm a Linux person by background, not a Windows sysadmin, so I am probably doing something wrong in the settings dialog. I'll figure that out. (EDIT: I was editing the terminal properties for the wrong shortcut. For some reason my system had shortcuts in two different places pointing to the same EXE.)
> 
> In any case, I hope this tip helps others to see if they have the same situation. It may not be a bash or WSL bug, but simply a corrupted setting on the program shortcut.

I;ve tried changing the text color to no avail. I know its there because I see a blinking cursor whenever I highlight all the terminal.

**Comment by PMARINA** [comment] 2020-06-02 11:16
I got a similar issue using WSL 1, ubuntu 18.04. I had everything working last night, shut down my machine normally, and then came back this morning to see Ubuntu not working. I haven't tried restarting yet, since that might fix it and log files are cool. 

Steps to create log files:
1. Following the [detailed logs](https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#8-detailed-logs) procedure: 
```
logman.exe create trace lxcore_kernel -p "{0CD1C309-0878-4515-83DB-749843B3F5C9}" -mode 0x00000008 -ft 10:00 -o .\lxcore_kernel.etl -ets
logman.exe create trace lxcore_user -p "{D90B9468-67F0-5B3B-42CC-82AC81FFD960}" -ft 1:00 -rt -o .\lxcore_user.etl -ets
logman.exe create trace lxcore_service -p "{B99CDB5A-039C-5046-E672-1A0DE0A40211}" -ft 1:00 -rt -o .\lxcore_service.etl -ets
```
2. Ran `bash` in the same cmd window
3. Waited 1 minute. 
4. `Ctrl+C` to quit bash and stop logging:
```
logman.exe stop lxcore_kernel -ets
logman.exe stop lxcore_user -ets
logman.exe stop lxcore_service -ets
```
[log files.zip](https://github.com/microsoft/WSL/files/4716725/log.files.zip)
I tried looking through the log files using Event Viewer but they seemed essentially empty.

**Comment by sna-scourtney** [comment] 2020-06-02 16:27
FWIW, I had this issue a long while back, and discovered that it was actually working, but the colors had gotten set to black text on a black background. I don’t have the solution readily at hand (or in my own memory), or I’d offer it here, but you might want to try dragging the mouse across that “black screen” to see if it really is empty.

Regards,
Scott

**Comment by mathmul** [comment] 2022-04-22 11:31
# The immediate cause (of the same thing happening to me)

## Setup

Windows 10 Pro 21H2 19044.1645
WSL 2.0 Ubuntu
16 GB RAM
Intel i7 7th gen CPU

I moved all my dev projects to the Linux filesystem.
Using VS Code with Remote Development extension pack.
My projects are run in Docker containers.
Backend is always a Laravel application (`docker-compose`) with `\public\FrontEnd` being a standalone Vue application (`yarn serve`) that consumes Laravel API.

## Issues

I had loads of issues starting with WSL. First things worked almost perfectly. Then suddenly my entire computer became sluggish at best. The reason behind it was that __WSL ate up my RAM__. I figured to limit maximum memory usage by WSL at 2GB, and while things were working for a second, it was very soon my computer came to a complete halt. The reason behind it this time being (given allowed RAM usage was maxed out) __CPU used disc instead of RAM__, and so disc usage elevated to 100%. Everything froze.

## Solution

I had to tweak the memory usage of WSL, and after some trial and error found __8GB__ to be the sweet spot for my system.

## Issue returns

All of the above being said, just now I had two Laravel projects opened at the same time, and when I opened the second Vue app, it happened again. Disc usage skyrocketed and VS Code lost connection in all 4 instances (Reload/retry didn't help). I closed all VS Code instances, and the CPU, RAM, and disc usage all went back to normal. Still, I tried to open Ubuntu for Windows and it was stuck on a black screen for a long while until it finally printed out that it was terminated.

I am fairly certain my issue will be resolved by a simple restart but just wanted to share my findings if they help anyone.

## Answer

The immediate cause is RAM and/or disc usage at the maximum, but who knows what the root cause of it all is.

**Comment by NikhilKomalla00** [comment] 2023-01-20 02:03
I tried with ctrl+c, Ctrl+Z, Ctrl+X it worked
