### ISSUE TITLE
setsockopt(fd, IPPROTO_IP, IP_MTU_DISCOVER, ...) fails

### ISSUE THREAD

**Issue by cgull** [Microsoft/BashOnWindows#170] opened 2016-04-13 05:02 UTC
I'm a maintainer of Mosh (https://github.com/mobile-shell/mosh).  I tried getting Mosh running on WSL, because it'll obviously be very interesting to the Mosh community.  `mosh-server` needs ptys, so that's obviously not going to work right now, but `mosh-client` is much more relevant for Windows client users anyway.  I ran into problems with two socket-related syscalls that Mosh makes, see cgull/mosh@90ce95bc33df04e2ebaff573485e2dce3d90013d for context and the workarounds I've got in place.
- `setsockopt( _fd, IPPROTO_IP, IP_MTU_DISCOVER, &flag, optlen )` fails, with EINVAL if i recall correctly.  I believe this code was incorrect (though working on Linux) originally, but even after I corrected the bug, it still fails.
- `recvmsg()` also fails with EINVAL.  Setup for this syscall is complex so I'm less sure our code is correct, but again this works fine on any Linux system.

Since Mosh is a fairly sophisticated UDP user, neither of these calls are commonly used, and we have reasonable workarounds, I don't expect fixes-- but it would be nice to at least track status on these issues.

With those workarounds, Mosh works surprisingly well, considering the currently very incomplete `xterm` emulation in WSL.  Thanks for this work!

**Comment by sunilmut** [comment] 2016-04-13 06:42
@cgull I can confirm that the IP_MTU_DISCOVER option is currently not supported. Please feel free to add that to the [User Voice page](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo)

I am bit surprised to see 'recvmsg' failing though because we have pretty extensive support for that. Can you tell us what parameters is 'recvmsg' being called with when it is failing?

**Comment by cgull** [comment] 2016-04-13 16:13
Look at the link above for code; you can get to before and after views of the file in question pretty easily.

Output from strace on mosh-client with the workarounds in that commit (not very helpful, unfortunately):

```
pselect6(5, [0 4], NULL, NULL, {0, 250000000}, {[], 8}) = 1 (in [4], left {0, 222825000})
clock_gettime(CLOCK_MONOTONIC, {48539, 611587000}) = 0
recvmsg(4, 0x7ff5fffed9a0, 0)           = -1 EINVAL (Invalid argument)
recvfrom(4, "\200\0\0\0\0\0\0\0\247\346\226\356\0\363Fs\274\312\223\325\323\327\n\257<\2246\316\214sv\20"..., 2048, 0, {sa_family=
AF_INET, sin_port=htons(60002), sin_addr=inet_addr("198.206.215.40")}, [16]) = 360
write(1, "\33[?25l\nThe programs included wit"..., 389) = 389
```

**Comment by cgull** [comment] 2016-05-18 00:26
I took a look at this again on 14342.  I found there was a bug in my [workarounds code](https://github.com/cgull/mosh/tree/wsl-workarounds), but even after fixing it, `recvmsg()` still fails.  I checked in GDB on Linux and the arguments for this call do seem to be constructed correctly.

Simple repro:
```python
#!/usr/bin/env python3
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, 0)
s.bind(("127.0.0.1", 5555))
print(repr(s.recvmsg(2048, 2048)))
```
You don't need to send anything to this, it'll fall over immediately on WSL.

**Comment by sunilmut** [comment] 2016-05-18 22:24
@cgull - This particular error is because WSL socket code was not respecting the 'msg_name' and 'msg_namelen' field in the 'msghdr' passed in [recvmsg](http://linux.die.net/man/2/recvmsg). This has already been fixed sometime back in the dev branch and should hit the release branch soon. Thanks for reporting it!

**Comment by cgull** [comment] 2016-06-09 23:11
The recvmsg issue seems to be resolved in 14361.  The only workaround required for Mosh now is ignoring the setsockopt error discussed above.

**Comment by benhillis** [comment] 2016-07-15 00:31
IP_MTU_DISCOVER support is on the backlog.

**Comment by cgull** [comment] 2016-09-18 03:26
I opened an issue on UserVoice some time ago, https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13413396-setsockopt-fd-ipproto-ip-ip-mtu-discover-fla

Please upvote if this is important to you.

**Comment by colemickens** [comment] 2016-09-29 01:15
Did this already get fixed? `mosh` from apt is working now. (insider build 14936 + upgraded to Xenial). Very nice!

**Comment by colemickens** [comment] 2016-09-29 01:15
Nevermind, apparently I built it and patched it and forgot.

**Comment by benhillis** [comment] 2016-09-29 01:34
@cgull We are continually improving our socket coverage, do you know what specifically is failing for you?

**Comment by cgull** [comment] 2016-10-01 22:06
The `setsockopt()` issue in the first comment.

This STC fails with 
`ip-mtu-discover: setsockopt(): Invalid argument` on 14926 and `ip-mtu-discover: setsockopt(): Protocol not available` on 14936.  So something has changed, but not improved, for us.

```C
#include <err.h>
#include <stdio.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <netdb.h>

int
main(int ac, char **av)
{
  int fd;

  fd = socket(AF_INET, SOCK_DGRAM, 0);
  if (fd < 0)
    err(1, "socket()");
  struct addrinfo *ai;
  int rv = getaddrinfo("127.0.0.1", "5555", NULL, &ai);
  if (rv < 0)
    err(1, "gai()");
  rv = bind(fd, ai->ai_addr, sizeof (struct sockaddr_in));
  if (rv < 0)
    err(1, "bind()");
  int opt = 1;
  rv = setsockopt(fd, IPPROTO_IP, IP_MTU_DISCOVER, &opt, sizeof opt);
  if (rv < 0)
    err(1, "setsockopt()");
  freeaddrinfo(ai);
  return 0;
}
```

**Comment by sunilmut** [comment] 2016-10-03 22:39
@cgull - Update on this. The Windows networking team just finished providing us support for the IP_MTU_DISCOVER option in the TCP/IP stack (thanks to them). I am now looking into enabling this option in WSL. As part of the validation, I will also try to run the `mosh-client`. Can you provide me detailed steps (or a link) for that? Thanks for your patience.

**Comment by colemickens** [comment] 2016-10-03 22:44
Step 1: Install mosh on a server. (`sudo apt-get install mosh`)

Step 2: Install mosh in WSL: `sudo apt-get install mosh`

Step 3: `mosh user@host` just like you'd use SSH. You need to have some high numbered UDP ports punched through your NSG if you use an Azure VM for the server-side.

**Comment by cgull** [comment] 2016-10-06 02:32
@sunilmut, for a more direct/standalone test you can also try
```shell
MOSH_KEY=AAAAAAAAAAAAAAAAAAAAAA src/frontend/mosh-client 127.0.0.1 60001
```
That starts the client executable without a corresponding remote server (which you don't need to check this issue).  If it immediately exits, setsockopt() is still returning an error.  If the client clears the screen, shows a blue status bar at the top of the screen, and exits on a timeout after ~18 seconds, setsockopt() is working acceptably for mosh.  mosh 1.2.4 (the version available on Ubuntu 14.04's standard package repos) will not print an error message but later versions may give you `Network exception: setsockopt: Protocol not available`.

**Comment by cgull** [comment] 2016-10-06 02:37
Also, on mosh-1.2.6, you can run an e2e test by doing `mosh --local 127.0.0.1`, which will set up a Mosh session on the local machine without using ssh.  See `https://launchpad.net/~keithw/+archive/ubuntu/mosh-dev` for a PPA that will let you install that version easily.

**Comment by cgull** [comment] 2016-11-06 20:23
@sunilmut, any news?  14959 shows no change from 14936's behavior.

**Comment by sunilmut** [comment] 2016-11-09 23:48
@cgull - We recently had the dependency of this met by the Windows TCP/IP team. We will be soon looking into lighting this up within WSL. Sorry, I don't have an ETA at the moment.

**Comment by tgies** [comment] 2016-11-10 00:27
Minutes _f666

**Comment by sunilmut** [comment] 2016-11-16 00:19
Just an update that the fix for IP_MTU_DISCOVER has been checked into the dev branch. I have verified that the `MOSH_KEY=AAAAAAAAAAAAAAAAAAAAAA mosh-client 127.0.0.1 60001` command works fine with the fix (although, it logs an error about the IP_RECVTOS socket option, but that is not fatal). The fix should make it to the release branch.

**Comment by Pyrepenol** [comment] 2016-12-17 15:26
Any updates on this? I just upgraded to Insider Preview 14965 and unfortunately found that this has not been resolved.

**Comment by sunilmut** [comment] 2016-12-17 19:40
@Pyrepenol - It should be in the next insider build. Thanks for your patience.

**Comment by Pyrepenol** [comment] 2016-12-18 19:45
I thought I updated to 14986 but it turns out the update actually failed-- so it might actually be released already. Will let you know if I get the upgrade working so you all can set this as fixed.

**Comment by sunilmut** [comment] 2016-12-19 19:39
@Pyrepenol - From the changelist, I can see that IP_MTU_DISCOVER is not in 14986, but you are most welcome to confirm the same at your end as well.

**Comment by Pyrepenol** [comment] 2016-12-24 15:56
Finally managed to get 14986 working and I can confirm this fix is not included unfortunately!

**Comment by sunilmut** [comment] 2017-01-09 23:32
This should be fixed in [15002](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-15002). Please validate and let us know if the issue persists.

**Comment by sunilmut** [comment] 2017-01-19 01:51
Closing this out. If anyone is still (on builds 15002+) having problems, please let us know and we can reopen.

**Closed by sunilmut** 2017-01-19 01:51 UTC
Labels: bug, fixedininsiderbuilds, network

**Comment by cgull** [comment] 2017-01-21 00:05
I forgot to comment earlier, I did test this on 15002 or 15007 and it works for me, mosh-1.3.0-rc2 passes all tests.  I'll note this as now working in Mosh release notes.
