### ISSUE TITLE
traceroute not working

### ISSUE THREAD

**Issue by smholsen** [Microsoft/BashOnWindows#1411] opened 2016-11-24 12:12 UTC
* A brief description
After downloading the traceroute package, i tried to perform a traceroute command, did not return expected result.

* Expected results
Traceroute of packet to destination

* Actual results (with terminal output if applicable)
traceroute to www.google.no (46.249.239.155), 30 hops max, 60 byte packets
setsockopt IP_MTU_DISCOVER: Invalid argument

* Your Windows build number
Build 14393.447

* Steps / All commands required to reproduce the error from a brand new installation 
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install traceroute
sudo traceroute www.google.com

**Comment by aseering** [comment] 2016-11-24 16:46
Hi @smholsen -- thanks for reporting your experience!  This is a known issue and is discussed in more detail on ticket #69 .  It affects a number of network commands.  (It sounds like you're running the stable Windows release; I know that `ping` is no longer affected in more-recent Insider builds, but I don't know about `traceroute` offhand.)

The workaround is to run Bash on Windows as a Windows Administrator -- the issue is not with Linux-level permissions (ie., root vs non-root) but with Windows permissions.

**Comment by benhillis** [comment] 2016-11-29 16:32
Closing as a duplicate.

**Closed by benhillis** 2016-11-29 16:32 UTC
Labels: duplicate
