### ISSUE TITLE
ifconfig command not working

### ISSUE THREAD

**Issue by bhaskargoyal** [Microsoft/BashOnWindows#1452] opened 2016-12-03 13:48 UTC
* Brief description
ifconfig  is  used to configure the kernel-resident network interfaces. But the network command is not working in bash on ubuntu on windows.

* Expected results
All network interfaces currently active.

* Actual results (with terminal output if applicable)
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.

* Your Windows build number
Edition: Windows 10 home Single Language
Version: 1607
OS Build: 14393.447

* Steps / All commands required to reproduce the error from a brand new installation 
>>> ifconfig

**Comment by goyal-naman** [comment] 2016-12-03 13:50
Surely the very basic command not working on Anniversary Update

**Comment by aseering** [comment] 2016-12-03 15:33
Thanks @bhaskargoyal for posting!  This issue has the same underlying cause as #468 , and is discussed in that ticket (though the ticket is very long so it may be hard to find the discussion).  In short:

* `ifconfig` does not work on the Anniversary Edition (build 14393, which you're running)
* `ifconfig` mostly works on the most-recent [Insider build](https://insider.windows.com/).  But there's a bug if you have a Teredo interface in Windows; you have to disable the interface to get these commands to work.
* We're told that it will work completely in an upcoming Insider build.

**Comment by Zx-EvM** [comment] 2016-12-03 23:43
https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/16109719-enable-network-connection-enumeration

https://blogs.msdn.microsoft.com/commandline/2016/11/10/ifconfig-and-network-connection-enumeration-support-in-windows-10-insider-build-14965/

**Comment by sunilmut** [comment] 2016-12-07 06:28
Marking this as duplicate of #468

**Comment by sunilmut** [comment] 2017-01-13 14:00
The teredo issue should be fixed in [15007](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-15007)

**Closed** 2017-01-19 01:54 UTC
Labels: duplicate, fixedininsiderbuilds, network

**Comment by staticfrost** [comment] 2017-03-03 23:20
How do i  check my insiderbuild number?

**Comment by aseering** [comment] 2017-03-03 23:22
Run `ver` in a cmd.exe shell.
