### ISSUE TITLE
"LxRun.exe /setdefaultuser" fails if temp folder is not accessible

### ISSUE THREAD

**Issue by zzpxyx** [Microsoft/BashOnWindows#752] opened 2016-08-04 02:55 UTC
* A brief description
`LxRun.exe /setdefaultuser` will fail if Windows temp folder is not accessible, either because of privilege or unsupported file systems like RAM disk, etc.

* Expected results
The default user should be set to the given user without any error.

* Actual results (with terminal output if applicable)
An error message like:
`/bin/bash: /mnt/d/TEMP/uid.txt: No such file or directory`
or
`/bin/bash: /mnt/c/WINDOWS/TEMP/uid.txt: No such file or directory`
Note that the first error message appears when my Temp folder is on a RAM disk, and the second appears when I'm using the system-level Temp folder (C:\Windows\Temp).

* Your Windows build number
10.0.14393

* Steps / commands required to reproduce the error
Set the Temp folder to a RAM disk or use the system-level Temp folder. Then execute the command:
`LxRun.exe /setdefaultuser <username>`

**Comment by rainabba** [comment] 2016-08-26 00:16
First hit on Google for this error, 21 days ago and no so much as another comment?! I'm not REALLY the 2nd person who's hit this bug am I?

I followed all instructions to get this far and had no other issues along the way so I don't think I caused it. I even used an elevated cmd prompt and tried `lxrun.exe /setdefaultuser` after hitting it the 2nd time so I don't think it's actually a permissions error on the standard Windows side and I started investigating.

My TEMP environment variable reports as `TEMP=C:\TEMP`, but my actual folder is `c:\Temp`. This cannot be changed at standard runtime because of app using the folder and being a Linux user, I'm aware of case issues in POSIX environments so I updated my environment variable with `set TEMP=c:\Temp` then tried again and it worked.

Workaround: `set TEMP={your actual temp folder, including case sensitivity}`

Fix: MS should check any environment variables and/or registry settings that this bash environment will be dependant on and make sure case is updated in those variables if it doesn't match. In Linux, suggesting such a thing would seem absurd since it's a standard requirement, but for a Windows user with limited bash experience, something this simple could be a real nightmare.

**Comment by benhillis** [comment] 2016-09-28 14:27
This had the same root cause as #598 for which a fix is incoming.  Marking this as a duplicate.  Thanks again for reporting!

**Closed by benhillis** 2016-09-28 14:27 UTC
Labels: bug

**Comment by kimfaint** [comment] 2016-12-09 02:31
I hit this issue when installing today. Cause was on my system C:\Temp was actually C:\temp.  Had to rename directory then rerun `lxrun.exe /setdefaultuser`.

**Comment by benhillis** [comment] 2016-12-09 03:23
Which Windows build are you on? This is fixed in recent insider builds.

**Comment by kimfaint** [comment] 2016-12-09 03:51
OS Build 14393.0.

**Comment by leonhui** [comment] 2016-12-14 11:06
`**/bin/bash: /mnt/c/TEMP/uid.txt: Input/output error**`

Bug exists if the **TEMP directory is a JUNCTION**.

My TEMP=C:\TEMP, where TEMP is mounted to a different volume via `diskmgmt.msc`.

Under cmd.exe it shows it as:

`12/02/2016  02:31    <JUNCTION>     TEMP [\??\Volume{xxxxxxxxxxxxxxxxxxxxxxxxxx}\]`

However, under bash, `ls` does not show but `cd /mnt/c/TEMP` errors with

`bash: cd: TEMP: Input/output error`

**Comment by aseering** [comment] 2016-12-14 15:29
@leonhui -- that sounds related to #559 and #1475 .  In general, WSL doesn't support Windows Junctions right now.  Those tickets have more details.

**Comment by benhillis** [comment] 2016-12-14 16:43
@leonhui - Are you on build 14393? This will not be a problem in recent insider builds.
