### ISSUE TITLE
ctrl-2 (ASCII NUL) is not delivered by termios

### ISSUE THREAD

**Issue by cgull** [Microsoft/BashOnWindows#188] opened 2016-04-14 01:30 UTC
I haven't yet been able to get ctrl-2 (or any other typed character combination like ctrl-shift-2 or ctrl-space, on the standard US keyboard layout) to deliver an ASCII NUL character to Linux apps, in termios' raw or canonical mode.  This works OK at a cmd prompt in Windows Console, so the issue seems to be in WSL, rather than Windows Console.

**Comment by benhillis** [comment] 2016-04-14 01:37
I believe @sunilmut fixed this recently and he fix is headed to he flights from branch. Sunil can you confirm?

**Comment by sunilmut** [comment] 2016-04-14 22:46
Confirmed that this is an issue in the publicly available builds and something that has already been fixed in our dev branch. All the above key mentioned presses should deliver ASCII NUL to the Linux app.

**Comment by cgull** [comment] 2016-04-23 17:51
This is improved but not completely fixed in 14328:  in raw mode, ctl-2 etc. properly generate an ASCII NUL (so Emacs is OK), but in cooked mode, it seems to cause an EOF in termios.  This can be demonstrated by running `cat` and typing ctl-2 -- for me that immediately returns to a shell prompt, and strace shows that `cat` is reading 0 bytes, and not being signaled.

**Comment by zadjii-msft** [comment] 2016-04-28 21:43
I'm gonna move this over to @sunilmut, I think the console is still sending the right sequence here, but this has to do more with the TTY and ECHOCTL implementation. See that `cat` then pressing Ctrl+2 results in `^@` getting echo'd in PuTTY, but the NUL doesn't get translated to "^@"

**Comment by cgull** [comment] 2016-04-30 17:31
That sounds plausible to me, I think my second issue is probably something that was hidden by the first issue, but is separate from it (and is likely a termios implementation issue).  Sorry for not making that clear.

**Comment by cgull** [comment] 2016-06-09 23:01
In 14361, the termio issue discussed here seems to be resolved, at least on an ssh pty.  But it now seems to be impossible to generate ASCII NUL with conhost, see #502.

**Comment by zadjii-msft** [comment] 2016-10-04 22:32
It looks like there are some recent changes in kernel-land that actually re-enable C-Spc, C-@, C-a, etc, so shout out to bperkins for that fix!

(also related: #583)

**Closed by zadjii-msft** 2016-10-04 22:32 UTC
Labels: console

**Comment by cgull** [comment] 2016-10-06 02:52
Doesn't work for me in 14936, at least via RDP + HyperV console (but it does work in Console+CMD and Cygwin).  Has this hit fast ring yet?

**Comment by zadjii-msft** [comment] 2016-10-06 15:32
I don't think so. This just showed up on my machine, so it'll probably still be a little while till insiders.

**Comment by cgull** [comment] 2016-11-14 05:08
Works for me in 14965.

**Comment by tekktonic** [comment] 2018-03-09 15:55
This bug has reappeared at some point: showkey -a shows that ctrl+@ doesn't generate anything, nor does (how I noticed the bug) ctrl+space, which means that emacs is broken without rebinding the set-mark function. I can't find my computer's build # but the show version screen does say that it's a version of Windows 10 Enterprise with a copyright date of 2017, after this bug was marked closed.

**Comment by makanikai** [comment] 2018-04-17 09:06
I also see this bug again

**Comment by emliunix** [comment] 2018-06-21 13:34
Not working in 17134.112

**Comment by therealkenc** [comment] 2018-06-21 23:48
Two posts with pronouns and one with no noun at all. Sigh.

_This_ bug, which _is closed_, was quoth: "I haven't yet been able to get ctrl-2 (or any other typed character combination like ctrl-shift-2 or ctrl-space, on the standard US keyboard layout) to deliver an ASCII NUL character to Linux apps".

If "it" hasn't been fixed, please file a new issue following `CONTRIBUTING.md`. Bearing in mind that `showkey(1)` isn't available in WSL because WSL has no keyboard device. Which is dupe #1806.
