### ISSUE TITLE
Starting bash gives error: 0x80070005

### ISSUE THREAD

**Issue by chikei** [Microsoft/BashOnWindows#2244] opened 2017-06-22 12:04 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

10.0.15063

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Starting Bash, then only output is error: 0x80070005 and press any key to return, then bash ends if I pressed any key

* What's wrong / what should be happening instead:

Bash should start normally

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

[lxcore_trace.zip](https://github.com/Microsoft/BashOnWindows/files/1094660/lxcore_trace.zip) made with [instuction from this comment](https://github.com/Microsoft/BashOnWindows/issues/473#issuecomment-271978053)

**Comment by benhillis** [comment] 2017-06-22 15:36
Marking as duplicate of #651

**Closed by benhillis** 2017-06-22 15:36 UTC
