### ISSUE TITLE
Scrolling up affects only the top line of the screen

### ISSUE THREAD

**Issue by mphaney** [Microsoft/BashOnWindows#42] opened 2016-04-07 18:32 UTC
With commands like **less** and **man**, scrolling down using the arrow keys works precisely as one might expect, however scrolling _up_ appears to only affect the top line of text on the screen.  Scrolling down again after having tried to scroll up, simply resumes the downward scroll as though the attempt to scroll up never occurred.

A similar phenomenon is observed when searching for text using /, or navigating using other shortcuts such as PgUp/PgDn or g/G

This is _possibly_ related to #34 but that one is very difficult to read and understand.

**Comment by zadjii-msft** [comment] 2016-04-18 16:35
This is a dupe of #27, and the fix should be on the way.

**Comment by bitcrazed** [comment] 2016-04-28 18:18
Closing as a dupe of #27

**Closed by bitcrazed** 2016-04-28 18:18 UTC
Labels: bug, console, duplicate
