### ISSUE TITLE
writev(2) seems not to set file pos correctly

### ISSUE THREAD

**Issue by unak** [Microsoft/BashOnWindows#420] opened 2016-05-24 15:37 UTC
Reproduce code (writev.c):

```C
#include <errno.h>
#include <fcntl.h>
#include <stdlib.h>
#include <sys/uio.h>

main(void)
{
    struct iovec iovec;
    int fd;

    fd = open("test.dat", O_CREAT | O_WRONLY | O_TRUNC, 0644);
    if (fd < 0) {
        perror("open");
        exit(1);
    }

    iovec.iov_base = "abcd\n";
    iovec.iov_len = 5;
    if (writev(fd, &iovec, 1) < 0) {
        perror("writev(1)");
        close(fd);
        exit(1);
    }

    iovec.iov_base = "ef\n";
    iovec.iov_len = 3;
    if (writev(fd, &iovec, 1) < 0) {
        perror("writev(2)");
        close(fd);
        exit(1);
    }

    close(fd);

    exit(0);
}
```

How to reproduce:

```
usa@METHUSS:~/tmp$ gcc writev.c
usa@METHUSS:~/tmp$ ./a.out
usa@METHUSS:~/tmp$ cat test.dat
ef
d
```

Expected result of `cat test.dat`:

```
abcd
ef
```

**Comment by benhillis** [comment] 2016-05-24 23:37
I believe that this is the same root cause as #313 which as been fixed and will be in a Windows Insider build soon.

Thank you for the detailed repro steps, I've tried them locally on our development branch and verified that it now matches the expected.

**Comment by unak** [comment] 2016-05-25 02:12
thank you for reviewing.  I'm looking forward to the fixed build :)

**Comment by russalex** [comment] 2016-06-09 00:22
Looks to be fixed in 14361.

```
russ@DESKTOP-K1JHN54:/mnt/c/temp$ vi foo.c
russ@DESKTOP-K1JHN54:/mnt/c/temp$ gcc foo.c
russ@DESKTOP-K1JHN54:/mnt/c/temp$ ./a.out
russ@DESKTOP-K1JHN54:/mnt/c/temp$ cat test.dat
abcd
ef
```

Thanks for the solid repro here.

**Closed** 2016-06-13 14:57 UTC
Labels: bug, duplicate, fixed
