### ISSUE TITLE
Horizontal pane rendering error with tmux and DejaVu Sans Mono font (and other fonts) on Creators Update

### ISSUE THREAD

**Issue by zer0beat** [Microsoft/BashOnWindows#2099] opened 2017-05-13 10:16 UTC
Windows build number: `Microsoft Windows [Versión 10.0.15063]`
Bash on Windows release:
```
➜  ~ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
winver.exe
![winver](https://cloud.githubusercontent.com/assets/1813251/26024584/70a68c30-37d4-11e7-9144-e253bf083bbb.PNG)

Components involved:
tmux: `sudo apt-get install tmux`
[DejaVu fonts](https://dejavu-fonts.github.io/)

Commands:
```
tmux
Ctrl+b, "
Ctrl+b, UpArrow
Ctrl+b, DownArrow
```
What's wrong
With the default consolas font, chars like arrows (used on default prompt theme of oh-my-zsh) doen't show correctly but all tmux panes are rendered correctly.
![tmux_split_for_consolas](https://cloud.githubusercontent.com/assets/1813251/26024610/1c9c3e22-37d5-11e7-8596-efd524fbaaf8.PNG)

To solve the chars problem in previous versions of BashOnWindows (Anniversary Update) I used the DejaVu Sans Mono fonts and all works as expected (chars and pane separators works great). But now, using creators update BashOnWindows version and DejaVu Sans Mono, the console don't render correctly the horizontal pane separators.
![tmux_split_for_dejavu_sans_mono](https://cloud.githubusercontent.com/assets/1813251/26024631/800ada04-37d5-11e7-9c83-1d847adb8bab.PNG)

I tried many monospace fonts and all have problems with horizontal pane in tmux.

**Comment by zadjii-msft** [comment] 2017-05-15 16:52
@zer0beat yep, I'm very aware of this one. DejaVu Sans is my daily driver typeface as well, and it just plain old does not work with tmux.

This is a dupe of #1907, despite the title. I'll leave this one open as a constant reminder to myself that I want this investigated. Last cycle, IIRC there wasn't anything that could be done about this, but who knows. I'll give it another look.

**Comment by zadjii-msft** [comment] 2017-05-25 22:41
This does not have a great solution, and I'm sure that next cycle I'm going to have to deal with this again, but that being said, this should be fixed in most fonts now. I'm not sure how apps like tmux, mc, etc interact with CJK fonts, but from my testing it seems to work better at least.

**Closed** 2017-05-25 23:29 UTC
Labels: console, duplicate, fixinbound
