### ISSUE TITLE
Flask not working?

### ISSUE THREAD

**Issue by chinant** [Microsoft/BashOnWindows#570] opened 2016-06-23 13:13 UTC
Flask for on Python 2 install fine, but I get some below error when run flask application.

curl -i http://127.0.0.1:5000/
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 12
Server: Werkzeug/0.11.10 Python/2.7.10
Date: Thu, 23 Jun 2016 13:07:40 GMT
## curl: (18) transfer closed with 12 bytes remaining to read

get an error ERR_CONNECTION_RESET  message on Chrome.

**Comment by sunilmut** [comment] 2016-06-23 18:25
Thanks for reporting the issue and trying out WSL! Which Windows build are you running? Can you also post the specific repro?

**Comment by chinant** [comment] 2016-06-24 04:19
@sunilmut , thanks for the reply.
build:  14367.rs1 release 160613-1700

**Comment by glebovsky** [comment] 2016-06-24 07:24
Hello!

Can confirm this on build 14372.rs1_release.160620-2342. 
Connection resets on a static file like this:

`http://127.0.0.1:8000/static/dist/vendor.bundle.js Failed to load resource: net::ERR_CONNECTION_RESET`

**Comment by xBytez** [comment] 2016-10-20 18:59
I think this might be related to #610

**Comment by sunilmut** [comment] 2016-12-04 10:02
Marking this as duplicate of #610 for now. The fix for #610 is making it's way to the Insider build. If the issue persists even with the fix for #610, I would happily take the `duplicate` tag off and investigate. thanks.

**Comment by sunilmut** [comment] 2016-12-06 23:48
The fix for #610 is in-bound to Insider builds. I don't have the repro for the above, so, I cannot validate whether #610 fixes this issue. If someone can post detailed repro, I am happy to try.

**Comment by xBytez** [comment] 2016-12-07 08:50
# PoC
```bash
# pip install Flask
# cat <<EOF > app.py
from flask import Flask
app = Flask(__name__)

@app.route('/')
def random():
    with open("/dev/urandom", 'rb') as f:
        return repr(f.read(10000000))

if __name__ == '__main__':
    app.run()
EOF
# python app.py
```

On Windows/WSL:
```bash
# curl -i http://127.0.0.1:5000/
```

# Expected result
Curl finishes without errors

# What happens when running the Flask server on WSL
* curl exits with a 'connection reset' error when curling from Windows 
* curl exits with a  "transfer closed with 521531 bytes remaining to read" when curling from WSL


I hope this is any use to you.

**Comment by sunilmut** [comment] 2017-01-16 19:30
@chinant - Given that #610 and #616 are fixed in 15002, this should be fixed as well. If you can validate your scenario and let us know, we can close this issue out.

**Comment by chinant** [comment] 2017-01-18 16:50
@sunilmut , it's ok, you can close it! thank you for your hard work

**Closed** 2017-01-18 17:07 UTC
Labels: duplicate, fixedininsiderbuilds, network
