### ISSUE TITLE
Gracefully handle subsystem crashes

### ISSUE THREAD

**Issue by krzysztofantczak** [Microsoft/BashOnWindows#1299] opened 2016-10-31 23:19 UTC
Hello,

Not really much to say here. I really like to play with things around and while testing ie. WSL Switcher (https://github.com/RoliSoft/WSL-Distribution-Switcher) or just playing around in LXSS on my own, sometimes it's really easy to literally blow system up - by typo, wrong perms, etc. ;-) It goes into nice blue-background screen which collects some info about crash and restarts the computer. Would it be possible to handle those crashes gracefully? Without OS restart? Ie. by simply terminating bash.exe with some general (or more detailed) error.

Thanks in advance.

**Comment by benhillis** [comment] 2016-10-31 23:22
@krzysztofantczak If you're hitting blue screens there's a bug somewhere that we should investigate.  Do you have reproducible steps that you can share?

**Comment by krzysztofantczak** [comment] 2016-10-31 23:28
@benhillis i did it in few different ways, but the last time was when playing with WSL Switcher and Kali Linux docker image (it's listed in their readme) - so after replacing original ubuntu with kali, which didn't finished successfully. It has to be something related to broken rootfs. Because before that, i also hitted the same issue when messing around with rootfs by hand - so i'm guessing i messed up some permissions or something... Anyway i bet i'll get there again in the near future, so i'll try to keep tracking my steps for You next time.

**Comment by sunilmut** [comment] 2016-10-31 23:32
@krzysztofantczak - Also, which Windows build are you running? Do you have any more information from the blue screen, like the code?

**Comment by krzysztofantczak** [comment] 2016-10-31 23:33
@sunilmut Build 14955.1000 and no, no code at this time.

**Comment by fpqc** [comment] 2016-11-01 00:02
@krysztofantczak There were lots of bluescreens two versions ago from a known bug. If you can reproduce in the current build, this is probably a bit more interesting.

Unfortunately though, because the subsystem lives inside the Windows Kernelmode, runaway threads or bugs can leave the kernel in an unsafe state and therefore trigger a bugcheck and reboot, just like a buggy device driver can.  There is not much they can do to make the subsystem halt gracefully except for fixing bugs in the driver, at least that is my understanding.

**Comment by benhillis** [comment] 2017-08-22 17:33
Closing this out.  Due to the nature of WSL being implemented as a kernel, occasionally bugs can cause blue screens.  That being said, we are constantly monitoring bluescreens that our users encounter and fix them as quickly as possible.

**Closed by benhillis** 2017-08-22 17:33 UTC
