### ISSUE TITLE
Say command not working

### ISSUE THREAD

**Issue by alexanderwhatley** [Microsoft/BashOnWindows#1300] opened 2016-11-01 00:11 UTC
My guess is that this is due to some audio driver not being implemented, but anyways:

alex@AlexanderPC:/mnt/c/Users/Alexander$ say hi
2016-11-01 00:10:01.134 say[15] No local time zone specified.
2016-11-01 00:10:01.135 say[15] Using time zone with absolute offset 0.
2016-11-01 00:10:01.131 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:01.213 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:01.267 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:01.328 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:01.382 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:01.435 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:01.487 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:01.540 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:01.593 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:01.646 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:01.699 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:01.751 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:01.805 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:01.858 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:01.911 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:01.964 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.017 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.069 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.122 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.175 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.229 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.282 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.335 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.387 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.441 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.517 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.571 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.624 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.677 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.730 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.783 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.836 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.890 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.943 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:02.996 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.049 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.101 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.154 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.207 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.261 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.313 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.367 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.421 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.474 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.526 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.579 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.633 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.685 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.738 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.791 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.844 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.896 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:03.949 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.002 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.056 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.109 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.162 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.216 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.268 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.322 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.375 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.428 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.481 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.535 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.588 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.640 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.694 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.748 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.803 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.856 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.910 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:04.962 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.015 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.069 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.122 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.175 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.227 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.281 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.334 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.387 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.440 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.493 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.546 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.599 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.652 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.705 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.758 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.811 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.866 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.919 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:05.972 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:06.025 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:06.078 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:06.131 say[15] connect attempt failed - Invalid argument
2016-11-01 00:10:06.185 say[15] connect attempt failed - Invalid argument
say: Uncaught exception NSInternalInconsistencyException, reason: unable to contact GDNC server -
please check that the gdnc process is running.
I attempted to start it at '/usr/bin/gdnc'

**Comment by stehufntdev** [comment] 2016-11-30 16:51
Thanks for reporting the issue.  Currently WSL does not support device access, and there are a few related posts.  Closing this out as a duplicate of #237 since it is a related issue.

**Closed by stehufntdev** 2016-11-30 16:51 UTC
Labels: duplicate
