### ISSUE TITLE
OpenWRT not compile

### ISSUE THREAD

**Issue by diogosilva** [Microsoft/BashOnWindows#432] opened 2016-05-26 21:56 UTC
Trying compile the OpenWRT get a error in the package m4.

```
git clone git://git.openwrt.org/15.05/openwrt.git
cd openwrt
make menuconfig
< Install all deps requested>
make V=99
```

**Comment by diogosilva** [comment] 2016-05-26 22:06
The problem it happens trying compile m4 1.4.17 separately too.

wget ftp://ftp.gnu.org/gnu/m4/m4-1.4.17.tar.gz
tar -xvzf m4-1.4.17.tar.gz
cd m4-1.4.17
./configure --prefix=/usr/local/m4
make

....

In file included from ./stdio.h:33:0,                                                                                                                                         from fopen.c:26:                                                                                                                            /usr/include/stdio.h:48:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'typedef'                                                           typedef struct _IO_FILE FILE;                                                                                                                                ^                                                                                                                                                           fopen.c:29:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'static'                                                                         static FILE *                                                                                                                                                ^                                                                                                                                                           fopen.c:29:1: error: unknown type name 'FILE'                                                                                                                In file included from ./stdio.h:33:0,                                                                                                                                         from stdio.h:43,                                                                                                                                             from fopen.c:38:                                                                                                                            /usr/include/stdio.h:195:1: error: unknown type name 'FILE'                                                                                                   extern FILE *tmpfile (void) __wur;


....

In Ubuntu this works fine.

**Comment by aseering** [comment] 2016-05-27 00:31
Interesting -- it looks like m4's configure script is observing a bunch of differences between the WSL environment and the environment on a real Ubuntu machine.  I would guess that it's encountering a combination of (un)supported features that it hasn't been tested with before.

Here are the differences between the generated `config.h` on a real Ubuntu system (`-`) vs WSL (`+`).  It looks like there are a pile of compatibility issues to do with syscalls that take a path to a file as an argument, in the scenario where someone appends a '/' to the end of the filename.  Also a couple possibly-unrelated issues:

```
--- lib/config.h        2016-05-26 20:12:01.999253409 -0400
+++ ../st.config.h      2016-05-26 20:20:28.238721223 -0400
@@ -70,7 +70,7 @@
 /* #undef FLT_SIGNBIT_WORD */

 /* Define to 1 if fopen() fails to recognize a trailing slash. */
-/* #undef FOPEN_TRAILING_SLASH_BUG */
+#define FOPEN_TRAILING_SLASH_BUG 1

 /* Enable compile-time and run-time bounds-checking, and some warnings,
       without upsetting newer glibc. */
@@ -1132,7 +1132,7 @@

 /* Define to 1 if 'lstat' dereferences a symlink specified with a trailing
    slash. */
-#define LSTAT_FOLLOWS_SLASHED_SYMLINK 1
+/* #undef LSTAT_FOLLOWS_SLASHED_SYMLINK */

 /* If malloc(0) is != NULL, define this to 1. Otherwise define this to 0. */
 #define MALLOC_0_IS_NONNULL 1
@@ -1204,7 +1204,7 @@
 /* #undef NEED_PRINTF_UNBOUNDED_PRECISION */

 /* Define to 1 if open() fails to recognize a trailing slash. */
-/* #undef OPEN_TRAILING_SLASH_BUG */
+#define OPEN_TRAILING_SLASH_BUG 1

 /* Name of package */
 #define PACKAGE "m4"
@@ -1254,7 +1254,7 @@
 /* #undef PTRDIFF_T_SUFFIX */

 /* Define to 1 if readlink fails to recognize a trailing slash. */
-/* #undef READLINK_TRAILING_SLASH_BUG */
+#define READLINK_TRAILING_SLASH_BUG 1

 /* Define if rename does not work when the destination file exists, as on
    Cygwin 1.5 or Windows. */
@@ -1269,11 +1269,11 @@

 /* Define if rename does not correctly handle slashes on the destination
    argument, such as on Solaris 10 or NetBSD 1.6. */
-/* #undef RENAME_TRAILING_SLASH_DEST_BUG */
+#define RENAME_TRAILING_SLASH_DEST_BUG 1

 /* Define if rename does not correctly handle slashes on the source argument,
    such as on Solaris 9 or cygwin 1.5. */
-/* #undef RENAME_TRAILING_SLASH_SOURCE_BUG */
+#define RENAME_TRAILING_SLASH_SOURCE_BUG 1

 /* Define to 1 if stat needs help when passed a directory name with a trailing
    slash */
@@ -1281,7 +1281,7 @@

 /* Define to 1 if stat needs help when passed a file name with a trailing
    slash */
-/* #undef REPLACE_FUNC_STAT_FILE */
+#define REPLACE_FUNC_STAT_FILE 1

 /* Define if nl_langinfo exists but is overridden by gnulib. */
 /* #undef REPLACE_NL_LANGINFO */
```

**Comment by KineticTheory** [comment] 2016-05-28 21:43
@diogosilva I'm seeing this exact same issue and can confirm the diffs detailed by @aseering.

**Comment by benhillis** [comment] 2016-06-15 20:00
This has the same root cause as #535.  Fix will be making its way to a Windows Insider build soon.

**Comment by diogosilva** [comment] 2016-06-18 00:07
@benhillis Can you check or confirm if the OpenWRT can do a full compile in the new Windows Insider build? Maybe some other bug appear.

**Comment by benhillis** [comment] 2016-06-18 00:11
@diogosilva Sure thing, giving that a try now.

**Comment by benhillis** [comment] 2016-06-18 04:12
Looks like it worked:

![image](https://cloud.githubusercontent.com/assets/17727402/16168957/3e0e36d6-34d0-11e6-8718-08bf9d9f21ad.png)

**Comment by diogosilva** [comment] 2016-06-18 12:39
@benhillis For check it you need do:

```
git clone git://git.openwrt.org/15.05/openwrt.git
cd openwrt
make menuconfig
< Install all deps requested>
make V=99
```

After the make V=99, please check the folder bin/<platform_dir>/ for many .bin files.

**Comment by benhillis** [comment] 2016-06-20 16:14
@diogosilva Could you please clarify what you mean by "Install app deps requested?"

**Comment by diogosilva** [comment] 2016-06-20 16:37
@benhillis if menuconfig fails, shows some depends (libs,programs) and that need to be installed.

To install depends:
sudo apt-get install build-essential subversion libncurses5-dev zlib1g-dev gawk gcc-multilib flex git-core gettext libssl-dev

I think this resolve. But you already show a menuconfig screen and you can run the make V=99, i think...

**Comment by benhillis** [comment] 2016-06-20 20:19
Looks like the "make V=99" succeeded.  Keep an eye out in the release notes for an entry that talks about handling of file paths that end in a '/' character, that's what seems to have unblocked this.

**Comment by benhillis** [comment] 2016-07-08 15:19
This is resolved in Build 14371.

**Comment by mchome** [comment] 2016-07-09 11:42
Hey, i have a problem with clone the openwrt repo on /mnt/c, git give the error "error: unable to create file xxx (Invalid argument)", but there's no error on ~/.

**Comment by diogosilva** [comment] 2016-07-09 12:34
Dont clone the Repo in the windows filesystem, clone in the linux And you can access the files from windows by c/users/USERNAME/Local/lxss/home/.

I am in the smartphone now, need confirm.

**Comment by diogosilva** [comment] 2016-07-09 17:42
@benhillis Yes, its working now.

I have only a problem to use Openwrt with precompiled 32bit toolchain in a particular platform. But this is another bug and is already open. I hope this can be fixed fast.

Bash on Windows will be available in the next stable Windows update (not insider version)?

**Comment by benhillis** [comment] 2016-07-09 18:07
Yes WSL will be part of the Windows 10 anniversary update.

https://blogs.msdn.microsoft.com/wsl/2016/07/08/bash-on-ubuntu-on-windows-10-anniversary-update/

**Closed** 2016-07-09 20:59 UTC
Labels: fixed
