### ISSUE TITLE
BoUoW causes entire windows to crash on a certain command (Fork bomb)

### ISSUE THREAD

**Issue by sandeepzgk** [Microsoft/BashOnWindows#1839] opened 2017-03-31 14:25 UTC
* A brief description
I was trying to run ":(){ :|:& };:" (fork bomb) command (without double quotes), This dramatically slows down the computer if you dont manage to close BoUoW within a few seconds of slowdown it causes windows to crash. and collects a memory dump.

* Expected results
It should work as expected and return value not crash entire system ( just maybe bash / subsystem )and not crash entire windows.
(Not sure if this is a reasonable expectation but still, putting it out there)

* Actual results (with terminal output if applicable)
[1] 15
* Your Windows build number

* Steps / All commands required to reproduce the error from a brand new installation 
Version 10.0.14393

* Strace of the failing command
N/A
* Required packages and commands to install
N/A

**Comment by fpqc** [comment] 2017-03-31 16:55
Release to the general public for RS2/CU is like next week. This is fixed and has been for months.

**Comment by sandeepzgk** [comment] 2017-03-31 16:57
@fpqc sorry, my bad for not checking

**Comment by benhillis** [comment] 2017-03-31 17:11
Marking as duplicate of #233.

**Closed by benhillis** 2017-03-31 17:11 UTC
