### ISSUE TITLE
ps aux fails after waking up from suspend

### ISSUE THREAD

**Issue by pkerichang** [Microsoft/BashOnWindows#1649] opened 2017-01-31 06:27 UTC
Hello,

This is windows prerelease build 15014, sometimes after waking up from suspend, ps aux will segfault.  Below is the message it prints:

-> ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
Signal 11 (SEGV) caught by ps (procps-ng version 3.3.10).
root         1  0.0  0.0  10640     4 ?        Ssps:display.c:66: please report this bug
Segmentation fault (core dumped)

If I just run ps or ps -u $USER, then it works correctly.

**Comment by stehufntdev** [comment] 2017-01-31 17:52
Thanks for reporting the issue.  I tried to repro this locally but was not able to hit any issues on a recent internal build.  Can you please take a strace before and after the suspend so we can see if there are any interesting syscall failures?

**Comment by benhillis** [comment] 2017-02-01 01:43
I was able to hit this once on my laptop but can't seem to reproduce this any more.

@pkerichang if you are able to reproduce this consistently it would be helpful to provide the output of this command:

`strace -v -s 256 ps aux`

**Comment by stehufntdev** [comment] 2017-02-03 00:14
I managed to hit a similar failure locally by running the command after adjusting my system time forward and backwards, and submitted a fix for the way start times are returned for threads.

I never hit the hibernate issue, but it's likely the same cause but please let us know if this comes up again after the fix hits insider builds soon.

**Comment by pkerichang** [comment] 2017-02-03 00:32
Thanks, a lot, sometimes when my computer wake up from sleep the login screen will show the time it went to sleep instead of the current time and won't update until a few second later.  This is probably similar issue.

Which insider version will be fix be in?  That way I can watch out to see if I get the same issue.  Thanks.

**Comment by benhillis** [comment] 2017-02-03 00:34
@pkerichang - definitely sounds like the issue @stehufntdev identified could be the root cause then. Stephen just checked in the change so it should be in an insider build in 1-2 weeks.

**Closed** 2017-05-20 16:52 UTC
Labels: fixedincreatorsupdate, need-repro

**Comment by bityob** [comment] 2018-05-28 06:13
Hi, this error happened to me also today - 

```bash
bit@mymachine:~$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   8304   104 ?        Ss   Jun04   0:01 /init ro
<...removed some rows...>
Signal 11 (SEGV) caught by ps (procps-ng version 3.3.10).
root     15472  0.0  0.0  19568  1120 ?        Ssps:display.c:66: please report this bug
Segmentation fault (core dumped)
```

OS Build - 17134.1

Regarding of @benhillis comment above - 

This is the tail output of the command - `strace -v -s 256 ps aux`

```bash
stat("/etc/localtime", {st_dev=makedev(0, 2), st_ino=281474977023961, st_mode=S_IFREG|0644, st_nlink=2, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=1129, st_atime=2018/02/04-16:23:13.751519800, st_mtime=2018/05/14-12:15:13.707070500, st_ctime=2018/05/14-12:15:13.707070500}) = 0
stat("/etc/localtime", {st_dev=makedev(0, 2), st_ino=281474977023961, st_mode=S_IFREG|0644, st_nlink=2, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=1129, st_atime=2018/02/04-16:23:13.751519800, st_mtime=2018/05/14-12:15:13.707070500, st_ctime=2018/05/14-12:15:13.707070500}) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x1c} ---
write(2, "Signal 11 (SEGV) caught by ps (procps-ng version 3.3.10).\n", 58) = 58
write(1, "root     15472  0.0  0.0  19568  1120 ?        Ss", 49) = 49
write(2, "ps:", 3)                      = 3
write(2, "display.c:66: ", 14)          = 14
write(2, "please report this bug", 22)  = 22
write(2, "\n", 1)                       = 1
rt_sigaction(SIGSEGV, {SIG_DFL, [SEGV], SA_RESTORER|SA_RESTART, 0x7f78f8e254b0}, {0x403220, ~[RTMIN RT_1], SA_RESTORER, 0x7f78f8e254b0}, 8) = 0
kill(16100, SIGSEGV)                    = 0
rt_sigreturn({mask=[]} <unfinished ...>
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_USER, si_pid=16100, si_uid=1000} ---
+++ killed by SIGSEGV (core dumped) +++
```

Do you needs more details? 

I saved whole output to file, if needed.
