### ISSUE TITLE
Node-dev cannot be installed globally

### ISSUE THREAD

**Issue by thenitai** [Microsoft/BashOnWindows#1689] opened 2017-02-10 18:38 UTC
* A brief description

node-dev cannot be installed globally

* Expected results

node-dev being installed globally :)

* Actual results (with terminal output if applicable)

At the end of the installation I see:

npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "node-dev"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules/node-dev
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules/node-dev'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules/node-dev'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules/node-dev' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nitai/npm-debug.log

* Your Windows build number

15031

* Required packages and commands to install

install node then 
npm install -g node-dev

**Comment by benhillis** [comment] 2017-02-10 18:48
To install global node packages you need to run "sudo npm install -g node-dev"

**Comment by thenitai** [comment] 2017-02-10 18:52
Apologies I've failed to mention that installing with sudo throws the following error:

```
Error: could not get uid/gid
net.js:145
    this._handle.open(options.fd);
                 ^

Error: EINVAL: invalid argument, uv_pipe_open
    at Error (native)
    at new Socket (net.js:145:18)
    at createWritableStdioStream (internal/process/stdio.js:156:16)
    at process.getStdout [as stdout] (internal/process/stdio.js:10:14)
    at console.js:100:37
    at NativeModule.compile (bootstrap_node.js:497:7)
    at Function.NativeModule.require (bootstrap_node.js:438:18)
    at get (bootstrap_node.js:254:34)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/uid-number/get-uid-gid.js:16:1)
    at Module._compile (module.js:570:32)

    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

**Comment by benhillis** [comment] 2017-02-10 18:56
No worries.  In that case this is a duplicate of #1683 which we have fixed internally and will be in an upcoming insider build.

**Closed by benhillis** 2017-02-10 18:56 UTC

**Comment by thenitai** [comment] 2017-02-10 20:01
Awesome. Thank you.
