### ISSUE TITLE
Cannot handle double slashes in soft links

### ISSUE THREAD

**Issue by ocaisa** [Microsoft/BashOnWindows#1503] opened 2016-12-14 18:55 UTC
* A brief description
If `//` is used in a soft link, it is considered a directory

* Expected results
```
touch file
ln -s .//file file_lnk
```
Link should still work as a soft link even with `//` in the path

* Actual results (with terminal output if applicable)
`cat: file_lnk: Is a directory`

* Your Windows build number
14393.479

* Steps / All commands required to reproduce the error from a brand new installation 
```
touch file
ln -s .//file file_lnk
ll file_lnk # Everything looks fine
cat file_lnk # Broken
```

**Comment by benhillis** [comment] 2016-12-15 16:26
This is a duplicate of #1147 which is fixed in 14936.

**Closed by benhillis** 2016-12-15 16:26 UTC
