### ISSUE TITLE
Ctrl-C doesn't work in any conhost to cancel the currently typed command.

### ISSUE THREAD

**Issue by AaronFriel** [Microsoft/BashOnWindows#1581] opened 2017-01-10 23:14 UTC
I understand #1569 reports an issue with Bash, but it's normal for me when typing in a terminal to use "Ctrl-C" to cancel the currently typed command and clear the current input.

Right now that doesn't work in any console that uses conhost, and I'm not sure where to report that.

Steps to reproduce:

Steps:
1. Type "foobar" into a console.
2. Press Ctrl-C

Expected behavior:

Input is cleared.

Actual behavior:

Nothing happens.

**Comment by jackchammons** [comment] 2017-01-10 23:20
Duplicate of #1569

**Closed by jackchammons** 2017-01-10 23:20 UTC
