### ISSUE TITLE
Emacs crashes when I use "M-x list-packages"

### ISSUE THREAD

**Issue by ijean** [Microsoft/BashOnWindows#2088] opened 2017-05-12 00:42 UTC
Hello,

I'm using Windows 10 Creators Update, version 10.0.15063, and a fresh WSL install (Ubuntu 16.04.2). I've installed Emacs with:

`sudo apt install emacs-nox`

When I use 

`M-x list-packages`

the packages list is shown, however any key I press Emacs is put in background and crashes. This basically means, that it is impossible to check the packages list and select what I want to install.

**Comment by sunjoong** [comment] 2017-05-12 03:15
@ijean - I have no idea what makes that problem, but hope you to find the way fixing that or workaround, so it might be helpful to clear issue that I can use "M-x list-packages", I think. I'm a gentoo linux user on WSL. I had installed app-editors/emacs-24.5-r3 package, and could checked and installed some pacages with emacs package manager; Some differences like ubuntu and gentoo, emacs-nox and emacs, but you could use emacs package manager on ubuntu, I think. Hmm... I would test with emacs, not emacs-nox, and VcXsrv Windows X Server on ubuntu in your shoses. Good luck.

**Comment by ijean** [comment] 2017-05-12 12:34
@sunjoong emacs-nox is basically emacs without the X parts, compiled from the same source as emacs.

**Comment by fcicq** [comment] 2017-05-12 20:48
please only report issues with the latest insider build (161xx), I guess the fixes will NEVER be backported to 14393.

**Comment by marcogroppo** [comment] 2017-05-13 11:47
@ijean it doesn't really crash, but it receives a SIGTTIN signal. If you type fg you can see that Emacs is still running, but the output is garbled. IMHO this issue is terminal-related

**Comment by ijean** [comment] 2017-05-13 13:26
@marcogroppo Thanks, this makes sense. I guess a simple test would be to connect, through ssh, to a running WSL from a Linux VM to see if the problem persist.

**Comment by marcogroppo** [comment] 2017-05-13 14:15
@ijean good idea! I don't have a VM here so I've tried to connect through SSH using Putty, but unfortunately the behavior was the same. I don't know, maybe it's not the terminal's fault after all... On the positive note: it works fine in graphical (X Windows) mode. 
These are the last lines of strace output when it fails (-nw, terminal mode):

```
ioctl(5, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_REALTIME, {1494684458, 125529400}) = 0
clock_gettime(CLOCK_REALTIME, {1494684458, 125613200}) = 0
clock_gettime(CLOCK_REALTIME, {1494684458, 125676500}) = 0
pselect6(8, [5 6 7], [], NULL, {66, 999916200}, {NULL, 8}) = 1 (in [5], left {59, 62414200})
clock_gettime(CLOCK_REALTIME, {1494684466, 63476000}) = 0
ioctl(5, FIONREAD, [3])                 = 0
read(5, 0x7fffceb00280, 3)              = -1 EINTR (Interrupted system call)
--- SIGTTIN {si_signo=SIGTTIN, si_code=SI_KERNEL} ---
```

fd `5` should be `/dev/tty`

**Comment by ijean** [comment] 2017-05-13 14:18
@marcogroppo OK, so I've connected remotely to WSL from a Mac machine, started Emacs (way faster than when I start directly on WSL!!!) but the bug persist. I mean, after I list the packages the Emacs process is still suspended, when I try to get the process in foreground with *fg* I get the same garbled screen.

**Comment by marcogroppo** [comment] 2017-05-13 17:07
@ijean yeah as I said no luck on Putty, either... Regarding the slow start see #1775

**Comment by sunjoong** [comment] 2017-05-13 20:11
Hmm... Some differences!! I launched "`emacs -nw`" on ubuntu, "`M-x list-packages`", press down arrow key, and then.... it really "`[1]+  Stopped                 emacs -nw`". But, there was no that happening on gentoo with the same command "`emacs -nw`".

**Comment by marcogroppo** [comment] 2017-05-14 08:47
@sunjoong what version of Emacs do you have on Gentoo?

**Comment by sunjoong** [comment] 2017-05-14 09:09
@ijean - app-editors/emacs-24.5-r3 and USE flag is "X gfile gtk inotify libxml2 png ssl svg toolkit-scroll-bars xft xpm zlib -Xaw3d -acl -alsa (-aqua) -athena -dbus -games -gconf -gif -gpm -gsettings -gtk3 -gzip-el -hesiod -imagemagick -jpeg -kerberos -livecd -m17n-lib -motif -pax_kernel (-selinux) -sound -source -tiff -wide-int".

**Comment by marcogroppo** [comment] 2017-05-14 09:22
@sunjoong I've recompiled the most recent version of Emacs (25.2.1) on Ubuntu but no luck: same issue on `M-x list-packages`. The difference in behavior between WSL/Ubuntu and WSL/Gentoo is interesting... maybe there is some difference in glibc or terminfo?

**Comment by sunjoong** [comment] 2017-05-14 09:30
@ijean - Well.... sys-libs/ncurses-6.0-r1 with USE flag "abi_x86_64 amd64 cxx elibc_glibc kernel_linux threads unicode" and sys-libs/glibc-2.23-r3 with "abi_x86_64 amd64 elibc_glibc kernel_linux suid".

**Comment by marcogroppo** [comment] 2017-05-14 09:35
@sunjoong same versions on ubuntu (ncurses 6.0 and glibc 2.23)...

**Comment by sunjoong** [comment] 2017-05-14 09:43
@ijean - Hmm.... I have no idea whether ncurses and glibc might be relevant or not, but if relevant, threads USE flag of ncurses and suid of glibc might be different; I appened those.

**Comment by ijean** [comment] 2017-05-18 04:25
I've also tried Emacs on the latest insider preview of Windows 10, version 10.0.16199.1000. Same errors when I use Emacs from console.

**Comment by sunjoong** [comment] 2017-05-18 04:55
@ijean - I think... it could be a metter of linux, i.e., ubuntu, rather than WSL, because no metter in gentoo.
@marcogroppo  - sorry. In above mentions.... I called @ijean, not you.

**Comment by sunjoong** [comment] 2017-05-18 07:22
I compared linked libraries of emacs in ubuntu and in my gentoo by `ldd` comand; There were some differences. I omit common libraries and ignore the differences of version.

ubuntu                     | gentoo
---------------------- | -----------------------
libacl.so.1                 | libEGL.so.1
libasound.so.2          | libGL.so.1
libattr.so.1                | libICE.so.6
libdbus-1.so.3          | libSM.so.6
libgcc_s.so.1             | libX11-xcb.so.1
libgcrypt.so.20         | libX11.so.6
libgpg-error.so.0     | libXau.so.6
libgpm.so.2             | libXcomposite.so.1
libicudata.so.55       | libXcursor.so.1
libicuuc.so.55          | libXdamage.so.1
libidn.so.11             | libXdmcp.so.6
libp11-kit.so.0         | libXext.so.6
libselinux.so.1         | libXfixes.so.3
libstdc++.so.6         | libXft.so.2
libsystemd.so.0        | libXi.so.6
libtinfo.so.5             | libXpm.so.4
. |       libXrandr.so.2
. |       libXrender.so.1
. |       libXxf86vm.so.1
. |       libatk-1.0.so.0
. |       libblkid.so.1
. |       libbsd.so.0
. |       libbz2.so.1
. |       libcairo.so.2
. |       libcroco-0.6.so.3
. |       libdrm.so.2
. |       libexpat.so.1
. |       libfontconfig.so.1
. |       libfreetype.so.6
. |       libgdk-x11-2.0.so.0
. |       libgdk_pixbuf-2.0.so.0
. |       libglapi.so.0
. |       libgtk-x11-2.0.so.0
. |       libharfbuzz.so.0
. |       libmount.so.1
. |       libncurses.so.6
. |       libpango-1.0.so.0
. |       libpangocairo-1.0.so.0
. |       libpangoft2-1.0.so.0
. |       libpixman-1.so.0
. |       libpng16.so.16
. |       librsvg-2.so.2
. |       libuuid.so.1
. |       libxcb-dri2.so.0
. |       libxcb-glx.so.0
. |       libxcb-render.so.0
. |       libxcb-shm.so.0
. |       libxcb-xfixes.so.0
. |       libxcb.so.1

I had thought emacs in ubuntu be also linked to ncurses, but it isn't. Some interesting libraries like libgpm, libselinux and libsystemd are linked, but I have no idea those are relevant or not.

**Comment by marcogroppo** [comment] 2017-05-18 08:39
on Ubuntu you've probably installed the emacs-nox package, which does not include X Windows support. I believe that libtinfo is a subset of ncurses (libncurses includes libtinfo)

**Comment by sunjoong** [comment] 2017-05-18 09:57
@marcogroppo - Yes, I know. My first suspect is ncurses, i.e., libtinfo, and second would be gpm.

**Comment by ijean** [comment] 2017-05-18 12:30
OK. I've tried to build from sources disabling all non-essential packages:

`./configure --without-x --without-all`

the above will disable both dbus and gpm. 

Same problem. I think I will simply use an Emacs binary compiled for Windows until WSL becomes more compatible with Linux.

**Comment by sunjoong** [comment] 2017-05-18 12:58
@ijean - I don't know what makes that. It might be from ncuses or glibc or other effects we don't know yet. I just guess.... what if it from console library.... what's different from mine to ubuntu? As mentioned above, I built up my gentoo system with ncurses supporting unicode and threads and I'm not sure that's same in ubuntu; I don't know that's why my emacs of gentoo is more compatible with WSL than that of ubuntu. That might be or might not, so I said that's my prime suspect; If I had more knowledge to ubuntu, I could check it, so still suspect.

**Comment by ijean** [comment] 2017-05-19 00:45
In the end I've installed XFCE 4, started Emacs GUI which works fine. Even under XFCE 4 starting emacs -nw will crash for listing the packages!

Anyway, I use the GUI version only when I need to install a package from ELPA or MELPA. Otherwise, for normal text editing emacs -nw seems to work.

It must be something related to ncurses or terminfo that is triggered when Emacs downloads the list of packages.

**Comment by Jonjoe** [comment] 2017-06-04 22:28
Hey! Appreciate the effort going in to try and fix this. 

Any further news?

**Comment by sunjoong** [comment] 2017-06-08 05:57
@ijean - I found some issues older than this but same to, and an interesting sentence
> WSL installs Ubuntu 14.04 [*] and installing the full emacs24 package does not show the issue (notice that also the full package, a GTK3 build, starts in terminal mode, no GUI).

in https://lists.gnu.org/archive/html/emacs-devel/2016-12/msg00725.html but did not test yet.

In my case, I had compiled emacs to support gtk2 on gentoo on WSL, and it does not make this problem even though in text terminal mode with -nw option.

**Comment by Jonjoe** [comment] 2017-06-11 12:56
Thanks @sunjoong !!!

**Comment by sunjoong** [comment] 2017-06-12 11:21
> > WSL installs Ubuntu 14.04 [*] and installing the full emacs24 package does not show the issue (notice that also the full package, a GTK3 build, starts in terminal mode, no GUI).
>
> in https://lists.gnu.org/archive/html/emacs-devel/2016-12/msg00725.html but did not test it yet.

Unfortunately, full emacs24 package show the issue in my test.

And... I found GNU bug report number 25221 - https://debbugs.gnu.org/cgi/bugreport.cgi?bug=25221

In there, I found this saying;
> While with previous installation (WSL-Ubuntu 14.04, Emacs-24.3), Emacs  worked fine, also with the package manager, now it shows the same issues I had with Emacs-25 branch or Emacs-master.. It seems I can't install/upgrade Elpa/Melpa packages any more...

But... I'm not sure.

**Comment by jrhz** [comment] 2017-07-24 18:28
This continues to be an issue on WSL. I generated a bug report for the Emacs folks: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27804 who do not believe this to be an Emacs problem, so it's unclear what the next steps are to potentially debug this. My particular system is running stock WSL:

`$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial`

With emacs-nox snapshots:
`$ emacs --version
GNU Emacs 26.0.50`

**Comment by benhillis** [comment] 2017-07-24 18:41
@jrhz - I'm a total emacs noob but would be happy to look into this.  After I launch emacs how to I input the `M-x list-packages` command?

**Comment by jrhz** [comment] 2017-07-24 18:47
Hit Esc then x then type list-packages then enter. At the next screen (hopefully a list of packages) use a movement key like down arrow.

**Comment by Eli-Zaretskii** [comment] 2017-07-25 05:13
Could it be that in this scenario Emacs sends some control characters to the terminal that is interpreted as a command to background the calling process?  The strace output shown above is very short, did someone try to look farther up the list of system calls, around the place where Emacs writes to the terminal?

**Comment by jrhz** [comment] 2017-07-25 14:50
Running it as `emacs -nw -Q -f list-packages` with strace, the last bit of strace output is:
```
readlinkat(AT_FDCWD, "/home/jrh/.emacs.d/elpa", 0x7fffd5dee2f0, 1024) = -1 EINVAL (Invalid argument)
newfstatat(AT_FDCWD, "/home/jrh/.emacs.d/elpa", {st_mode=S_IFDIR|0777, st_size=512, ...}, AT_SYMLINK_NOFOLLOW) = 0
rt_sigprocmask(SIG_BLOCK, [WINCH IO], NULL, 8) = 0
write(5, "\33[29;53H\33[?25l\33[30m\33[48;5;250m) "..., 74) = 74
rt_sigprocmask(SIG_UNBLOCK, [WINCH IO], NULL, 8) = 0
clock_gettime(CLOCK_REALTIME, {1500993887, 507344300}) = 0
clock_gettime(CLOCK_REALTIME, {1500993887, 507427200}) = 0
clock_gettime(CLOCK_REALTIME, {1500993887, 507511300}) = 0
clock_gettime(CLOCK_REALTIME, {1500993887, 507599500}) = 0
rt_sigprocmask(SIG_BLOCK, [WINCH IO], NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [WINCH IO], NULL, 8) = 0
clock_gettime(CLOCK_REALTIME, {1500993887, 507924500}) = 0
ioctl(5, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_REALTIME, {1500993887, 508093900}) = 0
clock_gettime(CLOCK_REALTIME, {1500993887, 508174300}) = 0
rt_sigprocmask(SIG_BLOCK, [INT], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
pselect6(6, [5], [], NULL, {2, 13348500}, {NULL, 8}) = 0 (Timeout)
rt_sigprocmask(SIG_BLOCK, [INT], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
clock_gettime(CLOCK_REALTIME, {1500993889, 525142900}) = 0
clock_gettime(CLOCK_REALTIME, {1500993889, 526140700}) = 0
rt_sigprocmask(SIG_BLOCK, [WINCH IO], NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [WINCH IO], NULL, 8) = 0
clock_gettime(CLOCK_REALTIME, {1500993889, 528562400}) = 0
clock_gettime(CLOCK_REALTIME, {1500993889, 529168800}) = 0
rt_sigprocmask(SIG_BLOCK, [INT], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
pselect6(6, [5], [], NULL, {3589, 497338400}, {NULL, 8}) = 1 (in [5], left {3571, 631524400})
rt_sigprocmask(SIG_BLOCK, [INT], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
clock_gettime(CLOCK_REALTIME, {1500993907, 400656900}) = 0
ioctl(5, FIONREAD, [3])                 = 0
read(5, 0x7fffd5df11e0, 3)              = -1 EINTR (Interrupted system call)
--- SIGTTIN {si_signo=SIGTTIN, si_code=SI_KERNEL} ---
```

The `pselect6(6, [5], [], NULL, {3589, 497338400}, {NULL, 8}) = 1 (in [5], left {3571, 631524400})` is where emacs is waiting for an input and I hit an arrow key. Then we get the `rt_sigprocmask(SIG_BLOCK, [INT], [], 8) = 0` and the rest.

**Comment by Eli-Zaretskii** [comment] 2017-07-25 15:06
So can it be that this part:

    write(5, "\33[29;53H\33[?25l\33[30m\33[48;5;250m) "..., 74) = 74

causes Emacs to be placed in background?

More generally, how about recording what Emacs outputs in a "dribble file", and then replaying it from, say, `cat`, to see if the result is a backgrounded application?  IOW, I think the question here is what causes Emacs to become backgrounded in the first place?

**Comment by benhillis** [comment] 2017-07-25 15:17
I tried this on a recent internal build and it seems to be working for me.  I know one of the other developers fixed some terminal related bugs recently, perhaps this was resolved by one of his changes.

The packages list and I can use the arrow keys to select various packages and view the details.  Are there any other steps required to reproduce the hang?

![image](https://user-images.githubusercontent.com/17727402/28579382-604b0642-7111-11e7-97f3-452afc7f07c3.png)

**Comment by jrhz** [comment] 2017-07-25 15:20
No other steps are required to trigger the bug. You're able to get further than I am, so it would appear that fixes it.

**Comment by marcogroppo** [comment] 2017-07-25 16:53
@benhillis if I may ask: are you using Ubuntu LTS on your insider build? Another user said that he could reproduce the issue only on Ubuntu

**Comment by benhillis** [comment] 2017-07-25 17:11
@marcogroppo - Yes I'm using I'm using Ubuntu 16.04 and Windows build 16251 (internal build).  The terminal related changes I mention above should be in a Windows Insider build soon.

**Comment by marcogroppo** [comment] 2017-07-25 17:40
@benhillis great! thanks

**Comment by benhillis** [comment] 2017-08-03 16:51
I believe this is fixed in 16257, if somebody is able to confirm that would be great!

**Comment by mrmcavoy715** [comment] 2017-09-03 15:01
I had the same issue. After upgrading to windows build 16278, the problem is resolved for me.

**Comment by talyian** [comment] 2017-09-21 22:27
Confirmed that installing Fall Creators Update fixed this issue for me.

**Comment by jrhz** [comment] 2017-09-26 17:25
Yes, Emacs 27.0.50 running on build16278 this is now resolved. I suspect this can be closed now.

**Comment by sunilmut** [comment] 2017-09-28 18:09
Thanks for the confirmation.

**Closed by sunilmut** 2017-09-28 18:09 UTC
Labels: fixinbound

**Comment by jpow187** [comment] 2017-11-15 08:42
I just find the package I want on melpa webpage then use the command `package-install` <RET> `[nameOfPackage]`
