### ISSUE TITLE
bash command window lockup after execute command 'mv'

### ISSUE THREAD

**Issue by echoonly** [Microsoft/BashOnWindows#1700] opened 2017-02-14 01:48 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
I'm trying to rename a folder in bash on windows by command 'mv', but it seems lock up when I knock the enter key. I've tried to restart bash, kill in windows task manager, but it still no response.  restart windows is works, but obviously it's not a good solution.
* Expected results
rename the folder
* Actual results (with terminal output if applicable)
no response
* Your Windows build number
1607 (OS inside 14393)
* Steps / All commands required to reproduce the error from a brand new installation 
execute mv command `mv ../foldername/ .`
* Strace of the failing command

* Required packages and commands to install
I run this command in tmux window(ver: tmux master)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment] 2017-02-14 02:00
This is a duplicate of #1008.

**Closed by benhillis** 2017-02-14 02:00 UTC
