### ISSUE TITLE
Can't execute i386 binary file

### ISSUE THREAD

**Issue by will131** [Microsoft/BashOnWindows#2186] opened 2017-06-03 11:24 UTC
* Your Windows build number: 

**10.0.15063**

* What you're doing and what's happening:  

I try to run i386 file in BashOnWindows.
I wrote a simple C program 'A.c' and use 'gcc A.c -m32' to make the file 'a.out'
When I use './a.out' to execute it.
It shows ''**bash: ./a.out: cannot execute binary file:**"

I use Google to find the solution for Ubuntu and try them.
When I use 'dpkg --print-foreign-architectures' to check out.
It shows 'i386' which means the system support  i386 binary file.
But when I use './a.out', it still shows ''**bash: ./a.out: cannot execute binary file:**"

* What's wrong / what should be happening instead:

I am a rookie, and I don't know what is wrong.

**Comment by CherryDT** [comment] 2017-06-03 13:57
WSL supports only 64-bit (you can consider upvoting the [relevant thread on User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13359735-add-x32-support) so it will only work without `-m32`.

**Comment by will131** [comment] 2017-06-03 15:29
@CherryDT Thanks~

**Comment by benhillis** [comment] 2017-06-03 17:33
Marking as duplicate of #228.

**Closed by benhillis** 2017-06-03 17:33 UTC
