### ISSUE TITLE
Symbolic link 

### ISSUE THREAD

**Issue by dpereira2016** [Microsoft/BashOnWindows#865] opened 2016-08-11 14:51 UTC
When create a symbolic link for directory ending with a slash it have an unexpected behavior.

Example:
- Create a symbolic link for a directory, for example:

  `root@THOR:/var/www/html# ln -s /usr/share/phpmyadmin/ . `
- Now enter in the directory:

  `root@THOR:/var/www/html# cd phpmyadmin `
  `root@THOR:/var/www/html/phpmyadmin# `
- Now edit the file `config.sample.inc.php`, for that write `vim conf` and then auto-complete the command with tab key:

  `root@THOR:/var/www/html/phpmyadmin# vim config.sample.inc.php/`

  The filename auto-completes with a slash and if you tab twices it will show the contents of the phpmyadmin diretory:

`root@THOR:/var/www/html/phpmyadmin# vim config.sample.inc.php/`
`browse_foreigners.php/       index.php/                   server_export.php/           tbl_move_copy.php/
changelog.php/               js/                          server_import.php/           tbl_operations.php/
chk_rel.php/                 libraries/                   server_plugins.php/          tbl_printview.php/
config.sample.inc.php/       license.php/                 server_privileges.php/       tbl_relation.php/
db_create.php/               locale/                      server_replication.php/      tbl_replace.php/
db_datadict.php/             navigation.php/              server_sql.php/              tbl_row_action.php/
db_events.php/               phpinfo.php/                 server_status_advisor.php/   tbl_select.php/
db_export.php/               phpmyadmin.css.php/          server_status_monitor.php/   tbl_sql.php/
db_import.php/               pmd_display_field.php/       server_status.php/           tbl_structure.php/
db_operations.php/           pmd_general.php/             server_status_queries.php/   tbl_tracking.php/
db_printview.php/            pmd_pdf.php/                 server_status_variables.php/ tbl_triggers.php/
db_qbe.php/                  pmd_relation_new.php/        server_variables.php/        tbl_zoom_select.php/
db_routines.php/             pmd_relation_upd.php/        setup/                       themes/
db_search.php/               pmd_save_pos.php/            show_config_errors.php/      themes.php/
db_sql.php/                  prefs_forms.php/             sql.php/                     transformation_overview.php/
db_structure.php/            prefs_manage.php/            tbl_addfield.php/            transformation_wrapper.php/
db_tracking.php/             print.css/                   tbl_change.php/              url.php/
db_triggers.php/             querywindow.php/             tbl_chart.php/               user_password.php/
export.php/                  schema_edit.php/             tbl_create.php/              version_check.php/
favicon.ico/                 schema_export.php/           tbl_export.php/              view_create.php/
file_echo.php/               server_binlog.php/           tbl_get_field.php/           view_operations.php/
gis_data_editor.php/         server_collations.php/       tbl_gis_visualization.php/   webapp.php/
import.php/                  server_databases.php/        tbl_import.php/
import_status.php/           server_engines.php/          tbl_indexes.php/`

This is not the expect behavior, when we use the tab key it should autocomplete the filename without a slash.

If we create the symbolic link without the slash in the directory it works as expected (`ln -s /usr/share/phpmyadmin . `)

Thanks and best regards,
Daniel Pereira

**Comment by benhillis** [comment] 2016-08-11 15:08
Duplicate of #650.

Thanks for reporting.

**Closed by benhillis** 2016-08-11 15:08 UTC
