### ISSUE TITLE
Various bugs (uptime, df, ip/ifconfig, ps) found with Neofetch

### ISSUE THREAD

**Issue by iandrewt** [Microsoft/BashOnWindows#1301] opened 2016-11-01 02:02 UTC
* A brief description

Some standard built in commands do not work or do not produce exepcted output

Some of these bugs may be duplicates, sorry.

`uptime`: prints time since terminal was opened instead of system uptime
`df`: Doesn't print correct information
`ip/ifconfig`: Crashes on startup (I think this is a known bug)
`ps`: Only prints processes from WSL (this probably can't be changed, but also means we cannot get CPU usage info for Neofetch)

These are taken from dylanaraps/neofetch#399

* Expected results

`uptime`: Prints time since boot (or perhaps add a flag to choose between these, Neofetch knows when it's running on WSL)
`df`: When using `--total`, should print total disk space and total usage (On my system, this is the total usage across disks: 322G / 1.1T)
`ip/ifconfig`: Prints network information
`ps`: Prints all processes on the system

* Actual results (with terminal output if applicable)

`uptime`: Prints time since the Bash window was opened
`df`: Prints incorrect information (resulting in 300G / 557G when I have a 120GB SSD and a 1TB HDD)
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs          112G   60G   52G  54% /
tmpfs           112G   60G   52G  54% /run
none            112G   60G   52G  54% /run/lock
none            112G   60G   52G  54% /run/shm
none            112G   60G   52G  54% /run/user
```
`ip/ifconfig`: Fails to run at all (fairly sure this is a known bug)
`ps`: Prints processes running in WSL

* Your Windows build number

10.0.14393.351

* Steps / All commands required to reproduce the error from a brand new installation 

1. Download [Neofetch](https://github.com/dylanaraps/neofetch) and `cd` to it
2. Run `./neofetch --test` and see where information does not appear to be correct

* Required packages and commands to install

Neofetch only uses built in commands for this information, but you can install it to see what I'm seeing more clearly

See also [this transcript of the Gitter chat when this was being discussed](https://gist.github.com/iandrewt/68f3a9d42c441fa355d9535cad92cb53)

**Comment by aseering** [comment] 2016-11-01 14:51
Hi @iandrewt -- thanks for reporting this!

WSL doesn't actually implement any of these commands itself.  Instead, it downloads the raw binaries from the Ubuntu repository and uses those.  (So, for example, if you would like a flag added to a binary, that request would best be addressed to Canonical, and they would add it for both Linux and WSL because the binary doesn't know whether it's running under WSL or not.)

If the commands aren't behaving properly, that means that some underlying piece of WSL-emulated kernel functionality isn't behaving as expected, or (because WSL doesn't currently use systemd to start up) some piece of at-startup logic isn't working the same way in WSL as in Linux-Ubuntu.  The WSL team can, generally speaking, fix that.  So, to set expectations, that's what a fix would look like.  Also, if you dig a little deeper to figure out what underlying functionality is behaving differently than expected, that information would help the team prioritize and address these issues more quickly.

**Comment by xilun** [comment] 2016-11-02 18:56
I'd say he expects different results returned by the kernel.
However, this needs to be reproduced on an Insider build (and the different problems separated in different issues).

**Comment by sunilmut** [comment] 2016-11-02 19:13
Agree with @xilun. My recommendation would also be to open different issues for different tools (for effective tracking), and possibly with results from the latest insider build.

**Comment by sunilmut** [comment] 2016-11-10 00:11
Just an update that 'ifconfig' and the 'ip' commands for network enumeration should be working in the latest fast insider build 14965, also see [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes)

**Comment by sunilmut** [comment] 2016-11-18 05:42
Closing this out since ifconfig is fixed now. Recommend opening new tasks for individual commands that are failing (if there is not one already).

**Closed by sunilmut** 2016-11-18 05:42 UTC
Labels: fixed, ifconfig, network
