### ISSUE TITLE
BSOD: cp -rv ./* ~ when .=/mnt/c/Users/...

### ISSUE THREAD

**Issue by mobluse** [Microsoft/BashOnWindows#2404] opened 2017-08-08 20:31 UTC
If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

This is a BSOD, but it has now been investigated by secure, and was harmless, but it still needs to be fixed.

* Your Windows build number:  Microsoft Windows [Version 10.0.16257.1]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I run https://www.microsoft.com/en-us/store/p/ubuntu/9nblggh4msv6

pi@lenovo5:/mnt/c/Users/pi/Downloads/home$ cp -rv ./* ~
*Writes a few lines*
BSOD

* What's wrong / what should be happening instead:
It should write all files and copy them. After BSOD the computer reboots and when I start Ubuntu again, no files or directories were copied.
I have rather many files and directories in home. The reason I copied all files from ~ to home was to install Ubuntu in the new way from scratch from Windows Store (this worked and Ubuntu has newest dist-upgrade, and then copy them back.

* Strace of the failing command, if applicable:  -

It is probably related to https://github.com/Microsoft/BashOnWindows/issues/2392 .

**Comment by benhillis** [comment] 2017-08-08 20:46
@mobluse - I suspect you are right that this is the same underlying issue as #2392 for which we have a fix inbound.  Will you reply to the mail that secure sent you and let them know that benhill would like to see the dump so I can confirm that the issue is fixed?

**Comment by mobluse** [comment] 2017-08-08 21:35
Yes, I did that now.

**Comment by benhillis** [comment] 2017-08-10 22:13
@mobluse - I was forwarded the dump and confirmed it is the same issue as #2392, thanks for sending that along.  I'm going to close this as a duplicate, it looks like the fix will be in the next Insider build (next week).

**Closed by benhillis** 2017-08-10 22:13 UTC
