### ISSUE TITLE
Bash.exe doesn't start into some directories

### ISSUE THREAD

**Issue by rodrymbo** [Microsoft/BashOnWindows#1528] opened 2016-12-21 17:44 UTC
* A brief description

If I start bash.exe from a cmd prompt in c:\temp or d:\temp, it comes up with `pwd` showing `/mnt/c/temp` or `/mnt/d/temp` as expected.
If I start bash.exe from a cmd prompt in e:\temp, bash comes up in ~ (home) directory.

* Expected results

The [Command Reference](https://msdn.microsoft.com/en-us/commandline/wsl/reference) says "Launches the Bash shell in the current directory." 

It used to work that way. I don't know when it stopped working. 

I want it to run a script on the current directory when I drop the script from that directory in Explorer onto a drop-target that starts bash.exe with `-c /path/to/scriptname`. (Drop target is a vbs script that converts the DOS path to WSL format to use with -c.) It recently stopped working on that directory and started trying to run on the contents of ~, which is not helpful.

A workaround is to add something like this at the top of the script:

```
DIR=`dirname $0`
pushd $DIR

```
So it isn't a game stopper for me (and I should probably have started off using that little trick).

Nevertheless, the command reference says that bash.exe starts 'in the current directory', so either it should be fixed so it once again starts in the 'current directory', or the command reference should be fixed to specify which "current directories" we should expect it to not start in.

The E: drive is a mounted drive. Yes, if I started bash.exe and mounted the drive with bash still running, it wouldn't find the drive, but since I start bash well after the drive is mounted, the drive behaves pretty much the same as C: or D: in all other respects. And as I said, it used to work. And I can `cd` or `pushd` to any directory on the E: drive with no problems once I am in bash.exe. Permissions seem to be just fine.

Maybe I'm the only one that this is happening to?

Let me know if you need strace or whatever.

* Your Windows build number

14986

**Comment by fpqc** [comment] 2016-12-21 17:46
Is E:  a fixed NTFS device?

**Comment by rodrymbo** [comment] 2016-12-21 20:47
It is NTFS. It behaves like it is fixed once mounted, but I haven't researched to learn whether it is identified as fixed in the registry or whatever. And it used to work. So even though it is not a fixed volume in the strictest sense, this new behavior is not welcome. If it were a drive mounted through SMB or a vfat USB drive, I wouldn't mind someone saying "it's not a fixed drive, they just repaired something that wasn't supposed to work before, so now it won't work anywhere".

This looks like #1389 in some ways.

**Comment by benhillis** [comment] 2016-12-27 16:28
@rodrymbo I agree this looks like #1389, which I have been unable to root cause.  Can you please describe your E: volume for me?  Is it different in any way than your other drives for which this is working?

**Comment by benhillis** [comment] 2017-05-20 16:40
Closing as a duplicate of #1389.

**Closed by benhillis** 2017-05-20 16:40 UTC
