### ISSUE TITLE
Detect BashOnWindows from Bash script

### ISSUE THREAD

**Issue by timmontague** [Microsoft/BashOnWindows#844] opened 2016-08-09 20:50 UTC
Is there a documented method for a Bash script to detect if it's running on "Ubuntu on Windows" vs native Ubuntu?

It looks like grepping /proc/version for the string `"Microsoft"` would work, but it could potentially have false positives.

For reference, these are the contents of /proc/version on my machines:

* Ubuntu on Windows:
`Linux version 3.4.0-Microsoft (Microsoft@Microsoft.com) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Wed Dec 31 14:42:53 PST 2014`

* Native Ubuntu:
`Linux version 4.4.0-31-generic (buildd@lgw01-16) (gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2.1) ) #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016`

My Windows build number: `Microsoft Windows [Version 10.0.14393]`

**Comment by benhillis** [comment] 2016-08-09 22:02
I would suggest /proc/sys/kernel/osrelease

Duplicate of #423

**Closed by benhillis** 2016-08-09 22:02 UTC
Labels: duplicate

**Comment by timmontague** [comment] 2016-08-09 22:10
Thank you!

**Comment by matthewpersico** [comment] 2019-07-01 21:08
How about `uname -r` which does the same thing?
