### ISSUE TITLE
tar with symbolic links

### ISSUE THREAD

**Issue by tinysun212** [Microsoft/BashOnWindows#9] opened 2016-04-07 05:09 UTC
I could create a symbolic links by ```ln -s```.

```
root@localhost:~# ls -l kkk
total 0
-rw-rw-rw- 1 root root 14 Apr  7 04:53 atest
lrwxrwxrwx 1 root root  5 Apr  7 04:54 btest -> atest
```

But I can't archive with the ```tar```.
```
root@localhost:~# tar cvf kkk.tar kkk
kkk/
kkk/atest
tar: kkk/btest: Cannot readlink: Invalid argument
tar: Exiting with failure status due to previous errors
```

In reverse, the symbolic links in a ```tar``` file which built on Linux can't be extracted.

**Comment by jokeyrhyme** [comment] 2016-04-07 05:20
Related to #3 and/or #6 ?

**Comment by tinysun212** [comment] 2016-04-07 05:34
The error messages are different.

In my case, ```ln -s``` is working, but not compatible with ```tar```.

Here is the reverse operation output. ( extracting symlinks containing tar whilch is built on real Linux )
```
root@localhost:~# tar tvf /mnt/c/temp/kkk.tar
drwxr-xr-x root/root         0 2016-04-07 05:25 kkk/
lrwxrwxrwx root/root         0 2016-04-07 05:25 kkk/btest -> atest
-rw-r--r-- root/root        12 2016-04-07 05:24 kkk/atest
root@localhost:~# tar xvf /mnt/c/temp/kkk.tar
kkk/
kkk/btest
tar: kkk/btest: Cannot create symlink to ‘atest’: Invalid argument
kkk/atest
tar: Exiting with failure status due to previous errors
```

**Comment by hfaran** [comment] 2016-04-07 08:45
I can echo this: I tried to install rvm from get.rvm.io and the script crashes and burns because of the tar symlink incompatibility.

**Comment by mphaney** [comment] 2016-04-07 15:13
I also can confirm this.  (Running on 64-bit, on the off chance that matters).  Can create symlinks just fine, cannot tar them or untar packages which contain them.  As an interesting consequence, apt packages which contain symlinks (Java) also cannot be installed.

**Comment by christoh** [comment] 2016-04-07 15:42
I was trying to copy files from a real linux box using tar. Also running into the symlink issue. As a workaround I was able to copy the files using bsdtar which creates symlinks correctly.

**Comment by ljharb** [comment] 2016-04-07 20:45
This is affecting http://nvm.sh installs via windows as well. https://github.com/creationix/nvm/issues/1054

**Comment by jbaribeault** [comment] 2016-04-07 21:27
This might relate to is #44 as well...for me anyway, the move won't work on tarballs/zips from CPAN which contain soft links.

**Comment by tomgrek** [comment] 2016-04-08 18:56
+1.
Can't install Meteor due to this issue.
Copying the files from a Linux VM sort of works if you re-create the tarball with the h option (i.e. tar cvfh).

**Comment by filipeaguiar** [comment] 2016-04-09 01:02
As @ljharb said: *nvm* doesn't install properly. And none of the tools that uses symlinks with tar works right now.

**Comment by ljharb** [comment] 2016-04-09 02:46
To clarify, this is affecting `nvm`'s ability to install node. `nvm` itself installs fine.

**Comment by julihermes** [comment] 2016-04-09 18:29
because of this error i am not able to install rbenv

**Comment by SvenGroot** [comment] 2016-04-10 03:15
The tar extraction problem with symlinks is caused by the missing symlinkat syscall (symlink was supported but not the at variant). This bug has been fixed internally.

Similarly, I believe creating a tar file with symlinks fails because readlinkat is missing.

**Comment by boulund** [comment] 2016-04-10 07:49
Just as a note if someone else stumbles upon this: this also affects installation of Miniconda using Continuum Analytics Miniconda installation shell script that extracts a tar archive containing symlinks. 

You get errors like this:

    tar: bin/2to3: Cannot create symlink to ‘2to3-3.5’: Invalid argument

**Comment by Dunkirk** [comment] 2016-04-10 12:34
Having the same trouble installing RVM. I can download the zip version and install manually, but I get a warning at the end of the install:

`  * WARNING: you are missing '/dev/fd' it is important for shell scripting used by RVM,
    You can fix it on most linux systems with:

      ln -sf /proc/self/fd /dev/fd`

/proc/self/fd does exist, but following those instructions gives me:

`root@localhost:~# ln -s /proc/self/fd /dev/fd
ln: failed to create symbolic link ‘/dev/fd’: Operation not permitted`

This is a different error. I make a note here wondering if the (internal) fix would address this, or if we're into some unsupported behavior in the /proc filesystem now.

I got RVM installed manually, but, of course, it wants to install rubies from tar-ed sources, which loops me back around to the original problem, and I'm tired of fighting it.

**Comment by SvenGroot** [comment] 2016-04-10 19:01
DunKirk, that error is due to some limitations of our /dev filesystem that prevent you from creating a link there. We're working to address this. This is separate from the symlinkat error.

**Comment by MadcowD** [comment] 2016-04-10 23:15
@SvenGroot thank you much!

**Comment by jessicah** [comment] 2016-04-11 00:02
I have an example where openat() on a symlink returns no such file or directory despite the symlink existing but not the target. Does the symlinkat fix also apply here?

    # e.g. openat("libsolv.so") fails with no such file or directory
    root@localhost:# ls -l
    total 0
    lwrxwrxwrx 1 root root 12 Apr 10 23:33 libsolv.so -> libsolv.so.1
    root@localhost:#

Example: https://github.com/haiku/haiku/blob/master/src/bin/package/command_extract.cpp#L552

**Comment by sunilmut** [comment] 2016-04-11 22:29
Thanks for the feedback. Support for both symlinkat and readlinkat has been added to the code, but the build has not made it to flighting yet.

**Comment by Edoa** [comment] 2016-04-12 08:54
Is there some kind of workaround for this?

**Comment by perlun** [comment] 2016-04-12 11:05
> Thanks for the feedback. Support for both symlinkat and readlinkat has been added to the code, but the build has not made it to flighting yet.

@sunilmut - any idea about when the new build will be released? Is there a release plan hidden somewhere? :wink:

**Comment by sunilmut** [comment] 2016-04-12 20:07
@perlun - Sorry, that information is not something we can provide reliably at this time. Though, we understand the need for better tracking and availability of information, and are looking into how we can improve that on our side. So, please bear with us until then.

**Comment by jessicah** [comment] 2016-04-14 00:55
> Thanks for the feedback. Support for both symlinkat and readlinkat has been added to the code, but the build has not made it to flighting yet.

@sunilmut Does this also include openat?

**Comment by SvenGroot** [comment] 2016-04-14 01:01
Openat is already supported in the current publicly available build.

**Comment by danbuche** [comment] 2016-04-14 05:13
Will this thread be updated as soon as this functionality gets fixed? Thanks!

**Comment by stewones** [comment] 2016-04-18 15:42
any workaround? i have to install node =/

**Comment by Sekhmet** [comment] 2016-04-18 15:46
@stewones We need to wait for Windows Update.

**Comment by Dunkirk** [comment] 2016-04-22 19:29
Build 14328 seems to have fixed the general symbolic link problem. Awesome, and thanks. However, I encountered this bug by trying to install RVM, and I still can't complete the process because of the related-but-different bug I listed above (about linking /dev/fd). Maybe we could re-open #222 to continue tracking this issue?

**Comment by benhillis** [comment] 2016-04-22 19:30
Sure I'll reopen #222.  Will you add more detail in that thread about the  issue's you're seeing?

**Comment by sunilmut** [comment] 2016-04-22 19:33
@perlrun 
>> any idea about when the new build will be released? Is there a release plan hidden somewhere?
Yes, :). A new Windows build [14328](https://blogs.windows.com/windowsexperience/2016/04/22/announcing-windows-10-insider-preview-build-14328-for-pc-and-mobile/) has been released and WSL specific release notes are [here](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes)

**Comment by perlun** [comment] 2016-04-22 20:05
@sunilmut - cool! When will it be out on the Fast channel?

**Comment by sunilmut** [comment] 2016-04-22 20:19
@perlun Its being released [today](https://blogs.windows.com/windowsexperience/2016/04/22/announcing-windows-10-insider-preview-build-14328-for-pc-and-mobile/) to the Fast ring. So, any moment, I would say.

**Comment by stewones** [comment] 2016-04-22 20:30
updating... u.u

**Comment by perlun** [comment] 2016-04-22 22:05
@sunilmut - awesome. Will try it once I get the update (sometime next week then, I guess).

**Comment by russalex** [comment] 2016-04-22 22:51
The update is now live and on the fasttrack:  https://msdn.microsoft.com/en-us/commandline/wsl/release_notes

Good news and bad news for this thread.  The good news is you can now untar items with symlinks under a non-mount directory.  Bad news is the fix to create a tar with a symlink is not in this build yet.

We do have the fix internally, along with the fix so this works on the /mnt drives.  These fixes are moving through the system and will be in a later build.

**Comment by hvdijk** [comment] 2016-04-23 11:09
> The good news is you can now untar items with symlinks under a non-mount directory.

As long as you're running as root. Otherwise, tar prints errors and return an exit status that indicates failure.

    tar: <symlink name>: Cannot utime: Operation not permitted

That's with a user created by `lxrun /setdefaultuser`. The symlinks do get created, but all symlinks appear to have root as their owner. Is that why utime is not permitted? Should I report this as a separate issue?

**Comment by SvenGroot** [comment] 2016-04-23 20:34
@hvdijk Thanks for reporting this issue. I've tested it, and was able to reproduce it in the current Windows Insider build. This issue has already been fixed in our internal builds (the links have the correct owner now), and this fix will be released in a future Insider build.

**Comment by tinysun212** [comment] 2016-04-23 23:12
I tested the same thing which I did when I created this issue.

In build 14328, the symbolic link containing tar file is successfully extracted.  It didn't work in 14316. Thanks.
```
root@DESKTOP-V9QH45Q:~# tar tvf kkk.tar
drwxrwxr-x tinysun/tinysun   0 2016-04-23 22:40 kkk/
-rw-rw-r-- tinysun/tinysun  11 2016-04-23 22:40 kkk/atest
lrwxrwxrwx tinysun/tinysun   0 2016-04-23 22:40 kkk/btest -> atest
root@DESKTOP-V9QH45Q:~# tar xvf kkk.tar
kkk/
kkk/atest
kkk/btest
root@DESKTOP-V9QH45Q:~# ls -l kkk
total 0
-rw-rw-r-- 1 1000 1000 11 Apr 23 22:40 atest
lrwxrwxrwx 1 1000 1000  5 Apr 23 22:40 btest -> atest
```

But the archiving test was failed with same messages as I showed at the first post. 
```
root@localhost:~# tar cvf kkk2.tar kkk
kkk/
kkk/atest
tar: kkk/btest: Cannot readlink: Invalid argument
tar: Exiting with failure status due to previous errors
```

**Comment by ljharb** [comment] 2016-04-24 04:43
@SvenGroot is there a reason the concept of an "internal build" exists? can this not be compiled natively from an open source repo and used within Windows?

**Comment by nsvrana** [comment] 2016-04-25 18:17
@ljharb I obviously don't speak for MS here, but it seems like a lot of these fixes are in the underlying subsystem in Windows not the high-level "Bash on Ubuntu on Windows" application that can be compiled and pushed on its own. It will probably be coupled to Windows builds for the foreseeable future.

**Comment by benhillis** [comment] 2016-04-25 18:21
@nsvrana you are correct. I'll also add on that internal builds exist for development and validation.  We go through a validation process to make sure that what is released to Insiders meets a certain quality bar and isn't going to harm their machine.

That being said, It would be nice if our update frequency was faster and we're discussing ways to make this possible in the future.

**Comment by perlun** [comment] 2016-04-25 19:22
`sudo apt-get upgrade ubuntu-on-windows` :wink:

**Comment by russalex** [comment] 2016-04-27 00:52
This looks to be fixed.  Try it with the new [14332 ](msdn.microsoft.com/en-us/commandline/wsl/release_notes)build.

**Comment by tinysun212** [comment] 2016-04-27 04:31
It works finally!
```
root@DESKTOP-V9QH45Q:~# ls -lR kkk
kkk:
total 0
-rw-rw-r-- 1 1000 1000 11 Apr 23 22:40 atest
lrwxrwxrwx 1 1000 1000  5 Apr 23 22:40 btest -> atest
root@DESKTOP-V9QH45Q:~# tar cvf kkk.tar kkk
kkk/
kkk/atest
kkk/btest
root@DESKTOP-V9QH45Q:~# tar tvf kkk.tar
drwxrwxr-x 1000/1000         0 2016-04-23 22:40 kkk/
-rw-rw-r-- 1000/1000        11 2016-04-23 22:40 kkk/atest
lrwxrwxrwx 1000/1000         0 2016-04-23 22:40 kkk/btest -> atest
```

It seems that the problem I presented in beginning is solved. If there is no objection, I will close this issue in this weekend.

Thanks you WSL team, that's totally awesome!

**Comment by julihermes** [comment] 2016-04-27 11:11
its fixed in the new build?

**Closed** 2016-05-02 04:52 UTC
Labels: fixed, fixinbound

**Comment by therevmj** [comment] 2016-05-17 21:56
This doesn't appear to be completely fixed or has been reverted.  I am running build 14343..rs1_release.160506-1708.

This can be tested in the following way:

JUPITER:~/tmp$ ls
JUPITER:~/tmp$ echo FOO > tmp1
JUPITER:~/tmp$ ln -s tmp1 tmp2
JUPITER:~/tmp$ grep -r FOO ./
./tmp1:FOO
grep: ./tmp2: Invalid argument

**Comment by tinysun212** [comment] 2016-05-17 22:49
Good detection!

This thread is for the combination of symlink and 'tar', not for all things related to symlink or tar.
Please create new issue with title like 'grep with symbolic links'.

**Comment by benhillis** [comment] 2016-05-17 22:53
@therevmj @tinysun212 I tried this repro internally and verified that this is now working.  The fix will be making its way to a windows insider build soon.

**Comment by perlun** [comment] 2016-05-18 05:58
Sorry to be _a bit_ OT, but how do you push your insider machine to download the latest build? Mine is still running the "original" 160402 (or so) release, meaning I don't have the symlink fixes etc...

**Comment by hfaran** [comment] 2016-05-18 06:03
@perlun http://www.cnet.com/how-to/change-to-the-fast-ring-for-more-frequent-windows-10-preview-updates/

**Comment by perlun** [comment] 2016-05-18 06:08
@hfaran - thanks. The problem is _I am_ already on the fast ring, but the updates don't seem to be coming. And I cannot find a way to manually force them to come. Any suggestions?
