### ISSUE TITLE
"top" renders incorrectly with lots of processes

### ISSUE THREAD

**Issue by aseering** [Microsoft/BashOnWindows#1215] opened 2016-10-16 21:44 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

When I run `top` with more running processes than the current window has lines, `top`  tries to print a line for all running processes rather than truncating at screen size as intended.

Note that my actual use case isn't running `top` locally:  I want to ssh into remote Linux servers and run `top` there.  Doing so currently fails in the same way; I'm assuming it fails for the same reason.

Note also that this is using Ubuntu 16.04 (both locally and on the remote Linux server in question).  I have been successful at using `top` in the past on a 14.04 server.

* Expected results

![2016-10-16 1](https://cloud.githubusercontent.com/assets/363982/19421109/f38d73a0-93c6-11e6-9c49-1a46ea4647df.png)

If more processes are running than can be listed, I expect only the top N processes to be displayed (where N is the number that fit on the screen); I expect the remainder to be omitted.

* Actual results (with terminal output if applicable)

![2016-10-16 3](https://cloud.githubusercontent.com/assets/363982/19421119/2b5dbc90-93c7-11e6-9a2f-f7693d0b659b.png)

Note the lack of the usual `top` header / summary information.

`top`, by default, refreshes once per 1.5 seconds by default.  Subsequent refreshes simply clear the window.

* Your Windows build number

14946

* Steps / All commands required to reproduce the error from a brand new installation 

```
# Create a bunch of processes for 'top' to list
for i in {1..100}; do sleep 100 & done

top
```

* Strace of the failing command

I think this is an issue with console escape-character handling, not with syscall support.  I can generate an strace if it would be useful.

* Required packages and commands to install

`top` is available by default.

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by zadjii-msft** [comment] 2016-10-17 14:45
@aseering I believe this is related to your other issue you just opened, #1217. So, yea, what's the output of `stty -a`?

**Comment by aseering** [comment] 2016-10-17 16:02
@zadjii-msft -- sure; will do later today, when I'm next at this machine.

**Comment by zadjii-msft** [comment] 2016-10-18 15:40
Considering the results posted in #1217, this is a dupe of that issue. Closing this one.

**Closed by zadjii-msft** 2016-10-18 15:40 UTC
Labels: console, duplicate
