### ISSUE TITLE
Running 'Siege' http/https regression testing and benchmarking utility fails/crashes

### ISSUE THREAD

**Issue by carlosroman** [Microsoft/BashOnWindows#1027] opened 2016-08-31 16:50 UTC
When running [Siege](https://www.joedog.org/siege-home/), random requests will fail with the following error:
```bash
[error] unable to set close control sock.c:127: Invalid argument
```
If I use basic auth using a siege config file `~/.siegerc`, with the contents:
```
login = login = username:password
```
Then the application fails straight away and exits.

The command being run is:
```bash
$ siege -g <some test url> -c10 -d1 -t60s
```
Running same command on a *nix system will run the load test for 60s seconds with each request hitting the URL specified. 

Windows build number: Version 1607 (OS Build 14393.82)

To install Siege just run:
```bash
$ sudo apt-get install -y siege
```
Strace of the failing command:
```
execve("/usr/bin/siege", ["siege", "-g", "<some test url>", "-c10", "-d1", "-t60s"], [/* 17 vars */]) = 0
brk(0)                                  = 0x7fffc1879000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f058ffe0000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=29814, ...}) = 0
mmap(NULL, 29814, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f058ffd8000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0po\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=141574, ...}) = 0
mmap(NULL, 2217264, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f058f9e0000
mprotect(0x7f058f9f9000, 2093056, PROT_NONE) = 0
mmap(0x7f058fbf8000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18000) = 0x7f058fbf8000
mmap(0x7f058fbfa000, 13616, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f058fbfa000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libssl.so.1.0.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\200.\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=387256, ...}) = 0
mmap(NULL, 2482544, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f058f780000
mprotect(0x7f058f7d5000, 2097152, PROT_NONE) = 0
mmap(0x7f058f9d5000, 40960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x55000) = 0x7f058f9d5000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libcrypto.so.1.0.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@\356\5\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=1934624, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f058ffd0000
mmap(NULL, 4044952, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f058f3a0000
mprotect(0x7f058f553000, 2093056, PROT_NONE) = 0
mmap(0x7f058f752000, 155648, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1b2000) = 0x7f058f752000
mmap(0x7f058f778000, 14488, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f058f778000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P \2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1840928, ...}) = 0
mmap(NULL, 3949248, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f058efd0000
mprotect(0x7f058f18a000, 2097152, PROT_NONE) = 0
mmap(0x7f058f38a000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ba000) = 0x7f058f38a000
mmap(0x7f058f390000, 17088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f058f390000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\16\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=14664, ...}) = 0
mmap(NULL, 2109744, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f058edc0000
mprotect(0x7f058edc3000, 2093056, PROT_NONE) = 0
mmap(0x7f058efc2000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f058efc2000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f058ffc0000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f058ffb0000
arch_prctl(ARCH_SET_FS, 0x7f058ffb0740) = 0
mprotect(0x7f058f38a000, 16384, PROT_READ) = 0
mprotect(0x7f058efc2000, 4096, PROT_READ) = 0
mprotect(0x7f058f752000, 110592, PROT_READ) = 0
mprotect(0x7f058f9d5000, 12288, PROT_READ) = 0
mprotect(0x7f058fbf8000, 4096, PROT_READ) = 0
mprotect(0x7f059021f000, 8192, PROT_READ) = 0
mprotect(0x7f058fe22000, 4096, PROT_READ) = 0
munmap(0x7f058ffd8000, 29814)           = 0
set_tid_address(0x7f058ffb0a10)         = 6455
set_robust_list(0x7f058ffb0a20, 24)     = 0
futex(0x7fffca0d2530, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, 7f058ffb0740) = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGRTMIN, {0x7f058f9e69f0, [], SA_RESTORER|SA_SIGINFO, 0x7f058f9f0330}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7f058f9e6a80, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f058f9f0330}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=8192*1024}) = 0
brk(0)                                  = 0x7fffc1879000
brk(0x7fffc189a000)                     = 0x7fffc189a000
rt_sigprocmask(SIG_BLOCK, [HUP INT ALRM TERM], NULL, 8) = 0
stat("/home/carlosr/.siegerc", {st_mode=S_IFREG|0666, st_size=34, ...}) = 0
open("/home/carlosr/.siegerc", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0666, st_size=34, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f058ffa0000
read(3, "login = login = username:passwor"..., 512) = 34
read(3, "", 512)                        = 0
close(3)                                = 0
munmap(0x7f058ffa0000, 4096)            = 0
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f058e5b0000
mprotect(0x7f058e5b0000, 4096, PROT_NONE) = 0
clone(child_stack=0x7f058edaffb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f058edb09d0, tls=0x7f058edb0700, child_tidptr=0x7f058edb09d0) = 6456
times({tms_utime=0, tms_stime=4, tms_cutime=0, tms_cstime=0}) = 2836691
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f058dda0000
mprotect(0x7f058dda0000, 4096, PROT_NONE) = 0
clone(child_stack=0x7f058e59ffb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f058e5a09d0, tls=0x7f058e5a0700, child_tidptr=0x7f058e5a09d0) = 6457
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f058d590000
mprotect(0x7f058d590000, 4096, PROT_NONE) = 0
clone(child_stack=0x7f058dd8ffb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f058dd909d0, tls=0x7f058dd90700, child_tidptr=0x7f058dd909d0) = 6458
open("/dev/urandom", O_RDONLY)          = 3
read(3, ".%\210\241", 4)                = 4
close(3)                                = 0
futex(0x7fffc1879354, FUTEX_CMP_REQUEUE_PRIVATE, 1, 2147483647, 0x7fffc1879328, 2) = -1 ENOSYS (Function not implemented)
futex(0x7fffc1879354, FUTEX_WAKE_PRIVATE, 2147483647) = 1
futex(0x7fffc1879328, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f058edb09d0, FUTEX_WAIT, 6456, NULL[error] unable to set close control sock.c:127: Invalid argument
 <unfinished ...>
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

**Comment by fpqc** [comment] 2016-09-01 00:37
This looks like the culprit, maybe?

`futex(0x7fffc1879354, FUTEX_CMP_REQUEUE_PRIVATE, 1, 2147483647, 0x7fffc1879328, 2) = -1 ENOSYS (Function not implemented)`

**Comment by therealkenc** [comment] 2016-09-04 17:19
Same as [1006](https://github.com/Microsoft/BashOnWindows/issues/1006#issuecomment-243191006) and [486](https://github.com/Microsoft/BashOnWindows/issues/486#issuecomment-234930031). POSIX_THREAD_PRIO_INHERIT is not supported.

**Comment by benhillis** [comment] 2016-09-13 15:42
Closing as a duplicate of #486 and #1006.

**Closed by benhillis** 2016-09-13 15:42 UTC

**Comment by mrodal** [comment] 2019-03-27 18:01
Hi, #1006 is marked as fixed in 1809, but I have 1809 and still get a lot of 
`[error] unable to set close control sock.c:141: Invalid argument`
and 
`[error] HTTPS requires libssl: Unable to reach ajax.googleapis.com with this protocol: Transport endpoint is already connected`

Is there something else going on?
