### ISSUE TITLE
French windows 10: impossible to launch bash

### ISSUE THREAD

**Issue by remisharrock** [Microsoft/BashOnWindows#268] opened 2016-04-25 23:28 UTC
As you can see in the screenshot, I cannot install bash with the french language activated systemwide.
Some strange characters are showing, and I cannot answer the question.
I had to switch to english and it worked !
windows 10 home version 14328
![bashlancement](https://cloud.githubusercontent.com/assets/8048877/14801937/ce76215e-0b4d-11e6-989b-8b9d9ac9632f.PNG)

**Comment by xilun** [comment] 2016-04-25 23:35
Actually you can install by typing "o"
But yes, they messed up the charset. (Well given how messy the handling of charsets by Windows in the console is, this is not surprising :p )

I already reported that charset pb in #247.

**Comment by remisharrock** [comment] 2016-04-25 23:38
@xilun tried with y o yes oui - didn't work :-(
merci quand même ;-)

**Comment by xilun** [comment] 2016-04-25 23:40
Oh, weird. I remember installing it once with windows setup in French. But I also installed it previously in English (and uninstalled in the mean time), so maybe that had an impact too, I don't know.

**Comment by benhillis** [comment] 2016-04-26 18:33
We have a couple of fixes inbound to allow people with non-English language settings to install bash.  I'm going to close this thread since this is the same root cause as #12.

Thanks for reporting this issue.

**Closed by benhillis** 2016-04-26 18:33 UTC
Labels: fixinbound
