### ISSUE TITLE
typescript compiler tsc -w fails on ioctl(..., FIOCLEX)    

### ISSUE THREAD

**Issue by therealkenc** [Microsoft/BashOnWindows#448] opened 2016-05-28 05:13 UTC
With build 14352 node 6.2.0 and typescript 1.8.10 now install perfectly. The tsc compiler works mostly, but the watch feature throws an EPERM in fs.js. I straced it down to ioctl(..., FIOCLEX).

```
stat("tsconfig.json", {st_mode=S_IFREG|0664, st_size=303, ...}) = 0
getcwd("/home/ken/devel/my-proj", 4096) = 24
inotify_init()                          = 9
ioctl(9, FIOCLEX)                       = -1 EPERM (Operation not permitted)
close(9)                                = 0
```

**Comment by stehufntdev** [comment] 2016-05-31 21:15
Thanks for reporting the issue, WSL has limited inotify support.  Closing this out as a duplicate of #216 so we can track.

**Closed by stehufntdev** 2016-05-31 21:15 UTC
