### ISSUE TITLE
df , ifconfig ,ping Error!!

### ISSUE THREAD

**Issue by litianZ** [Microsoft/BashOnWindows#239] opened 2016-04-21 02:06 UTC
hi, I curl www.microsoft.com successful.
root@localhost:/mnt/c/Users/litian# curl www.microsoft.com
Microsoft Corporation

Your current User-Agent string appears to be from an automated process, if this is incorrect, please click this link:United States English Microsoft Homepage

but, I do these failed
root@localhost:/mnt/c/Users/litian# df
df: cannot read table of mounted file systems: No such file or directory
root@localhost:/mnt/c/Users/litian# ifconfig
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.
root@localhost:/mnt/c/Users/litian# ping www.google.com
ping: icmp open socket: Socket type not supported
I had tried lxrun /uninstall and then lxrun /install, but it is still the same issue.
how can I do?

**Comment by sunilmut** [comment] 2016-04-21 02:12
@litianZ - Network tools such as ping\ifconfig not working is a known issue\limitation at the moment, unfortunately. The failure in these tools is not an indication of lack of network. See #66. If your network is working, you should be able to still apt-get packages and work with them. Please up vote the user voice page as indicated in #66. If network is working fine for you, I would suggest marking this as dupe of #66. And, thanks for trying out WSL and giving us feedback.

**Comment by Edwin-Edward** [comment] 2016-04-21 07:56
About df, take a look at #150 for a workaround :wink:

**Comment by benhillis** [comment] 2016-06-17 18:47
df and ping now work, I'm going to close this out as a duplicate of #66.

**Closed by benhillis** 2016-06-17 18:47 UTC
Labels: duplicate, network

**Comment by bitcrazed** [comment] 2016-09-15 22:40
Small update: As of build 14926, ping can run in a non-elevated bash instance.
