### ISSUE TITLE
Nginx not start

### ISSUE THREAD

**Issue by exileed** [Microsoft/BashOnWindows#68] opened 2016-04-08 11:37 UTC
`2016/04/08 11:34:44 [emerg] 10843#0: setsockopt(IPV6_V6ONLY) [::]:80 failed, ignored (22: Invalid argument)
2016/04/08 11:34:44 [emerg] 10843#0: bind() to [::]:80 failed (22: Invalid argument)`

**Comment by deyvisonrocha** [comment] 2016-04-08 12:47
If you comment the second line of listen works. But, not work on Windows accessing the localhost:<port>. =/

**Comment by hungys** [comment] 2016-04-10 18:11
Same here. I guess the IPv6 is not fully implemented.
However, after commenting out the IPv6 config in `/etc/nginx/sites-available/default`, I got another error:

```
2016/04/10 18:03:54 [emerg] 594#0: setsockopt(IPV6_V6ONLY) [::]:80 failed, ignored (22: Invalid argument)
2016/04/10 18:03:54 [emerg] 594#0: bind() to [::]:80 failed (22: Invalid argument)
2016/04/10 18:06:52 [alert] 661#0: ioctl(FIONBIO) failed while spawning "worker process" (22: Invalid argument)
2016/04/10 18:06:52 [alert] 661#0: ioctl(FIONBIO) failed while spawning "worker process" (22: Invalid argument)
2016/04/10 18:06:52 [alert] 661#0: ioctl(FIONBIO) failed while spawning "worker process" (22: Invalid argument)
2016/04/10 18:06:52 [alert] 661#0: ioctl(FIONBIO) failed while spawning "worker process" (22: Invalid argument)
```

**Comment by sunilmut** [comment] 2016-04-12 20:37
Can confirm from our side that the socket option IPPROTO_IPV6\IPV6_V6ONLY is not yet implemented. We have opened a bug on our side to track this. No ETA at this time.

**Comment by luisfavila** [comment] 2016-04-13 16:46
@sunilmut What about accessing nginx from Windows? I've got it running, but http://localhost won't work.

**Comment by sunilmut** [comment] 2016-04-13 17:36
@luisfavila If the nginx server is listening on the port, then you should be able to connect from Windows. 'netstat' is probably currently broken on WSL. Can you try 'netstat' on Windows to see if anyone is listening on the server port? If nginx is listening on the server port, you can also check your firewall settings (or disable it) to see if that makes any difference?

**Comment by luisfavila** [comment] 2016-04-13 18:01
@sunilmut Actually, nginx wasn't started at all. It did not show any error when starting, but reading logs it was due to IPV6, which is disabled now. It won't start anyway, though, showing the following error:
'ioctl(FIONBIO) failed while spawning "worker process" (22: Invalid argument)'
Apache2 seems to work, while presenting the following warning (after disabling IPv6, with IPv6 enabled will show one more warning):
`Invalid argument: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT`

**Comment by sunilmut** [comment] 2016-04-13 20:49
@luisfavila Regarding "ioctl(FIONBIO)" error, do you know on which file it is calling that IOCTL?

**Comment by sunilmut** [comment] 2016-04-13 20:55
@luisfavila - Also, glad to know that you got apache to work. We are working on getting support for IPV6_V6ONLY. Hopefully, you should see that light up soon.

**Comment by afridlund85** [comment] 2016-04-14 07:22
@luisfavila did you get apache to work? I get ipv6 errors but I didn't manage to disable it, all guides on how to disable ipv6 on ubuntu refered to config files that did not exists or didn't change anything when edited. How did you disable ipv6?

**Comment by luisfavila** [comment] 2016-04-14 13:43
@afridlund85 Edited /etc/apache2/ports.conf and changed `Listen 80` to `Listen 0.0.0.0:80`

> Regarding "ioctl(FIONBIO)" error, do you know on which file it is calling that IOCTL? 
@sunilmut No idea, it doesn't tell

> Also, glad to know that you got apache to work. We are working on getting support for IPV6_V6ONLY. Hopefully, you should see that light up soon.
@sunilmut Great! Looking forward to test it!

**Comment by Geeknux** [comment] 2016-04-17 09:47
I compile nginx without enabling IPv6 support bot it doesn't start either

i got this error:
`nginx: [emerg] bind() to 0.0.0.0:80 failed (22: Invalid argument)`

i compile nginx with this command:
/usr/local/nginx/sbin/nginx -V

```
nginx version: nginx/1.8.1
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
configure arguments: --prefix=/usr/local/nginx --without-http_autoindex_module --without-http_userid_module --without-http_auth_basic_module --without-http_fastcgi_module --without-http_empty_gif_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module
```

**Comment by luisfavila** [comment] 2016-04-17 18:00
@Geeknux Have you disabled IPv6 following my instructions? They were for Apache2; the way to do it in Nginx is different: edit the file /etc/nginx/sites-enabled/default and comment the line `listen [::]:80 default_server ipv6only=on;`

**Comment by Geeknux** [comment] 2016-04-18 07:00
@luisfavila Yes i did that, but it didn't resolve the problem, at least not for me

**Comment by luisfavila** [comment] 2016-04-18 13:58
@Geeknux I didn't get nginx to work either, only apache2. Nginx seemed load fine, but checking the error log in `/var/log/nginx` presented me `ioctl(FIONBIO) failed while spawning "worker process" (22: Invalid argument)` as I said above in this thread

**Comment by hungys** [comment] 2016-04-23 03:43
Still encounter the same issue on the latest build.

`ioctl(FIONBIO) failed while spawning "worker process" (22: Invalid argument)`

**Comment by kjhughes097** [comment] 2016-04-26 12:13
Same issue.

Initially did not bind, so I removed the IPV6 config item. Now I'm getting the 
`ioctl(FIONBIO) failed while spawning 'worker process' (22: Invalid argument)`
error

**Comment by sunilmut** [comment] 2016-05-05 00:09
I have verified that with IPV6ONLY fix and the fix to return EADDRINUSE in bind() when a port is already in use, apache2 starts fine (although it emits a warning around APR_TCP_DEFER_ACCEPT). I was able to connect to the apache webserver port using a browser and access the default page. These fixes should show up soon in the insider builds. Thanks for trying out WSL and providing feedback!

**Comment by adityanag** [comment] 2016-05-12 04:08
Confirmed that apache2 is working in the latest build with no need to edit any config files. 

However, nginx still doesn't work. I get a slightly different error (FIOASYNC)


`2016/05/12 04:07:38 [alert] 354#0: ioctl(FIOASYNC) failed while spawning "worker process" (22: Invalid argument)`

**Comment by sunilmut** [comment] 2016-05-19 19:37
I took a deeper look at 'Nginx'. It first binds to an IPv4 address and then to an IPv6 address (to the same port by default) using the IPV6_V6ONLY option. Unfortunately, we are not able to support the scenario immediately and we have a bug tracking this.
As an alternative, there are couple of options as workarounds:
Edit the default configuration of Nginx to start at different ports on IPv4 and IPv6. Or, use either IPv4 or IPv6. The port configuration for Nginx is stored in '/etc/nginx/sites-enabled/default'. I was able to verify that both these workarounds work and the Nginx server starts successfully on build 14342. We know its not ideal, but at least gets your one step further.
Meanwhile, we have an understanding of the bug on our side, but unfortunately, it might take some time to fix it because of dependencies outside of WSL.

**Comment by paladox** [comment] 2016-05-27 19:14
@sunilmut nginx still dosent start.

Shows this error now

2016/05/27 20:06:36 [alert] 79#0: ioctl(FIOASYNC) failed while spawning "worker process" (22: Invalid argument)
2016/05/27 20:06:36 [alert] 79#0: ioctl(FIOASYNC) failed while spawning "worker process" (22: Invalid argument)
2016/05/27 20:06:36 [alert] 79#0: ioctl(FIOASYNC) failed while spawning "worker process" (22: Invalid argument)
2016/05/27 20:06:36 [alert] 79#0: ioctl(FIOASYNC) failed while spawning "worker process" (22: Invalid argument)

I'm using the latest windows 10 build insider as of today.

**Comment by roydejong** [comment] 2016-05-28 16:45
+1, nginx is still broken even when ipv6 is disabled:

    2016/05/28 16:39:56 [alert] 53#0: ioctl(FIOASYNC) failed while spawning "worker process" (22: Invalid argument)

**Comment by xyzith** [comment] 2016-05-30 07:26
The windows HTTP Kernel-mode driver also block port 80.
http://flummox-engineering.blogspot.com/2015/08/apache-cannot-run-on-port-80-on-windows.html

After I disabled the HTTP Kernel-mode, I got the same error in error.log
ioctl(FIOASYNC) failed while spawning "worker process" (22: Invalid argument)

**Comment by chrisboylan** [comment] 2016-06-07 02:51
Yes, I'm on 14352, and even after setting: 
`listen 8080 default_server;`
`listen [::]:8081 default_server;`
When I curl http://localhost:8080, the request never completes, and error.log has 4 lines of:
`[alert] 9832#9832: ioctl(FIOASYNC) failed while spawning "worker process" (22: Invalid argument)`

@sunilmut - Can we remove the "workaround-available" tag since the workaround doesn't work?

**Comment by Mocilol** [comment] 2016-06-10 18:15
Add this to nginx.conf will let u able to run nginx, enough for development environment:
master_process off;
daemon off;

**Comment by paladox** [comment] 2016-06-10 18:21
Actually nginx now starts.

doing sudo service nginx status shows that it is running

I haven't tested nginx through localhost since I'm using apache2.

**Comment by paladox** [comment] 2016-06-11 12:48
@sunilmut nginx starts now. but loading website dosent. it shows the icon spinning meaning it's loading but your waiting there for ages for it to load.

**Comment by paladox** [comment] 2016-06-11 12:50
Starting nginx still shows this

2016/06/11 13:49:49 [alert] 9329#0: ioctl(FIOASYNC) failed while spawning "worker process" (22: Invalid argument)

but it starts but dosent load the webpage.

**Comment by Mocilol** [comment] 2016-06-11 13:15
@paladox  icon spinning and chrome says ERR_CONTENT_LENGTH_MISMATCH? 
I found this may be buff problem for large file.
Add this to nginx.conf in http context:
output_buffers 2 10m;

**Comment by paladox** [comment] 2016-06-11 13:26
@Mocilol I'm using internet explorer and no error shows just continues to show the loading sign.

**Comment by cjgreen** [comment] 2016-06-29 02:57
As mentioned by @Mocilol and in the following blog post [here](https://www.svennd.be/running-nginx-on-bash-for-windows-10/):

Add the following line to /etc/nginx/nginx.conf:
`master_process off;`

Then restart nginx:
`sudo service nginx restart;`

For some reason when also adding `daemon off;` as mentioned by @Mocilol nginx would not restart.

**Comment by lscgzwd** [comment] 2016-07-27 12:14
add master_process off;  works for me

**Comment by PeterDraex** [comment] 2016-07-27 17:07
Here's what I've tried:
- setting nginx&FPM to communicate only via 127.0.0.1:9000
- setting nginx&FPM to communicate only via unix socket
- adding `master_process off; daemon off;` to config
- adding `master_process off;` to config
- using FPM with Apache instead of nginx

None of these worked for me.  I've been seeing error messages with FIONBIO, TCP_INFO and maximum worker_connections (50 000) reached.

**Comment by aran112000** [comment] 2016-07-30 11:51
After setting `master_process off;` within my `nginx.conf`, I do still get errors within Nginx's `error.log` with the following:
`ioctl(eventfd, FIONBIO) failed (1: Operation not permitted)`

*However*, Nginx has still come up and is accepting connections.

After switching PHP-FPM to over 127.0.0.1:9000 rather than sockets, everything is working perfectly.

This is based on Windows build 14393.5, Nginx 1.11.3 and PHP-FPM (7.0.6).

**Comment by PeterDraex** [comment] 2016-07-31 04:42
In my only pool file in /etc/php/7.0/fpm/pool.d/www.conf I use `listen = 127.0.0.1:9000`.

This is what happens when I try to start FPM:
```
root@DESKTOP-NAME:~/# php-fpm7.0 -F
root@DESKTOP-1G3HA54:/run/php# php-fpm7.0 -F
[31-Jul-2016 06:32:41] ERROR: failed to retrieve TCP_INFO for socket: Invalid argument (22)
[31-Jul-2016 06:32:41] NOTICE: fpm is running, pid 771
[31-Jul-2016 06:32:41] NOTICE: ready to handle connections
[31-Jul-2016 06:32:41] NOTICE: systemd monitor interval set to 10000ms
[31-Jul-2016 06:32:42] ERROR: failed to retrieve TCP_INFO for socket: Invalid argument (22)
[31-Jul-2016 06:32:43] ERROR: failed to retrieve TCP_INFO for socket: Invalid argument (22)
[31-Jul-2016 06:32:44] ERROR: failed to retrieve TCP_INFO for socket: Invalid argument (22)
[31-Jul-2016 06:32:45] ERROR: failed to retrieve TCP_INFO for socket: Invalid argument (22)
...
```

Windows Build 14372.rs1_release, PHP 7.0.9-1+deb.sury.org~trusty+1.

**Comment by MJBGO** [comment] 2016-08-03 22:55
Same for me, having this message with 127.0.0.1:9000

ERROR: failed to retrieve TCP_INFO for socket: Invalid argument (22)

**Comment by aran112000** [comment] 2016-08-04 05:47
That sounds like your FPM config is still using sockets. Try putting the `listen = 127.0.0.1:9000` at the very end of your FPM conf file for the active pool to ensure there's nothing after setting it back to use sockets.

**Comment by MJBGO** [comment] 2016-08-04 22:42
@aran112000 Indeed, you were right. It's working fine now with 127.0.0.1:9000 :) 
I have a couple of errors though (but doesn't seem to affect the server)

> initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

> [04-Aug-2016 23:52:20] ERROR: failed to retrieve TCP_INFO for socket: Invalid argument (22)

**Comment by roozbehid-ic** [comment] 2016-08-05 22:22
I had to add master_process off; and disable ipv6 to make it work!

**Comment by jasonwilliams200OK** [comment] 2016-08-06 07:56
This is the same issue with Django, Redis, ASPNET (KestrelHttpServer), Rails (webrick, thin) all failing with `port is already in use`. https://github.com/Microsoft/BashOnWindows/issues/740, https://github.com/dotnet/cli/issues/3999. Lets re-purpose this ticket to track the generic port occupancy issue, and close all the duplicates.

**Comment by dumindaxsb** [comment] 2016-08-14 09:00
I got nginx working. Thanks to brilliant @Mocilol solution.

There are 2 separate issues here & 2 separate fixes.

1. IPV6 Not-Supported:
Comment or Remove `listen [::]:80 default_server ipv6only=on;` at /etc/nginx/sites-available/default

2. Worker processes issue:
Add following lines at /etc/nginx/nginx.conf

`master_process off;
daemon off;`

2.1 When running nginx on master_process, daemon off mode, sudo /etc/init.d/nginx start doesn't return and if you hit CTRL+C, it gets terminated. Start it in the background using sudo /etc/init.d/nginx start &

**Comment by wizardist** [comment] 2016-08-17 20:40
@dumindaxsb it works indeed. I could manage to start Nginx using pretty much the same steps. But I failed to do so at port 80. Is it blocked or what?

**Comment by PeterDraex** [comment] 2016-08-18 06:49
@wizardist  It works for me on port 80. You can use netstat in powershell to find out what's blocking your 80.

**Comment by Pilskalns** [comment] 2016-08-19 12:34
Even after long search, I have not found clear answer for choose between Unix socket and TCP when using Nginx+PHP-FPM.

* In case of Unix socket I get nginx error:
`2016/08/19 14:21:49 [alert] 412#0: *3 connect() failed (22: Invalid argument) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "localhost:8080"`

* In case of TCP port it works, but `/var/log/php5-fpm.log` every second gets line of:
`[19-Aug-2016 14:31:50] ERROR: failed to retrieve TCP_INFO for socket: Invalid argument (22)`
This is not production, but I can't turn it off with php settings, at some point silently spamming, that file will grow huge.


My setup from clean installation:
* /etc/nginx/nginx.conf:
`user www-data;
master_process off;
...
fastcgi_pass {with port or socket};
`
* /etc/php5/fpm/pool.d/www.conf:
`listen.mode = 0660
listen = 127.0.0.1:9009 or
listen = /var/run/php5-fpm.sock
`

If I spoil permissions, then error is different. What would you advise?

**Comment by sunilmut** [comment] 2016-09-14 20:55
With the help of the Windows networking team, we were able to fully implement the IPV6_V6ONLY flag. Hopefully this should resolve a bunch of issues here. The fix is still in our dev branch, but should soon hit the release branch.

**Comment by wizardist** [comment] 2016-09-26 16:42
> @dumindaxsb it works indeed. I could manage to start Nginx using pretty much the same steps. But I failed to do so at port 80. Is it blocked or what?

Just in case, Skype occupied port 80. Turning that feature of Skype off helped.

**Comment by bitcrazed** [comment] 2016-09-28 23:03
Should now be fixed in build 14936. Please let us know if you see this issue persist.

**Comment by hanlinking** [comment] 2016-10-08 21:51
I still have this issue in build 14942 with Ubuntu 16.04. whatever port I want bind return error, port is in using.I try every solution above but It still not work.on the othersides, I run a dotnet core web sample and the kestrel also return could  not bind the port,I have tryso many port.

**Comment by zhaorenjie110** [comment] 2016-10-10 04:44
@hanlinking i am also 14942 with 16.04 , you can try it ,it work for me.
![image](https://cloud.githubusercontent.com/assets/9960574/19227083/521032d0-8ee7-11e6-8e94-f6e55a8f689a.png)

**Comment by hanlinking** [comment] 2016-10-10 05:21
@zhaorenjie110 哥们不行啊。我这么做了之后确实没有报错了。但是windows这边还是连接不了nginx，我试了几个端口了，确定没有被使用。

**Comment by kundralaci** [comment] 2016-10-15 13:06
I'm still facing problems with ERR_CONTENT_LENGTH_MISMATCH.

@Mocilol advised `output_buffers 2 10m;` but it makes no difference for me.

My two additional observations:
- On Windows clients (Chrome) I don't get this error (strange!), only on Linux (Chrome), Android (Chrome), and iOS (Safari). 
- This error always occurs, if the requested file is > 256k. In this case, only the first 256k is received, nginx stops sending and finally timeouts (based on the `send_timeout 2;` value - it can be 10, 20, ... whatever value), so the browser fails with length mismatch.

I have also tested this with several nginx config files, one of them is the built-in default, and it haven't worked in any circumstances.

Win10 version: 14393.321 (1607)
nginx version: 1.10.1
Chrome version: 53.x

My questions:
- Should I open a new issue? Since nginx starts, but won't serve files larger than 256k.
- Does it also happen to others?
- Does anyone know a workaround?

**Comment by aseering** [comment] 2016-10-16 01:10
Is this perhaps related to #610 ?

**Comment by kundralaci** [comment] 2016-10-17 09:32
The root of the problem seems similar for me!

**Comment by magic007** [comment] 2016-10-21 08:01
加上这2个master_process off; daemon off;，把运行方式改为TCP模式9000，确实可以运行。不过PHP页面速度太慢，还不如访问虚拟机的速度。

**Comment by misenesi** [comment] 2016-12-07 01:37
The FIOASYNC is a duplicate of this bug [bug](https://github.com/Microsoft/BashOnWindows/issues/1196). It is lack of support for socket async I/O notifications.

**Comment by stehufntdev** [comment] 2017-01-19 23:00
After adding signal driven IO support for unix stream sockets, I was able to run nginx locally and load the default site.  Also confirmed that the errors were gone from the nginx error log.

The fix should be out in insider builds soon.

**Comment by hanlinking** [comment] 2017-01-21 10:09
@stehufntdev Can you tell me how to do for this "signal driven IO support for unix stream sockets"?

**Comment by stehufntdev** [comment] 2017-01-21 11:59
@hanlinking sorry didn't quite follow your reply, could you please clarify?

By "signal driven IO support for unix stream sockets", I was referring to nginx's use of FIOASYNC with F_SETOWNER on a unix stream socket.  This combination of syscalls enables SIGIO to be delivered when interesting events happen on the socket.  That fix seems to have been the last thing blocking nginx's default configuration from starting and should be out in an insider build soon.

**Comment by samayo** [comment] 2017-01-27 16:23
Still having the same problem. The solution from @dumindaxsb doesn't work, since I can't restart, stop, start nginx afterwards. It just gets stuck

**Closed** 2017-02-14 23:34 UTC
Labels: bug, fixinbound, nginx
