### ISSUE TITLE
Inotify not working properly, failing to watch when running jekyll serve

### ISSUE THREAD

**Issue by bluefantail** [Microsoft/BashOnWindows#433] opened 2016-05-26 22:58 UTC
I'm not 100% certain whether this is an issue for here just yet, but since I can't seem to find a scrap of info about this bug anywhere I figured I'd see what people thought.

I can't get a basic `jekyll serve` to run with `--watch` without it complaining about `.git/hooks` with 
```
Invalid argument - Failed to watch "/mnt/c/Sites/jamiemackman/.git/hooks": the given event mask contains no legal events; or fd is not an inotify file descriptor. (Errno::EINVAL)
```

I can run jekyll just fine with `--no-watch`, or `--force_polling`.

Any ideas?

```
jekyll s -t --verbose
```
Gives me:
```                                   
  Logging at level: debug                                                                                            
Configuration file: /mnt/c/Sites/jamiemackman/_config.yml                                                            
         Requiring: kramdown                                                                                         
            Source: /mnt/c/Sites/jamiemackman                                                                        
       Destination: /mnt/c/Sites/jamiemackman/_site                                                                  
 Incremental build: disabled. Enable with --incremental                                                              
      Generating...                                                                                                  
       EntryFilter: excluded /Gemfile                                                                                
       EntryFilter: excluded /Gemfile.lock                                                                           
         Rendering: contact.html                                                                                     
  Pre-Render Hooks: contact.html                                                                                     
  Rendering Liquid: contact.html                                                                                     
  Rendering Markup: contact.html                                                                                     
  Rendering Layout: contact.html                                                                                     
         Rendering: index.html                                                                                       
  Pre-Render Hooks: index.html                                                                                       
  Rendering Liquid: index.html                                                                                       
  Rendering Markup: index.html                                                                                       
  Rendering Layout: index.html                                                                                       
         Rendering: info.html                                                                                        
  Pre-Render Hooks: info.html                                                                                        
  Rendering Liquid: info.html                                                                                        
  Rendering Markup: info.html                                                                                        
  Rendering Layout: info.html                                                                                        
         Rendering: paintings.html                                                                                   
  Pre-Render Hooks: paintings.html                                                                                   
  Rendering Liquid: paintings.html                                                                                   
  Rendering Markup: paintings.html                                                                                   
  Rendering Layout: paintings.html                                                                                   
         Rendering: /required/styles/style.scss                                                                      
  Pre-Render Hooks: /required/styles/style.scss                                                                      
  Rendering Liquid: /required/styles/style.scss                                                                      
  Rendering Markup: /required/styles/style.scss                                                                      
         Rendering: thanks.html                                                                                      
  Pre-Render Hooks: thanks.html                                                                                      
  Rendering Liquid: thanks.html                                                                                      
  Rendering Markup: thanks.html                                                                                      
  Rendering Layout: thanks.html                                                                                      
                    done in 0.303 seconds.                                                                           
         Requiring: jekyll-watch                                                                                     
         Requiring: kramdown                                                                                         
           Watcher: Ignoring (?-mix:_config\.yml)                                                                    
           Watcher: Ignoring (?-mix:_site)                                                                           
           Watcher: Ignoring (?-mix:Gemfile)                                                                         
           Watcher: Ignoring (?-mix:Gemfile\.lock)                                                                   
/var/lib/gems/2.1.0/gems/rb-inotify-0.9.7/lib/rb-inotify/watcher.rb:74:in `initialize': Invalid argument - Failed to 
watch "/mnt/c/Sites/jamiemackman/.git/hooks": the given event mask contains no legal events; or fd is not an inotify 
file descriptor. (Errno::EINVAL)                                                                                     
        from /var/lib/gems/2.1.0/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:190:in `new'                       
        from /var/lib/gems/2.1.0/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:190:in `watch'                     
        from /var/lib/gems/2.1.0/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:204:in `watch'                     
        from /var/lib/gems/2.1.0/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:198:in `block in watch'            
        from /var/lib/gems/2.1.0/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:194:in `each'                      
        from /var/lib/gems/2.1.0/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:194:in `watch'                     
        from /var/lib/gems/2.1.0/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:198:in `block in watch'            
        from /var/lib/gems/2.1.0/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:194:in `each'                      
        from /var/lib/gems/2.1.0/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:194:in `watch'                     
        from /var/lib/gems/2.1.0/gems/listen-3.0.6/lib/listen/adapter/linux.rb:32:in `_configure'                    
        from /var/lib/gems/2.1.0/gems/listen-3.0.6/lib/listen/adapter/base.rb:45:in `block in configure'             
        from /var/lib/gems/2.1.0/gems/listen-3.0.6/lib/listen/adapter/base.rb:40:in `each'                           
        from /var/lib/gems/2.1.0/gems/listen-3.0.6/lib/listen/adapter/base.rb:40:in `configure'                      
        from /var/lib/gems/2.1.0/gems/listen-3.0.6/lib/listen/adapter/base.rb:63:in `start'                          
        from /var/lib/gems/2.1.0/gems/listen-3.0.6/lib/listen/backend.rb:26:in `start'                               
        from /var/lib/gems/2.1.0/gems/listen-3.0.6/lib/listen/listener.rb:67:in `block in <class:Listener>'          
        from /var/lib/gems/2.1.0/gems/listen-3.0.6/lib/listen/fsm.rb:120:in `instance_eval'                          
        from /var/lib/gems/2.1.0/gems/listen-3.0.6/lib/listen/fsm.rb:120:in `call'                                   
        from /var/lib/gems/2.1.0/gems/listen-3.0.6/lib/listen/fsm.rb:91:in `transition_with_callbacks!'              
        from /var/lib/gems/2.1.0/gems/listen-3.0.6/lib/listen/fsm.rb:57:in `transition'                              
        from /var/lib/gems/2.1.0/gems/listen-3.0.6/lib/listen/listener.rb:90:in `start'                              
        from /var/lib/gems/2.1.0/gems/jekyll-watch-1.3.1/lib/jekyll/watcher.rb:12:in `watch'                         
        from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/commands/build.rb:72:in `watch'                        
        from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/commands/build.rb:39:in `process'                      
        from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/lib/jekyll/commands/serve.rb:34:in `block (2 levels) in init_with_
program'                                                                                                             
        from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'                         
        from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'             
        from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'                         
        from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'                      
        from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'                            
        from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'                               
        from /var/lib/gems/2.1.0/gems/jekyll-3.1.2/bin/jekyll:13:in `<top (required)>'                               
        from /usr/local/bin/jekyll:23:in `load'                                                                      
        from /usr/local/bin/jekyll:23:in `<main>'       
```

**Comment by bluefantail** [comment] 2016-05-26 23:45
Just spotted the 14352 announcement. Updating now ..

**Comment by SvenGroot** [comment] 2016-05-27 00:05
Hi bluefantail,

Thanks for your interest in WSL. Our inotify support is very limited right now, unfortunately. The following User Voice request is used to track this: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13469097-support-for-filesystem-watchers-like-inotify

This is a duplicate of #216

**Comment by bluefantail** [comment] 2016-05-27 00:35
Ah thanks for that, I missed that issue.

**Comment by benhillis** [comment] 2016-05-27 00:41
Closing this out as a duplicate so we can use #216 to track.

**Closed by benhillis** 2016-05-27 00:41 UTC
Labels: duplicate
