### ISSUE TITLE
Linux processes don't show in Task Manager

### ISSUE THREAD

**Issue by tycho** [Microsoft/BashOnWindows#122] opened 2016-04-11 07:54 UTC
There's no way to know when a Linux process is consuming all the compute resources locally. For example, if I run something that just eats CPU time on every core:
* The Performance tab shows that 100% CPU is being utilized
* The Details tab shows nothing utilizing CPU to any significant degree

**Comment by Aneurin** [comment] 2016-04-11 10:00
Curiously, although it doesn't show in Task Manager, it does show in Resource Monitor.

**Comment by jackchammons** [comment] 2016-04-11 17:18
Currently, you should be able to see the bash processes in Resource Monitor but Linux processes are not available for viewing. We are looking for a solution to this.

**Comment by Edoa** [comment] 2016-04-12 09:16
I can confirm this ... It's quite strange.
At first I tough for a moment that it was some sort of virtualization, also because free command reports just 1GB of total ram on a machine that has 3GB...

![image](https://cloud.githubusercontent.com/assets/7404683/14455477/f9a0570e-009f-11e6-8721-d6701f09cb21.png)

**Comment by tycho** [comment] 2016-04-18 17:09
@jackchammons I'd strongly recommend keeping an issue open for this and keeping people posted on progress. Some people are already suggesting some of the security implications of it. For example, this hit Hacker News this morning.

https://ma.ttias.be/bash-windows-hidden-bitcoin-goldmine/

**Comment by squillace** [comment] 2016-04-18 21:26
@jackchammons Um, yeah. This should remain open until a behavior is chosen, regardless what that is.

**Comment by benhillis** [comment] 2016-04-18 22:05
Reopening this thread, we are looking into adding the correct info for the tasks to show up in task manager and not just resource monitor.  I will update with more information once the fix is made in our dev branch.

**Comment by benhillis** [comment] 2016-04-20 00:36
The fix for this issue was checked into our development branch today and is making it's way to the flighting branch.

**Comment by tycho** [comment] 2016-04-20 03:42
@benhillis Thanks for providing updates and openly communicating on the issue -- it's a refreshing thing to see from Microsoft!

**Comment by benhillis** [comment] 2016-05-27 18:57
I've verified that Linux processes now are showing up in task manager in build 14352.

**Closed by benhillis** 2016-05-27 18:57 UTC
Labels: bug, fixed
