### ISSUE TITLE
Java cannot allocate memory (sbt)

### ISSUE THREAD

**Issue by pradyuman** [Microsoft/BashOnWindows#1365] opened 2016-11-15 03:12 UTC
* A brief description
I'm trying to run the sbt console, and after some time, the sbt console stops working with a "Cannot allocate memory" error.

* Expected results
sbt console works as normal

* Actual results (with terminal output if applicable)
![image](https://cloud.githubusercontent.com/assets/9904569/20291860/3c6732ee-aab7-11e6-889c-76f667feb9d0.png)

* Your Windows build number
14965

* Steps / All commands required to reproduce the error from a brand new installation 
1. Launch sbt
2. Wait some time

* Required packages and commands to install
[sbt](http://www.scala-sbt.org/)

**Comment by pradyuman** [comment] 2016-11-15 04:10
I have tried increasing my paging memory to min 5GB max 10GB and it still doesn't work (computer has about 3.7GB of regular memory available).

**Comment by glenstarchman** [comment] 2016-11-18 15:26
Strange... sbt has been one thing that has been rock solid for me over the last several builds. What version of sbt are you using? Do you have a custom launch script? What happens if you do `sbt -mem 2048`?

**Comment by pradyuman** [comment] 2016-11-18 15:28
I'm using sbt 13.13 with no launch script. I'll try with sbt -mem 2048 and get back to you.

**Comment by mvlabat** [comment] 2016-11-22 15:23
Having the same issue... `sbt -mem 2048` doesn't help. Btw, despite exceptions, sbt (and console) actually starts and basic commands work. But anyway that's not normal

**Comment by pradyuman** [comment] 2016-11-22 15:24
Yeah sbt -mem 2048 didn't fix anything for me either.

**Comment by mvlabat** [comment] 2016-11-22 15:27
Update. Sorry, my issue is a little bit different. I have the same exception messages, but I receive them on sbt start, but not after some time..

> I'm trying to run the sbt console, and after some time, the sbt console stops working with a "Cannot allocate memory" error.

**Comment by pradyuman** [comment] 2016-11-22 15:29
Ah ok. sbt will start for me as well (with the memory exceptions) but it's very inconsistent with when commands will actually run in the console and when everything just fails.

**Comment by benhillis** [comment] 2016-12-01 23:38
Marking this as a duplicate of #851 - see my comment about the incoming fix #851 (comment)

**Closed by benhillis** 2016-12-01 23:38 UTC
Labels: duplicate, fixinbound, memory
