### ISSUE TITLE
Can't Install both Oracle JDK and OpenJDK due to so many reason.

### ISSUE THREAD

**Issue by yoshioterada** [Microsoft/BashOnWindows#174] opened 2016-04-13 10:45 UTC
Pattern 1:
# add-apt-repository ppa:webupd8team/java
# apt-get update
# apt-get install oracle-java8-installer
172032K ........ ........ ........ ........ ........ ........ 98% 3.43M 0s
175104K ........ ........ ........ .......                   100% 4.51M=41s
2016-04-12 18:22:29 (4.17 MB/s) - ‘jdk-8u77-linux-x64.tar.gz’ saved [181365687/181365687]
Download done.
Removing outdated cached downloads...
sha256sum mismatch jdk-8u77-linux-x64.tar.gz
Oracle JDK 8 is NOT installed.
dpkg: error processing package oracle-java8-installer (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up gsfonts (1:8.11+urwcyr1.0.7~pre44-4.2ubuntu1) ...
Setting up x11-common (1:7.7+1ubuntu8.1) ...
dmesg: klogctl failed: Invalid argument
/bin/df: cannot read table of mounted file systems: No such file or directory
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: No such file or directory
runlevel:/var/run/utmp: No such file or directory
 * Setting up X socket directories...                                                             [ OK ]
Processing triggers for ureadahead (0.100.0-16) ...
Setting up xfonts-encodings (1:1.0.4-1ubuntu1) ...
Setting up xfonts-utils (1:7.7+1) ...
Setting up gsfonts-x11 (0.22) ...
Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
Errors were encountered while processing:
 oracle-java8-installer
E: Sub-process /usr/bin/dpkg returned an error code (1)

Pattern 2:
# wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u77-b03/jdk-8u77-linux-x64.tar.gz"
# tar xvfz jdk-8u77-linux-x64.tar.gz
jdk1.8.0_77/jre/lib/fontconfig.SuSE.10.properties.src
jdk1.8.0_77/jre/lib/fontconfig.SuSE.11.bfc
jdk1.8.0_77/jre/COPYRIGHT
jdk1.8.0_77/jre/THIRDPARTYLICENSEREADME-JAVAFX.txt
jdk1.8.0_77/jre/Welcome.html
jdk1.8.0_77/jre/README
jdk1.8.0_77/README.html
tar: jdk1.8.0_77/jre/lib/amd64/server/libjsig.so: Cannot create symlink to ‘../libjsig.so’: Invalid argument
tar: Exiting with failure status due to previous errors
root@localhost:/tmp#
root@localhost:/tmp/jdk1.8.0_77/bin#
root@localhost:/tmp/jdk1.8.0_77/bin# ./java -version
<---- In this time, Hung up no response

Pattern 3:
# apt-get install default-jdk
Setting up policykit-1-gnome (0.105-1ubuntu4) ...
Setting up gconf-service (3.2.6-0ubuntu2) ...
Setting up libgnome2-bin (2.32.1-4ubuntu1) ...
Setting up libgconf2-4:amd64 (3.2.6-0ubuntu2) ...
Setting up openjdk-7-jre-headless:amd64 (7u95-2.6.4-0ubuntu0.14.04.2) ...
the java command requires a mounted proc fs (/proc).
dpkg: error processing package openjdk-7-jre-headless:amd64 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of default-jre-headless:
 default-jre-headless depends on openjdk-7-jre-headless (>= 7~u3-2.1.1); however:
  Package openjdk-7-jre-headless:amd64 is not configured yet.
dpkg: error processing package default-jre-headless (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of openjdk-7-jre:amd64:
 openjdk-7-jre:amd64 depends on openjdk-7-jre-headless (= 7u95-2.6.4-0ubuntu0.14.04.2); however:
  Package openjdk-7-jre-headless:amd64 is not configured yet.
dpkg: error processing package openjdk-7-jre:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of default-jre:
 default-jre depends on default-jre-headless (= 2:1.7-51); however:
  Package default-jre-headless is not configured yet.
dpkg: error processing package default-jre (--configure):
 dependency problems - leaving unconfigured
Setting up gconf-service-backend (3.2.6-0ubuntu2) ...
dmesg: klogctl failed: Invalid argument
Setting up gconf2 (3.2.6-0ubuntu2) ...
/bin/df: cannot read table of mounted file systems: No such file or directory
No apport report written because the error message indicates its a followup error from a previous failure.
No apport report written because MaxReports is reached already
No apport report written because MaxReports is reached already
update-alternatives: using /usr/bin/gconftool-2 to provide /usr/bin/gconftool (gconftool) in auto mode
(gconftool-2:8236): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Setting up libgnomevfs2-common (1:2.24.4-1ubuntu6) ...
Setting up libgnomevfs2-0:amd64 (1:2.24.4-1ubuntu6) ...
Setting up libgnome2-common (2.32.1-4ubuntu1) ...
Setting up libgnome2-0:amd64 (2.32.1-4ubuntu1) ...
dpkg: dependency problems prevent configuration of openjdk-7-jdk:amd64:
 openjdk-7-jdk:amd64 depends on openjdk-7-jre (= 7u95-2.6.4-0ubuntu0.14.04.2); however:
  Package openjdk-7-jre:amd64 is not configured yet.
dpkg: error processing package openjdk-7-jdk:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of default-jdk:
 default-jdk depends on default-jre (= 2:1.7-51); however:
  Package default-jre is not configured yet.
 default-jdk depends on openjdk-7-jdk (>= 7~u3-2.1.1); however:
  Package openjdk-7-jdk:amd64 is not configured yet.
dpkg: error processing package default-jdk (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of ca-certificates-java:
 ca-certificates-java depends on openjdk-7-jre-headless (>= 7~u3-2.1.1~pre1-1) | java6-runtime-headless; however:
  Package openjdk-7-jre-headless:amd64 is not configured yet.
  Package java6-runtime-headless is not installed.
  Package oracle-java8-installer which provides java6-runtime-headless is not configured yet.
  Package default-jre-headless which provides java6-runtime-headless is not configured yet.
  Package openjdk-7-jre-headless:amd64 which provides java6-runtime-headless is not configured yet.
dpkg: error processing package ca-certificates-java (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libatk-wrapper-java:
 libatk-wrapper-java depends on default-jre | java2-runtime; however:
  Package default-jre is not configured yet.
  Package oracle-java8-installer which provides default-jre is not configured yet.
  Package java2-runtime is not installed.
  Package default-jre which provides java2-runtime is not configured yet.
  Package oracle-java8-installer which provides java2-runtime is not configured yet.
  Package openjdk-7-jre:amd64 which provides java2-runtime is not configured yet.
dpkg: error processing package libatk-wrapper-java (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libatk-wrapper-java-jni:amd64:
 libatk-wrapper-java-jni:amd64 depends on default-jre | java2-runtime; however:
  Package default-jre is not configured yet.
  Package oracle-java8-installer which provides default-jre is not configured yet.
  Package java2-runtime is not installed.
  Package default-jre which provides java2-runtime is not configured yet.
  Package oracle-java8-installer which provides java2-runtime is not configured yet.
  Package openjdk-7-jre:amd64 which provides java2-runtime is not configured yet.
 libatk-wrapper-java-jni:amd64 depends on libatk-wrapper-java (>= 0.30.4-4); however:
  Package libatk-wrapper-java is not configured yet.
dpkg: error processing package libatk-wrapper-java-jni:amd64 (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
No apport report written because MaxReports is reached already
No apport report written because MaxReports is reached already
No apport report written because MaxReports is reached already
No apport report written because MaxReports is reached already
No apport report written because MaxReports is reached already
Errors were encountered while processing:
 oracle-java8-installer
 openjdk-7-jre-headless:amd64
 default-jre-headless
 openjdk-7-jre:amd64
 default-jre
 openjdk-7-jdk:amd64
 default-jdk
 ca-certificates-java
 libatk-wrapper-java
 libatk-wrapper-java-jni:amd64
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@localhost:~#

**Comment by niqolay** [comment] 2016-04-13 13:26
The first error in "apt-get install default-jdk" output is "the java command requires a mounted proc fs (/proc)." So it can be connected with #105

**Comment by mphaney** [comment] 2016-04-13 16:02
The second error is due to #9 (tar's current inability to handle symlinks).  I believe they've fixed that in the current code, but we won't see it until the next flight.  The third issue is a duplicate of #49.  Seems they've gotten Oracle's Java running on their internal builds but, again, we have to wait a while.  I'm just grateful for all the attention they're pouring into this!

**Comment by russalex** [comment] 2016-04-13 18:50
Support for installing Java manually is inbound.  See #49.

Everything else is in bugs we're tracking.

I'm going to close this one as a dup of #49.

**Closed by russalex** 2016-04-13 18:50 UTC
