### ISSUE TITLE
Node: invalid argument, uv_interface_addresses

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/BashOnWindows#1343] opened 2016-11-10 16:34 UTC
Node 7.0
Windows build 14965.1001

Create test.js:
```js
var os = require("os");
os.networkInterfaces();
```

```
node ./test.js
```
Output:
```
os.networkInterfaces();                                 
   ^                                                    
                                                        
Error: EINVAL: invalid argument, uv_interface_addresses 
    at Object.<anonymous> (/home/asvetl/test.js:3:4)    
    at Module._compile (module.js:573:32)               
    at Object.Module._extensions..js (module.js:582:10) 
    at Module.load (module.js:490:32)                   
    at tryModuleLoad (module.js:449:12)                 
    at Function.Module._load (module.js:441:3)          
    at Module.runMain (module.js:607:10)                
    at run (bootstrap_node.js:382:7)                    
    at startup (bootstrap_node.js:137:9)                
    at bootstrap_node.js:497:3
```
In my case i was trying to run webpack with css-loader (the error comes from it).

**Comment by JasonLinMS** [comment] 2016-11-10 23:36
We're aware of this issue, and the fix will be pushed out soon, thanks.

**Comment by antcook** [comment] 2016-11-23 23:43
This bug is still apparent in build 14971,  is a fix still inbound?

**Comment by ShimShamSam** [comment] 2016-11-30 01:05
@antcook According to their latest [Bash on Windows Release Notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes), they were unable to push any changes in the last release.

**Comment by antcook** [comment] 2016-12-08 02:02
@russalex  Just updated to 14986 and I can confirm that the issue is no longer present. (Node v7.0.1)

**Comment by therealkenc** [comment] 2016-12-08 05:43
_"Note that the Linux "ip" utility contains a bug where it will crash if WSL reports a 32-byte hardware address. This is a bug in "ip", not WSL. The “ip” utility hard-codes the length of the string buffer used to print the hardware address, and that buffer is too small to print a 32-byte hardware address."_
```
cat /sys/devices/virtual/net/und0
00:00:00:00:00:00:00:e0:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
```
Seriously??? Even on Windows with `ipconfig /all` those trailing zeros are apropos of nothing. If `00:00:...??.....00:00:01` is a valid address (and I am not sure even that is the case), jeez just XOR the thing down to 20 bytes or whatever buffer length happens to customary. Yes, the buffer is too small, and that's a bug. But there's a rather stronger argument that outputting a string that has _63 zeros_ in it is also a bug. 32 bytes, and it isn't even great as a UID.

`Tunnel adapter Teredo Tunneling Pseudo-Interface:`
   `Connection-specific DNS Suffix  . :`
   `Description . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface`
   **`Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0`**
   `DHCP Enabled. . . . . . . . . . . : No`
   `Autoconfiguration Enabled . . . . : Yes`
   `IPv6 Address. . . . . . . . . . . : 2001:0:9d38:6abd:3882:3089:bacd:5430(Preferred)`
   `Link-local IPv6 Address . . . . . : fe80::3882:3089:bacd:5430%59(Preferred)`
   `Default Gateway . . . . . . . . . :`
   `DHCPv6 IAID . . . . . . . . . . . : 989855744`
   `DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1F-78-C2-19-38-D5-47-23-08-52`
   `NetBIOS over Tcpip. . . . . . . . : Disabled`

**Comment by JasonLinMS** [comment] 2016-12-17 00:57
@therealkenc Thanks for your feedback, what you are saying does make sense, we've decided to truncate the physical address length returned by lxcore to 16 bytes.

**Comment by sunilmut** [comment] 2017-01-13 14:02
The teredo issue should be fixed in [15007](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-15007)

**Comment by Markus-ipse** [comment] 2017-01-26 20:37
Any ETA for when this fix will be available for people not able to use Insider preview builds (work computer)?

**Comment by benhillis** [comment] 2017-01-26 20:39
@Markus-ipse - Windows 10 Creator's update due later this year.

**Comment by Markus-ipse** [comment] 2017-01-26 20:53
Haha, could we get something a tad more specific than "later this year", since we're not event out of January yet? 😁

**Comment by benhillis** [comment] 2017-01-26 23:37
@Markus-ipse - we have not yet announced a release date beyond "Spring 2017"

https://www.microsoft.com/en-us/windows/upcoming-features

**Comment by buzinas** [comment] 2017-02-14 17:48
I already had this issue and I'm doing this as a workaround:

```javascript
// hack for Ubuntu on Windows
try {
  require('os').networkInterfaces();
}
catch (e) {
  require('os').networkInterfaces = () => ({});
}
```

Place that code in a file and require it in `webpack.config.js` file.

**Comment by Vheissu** [comment] 2017-02-22 12:04
@buzinas Brilliant. I love you. I didn't need to put it into a separate file, I just put it at the top of my Webpack config.

**Comment by Reon90** [comment] 2017-03-01 09:11
@buzinas Amazing!!!

**Comment by therealkenc** [comment] 2017-03-01 14:55
Almost as amazing as when it was posted by @ghost [last august](https://github.com/Microsoft/BashOnWindows/issues/468#issuecomment-239358331). 😉

**Comment by LeoLiuYan** [comment] 2017-03-16 08:44
@buzinas  Good!!!

**Comment by sunilmut** [comment] 2017-03-16 23:48
Closing the issue out since it is fixed in the insider builds.

**Closed by sunilmut** 2017-03-16 23:48 UTC
Labels: bug, fixedininsiderbuilds

**Comment by cbier1** [comment] 2017-04-20 17:52
@sunilmut Thank you! When will it be available for folks who do not use the insider builds?

**Comment by vunb** [comment] 2017-04-20 18:09
@cbier1 I'm running well on Windows 10 Creators Update 😁
