### ISSUE TITLE
Perl Modules

### ISSUE THREAD

**Issue by genio** [Microsoft/BashOnWindows#186] opened 2016-04-13 23:38 UTC
Installing Perl modules is an essential part of working with Perl.  Rather than get into an in-depth explanation of using `cpan` or `cpanm` along with `local::lib`, I'll just break it down into the simplest way possible, manual installation.

``` bash
root@localhost:~# curl -LO https://cpan.metacpan.org/authors/id/E/ET/ETHER/Try-Tiny-0.24.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30666  100 30666    0     0   100k      0 --:--:-- --:--:-- --:--:--  100k
root@localhost:~# tar zxvf Try-Tiny-0.24.tar.gz
Try-Tiny-0.24/
Try-Tiny-0.24/Changes
Try-Tiny-0.24/CONTRIBUTING
Try-Tiny-0.24/dist.ini
Try-Tiny-0.24/INSTALL
Try-Tiny-0.24/lib/
Try-Tiny-0.24/LICENCE
Try-Tiny-0.24/maint/
Try-Tiny-0.24/Makefile.PL
Try-Tiny-0.24/MANIFEST
Try-Tiny-0.24/META.json
Try-Tiny-0.24/META.yml
Try-Tiny-0.24/README
Try-Tiny-0.24/t/
Try-Tiny-0.24/xt/
Try-Tiny-0.24/xt/author/
Try-Tiny-0.24/xt/release/
Try-Tiny-0.24/xt/release/changes_has_content.t
Try-Tiny-0.24/xt/release/cpan-changes.t
Try-Tiny-0.24/xt/release/distmeta.t
Try-Tiny-0.24/xt/release/pod-no404s.t
Try-Tiny-0.24/xt/release/portability.t
Try-Tiny-0.24/xt/author/00-compile.t
Try-Tiny-0.24/xt/author/eol.t
Try-Tiny-0.24/xt/author/kwalitee.t
Try-Tiny-0.24/xt/author/mojibake.t
Try-Tiny-0.24/xt/author/no-tabs.t
Try-Tiny-0.24/xt/author/pod-coverage.t
Try-Tiny-0.24/xt/author/pod-spell.t
Try-Tiny-0.24/xt/author/pod-syntax.t
Try-Tiny-0.24/t/00-report-prereqs.dd
Try-Tiny-0.24/t/00-report-prereqs.t
Try-Tiny-0.24/t/basic.t
Try-Tiny-0.24/t/context.t
Try-Tiny-0.24/t/erroneous_usage.t
Try-Tiny-0.24/t/finally.t
Try-Tiny-0.24/t/given_when.t
Try-Tiny-0.24/t/global_destruction_forked.t
Try-Tiny-0.24/t/global_destruction_load.t
Try-Tiny-0.24/t/lib/
Try-Tiny-0.24/t/named.t
Try-Tiny-0.24/t/when.t
Try-Tiny-0.24/t/lib/TryUser.pm
Try-Tiny-0.24/maint/bench.pl
Try-Tiny-0.24/lib/Try/
Try-Tiny-0.24/lib/Try/Tiny.pm
root@localhost:~# cd Try-Tiny-0.24
root@localhost:~/Try-Tiny-0.24# ll
total 136
drwx------ 2  502 staff     0 Dec 11 05:20 ./
drwx------ 2 root root      0 Apr 13 23:35 ../
-rw------- 1  502 staff  2885 Dec 11 05:20 Changes
-rw-r--r-- 1  502 staff  3607 Dec 11 05:20 CONTRIBUTING
-rw------- 1  502 staff   837 Dec 11 05:20 dist.ini
-rw-r--r-- 1  502 staff   925 Dec 11 05:20 INSTALL
drwx------ 2  502 staff     0 Apr 13 23:35 lib/
-rw-r--r-- 1  502 staff  1182 Dec 11 05:20 LICENCE
drwx------ 2  502 staff     0 Apr 13 23:35 maint/
-rw-r--r-- 1  502 staff  1435 Dec 11 05:20 Makefile.PL
-rw-r--r-- 1  502 staff   714 Dec 11 05:20 MANIFEST
-rw-r--r-- 1  502 staff 41924 Dec 11 05:20 META.json
-rw-r--r-- 1  502 staff 24356 Dec 11 05:20 META.yml
-rw-r--r-- 1  502 staff   332 Dec 11 05:20 README
drwx------ 2  502 staff     0 Apr 13 23:35 t/
drwx------ 2  502 staff     0 Dec 11 05:20 xt/
root@localhost:~/Try-Tiny-0.24# perl Makefile.PL
Checking if your kit is complete...
Warning: the following files are missing in your kit:
        lib/Try/Tiny.pm
        maint/bench.pl
        t/00-report-prereqs.dd
        t/00-report-prereqs.t
        t/basic.t
        t/context.t
        t/erroneous_usage.t
        t/finally.t
        t/given_when.t
        t/global_destruction_forked.t
        t/global_destruction_load.t
        t/lib/TryUser.pm
        t/named.t
        t/when.t
        xt/author/00-compile.t
        xt/author/eol.t
        xt/author/kwalitee.t
        xt/author/mojibake.t
        xt/author/no-tabs.t
        xt/author/pod-coverage.t
        xt/author/pod-spell.t
        xt/author/pod-syntax.t
        xt/release/changes_has_content.t
        xt/release/cpan-changes.t
        xt/release/distmeta.t
        xt/release/pod-no404s.t
        xt/release/portability.t
Please inform the author.
Writing Makefile for Try::Tiny
Wide character in print at /usr/share/perl/5.18/ExtUtils/MakeMaker.pm line 1034.
Wide character in print at /usr/share/perl/5.18/ExtUtils/MakeMaker.pm line 1034.
Wide character in print at /usr/share/perl/5.18/ExtUtils/MakeMaker.pm line 1034.
Writing MYMETA.yml and MYMETA.json
root@localhost:~/Try-Tiny-0.24#
```

In short, Perl modules cannot be installed because, for some reason, the files aren't really there even though I can browse, view, edit, delete, etc. those files.

**Comment by sunilmut** [comment] 2016-04-14 00:06
Thanks for trying this out. Could you collect a strace for the 'perl Makefile.PL' command and see why it is complaining?

**Comment by genio** [comment] 2016-04-14 00:35
[trace.txt](https://github.com/Microsoft/BashOnWindows/files/218185/trace.txt)

**Comment by karenetheridge** [comment] 2016-04-16 19:18
What version of ExtUtils::MakeMaker is installed?

**Comment by karenetheridge** [comment] 2016-04-16 19:31
...and what version of ExtUtils::Manifest?

and then, can you try again with updated EUM+EUMM and see if the outcome is different/better?

**Comment by kentfredric** [comment] 2016-04-16 19:45
Just commenting to keep windows updated on the issue so it doesn't look like a tumbleweed.

Issue has been reproduced using Perl 5.18.2's File::Find ( which there is no upgrade path for without an upgrade of Perl itself ).

```
root@localhost:~/Try-Tiny-0.24# perl -MFile::Find -E 'say find({wanted=>sub{warn $File::Find::name}}, q(.))'
```
^ Shows only top level entries, fails to recurse.

```
root@localhost:~/Try-Tiny-0.24# find
```

^ However shows entries recursively.

**Comment by genio** [comment] 2016-04-16 20:22
Perl 5.18.2
ExtUtils::MakeMaker 6.66

I downloaded 7.1 and ran
```perl -I/root/ExtUtils-MakeMaker-7.10/lib Makefile.PL``` with the same result.

```perl -MFile::Find -E '$File::Find::dont_use_nlink=1; say find({wanted=>sub{warn $File::Find::name},no_chdir=>1}, q(.))``` shows all of the files

**Comment by genio** [comment] 2016-04-16 20:43
I forgot to mention that the version of ExtUtils::Manifest is 1.63

**Comment by genio** [comment] 2016-04-16 20:59
Well, doing the following will allow users to install modules:

1. ```yum install liblocal-lib-perl cpanminus build-essential```
1. ```vim /usr/share/perl/5.18/ExtUtils/Manifest.pm```
  * add ```$File::Find::dont_use_nlink=1;``` just before the call to ```find()```
1. ```eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"```
1. ```cpanm Try::Tiny```

This is just a work-around.

**Comment by yuki-kimoto** [comment] 2016-08-17 00:54
Latest Perl resolve File::Find problem?

Or problem is the implementation of hard link in "bash on windows" ?

**Comment by cthulhuology** [comment] 2016-08-17 17:27
A better patch than editing /user/share/perl/5.18/File/Find.pm is to change line 19 in /usr/lib/perl/5.18.2/Config.pm to:
`     dont_use_nlink => 1,`

**Comment by yuki-kimoto** [comment] 2016-08-18 00:29
This is great way! This is easy!

**Comment by yuki-kimoto** [comment] 2016-08-18 00:37
Improve the way to install cpan module.

1. `apt-get install liblocal-lib-perl cpanminus build-essentia`
2. `vim /usr/lib/perl/5.18.2/Config.pm`  `set dont_use_nlink => 1 line 94`
3. `eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"`
4. `cpanm Try::Tiny`

**Comment by genio** [comment] 2016-08-18 01:09
I'm not quite sure which is better.  The first way doesn't result in requiring Config.pm at all.  I'm not aware of anywhere else that uses the ```dont_use_nlink``` value within Config.pm other than File::Find.  However, if other places are relying on that value and get their information from Config.pm, then maybe the second one is better.

That being said, I updated the work-around to show both methods.  They're both a really easy on-line ```sed``` command.

**Comment by yuki-kimoto** [comment] 2016-08-18 12:44
I apply the above patch, and install some modules.

Installation of IO::Socket::IP 0.38 fail.

    Checking dependencies from MYMETA.json ...
    Checking if you have IO::Socket 0 ... Yes (1.36)
    Checking if you have Socket 1.97 ... Yes (2.009)
    Checking if you have Test::More 0.88 ... Yes (0.98)
    Building and testing IO-Socket-IP-0.38
    Building IO-Socket-IP
    t/00use.t ........................... ok
    t/01local-client-v4.t ............... ok
    t/02local-server-v4.t ............... ok
    t/03local-cross-v4.t ................ ok
    t/04local-client-v6.t ............... ok
    t/05local-server-v6.t ............... ok
    t/06local-cross-v6.t ................ ok
    t/10args.t .......................... ok
    t/11sockopts.t ...................... ok
    t/12port-fallback.t ................. ok
    t/13addrinfo.t ...................... ok
    t/14fileno.t ........................ ok
    t/15io-socket.t ..................... ok
    t/16v6only.t ........................ ok
    t/17gai-flags.t ..................... ok
    t/18fdopen.t ........................ ok
    t/19no-addrs.t ...................... ok
    t/20subclass.t ...................... ok
    t/21as-inet.t ....................... ok
    t/22timeout.t ....................... ok
    t/30nonblocking-connect.t ........... ok

    #   Failed test '$socket not yet connected'
    #   at t/31nonblocking-connect-internet.t line 38.

    #   Failed test '->connect eventually fails with ECONNREFUSED'
    #   at t/31nonblocking-connect-internet.t line 92.
    #   dollarbang = 通信端点が接続されていません
    # Looks like you failed 2 tests of 9.
    t/31nonblocking-connect-internet.t ..
    Dubious, test returned 2 (wstat 512, 0x200)
    Failed 2/9 subtests
    t/99pod.t ........................... skipped: Test::Pod 1.00 required for testing POD

**Comment by genio** [comment] 2016-08-18 13:31
@yuki-kimoto That module not installing is a different thing entirely.  For module support, you should really take this discussion to IRC:
[#IRC on irc.perl.org](https://chat.mibbit.com/?channel=%23mojo&server=irc.perl.org)

**Comment by ryanerwin** [comment] 2016-12-03 04:15
What is the Microsoft / Unbntu plan for this? Seems like the ideal think would be to make `nlink` work on WSL. In either case, I hope when I'm reinstalling or upgrading WSL I don't run into tweaking my `/usr/lib/perl/5.18.2/Config.pm` again...

**Comment by yorickdowne** [comment] 2016-12-03 10:14
Actually the ideal situation would be that File::Find detects that nlink can't be used, and disables it for us. nlink in File::Find breaks with many file systems, including ISO9660. Which is why File::Find tries (and fails on WSL) to figure out whether nlink can safely be used, and disables it if not.

In a discussion from 2000, Randal L. Schwartz said:

"If you find an architecture on which you need to set this manually, please report it to the developers. This is supposed to be set automatically on those system which need it. If it isn't, it's a bug."
http://www.perlmonks.org/?node_id=32791

Ideal situation? File::Find figures out to disable nlink when running on WSL. Whether that requires a change to File::Find or to WSL I wouldn't hazard a guess. 

It could be that File::Find's nlink detection is thrown off because it doesn't expect to be in a "Ubuntu on Windows" environment, in which case File::Find would need to change. 

It could be that File::Find's nlink detection doesn't work because WSL delivers the wrong answers to the tests File::Find makes to see whether nlink is supported, in which case WSL would need to change.

**Comment by ryanerwin** [comment] 2016-12-03 10:43
@yorickdowne 

I see your point. Looking at the `File::Find` code I see:

```
$File::Find::dont_use_nlink = 1
    if $^O eq 'os2' || $^O eq 'dos' || $^O eq 'amigaos' || $Is_Win32 ||
       $^O eq 'interix' || $^O eq 'cygwin' || $^O eq 'epoc' || $^O eq 'qnx' ||
     $^O eq 'nto';
```

Of course when I run:  `perl -e 'print $^O'` under WSL, I get `linux`.

I had a similar problem in my own `~/.zshrc`. There were some commands that I only wanted to run if I was running under WSL. Currently my solution is:

```
if [ -f "/mnt/c/Windows/System32/bash.exe" ]; then
  # must be running under WSL...
fi
```

The problem with this code is that someone may change their Windows folder to another location, but WSL doesn't have access to the windows environment variables to check for %WINDIR%.

Apparently some newer development versions of WSL support calling cmd.exe from inside WSL, so that may provide a better solution.

**Comment by yorickdowne** [comment] 2016-12-03 18:11
@ryanerwin Thanks for digging and finding that!

We can positively detect WSL via /proc/version and MS states they can't see a situation where they'd change that. See https://github.com/Microsoft/BashOnWindows/issues/423

Do you think checking for the presence of "Windows" in /proc/version just for nlink is the right way to go? 
I wouldn't want to set Is_Win32 because it's not, by and large apps should think they are on Linux. Ubuntu on WSL is close enough to Linux for that to be the right way to go, though there's no actual Linux anywhere to be seen, just a bunch of GNU and other apps running on WSL :).

If /proc/version is the right way to go here, I can create a pull request with it for File::Find (assuming that lives on GitHub).

**Comment by yorickdowne** [comment] 2016-12-03 19:35
Okay I have something that works. Insert this:

`# Special-case for WSL by reading /proc/version
if ($^O eq 'linux') {
    open my $lv, '<', '/proc/version';
    if (index(<$lv>,'Windows') || index(<$lv>,'WSL')) {
        $File::Find::dont_use_nlink = 1;
    }
    close $lv;
}`

just after this code in Find.pm:

`# These are hard-coded for now, but may move to hint files.
if ($^O eq 'VMS') {
    $Is_VMS = 1;
    $File::Find::dont_use_nlink  = 1;
}
elsif ($^O eq 'MSWin32') {
    $Is_Win32 = 1;
}`

I only dabble in Perl, so I'm not sure how to get this over to the perl devs for inclusion in File::Find.

**Comment by genio** [comment] 2016-12-03 19:44
```irc.perl.org #p5p``` or the [Perl 5 Porters Mailing list](https://www.nntp.perl.org/group/perl.perl5.porters/)

I've made the IRC channel aware of the discussion, but it can't hurt to start a mailing list discussion with the group about it.

**Comment by yorickdowne** [comment] 2016-12-03 19:53
Thank you @genio! I sent something out to the mailing list.

**Comment by yorickdowne** [comment] 2016-12-03 20:05
On further thought, this might be a little cleaner, just add another elsif to the existing section:

```
# These are hard-coded for now, but may move to hint files.
if ($^O eq 'VMS') {
    $Is_VMS = 1;
    $File::Find::dont_use_nlink  = 1;
}
elsif ($^O eq 'MSWin32') {
    $Is_Win32 = 1;
}
elsif ($^O eq 'linux') {
    open my $lv, '<', '/proc/version';
    if (index(<$lv>,'Windows') || index(<$lv>,'WSL')) {
        $File::Find::dont_use_nlink = 1;
    }
    close $lv;
}
```

**Comment by yorickdowne** [comment] 2016-12-04 03:46
@genio, P5P maintainers are a friendly and gracious bunch. I've received help and direction to satisfy the Ubuntu perl maintainers first, then they can submit upstream to P5P.

I've filed a bug for this in the Ubuntu system: https://bugs.launchpad.net/ubuntu/+source/perl/+bug/1647120

**Comment by Leont** [comment] 2016-12-04 14:17
How is this handled in find(1)? I would expect it to be broken too when not using `-noleaf`, yet apparently it isn't. It would need `-noleaf` too, right?

**Comment by yorickdowne** [comment] 2016-12-05 00:29
@Leont I'm not quite sure. I tried to go through the util.c in find(1), but I'm a bit lost as to how the auto-detection works. I know oldfind.c reads the entries, checks, and if stat doesn't match up, set's -noleaf automatically.
How current find handled that I didn't fully grasp. I'm assuming it has a similar detection mechanism somewhere.

**Comment by yorickdowne** [comment] 2016-12-05 00:42
James E. Keenan has a patch for this that also tidies up how dont_use_nlink is set. https://rt.perl.org/Public/Bug/Display.html?id=130258

**Comment by Leont** [comment] 2016-12-05 15:48
>  How current find handled that I didn't fully grasp. I'm assuming it has a similar detection mechanism somewhere.

File::Find also tries to detect this, in particular the nlink logic is disabled if is sees a directory with less than 2 links, but apparently it isn't triggered in this particular case.

**Comment by yorickdowne** [comment] 2016-12-05 20:38
Confirmed that this issue is also present in WSL Insider build 14965 with Ubuntu 16.04 LTS and perl v5.22.1. As we expected it would be, just crossing t's and making sure.

**Comment by yorickdowne** [comment] 2016-12-05 22:53
https://github.com/Microsoft/BashOnWindows/issues/910 might mean this gets fixed in WSL. It's not fixed there now, mind you, as far as I can tell. But if WSL learns how to handle the nlink hack, efforts to change File::Find should probably stop.

**Comment by Leont** [comment] 2016-12-06 15:40
> File::Find also tries to detect this, in particular the nlink logic is disabled if is sees a directory with less than 2 links, but apparently it isn't triggered in this particular case.

Can someone tell me what the link count of such a directory on WSL is? (`stat $dirname` should tell you).

**Comment by Leont** [comment] 2016-12-06 15:41
> File::Find also tries to detect this, in particular the nlink logic is disabled if is sees a directory with less than 2 links, but apparently it isn't triggered in this particular case.

Can someone tell me what the link count of such a directory on WSL is? (`stat $dirname` should tell you), along with the number of subdirectories.

**Comment by yorickdowne** [comment] 2016-12-06 16:11
tbehrens@DESKTOP-J1SS16J:~$ tree Test
Test
└── a
    ├── b
    │   ├── f1.txt
    │   └── f2.txt
    └── c

3 directories, 2 files
tbehrens@DESKTOP-J1SS16J:~$ stat Test
  File: 'Test'
  Size: 0               Blocks: 0          IO Block: 512    directory
Device: 11h/17d Inode: 1125899906978852  Links: 0
Access: (0777/drwxrwxrwx)  Uid: ( 1000/tbehrens)   Gid: ( 1000/tbehrens)
Access: 2016-12-06 11:08:09.880282000 -0500
Modify: 2016-12-06 11:08:09.880575400 -0500
Change: 2016-12-06 11:08:09.880575400 -0500
 Birth: -
tbehrens@DESKTOP-J1SS16J:~$ stat Test/a
  File: 'Test/a'
  Size: 0               Blocks: 0          IO Block: 512    directory
Device: 11h/17d Inode: 1125899906978859  Links: 0
Access: (0777/drwxrwxrwx)  Uid: ( 1000/tbehrens)   Gid: ( 1000/tbehrens)
Access: 2016-12-06 11:08:09.880509600 -0500
Modify: 2016-12-06 11:08:12.544527000 -0500
Change: 2016-12-06 11:08:12.544527000 -0500
 Birth: -
tbehrens@DESKTOP-J1SS16J:~$ stat Test/a/b
  File: 'Test/a/b'
  Size: 0               Blocks: 0          IO Block: 512    directory
Device: 11h/17d Inode: 5910974511060019  Links: 0
Access: (0777/drwxrwxrwx)  Uid: ( 1000/tbehrens)   Gid: ( 1000/tbehrens)
Access: 2016-12-06 11:08:09.880637000 -0500
Modify: 2016-12-06 11:08:22.798697400 -0500
Change: 2016-12-06 11:08:22.798697400 -0500
 Birth: -
tbehrens@DESKTOP-J1SS16J:~$ stat Test/a/c
  File: 'Test/a/c'
  Size: 0               Blocks: 0          IO Block: 512    directory
Device: 11h/17d Inode: 3096224743953465  Links: 0
Access: (0777/drwxrwxrwx)  Uid: ( 1000/tbehrens)   Gid: ( 1000/tbehrens)
Access: 2016-12-06 11:08:12.544411100 -0500
Modify: 2016-12-06 11:08:12.544411100 -0500
Change: 2016-12-06 11:08:12.544411100 -0500
 Birth: -

**Comment by ryanerwin** [comment] 2016-12-06 16:16
```
mkdir -p test1/{alpha}; touch test1/{a}; mkdir -p test2/{alpha,beta}; touch test2/{b,c}; mkdir -p test3/{alpha,beta,gamma}; touch test3/{a,b,c}

➜  % tree                                                                                                                                          0:15.
├── test1
│   ├── {a}
│   └── {alpha}
├── test2
│   ├── alpha
│   ├── b
│   ├── beta
│   └── c
└── test3
    ├── a
    ├── alpha
    ├── b
    ├── beta
    ├── c
    └── gamma

9 directories, 6 files

➜  % find . | xargs -n 1 stat | grep "File\\|Links"                                                                                                0:15
  File: ‘.’
Device: 1h/1d   Inode: 16607023625939185  Links: 2
  File: ‘./test1’
Device: 1h/1d   Inode: 27021597764469325  Links: 2
  File: ‘./test1/{alpha}’
Device: 1h/1d   Inode: 9288674231855754  Links: 2
  File: ‘./test1/{a}’
Device: 1h/1d   Inode: 13792273859226271  Links: 1
  File: ‘./test2’
Device: 1h/1d   Inode: 10696049115409146  Links: 2
  File: ‘./test2/alpha’
Device: 1h/1d   Inode: 16044073672911611  Links: 2
  File: ‘./test2/b’
Device: 1h/1d   Inode: 7599824371592357  Links: 1
  File: ‘./test2/beta’
Device: 1h/1d   Inode: 4503599627775068  Links: 2
  File: ‘./test2/c’
Device: 1h/1d   Inode: 14636698789358796  Links: 1
  File: ‘./test3’
Device: 1h/1d   Inode: 5629499534617819  Links: 2
  File: ‘./test3/a’
Device: 1h/1d   Inode: 8162774325014664  Links: 1
  File: ‘./test3/alpha’
Device: 1h/1d   Inode: 6473924464749840  Links: 2
  File: ‘./test3/b’
Device: 1h/1d   Inode: 8444249301725472  Links: 1
  File: ‘./test3/beta’
Device: 1h/1d   Inode: 4503599627775337  Links: 2
  File: ‘./test3/c’
Device: 1h/1d   Inode: 5066549581197810  Links: 1
  File: ‘./test3/gamma’
Device: 1h/1d   Inode: 9288674231856492  Links: 2
```

**Comment by yorickdowne** [comment] 2016-12-06 16:25
Ryan, which build is this? I'm a slightly older one, 14965 (because UUP work that started Friday the 2nd, all I had was ISO), and I'm getting 0 links for directories.

If this is fixed that'd be great news. Can you try:

```
perl -e 'use File::Find;find(sub {print $File::Find::name,$/;},".");'
```

And see whether it works recursively in your build? Assuming you didn't change don't_use_nlink that is, if you did, that will of course work.

**Comment by yorickdowne** [comment] 2016-12-06 16:46
I think I have to walk my statement back. Upon further testing, recursive File::Find appears to work in my build, and I can install modules from cpan. I fiddled with File::Find previously, but best as I can tell, I have removed those changes and dont_use_nlink is not being set manually.

It'd be good to have that confirmed.

**Comment by Leont** [comment] 2016-12-06 16:48
> It'd be good to have that confirmed.

A link count of `0` on the directory should disable the nlink optimization AFAICT. The whole optimization is assuming the `linkcount == $subdirs + 2`, and that evidently can't be the case if `$linkcount < 2` on a directory.

**Comment by yorickdowne** [comment] 2016-12-06 16:48
Right. So that'd mean my testing yesterday evening was sloppy, and MS **did** fix this in an insider build by forcing the link count to 0.

**Comment by ryanerwin** [comment] 2016-12-06 16:52
I've been testing on the default "Anniversary Edition" version of WSL, and switching between the default Ubuntu image and a CentOS 7 image.

When Config.pm: `dont_use_nlink => ''`
```
➜  % perl -e 'use File::Find;find(sub {print $File::Find::name,$/;},".");'                                                                         0:47.
./test1
./test2
./test3
```

When Config.pm `dont_use_nlink => 'defined'`
```
➜  % perl -e 'use File::Find;find(sub {print $File::Find::name,$/;},".");'                                                                         0:50.
./test1
./test1/{a}
./test1/{alpha}
./test2
./test2/b
./test2/c
./test2/alpha
./test2/beta
./test3
./test3/a
./test3/b
./test3/c
./test3/alpha
./test3/beta
./test3/gamma
```

**Comment by yorickdowne** [comment] 2016-12-06 16:55
Thanks @ryanerwin ! I think that's conclusive. In my system, `dont_use_nlink => undef` and as best I can tell I've removed the code I had previously added to File::Find, and I get:

```
tbehrens@DESKTOP-J1SS16J:~/Test$ perl -e 'use File::Find;find(sub {print $File::Find::name,$/;},".");'
.
./a
./a/b
./a/b/f1.txt
./a/b/f2.txt
./a/c
```

That'd mean MS has fixed it in Insider build, and therefore in Creator's Update, and my whole push towards changes in File::Find was misguided.

**Comment by jackchammons** [comment] 2016-12-14 23:16
@all As of build number 14986 I am no longer able to reproduce the original error that spawned this thread. Based on @yorickdowne 's comment above it looks like this issue has been fixed.

Feel free to reopen if I am closing prematurely.

**Closed by jackchammons** 2016-12-14 23:16 UTC
Labels: bug, fixedininsiderbuilds, workaround-available

**Comment by kenny-evitt** [comment] 2018-10-19 15:52
I'm having trouble *using* Perl modules, tho I couldn't see any obvious problems with them being installed.

I previously installed the *Crypt::HXSKPasswd* module without `sudo`. I got the same `command not found` error so I closed my Ubuntu window and opened a new one:

```bash
kenny@LT-NYC123:~$ hsxkpasswd
hsxkpasswd: command not found
kenny@LT-NYC123:~$ sudo cpan Crypt::HXSKPasswd
[sudo] password for kenny:
Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/home/kenny/.cpan/Metadata'
  Database was generated on Fri, 19 Oct 2018 15:17:03 GMT
kenny@LT-NYC123:~$ hsxkpasswd
hsxkpasswd: command not found
kenny@LT-NYC123:~$ cpan --help
Loading internal null logger. Install Log::Log4perl for logging messages
/usr/bin/cpan version 1.64 calling Getopt::Std::getopts (version 1.12 [paranoid]),
running under Perl version 5.26.1.

Usage: cpan [-OPTIONS [-MORE_OPTIONS]] [--] [PROGRAM_ARG1 ...]

The following single-character options are accepted:
        With arguments: -M -j
        Boolean (without arguments): -h -v -V -I -g -G -C -A -D -O -l -L -a -r -p -P -J -w -x -X -T -c -f -i -m -s -t -u

Options may be merged together.  -- stops processing of options.
Space is not required between options and their arguments.

For more details run
        perldoc -F /usr/bin/cpan
  [Now continuing due to backward compatibility and excessive paranoia.
   See 'perldoc Getopt::Std' about $Getopt::Std::STANDARD_HELP_VERSION.]
Nothing to install!
kenny@LT-NYC123:~$ perldoc -F /usr/bin/cpan
You need to install the perl-doc package to use this program.
kenny@LT-NYC123:~$ man cpan
kenny@LT-NYC123:~$ sudo cpan App::cpanminus
Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/home/kenny/.cpan/Metadata'
  Database was generated on Fri, 19 Oct 2018 15:17:03 GMT
Running install for module 'App::cpanminus'
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/M/MI/MIYAGAWA/CHECKSUMS
Checksum for /home/kenny/.cpan/sources/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for App::cpanminus
Writing MYMETA.yml and MYMETA.json
  MIYAGAWA/App-cpanminus-1.7044.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz
  MIYAGAWA/App-cpanminus-1.7044.tar.gz
  make -- NOT OK
  No such file or directory
kenny@LT-NYC123:~$ sudo cpanm --uninstall Crypt::HSXKPasswd
sudo: cpanm: command not found
kenny@LT-NYC123:~$ sudo apt install liblocal-lib-perl cpanminus build-essential
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package liblocal-lib-perl
E: Unable to locate package cpanminus
kenny@LT-NYC123:~$ sudo lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

**Comment by kenny-evitt** [comment] 2018-10-19 15:55
More attempts to get the module working:

```bash
kenny@LT-NYC123:~$ perl -MConfig -e'CORE::say $INC{"Config.pm"}'
/usr/lib/x86_64-linux-gnu/perl/5.26/Config.pm
kenny@LT-NYC123:~$ vim /usr/lib/x86_64-linux-gnu/perl/5.26/Config.pm
kenny@LT-NYC123:~$ sudo vim /usr/lib/x86_64-linux-gnu/perl/5.26/Config.pm
kenny@LT-NYC123:~$ sudo cpan Crypt::HXSKPasswd
Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/home/kenny/.cpan/Metadata'
  Database was generated on Fri, 19 Oct 2018 15:17:03 GMT
kenny@LT-NYC123:~$ hsxkpasswd
hsxkpasswd: command not found
kenny@LT-NYC123:~$ sudo cpan App::cpanminus
Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/home/kenny/.cpan/Metadata'
  Database was generated on Fri, 19 Oct 2018 15:17:03 GMT
Running install for module 'App::cpanminus'
Checksum for /home/kenny/.cpan/sources/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for App::cpanminus
Writing MYMETA.yml and MYMETA.json
  MIYAGAWA/App-cpanminus-1.7044.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz
  MIYAGAWA/App-cpanminus-1.7044.tar.gz
  make -- NOT OK
  No such file or directory
kenny@LT-NYC123:~$ sudo cpanm --help
sudo: cpanm: command not found
```
