### ISSUE TITLE
Folders are occasionally seen as Files

### ISSUE THREAD

**Issue by Plailect** [Microsoft/BashOnWindows#2425] opened 2017-08-15 19:33 UTC
Microsoft Windows [Version 10.0.16257.1] (running [alwsl/alwsl](https://github.com/alwsl/alwsl))

I first noticed this issue attempting to build a Jekyll site. I kept receiving various `File exists @ dir_s_mkdir`.

![image](https://user-images.githubusercontent.com/16979510/29332521-4c532b60-81ce-11e7-924e-51c5386f478d.png)

This seems to be because it cannot find the folder in the cache it expects, so it tries to create it only to discover that a "file" already exists with the same name. The problem with this is that there are no files, and viewing the cache directory with Explorer shows only folders.

![image](https://user-images.githubusercontent.com/16979510/29332571-7d6ef5a8-81ce-11e7-9156-405d8ddd14a0.png)

Additionally, the first `ls` of the directory claims to only see 4 folders and 8 files, yet subsequent `ls` attempts see all 12 folders (note that highlighted `ls` results are folders).

I cannot figure out why this only happens sometimes (though perhaps it is caused by the attempted Jekyll build process?), but on another instance of this bug I was able to use `ls -HALR`.

![image](https://user-images.githubusercontent.com/16979510/29332714-fb683f00-81ce-11e7-9e2f-b8bb50ae33ee.png)

Another time with two `ls -al` commands back to back:

![image](https://user-images.githubusercontent.com/16979510/29332965-f67cba10-81cf-11e7-8fe1-b611615a8b71.png)

Additionally, attempting to `cat` one of these "files" (while WSL still thinks they are files) causes a BSOD with the error `kernel_data_inpage_error`.

**Comment by benhillis** [comment] 2017-08-15 19:42
duplicate of #2392

**Closed by benhillis** 2017-08-15 19:42 UTC
