### ISSUE TITLE
ln -s have BUG  don't open the secondary directory

### ISSUE THREAD

**Issue by swat199538** [Microsoft/BashOnWindows#1826] opened 2017-03-29 08:36 UTC
swat@DESKTOP-O3S2D9N:/var/www$ sudo ln -s /mnt/c/Linux/
swat@DESKTOP-O3S2D9N:/var/www$ ls
Linux
swat@DESKTOP-O3S2D9N:/var/www$ cd Linux
swat@DESKTOP-O3S2D9N:/var/www/Linux$ ls
000-default.conf  blog  test
swat@DESKTOP-O3S2D9N:/var/www/Linux$ cd test/
swat@DESKTOP-O3S2D9N:/var/www/Linux/test$ ls
000-default.conf  blog  test
swat@DESKTOP-O3S2D9N:/var/www/Linux/test$ ls
000-default.conf  blog  test
swat@DESKTOP-O3S2D9N:/var/www/Linux/test$

I can't open the secondary directory

**Comment by aseering** [comment] 2017-03-29 14:53
Hi @swat199538 , thanks for posting!  This sounds like the same issue as #729 , which in turn has the same root cause as #650 and which has been fixed in recent [Insider builds](https://insider.windows.com).  Could you take a look?

**Comment by benhillis** [comment] 2017-03-29 15:03
Agreed, closing as a duplicate.

**Closed by benhillis** 2017-03-29 15:03 UTC
