### ISSUE TITLE
find command output newline problem

### ISSUE THREAD

**Issue by mertkaplanTR** [Microsoft/BashOnWindows#1097] opened 2016-09-18 20:37 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
Bash on Ubuntu on Windows has some newline issue about find command.
Example command:
find .  -name '*.txt' > /mnt/c/ExpectResultHaveNoNewLine.txt

* Expected results
In /mnt/c/ExpectResultHaveNoNewLine.txt
Should be line by line:
1.txt
2.txt
3.txt

* Actual results (with terminal output if applicable)
Terminal output working well but while writing the ExpectResultHaveNoNewLine.txt
1.txt2.txt3.txt
* Your Windows build number
14393.187
* Steps / All commands required to reproduce the error from a brand new installation 
----
* Strace of the failing command
find .  -name '*.txt' > /mnt/c/ExpectResultHaveNoNewLine.txt
* Required packages and commands to install
---
See [our contributing instructions](/CONTRIBUTING.md) for assistance.
![capture1](https://cloud.githubusercontent.com/assets/8864161/18618902/c7682376-7df8-11e6-9f78-dea13c91e39b.PNG)
![capture2](https://cloud.githubusercontent.com/assets/8864161/18618903/cc899308-7df8-11e6-9c90-cb8dfefa86c4.PNG)

**Comment by wizardist** [comment] 2016-09-19 12:10
It's an issue in Notepad, WSL and Ubuntu in general do fine. It only recognizes `\r\n` as a new-line delimiter (thus called "Windows style"). In Linux and other Unix-derived systems `\n` is used to delimit new lines (called "Unix style").

NOTABUG.

**Comment by fpqc** [comment] 2016-09-19 14:31
Some history:
The \r (carriage return) and \n (line feed) thing is actually pretty cool, but first one thing I noticed just now: In linux, sometimes you have weird behavior that can occur in a *nix tty when the system is having a problem.  This behavior makes it so newlines in the tty will start directly beneath the end of the previous line.  There are all kinds of funny bugs that do this, and it's interesting because it's exactly what you would imagine a teletype (TTY, remember) would do if you only fed it a line feed without a preceding carriage return.

Microsoft's convention of new lines in text documents requiring both 
carriage return `\r` and a line feed `\n` 
comes from the old convention on teletypes, where these control codes respectively tell the carriage (the assembly containing the writing head mechanism) to return to the beginning of the line and then tell the teletype to feed the paper up by one line.  

Microsoft is pretty old as far as software companies go, and it adopted the original convention used in teletypes.  As teletypes fell out of style in favor of electronic terminals and crt monitors, lots of other operating systems dropped the carriage return, but Microsoft has kept it all these years in order to support backwards compatibility (same reason as much of the weird stuff in Windows, like the UTF-16 little endian character set used in every single part of NT, from top to bottom, before UTF-8 became popular through the web).

That said, they should just add a stupid compatibility mode for notepad like they did in conhost, but I guess we'll see.

VS Code can read those files fine though, and it's really nice and fast (and open source/free software and has a bunch of nice plugins with a central repository).  Or you can use SublimeText, which is free for personal use and also really nice, with lots of cool shiny features that integrate regexp and manual highlighting (multiple highlights and caret for multi-replace without having to manually create a regexp, a trivial case of which is allowing you to type on multiple lines at the same time, which is a demo on their site).

**Comment by amanuel2** [comment] 2016-10-15 22:48
Can someone fix this please? It is affecting BoneOS(github.com/Bone-Project/BoneOS) , with the Root Makefile.. The variables get messed up with the carriage return. Thank you!

**Comment by ericblade** [comment] 2016-10-15 23:43
fix... what? the bug seems to indicate the rather well known phenomenon that Notepad doesn't deal correctly with Unix EOLs.  As far as I know, everything WSL side is working as it should?

**Comment by amanuel2** [comment] 2016-10-16 00:10
Windows uses carriage return and new line . I am trying to say fix it so it has like *NIX Operating system just a new line.

**Comment by aseering** [comment] 2016-10-16 01:03
@amanuel2 -- why are you trying to use Notepad?  I think this is not a bug; I think it is a case of your trying to use a program that is not appropriate for your task.

**Comment by benhillis** [comment] 2016-10-16 01:16
This issue is older than the internet. I'd suggest either using a different text editor or using the Linux tool dos2unix to change \r\n into \n. 

Closing this out as by design.

**Closed by benhillis** 2016-10-16 01:16 UTC
Labels: console
