### ISSUE TITLE
apt-get update connection failed

### ISSUE THREAD

**Issue by Rfilip** [Microsoft/BashOnWindows#761] opened 2016-08-04 09:37 UTC
* A brief description

After install of BOW I tried to update packages
* Expected results

Updated list of packages
* Actual results (with terminal output if applicable)

Apt-get can't connect to internet, I see those lines repeating
```
Cannot initiate the connection to security.ubuntu.com:80 (91.189.88.162). - connect (13: Permission denied) [IP: 91.189.88.162 80]
Cannot initiate the connection to archive.ubuntu.com:80 (91.189.88.162). - connect (13: Permission denied) [IP: 91.189.88.162 80]
```
full log here: https://gist.github.com/Rfilip/20b92f3ad44a28a9a52e8222949baacc

My internet conection is Wired with DHCP.
* Your Windows build number

Microsoft Windows [Version 10.0.14393]
* Steps / commands required to reproduce the error

` sudo apt-get update`
* Strace of the failing command

https://gist.github.com/Rfilip/20b92f3ad44a28a9a52e8222949baacc
* Required packages and commands to install

**Comment by Tekki** [comment] 2016-08-04 10:57
Had the same problem. When I stop Kaspersky Internet Security it works.

**Comment by Rfilip** [comment] 2016-08-04 11:26
I have AVG Internet Security but disabling it don't solve problem

**Comment by onomatopellan** [comment] 2016-08-04 12:59
You probably will need to uninstall it instead of disabling it. Same happens with Avast.

**Comment by Tekki** [comment] 2016-08-04 13:08
For Kaspersky, this issue is already discussed in the forum: https://forum.kaspersky.com/index.php?showtopic=354919

**Comment by Rfilip** [comment] 2016-08-04 14:55
Thanks, uninstalling AVG did its job. Apt-get and other network using commands works now.

**Comment by russalex** [comment] 2016-08-04 16:07
Linking this one to #475.  We are aware of the firewall issues (both inbound and outbound traffic) and are looking into it.

**Comment by jackchammons** [comment] 2016-10-25 00:27
Closing as duplicate of #475

**Closed by jackchammons** 2016-10-25 00:27 UTC
Labels: duplicate

**Comment by naitsirhc007** [comment] 2017-04-01 07:06
Thanks, Kaspersky was the problem, I was uninstall and reinstall bash... 
thx

**Comment by MarcelBlanck** [comment] 2019-02-15 22:01
In Bitdefender Total Security I deactivated the firewall and it works. No need to uninstall or reinstall anything, it's just the firewall. But I was not able to add a rule for /usr/lib/apt/methods/http (not even automatically when I enable alert for each connection) - it tells me the path is not valid. Setting a rule for bash.exe did not help at all.

So I think Bitdefender's Firewall is simply not designed to work with Ubuntu's internal file system on Windows. Turn the Firewall off while developing and turn it on while surfing and you should be fine.

**Comment by rohantalesara** [comment] 2019-04-17 15:58
This link on the Kaspersky forum helped me: https://forum.kaspersky.com/index.php?/topic/395813-bash-windows-10-wsl-connection-issues/

I disabled the HTTPS rules as explained in one of the posts. Settings > Additional > Network > Monitored ports: Monitor selected ports only > Select > Disabling the HTTPS rule.
