### ISSUE TITLE
setsockopt for system_name = IP_MTU_DISCOVER does not work.

### ISSUE THREAD

**Issue by migueldeicaza** [Microsoft/BashOnWindows#2115] opened 2017-05-16 17:14 UTC
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Windows 10.0.15063

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Trying to use Ubuntu's Mono to and use the web stack, this relies on `setsockopt` to implement support for `IP_MTU_DISCOVER` to implement the .NET `DontFragment` property on `System.Socket`.

To reproduce, install with apt-get mono 5.0 on Ubuntu 16.04:

```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/ubuntu xenial main" | sudo tee /etc/apt/sources.list.d/mono-official.list
sudo apt-get update
```

Then run:

```
csharp -e 'new System.Net.WebClient ().DownloadString ("https://www.microsoft.com")
```

This aborts.

* What's wrong / what should be happening instead:

The call should succeed.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

```
setsockopt (sockfd, SOL_IP, IP_MTU_DISCOVER, [0], 4) = -1 EINVALI
```

**Comment by sunilmut** [comment] 2017-05-17 02:06
@migueldeicaza - Thanks for your post and detailed issue report. Is the `sockfd` a TCP socket? That part of the strace is missing and so I cannot tell. If so, the support for `IP_MTU_DISCOVER` for TCP sockets was just checked in the dev branch (internal) today :). It should make it's way to the Insiders build soon. It `sockfd` is a UDP socket, then the support for it was enabled in build [15002](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-15002). I would be very surprised if it's a UDP socket.

**Comment by therealkenc** [comment] 2017-05-17 22:19
>  I would be very surprised if it's a UDP socket.

C# System.Net.WebClient(). Don't even need to guess. Nice to see `IP_MTU_DISCOVER` for TCP sockets ticked off the list. 💯

**Comment by sunilmut** [comment] 2017-06-14 19:09
Marking this duplicate of #1639

**Comment by sunilmut** [comment] 2017-06-22 18:22
This should be fixed in Insider build [16215(https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16215)

**Closed** 2017-06-26 19:52 UTC
Labels: fixedininsiderbuilds, network
