### ISSUE TITLE
On local server start error says the port is already in use

### ISSUE THREAD

**Issue by maroof-ahmad** [Microsoft/BashOnWindows#740] opened 2016-08-03 16:52 UTC
* While restarting the Django development server the error comes up which says that the port is already in use

* Server should restart normally as it does on cmd

* Server doesn't restart

* Windows build number - 14393.10

![capture](https://cloud.githubusercontent.com/assets/11515513/17374205/1e7b759a-59c9-11e6-8041-a920b34b75ac.PNG)

**Comment by wtchangdm** [comment] 2016-08-03 17:27
Can confirm on the same windows version.

I've run bash on administrator and tried to run nginx

`wtc@DESKTOP:~$ sudo netstat -tulpn | grep :80`
`wtc@DESKTOP:~$ sudo /usr/sbin/nginx -t`
`nginx: the configuration file /etc/nginx/nginx.conf syntax is ok`
`nginx: configuration file /etc/nginx/nginx.conf test is successful`
`wtc@DESKTOP:~$ sudo /usr/sbin/nginx`
`nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)`
`nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)`
`nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)`
`nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)`
`nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)`
`nginx: [emerg] still could not bind()`
`wtc@DESKTOP:~$`

**Comment by misenesi** [comment] 2016-08-03 17:58
When you run in another cmd.exe:

netstat -anb

Do you see the port being occupied? If you run in bash:

lsof -i :8000

Can you see who is using that port?

**Comment by dvlsg** [comment] 2016-08-03 18:04
I also have this issue, but with redis. `lsof -i :6379` doesn't report that anything is already using the port. `netstat -anb` from `cmd.exe` confirms the same.

Output from running a newly built `redis-server` (with default configuration) states:
`Creating server TCP listening socket *:6379: bind: Address already in use`

**Comment by misenesi** [comment] 2016-08-03 18:07
Could you provide repro steps along with strace please, so I can look more into it?

More here:
https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md

**Comment by dvlsg** [comment] 2016-08-03 18:36
Of course! I can re-open a separate ticket if you think the issues are unrelated.

Here is the gist containing the strace created with `strace redis-server &> redis-server-strace.txt`

[https://gist.github.com/dvlsg/6232d2adde9971a3479c848ce5b2704b](https://gist.github.com/dvlsg/6232d2adde9971a3479c848ce5b2704b)

And here are the steps I used to install `redis` (taken from their [website](http://redis.io/topics/quickstart), and slightly modified to get around some issues I ran into). So to reproduce, from start to finish:

```bash
wget http://download.redis.io/redis-stable.tar.gz
tar xvzf redis-stable.tar.gz
cd redis-stable/deps
# i had to first make each dep manually, for some reason.
make geohash-int hiredis jemalloc linenoise lua
cd ..
make
cd src
redis-server
```

And just to reconfirm, the following two commands result in empty outputs (I also looked through the `netstat` by hand, just in case I was misremembering how `findstr` worked);

```
netstat -anb | findstr 6379
lsof -i :6379
```

**Comment by mmalek06** [comment] 2016-09-02 18:45
Any info on what's the expected time of fix release? I'm experiencing the same exact issue as the guys.

**Comment by sunilmut** [comment] 2016-09-02 21:29
This looks related to #996. Essentially, the problem is lack of full support for IPV6_V6ONLY. See #996 for detailed analysis. Apologize for the inconvinience. We are actively working with the Windows networking team to address this issue and expect it to be fixed shortly. But as a workaround, you can try using only IPV4 or different ports for IPV4 and IPV6.

From the trace shared by @dvlsg 
`setsockopt(4, SOL_IPV6, **IPV6_V6ONLY**, [1], 4) = 0
setsockopt(4, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(4, {sa_family=AF_INET6, sin6_port=**htons(6379),** inet_pton(AF_INET6, "::", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 0
socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 5
setsockopt(5, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(5, {sa_family=AF_INET, sin_port=**htons(6379**), sin_addr=inet_addr("0.0.0.0")}, 16) = -1 EADDRINUSE (Address already in use)`

**Comment by sunilmut** [comment] 2016-09-14 21:50
With the help of the Windows networking team, we were able to fully implement the IPV6_V6ONLY flag. I was able to get the `redis-server` up and running by following the repro about by @dvlsg. The fix is still in our dev branch, but should soon hit the release branch.

**Comment by sunilmut** [comment] 2016-09-29 02:19
Just FYI that the IPV6_V6ONLY issue is fixed in 14936 (see [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes))

**Comment by sunilmut** [comment] 2016-10-14 18:39
Closing this out. If this is still failing for people in 14942+, do let us know.

**Closed by sunilmut** 2016-10-14 18:39 UTC
Labels: fixed
