### ISSUE TITLE
Interrupted system call error

### ISSUE THREAD

**Issue by rameshb2** [Microsoft/BashOnWindows#1198] opened 2016-10-12 18:05 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
On occasion, commands fail to execute on BashOnWindows.
For example, when I run the following command on bash on ubuntu on windows: 
go get github.com/blynn/nex

I get the following error message:
go build github.com/blynn/nex: /usr/local/go/pkg/tool/linux_amd64/link: read |0: interrupted system call

Other users have reported the same problem. However, this seems to be intermittent. Subsequent invocations of the same command may get through just fine.

* Expected results
No error when executing go command

* Actual results (with terminal output if applicable)
~/work/src/github.com/blynn/nex/test$ go test 
go build github.com/blynn/nex/test: /usr/local/go/pkg/tool/linux_amd64/compile: read |0: interrupted system call 
FAIL github.com/blynn/nex/test [build failed]

~/work/src/github.com/blynn/nex/test$ go test 
--- FAIL: TestNexPrograms (3.41s) 
nex_test.go:38: wc.nex go build command-line-arguments: /usr/local/go/pkg/tool/linux_amd64/link: read |0: interrupted system call 
2016/10/12 11:23:43 go run: exit status 1 
: exit status 1 
--- FAIL: TestGiantProgram (0.10s) 
nex_test.go:38: nex: package main 
import "./nex_test0" 
import "./nex_test1" 
import "./nex_test2" 
: read |0: interrupted system call 
FAIL 
exit status 1 
FAIL github.com/blynn/nex/test 4.307s

* Your Windows build number

Version 1607 (OS Build 14393.222)

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install

Install go language tools
Install nex from http://crypto.stanford.edu/~blynn/nex/

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by sunilmut** [comment] 2016-10-12 18:10
@SvenGroot as FYI as this seems related to "restartable system calls"
@rameshb2 - Thanks for reporting the issue.

**Comment by stehufntdev** [comment] 2016-10-12 19:55
This is a duplicate of #349.  The issue is fixed in the Windows Insider builds. 14393 is the Anniversary update build, which does not get the Insider updates until the next release. If joining the Insider program works for you, that's the best place to get updates for this feature, at the moment.

**Closed by stehufntdev** 2016-10-12 19:55 UTC

**Comment by rameshb2** [comment] 2016-10-13 12:03
Thanks! Appreciate you taking a look at this issue. If it comes to it, I'll switch to an insider build. (But I'd rather not, because I support customers who do not have access or the know how to install non-standard builds). When do you think this update is going to get rolled out?


Regards,


--ramesh


________________________________

**Comment by stehufntdev** [comment] 2016-10-13 14:10
The update should be available with the next official release, but I don't think that a date has been announced yet.

**Comment by technowar** [comment] 2016-10-20 00:08
Great. Thanks @stehufntdev
