### ISSUE TITLE
DISABLE_NEWLINE_AUTO_RETURN has unexpected impact on applications that output \n

### ISSUE THREAD

**Issue by cowwoc** [Microsoft/BashOnWindows#1273] opened 2016-10-26 05:13 UTC
* A brief description
I don't know if this is considered a bug or a "feature" but enabling DISABLE_NEWLINE_AUTO_RETURN seems to cause the console to swallow carriage returns. When I output "foo\nbar" (in Java) I get:

* Expected results
foo
[Caret moves to the beginning of the next line]
bar

* Actual results (with terminal output if applicable)
foo
[horizontal space]bar

(that is, I get a newline but no carriage return)

* Your Windows build number
Both 10.0.14393 and 10.0.14946

**Comment by fpqc** [comment] 2016-10-26 06:13
Hey Cowwoc, is this in WSL or in Windows Java?

**Comment by cowwoc** [comment] 2016-10-26 13:18
Java running under cmd.exe (so I guess Windows Java).

**Comment by fpqc** [comment] 2016-10-26 14:23
@cowwoc Ok, well I just want you to know that in general this is an inappropriate place to post this.  Maybe we can ask @zadjii-msft where is a better place.

**Comment by cowwoc** [comment] 2016-10-26 14:40
Fair enough. I was also wondering the same thing. I looked at the forums but they didn't seem appropriate for this either.

**Comment by stehufntdev** [comment] 2016-10-26 16:17
Yes @zadjii-msft can probably point you in the right direction but closing this out for now since it isn't a WSL issue.

**Closed by stehufntdev** 2016-10-26 16:17 UTC
Labels: console

**Comment by cowwoc** [comment] 2016-10-26 17:21
@zadjii-msft Waiting for your response...

**Comment by zadjii-msft** [comment] 2016-10-27 15:20
I'll say, this is still the best place for console issues of any type, until we can get @bitcrazed freed up from bureaucracy to figure out a better option.

@cowwoc What you're seeing here is the expected behavior of DISABLE_NEWLINE_AUTO_RETURN. Typically in the console, when you emit a '\n' or "Line Feed", what the console performs is "\r\n", or Carriage Return + Line Feed. Technically, '\n' should only ever bring you down one line from where the cursor currently is (`y++`), and '\r' is only for resetting the horizontal position of the cursor (x=0).

However, most applications only emit a '\n', and on *nix systems, the stty will perform both for you.
From `man stty`:
``` man
onlcr: translate newline to carriage return-newline
```

Windows would emulate this behavior by performing a full CRLF in just a '\n'. However, we found in implementing the WSL that we'd need a mode for not doing the CR on a LF, so that's what DISABLE_NEWLINE_AUTO_RETURN does. It prevents the CR on newlines. What you're seeing is the expected behavior.

**Comment by cowwoc** [comment] 2016-10-27 19:02
@zadjii-msft Thanks for the clarification. I humbly suggest that you revise the documentation, specification the sentence that reads:

>In contrast with this flag set, the scroll operation and cursor move is **delayed** until the next character arrives.

My interpretation of this sentence is that the flag simply delays an operation. You seem to be implying that the flag actually disables the carriage return rendering indefinitely. That is definitely not clear (to me) from the existing documentation.

**Comment by zadjii-msft** [comment] 2016-10-27 19:27
Oh would you look at that. That description looks familiar, and like it's describing something like DELAYED_NEWLINE_AUTO_RETURN. I vaguely recall something like that getting implemented, but it might have just been rolled in to DISABLE_NEWLINE_AUTO_RETURN. 

@miniksa for guidance, he might remember better.

**Comment by miniksa** [comment] 2016-10-27 19:30
@cowwoc... where did you find that line of text. I'm half-way through a slow going process of overhauling console documentation and have seen enough varying descriptions of things to make my head spin.

Give me the URL with the incorrect description and I can have it corrected.

**Comment by cowwoc** [comment] 2016-10-27 19:31
@miniksa In https://msdn.microsoft.com/en-us/library/windows/desktop/ms683167(v=vs.85).aspx search for:

> In contrast with this flag set, the scroll operation and cursor move is delayed until the next character arrives.

**Comment by miniksa** [comment] 2016-10-27 19:41
OK. I filed 9557746 internally and will route it to the team to update MSDN.

I think this happened because in preview releases of Anniversary Update, I was experimenting with DELAYED vs. DISABLED newline-auto-return to try to figure out the best way to mesh with WSL. And then we figured out about the stty thing with onlcr and converged it on DISABLED as the correct solution. I probably fixed the code and forgot to go back and update the document I sent to content publishing for MSDN for RTM and overlooked it again on proofreading before it was published. :( Sorry about that.

I had never really intended this flag to be used with anything except WSL and WSL-type tools, but because it's a public API, I'm compelled to publish what I do and add on MSDN in case anyone else has a use case for it. :)

I'm hoping to move the console docs to open publishing like the WSL ones are sometime so we can correct these things faster and provide better help content. But for now, I'll try to get this fixed through the existing publishing process. Please let us know if you find anything else or have any other questions about it.

**Comment by cowwoc** [comment] 2016-10-27 19:45
@miniksa Beware https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx

It mentions `DISABLE_NEWLINE_AUTO_RETURN` twice. The first one encourage users to use it (outside of WSL). The second one is sample code that encourages users to set it.

If this flag is meant for internal use, I would remove it from both those places.

**Comment by miniksa** [comment] 2016-10-27 19:51
@cowwoc  Well it's not really for internal-only use or I would have made it an internal-only API.

It's intended most specifically for compatibility with Emacs in a Linux environment where it purposefully uses newlines alone as a minimal-bytes way of moving the cursor down a row.

I probably don't need to discourage usage but more clarify what I mean for its usage (e.g. if you're doing 100% your own rendering in minimal-byte-streams like Emacs does OR you have another platform already handling your line discipline like stty, then use this flag.)

**Comment by cowwoc** [comment] 2016-10-27 19:55
@miniksa Okay, sounds good. How do I subscribe for notification when the MSDN page gets updated?

**Comment by miniksa** [comment] 2016-10-27 19:56
@cowwoc I honestly have no idea. If there's anything I can answer for you here, I'm happy to do so at this time. I'm following up with my team on getting a better content publishing story.
