### ISSUE TITLE
Glasgow Haskell Compiler and binaries built with it crash

### ISSUE THREAD

**Issue by AaronFriel** [Microsoft/BashOnWindows#112] opened 2016-04-10 20:58 UTC
`apt-get install ghc` fails here:

```
Setting up ghc (7.6.3-10) ... 
ghc: timer_create: Invalid argument 
update-alternatives: using /usr/bin/ghc to provide /usr/bin/haskell-compiler (haskell-compiler) in auto mode 
ghc-pkg: timer_create: Invalid argument 
dpkg: error processing package ghc (--configure): 
subprocess installed post-installation script returned error exit status 1 
Processing triggers for libc-bin (2.19-0ubuntu6.7) ... 
dmesg: klogctl failed: Invalid argument 
/bin/df: cannot read table of mounted file systems: No such file or directory 
Errors were encountered while processing: 
ghc 
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Attempting to install the [Haskell Stack](https://github.com/commercialhaskell/stack) also fails with `timer_create: Invalid argument`. Both ghc and stack are compiled with the threaded runtime by default. The call to `timer_create` is [here](https://github.com/ghc/ghc/blob/master/rts/posix/Itimer.c#L258) in `ltimer.c` of the GHC source.

**Comment by voltagex** [comment] 2016-04-11 01:28
There are a number of problems here that are probably worthy of their own bugs:

* timer_create appears to be a syscall that isn't supported

* klogctl is another unsupported syscall

* df -h fails because it can't read `/proc/self/mountinfo` or `/etc/mtab`

**Comment by CoderDennis** [comment] 2016-04-14 12:13
elm gets the same `timer_create: Invalid argument` error. It's compiled from Haskell, so sounds like the same issue.

**Comment by PatrickLang** [comment] 2016-04-26 19:02
Same with PanDoc.

```
apt-get install pandoc
...
patrick@DESKTOP-MHE51S4:~$ pandoc
pandoc: timer_create: Invalid argument
```

**Comment by fredzannarbor** [comment] 2016-05-02 19:36
Pandoc error is on my critical path.

**Comment by mysteryjeans** [comment] 2016-07-29 12:02
I am back to VM because of this :(

**Comment by KitFreddura** [comment] 2016-08-07 02:54
Same issue, frustrating as I use Haskell quite often, is there any roadmap for this problem?

**Comment by benhillis** [comment] 2016-10-31 19:56
Marking this thread as a duplicate of #307. Fix is inbound to Windows Insider builds.

**Closed by benhillis** 2016-10-31 19:56 UTC
Labels: bug

**Comment by AaronFriel** [comment] 2017-05-17 00:18
@benhillis This should be relabeled closed, I believe?
