### ISSUE TITLE
shmget: function not implemented

### ISSUE THREAD

**Issue by rorybolt** [Microsoft/BashOnWindows#1134] opened 2016-09-28 04:22 UTC
* Attempting to run fio resulted in the following error messages:
shmget: Function not implemented
error: failed to setup shm segment

* Expected results - benchmarking output characterizing the I/O subsystem

* Actual results (with terminal output if applicable)
shmget: Function not implemented
error: failed to setup shm segment

* Your Windows build number
Version 1607 (OS Build 14393.187)

* Steps / All commands required to reproduce the error from a brand new installation 
sudo apt-get install fio
fio --name=randrw --ioengine=libaio --direct=1 --bs=4k --iodepth=64 --size=4G --rw=randrw --rwmixread=75 --gtod_reduce=1

* Strace of the failing command
rory@IOSTATION:/mnt/c/Windows/System32$ strace fio --name=randrw --ioengine=libaio --direct=1 --bs=4k --iodepth=64 --siz
e=4G --rw=randrw --rwmixread=75 --gtod_reduce=1
execve("/usr/bin/fio", ["fio", "--name=randrw", "--ioengine=libaio", "--direct=1", "--bs=4k", "--iodepth=64", "--size=4G", "--rw=randrw", "--rwmixread=75", "--gtod_reduce=1"], [/* 15 vars */]) = 0
brk(0)                                  = 0x1c7a000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e0c660000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=18971, ...}) = 0
mmap(NULL, 18971, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f8e0c66b000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/librdmacm.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20&\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=55960, ...}) = 0
mmap(NULL, 2151752, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8e0c1f0000
mprotect(0x7f8e0c1fd000, 2093056, PROT_NONE) = 0
mmap(0x7f8e0c3fc000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xc000) = 0x7f8e0c3fc000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/usr/lib/libibverbs.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`7\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=56128, ...}) = 0
mmap(NULL, 2151360, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8e0bfe0000
mprotect(0x7f8e0bfec000, 2097152, PROT_NONE) = 0
mmap(0x7f8e0c1ec000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xc000) = 0x7f8e0c1ec000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P#\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=31792, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e0c650000
mmap(NULL, 2129016, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8e0bdd0000
mprotect(0x7f8e0bdd7000, 2093056, PROT_NONE) = 0
mmap(0x7f8e0bfd6000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6000) = 0x7f8e0bfd6000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libaio.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\360\4\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=5256, ...}) = 0
mmap(NULL, 2101296, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8e0bbc0000
mprotect(0x7f8e0bbc1000, 2093056, PROT_NONE) = 0
mmap(0x7f8e0bdc0000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0) = 0x7f8e0bdc0000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\36\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=100728, ...}) = 0
mmap(NULL, 2195784, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8e0b9a0000
mprotect(0x7f8e0b9b8000, 2093056, PROT_NONE) = 0
mmap(0x7f8e0bbb7000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7f8e0bbb7000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20V\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=1071552, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e0c640000
mmap(NULL, 3166568, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8e0b690000
mprotect(0x7f8e0b795000, 2093056, PROT_NONE) = 0
mmap(0x7f8e0b994000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x104000) = 0x7f8e0b994000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0po\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=141574, ...}) = 0
mmap(NULL, 2217264, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8e0b470000
mprotect(0x7f8e0b489000, 2093056, PROT_NONE) = 0
mmap(0x7f8e0b688000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18000) = 0x7f8e0b688000
mmap(0x7f8e0b68a000, 13616, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f8e0b68a000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\16\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=14664, ...}) = 0
mmap(NULL, 2109744, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8e0b260000
mprotect(0x7f8e0b263000, 2093056, PROT_NONE) = 0
mmap(0x7f8e0b462000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f8e0b462000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\37\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1840928, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e0c630000
mmap(NULL, 3949248, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8e0ae90000
mprotect(0x7f8e0b04b000, 2093056, PROT_NONE) = 0
mmap(0x7f8e0b24a000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ba000) = 0x7f8e0b24a000
mmap(0x7f8e0b250000, 17088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f8e0b250000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e0c620000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e0c610000
arch_prctl(ARCH_SET_FS, 0x7f8e0c610780) = 0
mprotect(0x7f8e0b24a000, 16384, PROT_READ) = 0
mprotect(0x7f8e0b462000, 4096, PROT_READ) = 0
mprotect(0x7f8e0b688000, 4096, PROT_READ) = 0
mprotect(0x7f8e0b994000, 4096, PROT_READ) = 0
mprotect(0x7f8e0bbb7000, 4096, PROT_READ) = 0
mprotect(0x7f8e0bdc0000, 4096, PROT_READ) = 0
mprotect(0x7f8e0bfd6000, 4096, PROT_READ) = 0
mprotect(0x7f8e0c1ec000, 4096, PROT_READ) = 0
mprotect(0x7f8e0c3fc000, 4096, PROT_READ) = 0
mprotect(0x66c000, 4096, PROT_READ)     = 0
mprotect(0x7f8e0c622000, 4096, PROT_READ) = 0
munmap(0x7f8e0c66b000, 18971)           = 0
set_tid_address(0x7f8e0c610a50)         = 291
set_robust_list(0x7f8e0c610a60, 24)     = 0
futex(0x7fffd2f09580, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, 7f8e0c610780) = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGRTMIN, {0x7f8e0b4769f0, [], SA_RESTORER|SA_SIGINFO, 0x7f8e0b480340}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7f8e0b476a80, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f8e0b480340}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=8192*1024}) = 0
brk(0)                                  = 0x1c7a000
brk(0x1c9b000)                          = 0x1c9b000
mmap(NULL, 104, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_ANONYMOUS, -1, 0) = 0x7f8e0c66f000
mmap(NULL, 104, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_ANONYMOUS, -1, 0) = 0x7f8e0c66e000
mmap(NULL, 64, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_ANONYMOUS, -1, 0) = 0x7f8e0c66d000
mmap(NULL, 8422404, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_ANONYMOUS, -1, 0) = 0x7f8e0a687000
mmap(NULL, 104, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_ANONYMOUS, -1, 0) = 0x7f8e0c66c000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2919792, ...}) = 0
mmap(NULL, 2919792, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f8e0a3be000
close(3)                                = 0
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2570, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e0c600000
read(3, "# Locale name alias data base.\n#"..., 4096) = 2570
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7f8e0c600000, 4096)            = 0
open("/usr/lib/locale/en_US/LC_NUMERIC", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/locale/en/LC_NUMERIC", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US/LC_NUMERIC", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en/LC_NUMERIC", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/proc/meminfo", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e0c600000
read(3, "MemTotal:      134138036 kB\nMemF"..., 1024) = 1024
close(3)                                = 0
munmap(0x7f8e0c600000, 4096)            = 0
time(NULL)                              = 1475036399
open("/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 3
read(3, "0-35\n", 8192)                 = 5
close(3)                                = 0
sched_getaffinity(291, 128, {fffffffff}) = 8
dup(2)                                  = 3
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fstat(3, {st_mode=S_IFCHR|0600, st_rdev=makedev(4, 1), ...}) = 0
ioctl(3, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e0c600000
lseek(3, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
write(3, "shmget: Function not implemented"..., 33shmget: Function not implemented
) = 33
close(3)                                = 0
munmap(0x7f8e0c600000, 4096)            = 0
write(2, "error: failed to setup shm segme"..., 35error: failed to setup shm segment
) = 35
clock_gettime(CLOCK_MONOTONIC, {879, 477808000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 478506000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 479251000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 479904000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 480632000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 481368000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 482154000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 482784000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 483487000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 484226000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 484848000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 486829000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 487521000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 488278000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 489036000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 489690000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 490398000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 491158000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 491788000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 492506000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 493229000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 493840000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 494508000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 496574000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 497353000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 498062000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 498717000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 499416000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 500122000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 500738000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 501437000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 502175000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 502770000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 503460000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 525683000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 527547000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 528371000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 529196000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 529838000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 530667000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 531408000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 532160000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 532775000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 533534000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 534295000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 548722000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 550591000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 551441000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 552287000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 553035000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 553719000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 554510000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 555273000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 555994000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 556666000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 557368000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 558101000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 558721000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 560506000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 561261000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 561907000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 562555000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 563270000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 563900000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 564571000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 565301000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 566249000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 566831000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 567494000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 568222000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 568819000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 570817000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 571517000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 572197000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 572792000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 573517000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 574337000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 575059000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 575714000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 576429000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 577174000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 577794000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 578465000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 579223000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 581265000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 581973000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 582600000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 583302000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 583996000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 584656000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 585347000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 586066000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 586703000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 587409000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 588145000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 588789000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 590673000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 591372000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 592144000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 592784000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 593470000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 594145000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 594795000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 595502000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 596259000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 597078000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 597722000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 598378000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 599134000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 601181000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 601782000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 602427000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 603150000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 603786000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 604500000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 605287000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 605995000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 606678000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 607377000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 608092000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 608703000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 610645000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 611345000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 612096000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 612724000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 613439000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 614204000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 614822000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 615475000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 616224000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 616819000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 617494000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 618258000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 618963000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 620968000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 621651000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 622385000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 623194000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 623852000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 624529000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 625244000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 625951000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 626656000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 627372000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 628396000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 629173000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 631204000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 631825000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 632490000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 633248000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 633843000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 634499000}) = 0
clock_gettime(CLOCK_MONOTONIC, {879, 635304000}) = 0
nanosleep({0, 1000}, NULL)              = 0
nanosleep({0, 1000}, NULL)              = 0
nanosleep({0, 1000}, NULL)              = 0
nanosleep({0, 1000}, NULL)              = 0
nanosleep({0, 1000}, NULL)              = 0
nanosleep({0, 1000}, NULL)              = 0
nanosleep({0, 1000}, NULL)              = 0
nanosleep({0, 1000}, NULL)              = 0
nanosleep({0, 1000}, NULL)              = 0
nanosleep({0, 1000}, NULL)              = 0
munmap(0x7f8e0a687000, 8422404)         = 0
munmap(0x7f8e0c66c000, 104)             = 0
munmap(0x7f8e0c66d000, 64)              = 0
munmap(0x7f8e0c66e000, 104)             = 0
munmap(0x7f8e0c66f000, 104)             = 0
exit_group(0)                           = ?
+++ exited with 0 +++
r
* Required packages and commands to install
fio

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment] 2016-09-28 09:12
Same as #1016 and #61.

**Comment by stehufntdev** [comment] 2016-09-28 15:52
Thanks for reporting the issue.  Agree with therealkenc that this is a duplicate of other posts so closing this out for now.  Please provide feedback on uservoice so we can prioritize - https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo.

**Closed by stehufntdev** 2016-09-28 15:52 UTC

**Comment by eyalroth** [comment] 2018-09-26 14:49
Note that you were using the flag `--ioengine=libaio`. You can omit the flag in which case the `sync` engine will come into play and the tool will work.

However, I would advice using this utility from a native command line so it will utilize the native Windows IO engine (`windowsaio`) and will give a much more accurate measurement. There are instructions on the [tool's Github page](https://github.com/axboe/fio) for how to compile `fio` to Windows using Cygwin, or otherwise download the binaries from https://bluestop.org/fio/.
