### ISSUE TITLE
Editing the .bashrc from windows will make it not visible on bash

### ISSUE THREAD

**Issue by yupal** [Microsoft/BashOnWindows#65] opened 2016-04-08 10:41 UTC
I edited the .bashrc file from APPDATA folder using Visual Studio Code, 
and after edit the file was not executed anymore, or visible in bash

**Comment by mphaney** [comment] 2016-04-08 15:10
This would seem to relate to the (now closed) issue #45.  Essentially, we shouldn't be editing the Linux files from the Windows side, as this can cause instability and some other scary words.  The reverse, however, (editing Windows files from the Linux side) works fantastic and is intended to do so.  Suggest closing this issue?

Props for using Visual Studio Code, though.  That thing rocks :-)

**Comment by yupal** [comment] 2016-04-08 15:24
For the moment it seems ok not to edit the linux files from windows, but as a person that hates vim I would like to have the posibility to edit the files in a win32 app or metro :P app.

Also this reminds me of another bug, in nano you can not scoll the document the texts overlaps.

**Comment by benhillis** [comment] 2016-05-28 17:05
Closing this out as a duplicate.

**Closed by benhillis** 2016-05-28 17:05 UTC
Labels: duplicate

**Comment by ButterHub** [comment] 2017-10-26 14:36
To fix this issue:
first on Windows: Copy the .bashrc into another folder. Delete the .bashrc file (or other files) in the initial directory.
Then in Bash: Type "vim .bashrc", and paste the text back in, using right click. (Make sure you are in the home folder, but typing "cd".)

In the long term, don't edit crucial linux files with Windows applications. 
https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/

**Comment by ZYinMD** [comment] 2018-07-17 16:43
After reading this issue, I realized that I have edited my .bashrc in Sublime Text many times, and have encountered no issues so far. Has this issue been improved recently? Just curious.

**Comment by Biswa96** [comment] 2018-07-17 17:24
@ZYinMD It is highly advisable not to modify any WSL files from Windows programs. Always make a backup the `.bashrc` file. Open the file in any Windows text editor you want, edit it. Now the file permission will be `000`. So change the file permission with `chmod 664 ~/.bashrc`. This is only for experimenting.

**Comment by ZYinMD** [comment] 2018-07-17 18:23
@Biswa96 Thanks! I took a look, and indeed the permission of my .bashrc has become 000. However, it's still working as intended, somehow it can still be read by linux on start up. Hmmm~
