### ISSUE TITLE
difficulties launching a Windows GUI file editor from a bash window

### ISSUE THREAD

**Issue by raymod2** [Microsoft/BashOnWindows#1919] opened 2017-04-14 19:59 UTC
I prefer to browse the file system from a bash window but edit files using a GUI editor.  Usually I create a script or alias so that I can type "vi foo.txt" and it will launch a gvim.exe window as a background process.  However, with Bash on Windows this is not trivial because Windows applications can't directly access the file system on Bash.  I came up with the script below that works fairly well but it relies on implementation details that might change.  There has to be a better way.  Maybe the path conversion could be done automatically when invoking a PE file from the bash command line?

<pre>
#!/bin/bash

ROOT=C:/Users/$USER/AppData/Local/lxss
FILE=$1

[[ $1 =~ ^/ ]] || FILE=$PWD/$FILE

if   [[ $FILE =~ ^/c/ ]];                        then FILE=${FILE#/c};
elif [[ $FILE =~ ^/mnt/c/ ]];                    then FILE=${FILE#/mnt/c};
elif [[ $FILE =~ ^/home/ || $FILE =~ ^/root/ ]]; then FILE=$ROOT$FILE;
else                                                  FILE=$ROOT/rootfs$FILE;
fi

if [ ! -e $1 ]; then touch $1 ; fi
gvim.exe $FILE 2>/dev/null &
</pre>

**Comment by raymod2** [comment] 2017-04-14 21:15
There's a bigger problem with the script above.  It works OK until you close the bash session and open a new one.  When you do that any files you edited that are not under /mnt/c will become invisible.  You won't see them in a 'ls' listing.  But if you try to recreate them you will get an error that the file already exists!  The only way to recover from this is to delete the file from outside of bash (ie. using Windows Explorer and navigating to "C:/Users/$USER/AppData/Local/lxss").

**Comment by benhillis** [comment] 2017-04-14 21:19
Closing this out as a duplicate of #51. Have a look at this [blog post](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/) that @bitcrazed wrote for more detail.

**Closed by benhillis** 2017-04-14 21:19 UTC
Labels: duplicate

**Comment by raymod2** [comment] 2017-04-20 16:43
FYI, I am now using the following script to launch the Windows version of gvim for files under /c and /mnt/c and the Linux version of gvim for all other files.  It's not ideal but it will do until interoperability between the Windows and Linux filesystems is improved.

```
#!/bin/bash

FILE=$1
LINUX_FS=0

[[ $FILE =~ ^/ ]] || FILE=$PWD/$FILE

if   [[ $FILE =~ ^/c/ ]];     then FILE=${FILE#/c};
elif [[ $FILE =~ ^/mnt/c/ ]]; then FILE=${FILE#/mnt/c};
else                          LINUX_FS=1;
fi

if [ $LINUX_FS -eq 0 ]; then
   gvim.exe "$FILE" 2>/dev/null &
else
   /usr/bin/gvim "$FILE" 2>/dev/null
fi
```

**Comment by rickywu** [comment] 2017-12-27 08:23
Just alias givm='/mnt/d/Program Files/Vim/vim80/gvim.exe'
gvim will open target file and conversion WSL path automatically
Of course you should operate files not in lxss root folder, correct way should be in /mnt/d/xxx etc.

**Comment by raymod2** [comment] 2017-12-28 00:22
@rickywu, That won't allow you to open files in the Linux filesystem (ie. in your home directory) using the Windows gvim.exe.  That's what my script above addresses.
