### ISSUE TITLE
Bash Error: 0x80070005

### ISSUE THREAD

**Issue by derekyu56** [Microsoft/BashOnWindows#1924] opened 2017-04-15 15:28 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
Trying to start bash and got Error: 0x80070005
* Expected results
Get the bash prompt and continue.
* Actual results (with terminal output if applicable)
Error: 0x80070005
Press any key to continue...
* Your Windows build number
Version 1703 (OS Build 15063.138)
* Steps / All commands required to reproduce the error from a brand new installation 

1. Install package required for yocto build:
sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib \
build-essential chrpath socat cpio python python3 python3-pip python3-pexpect libsdl1.2-dev xterm
2. Get Yocto project using "git clone git://git.yoctoproject.org/poky". Before it complete, hit control-C to stop it.
3. Close the power shell window.
4. Open a new power shell window and enter "bash", got error 0x8007005
5. Restart windows and try again, same error.
6. Attempted to delete files in %localappdata%\lxss in admin power shell failed.

There were issues like this reported, seem not for creator update. The way I see it means I cannot recover without uninstall bash. Not a preferred option.

Trace enclosed.
[lxcore.zip](https://github.com/Microsoft/BashOnWindows/files/923695/lxcore.zip)

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by derekyu56** [comment] 2017-04-15 15:37
In step 6, I meant files in %localappdata%\lxss\temp. I tried to delete them but failed.

**Comment by benhillis** [comment] 2017-04-15 17:25
Thanks for reporting. I have a repro of this locally and will debug this.

**Comment by benhillis** [comment] 2017-04-16 01:02
Marking as a duplicate of #651.

**Closed by benhillis** 2017-04-16 01:02 UTC
