### ISSUE TITLE
Bundler install memory error

### ISSUE THREAD

**Issue by LordPrettyFlacko** [Microsoft/BashOnWindows#965] opened 2016-08-22 19:34 UTC
When i install gems via bundler i get an "Cannot allocate memory" error. Specific one this time is the following: 
`/home/bee/.rvm/gems/ruby-2.2.4@gemset/gems/bundler-1.12.3/lib/bundler/source/git/git_proxy.rb:149:in``': Cannot allocate memory - git (Errno::ENOMEM)
`
Expected result is obviously that the gems get installed.

My windows build number is 14393.51

To reproduce you need to install rvm following the guide from the website and then install bundler via gem install bundler. After that install some gems from gemfile via "bundle install"

I already see that there are some other issues with the "allocate memory" error but they dont work for me. Maybe somebody knows what to do

**Comment by onomatopellan** [comment] 2016-08-23 07:14
Could you type `free` on bash and post what it shows?

**Comment by JasonLinMS** [comment] 2016-09-02 19:02
What is the size of your Windows pagefile? I had to increase mine to 2.5 GB to stop getting the "Cannot allocate memory" errors.

**Comment by bashcoder** [comment] 2016-10-02 14:16
I'm having the same issue. Here is the output of the `free` command on a fresh bash window:
```
             total       used       free     shared    buffers     cached
Mem:       3884696    2704944    1179752      17720      34032     188576
-/+ buffers/cache:    2482336    1402360
Swap:      1441792      96304    1345488
```

**Comment by bryceroney** [comment] 2016-10-04 04:49
I'm currently receiving this issue with 2999MB allocated as my swap.

The `free` command results in:
```
             total       used       free     shared    buffers     cached
Mem:       8312940    6149696    2163244      17720      34032     188576
-/+ buffers/cache:    5927088    2385852
Swap:      3014656     182680    2831976
```

**Comment by nulian** [comment] 2016-11-19 01:48
Awesome also put a fixed page file and it works fine now 👍

**Comment by benhillis** [comment] 2016-12-01 22:26
Marking this as a duplicate of #851 - see my comment about the incoming fix https://github.com/Microsoft/BashOnWindows/issues/851#issuecomment-264314420

**Closed by benhillis** 2016-12-01 22:26 UTC
Labels: duplicate, fixinbound, memory

**Comment by aurimus** [comment] 2017-03-22 09:06
Any way to fix this?

**Comment by aseering** [comment] 2017-03-22 13:08
Hi @aurimus -- @benhillis [claims](https://github.com/Microsoft/BashOnWindows/issues/851#issuecomment-264314420) that this is fixed in a recent [Insider build](https://insider.windows.com/).

**Comment by aurimus** [comment] 2017-03-23 21:17
Confirm, after windows update it worked!
