### ISSUE TITLE
[Console] totally discard all old buffer 

### ISSUE THREAD

**Issue by tg123** [Microsoft/BashOnWindows#1098] opened 2016-09-19 07:30 UTC
* A brief description
want to totally discard all old buffer 

* Expected results
no such feature, 

not `CTRL + L` or `clear`.

* Your Windows build number
Version 10.0.14393

**Comment by fpqc** [comment] 2016-09-20 02:42
Clear seems to work fine here.

**Comment by dmex** [comment] 2016-09-24 18:27
@fpqc 

The clear command only removes the last 15 lines from the console screen buffer?

You can reproduce this by running any command that will fill up the console with text (e.g. "strace ping"), once finished type "clear" then scroll up in the console and you'll see it only clears the last 15 lines... If you want to completely clear the screen buffer you have to either type clear several times or exit the console.

**Comment by zadjii-msft** [comment] 2016-10-18 22:40
So this is one difference that I never really pegged down. On ubuntu, you'll get a ^[[3J when you clear, which is also supposed to clear the scrollback, while on a WSL image I haven't ever gotten that. 

@tg123 you're correct, `clear`/`C-l` doesn't clear the scrollback (buffer). It only clears the viewport of the screen. We don't have current plans to add support for ^[[3J in the next Windows release, especially considering it's not used on WSL. Also, the concept of a "scrollback" doesn't exactly apply to the console, either.

This is a dupe of #1020, so I'm gonna close this issue as such.

**Closed by zadjii-msft** 2016-10-18 22:40 UTC
Labels: console, duplicate, feature
