### ISSUE TITLE
Is Bash on Windows included in the 32Bit version of Anniversary Edition,bcz can't find it.

### ISSUE THREAD

**Issue by gregorydillon** [Microsoft/BashOnWindows#775] opened 2016-08-05 04:19 UTC
I've installed Windows 10 Anniversary Edition on a 32 Bit system.   I've put it into developer mode.   And read the directions to change "Features" to include "Windows subsystem for Linux"  but that choice is not available.

Could you confirm if Bash on Windows is available for the 32 Bit version of Windows 10 Anniversary edition?   ( are the installation instructions the same??)

**Comment by aseering** [comment] 2016-08-05 04:22
Hi @gregorydillon -- thanks for your interest in WSL!  Unfortunately, WSL is 64-bit only.  See the first and third lines on the Prerequisites section of the official installation guide:

https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

**Comment by benhillis** [comment] 2016-08-05 15:09
Duplicate of #281

**Closed by benhillis** 2016-08-05 15:09 UTC
