### ISSUE TITLE
MS Linux Kernel no 32-bit ELF execution ability?

### ISSUE THREAD

**Issue by nobk** [Microsoft/BashOnWindows#1251] opened 2016-10-22 19:21 UTC
x86(intel 80386) ELF 32-bit executable file can not run on WSL, But many project mix 32-bit and 64-bit build tools.
Add: I find the vote link, who need 32-bit like me please [vote](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13377507-please-add-32-bit-elf-support-to-the-kernel).
```sh
$ cat t3264.c
#include <stdio.h>
int main(){printf("hello\n");return 0;}

$ gcc -o t64 t3264.c
$ gcc -m32 -o t32 t3264.c
$ ./t64
hello
$ ./t32
bash: ./t32: cannot execute binary file: Exec format error
$ file t64 t32
t64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=67876d323a7a3e28341172dc3ad049b092b8dab7, not stripped
t32: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=023227dbdab55645b16d65a2d48b3e687a2cb83d, not stripped
$ uname -a
Linux PC 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013 x86_64 x86_64 x86_64 GNU/Linux
$
```

**Comment by fpqc** [comment] 2016-10-22 20:00
[bydesign] please close and request on uservoice.

**Comment by benhillis** [comment] 2016-10-23 05:57
Duplicate of #390.

**Closed by benhillis** 2016-10-23 05:57 UTC
Labels: duplicate
