### ISSUE TITLE
Black Screen, and White boxes

### ISSUE THREAD

**Issue by LuchoFLA** [Microsoft/BashOnWindows#1158] opened 2016-10-04 00:19 UTC
![issue](https://cloud.githubusercontent.com/assets/22605199/19058557/9ef6041e-89ae-11e6-8a28-462237adea33.png)

Please Help Me 
Build 14936.rs_prerelease.160923-1700

Pentium Dual-Core E5300 2.60Ghz
Ram: 2Gb
Video Card: Intel G33/G31 Express Chipset Family

**Comment by misenesi** [comment] 2016-10-04 00:52
Hi @LuchoFLA.

thank you for reporting your issue. I am not sure what the question is. Could you provide repro steps and how does native Ubuntu behave for your given problem, possibly with strace output/differences?

**Comment by benhillis** [comment] 2016-10-04 00:53
This is a screenshot of the Windows setting dialog. This looks to be a UI bug in Windows - unrelated to WSL.

**Comment by onomatopellan** [comment] 2016-10-04 18:17
I have the same bug on my old Hp-Compaqdx2400. The problem happens on almost every intel GPUs without Directx10 hardware support out there.

In order to enable WSL you need to see Settings so you can go to Device Manager and update manually the video driver to **Microsoft Basic Display Adapter** (which is WDDM 1.3) and reboot. You should see Settings properly again but it will be slower as it's a software rendering video driver.

I suspect the problem is the Directx10->Directx9 conversion that happens when rendering XAML with WDDM1.0 on Windows10. On every affected PC with white boxes you can see on Resource Monitor that D3D10Level9.dll was loaded in memory.

I wish the UI or Direct3D team had a issues github as great and responsive as this one, bug probably would be fixed.

**Comment by benhillis** [comment] 2017-04-10 19:27
Closing as this is unrelated to WSL.

**Closed by benhillis** 2017-04-10 19:27 UTC
