### ISSUE TITLE
Queston: Is there's a way to take a snapshop of WSL?

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/BashOnWindows#2147] opened 2017-05-23 12:22 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16199.1000]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
N/A

* What's wrong / what should be happening instead:
Nothing wrong! But, I would love to find out if there's a way to take a snapshot of the current WSL instead to doing a clean install.  This way I could do some testing without rebuilding the whole environment.

Is this possible?

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment] 2017-05-23 15:09
No, not currently.  Marking as a duplicate of #284.

**Closed by benhillis** 2017-05-23 15:09 UTC
