### ISSUE TITLE
Running notepad.exe from bash on windows to open a file in Linux

### ISSUE THREAD

**Issue by vijayjt** [Microsoft/BashOnWindows#1913] opened 2017-04-14 10:36 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
From reading the blog post here https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/ 

I should be able to open a bash on windows shell, then run notepad.exe to open a file in Linux. Specifically the example in the post shows this:
```
vijay@DESKTOP:~$ echo hello > hello.txt
vijay@DESKTOP:~$ cat hello.txt
hello
vijay@DESKTOPI:~$ notepad.exe hello.txt
Unable to translate current working directory. Using C:\Users\vijay\Desktop
```
But after running notepad.exe it attempts to create a new file because it can't interpret the path to the file.

It's worth noting that I can open the file if I specify the actual Windows style path to the file e.g. 
```
notepad.exe C:\\Users\\vijay\\AppData\\Local\\lxss\\home\\vijay\\install_go.sh
```

This is okay as a workaround but pretty awkward to use and from the blog it seems it should be able to interpret/translate the path?

Here is the output from strace:
```
vijay@DESKTOP$ strace notepad.exe install_go.sh
execve("/mnt/c/Windows/System32/notepad.exe", ["notepad.exe", "install_go.sh"], [/* 16 vars */]) = 0
brk(NULL)                               = 0x7fffc9c24000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f39fb2a0000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=20096, ...}) = 0
mmap(NULL, 20096, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f39fb2a9000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1864888, ...}) = 0
mmap(NULL, 3967392, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f39fac30000
mprotect(0x7f39fadef000, 2097152, PROT_NONE) = 0
mmap(0x7f39fafef000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bf000) = 0x7f39fafef000
mmap(0x7f39faff5000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f39faff5000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f39fb290000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f39fb280000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f39fb270000
arch_prctl(ARCH_SET_FS, 0x7f39fb280700) = 0
mprotect(0x7f39fafef000, 16384, PROT_READ) = 0
mprotect(0x7f39fb609000, 4096, PROT_READ) = 0
mprotect(0x7f39fb225000, 4096, PROT_READ) = 0
munmap(0x7f39fb2a9000, 20096)           = 0
getpid()                                = 153
brk(NULL)                               = 0x7fffc9c24000
brk(0x7fffc9c45000)                     = 0x7fffc9c45000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2981280, ...}) = 0
mmap(NULL, 2981280, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f39fa958000
close(3)                                = 0
getcwd("/home/vijay", 4096)             = 12
open("/dev/lxssclient", O_RDWR)         = 3
ioctl(3, _IOC(0, 0x00, 0x2f, 0x22), 0x7fffd1b1ec40) = 0
open("/mnt/c/Windows/System32/notepad.exe", O_RDONLY) = 5
ioctl(3, _IOC(0, 0x00, 0x3f, 0x22), 0x7fffd1b1eaf0) = 0
close(5)                                = 0
open("/home/vijay", O_RDONLY)           = 5
ioctl(3, _IOC(0, 0x00, 0x3f, 0x22), 0x7fffd1b1eaf0) = -1 EINVAL (Invalid argument)
close(5)                                = 0
ioctl(4, _IOC(0, 0x00, 0x97, 0x22), 0x7fffd1b1eb98) = 0
ioctl(4, _IOC(0, 0x00, 0xb7, 0x22), 0x7fffd1b1eb90) = 0
ioctl(4, _IOC(0, 0x00, 0xb7, 0x22), 0x7fffd1b1eb90) = 0
ioctl(4, _IOC(0, 0x00, 0xb7, 0x22), 0x7fffd1b1eb90) = 0
write(4, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\36\0\0\0\0\0\0\0"..., 163) = 163
read(4, Unable to translate current working directory. Using C:\Users\vijay\Desktop
"\0\0\0\0\0\0\0\0\25\0\0\0\0\0\0\0", 16) = 16
ioctl(4, _IOC(0, 0x00, 0x9b, 0x22), 0x7fffd1b1ec38) = 0
write(4, "\0\0\0\0\0\0\0\0\25\0\0\0\0\0\0\0", 16) = 16
ioctl(5, _IOC(0, 0x00, 0xbf, 0x22)
, 0x7fffd1b1ec30) = 0
close(3)                                = 0
close(4)                                = 0
close(5)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

I am on on Ubuntu version details below:
```
vijay@DESKTOP$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

Not I did an in place upgrade to 16.04, so not sure if this could be related (I didn't want to have to reinstall packages and go through the back/restore configs process).

* Expected results

Assuming the blog post is correct and didn't omit the actual steps/experience, I should just be able to open the file without specifying the Windows style path.

* Actual results (with terminal output if applicable)

```
vijay@DESKTOPI:~$ notepad.exe hello.txt
Unable to translate current working directory. Using C:\Users\vijay\Desktop
```

* Your Windows build number

Microsoft Windows [Version 10.0.15063]

* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment] 2017-04-14 15:16
Closing this out as a duplicate of #51. Have a look at this [blog post](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/) that @bitcrazed wrote for more detail.

**Closed by benhillis** 2017-04-14 15:16 UTC
