### ISSUE TITLE
The ifconfig command do not work 

### ISSUE THREAD

**Issue by thinksource** [Microsoft/BashOnWindows#1036] opened 2016-09-02 05:26 UTC
* A brief description
the ifconfig tools can not work 
* Expected results
ens33: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 64.137.193.119  netmask 255.255.255.0  broadcast 64.137.193.255
        inet6 fe80::250:56ff:fea4:7df1  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:a4:7d:f1  txqueuelen 1000  (Ethernet)
        RX packets 195  bytes 21613 (21.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 124  bytes 19197 (18.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
* Actual results (with terminal output if applicable)
cas@LAPTOP-51VR10QS:~$ sudo ifconfig
[sudo] password for cas:
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.

* Your Windows build number
version 1607
os build 14393.105
* Steps / commands required to reproduce the error
 sudo ifconfig
* Strace of the failing command
cas@LAPTOP-51VR10QS:~$ strace sudo ifconfig
execve("/usr/bin/sudo", ["sudo", "ifconfig"], [/* 15 vars */]) = -1 EPERM (Operation not permitted)
write(2, "strace: exec: Operation not perm"..., 38strace: exec: Operation not permitted
) = 38
exit_group(1)                           = ?
+++ exited with 1 +++
* Required packages and commands to install
net-tools
See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by iz0eyj** [comment] 2016-09-02 05:41
@thinksource look @ https://github.com/Microsoft/BashOnWindows/issues/908

**Comment by stehufntdev** [comment] 2016-09-02 16:43
Thanks for reporting the issue.  This is a known issue that we are tracking.  Closing this out as a duplicate of #908 so we can track it in one place.

**Closed by stehufntdev** 2016-09-02 16:43 UTC
