### ISSUE TITLE
eventfd(0, EFD_SEMAPHORE) issues an "Invalid argument" error

### ISSUE THREAD

**Issue by vladon** [Microsoft/BashOnWindows#1654] opened 2017-02-01 15:50 UTC
`eventfd(0, EFD_SEMAPHORE)` returns `EINVAL`

Windows build 15007

**Comment by stehufntdev** [comment] 2017-02-01 15:52
Thanks for reporting the issue.  EFD_SEMAPHORE was added recently and should be out in an insider build soon.  Closing this out as a duplicate of #452 so we can track the progress in one thread.

**Closed by stehufntdev** 2017-02-01 15:52 UTC
