### ISSUE TITLE
docker installation fails E: Can not write log(Is /dev/pts mounted?)

### ISSUE THREAD

**Issue by uadev** [Microsoft/BashOnWindows#85] opened 2016-04-08 22:41 UTC
``` sh
root@localhost:/mnt/c/apps/cmder# apt-get install docker
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  docker
0 upgraded, 1 newly installed, 0 to remove and 10 not upgraded.
Need to get 0 B/12.2 kB of archives.
After this operation, 65.5 kB of additional disk space will be used.
E: Can not write log (Is /dev/pts mounted?) - openpty (2: No such file or directory)
Selecting previously unselected package docker.
(Reading database ... 24948 files and directories currently installed.)
Preparing to unpack .../docker_1.5-1_amd64.deb ...
Unpacking docker (1.5-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up docker (1.5-1) ...
root@localhost:/mnt/c/apps/cmder# docker
The program 'docker' is currently not installed. You can install it by typing:
apt-get install docker
root@localhost:/mnt/c/apps/cmder#
```

**Comment by mphaney** [comment] 2016-04-08 23:05
Seems to be related to #80.  I'm not convinced that the log error is causing docker to fail to install (but what do I know, I'm just some random guy on the Internet), but it nevertheless isn't working, just as you say.

**Comment by russalex** [comment] 2016-04-09 00:42
The logs error is known and is a [red herring](https://en.wikipedia.org/wiki/Red_herring), sorry.  Docker does not run on WSL at this time.  it is something on our radar but not something we want to talk about quite yet.  That said, if someone wants to play with Docker here's what they will see:

1) Docker install instructions are [here](https://docs.docker.com/engine/installation/linux/ubuntulinux/).  Follow the instructions for Trusty 14.04 (LTS)
2) Starting the Docker service gives the following error (you also see this error on the apt-get install docker-engine when it tries to start the service):
> $ sudo service docker start
> initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: No such fi
> le or directory
>  * Starting Docker: docker                                                                 [ OK ]
> 

While it says the Docker service is started, don't be fooled:
> $ sudo docker run hello-world
> docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
> See 'docker run --help'.
>

**Comment by uadev** [comment] 2016-04-09 09:38
@russalex You've managed to run `upstart` somehow? Is there an instruction for this?

**Comment by mjoppich** [comment] 2016-04-11 16:23
@russalex it'd be interesting to see how you overcame upstart ...

**Comment by russalex** [comment] 2016-04-12 23:18
Hate to say it, but I did nothing special for upstart.  Before running this test I uninstalled using lxrun /uninstall, then did my usual round of apt-get installs for update, upgrade, build-essential, git and ruby.  After that I just followed the instructions on the [webpage](https://docs.docker.com/engine/installation/linux/ubuntulinux/).  What I believe you're seeing is an error that was a result of #143.

Running docker with the apt-get fixes on that thread it looks like:

```
russ@RUSSALEX-DESK:~$ sudo service docker start
 * Starting Docker: docker                                                         [ OK ]
russ@RUSSALEX-DESK:~$ sudo docker run hello-world
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.
```

**Comment by mjoppich** [comment] 2016-04-13 06:45
Thanks for the heads up.

Even though the service seems to start at my end, something else must be broken, as not even

`root@localhost:~# docker -D info
^Croot@localhost:~# docker --help
^Croot@localhost:~#`

info or help are displayed. I guess this got to do with docker itself which requires Kernel 3.10+. Is there any chance we get a more recent kernel for WSL?

Coming from computer science, I really think the ability to run docker containers and any other linux tools could really boost bioinformatics, where there are also a lot of non-computer-affine people :)

**Comment by tkelman** [comment] 2016-04-13 07:42
WSL isn't a Linux kernel, it's an emulation layer. Though good question what kernel ABI version is being targeted. Presumably things may need to be updated a bit when the Ubuntu version gets `dist-upgrade`d from 14.04 to 16.04.

**Comment by tacnoman** [comment] 2016-04-25 17:11
Someone made the Docker work?

**Comment by russalex** [comment] 2016-05-16 16:48
The docker engine is not a supported scenario in the short term.  I would suggest hitting our [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash) page and upvoting Docker if you're looking to run the docker engine.

The docker client however should be running in build 14342. I have been able to run the docker client and connect to a docker engine running in a VM.

**Comment by yarmand** [comment] 2016-05-29 17:53
To help future work, here is my investigation.
I installed latest docker-engine following instruction at:
https://docs.docker.com/engine/installation/linux/ubuntulinux/

issues:
- The doc specify a kernel version 3.10 minimum when lxss is 3.0.4+
- when daemon is starting it fails with error:
```
FATA[0000] can't create unix socket /var/run/docker.sock: listen unix /var/run/docker.sock: setsockopt: invalid argument
```

The strace reveal invalid argument on setsockopt:
```
sudo strace docker daemon
...
setsockopt(4, SOL_SOCKET, SO_BROADCAST, [1], 4) = -1 EINVAL (Invalid argument)
close(4)
...
```

value 1 as Boolean flag seems fine for SO_BROADCAST when looking at `man 7 socket`

**Comment by davetropeano** [comment] 2016-07-21 12:12
@russalex - we can't upvote Docker on UserVoice.. it is locked :(

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13250370-docker

**Comment by aseering** [comment] 2016-07-21 14:24
For what it's worth:  A big piece of docker-engine actually lives inside the kernel itself.  That's why it keeps requiring newer kernels.  (The docker-engine process doesn't actually do a whole lot itself when running a container; its job is to tell the kernel what to do, the kernel does the real work.)

WSL a clean-room kernel reimplementation.  So it can't, for both technical and legal reasons, simply take  the kernel components of Docker and "make it work".  They would need to reverse-engineer years of ongoing kernel development and reimplement it.  (Or take some other nontrivial approach.)

If I were a WSL dev (which I'm not), I would totally enjoy that project.  But it would take me a huge amount of time, time that could be spent building many other big features.

**Comment by benhillis** [comment] 2016-07-21 15:25
@aseering Great explanation. Without making any promises I can say that we know docker is an important and powerful too and definitely something we're looking into.

**Comment by krisbulman** [comment] 2016-08-03 00:03
I can confirm the issue from May posted by @yarmand is still the same as it is today. 

```bash
$ docker -D info

Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

```bash
$ sudo docker daemon

can't create unix socket /var/run/docker.sock: listen unix /var/run/docker.sock: setsockopt: invalid argument
```

```bash
$ sudo strace docker daemon

setsockopt(4, SOL_SOCKET, SO_BROADCAST, [1], 4) = -1 EINVAL (Invalid argument)
close(4)                                = 0
```

**Comment by bbarker** [comment] 2016-08-11 19:17
It seems like (1) supporting windows server containers in Windows 10 and (2) [using Windows Docker from Windows Bash](http://serverfault.com/questions/767994/can-you-run-docker-natively-on-the-new-windows-10-ubuntu-bash-userspace) (already working) would be acceptable.

**Comment by yarmand** [comment] 2016-08-11 21:41
@bbarker  I do not understand the benefit you are describing. Being able to run docker client inside WSL in order to run a windows app as a container looks a bit overcomplicated to me.
The point we try to make here is being able to run Linux containers without the need of a VM.

It also seems the first error we are blocking on here, is a better support for sockets into WSL, which will be a good thing to have anyway.

**Comment by bbarker** [comment] 2016-08-11 21:52
@yarmand I agree for not needing a VM - this is why I said support *windows server containers*, which I believe does not require Hyper-V ([source](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/about/about_overview)). As for being complicated, it really wasn't - I got it up and running in a matter of minutes. Of course, in my case, I was using Hyper-V as I'm on Windows 10.

I'm all for better Linux kernel emulation, just saying this might be an easier route. I'd like to have real containers on Windows 10 instead of using Hyper-V, though I realize that is an "upstream" concern.

**Comment by fpqc** [comment] 2016-08-27 06:17
@aseering Does docker use anything in the kernel other than cgroups, namespaces, and chroot?  If those are all that are being used, doesn't docker support come practically for free from support for chroot and systemd?

**Comment by aseering** [comment] 2016-08-27 17:49
@fpqc -- I don't know the full list offhand, but I know it also does a bunch of stuff with the kernel network layer.  It creates virtual network devices (related to tap/tun devices, I think?, which [as you've said](https://github.com/Microsoft/BashOnWindows/issues/874#issuecomment-242864515) are very low priority right now).  It creates a virtual network bridge (same syscalls as `brctl`, as far as I know).  It uses `iptables` for routing network traffic between containers.

WSL's socket implementation is in general not robust enough yet.  It can run over TCP today; but even in that scenario, which is in theory supported, Docker puts a fair bit of stress on the socket, especially when building new containers (it has a client/server model so sends all filesystem data over the network) and there are still bugs/deadlocks in WSL's socket implementation ( #30 #575 ) that cause it to intermittently hang.  And, of course, it prefers and defaults to AF_UNIX, which still needs more functionality as you mentioned.

It also does bind-mounts of both directories and files, I believe.  Bind-mounts ought to be easy to implement, I think?  But I don't think they work yet.

WSL would have to implement the requirements for at least one of the storage backends -- one of  AUFS, OverlayFS, BtrFS's snapshotting capabilities, or the whole DeviceMapper subsystem plus loopback devices and `mount` support for ext4, etc.  I think there is a backend that mostly works on just a regular filesystem, but I believe it's firmly labeled as not for production use / mostly just for debugging Docker -- Docker uses copy-on-write semantics extensively; emulating that is expensive and a pain to get right.

Also, there's "supports cgroups and namespaces" and then there's "supports cgroups and namespaces" :-)  My understanding, which may be incorrect, is that systemd only really requires pretty basic support for both, at least to get it minimally working.  Enumerating the available cgroups, setting some values, etc.  Docker uses both cgroups and namespaces extensively; I would be surprised if it worked properly without relatively complete support for the network namespace; I don't know offhand about other namespaces.  Docker uses cgroups to impose various restrictions on the processes within a container; I don't have a clear picture in my head of exactly how it uses cgroups, but my guess is that basic containers would mostly work with stubbed-out support there, but they would be somewhat flaky and wouldn't support a bunch of Docker's resource-limiting features without more complete support.


You're right that Docker doesn't require specific kernel patches.  For perspective, though:  In the US at least, Red Hat Enterprise Linux is the most popular enterprise Linux solution.  And RHEL 6 (or its free counterpart CentOS 6) is the most common version in existing deployments.  So there's a huge market pressure to support RHEL 6 -- lots of big companies would be willing to pay someone to make it work.  Docker never supported RHEL 6.4 or older because its kernel simply lacked necessary functionality.  They worked with Red Hat to backport some network-namespace-related stuff from newer kernels into the CentOS 6.5 and 6.6 kernels, but that effort proved to be buggy and insufficient so they have since dropped support for RHEL 6 entirely.  (Though Red Hat will happily sell you Docker support and extra features on RHEL 7 :-) )  Docker doesn't require patches because they're working with, and extending, features that are baked into the core kernel.  As I recall, networking was an issue at one point, as was capping physical memory (Linux has supported virtual-memory caps for a long time but I believe physical-memory caps are more recent).  Other things too, I'm sure.  These days, I think it's filesystem stuff; their [OverlayFS doc](https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/) hints a little bit about the kinds of new kernel functionality that they're using.  WSL is keeping the Windows kernel team busy, but the Linux kernel team is busy too :-)

**Comment by fpqc** [comment] 2016-08-27 21:12
@aseering I have to admit, I wouldn't be very surprised if MS decides to wait until something like Redstone 3 or Redstone 4, after Server 2016 and Windows containers come out, if only because container-mania, if it continues that long, will make it so MS's customers will demand the ability to run both Windows and Linux workloads on a single kernel without any further virtualization.

The difference between RHEL6/CentOS6 is that Windows Server 2016 will not be just LTS.  RHEL6 and CentOS6 are using basically an LTS kernel forked from the mainline kernel all the way back in 2009, with only security updates backported, which means no cgroups whatsoever.  That's like asking MS to backport Windows Containers back to Windows Server 2008R2.  Docker doesn't support kernels that are older probably than cgroupsv2.  If it supported cgroupsv1 (not sure how old Docker is), compatibility was dropped because cgroupsv1 was deemed unstable and was removed from the Kernel.

But yeah, the thing you said about the level of cgroups support necessary for docker, as well as docker taking over Linux's network configuration, means that Docker would be hard to support (based on my reading of its Kernel Option requirements listed on the Gentoo wiki).  Thanks for your long and detailed answer though.

**Comment by fpqc** [comment] 2016-08-28 02:13
@aseering True, but I suspect that since MS has cgroups-like functionality inside of the NT kernel as part of the Windows containers project, they might be able to write a thin layer to implement cgroups, rather than having to emulate everything.

**Comment by aseering** [comment] 2016-08-28 02:23
@fpqc -- ah, good point.

**Comment by bluefoxicy** [comment] 2016-12-12 17:54
@russalex The [Docker suggestion](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13250370-docker) was closed, as noted prior.

Users here are asking for Docker to work inside a WSL container, such that a Docker container runs its cgroups in that WSL container's context and thus runs a Docker container inside WSL.  Microsoft's response has apparently been to comment that they don't want to do that.

I don't care how it's done; from my standpoint as a user, it's not complete and correct until copying the same files and running a `docker-compose up -d` works as expected.  If you have to do special things to make Docker run a container, then Docker doesn't work.

**Comment by fpqc** [comment] 2016-12-12 18:06
@bluefoxicy You heard incorrectly. Docker engine does not work and will not work for the foreseeable future (and nobody has claimed it will work).  We're much more likely to see rkt working first (should come for free if systemd-nspawn will eventually work).

Docker engine requires a huge number of special kernel options enabled, as well as installation of AUFS, which is an out-of-tree kernel module.  Microsoft may eventually decide for enterprise reasons to work extremely hard to get docker engine running in WSL, but it is not a current goal.

**Comment by bluefoxicy** [comment] 2016-12-12 22:29
@fpqc nothing you said contradicts anything I said.

**Comment by fpqc** [comment] 2016-12-12 22:53
@bluefoxicy I dunno then. You are sitting here dictating to the devs what you would need in order to consider a feature that is expressly not being worked on finished.  I won't consider OS X emulation complete until my laptop has a touch bar, lol.  

If they do decide that they want to support Docker engine, I am sure they will do a good job.  It's just not all high on their priorities.

**Comment by itopiacloud** [comment] 2017-02-07 16:12
I'm running Docker for Windows 1.13.0 and WSL - having installed docker into WSL (and having all the fail-whale drama), I *can* however, run "docker -H localhost:2375 run hello-world" and send other commands from WSL into windows native. Cool. What *would* be useful here, would be able to edit the DOCKER_OPTS (https://docs.docker.com/engine/admin/), set the daemon to point to the Windows version and then start-up. Surely not too much to ask!

**Comment by aseering** [comment] 2017-02-07 22:00
Hi @itopiacloud -- unfortunately, `DOCKER_OPTS` is not respected by the Docker client.  That decision is under the control of the Docker project; you might consider bringing it up on [their forums](https://forums.docker.com/).

What you could do, though, would be something like `$ alias docker='docker -H localhost:2375'`.  That wouldn't help inside shell scripts, but it would help at the command line.  Or you could write a wrapper script that does the same thing and add it to the front of `$PATH`.  More work, and it still wouldn't be perfect, but it would work in most cases.

**Comment by alexlopes** [comment] 2017-03-25 14:34
I found a workaroud [here](https://forums.docker.com/t/docker-for-windows-and-windows-subsystem-for-linux/12854/11) but you need docker for windows running

**Comment by itopiacloud** [comment] 2017-03-27 09:44
@alexlopes Hah - I've commented much the same on that thread too..

**Comment by bkr32** [comment] 2017-05-24 18:01
i keep running into this issue `unknown filesystem type 'cgroup'`
when trying to start the docker service, can anyone point out a workaround?

**Comment by evertramos** [comment] 2017-05-28 19:28
I am getting this error on stating `docker`:

```
root@home:/# service docker start
mount: unknown filesystem type 'cgroup'
 * Starting Docker: docker                                                                                    [ OK ]
root@home:/# docker run hello-world
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
root@home:/#
```

So, there is some problem with `cgroup` file system:

```
mount: unknown filesystem type 'cgroup'
```

**Comment by fpqc** [comment] 2017-05-28 21:53
yeah, cgroups aren't implemented to my knowledge.

**Comment by benhillis** [comment] 2017-08-18 19:44
Closing this out because as of Creator's Update, docker installs successfully.  There are various other issues tracking docker and docker daemon functionality.

**Closed by benhillis** 2017-08-18 19:44 UTC
Labels: feature

**Comment by tnguyen14** [comment] 2017-08-18 20:11
Is the Creator's Update GA?

**Comment by benhillis** [comment] 2017-08-18 20:18
@tnguyen14 - Yes, it was released a few months ago:
https://support.microsoft.com/en-us/help/4028685/windows-get-the-windows-10-creators-update

**Comment by itaysk** [comment] 2017-08-18 21:28
@benhillis  wait, so we can run linux docker containers on wsl now?

**Comment by benhillis** [comment] 2017-08-18 22:29
@itaysk - This issue is specifically about docker not installing, which as been fixed.  There are other issues tracking various docker pieces not working.

**Comment by 4mitch** [comment] 2017-08-27 12:13
It seems now we should trace for following issue #2291

**Comment by tangyouwo** [comment] 2017-12-08 02:28
@benhillis now i tried install docker-ce according to the official website documentation。
https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-from-a-package
but run : docker run hello-world 
it still : docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.

**Comment by benhillis** [comment] 2017-12-08 03:03
Can you try manually launching the docker daemon before running this command?

**Comment by tangyouwo** [comment] 2017-12-08 03:09
@benhillis  yeah
i tried to run      service docker start  ,
and it output:  * Starting Docker: docker                                                                                       [ OK ]
but run  ps , no ouput any docker's  process

**Comment by fruch** [comment] 2017-12-08 03:50
dockerd can run on WSL yes, if you'll try running dockerd you'll see the errors.

there are multiple things missing from the kernel in WSL, cgroups is one of them.

I think it would be a killer feature for WSL. but sound like it conflicts with Microsoft selling windows docker support as part of windows 10 pro.

It's it a bit sad that I need to assume such thing.

Can someone from Microsoft end please say it bit more clearly ? what is the direction here ? lots of threads I've seen here around this specific issue.

And I believe it's more then technical question.

Don't get me wrong, Microsoft are entitled to this money, this task of getting docker to work natively is far from being easy nor cheap.

**Comment by fpqc** [comment] 2017-12-09 20:19
@fruch cgroups are a feature of the memory manager, and in Linux non-server systems, they are almost entirely used by Systemd.  By the way, Windows containers are not available in Win10 Pro.  Hyper-V containers are, and the reason why they are restricted to Win10Pro is because Hyper-V is only available on Win10 Pro.

**Comment by fruch** [comment] 2017-12-09 20:49
@fpqc thanks,  I actually meant hyper-v (I don't have much need yet for windows containers), and I don't really care much how it works under the hood (A big fat lie..) as long it's working fast and reliable, and have the same features as docker on linux system. and I want for free... (could be nice if it would be free, but 99$ extra for win10pro sounds reasonable enough for me, as long it's working from WSL)

**Comment by Paul-Pushkarov** [comment] 2018-04-02 21:58
This is what I get trying to start `dockerd` manually:

```
:/mnt/c/www$ sudo dockerd
WARN[2018-04-02T14:46:43.056552600-07:00] Could not set daemon root propagation to shared, this is not generally critical but may cause some functionality to not work or fallback to less desirable behavior  dir=/var/lib/docker error="invalid argument"
INFO[2018-04-02T14:46:43.091924600-07:00] libcontainerd: started new docker-containerd process  pid=9993
INFO[0000] starting containerd                           module=containerd revision=cfd04396dc68220d1cecbe686a6cc3aa5ce3667c version=v1.0.2
INFO[0000] loading plugin "io.containerd.content.v1.content"...  module=containerd type=io.containerd.content.v1
INFO[0000] loading plugin "io.containerd.snapshotter.v1.btrfs"...  module=containerd type=io.containerd.snapshotter.v1
WARN[0000] failed to load plugin io.containerd.snapshotter.v1.btrfs  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module=containerd
INFO[0000] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  module=containerd type=io.containerd.snapshotter.v1
INFO[0000] loading plugin "io.containerd.metadata.v1.bolt"...  module=containerd type=io.containerd.metadata.v1
WARN[0000] could not use snapshotter btrfs in metadata plugin  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module="containerd/io.containerd.metadata.v1.bolt"
INFO[0000] loading plugin "io.containerd.differ.v1.walking"...  module=containerd type=io.containerd.differ.v1
INFO[0000] loading plugin "io.containerd.gc.v1.scheduler"...  module=containerd type=io.containerd.gc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.containers"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.content"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.diff"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.events"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.healthcheck"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.images"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.leases"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.namespaces"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.snapshots"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.monitor.v1.cgroups"...  module=containerd type=io.containerd.monitor.v1
INFO[0000] loading plugin "io.containerd.runtime.v1.linux"...  module=containerd type=io.containerd.runtime.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.tasks"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.version"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.introspection"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] serving...                                    address="/var/run/docker/containerd/docker-containerd-debug.sock" module="containerd/debug"
INFO[0000] serving...                                    address="/var/run/docker/containerd/docker-containerd.sock" module="containerd/grpc"
INFO[0000] containerd successfully booted in 0.095300s   module=containerd
INFO[2018-04-02T14:46:43.410322300-07:00] Graph migration to content-addressability took 0.00 seconds
WARN[2018-04-02T14:46:43.410986500-07:00] Your kernel does not support cgroup memory limit
WARN[2018-04-02T14:46:43.411430700-07:00] Unable to find cpu cgroup in mounts
WARN[2018-04-02T14:46:43.433371200-07:00] Unable to find blkio cgroup in mounts
WARN[2018-04-02T14:46:43.433807500-07:00] Unable to find cpuset cgroup in mounts
WARN[2018-04-02T14:46:43.435181100-07:00] mountpoint for pids not found
Error starting daemon: Devices cgroup isn't mounted
```

**Comment by fpqc** [comment] 2018-04-03 01:06
No cgroups support right now. I wonder what would happen if it were for all intents and purposes stubbed out.

**Comment by therealkenc** [comment] 2018-04-03 01:54
>  I wonder what would happen if it were for all intents and purposes stubbed out.

I say go full Law of WSL Github and ask [for this](https://linuxcontainers.org/lxcfs/introduction/).

**Comment by onomatopellan** [comment] 2018-04-25 09:04
Dunno if it has been stubbed out but in build 17134 this is what a [working dockerd](https://github.com/Microsoft/WSL/issues/2291#issuecomment-383698720) inside WSL shows at launch:

> ~$ sudo dockerd
WARN[2018-04-25T10:48:24.718002800+02:00] Could not set daemon root propagation to shared, this is not generally critical but may cause some functionality to not work or fallback to less desirable behavior  dir=/var/lib/docker error="invalid argument"
INFO[2018-04-25T10:48:24.744789300+02:00] libcontainerd: started new docker-containerd process  pid=24
INFO[0000] starting containerd                           module=containerd revision=cfd04396dc68220d1cecbe686a6cc3aa5ce3667c version=v1.0.2
INFO[0000] loading plugin "io.containerd.content.v1.content"...  module=containerd type=io.containerd.content.v1
INFO[0000] loading plugin "io.containerd.snapshotter.v1.btrfs"...  module=containerd type=io.containerd.snapshotter.v1
WARN[0000] failed to load plugin io.containerd.snapshotter.v1.btrfs  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module=containerd
INFO[0000] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  module=containerd type=io.containerd.snapshotter.v1
INFO[0000] loading plugin "io.containerd.metadata.v1.bolt"...  module=containerd type=io.containerd.metadata.v1
WARN[0000] could not use snapshotter btrfs in metadata plugin  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module="containerd/io.containerd.metadata.v1.bolt"
INFO[0000] loading plugin "io.containerd.differ.v1.walking"...  module=containerd type=io.containerd.differ.v1
INFO[0000] loading plugin "io.containerd.gc.v1.scheduler"...  module=containerd type=io.containerd.gc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.containers"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.content"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.diff"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.events"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.healthcheck"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.images"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.leases"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.namespaces"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.snapshots"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.monitor.v1.cgroups"...  module=containerd type=io.containerd.monitor.v1
INFO[0000] loading plugin "io.containerd.runtime.v1.linux"...  module=containerd type=io.containerd.runtime.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.tasks"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.version"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.introspection"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] serving...                                    address="/var/run/docker/containerd/docker-containerd-debug.sock" module="containerd/debug"
INFO[0000] serving...                                    address="/var/run/docker/containerd/docker-containerd.sock" module="containerd/grpc"
INFO[0000] containerd successfully booted in 0.038597s   module=containerd
INFO[2018-04-25T10:48:24.858531900+02:00] [graphdriver] using prior storage driver: overlay2
INFO[2018-04-25T10:48:24.886666900+02:00] Graph migration to content-addressability took 0.00 seconds
WARN[2018-04-25T10:48:24.887427000+02:00] Your kernel does not support cgroup memory limit
WARN[2018-04-25T10:48:24.887707200+02:00] Unable to find cpu cgroup in mounts
WARN[2018-04-25T10:48:24.888396600+02:00] Unable to find blkio cgroup in mounts
WARN[2018-04-25T10:48:24.889953100+02:00] Unable to find cpuset cgroup in mounts
WARN[2018-04-25T10:48:24.890864000+02:00] mountpoint for pids not found
INFO[2018-04-25T10:48:24.895964100+02:00] Loading containers: start.
WARN[2018-04-25T10:48:24.906860200+02:00] Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: WARNING: Module nf_nat not found in directory /lib/modules/4.4.0-17134-Microsoft`, error: exit status 1
WARN[2018-04-25T10:48:24.921238800+02:00] Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: WARNING: Module xt_conntrack not found in directory /lib/modules/4.4.0-17134-Microsoft`, error: exit status 1
WARN[2018-04-25T10:48:25.254382100+02:00] Could not load necessary modules for IPSEC rules: Running modprobe xfrm_user failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: WARNING: Module xfrm_user not found in directory /lib/modules/4.4.0-17134-Microsoft`, error: exit status 1
WARN[2018-04-25T10:48:25.266617700+02:00] Could not load necessary modules for Conntrack: Running modprobe nf_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: WARNING: Module nf_conntrack not found in directory /lib/modules/4.4.0-17134-Microsoft`, error: exit status 1
INFO[2018-04-25T10:48:30.240060700+02:00] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address
INFO[2018-04-25T10:48:30.744728800+02:00] Loading containers: done.
INFO[2018-04-25T10:48:30.805650100+02:00] Docker daemon                                 commit=fcdc984cfd graphdriver(s)=overlay2 version=dev
INFO[2018-04-25T10:48:30.810311200+02:00] Daemon has completed initialization
INFO[2018-04-25T10:48:30.837209000+02:00] API listen on /var/run/docker.sock
