### ISSUE TITLE
Bash BSOD When Installing Elasticsearch Plugins

### ISSUE THREAD

**Issue by adeeb1** [Microsoft/BashOnWindows#554] opened 2016-06-18 19:26 UTC
OS: Windows 10 Pro Insider Preview (Build 14367)
Hardware: Dell Inspiron 14R N4110

I am setting up a Ruby on Rails development environment, and I got pretty far along the way. While setting up the Marvel plugin for Elasticsearch 1.5.2, I received a BSOD. The BSOD occurred right after I ran the following command:

`bin/plugin --install elasticsearch/elasticsearch-lang-mvel/1.5.0 `

After restarting, Bash on Ubuntu won't load, and my Wi-Fi drivers don't seem to be working either. When I try to launch Bash on Ubuntu, the CLI window appears for half a second and then disappears. I've tried reinstalling it via the "Turn Windows features on or off" screen, but that didn't work.

Great work on Ubuntu on Bash so far! I'm really looking forward to having it replace my VM.

**Comment by benhillis** [comment] 2016-06-20 15:27
I'm getting 404 when I try to access your above dump (tried both .txt and .dmp).  Could you please upload the dump somewhere and send email to: InsiderSupport@microsoft.com with a link? Include in the subject / message to forward to the WSL team. In the body of the email mention it is for benhill.

Thanks for proactively trying to share the dump!  But for future reference, it's generally not a good idea to share full memory dumps on public forums, they can contain personal information (since it is the full virtual memory context your system).

**Comment by adeeb1** [comment] 2016-06-20 16:39
Thank you for the information! I will email it out later when I have access to that machine!

**Comment by adeeb1** [comment] 2016-06-21 01:10
@benhillis Just sent out an email!

**Comment by adeeb1** [comment] 2016-06-21 02:43
I'm leaving a quick note that I was able to reproduce the issue a second time by running the same exact command. This time, I had Oracle Java 8 installed, but apparently it doesn't matter.

**Comment by benhillis** [comment] 2016-06-21 16:43
Thank you, I received your dump and confirmed that this is the same bugcheck that was fixed recently.  The fix will be in an upcoming Windows Insider build.

**Comment by adeeb1** [comment] 2016-07-10 17:17
I tested today on build 14385, and this issue is fixed. Thank you very much!! I think we can close this issue.

**Comment by benhillis** [comment] 2016-07-10 20:29
Thanks for confirming!

**Closed by benhillis** 2016-07-10 20:29 UTC
Labels: bug, fixed
