### ISSUE TITLE
Some control keys not working

### ISSUE THREAD

**Issue by landtuna** [Microsoft/BashOnWindows#943] opened 2016-08-19 18:44 UTC
* A brief description

Some control keys aren't working for me in Bash on Windows, which prevents me from using emacs.

* Expected results

$ showkey -a
(hit control-spacebar)
^@        0 0000 0x00
(hit control-/)
^_       31 0037 0x1f

* Actual results (with terminal output if applicable)

$ showkey -a
(hit control-spacebar)
(no response)
(hit control-/)
(no response)

* Your Windows build number

14393.51

**Comment by zadjii-msft** [comment] 2016-10-04 22:27
This is actually a dupe of another issue, maybe #583? Probably many more going back a while.

It looks like there are some recent changes in kernel-land that actually re-enable C-Spc, C-@, C-a, etc, so shout out to bperkins for that fix!

**Closed by zadjii-msft** 2016-10-04 22:27 UTC
Labels: console
