### ISSUE TITLE
Installation path windows subsystem

### ISSUE THREAD

**Issue by jharry78** [Microsoft/BashOnWindows#1270] opened 2016-10-25 11:56 UTC
I want to install the linux subsystem on my D hard drive but the default location is on C hard drive how to change the path of the installation ?

**Comment by fpqc** [comment] 2016-10-25 18:08
I think someone was able to use NTFS Junction points.

**Comment by rodrymbo** [comment] 2016-10-26 19:53
That would be something new. Junction points (NTFS symlinks) haven't worked that I know of. I haven't seen it in a [recent release note](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes?f=255&MSPPError=-2147217396), and I believe it is a request in the UserVoice area. 

If I'm wrong, please let me know how to do it!

**Comment by russalex** [comment] 2016-10-26 23:53
Thanks for the feedback.  The ability to install to a different drive is something we're asked for quite a bit and is on our backlog.  You can upvote the User Voice [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13364193-alternate-install-location-option-would-be-nice).

**Comment by benhillis** [comment] 2016-10-27 15:20
Closing as duplicate of #449

**Closed by benhillis** 2016-10-27 15:20 UTC
Labels: duplicate, feature
