### ISSUE TITLE
Files suddenly disappear from Bash but are still present on the file system

### ISSUE THREAD

**Issue by laurent22** [Microsoft/BashOnWindows#942] opened 2016-08-19 18:19 UTC
It looks like sometime files are being made invisible and inaccessible to WSL. I had some text files that I've edited in a text editor, I made some changes, they were still there, I made more changes, still there, and after a while they suddenly vanish from WSL, even though they are still in the file system.

See below:

If I look in **cmd.exe**, all the files are there:

	Laurent@ROG C:\Users\Laurent\AppData\Local\lxss\home\laurent
	> dir
	 Le volume dans le lecteur C s’appelle Windows
	 Le numéro de série du volume est E042-22E9

	 Répertoire de C:\Users\Laurent\AppData\Local\lxss\home\laurent

	19/08/2016  19:05    <DIR>          .
	19/08/2016  19:05    <DIR>          ..
	12/08/2016  21:45             3 671 .bashrc
	19/08/2016  19:04             1 546 .bash_history
	12/08/2016  21:40               220 .bash_logout
	12/08/2016  21:42    <DIR>          .config
	12/08/2016  21:42                33 .gitconfig
	12/08/2016  21:42                29 .grcat
	12/08/2016  22:55                20 .inputrc
	13/08/2016  11:43                47 .lesshst
	12/08/2016  21:42                30 .my.cnf
	12/08/2016  21:40               675 .profile
	13/08/2016  12:00    <DIR>          .rsync_tmbackup
	12/08/2016  21:42                27 .vim
	19/08/2016  18:50             4 004 .viminfo
	12/08/2016  21:42                24 .vimrc
	12/08/2016  22:04             2 083 backup_excluded_patterns.txt
	13/08/2016  11:51             1 231 backup_excluded_patterns_Donnees.txt
	12/08/2016  22:04               372 backup_excluded_patterns_etc.txt
	12/08/2016  22:04                64 backup_excluded_patterns_var.txt
	12/08/2016  22:04             1 321 backup_excluded_patterns_WindowsUsers.txt
	12/08/2016  22:09                11 Docs
	12/08/2016  21:41    <DIR>          dotfiles
	19/08/2016  19:04             4 919 timebackup.sh
	12/08/2016  22:09             4 869 timebackup.sh.BAK
	              20 fichier(s)           25 196 octets
	               5 Rép(s)  25 375 801 344 octets libres

From **Bash** however, 3 files are missing, specifically "backup_excluded_patterns_Donnees.txt", "timebackup.sh" and "timebackup.sh.BAK".

	laurent@ROG:~$ ls -la
	total 36
	drwxr-xr-x 2 laurent laurent    0 Aug 19 19:05 .
	drwxr-xr-x 2 root    root       0 Jan  1  1970 ..
	-rw------- 1 laurent laurent 1546 Aug 19 19:04 .bash_history
	-rw-r--r-- 1 laurent laurent  220 Aug 12 21:40 .bash_logout
	-rw-r--r-- 1 laurent laurent 3671 Aug 12 21:45 .bashrc
	drwxrwxrwx 2 laurent laurent    0 Aug 12 21:42 .config
	lrwxrwxrwx 1 laurent laurent   33 Aug 12 21:42 .gitconfig -> /home/laurent/dotfiles/.gitconfig
	lrwxrwxrwx 1 laurent laurent   29 Aug 12 21:42 .grcat -> /home/laurent/dotfiles/.grcat
	-rw-rw-rw- 1 laurent laurent   20 Aug 12 22:55 .inputrc
	-rw------- 1 laurent laurent   47 Aug 13 11:43 .lesshst
	lrwxrwxrwx 1 laurent laurent   30 Aug 12 21:42 .my.cnf -> /home/laurent/dotfiles/.my.cnf
	-rw-r--r-- 1 laurent laurent  675 Aug 12 21:40 .profile
	drwxrwxrwx 2 laurent laurent    0 Aug 13 12:00 .rsync_tmbackup
	lrwxrwxrwx 1 laurent laurent   27 Aug 12 21:42 .vim -> /home/laurent/dotfiles/.vim
	-rw------- 1 laurent laurent 4004 Aug 19 18:50 .viminfo
	lrwxrwxrwx 1 laurent laurent   24 Aug 12 21:42 .vimrc -> /home/laurent/.vim/vimrc
	lrwxrwxrwx 1 laurent laurent   11 Aug 12 22:09 Docs -> /mnt/d/Docs
	-rw-rw-rw- 1 laurent laurent 2083 Aug 12 22:04 backup_excluded_patterns.txt
	-rw-rw-rw- 1 laurent laurent 1321 Aug 12 22:04 backup_excluded_patterns_WindowsUsers.txt
	-rw-rw-rw- 1 laurent laurent  372 Aug 12 22:04 backup_excluded_patterns_etc.txt
	-rw-rw-rw- 1 laurent laurent   64 Aug 12 22:04 backup_excluded_patterns_var.txt
	drwxrwxrwx 2 laurent laurent    0 Aug 12 21:41 dotfiles

These files are definitely still there and accessible from Windows and **cmd.exe** in particular:

	Laurent@ROG C:\Users\Laurent\AppData\Local\lxss\home\laurent
	> dir timebackup.sh
	 Le volume dans le lecteur C s’appelle Windows
	 Le numéro de série du volume est E042-22E9

	 Répertoire de C:\Users\Laurent\AppData\Local\lxss\home\laurent

	19/08/2016  19:04             4 919 timebackup.sh
	               1 fichier(s)            4 919 octets
	               0 Rép(s)  25 375 801 344 octets libres

But are inaccessible from **Bash**:

	laurent@ROG:~$ ll timebackup.sh
	ls: cannot access timebackup.sh: No such file or directory

Any idea what could cause this issue and how to fix it?

* Your Windows build number

Microsoft Windows [version 10.0.14393]

* Steps / commands required to reproduce the error

I cannot replicate this in a consistent way, but it seems to mostly happen to files that I edit in an external (Windows GUI) editor. After a while the file vanish from Bash.

**Comment by fpqc** [comment] 2016-08-19 18:26
Don't edit files inside the hidden lxss folder.  It is hidden for a reason, namely that editing anything inside of it (without being very very careful and using special tools that are aware of the NTFS extended attributes) will cause it to disappear.  Read the blogpost on VolFS vs DriveFS for more details.

**Comment by rodrymbo** [comment] 2016-08-19 21:16
There are other workarounds. For example, if you [start sshd](http://wsl-forum.qztc.io/viewtopic.php?f=6&t=10&p=54#p54), you could use an editor that knows about both sftp and unix line endings to edit a text file on VolFS. Since it is being saved by a linux process (using your linux credentials) the EAs will be created properly. Plus you'll be viewing the file quite legally through sftp instead of using a part of your profile Microsoft doesn't (yet) support  you going to with Explorer.

**Comment by benhillis** [comment] 2016-09-12 15:26
Duplicate of #659

**Closed by benhillis** 2016-09-12 15:26 UTC
