### ISSUE TITLE
GPG smart card not working

### ISSUE THREAD

**Issue by XIAZY** [Microsoft/BashOnWindows#1521] opened 2016-12-19 22:19 UTC
GPG not working when using smart card.
```
gpg: apdu_open_reader: failed to open driver `libpcsclite.so.1': libpcsclite.so.1: cannot open shared object file: No such file or directory
gpg: card reader not available
gpg: OpenPGP card not available: general error
```

Expected to fetch information from smart card.

Tested on Microsoft Windows [Version 10.0.14393]

Steps to reproduce:
```
gpg --card-status
```

**Comment by sunilmut** [comment] 2016-12-19 23:13
@XIAZY - Thanks for using WSL and the feedback. Unfortunately, hardware devices such as USB card reader, GPU etc. not yet exposed and supported by WSL. For example, see the user voice post for supporting [USB drives](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13717092-mount-usb-sd-removable-storage-devices) and [this](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/16108045-opencl-cuda-gpu-support) one for GPU. If you would like to see better support for smart card reader, we would recommend opening up a new user voice post for that (if there is not one already). We definitely look at our user voice page for prioritizing feature implementation.

**Comment by XIAZY** [comment] 2016-12-20 06:11
Thank you. I just voted to libusb and smart card support. Shall I leave this issue open?


2016年12月19日 -0500 PM6:13 Sunil Muthuswamy <notifications@github.com>，写道：

@XIAZY<https://github.com/XIAZY> - Thanks for using WSL and the feedback. Unfortunately, hardware devices such as USB card reader, GPU etc. not yet exposed and supported by WSL. For example, see the user voice post for supporting USB drives<https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13717092-mount-usb-sd-removable-storage-devices> and this<https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/16108045-opencl-cuda-gpu-support> one for GPU. If you would like to see better support for smart card reader, we would recommend opening up a new user voice post for that (if there is not one already). We definitely look at our user voice page for prioritizing feature implementation.

**Comment by sunilmut** [comment] 2016-12-20 06:53
Thanks! Yes, feel free to leave this open. I have already marked it with the "feature" tag.

**Comment by sunilmut** [comment] 2016-12-20 06:56
Thanks. I am marking this duplicate of #412 and closing it out. Let me know if that does not cover the use case here and I am happy to reopen this one.

**Closed by sunilmut** 2016-12-20 06:56 UTC
Labels: feature

**Comment by mdddev** [comment] 2019-05-10 18:37
Will WSL2 be the remedy?

**Comment by AquilaFasciata** [comment] 2020-07-12 03:21
@mdddev Considering it has access to system calls, I'm inclined to say yes, but I am only updating now.
