### ISSUE TITLE
Why is the bash virtualized with hypervisor?

### ISSUE THREAD

**Issue by cia48621793** [Microsoft/BashOnWindows#1256] opened 2016-10-23 01:03 UTC
```
C:\Windows\system32>bash
root@DESKTOP-3E3UEAT:/mnt/c/Windows/System32# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      :         <REDACTED>
stepping        : 9
microcode       : 0xffffffff
cpu MHz         : 3300.000
cache size      : 256 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm pni pclmulqdq est tm2 ssse3 cx16 xtpr sse4_1 sse4_2 popcnt xsave osxsave avx f16c hypervisor
bogomips        : 6600.00
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      :         <REDACTED>
stepping        : 9
microcode       : 0xffffffff
cpu MHz         : 3300.000
cache size      : 256 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm pni pclmulqdq est tm2 ssse3 cx16 xtpr sse4_1 sse4_2 popcnt xsave osxsave avx f16c hypervisor
bogomips        : 6600.00
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      :         <REDACTED>
stepping        : 9
microcode       : 0xffffffff
cpu MHz         : 3300.000
cache size      : 256 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm pni pclmulqdq est tm2 ssse3 cx16 xtpr sse4_1 sse4_2 popcnt xsave osxsave avx f16c hypervisor
bogomips        : 6600.00
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      :         <REDACTED>
stepping        : 9
microcode       : 0xffffffff
cpu MHz         : 3300.000
cache size      : 256 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm pni pclmulqdq est tm2 ssse3 cx16 xtpr sse4_1 sse4_2 popcnt xsave osxsave avx f16c hypervisor
bogomips        : 6600.00
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
```

I want to run KVM but there were neither vmx nor svm flag. Security measure to disable virtualization? Still Hyper-V is available in my PC but not an option for me.

**Comment by cia48621793** [comment] 2016-10-23 01:05
```
root@DESKTOP-3E3UEAT:/mnt/c/Windows/System32# kvm-ok
INFO: Your CPU does not support KVM extensions
KVM acceleration can NOT be used
```

**Comment by fpqc** [comment] 2016-10-23 03:04
Hyper-v takes over VT-X if you have hyper-v installed.  Windows 10 will run in the root partition bc Hyper-v is actually a bare-metal hypervisor.

**Comment by stehufntdev** [comment] 2016-10-26 16:33
Hypervisors (e.g. KVM, virtualbox, ...) are not supported in WSL.  Closing this out as a duplicate of #733 since it is a similar request.

**Closed by stehufntdev** 2016-10-26 16:33 UTC
