### ISSUE TITLE
Bash on Ubuntu on Windows is an ungoogleable name

### ISSUE THREAD

**Issue by thmcmahon** [Microsoft/BashOnWindows#490] opened 2016-06-08 22:04 UTC
This is not really a technical issue, but it does lead to a lot of technical issues. It's impossible to search the internet for issues that are specific to `Bash on Ubuntu on Windows`, you inevitably get results that are about a combination of those terms that are not relevant.

If this project were called something specific and new, then it would be a lot easier to get technical support.

I understand it's probably too late to change this, but I think that it's a serious problem with the project.

**Comment by benhillis** [comment] 2016-06-08 22:09
Maybe the results are better on Bing :)

**Comment by russalex** [comment] 2016-06-08 22:39
Completely agree.  I generally do my searches on "Windows Subsystem for Linux" or add "WSL" as a search keyword.  It's not 100%, but it does help some.

**Comment by fpqc** [comment] 2016-06-09 13:08
It's probably mercy that people don't find this github immediately, since all things considered, it isn't getting crapflooded like some of the bugtrackers I use (we get thousands of duplicate reports a month).

**Comment by thmcmahon** [comment] 2016-06-09 13:17
@fpqc to be clear, I don't mean this finding this github repo, I mean finding solutions to technical problems associated with Bash on Ubuntu on Windows is difficult because the name is not unique.

**Comment by fpqc** [comment] 2016-06-09 16:12
thmcmahon, that's because Bash on Ubuntu on Windows isn't the actual name.  

The actual name is Windows Subsystem for Linux (WSL) or probably lxss (short for linux subsystem).

**Comment by dreyks** [comment] 2016-06-09 21:18
bash.exe will lead you to cygwin and mingw

**Comment by zerocool4u2** [comment] 2016-06-16 21:29
a space to form a community and gain traction is need it in my opinion, i agree that is really hard to find specific information right now, most of useful things i found are comments in some random repository :/, i wanna share some wsl specific stuffs that i been working on, but i don't think that would be appropriated to just submit an issue and ask for the discussion label, any plans on something like this? i know there is uservoice, the opinion center(don't know is the right translation) and the comments sections in blogs and stuff, but, and hoping not to sound like asshole, they kinda suck.
This as a communication tool is awesome, your response is been incredible and the community is also there, but is really limited to the issue topic, i would love to have this community in something like http://askubuntu.com/ and to be established before where this gets to public release and millions start to use it, askubuntuonwindows.com kappa :P regards!
PD: Thanks for all the work on this, is already a big part of my life and my everyday work, and with every release is getting more awesome, .

**Comment by aseering** [comment] 2016-06-17 14:15
There are Microsoft forums as well.  But my experience posting there are that they have the wrong audience; they don't know how to help.

WSL folks -- do y'all have plans to start a user forum prior to your big Anniversary release, so that there's a place for what I would anticipate to be an influx of new users, both less-experienced end users and devs trying to support the new environment, to talk?

**Comment by axfelix** [comment] 2016-06-24 01:02
Yes please. I'm having a frustrating time with Linux these days (too many teleconf apps I need for work that I need to run in Wine or a VM) and am on the verge of switching back to Windows but I'm deeply hesitant to do so if it makes searching StackOverflow and Github issue trackers like this one more difficult for what I assume will be an initially small user base. I want this to work but I'm very leery of the UTF-8 bugs I'm reading about, the inability to install Xenial, etc...

**Comment by Manouchehri** [comment] 2016-06-30 06:29
I really hope the official launch only brands as "Windows Subsystem for Linux" and drop all this "Bash on Ubuntu on Windows" stuff. It's a nightmare trying to Google results.

**Comment by fpqc** [comment] 2016-06-30 09:39
@axfelix Actually I haven't seen any UTF8 bugs in WSL itself.  There are tons and tons and tons of problems with conhost (Windows Console Host) and the bash.exe Windows Console wrapper, but running things through Xming and a Unicode-compatible X-based terminal emulator has totally fixed those UTF8 problems.  It also happens to be the case that if you want to do any serious work in WSL terminals (not just using it for executing automation), you will want to use a proper X terminal emulator (rxvt-unicode) is confirmed working and properly functional if you start the daemon urxvtd as "urxvtd -f" and run the client urxvtc separately.

Also, xilun has a very nice project called cbwin up on github https://github.com/xilun/cbwin that allows calling and execution of Windows executables from the Linux side.  He also said that he is planning to add some kind of session-based functionality that will make it compatible with terminal emulators running through X (right now, it only works directly in the Windows console, which is still crippled, as noted above).

**Comment by axfelix** [comment] 2016-06-30 15:17
That's encouraging!

I suppose for now I could probably just maintain a separate msysgit-in-ConEmu shell as I used to alongside the Ubuntu shell, and use the former for stuff that can be installed via chocolatey and the latter for things that require building or obscure linux executables for which there isn't likely to be a Windows equivalent (unlike ffmpeg/wget/etc. which are all reasonably well maintained in choco these days). Still, that's a bit hackier than I'd like. Thanks!

**Comment by SungamR** [comment] 2016-07-04 14:39
I hope that WSL will stick. It doesn't clash with any big existing software project so its good for search.
Its on [Wikipedia](https://en.wikipedia.org/wiki/WSL) already also so :+1:

**Comment by pnegry** [comment] 2016-08-03 22:18
'Bash on Ubuntu on Windows' is a terrible name. It looks ugly, and it's a misnomer.

**Comment by aseering** [comment] 2016-08-03 22:49
"WSL" seems to be catching on; at least I tend to find decent search results if I use it in a search.

**Comment by fpqc** [comment] 2016-08-03 23:36
The official blog calls it WSL

**Comment by EricGT** [comment] 2016-08-08 13:26
Back to the original question of how to Google for Bash on Ubuntu on Windows.

I find using these two keywords together works. **wsl** **linux**

**Comment by airstrike** [comment] 2016-08-29 16:50
too bad WSL also stands for World Surf League..

**Comment by dreyks** [comment] 2016-08-29 21:00
@airstrike yeah, constantly bumping into threads that discuss [backdoors](http://www.surfing-waves.com/surf_talk.htm#B) in WSL...

**Comment by ericblade** [comment] 2016-08-29 21:57
Agree, also. At least some kind of unique code name that can be associated. WSL isn't particularly unique, Windows Subsystem Linux isn't particularly unique, Bash Windows Linux Ubuntu are definitely not unique...

**Comment by DraTeots** [comment] 2016-08-29 22:33
Even if WSL does catch on, it is still doesn't help searching much. Searching something with unique name is SO much easier. Compare with Ubuntu by itself, bash, mandriva, OxyPlot, etc.

**Comment by fpqc** [comment] 2016-08-29 23:40
Since the original project for android was called project  Astoria, maybe we should call it project Listeria XD

**Comment by benhillis** [comment] 2017-05-20 16:26
"Windows Subsystem for Linux" is the preferred nomenclature, dude.  Closing this out since this discussion has run its course.

**Closed by benhillis** 2017-05-20 16:26 UTC
Labels: discussion
