### ISSUE TITLE
Composer fails to install or update packages after upgrading to Ubuntu 17.04

### ISSUE THREAD

**Issue by LordMonoxide** [Microsoft/BashOnWindows#2369] opened 2017-07-25 18:20 UTC
* **Your Windows build number:**
16241

* **Ubuntu version:**
17.04

* **What you're doing and what's happening:**
  * Execute `composer install`
  * `composer` begins downloading packages, extracting them to the vendor directory, etc.
  * Every time it finishes installing a package, **it deletes the vendor directory entirely**.  I initially thought `composer` might be symlinking the directory, or something like that, but if I `cd` into the directory while it's still installing a package, wait for it to move on to the next package, and execute `realpath .`, it tells me the directory doesn't exist

* **What's wrong / what should be happening instead:**
  * Execute `composer install`
  * `composer` begins downloading packages, extracting them to the vendor directory, etc.
  * `composer` finishes installing packages, generates the classmap, and the vendor directory contains all necessary vendor code and autoload files

* **Strace of the failing command, if applicable:**
Please note I have filtered out all calls to `gettimeofday` as they add over 540mb to the file size.  They appear to be used solely for timing.  I can upload the full (548mb) file upon request.  [strace_no_gettimeofday.txt](https://github.com/Microsoft/BashOnWindows/files/1174350/strace_no_gettimeofday.txt)

* **Additional notes**
  * It worked before upgrading to 17.04
  * It still works when used under `/mnt/c/`

**Comment by therealkenc** [comment] 2017-07-26 00:01
It commits suicide for some reason (`grep` on `unlink`). Can't tell you why, mind. But as far as the _symptom_ goes, WSL is just doing what it is told.

[Appreciate the filter on `gettimeofday()` BTW. It's a personal pet peeve. I don't honestly know why coders find it necessary to check how far the earth has rotated all the time.]

**Comment by LordMonoxide** [comment] 2017-07-26 02:21
The most interesting part to me is that it works properly when run against clones in `/mnt/c/`, just not in the "normal" WSL filesystem.

A few clarifications:
I just took a look at the unlink calls, and they appear to be expected behaviour (eg. the cache file `vendor/mobiledetect/mobiledetectlib/927015e04880ec1a7f0c31ae6a9ff476`).  The problems appears to me to be that the **entire** `vendor` directory is getting deleted after each package is installed, not just the `vendor/<vendor>/<package>/<hash>` file nested within.

**Comment by therealkenc** [comment] 2017-07-26 03:23
> The problems appears to me to be that the entire vendor directory is getting deleted

You're right. I looked at those `unlink()`s too casually. One thing; there's a lot of `clone()` calls in there but it looks (at a glance) like we're only getting one thread in the `strace`. If that's the case do a `strace -ff composer install 2> composer.strace`. Maybe the kids are misbehaved.

**Comment by LordMonoxide** [comment] 2017-07-26 15:09
Here's an `strace` showing all forks...  You'll notice that there **are** `unlink` calls for the vendor directory.

[strace_no_gettimeofday2.zip](https://github.com/Microsoft/BashOnWindows/files/1177013/strace_no_gettimeofday2.zip)

Let me know if there's any more information you need.

**Comment by benhillis** [comment] 2017-08-01 19:36
I'm not able to reproduce this.  After upgrading to 17.04 composer install is working just fine for me.  Is there anything other steps I need to do?

1. Upgrade to 17.04
2. sudo apt install composer
3. Created a simple composer.json file 
4. Ran composer install in my home directory
5. Command succeeded and vendor directory was not deleted.

![composer](https://user-images.githubusercontent.com/17727402/28843257-59249ab4-76b5-11e7-8ac4-7cdce5b01bb1.png)

I'm running a very recent internal build so it's possible that I have fixes that have not yet made the Insider branch.  @LordMonoxide - keep an eye out for new Insider builds, I suspect an upcoming one will fix the issue you are seeing.

**Comment by LordMonoxide** [comment] 2017-08-01 19:47
@benhillis Cool, I'll check back in when the next build drops :)

**Comment by LordMonoxide** [comment] 2017-08-22 15:12
@benhillis Sorry about the slow reply.  I finally had a chance to test this on build 16257, and all is well.

**Comment by benhillis** [comment] 2017-08-22 15:20
@LordMonoxide - Not a problem at all, thanks for looping back to verify.  I'll go ahead and close this out, thanks again.

**Closed by benhillis** 2017-08-22 15:20 UTC
