### ISSUE TITLE
Emacs crashes session if run early

### ISSUE THREAD

**Issue by rgardler** [Microsoft/BashOnWindows#127] opened 2016-04-11 09:12 UTC
More often than not emacs crashes the session if it is started quickly. However, waiting a minute or so and then starting emacs seems to work consistently (at least in my small number of tests so far).

**Comment by benhillis** [comment] 2016-05-23 21:30
@rgardler Are you still experiencing this issue?  Also to clarify what do you mean by session?  NT Session or WSL Session?

**Comment by benhillis** [comment] 2016-06-01 18:05
Closing this out since I have been unable to reproduce this.  Please let us know if you are continuing to see this issue in newer Windows Insider Fast Ring builds.

**Closed by benhillis** 2016-06-01 18:05 UTC
Labels: need-repro
