### ISSUE TITLE
WSL hangs while trying to move folder/file inside /mnt/c folder

### ISSUE THREAD

**Issue by manubalasree** [Microsoft/BashOnWindows#885] opened 2016-08-13 11:39 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues:

WSL hangs while trying to move folder/file inside /mnt/c folder

folder move does not work and i have to do a restart of Windows to get back  the bash prompt

* Actual results (with terminal output if applicable)

Build: 14393.0

* Steps / commands required to reproduce the error

    cd to /mnt/users/* and try to mv a folder

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by iz0eyj** [comment] 2016-08-13 18:13
@manubalasree My Xfce personal folders are mapped on my user Win side and I can move, edit, delete etc etc everything.

**Comment by rodrymbo** [comment] 2016-08-14 17:42
Maybe that should be `/mnt/c/Users/` ? 

There are folders and files there that no one has permission to move; and there are files that cannot be moved while Windows is running. Also, that's where WSL/Bash hides its files, and it probably doesn't want them moved while it is running (and won't work if they are moved while it is not running).  So while `mv` should report an error instead of locking up, it's not surprising that it can't move that entire directory tree.

**Comment by benhillis** [comment] 2016-08-15 15:13
This looks like a duplicate of #671.

**Closed** 2016-08-16 15:22 UTC
Labels: duplicate
