### ISSUE TITLE
Ionic Framework can't get IPv4 address

### ISSUE THREAD

**Issue by jamespacileo** [Microsoft/BashOnWindows#1316] opened 2016-11-03 19:04 UTC
Ionic serves a web app via the command `ionic serve`

instead the following error is returned:

    Error getting IPv4 address: Error: ENOTSUP: operation not supported on socket, uv_interface_addresses (CLI v2.1.4)

BUILD 14955.1000

Bash was uninstalled and reinstalled after updating to this build.

_____

To reproduce the problem do the following:

- `npm install -g cordova ionic`

- [Create a starter app](http://ionicframework.com/docs/v2/getting-started/tutorial/) create a folder and use `ionic start TestApp tutorial --v2`

- within the created folder run `npm install` to make sure that all dependencies are installed

- within the folder run `ionic serve`

**Comment by benhillis** [comment] 2016-11-03 21:03
Closing as a duplicate of #468.

**Closed by benhillis** 2016-11-03 21:03 UTC
Labels: duplicate
