### ISSUE TITLE
PowerShell for Linux doesn't work well with the VT100 emulation of Console Host.

### ISSUE THREAD

**Issue by segin** [Microsoft/BashOnWindows#933] opened 2016-08-18 20:28 UTC
- A brief description

Typing in commands, running them, error prompts, etc, basically any interaction causes the console output to be scrambled.
- Expected results

As shown in this xterm window running in WSL and using VcXsrv as the X server:
![image](https://cloud.githubusercontent.com/assets/480709/17789548/4cf2a9e4-6558-11e6-87e6-aa56d362178f.png)
- Actual results (with terminal output if applicable)

![image](https://cloud.githubusercontent.com/assets/480709/17789354/86b5f786-6557-11e6-850c-25b4baaac699.png)
- Your Windows build number

Build 14393.67
- Steps / commands required to reproduce the error
1. Download and install PowerShell for Linux under WSL using the .deb package provided on the [PowerShell GitHub page](https://github.com/PowerShell/PowerShell)
2. Try to use PowerShell within the WSL environment using the Console Host as the terminal emulator (i.e. by simply using the console window provided by bash.exe/conhost.exe) 
- Strace of the failing command

_Not provided as it's likely not useful or relevant_
- Required packages and commands to install

[Listed here](https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#ubuntu-1404)

**Comment by bitcrazed** [comment] 2016-08-18 21:23
Thanks for reporting. I eagerly installed & started PowerShell on Bash/WSL this morning but found much the same as you report. We'll dig into this and figure out what's what.

**Comment by segin** [comment] 2016-08-19 04:21
There's several workarounds I can recommend to users that wish to use PowerShell under WSL: 

1. Use a terminal multiplexing program like `tmux` or `screen`
2. Use an X-based terminal emulator. Install `xterm` via `sudo apt install xterm`, install VcXsrv from https://sourceforge.net/projects/vcxsrv/files/vcxsrv/1.18.3.0/vcxsrv-64.1.18.3.0.installer.exe/download, and run `xterm` as `xterm -display localhost:0`. 
3. Use an SSH server (`sudo apt-get openssh-server ; sudo /etc/init.d/ssh start`) and connect to localhost via PuTTY or BitVise. 

And as I've been a bit aggressive with @bitcrazed on Twitter about, perhaps instead of trying to emulate an existing $TERM type, perhaps it's a better idea to create a termcap and/or terminfo entry for ConHost, although that would require the cooperation of the team that's working on the Console Host, and thus possibly not feasible, but it would fix some things in the short term.

**Comment by gaelcolas** [comment] 2016-08-24 14:10
I had the same problem, and found an MSDN article that shows how to use Tmux:
https://blogs.msdn.microsoft.com/commandline/2016/06/08/tmux-support-arrives-for-bash-on-ubuntu-on-windows/
In short: Start bash, then execute tmux, then finally start powershell.
![powershell_on_ubuntu_on_windows](https://cloud.githubusercontent.com/assets/8962101/17933664/dc79596a-6a0c-11e6-8065-788bb9336e8c.gif)

**Comment by zadjii-msft** [comment] 2016-08-24 21:59
I'm gonna personally recommend segin's first option, using powershell within tmux on conhost seems to fix it. I'm trying to understand why exactly that is - there doesn't seem to be anything that's wrong in our  (conhost.exe's) handling of the escape sequences powershell is sending us, but they do seem to be sending us sequences that cause the strangeness, and only without tmux as a wrapper. So I'll dig around in their code and see if I can't figure it out.

**Comment by segin** [comment] 2016-08-24 22:23
@zadjii-msft - It's because 'tmux' is itself a terminal emulator. Thus, it's interpreting the escape sequences from programs attached to it's own sub-terminals, processing them internally, and then creating a brand new set of escape sequences to pass to the real terminal to display the internal representation. 

In this case, you could think of it as a translating proxy :)

**Comment by MaximoTrinidad** [comment] 2016-10-02 15:32
Hum! So, we have a workaround using xterm. But I haven't seen any mention of this been worked on since August 24th.  I seen strong benefit in having WSL Bash working with PowerShell Open Source.  

Any idea if this is going to be corrected? 

Thx

**Comment by MaximoTrinidad** [comment] 2016-10-03 02:41
Thanks for the information provided here. I did to test and did a little research and I'm happy to say that at least the workaround (using either of screen and xterm application) works. 

Of course, the PowerShell cmdlet Clear-Host nor Linux 'clear' command won't work but I can use PowerShell in Bash for Windows.

I just blogged about it. If anyone care to check it out: [http://www.maxtblog.com/2016/10/running-powershell-in-windows-10-bash-workaround/] 

This is Awesome!

**Comment by segin** [comment] 2016-10-03 09:10
@MaximoTrinidad - Please keep in mind that you can also use 'tmux' as well, which does not require elevated privileges, that is, does not require being run as 'root'. 

This may be of value if you are using `openssh-server` to provide shell access for collaborative development or exploration of WSL and wish to use the traditional Linux security model for Linux user separation.

**Comment by MaximoTrinidad** [comment] 2016-10-03 13:00
@segin This is Great! I already been using "Xserver for Windows" for some time and recently using 'screen' on my Linux box.  I just needed to know about 'xterm' then try them in Bash for Windows. I already know to look for the configuration file could help in clearing some issues. So I found more information on the internet to get what I wanted.  I did update my blog and added the links I use for the workaround.

I love this community!

**Comment by zadjii-msft** [comment] 2016-10-03 15:56
So, just to follow up with everyone:

I have been investigating this for a little while now, and the problem isn't with conhost.exe or powershell itself. That being said, I'm not really sure what the problem is yet, but it goes all the way down to dotnet core's implementation of System.Console.GetCursor{Top/Left}, and it's interaction with LXCore/bash.exe.

I believe (but can't prove yet unfortunately) that this is also related to some problems with other applications as well, so this is my highest priority at the moment.

Until then, I agree with @segin's recommendation to use tmux, which somehow avoids this problem.

**Comment by MaximoTrinidad** [comment] 2016-10-03 16:02
Awesome!  I'm kind of like using 'screen' as I don't need to use xserver to open an external terminal. It comes down to user choice. That's why I blogged about both of them and discover how to configure xterm to use the mouse scroll bar.  I love this hacking techniques!

And, most important! I finally can use PowerShell in Bash for Windows.

Hum! I realized that I haven't use tmux.  I'll give it a try.  

Thanks everyone!
:)

**Comment by MaximoTrinidad** [comment] 2016-10-03 16:20
Ah! I just tested tmux and doesn't work for me.  I'm expecting to be able to scroll up and down in PowerShell after starting the application.  So, I'm guessing there's another set of ctrl keys or a configuration file to make it work.  

For now, I'm comfortable using either 'screen' or 'xterm' application.

**Comment by MaximoTrinidad** [comment] 2016-10-03 16:28
Thanks @segin !!  
I got the cheat sheet for tmux: `https://tmuxcheatsheet.com/`.   Now , I understand and I'm now liking it

I will build a short blog soon about it.

Sample image using Crtl-B + pgUp:

![tmuxsampleup_2016-10-03](https://cloud.githubusercontent.com/assets/19892435/19045012/c4b5c670-8964-11e6-84f8-9fa668294786.jpg)

**Comment by zadjii-msft** [comment] 2017-02-06 16:31
Status Update:
I made a change to the lxss kernel last friday that should make input sequences that are generated by a single keypress all get injected into the subsystem at the same time, as opposed to character by character. This was in response to a number of issues, #425, #933, #980, and a reported issue with `ghci`. 

Ideally, this should be fixed in an insiders build soon<sup>tm</sup>. 

I don't think it fixes *everything* with Powershell on WSL (they still repaint the entire line on any input, and that can cause some blinking/cursor jumping), but it should be at least usable now.

**Comment by MaximoTrinidad** [comment] 2017-02-06 16:57
Just recently, recently I finally got PowerShell working in WSL. But is thanks to installing Ubuntu Desktop. I blogged about it, and seems to work: http://www.maxtblog.com/2017/01/windows-10-bash-and-powershell-redux/

So, now that I got it to work, I haven't try using both 'screen' or 'xterm' in the Ubuntu Desktop environment.   (see image below)

One thing, the 'screen' app in WSL is not working correctly. The screen welcome page doesn't come up and the it resize the console prompt.  I will create an incident about it today!

![powershell_works_2017-01-20_16-35-28](https://cloud.githubusercontent.com/assets/19892435/22657066/316bccea-ec63-11e6-8354-fc68a4392417.jpg)

**Comment by zadjii-msft** [comment] 2017-02-06 17:15
@MaximoTrinidad Oh, that part about `screen` resizing the window should also be fixed in insiders, don't you worry. I believe that change also fixed the startup page as well.

**Comment by MaximoTrinidad** [comment] 2017-02-06 17:17
@zadjii-msft,

Ah! I posted the issue.  No worries! Have some one closed the incident if is already resolved.
Sorry!!
:)

**Comment by MaximoTrinidad** [comment] 2017-02-06 17:43
Hi @zadjii-msft 

BTW,  all my issues with PowerShell has been corrected by using 'Ubuntu Desktop'.  I can even use both 'screen' and xterm app to run PowerShell. 

![screenfix_03_2017-02-06_11-59-11](https://cloud.githubusercontent.com/assets/19892435/22658919/ca429966-ec69-11e6-95fe-a7306aebaa26.jpg)

**Closed** 2017-05-20 16:52 UTC
Labels: console, fixedincreatorsupdate
