### ISSUE TITLE
PowerShell in Windows BASH display issues when typing cmdlets

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/BashOnWindows#980] opened 2016-08-24 19:52 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description
  Please see GitHub issue: "PowerShell in Windows BASH display issues #1829"
  https://github.com/PowerShell/PowerShell/issues/1829#issuecomment-242179505 

The cursor going back to the top of the screen everytime you press enter.
- Expected results
  To be able to run cmdlet without the cursor going back to the top of the screen everytime you press enter.
- Actual results (with terminal output if applicable)
  ![bashposherr_01](https://cloud.githubusercontent.com/assets/19892435/17945444/eca90718-6a11-11e6-8e9f-5cbec85ef413.jpg)
  ![bashposherr_02](https://cloud.githubusercontent.com/assets/19892435/17945447/f1282dd2-6a11-11e6-94a0-e8fff3def222.jpg)
  ![bashposherr_03](https://cloud.githubusercontent.com/assets/19892435/17945451/f39b14e4-6a11-11e6-9bb7-be31debe8cd5.jpg)

![bashposherr_04](https://cloud.githubusercontent.com/assets/19892435/17945456/f96eddba-6a11-11e6-90b7-4f63331bc498.jpg)
- Your Windows build number
  Windows 10 Pro Insider Preview
  Build 14905.rs_prerelease.160811-1739

P$PSVersionTable

Name                           Value

---

PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.9
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
- Steps / commands required to reproduce the error
- Strace of the failing command
- Required packages and commands to install
  PowerShell in Windows Bash cmd. I installed it using the Ubuntu version 14.04.
  (Instruction: https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#ubuntu-1404)

$ sudo apt-get install libunwind8
$ sudo apt-get install libicu52
$ cd Downloads
$ sudo dpkg -i powershell_6.0.0-alpha.9-1ubuntu1.14.04.1_amd64.deb

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by russalex** [comment] 2016-08-24 20:24
Thanks for giving Powershell a shot on WSL.

We've seen this one as well and it looks to be related to #933.  @bitcrazed and his team are looking into this.

**Comment by MaximoTrinidad** [comment] 2016-10-03 02:45
Thanks for the information at the BASH incident: [https://github.com/Microsoft/BashOnWindows/issues/933] 

I did some test and little more  research and I'm happy to say that at least the workaround (using either of screen and xterm application) works. 

Of course, the PowerShell cmdlet Clear-Host nor Linux 'clear' command won't work but I can use PowerShell in Bash for Windows.

I just blogged about it. If anyone care to check it out: [http://www.maxtblog.com/2016/10/running-powershell-in-windows-10-bash-workaround/] 

This is Awesome!

**Comment by MaximoTrinidad** [comment] 2016-10-18 19:12
@russalex  - Just an FYI

There's no change yet with the new release powershell-6.0.0-alpha.11*.deb.
:)

Max

**Comment by lypanov** [comment] 2016-12-10 21:47
I finally found a work around to this and to many of the issues I have with bash on Windows. Even with 13 there are still massive issues with display.

I now run Token2Shell/MD "Metro" application and SSH to my bash instance running a tmux. Alternative might be putty but I like the above.

Still powershell isn't working but now at least not for this reason! :)

**Comment by zadjii-msft** [comment] 2017-02-06 17:17
As mentioned in #933, A fix for this should be coming in insiders builds soon. I'm gonna close this issue, as it's generally a dupe of that thread.

**Closed by zadjii-msft** 2017-02-06 17:17 UTC
Labels: console, duplicate

**Comment by MaximoTrinidad** [comment] 2017-02-06 17:22
Thanks!
:)
