### ISSUE TITLE
Unable to execute lsusb or lsblk

### ISSUE THREAD

**Issue by gravityFlower** [Microsoft/BashOnWindows#2287] opened 2017-07-05 12:50 UTC
Version used: 
Microsoft Windows [Version 10.0.15063]

Command which were attempted:
`$ lsusb
unable to initialize libusb: -99`

`lsblk
lsblk: failed to access sysfs directory: /sys/dev/block: Datei oder Verzeichnis nicht gefunden`

expected:
- list of usb devices and block device (listing and interaction with them)

purpose:
access disks formatted with linux file systems

**Comment by sunjoong** [comment] 2017-07-05 14:48
@gravityFlower - There is no usb support on 15063, but on 16176;
* https://stackoverflow.com/questions/38954691/is-usb-supported-on-bash-on-ubuntu-on-windows-10
* https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-16176
* https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/16759696-add-usb-device-support

**Comment by benhillis** [comment] 2017-07-05 16:09
Marking as a duplicate of #689 (block device support).

**Closed by benhillis** 2017-07-05 16:09 UTC
