### ISSUE TITLE
"/init cmd /C set" contains too few environment variables, some softwares run failed

### ISSUE THREAD

**Issue by goreliu** [Microsoft/BashOnWindows#1257] opened 2016-10-23 13:12 UTC
* A brief description

`/init cmd /C set` contains too few environment variables, some softwares run failed, like `shutdown`.

```
$ /init shutdown
The system could not find the environment option that was entered.(203)

$ /init cmd /C 'set COMPUTERNAME=MY-PC & shutdown'
Usage: shutdown ...
```

And without `TMP` variable, some softwares run failed.

* Your Windows build number

```
14951.1000
```

* Steps / All commands required to reproduce the error from a brand new installation

```
/init shutdown
```

**Comment by benhillis** [comment] 2016-10-23 15:33
Thanks for reporting this. The processes created out of WSL should have the same environment as the bash.exe window you are running.  This is working for me internally. How are you launching bash? Could you share the output of this command with me?

`/init cmd.exe /c set`

My output shows TMP, COMPUTERNAME, etc.

**Comment by goreliu** [comment] 2016-10-23 16:38
It‘s my carelessness. I ran it in [wslbridge](https://github.com/rprichard/wslbridge) in [mintty](https://github.com/mintty/mintty/). I think the problem was caused by mintty. Thanks.

**Comment by mintty** [comment] 2016-10-23 17:12
The problem is certainly not *cause* by mintty or wsltty. If `shutdown` depends on the setting of some non-standard environment variable, it's an incompatibility of shutdown (provided the Linux version of shutdown is meant). Setting TMP is not strictly required in a Linux environment, but should normally be set somewhere in the /etc profile scripts. This is a WSL configuration issue.

**Comment by goreliu** [comment] 2016-10-23 17:19
@mintty The shutdown is shutdown.exe instead of /usr/bin/shutdown in WSL, it requires Windows environment variables,.

**Comment by mintty** [comment] 2016-10-23 17:51
> it requires Windows environment variables

Nice, so if WSL assumes a set of proprietary settings, they should properly document that somewhere (first issue from my point of view), then we could ask third-party invocation tools (`wslbridge`) to replicate that behaviour (second issue).

I suggest you reopen this issue.

**Comment by goreliu** [comment] 2016-10-23 18:05
@mintty I run bash.exe with some Windows environment variables, then run Windows softwares with /init, it has nothing to do with WSL. I don't know what environment variables the software requires, WSL doesn't know neither.

**Comment by mintty** [comment] 2016-10-23 18:15
Oh, understood. In that case I suggest to close this issue again :/
and reopen the other one.

**Closed** 2016-10-23 18:16 UTC
