### ISSUE TITLE
Windows 10 LTSB or LTSC.

### ISSUE THREAD

**Issue by jdm7dv** [Microsoft/BashOnWindows#2556] opened 2017-10-10 21:39 UTC
Microsoft Windows [Version 10.0.10240]

When is the Linux Subsystem going to support my build. And how do I install it.

**Comment by benhillis** [comment] 2017-10-10 21:46
I suggest installing the most recent version of Windows 10:  https://support.microsoft.com/en-us/help/4028685/windows-get-the-windows-10-creators-update

Fall Creator's Update is due very soon.

**Comment by benhillis** [comment] 2017-10-10 21:46
Duplicate of #1281.

**Closed by benhillis** 2017-10-10 21:46 UTC
