### ISSUE TITLE
error installing "libwww-perl_6.05-2_all.deb"

### ISSUE THREAD

**Issue by nomike** [Microsoft/BashOnWindows#1547] opened 2016-12-28 11:17 UTC
* A brief description
When trying to install "libwww-perl" im getting an error message from dpkg.

* Expected results
"libwww-perl" should be installed without errors.

* Actual results (with terminal output if applicable)
---SNIP---
    micpos@VIE-MICPOS-MOB:/mnt/c/Users/micpos/Downloads$ sudo apt-get install libwww-perl
    [sudo] password for micpos:
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    Suggested packages:
      libauthen-ntlm-perl
    The following NEW packages will be installed:
      libwww-perl
    0 upgraded, 1 newly installed, 0 to remove and 68 not upgraded.
    93 not fully installed or removed.
    Need to get 0 B/146 kB of archives.
    After this operation, 384 kB of additional disk space will be used.
    (Reading database ... 27998 files and directories currently installed.)
    Preparing to unpack .../libwww-perl_6.05-2_all.deb ...
    Unpacking libwww-perl (6.05-2) ...
    dpkg: error processing archive /var/cache/apt/archives/libwww-perl_6.05-2_all.deb (--unpack):
     unable to install new version of `/usr/bin/HEAD': File exists
    Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
    Errors were encountered while processing:
     /var/cache/apt/archives/libwww-perl_6.05-2_all.deb
    E: Sub-process /usr/bin/dpkg returned an error code (1)
---SNAP---

* Your Windows build number
14393

* Steps / All commands required to reproduce the error from a brand new installation 
See above

* Strace of the failing command

See attachment
[libwww-perl.strace.txt](https://github.com/Microsoft/BashOnWindows/files/675475/libwww-perl.strace.txt)

* Required packages and commands to install

See above

**Comment by sunilmut** [comment] 2016-12-28 20:25
@nomike - Thanks for the report. I cannot reproduce the issue on the Insider builds. WSL gets regular updates through Insider builds and these fixes will also be available in the next general release (a.k.a `Creator Update`). But these fixes are not getting backported to Anniversary Update build (14393, the one that you are running). So, if you are able to validate this in the Insider build, that would be great. I am marking the issue closed as per above. Please let us know if the issue still exists in Insider builds and we can reopen it.

**Closed by sunilmut** 2016-12-28 20:25 UTC
