### ISSUE TITLE
Cmake cannot find the gcc/g++ compilers

### ISSUE THREAD

**Issue by nlappas** [Microsoft/BashOnWindows#272] opened 2016-04-26 16:00 UTC
Hi, I installed build essentials, gcc, g++, cmake, make and I tried to run a simple project.
However I get error messages from CMAKE that the compiler is broken.

:/mnt/c/Users/NAME/Documents/githubLocal/mybuild$ cmake Unix Makefiles -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=/usr/bin/g++ -     DCMAKE_CC_COMPILER=/usr/bin/gcc ..
     -- The C compiler identification is unknown 
     CMake Error at /usr/share/cmake-2.8/Modules/CMakeDetermineCCompiler.cmake:186    (configure_file):
     configure_file Problem configuring file 
     Call Stack (most recent call first):
     CMakeLists.txt:59 (project)

     -- The CXX compiler identification is unknown
    CMake Error at /usr/share/cmake-2.8/Modules/CMakeDetermineCXXCompiler.cmake:185     (configure_file):
   configure_file Problem configuring file
   Call Stack (most recent call first):
   CMakeLists.txt:59 (project)

-- Check for working C compiler: /usr/bin/cc
CMake Error at /usr/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:47 (try_compile):
  Unknown extension ".c" for file

    /mnt/c/Users/NAME/Documents/githubLocal/mybuild/CMakeFiles/CMakeTmp/testCCompiler.c

  try_compile() works only for enabled languages.  Currently these are:

    C CXX

  See project() command to enable other languages.
Call Stack (most recent call first):
  CMakeLists.txt:59 (project)

-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/bin/cc" is not able to compile a simple test program.

  It fails with the following output:

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:59 (project)

-- Configuring incomplete, errors occurred!
See also "/mnt/c/Users/NAME/Documents/githubLocal/mybuild/CMakeFiles/CMakeOutput.log".
See also "/mnt/c/Users/NAME/Documents/githubLocal/mybuild/CMakeFiles/CMakeError.log".
nlappas@NIKOS-SURFACE:/mnt/c/Users/Nikos/Documents/githubLoca/mybuild$`

By the way the compilers work properly, when I use them from the command line, they compile source files and link them succesfully. Which gcc and which g++ give me also the correct paths.

**Comment by benhillis** [comment] 2016-04-26 21:45
Could you try cloning your git repro into your UNIX user's home directory (cd ~) and try building again?  

If this is a public GitHub repro?  If so send me the link and I can try this myself.

Thanks!

**Comment by nlappas** [comment] 2016-04-26 22:12
I tried a minimal helloworld c++ test program with the corresponding cmakefile that fails for me even in the home directory.
https://github.com/nlappas/CMAKE_BASH_WINDOWS_TEST.git

**Comment by mxalbert1996** [comment] 2016-04-27 14:25
Same problem here. I wanted to compile x265 (https://bitbucket.org/multicoreware/x265) and it showed:
>-- The C compiler identification is unknown
>CMake Error at /usr/share/cmake-2.8/Modules/CMakeDetermineCCompiler.cmake:186 (configure_file):
>  configure_file Problem configuring file
>Call Stack (most recent call first):
>  CMakeLists.txt:19 (project)
>
>-- The CXX compiler identification is unknown
>CMake Error at /usr/share/cmake-2.8/Modules/CMakeDetermineCXXCompiler.cmake:185 (configure_file):
>  configure_file Problem configuring file
>Call Stack (most recent call first):
>  CMakeLists.txt:19 (project)
>
>-- Check for working C compiler: /usr/bin/cc
>CMake Error at /usr/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:47 (try_compile):
>  Unknown extension ".c" for file
>
>    /root/Dev/x86_64/x265/build/CMakeFiles/CMakeTmp/testCCompiler.c

CMakeError.log:
>Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
>Compiler: /usr/bin/cc 
>Build flags: 
>Id flags: 
>
>The output was:
>1
>/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: in function `_start'
>(.text+0x20): undefined reference to `main'
>collect2: error: ld returned 1 exit status
>
>The C compiler identification could not be found in >"/root/Dev/x86_64/x265/build/linux/CMakeFiles/2.8.12.2/CompilerIdC/CMakeCCompilerId.o"

Currently using Insider Preview 14332. There were no problem on 14295. Not sure on 14318.

**Comment by mcgoo** [comment] 2016-04-28 02:31
This appears to be caused by the writev system call failing with -EFAULT on WSL and succeeding on linux when passed a struct iovec containing a null pointer.

repro :-

#include <sys/uio.h>
#include <iostream>

//  gcc -std=c++11 main.cpp -lstdc++ && ./a.out

int main()
{
    iovec iov{nullptr,0};
    auto res = writev(1, &iov, 1);
    std::cout << res << std::endl;
    return 0;
}

**Comment by benhillis** [comment] 2016-04-28 02:37
I'm actually working on a fix for this right now. I'm try make to make sure it works with my change.

**Comment by benhillis** [comment] 2016-04-28 02:38
@Mcgoo Thanks for the awesome debugging!

**Comment by benhillis** [comment] 2016-04-28 02:41
@Mcgoo Minor note. Its actually the buffer size of zero that makes the above example work. If you change the size to non zero you will get EFAULT.

**Comment by mcgoo** [comment] 2016-04-28 03:28
@benhillis Yeah, seems like it shouldn't validate the pointer member if the length is zero. I'd expect EFAULT with a null pointer and a non-zero length. 

Thanks, WSL is great stuff.

**Comment by benhillis** [comment] 2016-04-29 16:55
@mcgoo after fixing the issue with the writev system call that you identified I'm able to build run cmake on the project that @nlappas linked.

@mxalbert1996 I'm trying out https://bitbucket.org/multicoreware/x265 now.

```
root@BENHILL-VM7:~/CMAKE_BASH_WINDOWS_TEST# cmake .
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
```
-- Build files have been written to: /root/CMAKE_BASH_WINDOWS_TEST

**Comment by benhillis** [comment] 2016-04-29 17:04
@mxalbert1996 Looks like cmake is finding the C and C++ compilers, but I'm not sure what to do at this screen.  If I press 'c' I get an "Errors occurred during the last pass" error.

![image](https://cloud.githubusercontent.com/assets/17727402/14923378/c5443b06-0df1-11e6-9ffd-d802b7f38f61.png)

**Comment by aidsjorb** [comment] 2016-04-29 17:18
I'm afraid I don't know what to say on that latest issue but I did get the same cmake compiler errors on both wangle (https://github.com/facebook/wangle) and casablanca (https://github.com/Microsoft/cpprestsdk) if you're looking for other projects to try it out on.

**Comment by mcgoo** [comment] 2016-04-29 18:48
@benhillis maybe try 

cd ~/x265; mkdir tmp; cd tmp; cmake ../source

and you should be able to see what cmake is complaining about.

**Comment by WhiteBearSpirit** [comment] 2016-04-29 19:50
Hello @benhillis !
I am trying to setup torch7 on my BashOnWindows and I'm getting exactly same error as described in this topic:
> CMake Error at /usr/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:47 (try_compile):
>   Unknown extension ".c" for file
> 
>     /home/white/torch/build/CMakeFiles/CMakeTmp/testCCompiler.c
> 
>   try_compile() works only for enabled languages.  Currently these are:
> 
>     C CXX

My cmake version is 2.8.12.2

I've installed Bash on my Windows 10 (build 14332) like 40 minutes ago, so i guess it's the newest version of it. If this error is already fixed, please tell me how can I get this fix.
I'm very glad that here I can get support from a direct developer and I am really hoping for your feedback!

**Comment by benhillis** [comment] 2016-04-29 19:59
@WhiteBearSpirit Unfortunately you'll have to wait for another external release to the fast ring for this to be fixed.  The change that fixes this was made a few days ago on our development branch and will take some time to reach the fast ring.  Unfortunately there is currently no workaround.

Keep an eye out for our release notes as we release new builds.

**Comment by nlappas** [comment] 2016-04-29 20:49
Thanks @benhillis  !

**Comment by bitcrazed** [comment] 2016-05-01 20:03
Bug also filed over here on the CMake tracker - https://cmake.org/Bug/view.php?id=16079.

Will point them this way as the source of the fix.

**Comment by hohoCode** [comment] 2016-05-02 14:17
Hi @WhiteBearSpirit , if you can install Torch7 on this great Windows Bash (after they fixed the bug), please let me know... I also want to install Torch7 on Windows. Thanks!!

**Comment by benhillis** [comment] 2016-05-04 15:18
Adding a link to #238 as this is the same issue.

**Comment by benhillis** [comment] 2016-05-04 15:18
Adding a link to #238 since this has the same root cause.

**Comment by mcgoo** [comment] 2016-05-11 14:16
I just updated - looks like this fix did not make it in time for 14342.

**Comment by benhillis** [comment] 2016-05-11 15:13
@mcgoo thanks for confirming, I will make sure that our release notes for 14342 get published today.

**Comment by davidanthoff** [comment] 2016-05-16 17:25
If you want another public repo that is affected by this, try https://github.com/julialang/julia. That might actually generally be a good test case, it compiles a LOT of external dependencies etc., so it might be a good test case.

**Comment by vertgo** [comment] 2016-05-18 17:25
What build number (and later) is this fixed in?

**Comment by kimjs29** [comment] 2016-05-22 03:19
@mcgoo Your test case passes successfully on 14342, specifically to STDIN_FILENO.
@benhillis But a similar test case to disk file has failed. I modified @mcgoo's test case as follows
```
#include <sys/uio.h>
#include <stdio.h>
#include <fcntl.h>
//  gcc main.c && ./a.out
int main()
{
    struct iovec iov = {NULL,0};
    int fd = creat("test.txt", O_WRONLY);
    if (writev(fd, &iov, 1) < 0)
        perror("writev error: ");
    close(fd);
}
```

**Comment by benhillis** [comment] 2016-05-23 15:24
@kimjs29 Thanks for providing such a clear repro.  I'll give this a shot as soon as I get to my desk.

**Comment by mrunix** [comment] 2016-05-27 02:39
when I can get the fixed release? Thank you.

**Comment by nlappas** [comment] 2016-05-27 03:34
It seems fixed in the build 14352 that was released today to the fast ring :D

**Comment by benhillis** [comment] 2016-05-27 19:00
Closing this out as users have verified this is fixed in build 14352, please reopen if you continue to see this issue. Thanks!

**Closed by benhillis** 2016-05-27 19:00 UTC
Labels: fixed

**Comment by eliseofe** [comment] 2016-05-31 16:41
I confirm too!

**Comment by vagarwal87** [comment] 2016-06-04 00:53
is there a way to fix this issue without upgrading the build? the build upgrade screws up other components of my computer so I'm hoping to find a workaround with build 14342

**Comment by sunilmut** [comment] 2016-06-06 22:14
@vagarwal87 - No. At the moment and unfortunately, WSL upgrade is tied to Windows build upgrade.

**Comment by Laz3rPanth3r** [comment] 2016-10-19 22:55
Is this coming to regular users anytime soon? If it's been fixed since May, well its now October and I just ran into this bug in the Windows Anniversary edition.

**Comment by cvelten** [comment] 2016-10-20 00:02
It indeed is fixed, might be that those fixes haven't made it into the newest official builds? Just subscribe to the Release Preview channel for Windows Insider, which will give you one of the most stable versions. I can confirm that in the current build of the Release Preview ring, this bug is fixed.

**Comment by admo** [comment] 2019-06-11 12:54
@benhillis  This error reappear in Windows 1903:
```sh
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:186 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- The C compiler identification is GNU 7.4.0
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCCompiler.cmake:192 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- The CXX compiler identification is GNU 7.4.0
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:190 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Detecting C compile features
-- Detecting C compile features - failed
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:72 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - failed
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:65 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- Configuring incomplete, errors occurred!
```

I have clean Ubuntu WSL Bionic installation. Just install cmake and build-essential package. I've tried to generate project for very simple CMakeLists.txt:
```cmake
project(test)
```
