### ISSUE TITLE
Error: 0x80070057

### ISSUE THREAD

**Issue by leonardowolf** [Microsoft/BashOnWindows#7] opened 2016-04-07 03:56 UTC
I'm an early adopter and a think I comited some sort of mistake in the processo of instalation of bash on my Windows computer. I did just like the blog step by step says, but by some kind of sorcery, if i have to do some serious shit on my cmd (this is an old trouble) i need to open it as admin. I'v done the activation of Windows Subsystem for Linux and restarted my SO. But when I come back to install the bash by cmd I forgot to open it as admin. There was no trouble at all during the instalation but now when I try to open the bash, from the cmd (as adm or not), or even from the installed app I have this error by response:"Error: 0x80070057". 

Any tips to fix this? and yes I alredy tryed to restart my computer fhaushfuashdf (sad this didn't worked)

**Comment by leonardowolf** [comment] 2016-04-07 04:13
https://github.com/Microsoft/BashOnWindows/issues/4#issuecomment-206662392

I tryed these, Re-installed all the bash from an adm prompt and i still got the same error

**Comment by J-Gonzalez** [comment] 2016-04-07 04:26
I've noticed this error occurs if you have the command prompt in legacy mode. Make sure you disable legacy mode and try if that works.

![image](https://cloud.githubusercontent.com/assets/1047598/14340635/44b86e22-fc3e-11e5-9c06-1aef4ebbebfa.png)

**Comment by raeesiqbal** [comment] 2016-04-07 09:21
Related to https://github.com/Microsoft/BashOnWindows/issues/2

**Comment by AlvaroOrduna** [comment] 2016-04-07 10:55
I had the same error when attempting to start bash in WSL. It has been fixed by **disabling legacy mode** in the console options.

**Comment by leonardowolf** [comment] 2016-04-07 13:52
Wow  bro, TY all, worked fine here

**Closed** 2016-04-07 13:53 UTC

**Comment by jbaribeault** [comment] 2016-04-07 22:05
I noticed this setting gets set the moment you try and change the colors too - be careful!

**Comment by vidarw** [comment] 2016-04-12 07:53
Should this be closed?
Even if we have a proper workaround and identified the cause of the problem, it's still breaking bug!

**Comment by mabotn** [comment] 2016-04-12 11:23
Hi,
the solution is simple :)
1. open CMD
2. go to its properties
3. disable legacy mode
4. restart cmd
5. run bash

enjoy :D

**Comment by Arthur2e5** [comment] 2016-04-13 19:08
This happens with other terminal emulators like mintty too. I was trying to escape from conhost's crappy emulation (e.g. problem with inserting characters in the middle of a bash command), but neither sshd nor other emulators worked.

Perhaps I should get xterm.

**Comment by hbsis-lucianorodrigues** [comment] 2016-06-15 15:57
Disable legacy mode do not works to me. I'm executing bash from java:

`String script = "/mnt/d/bla.sh"; // "d:\\bla.sh"; // "d:/bla.sh"       /* None works! */`
`Process process = new ProcessBuilder("bash.exe", "-xe", script).start();`

**Comment by Napo2k** [comment] 2016-11-16 15:12
I am having this same issue when executing bash from a Jenkins job

**Comment by rudolphos** [comment] 2017-02-13 03:41
Legacy mode disabled.

> C:\WINDOWS\system32>bash
> Error: 0x80070002

Bash just opens and closes when I run the exe. In cmd it shows that error.

**Comment by sunilmut** [comment] 2017-03-02 00:39
@rudolphos - Thanks for your post. Can you please collect ETL traces using [these](https://msdn.microsoft.com/en-us/commandline/wsl/troubleshooting#starting-bash-gives-an-error-code) steps and share the traces out?

Also, which windows build are you running. You can find that out using the windows `ver` command.

**Comment by ReFruity** [comment] 2017-03-11 12:21
I get this error when using %%bash magic in Jupyter Notebook. Any idea how to fix this?

**Comment by aseering** [comment] 2017-03-11 15:08
Hi @ReFruity -- could you be more specific about exactly what you're doing when you get this error?  Are you using the Windows or the Linux version of Jupyter Notebook?  What's an example of the exact magic that causes this error for you?

Also, per @sunilmut 's question above:  Which Windows build are you running?  You can find that out using the Windows `ver` command (at a Windows command prompt).

**Comment by rudolphos** [comment] 2017-03-12 01:39
@sunilmut 

My Win version: Microsoft Windows [Version 10.0.14393
etl files:
[lxcore_win_10.0.14393.zip](https://github.com/Microsoft/BashOnWindows/files/836245/lxcore_win_10.0.14393.zip)]

**Comment by ReFruity** [comment] 2017-03-18 09:49
@aseering I am using Anaconda2-4.3.0.1 on Windows 10 with enabled bash support. 

Any simple bash command, for example,
```
%%bash
ls
```
will cause this error.

**Comment by tksunw** [comment] 2017-03-20 00:43
I am getting `Error: 0x80070057` when I try to install the Linux bits, via running `bash` or running `lxrun /install`, as an admin user or a regular user.

I have read several of the other threads in this forum that mentioned this issue, and none of the solutions worked for me, so I'm starting a new thread.

Here is the terminal output:
```
PS C:\Users\tkennedy\WS_ETL> lxrun /install
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Error: 0x80070057
```

My Microsoft build is:
`Microsoft Windows [Version 10.0.14393]`

* Steps to reproduce:

- `lxrun /uninstall /full /y'
- `lxrun /install /y`

I have ETL files from the lxcore_trace scripts.  [WSL_ETL.zip](https://github.com/Microsoft/BashOnWindows/files/852032/WSL_ETL.zip)

Ran a full `chkdsk /R`, followed by a reboot, just in case it was a disk issue.

Same error.

Disabled the WSL feature, by running:
`Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
And rebooting.  After reboot, re-enabled the WSL feature, by running:
`Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
And rebooting again.

Same error:

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

Z:\>bash
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Error: 0x80070057
```

**Comment by tksunw** [comment] 2017-03-20 02:28
1.  `Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
2.  `Remove-Item "$env:windir\System32\Tasks\Microsoft\Windows\Windows Subsystem for Linux" -Recurse -Force`  ( as seen in #931 )
2.  Reboot
3.  `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
4.  Reboot
5.  Failure to even install the feature now.

**Comment by huangqingxin** [comment] 2017-07-05 06:30
I meet  new  problems , any others see this before

PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Enable-WindowsOptionalFeature : The parameter is incorrect.
At line:1 char:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], PSArgumentException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

**Comment by hsluoyz** [comment] 2017-07-15 15:05
@huangqingxin  I met the same issue:

![image](https://user-images.githubusercontent.com/3787410/28240312-0a2c1050-69b2-11e7-81c7-2e9a3fa63fad.png)

**Comment by samfullman** [comment] 2017-07-28 15:50
> I've noticed this error occurs if you have the command prompt in legacy mode. Make sure you disable legacy mode and try if that works.
from J-Gonzales on April 7th above..
This helped me though ironically I _checked_ the legacy mode and it worked.

**Comment by eltechnic0** [comment] 2017-09-12 08:30
Still having this error when piping or redirecting the output. For instance: `bash -c "ls -la" > out` writes `E r r o r :   0 x 8 0 0 7 0 0 5 7` to file `out`.
With no pipes or redir it works fine. Legacy mode is disabled.

**Comment by bardware** [comment] 2018-03-26 19:43
I got this error today when I started `kali`. It has worked in the past.
```
C:\Users\bd>kali
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070057
Error: 0x80070057 Falscher Parameter.
```
`Legacy console` is disabled.

![image](https://user-images.githubusercontent.com/802702/37928870-9c0059ba-313e-11e8-93b5-e40fe1a9e445.png)

**Comment by kyuuketsukikurai** [comment] 2018-03-27 12:17
Also getting this error when starting Kali. Any suggestions?

**Comment by DarthSpock** [comment] 2018-03-27 12:26
@kyuuketsukikurai @bardware See #3054

**Comment by tksunw** [comment] 2018-03-28 00:18
I have seen this error, 0x80070057, on two systems, and the only fix I ever found is a complete reinstall of Windows.

**Comment by ericclpt** [comment] 2019-02-04 10:42
I have the same issue while trying to re-install WSL, immediatly after approbation in command line mode.
Some corrupted files in a linux deep folder wasnt deletables and even renaming the lxss/root folder to something else wasn't enough after an uninstallation that has failled.
The only solution I found was to rename the lxrun folder itself in explorer. ( .../Appdata/Local/lxss to .../Appdata/Local/lxss_bad) and then installation have started normaly whitout reboot ...
After Linux installation it is possible to delete corrupted folder from bash prompt by "rm -rf lxss_bad" in the appropriate place (/mnt/c/Users/<user_name_/Local/).
This is a M2 disk and chkdsk wasn't able to find problems cause this is certainly more a "logical" corruption than physical.

**Comment by XDo0** [comment] 2021-12-08 11:25
- If you have used proxy, you will also encounter this error:
> ubuntu2004 config --default-user Username
> Error: 0x80070057 
And also see the error when : 
> `wsl`or`ubuntu2004` 
> 参考的对象类型不支持尝试的操作。（The attempted operation is not supported for the type of object referenced.）
- To solve:
> `netsh winsock reset` and reboot
