### ISSUE TITLE
LinuxWatchService fails when running clojure boot

### ISSUE THREAD

**Issue by laforge49** [Microsoft/BashOnWindows#1760] opened 2017-03-08 15:37 UTC
When running clojure boot, the LinuxWatchService throws an exception.

bill@T540P:/mnt/c/Users/Bill/Documents/rolonicArk/simpleArk$ boot.sh test-it
sun.nio.fs.UnixException: Bad file descriptor
        at sun.nio.fs.UnixNativeDispatcher.read(Native Method)
        at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:318)
        at java.lang.Thread.run(Thread.java:745)

Windows 10 version 1607 (OS Build 14393.693)

The boot development environment monitors the file system for changes. So this is a critical API when using clojure boot.

**Comment by laforge49** [comment] 2017-03-08 15:41
Forgot to mention the java version...

bill@T540P:~$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
bill@T540P:~$

**Comment by laforge49** [comment] 2017-03-08 15:43
Boot version info:

BOOT_CLOJURE_VERSION=1.9.0-alpha10
BOOT_VERSION=2.6.0
BOOT_EMIT_TARGET=no

**Comment by seancorfield** [comment] 2017-03-08 16:51
I believe this is a duplicate of some of the problems highlighted in #277 and is fixed in later Windows 10 builds. In particular, see my comment https://github.com/Microsoft/BashOnWindows/issues/277#issuecomment-241632789 which shows the same Bad file descriptor error.

**Closed** 2017-03-08 17:10 UTC
