### ISSUE TITLE
failed to repo sync aosp source code

### ISSUE THREAD

**Issue by tthsn** [Microsoft/BashOnWindows#1828] opened 2017-03-29 09:47 UTC
* A brief description
failed to repo sync aosp source code

* Actual results (with terminal output if applicable)
```
...
Fetching project platform/external/jemalloc
Fetching projects: 100% (545/545), done.
error: unable to create file frontend/client/src/autotest/public/Open+Sans:300.woff (Invalid argument)
error: unable to create file frontend/client/src/autotest/public/Roboto+Bold:700.woff (Invalid argument)
error: unable to create file frontend/client/src/autotest/public/Roboto+Light:300.woff (Invalid argument)
error: unable to create file frontend/client/src/autotest/public/Roboto+Medium:500.woff (Invalid argument)
error: unable to create file frontend/client/src/autotest/public/Roboto+Regular:400.woff (Invalid argument)
error: unable to create file server/site_tests/display_EdidStress/test_data/edids/weekly/SCT_272_STEELCASE_m:s_HDMI.txt (Invalid argument)
Checking out files: 100% (9442/9442), done.
Traceback (most recent call last):
  File "/mnt/d/aosp/.repo/repo/main.py", line 531, in <module>
    _Main(sys.argv[1:])
  File "/mnt/d/aosp/.repo/repo/main.py", line 507, in _Main
    result = repo._Run(argv) or 0
  File "/mnt/d/aosp/.repo/repo/main.py", line 180, in _Run
    result = cmd.Execute(copts, cargs)
  File "/mnt/d/aosp/.repo/repo/subcmds/sync.py", line 769, in Execute
    project.Sync_LocalHalf(syncbuf, force_sync=opt.force_sync)
  File "/mnt/d/aosp/.repo/repo/project.py", line 1247, in Sync_LocalHalf
    self._InitWorkTree(force_sync=force_sync)
  File "/mnt/d/aosp/.repo/repo/project.py", line 2393, in _InitWorkTree
    raise GitError("cannot initialize work tree")
error.GitError: cannot initialize work tree
```
* Your Windows build number
`Windows 10 Version 1607 (OS Build 14393.969)`

* Steps / All commands required to reproduce the error from a brand new installation 

```
$ cd ~
$ curl https://storage.googleapis.com/git-repo-downloads/repo > repo
$ chmod a+x ~/repo
$ ~/repo init -u https://android.googlesource.com/platform/manifest
$ ~/repo sync -j1

```
* Strace of the failing command

N/A

* Required packages and commands to install
```
$ sudo apt-get install git-core gnupg flex bison gperf build-essential \
  zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
  lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache \
  libgl1-mesa-dev libxml2-utils xsltproc unzip
```

**Comment by tthsn** [comment] 2017-03-29 09:49
It seems caused by colon(:) in filename in NTFS file system.
Is there any workaround?

**Comment by aseering** [comment] 2017-03-29 15:04
Unfortunately, no.  See #1514.

If you're trying to work with aosp, you should also have a look at #1771 .  Basically, it ain't gonna work yet :-)  Feel free to follow up on either of those tickets.

**Comment by benhillis** [comment] 2017-03-29 15:08
Closing as a duplicate of #1514.

**Closed by benhillis** 2017-03-29 15:08 UTC

**Comment by cydia2020** [comment] 2017-09-06 05:23
Same situation here

**Comment by fatterx** [comment] 2018-02-07 02:56
workaround:

modify ./repo/repo/project.py

goto line 2485

comment this two lines

#        if GitCommand(self, cmd).Wait() != 0:
#          raise GitError("cannot initialize work tree")

**Comment by xonq** [comment] 2019-07-04 20:22
> workaround:
> 
> modify ./repo/repo/project.py
> 
> goto line 2485
> 
> comment this two lines
> 
> `# if GitCommand(self, cmd).Wait() != 0:`
> `# raise GitError("cannot initialize work tree")`

how does that fix it - it simply bypasses reporting the error?
