### ISSUE TITLE
Please support disk device files  under /dev !

### ISSUE THREAD

**Issue by ytrezq** [Microsoft/BashOnWindows#1120] opened 2016-09-25 13:19 UTC
On Cygwin I can use`/dev/sd`XX files directly.

This allows me to manages the fileystems of embedded devices runing linux directly *(for example I can run something like `mkfs.ext2 /dev/sdc1`or copy a firmware to the ꜱᴅ card using `dd`)*

Would it be possible to have the same feature on Windows subsystem for Linux ?
Please note I don’t want to be able to mount the filesystems, but just read and write to their device files.

Otherwise, wsl isn’t a good platform for building and loading firmwares on the ꜱᴅ card.

**Comment by fpqc** [comment] 2016-09-25 13:53
This is a duplicate of https://github.com/Microsoft/BashOnWindows/issues/689

**Closed** 2016-09-25 13:55 UTC
