### ISSUE TITLE
tmux does not work as usual

### ISSUE THREAD

**Issue by atari** [Microsoft/BashOnWindows#40] opened 2016-04-07 17:59 UTC
tmux does not work as usual - opening tmux results in nothing?

**Comment by gdude2002** [comment] 2016-04-07 18:22
There's no pty right now - I believe this is listed as a TODO, though.

**Comment by patryk9200** [comment] 2016-04-07 18:22
MS know about that, they are working to fix this.
You can read about this there:
https://insights.ubuntu.com/2016/03/30/ubuntu-on-windows-the-ubuntu-userspace-for-windows-developers/
Duplicate of #39

**Comment by yunfan** [comment] 2016-04-09 12:28
how can you claim you have provide a subsystem for linux when you even cant support pty? its a basic requirement

**Comment by gdude2002** [comment] 2016-04-09 12:29
@yunfan They don't claim to have provided one yet, this is still in very early alpha. Or don't you understand the nature of insider builds?

**Comment by sunilmut** [comment] 2016-04-11 21:58
Yes, PTY is not yet fully implemented and we are aware of this limitation. We will be tracking\prioritizing which features to light up next by looking at the feedback provided at the wpdev portal. We appreciate your feedback and please make sure to provide it through the wpdev portal as well. Looks like there is already a post tracking this which you can up vote (or add a new one):

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13248360-pseudoterminals

**Closed by sunilmut** 2016-04-11 21:58 UTC

**Comment by russalex** [comment] 2016-06-08 20:29
Pulling this one back up.  TMUX is now functional in build 14361.

**Comment by therealkenc** [comment] 2016-06-09 01:21
xterm is also working. That's awesome; you guys are being too modest!
