### ISSUE TITLE
Trouble renaming/moving windows directories in bash

### ISSUE THREAD

**Issue by slugmuffin** [Microsoft/BashOnWindows#1768] opened 2017-03-09 21:43 UTC
* A brief description
I used SVN to checkout a directory and then I wanted to rename it.
$ mv myprojectname myNEWprojectname

* Expected results
I expected the directory to be renamed (and quickly)

* Actual results (with terminal output if applicable)
bash hung until I rebooted.

* Your Windows build number
062316

**Comment by slugmuffin** [comment] 2017-03-09 21:54
I tried it again without worrying about svn and it still an issue:

**Steps to reproduce:**
`user@host:/mnt/c/work$ mkdir test`
`user@host:/mnt/c/work$ mv test/ newtest`

**Comment by jackchammons** [comment] 2017-03-09 21:56
Could you confirm your build number? Using CMD execute the `ver` command.

**Comment by slugmuffin** [comment] 2017-03-09 21:57
Sorry, previous version was read from wrong place.

Microsoft Windows [Version 10.0.14393]

**Comment by sunilmut** [comment] 2017-03-09 21:57
@slugmuffin - Thanks for your post. Does it look like a duplicate of #765? Unfortunately, the fix for #765 is not yet available to retail builds (but only on Insider builds). But, worry not, it will be soon available in the "Creators Update" release. Or, if you are willing, you can move to the Insider build.

**Comment by slugmuffin** [comment] 2017-03-09 22:03
Thanks, this looks like it's a duplicate - I did search, didn't see that for some reason.

**Comment by sunilmut** [comment] 2017-03-09 22:34
@slugmuffin - Thanks for confirming. "Creators" build should be soon out. Hang in there and please keep the feedback coming.

**Closed by sunilmut** 2017-03-09 22:34 UTC
Labels: duplicate
