### ISSUE TITLE
mv sometimes hangs all bash processes (need to reboot)

### ISSUE THREAD

**Issue by capisce** [Microsoft/BashOnWindows#2129] opened 2017-05-18 18:01 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.14393]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

sudo apt-get install git
git clone https://github.com/npm/npm.git
mkdir test
mv npm test
mv test/npm/ .

* What's wrong / what should be happening instead:

All active bash processes hang and it's not possible to start new ones.

The problem only happens when including the trailing slash in the mv command. Without the trailing slash things work as expected:

mv test/npm .

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment] 2017-05-18 18:20
#1008, but larger question is, why are so many people stuck on Anniversary?

**Comment by fpqc** [comment] 2017-05-18 20:48
@therealkenc idk some machines haven't had it rolled out yet.

**Comment by benhillis** [comment] 2017-05-18 23:35
Closing as a duplicate of #1008.

**Closed by benhillis** 2017-05-18 23:35 UTC
