### ISSUE TITLE
Launching bash from a Windows program which was started from bash fails (with an incorrectly formatted error)

### ISSUE THREAD

**Issue by CherryDT** [Microsoft/BashOnWindows#2023] opened 2017-04-27 12:53 UTC
I have build 15063.138.

Steps to reproduce:
* Open bash.
* Start cmd.exe.
* Start bash (or try starting a linux tool using `bash -c something`).
Or, alternatively, run `cmd.exe /c bash` in bash.

Expected result: bash starts cmd, cmd starts another bash. (Should continue as deeply as I want.)

Actual result: The second bash doesn't start, but instead displays an error, which is even formatted incorrectly (see #2024). The text in the screenshot below would (after fixing the missing umlauts) translate as "The process is not supported. Press any key to continue.".

It is the same when just running `bash.exe` from within bash.

![image](https://cloud.githubusercontent.com/assets/6010463/25483998/6b850b9c-2b58-11e7-8197-054cd8324080.png)

Running `lxrun /update` gives an also incorrectly formatted "Searching updates..." but then exits without further action.

**Comment by zadjii-msft** [comment] 2017-04-27 16:23
Launching bash.exe using interop from inside WSL isn't a supported scenario at the time. 

@jackchammons can provide details.

**Comment by therealkenc** [comment] 2017-04-30 19:01
#1228

**Comment by benhillis** [comment] 2017-05-05 16:52
Marking as a duplicate of #1228.

**Closed by benhillis** 2017-05-05 16:52 UTC
Labels: interop
