### ISSUE TITLE
Socket error when using memcached as php session storage with session data over 8112 bytes

### ISSUE THREAD

**Issue by heldchen** [Microsoft/BashOnWindows#2351] opened 2017-07-18 08:12 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
16241

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
```
sudo apt-get install php7.1-cli php-memcached memcached
sudo service memcached start
php -d 'session.save_handler=memcached' -d 'session.save_path=127.0.0.1' -r 'session_start(); 
$_SESSION["test"]=str_repeat("1", 8113); session_write_close();
``` 
* What's wrong / what should be happening instead:
upon closing the session, an error is thrown in libmemcached/io.cc and no session data stored:
```
Warning: Unknown: error saving session to memcached: (0x7fc6e54a9000) INVALID ARGUMENTS(Invalid argument), host: 127.0.0.1:11211 -> libmemcached/io.cc:392 in Unknown on line 0

Warning: Unknown: Failed to write session data (memcached). Please verify that the current setting of session.save_path is correct (127.0.0.1:11211) in Unknown on line 0
```
the libmemcached used by php-memcached is 1.0.18. according to its source code, it seems to be a socket error happening when writing to the socket: https://github.com/arthurnn/memcached/blob/master/vendor/libmemcached-1.0.18/libmemcached/io.cc#L329
the threshold in the above commandline example is 8112 bytes, everything larger results in the error.

the exact same configuration including the exact same package and dependencies versions works fine in a VMWare Worstation Pro vm. using `session.save_handler = file` works fine in WSL.

**Comment by heldchen** [comment] 2017-07-18 08:38
the session key name also takes up some bytes, so the mentioned 8112 bytes is not the exact upper limit at which it fails. it seems to relate to the entire session array size, as this will also fail:
`php -d "session.save_handler=memcached" -d "session.save_path=127.0.0.1" -r 'session_start(); for($i=0; $i < 916; $i++) $_SESSION["t".$i]=1; session_write_close();'`

**Comment by heldchen** [comment] 2017-07-18 08:49
memcached in `-vvv` mode does not report any errors when writing the large session data:
```
> FOUND KEY memc.sess.lock.1j27brffvqfci5mlnufq68j8qs
>31 Writing bin response:
>31   0x81 0x04 0x00 0x00
>31   0x00 0x00 0x00 0x00
>31   0x00 0x00 0x00 0x00
>31   0x00 0x05 0x00 0x00
>31   0x00 0x00 0x00 0x00
>31   0x00 0x00 0x00 0x00
31: going from conn_nread to conn_mwrite
31: going from conn_mwrite to conn_new_cmd
31: going from conn_new_cmd to conn_waiting
31: going from conn_waiting to conn_read
31: going from conn_read to conn_parse_cmd
<31 Read binary protocol data:
<31    0x80 0x07 0x00 0x00
<31    0x00 0x00 0x00 0x00
<31    0x00 0x00 0x00 0x00
<31    0x00 0x06 0x00 0x00
<31    0x00 0x00 0x00 0x00
<31    0x00 0x00 0x00 0x00
>31 Writing bin response:
>31   0x81 0x07 0x00 0x00
>31   0x00 0x00 0x00 0x00
>31   0x00 0x00 0x00 0x00
>31   0x00 0x06 0x00 0x00
>31   0x00 0x00 0x00 0x00
>31   0x00 0x00 0x00 0x00
31: going from conn_parse_cmd to conn_mwrite
31: going from conn_mwrite to conn_closing
<31 connection closed.
31: going from conn_closing to conn_closed
```

**Comment by heldchen** [comment] 2017-07-18 08:55
the same error happens when using an external memcached service (i.e. one from a different non-wsl machine) from within wsl. so I'm not sure what more to test from here on, open to suggestions.

**Comment by therealkenc** [comment] 2017-07-18 15:05
Do:
```
strace -ff php -d 'session.save_handler=memcached' -d 'session.save_path=127.0.0.1' -r 'session_start(); 
$_SESSION["test"]=str_repeat("1", 8113); session_write_close();' 2> php.strace
```
...or similar. Then post a link to a gist of the output. If you can use an external `memcached` on Real Linux that is even better because that will remove a variable, though it sounds from your description that the problem is with the client. It could be both of course, but we can cross that bridge after looking at the client.

Since we know the error you can probably even just do a `grep EINVAL` on the `strace` output and skip the middle man.

**Comment by heldchen** [comment] 2017-07-18 15:17
`sendto(4, "\200\1\0$\10\0\0\0\0\0\37\354\0\4\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\5\240"..., 8196, MSG_NOSIGNAL|MSG_MORE, NULL, 0) = -1 EINVAL (Invalid argument)`

https://gist.github.com/heldchen/7bc8ec3c9ca57309bb12f6fa4d829152

**Comment by heldchen** [comment] 2017-07-18 15:32
so it is the `MSG_MORE` parameter of `sendto`. with smaller session sizes, only `MSG_NOSIGNAL` is used.

**Comment by therealkenc** [comment] 2017-07-18 17:42
Interestingly `MSG_NOSIGNAL|MSG_MORE` does take with `sendmmsg()`, at least in some scenarios. Saw it just last week [here](https://github.com/Microsoft/BashOnWindows/issues/2314#issuecomment-314611205). So I speculate is the "`..., NULL, 0`" not the flags. Could be wrong. Thanks for the follow-up.

**Comment by heldchen** [comment] 2017-07-18 20:01
I see. thanks for your analysis. if anything more is needed to be tested, I'm willing to invest some time to get this fixed eventually.

**Comment by sunilmut** [comment] 2017-07-18 22:45
@heldchen - Thanks for the post and the traces. I can confirm that `MSG_MORE` is currently not implemented/supported in WSL.

@therealkenc - Good eyes! Interesting correlation :). You may also find it interesting to know that WSL ignores the `msg_flags` fields in the `msghdr` as per the [man page](http://man7.org/linux/man-pages/man2/sendmsg.2.html). See comment about `/* flags (unused) */` and `The msg_flags field is ignored` (which is why it is working in the other case). But, in this case, `MSG_MORE` is sent directly in `sendto`. I am curious to see if Linux also ignores the `msg_flags` field in `msghdr` as it says in the man page.

Also, the other interesting question here is, what will be the impact (compat) of ignoring `MSG_MORE` flag? I am less concerned about stream based connection-oriented sockets, as is this case here. But, more concerned about compat on UDP sockets.
Stubbing it out might unblock the scenario in this case though. Time to do some experiments :)

**Comment by sunilmut** [comment] 2017-07-18 22:47
It's also funny that Java is sending so many flags under `msg_flags` :)

**Comment by sunilmut** [comment] 2017-07-19 18:03
@heldchen - I stubbed `MSG_MORE` in WSL for TCP and it seemed to have unblocked this particular scenario. I am not very comfortable stubbing it for UDP. But, I will try to get this change in. 

Note that on WSL, you will have to explicitly start the `memcached` service because WSL does not yet support auto-start of services.

```
root@:~# /etc/init.d/memcached start
Starting memcached: memcached.
root@:~# /etc/init.d/memcached status
 * memcached is running
root@:~# php -d 'session.save_handler=memcached' -d 'session.save_path=127.0.0.1' -r 'session_start(); $_SESSION["test"]=str_repeat("1", 8113); session_write_close();'
root@:~#
```

**Comment by heldchen** [comment] 2017-07-19 18:06
awesome, thanks @sunilmut, looking forward to a future build :-)

**Comment by sunilmut** [comment] 2017-07-19 21:18
The PR has been merged with the dev branch and should be out in sometime to the Insider build and eventually also to the Fall Creators Update.

**Comment by heldchen** [comment] 2017-07-19 21:24
this is amazing, thanks again for taking the time to look into the problem and the quick fix!

**Comment by heldchen** [comment] 2017-08-03 02:03
this seems to have made it into build 16257 - I cannot repo the error anymore. thanks @sunilmut

**Comment by sunilmut** [comment] 2017-08-03 02:12
@heldchen - Great! Thanks for the confirmation.

**Closed by sunilmut** 2017-08-03 02:12 UTC
Labels: fixedininsiderbuilds, network
