### ISSUE TITLE
Unable to get angular-cli working

### ISSUE THREAD

**Issue by caiusCitiriga** [Microsoft/BashOnWindows#1522] opened 2016-12-20 08:39 UTC
Installing node with the following commands:
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

And angular-cli with this command:
`npm install -g angular-cli`

I was expecting to see the ng cli help list with the following command:
`ng help`

The actual result instead is this:
```
EINVAL: invalid argument, uv_interface_addresses
Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at /usr/lib/node_modules/angular-cli/node_modules/portfinder/lib/portfinder.js:395:23
    at Object.<anonymous> (/usr/lib/node_modules/angular-cli/node_modules/portfinder/lib/portfinder.js:410:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/angular-cli/commands/serve.js:6:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Class.includedCommands (/usr/lib/node_modules/angular-cli/addon/index.js:22:16)
    at /usr/lib/node_modules/angular-cli/angular-cli/lib/models/project.js:392:61
    at Array.forEach (native)
    at Project.addonCommands (/usr/lib/node_modules/angular-cli/angular-cli/lib/models/project.js:391:15)
    at Project.eachAddonCommand (/usr/lib/node_modules/angular-cli/angular-cli/lib/models/project.js:426:30)
    at module.exports (/usr/lib/node_modules/angular-cli/angular-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/usr/lib/node_modules/angular-cli/angular-cli/lib/cli/cli.js:34:26)
    at tryCatch (/usr/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/usr/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/usr/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/usr/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

My OS is Windows 10 and the build is the 14393 

To reproduce the error from a brand new installation you can use the following commands:
```
sudo apt-get install npm

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

sudo apt-get install -y nodejs

npm install -g angular-cli

ng help
```

Hope you guys can help me!
Thanks

**Comment by aseering** [comment] 2016-12-20 15:09
Hi @caiusCitiriga -- thanks for reporting this!  Would you be willing to try an [Insider build](https://insider.windows.com/) of Windows?  This issue, along with a lot of other issues, no longer reproduces for me on the latest Fast-ring Insider build.

**Comment by caiusCitiriga** [comment] 2016-12-20 16:10
Hi @aseering! Thanks for the reply. Are these builds stable? I'm using the company PC to develop on and I wouldn't like to encounter crashes or other problems that could lose my work. Otherwise can this be fixed with an update of the SO from the update manager? I'm currently on a Windows 10 Enterprise edition.

**Comment by benhillis** [comment] 2016-12-20 16:15
@caiusCitiriga - The Windows Insider builds are pretty stable but I wouldn't suggest using it on your primary work machine.  Another lower risk option is to create a Hyper-V VM and install the insider build there.

As @aseering mentioned this has been fixed for some time. Marking this as a duplicate of #972.

**Closed by benhillis** 2016-12-20 16:15 UTC

**Comment by caiusCitiriga** [comment] 2016-12-20 16:22
@benhillis thanks! I'll try the Hyper-V VM solution! ;)
