### ISSUE TITLE
Install not working after upgrade to 14361

### ISSUE THREAD

**Issue by N00byEdge** [Microsoft/BashOnWindows#538] opened 2016-06-15 23:14 UTC
I went and upgraded to build 14361, now there is a bash process running at 100% CPU usage on one of my cores. I am unable to exit this process using any tools, and it can sit there for hours. It doesn't cause any disk/network activity, only CPU. I get the following error when attempting an uninstall:

```
C:\Users\N00byEdge>lxrun /uninstall /full /y
This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications, new applications, and user data.
Uninstalling...
Error: 0x80080005
```

The error takes about a minute until it appears. This install was very unstable on the last build, but it was at least working. No modifications made to the install, and Windows is running on a real PC, no VM.

**Comment by N00byEdge** [comment] 2016-06-15 23:16
I just realized there is a new preview build. I'm installing it as I write this, and will report back if that fixed it.

**Comment by benhillis** [comment] 2016-06-16 00:41
Thanks for reporting this, I'll be curious to see if this issue goes away when you upgrade.

**Comment by N00byEdge** [comment] 2016-06-16 08:35
The issue persists. The only difference it that I can no longer ctrl+c a cmd trying to start Bash. What error info do you want me to collect?

**Comment by N00byEdge** [comment] 2016-06-16 08:37
I of course tried to uninstall the feature and install it again (and yes, it was uninstalled after the first reboot), but it still wouldn't start. This makes me think that it's the Ubuntu install that is broken.

**Comment by N00byEdge** [comment] 2016-06-16 08:51
Wow, in the latest build the Bash process was not running on startup(which it was on the last build), which enabled me to do the uninstall. The uninstall is still unresponsive after the bash process has been opened.

However, it still seems like the issue is there. Maybe it's hardware related? [Screenshot](http://puu.sh/puCrn.png)

**Comment by benhillis** [comment] 2016-06-16 15:30
Did your install eventually succeed?  We do launch some commands as part of post install, I suspect that's what's happening in your screenshot.

There are instructions here how on collecting tracing information.  I would suggest uninstalling, rebooting, then starting the trace and running install.

Tracing instructions: https://github.com/Microsoft/BashOnWindows/issues/410#issuecomment-221463487

**Comment by N00byEdge** [comment] 2016-06-16 15:59
@benhillis I didn't quit the process after taking that screenshot and all, but as I am writing this, the process is still running. I think that we should call a 7 hour wait good enough, right? I'll go ahead and follow those instructions.

**Comment by N00byEdge** [comment] 2016-06-17 21:41
Is there an update to this issue? The files that were collected were very small, and I do not know if it was even able to start. Anyways, at that state it just sits there and babysits one of my cores at all times. It has started running at startup again. If you want to look at this through TeamViewer or something, I could possibly arrange that.

**Comment by benhillis** [comment] 2016-06-17 21:48
I got your traces but, as you mention, they are quite small and there aren't any useful breadcrumbs in them.  Above you mention reinstalling the feature, did you do that via the "Turn Windows features on or off" page or by the below commands?

```
lxrun.exe /uninstall /full
lxrun.exe /install
```

If you haven't already, I'd suggest this.  Reboot, then run the above commands.

**Comment by N00byEdge** [comment] 2016-06-18 08:27
@benhillis That's exactly what I did before running the capture. It must be that it never even successfully starts, then.

**Comment by N00byEdge** [comment] 2016-06-21 15:57
That means I did that before sending the files.

**Comment by N00byEdge** [comment] 2016-06-22 10:26
Issue still present on 14367

**Comment by benhillis** [comment] 2016-06-22 15:20
This sounds very similar to #358.  @N00byEdge by chance was this an upgrade from an earlier version of Windows (not an earlier Windows 10 Insider flight, like the release version of Windows 10).

The following information would be useful to help me try to repro this:

1. Which Windows build number are you running?
2. What Windows locale is your install?
3. What is your Windows username?
4. Any other configuration differences you can think of from a fresh Windows install.

**Comment by N00byEdge** [comment] 2016-06-22 22:16
1. Build 14367
2. sv;Swedish
3. Orion\n00byedge, local user. Computer is on a domain.
4. Upgraded from W7 -> W10 Release -> W10 IP

**Comment by N00byEdge** [comment] 2016-06-22 22:19
I tried doing the same thing with a domain user with only letters in the username, same issue.

**Comment by benhillis** [comment] 2016-06-22 22:26
Thanks for the info, I will try to reproduce this.

**Comment by benhillis** [comment] 2016-06-22 23:31
@N00byEdge To confirm, you're using the en-US version of Windows not sv-SE?  Originally you said you were using Swedish so that's what I installed.

**Comment by N00byEdge** [comment] 2016-06-23 06:25
Sorry, maybe I should have typed out this in the last post. I have English language with Swedish input, and a Swedish language pack for spelling and hand writing, but I am using English as Windows and UI language:
CurrentCulture   : sv-SE
CurrentUICulture : en-US
from Get-Host in powersell

**Comment by benhillis** [comment] 2016-06-28 20:42
Unfortunately I'm still unable to reproduce this locally.  If you would be able to take a sample profile trace so we can identify where /bin/bash is getting stuck that'd be very useful.  I have instructions in another thread: https://github.com/Microsoft/BashOnWindows/issues/358#issuecomment-229176401

Let me know if you have any questions.

**Comment by N00byEdge** [comment] 2016-06-28 22:54
I'm getting the following error:
```
C:\Users\N00byEdge>xperf.exe -on PROC_THREAD+LOADER+INTERRUPT+DPC+PROFILE -stackwalk profile -minbuffers 16 -maxbuffers 1024 -flushtimer 0 -f tmp.etl
xperf: error: NT Kernel Logger: Invalid flags. (0x3ec).
```

**Comment by N00byEdge** [comment] 2016-06-28 22:56
```
C:\WINDOWS\system32>xperf.exe -on PROC_THREAD+LOADER+INTERRUPT+DPC+PROFILE -stackwalk profile -minbuffers 16 -maxbuffers 1024 -flushtimer 0 -f tmp.etl
xperf: error: NT Kernel Logger: Cannot create a file when that file already exists. (0xb7).
```

There is not a single `tmp.etl` on my system. What should I look for?

**Comment by N00byEdge** [comment] 2016-06-28 22:59
I don't know if it's worth mentioning, but when it was running, I was getting #143.

**Comment by benhillis** [comment] 2016-06-28 23:01
@N00byEdge The above error means you're already collecting a trace, use `xperf.exe -d profile.etl ` to stop.

**Comment by N00byEdge** [comment] 2016-06-28 23:02
That did not work.
```
C:\WINDOWS\system32>xperf.exe -d profile.etl
xperf: error: Merge ETL: The system cannot find the path specified. (0x3).

C:\WINDOWS\system32>xperf.exe -on PROC_THREAD+LOADER+INTERRUPT+DPC+PROFILE -stackwalk profile -minbuffers 16 -maxbuffers 1024 -flushtimer 0 -f tmp.etl
xperf: error: NT Kernel Logger: Cannot create a file when that file already exists. (0xb7).
```

**Comment by benhillis** [comment] 2016-06-28 23:09
This is probably because you're running out of System32.  Can you change to a different directory like your desktop?

**Comment by N00byEdge** [comment] 2016-06-28 23:12
```
F:\>mkdir dmp

F:\>cd dmp

F:\dmp>xperf.exe -on PROC_THREAD+LOADER+INTERRUPT+DPC+PROFILE -stackwalk profile -minbuffers 16 -maxbuffers 1024 -flushtimer 0 -f tmp.etl
xperf: error: NT Kernel Logger: Cannot create a file when that file already exists. (0xb7).

F:\dmp>xperf.exe -d profile.etl
xperf: error: Merge ETL: The system cannot find the path specified. (0x3).

F:\dmp>mkdir C:\Users\N00byEdge\Desktop\dmp

F:\dmp>cd /d C:\Users\N00byEdge\Desktop\dmp

C:\Users\N00byEdge\Desktop\dmp>xperf.exe -on PROC_THREAD+LOADER+INTERRUPT+DPC+PROFILE -stackwalk profile -minbuffers 16 -maxbuffers 1024 -flushtimer 0 -f tmp.etl
xperf: error: NT Kernel Logger: Cannot create a file when that file already exists. (0xb7).

C:\Users\N00byEdge\Desktop\dmp>xperf.exe -d profile.etl
xperf: error: Merge ETL: The system cannot find the path specified. (0x3).
```

**Comment by benhillis** [comment] 2016-06-28 23:16
And you're running this in an Admin command prompt?

Can you run "which xperf.exe"?

**Comment by N00byEdge** [comment] 2016-06-28 23:17
Yes.
```
C:\WINDOWS\system32>which xperf.exe
'which' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by benhillis** [comment] 2016-06-28 23:17
Sorry I mean "where xperf.exe".  Linux is creeping into my world :)

**Comment by N00byEdge** [comment] 2016-06-28 23:18
Ah, thought so.
```
C:\WINDOWS\system32>where xperf.exe
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\xperf.exe
```
I don't know what kind of voodoo magic you are working, though.

**Comment by N00byEdge** [comment] 2016-06-28 23:20
Huh, that's interesting. I literally uninstalled the Windows 10 kit when I installed the W8.1 kit you requested me to install. Will retry install.

**Comment by benhillis** [comment] 2016-06-28 23:21
That is odd, the Windows 10 version of xperf should work as well...

C:\Users\benhill>which xperf.exe
C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\xperf.exe

**Comment by N00byEdge** [comment] 2016-06-28 23:22
Samme issue.
```
C:\WINDOWS\system32>"C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\xperf.exe" xperf.exe -d profile.etl
xperf: error: xperf.exe: The parameter is incorrect. (0x80070057).

C:\WINDOWS\system32>"C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\xperf.exe" -d profile.etl
xperf: error: Merge ETL: The system cannot find the path specified. (0x3).
```

**Comment by benhillis** [comment] 2016-06-28 23:24
Maybe try rebooting?  Xperf might have gotten in a funny state.  After you reboot run the below from an admin command prompt:

`xperf.exe -on PROC_THREAD+LOADER+INTERRUPT+DPC+PROFILE -stackwalk profile -minbuffers 16 -maxbuffers 1024 -flushtimer 0`

**Comment by N00byEdge** [comment] 2016-06-28 23:26
Okay, be right back!

**Comment by N00byEdge** [comment] 2016-06-28 23:29
Still facing the same issue:
```
C:\WINDOWS\system32>xperf.exe -on PROC_THREAD+LOADER+INTERRUPT+DPC+PROFILE -stackwalk profile -minbuffers 16 -maxbuffers 1024 -flushtimer 0

C:\WINDOWS\system32>cd /d C:\Users\N00byEdge\Desktop\dmp

C:\Users\N00byEdge\Desktop\dmp>"C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\xperf.exe" xperf.exe -d profile.etl
xperf: error: xperf.exe: The parameter is incorrect. (0x80070057).
```

**Comment by N00byEdge** [comment] 2016-06-28 23:33
Also;
`C:\Users\N00byEdge\Desktop\dmp>"C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\xperf.exe" -on PROC_THREAD+LOADER+INTERRUPT+DPC+PROFILE -stackwalk profile -minbuffers 16 -maxbuffers 1024 -flushtimer 0`

**Comment by benhillis** [comment] 2016-06-28 23:33
Your second command is incorrect, you're running"xperf.exe xperf.exe -d profile.etl"

**Comment by N00byEdge** [comment] 2016-06-28 23:35
Oh man, that was awkward. And stupid.
```
C:\Users\N00byEdge\Desktop\dmp>xperf.exe -on PROC_THREAD+LOADER+INTERRUPT+DPC+PROFILE -stackwalk profile -minbuffers 16 -maxbuffers 1024 -flushtimer 0 -f tmp.etl

C:\Users\N00byEdge\Desktop\dmp>bash.exe
```
Gonna let this run for a bit.

**Comment by N00byEdge** [comment] 2016-06-28 23:36
Also; should I ctrl + c the bash.exe or let it run when I stop the trace?

**Comment by benhillis** [comment] 2016-06-28 23:37
Leave it running, you can close it after you stop the trace.

**Comment by N00byEdge** [comment] 2016-06-28 23:40
Yeah, nevermind. Just realized I can't stop Bash.exe without reboot. File size:
```
2016-06-29  01:38       124 911 616 profile.etl
```
Mail is coming. Let's hope something comes out of this.

**Comment by N00byEdge** [comment] 2016-06-28 23:47
Mail is sent. My web server didn't like my 121 MB file, so I uploaded it and shared a link. Hope that's not an issue.

**Comment by benhillis** [comment] 2016-06-28 23:49
Nope that's perfect.  Thank you very much, I hope this sheds some light on the issue!

**Comment by N00byEdge** [comment] 2016-06-29 10:45
Just caught this little guy in the corner of my eye in the taskbar all of a sudden for the first time since my issues started: http://puu.sh/pK5S7.png

It's frozen, I don't know how long it has been for, but at least a couple of minutes after finding it.

**Comment by N00byEdge** [comment] 2016-06-29 10:46
Now Bash.exe gives this:
```
C:\Users\N00byEdge>bash
Cannot launch bash because the LX subsystem has an install, uninstall, or servicing operation pending.
```
Do I reinstall at this point?

**Comment by benhillis** [comment] 2016-06-29 13:56
Just close that update window.

**Comment by N00byEdge** [comment] 2016-06-29 13:58
Yeah, I did.

**Comment by benhillis** [comment] 2016-06-29 17:34
I received your trace and I've identified what's getting hung.  I'd like to try to get a repro locally so I can validate my fix.  Out of curiosity do you not have a page file on your system?

You can check this via:
`Advanced system settings -> Advanced tab -> Performance Settings -> Advanced tab -> Virtual memory Change`

**Comment by N00byEdge** [comment] 2016-06-29 17:35
I have a page file, but not on my main drive, my ssd raid. I had one on there though up until about 4 days ago.

**Comment by N00byEdge** [comment] 2016-06-29 17:36
Here is a screenshot: http://puu.sh/pKqEC.png

**Comment by benhillis** [comment] 2016-06-29 17:38
Ok but you do have multiple page files.  I think I see what the issue is let me confirm my hypothesis.

**Comment by benhillis** [comment] 2016-06-29 18:42
@N00byEdge Thank you very much for your patience and persistence.  I would not have been able to figure this out without your help!

Because of your trace file I have identified a bug in the code that is calculating the swap file size.  This function is used by both the sysinfo system call and generating the contents of /proc/meminfo.  This problem will happen when you have multiple pagefiles on your machine.  There are three different outcomes that can happen as a result of this bug:

1. The swapfile size will be reported incorrectly
2. Our driver will dereference an invalid memory address and cause a bluescreen
3. The machine will enter an infinite loop when calculating the swap file size (this is the one you are seeing)

As a temporary workaround if you remove all but one of your pagefiles you should be able to use WSL. I am coding up a fix for this right now.

**Comment by N00byEdge** [comment] 2016-06-29 19:38
Thanks, I love WSL and will temprarely disable all but one pagefile and come back with my results. Also, will you report back when this is fixed (will it be in the next build)?

**Comment by N00byEdge** [comment] 2016-06-29 19:43
I can confirm that WSL yet again works with a single swapfile! Thanks for all the persistence and help!
```
C:\Users\N00byEdge>bash
root@ORION:/mnt/c/Users/N00byEdge#
```

**Comment by benhillis** [comment] 2016-06-29 19:49
Great to heart, I'm going to reopen this thread until the issue is fixed in an insider build but I will tag the thread with "workaround available"

**Comment by N00byEdge** [comment] 2016-06-29 20:01
Okay, fair enough.

**Comment by CryptXor** [comment] 2016-08-12 07:44
+1 to the install, update, upgrade/etc/etc not working. Running under sudo su
```
root@MSI:/home/DarkSt0rm# apt-get update
Err http://security.ubuntu.com trusty-security InRelease

Err http://archive.ubuntu.com trusty InRelease

Err http://archive.ubuntu.com trusty-updates InRelease

Err http://security.ubuntu.com trusty-security Release.gpg
  Could not resolve 'security.ubuntu.com'
Err http://archive.ubuntu.com trusty Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
Reading package lists... Done
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/InRelease

W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'security.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Some index files failed to download. They have been ignored, or old ones used instead.
```

My firewall is not blocking anything because I tried with everything disabled as well. Yesterday I could ping `http://archive.ubuntu.com` from the powershell but not winbash and now neither works. Error with conical?

**Comment by N00byEdge** [comment] 2016-08-14 14:21
@CryptXor Wait, doesn't that imply that the install worked for you? Are you sure this is the correct issue?

**Comment by ReginaldShao** [comment] 2016-10-16 05:43
i solved the problem by disable the function,restart computer and enable the function again.
then,when i run bash command,it worked!
![1](https://cloud.githubusercontent.com/assets/13191006/19415570/94087daa-93a6-11e6-958c-a2305d3e09eb.PNG)

**Comment by vitordouzi** [comment] 2017-03-15 00:17
In my case, any mv or cp command was blocked by the windows firewall. When I cancel one of this command, the problem with the uninstall happens. Try to disable the firewall, reboot the windows and run the uninstall. That work with me.

**Closed** 2017-07-12 19:16 UTC
Labels: fixedincreatorsupdate
