### ISSUE TITLE
Running a Linux-32 bit custom application with WSL

### ISSUE THREAD

**Issue by Danielecker** [Microsoft/BashOnWindows#1360] opened 2016-11-14 10:58 UTC
Hello everyone. 
I'm trying to run a personal application, created and compiled in Linux-environment on WSL. Now, the application was compiled on a 32 bit, i386 architecture. I've already done all the classical passages, that is:

`sudo dpkg --add-architecture i386`
`sudo apt-get update`
`sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386`

But the application still not works, launching the error:

`-bash: ./myapplication: cannot execute binary file: exec format error`

Here is the file information:

`ELF 32-bit LSB  executable, Intel 80386, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=21b824bc67b72519dfe6cde72378508fd0892163, not stripped`

I was wondering if this error is related to WSL itslef, by taking into account that I've managed to install a Window server (vcXsrv) and solved some D-Bus issues (by telling it to use TCP instead), or am I missing something in the configuration or in the application that I've created. I' ll post you also the output of the command:

`uname -a`
`Linux DESKTOP-41BP67O 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013 x86_64 x86_64 x86_64 GNU/Linux`

Now, I know that WSL is not supposed to be used in this way, and that I could simply run a Virtual Machine, avoiding lots of headaches, but I need to get this work. Sorry for bad english, and thanks in advance for your help.

**Comment by iz0eyj** [comment] 2016-11-14 12:59
I think because WSL only executes ELF-64.

WSL execution is better tha a VM, because it geives a solid and modern kernel to the open source community.

I'm sorry because my english is worst than yours :)

**Comment by fpqc** [comment] 2016-11-14 15:41
Yeah, if you could rebuild your executable for 64-bit it should work.

**Comment by benhillis** [comment] 2016-11-14 16:12
Thanks for reporting, marking this as a duplicate of #390.

**Closed by benhillis** 2016-11-14 16:12 UTC
