### ISSUE TITLE
env command incorrectly picks directories over executables appearing later in the PATH

### ISSUE THREAD

**Issue by cshei** [Microsoft/BashOnWindows#961] opened 2016-08-22 00:39 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description

The env command incorrectly picks directories over executables appearing later in the PATH.  I ran into this while running the TypeScript compiler after installing Emscripten, which puts a directory on the path that contains a "node" directory at the beginning of the PATH.  tsc has a "#!/usr/bin/env node", which then incorrectly picks up the node directory instead of the node executable, which appears in a directory later in PATH.
- Expected results

"env ls" should run the ls command, even if there is a directory named "ls" in a directory that appears earlier in the PATH.  This works as expected on a real Ubuntu 14.04 install.
- Actual results (with terminal output if applicable)

$ env ls
env: ls: Is a directory
- Your Windows build number

10.0.14393
- Steps / commands required to reproduce the error

$ cd
$ mkdir ls
$ export PATH=$HOME:$PATH
$ env ls
env: ls: Is a directory
- Strace of the failing command

https://gist.github.com/anonymous/0a3592cea23d861296451e9ea5467f19
- Required packages and commands to install

None.

**Comment by therealkenc** [comment] 2016-08-22 02:21
Difference appears to be native returns `EACCES` while WSL returns `EISDIR` on `execve("/home/me/ls", ...)`. Sure enough, the man page for [execvp(3)](http://linux.die.net/man/3/execvp) says it only keeps searching the path on `EACCES`. The `EISDIR` causes glibc to quit on the first try. Chalk this one up to "weird POSIX behavior" I guess. If you asked me twenty minutes ago, I would have assumed `execvp(3)` would keep trying the path on `EACCES`, `EISDIR`, `lp0 on fire`, whatever, until it ran out of places to look.

**Comment by SRGOM** [comment] 2016-08-22 06:56
This bites you specially if you have a git repo in which there are folders named ssh and vim. The result would be that when you try to commit, git tries to open vim (your `EDITOR`) and fails to because it's a directory. So you do a `git commit -m "..."`. Then you try to push your changes using ssh prootcol. git tries to start ssh but fails because it's a directory.

**Comment by russalex** [comment] 2016-08-24 21:46
Great catch.  Thanks.

I was able to reproduce this on build 14393 (thanks for the easy to follow steps).  I was not able to reproduce this on build 14905.  Any chance you could try this on the most recent insider build?

**Comment by cshei** [comment] 2016-08-25 03:03
I ran into error 0x80040154 after upgrading to build 14905, and after turning the feature back on, ran into error 0x80070091.  After deleting %localappdata%\lxss and starting over, I'm still able to reproduce this on build 14905.  Strace still shows:

execve("/home/cshei/ls", ["ls"], [/* 16 vars */]) = -1 EISDIR (Is a directory)

**Comment by russalex** [comment] 2016-08-26 20:30
Interesting.  Filing a bug on this one since you're still hitting it.

Thanks again for finding this one.

**Comment by therealkenc** [comment] 2016-08-26 23:25
Confirmed `EISDIR` here too on 14905 using:

`strace -f env ls 2> ls.strace`

**Comment by stehufntdev** [comment] 2016-10-12 21:22
Thanks for reporting the issue, a fix for this should be out in insider builds soon.

**Comment by russalex** [comment] 2016-11-16 22:00
Going through and looking at some of the old bugs.  The fix here looks to have gone out a while ago.  Marking this one as fixed.

**Closed** 2016-12-05 22:14 UTC
Labels: bug, fixed
