### ISSUE TITLE
du shows inaccurate estimates of disk usage

### ISSUE THREAD

**Issue by ty274** [Microsoft/BashOnWindows#2400] opened 2017-08-08 08:56 UTC
Cygwin (correct)
![image](https://user-images.githubusercontent.com/8159197/29063783-d41fd640-7bdb-11e7-8443-668ebaaac8cc.png)

BashOnWindows - Microsoft Windows [Version 10.0.15063]
![image](https://user-images.githubusercontent.com/8159197/29063820-f086e5e4-7bdb-11e7-9b49-b3fc8062f982.png)

Thanks

**Comment by benhillis** [comment] 2017-08-08 15:14
Marking as a duplicate of #2347 and #1894.

**Closed by benhillis** 2017-08-08 15:14 UTC
Labels: duplicate
