### ISSUE TITLE
emacsclient (+ tmux + zsh) = hung processes

### ISSUE THREAD

**Issue by glenstarchman** [Microsoft/BashOnWindows#1127] opened 2016-09-26 14:06 UTC
- A brief description

This is a bit hard to pin down, but some combination of tmux + zsh + emacsclient results in a hung environment. There is also no way to kill the zombie processes without rebooting. 

It is possible to launch a new install of bash and run `top` to see running processes, but tools like `ps` just hang.

In the `top` output you will see (unkillable) processes for `emacs` and `zsh`. 

At this point the only solution is to reboot. 

Some notes:
- This only seems to happen with `emacsclient`
- It does not happen right away... I have been able to launch 5+ `emacsclient`s before this happens, but other times it occurs on the first launch
- Plain `bash` + `emacs` (not `emacsclient`) can also trigger this, although it is usually after an hour or so of work and I have yet to see this happen with build 14931
-  Build 14931 is an improvement as in earlier builds this would result in a BSOD instead of just hanging the `bash` process
- This happens in all combinations of: conhost, wsltty, conemu, and terminator exported via VcXsrv
- The only _seems_ to  happen with `emacs` or `emacsclient`... I have not been able to replicate this with `vim`
- Just noticed that in the `emacs` instance the error is: `[persp-mode] Error: Can not deactivate frame`. 
- This is nearly guaranteed when using `tmux` but may or may not occur without it.
- Ditto with zsh
- Your Windows build number
  14931

**Comment by glenstarchman** [comment] 2016-09-26 15:03
Some additional information... this may be somehow related to `ensime`.  I was just able to reproduce, but killing the `java` process behind `ensime-server` allowed me to launch `emacs` in a new bash instance.

**Comment by fpqc** [comment] 2016-09-26 16:15
@glenstarchman Yeah, I already demonstrated this with tmux and oh-my-zsh.  They're working on it.  I'm 99% sure that it involves the pty implementation.

**Comment by benhillis** [comment] 2016-09-26 16:21
@fpqc @glenstarchman  - We identified a locking issue in our pty code that has been resolved and will be in an Insider build soon.

**Comment by glenstarchman** [comment] 2016-09-26 16:22
Thanks, guys... my normal Linux setup is *so close* to working with WSL. Almost there.

**Comment by glenstarchman** [comment] 2016-09-29 15:44
With build 14936 general crashes of the above seem to have gone away. However, launching more than 1 instance of `emacsclient` within a single bash window will hang the entire system...  while normal `emacs` works just fine. For now a workaround is to launch `server-start` from within a *WINDOWS* emacs. Once that occurs you can launch as many `emacslient`s as you want from within  bash.

**Comment by fpqc** [comment] 2016-09-29 18:45
@glenstarchman Does it hang the system (I haven't seen this happen since Win9x) or does it bugcheck/bsod?  BSOD is a known issue in this build, says it on the changelog site.

**Comment by glenstarchman** [comment] 2016-10-02 14:40
I have narrowed this down even further. The culprit appears to be `spacemacs` and `emacsclient` in conjunction. Something in the way they are loading packages causes a hang in the terminal (eg, unresponsive in `cmd`, `mintty`, and `terminator`). Once this happens it is impossible to launch a `bash` instance again without a reboot. Digging deeper today.

**Comment by glenstarchman** [comment] 2016-10-02 14:43
@fpqc I should  have been more explicit. It hangs whatever terminal bash is running in. Once that happens the only way  to continue to use bash is a reboot. 

I have not received a single BSOD in this version, so that is very hopeful.

**Comment by fpqc** [comment] 2016-10-02 19:30
@glenstarchman Latest version?

**Comment by fpqc** [comment] 2016-10-02 20:00
@glenstarchman btw if you can submit a memdump to @russalex or @benhillis  It will probably be useful.

**Comment by glenstarchman** [comment] 2016-10-12 14:33
Update: No BSOD in latest build, but emacsclient still hangs the entire subsystem. I'll do some more digging later today.

**Comment by fpqc** [comment] 2016-10-12 17:10
@glenstarchman Same.  It no longer hangs rebooting my system, but it isn't fixed 

(with oh my zsh and tmux).

**Comment by glenstarchman** [comment] 2016-10-12 17:23
@fpqc I can actually duplicate this without tmux or oh-my-ssh. It is not always consistent, but launching one or more emacsclient instances (or even multiple emacs instances) will render the entire subsystem unusable. This is using vanilla bash in the normal console. 

Note: I have been able to replicate this with vanilla emacs, prelude, and spacemacs both with and without tmux and oh-my-zsh.  My current thought is that it has something to do with drawing multiple emacs frames. I noticed that the the Windows native emacs also seems to have some trouble with freezing from time to time and wonder if it is somehow related. I can use tmux, oh-my-zsh and multiple vim instances without any problem at all.

**Comment by fpqc** [comment] 2016-10-12 17:49
Happens wo emacs. It is ptys in general.

**Comment by arcanis** [comment] 2016-10-20 17:51
I haven't been able to reproduce this in the latest build (14946), have you?

**Comment by fpqc** [comment] 2016-10-20 18:01
I was.

**Comment by arcanis** [comment] 2016-10-20 18:09
Yeah just got it too when launching emacs .. maybe the fixinbound tag should be removed

**Comment by fpqc** [comment] 2016-10-20 19:17
@arcanis if you look at #1085 Russalex said it's fixed in their internal builds.

**Comment by glenstarchman** [comment] 2016-10-21 23:23
Not sure if this is helpful or not but in the latest build simply launching zsh can completely hang the bash process. Looking forward for the fix! I can work with not having zsh (painfully) but a hanging emacsclient is a deal breaker.

**Comment by russalex** [comment] 2016-10-21 23:37
I have not tested with emacsclient.  I have to admit I am not an emacs person.

Happy to repro this one myself if someone can give me the steps.  I want to make certain I am installing / running emacs the same way as everyone else.

The tmux + zsh one I did validate is fixed internally.

**Comment by glenstarchman** [comment] 2016-10-21 23:40
+1 on the tmux + zsh. My guess is that the fix for that will also fix the emacsclient issue. However, to attempt to duplicate do the following:

`emacs --daemon`
then launch a few `emacsclient -t [filename]` instances.

Sometimes it freezes at one but other times it takes a few different clients... but eventually it will completely freeze the bash process.

**Comment by russalex** [comment] 2016-10-22 18:56
I was never able to repro this.  A screen like this should freeze, correct?

![image](https://cloud.githubusercontent.com/assets/17343422/19621780/5409eb2e-984e-11e6-94fb-46ba49463581.png)


Tried on 14951 but really put it through it's paces on an internal build.  The screenshot is internal and has:

1) 32 emacsclient instances in 2 tmux windows (~/tmp/emacsclient -t foo)
2) A tmux window where I held down the return key for about 15 seconds

Other than the internal build, only thing special I can think of is I have a .tmux.conf of `set-option -g mouse on`.

**Comment by fpqc** [comment] 2016-10-22 18:59
@russalex I'll have you know that on a proper (non-Apple) keyboard, it is called an Enter key. =O!!!!

**Comment by glenstarchman** [comment] 2016-10-22 19:12
The latest build is *much* more stable and so far I have only experienced a freeze when closing an emacs window. Almost there!

**Comment by comzyh** [comment] 2016-11-04 08:59
Build 14959 seems solved this issue.

**Comment by glenstarchman** [comment] 2016-11-08 21:50
I have not seen this issue occur on build 14959, although on first run I got a BSOD using WSL on Mintty. Using a native Linux terminal exported via an xserver works just fine.

**Comment by fpqc** [comment] 2016-11-08 21:56
@glenstarchman If you can find the minidump (I couldn't when I had a bugcheck), try seeing if you can send it over to secure@microsoft.com (email them first and they will tell you how and where to put it).

**Comment by glenstarchman** [comment] 2016-11-15 15:47
I have been unable to duplicate any issues with 14965. There are a few random freezes and whatnot within Spacemacs, but I really think this has more to do with Spacemacs than the build.

**Comment by russalex** [comment] 2016-11-15 19:49
Thanks @glenstarchman.  I am going to go aheadand close this one out.

**Closed** 2016-11-15 19:50 UTC
Labels: fixed, fixinbound
