### ISSUE TITLE
All processes are terminated when last bash window closed

### ISSUE THREAD

**Issue by gczuczy** [Microsoft/BashOnWindows#1263] opened 2016-10-24 12:57 UTC
When the last Bash window is closed, all the linux processes are terminated, including daemons, like sshd, or ssh-agent. I think background processes should be kept alive across sessions.

Windows versions: Microsoft Windows [Version 10.0.14393]

Reproduction: launch ssh-agent, close all the bash windows, start a new one, look for the already started daemon.
OR: start sshd, ssh into the linux subsystem, close all bash windows, and your ssh session will terminate.

**Comment by fpqc** [comment] 2016-10-24 13:34
By design for now.  Once they open up the COM interface, you could probably program it to control an instance with something like a tray icon.

**Comment by stehufntdev** [comment] 2016-10-26 16:29
Thanks for reporting the issue. There's a few related posts on this so closing it out as a duplicate. Please see #834 and #1007 for more details.

**Closed by stehufntdev** 2016-10-26 16:29 UTC
