### ISSUE TITLE
where's my core file?

### ISSUE THREAD

**Issue by SailorBassman** [Microsoft/BashOnWindows#1468] opened 2016-12-07 15:11 UTC
I am trying to expand an array dynamically by malloc()ing a bigger one and copying / free()ing the original until I run out of input.  Sure enough, Murphy's Law for c programming holds and it it segfaults. 

Segmentation fault (core dumped)

But where is the coredump file in a WSL environment?  Not in my cwd, not in my $HOME.

I will step thru the executable w/gdb and get there eventually.  I just prefer to look at coredumps if they are available.

**Comment by fpqc** [comment] 2016-12-07 15:13
On real Linux, doesn't syslogd or journald actually take care of writing core dumps to disk?

**Comment by misenesi** [comment] 2016-12-07 19:56
We know about [this](https://github.com/Microsoft/BashOnWindows/issues/1262). Please use [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo) to help us prioritize this feature.

**Comment by stehufntdev** [comment] 2017-01-06 17:43
Closing this out as a duplicate of #1262 so we just have one post tracking the issue.

**Closed by stehufntdev** 2017-01-06 17:43 UTC
Labels: duplicate
