### ISSUE TITLE
Piping between two Win32 processes in Bash doesn't work

### ISSUE THREAD

**Issue by leojbgiusti** [Microsoft/BashOnWindows#1327] opened 2016-11-07 12:27 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
I tried executing "/mnt/c/Windows/System32/ipconfig.exe|/mnt/c/Windows/System32/clip.exe" and got back "INFO: Type "CLIP /?" for usage."

* Expected results
Nothing to be printed to the terminal and return straight to the prompt for a new command.

* Actual results (with terminal output if applicable)
"INFO: Type "CLIP /?" for usage."

* Your Windows build number
14959
* Steps / All commands required to reproduce the error from a brand new installation 
/mnt/c/Windows/System32/ipconfig.exe|/mnt/c/Windows/System32/clip.exe

* Strace of the failing command
None as this is an issue with Win32 interop
* Required packages and commands to install
None

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by benhillis** [comment] 2016-11-07 16:05
Duplicate of #1255

**Closed by benhillis** 2016-11-07 16:05 UTC
