### ISSUE TITLE
Bash caused windows blue screen

### ISSUE THREAD

**Issue by dtracers** [Microsoft/BashOnWindows#356] opened 2016-05-13 16:29 UTC
I ran this script on a fresh install of bash:

```
sudo apt-get update
sudo apt-get upgrade


sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
sudo pip install numpy
sudo apt-get install python-matplotlib

wget --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
sudo su
mkdir /opt/jdk
tar -zxf jdk-8u5-linux-x64.tar.gz -C /opt/jdk
ls /opt/jdk
update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_05/bin/java 100
update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_05/bin/javac 100
```

Then I ran this script:
```
sudo apt-get update
sudo apt-get upgrade


sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
sudo pip install numpy
sudo apt-get install python-matplotlib

wget --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
sudo mkdir /opt/jdk
sudo tar -zxf jdk-8u5-linux-x64.tar.gz -C /opt/jdk
sudo ls /opt/jdk
sudo update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_05/bin/java 100
sudo update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_05/bin/javac 100
```

![img_20160513_112357](https://cloud.githubusercontent.com/assets/1933836/15254739/f39ee21e-18fd-11e6-9d01-e5a953221767.jpg)

I do not know if this is reproducible

It could have something to do with sudo su then later running a sudo command? but I am not sure at all.

I ran the second script again after the computer restarted and did not experience any blue screen

**Comment by benhillis** [comment] 2016-05-13 18:50
Thanks for reporting this, I tried your script locally and I'm not seeing a bugcheck either.  Can you share which build number you are using?

**Comment by dtracers** [comment] 2016-05-13 18:53
Build number 14342.rs1_release.160506-1708

**Comment by benhillis** [comment] 2016-05-13 21:21
@dtracers Thanks! Do you happen to have a C:\Windows\MEMORY.DMP file on your machine?  If so could you upload it somewhere and send me the link so I can take a look?

Thanks!

**Comment by dtracers** [comment] 2016-05-13 22:22
I could not find that file.  Would it get deleted or removed in certain cases?

**Comment by haikarainen** [comment] 2016-05-16 18:50
@dtracers I think you can use bluescreenview to get  the dump file from previous bluescreens. http://www.nirsoft.net/utils/blue_screen_view.html

**Comment by benhillis** [comment] 2016-06-17 19:03
We've fixed a couple of bugchecks recently and I suspect yours was caused by one of the bugs.  Marking this as fixinbound.

**Comment by dtracers** [comment] 2016-06-17 19:04
Okay thank you!

It has not happened since so I would say it is fairly stable!

Thanks for the great very very useful product!!

**Comment by benhillis** [comment] 2016-06-17 19:14
@dtracers Thank you (and the rest of this great GitHub community) for the help!

**Comment by benhillis** [comment] 2016-07-08 15:30
This bluescreen is fixed in build 14376.  Please let us know if you see any bluescreen in this build, thanks!

**Closed by benhillis** 2016-07-08 15:30 UTC
Labels: bug, fixed

**Comment by ktrinanm** [comment] 2016-09-29 16:27
I've been having this issue for the last month or so, especially when using compilers. My most recent crashes have happened using mlton, but it's also happened using racket, Javac, and gcc.

**Comment by jackchammons** [comment] 2016-09-29 22:29
@ktrinanm any chance that you could provide a repro?

**Comment by ktrinanm** [comment] 2016-09-29 23:57
Do you just need a picture of the crash? I have this: https://drive.google.com/file/d/0B6ZXWVT-c9FYTGdMSi1fVTZjUnM/view?usp=drivesdk

**Comment by jackchammons** [comment] 2016-10-05 19:55
@ktrinanm Take a look at our [contributing.md](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md). Specifically, it would help if you could provide detailed steps necessary for us to reproduce this issue internally.

**Comment by ktrinanm** [comment] 2016-10-05 20:30
oh gotcha. My bash did just update, so I'll see if that changed anything. 

Specifically, I have been using mlton compiler from '$apt-get mlton' then '$mlton standml.sml' It crashes directly afterwards.

**Comment by jackchammons** [comment] 2016-10-05 21:11
@ktrinanm Could you share `standml.sml`?

**Comment by ktrinanm** [comment] 2016-10-05 21:23
It's only a few lines, but here it is
![image](https://cloud.githubusercontent.com/assets/16170034/19132191/b072001e-8b0f-11e6-9446-63b3efefe6c8.png)
