### ISSUE TITLE
Ability to choose the installation folder

### ISSUE THREAD

**Issue by Lectem** [Microsoft/BashOnWindows#780] opened 2016-08-05 13:21 UTC
## Feature request
It seems that the current installation folder is C:\Users\[user]\AppData\Local\lxss according to #402, while one might want to install it on another drive or folder. (to save space or whatever)
A command switch or dialog to specify the installation folder would be nice.

**Comment by benhillis** [comment] 2016-08-05 15:07
Duplicate of #449.

**Closed by benhillis** 2016-08-05 15:07 UTC

**Comment by Lectem** [comment] 2016-08-05 15:10
Oh right sorry, I didnt find it when searching
