### ISSUE TITLE
ip command ( replacement for ifconfig) not working

### ISSUE THREAD

**Issue by dragon512** [Microsoft/BashOnWindows#1114] opened 2016-09-22 19:48 UTC
Build 14931

This might be a duplicate issue as ifconfig does not work as well. Just logging it here.

the command ip fail: (example)
> ip
SO_SNDBUF: Invalid argument

From a networking point of view it would be nice for this to work as "ifconfig" as I understand it is being replaced with "ip"
Should note that all commands to ip seem to fail the same way.

**Comment by sunilmut** [comment] 2016-09-22 22:59
Thanks @dragon512 for the feedback. Yes, `ip` tool does not work today, just as `ifconfig`, for different reasons though. `ip` has dependency on [NETLINK](http://man7.org/linux/man-pages/man7/netlink.7.html) sockets and `ifconfig` relies on [SIOCG* IOCTLS](http://man7.org/linux/man-pages/man7/netdevice.7.html). Both of these are currently not implemented in WSL and we are looking into enabling these tools. This is also covered in this [User Voice Post](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/15202875-would-you-like-to-support-ifconfig-iw-iwconfig-t). Feel free to voice your opinion and vote there. Similar posts are #908, #767. Do bear with us as we make progress and hopefully you are having fun with WSL!

**Comment by bitcrazed** [comment] 2016-09-27 02:54
Closing as dupe of  #908, #767.

**Closed by bitcrazed** 2016-09-27 02:54 UTC
Labels: duplicate
