### ISSUE TITLE
tab completion always adds trailing slash

### ISSUE THREAD

**Issue by cvelten** [Microsoft/BashOnWindows#954] opened 2016-08-21 15:18 UTC
When using the tab completion feature, it appears that the console always adds in a trailing slash, not just with directories, which leads to e.g. python not being able to read a file.

Consider this:

```
 $ ls listfiles.py -la
-rwxrwxrwx 1 root root 1565 Jul  1 09:54 listfiles.py
 $ python listfiles.py/
python: can't open file 'listfiles.py/': [Errno 20] Not a directory
 $ python listfiles.py
usage: listfiles.py [-h] [--dir DIR] [-Q] [-B] [-X] path
listfiles.py: error: too few arguments
```

I have experienced that issue not just with **python**, but also with **root**, **cat**, and others. I have no running Linux machine available right now so I can't assert the bug better.

I am running on the Release Preview ring (14393.82), so it might already be fixed in the fast ring. However, I didn't find any issues posted here.

If you manually remove the slash it does obviously work, but it is of somewhat inconvenience.

Cheers

**Comment by aseering** [comment] 2016-08-21 15:35
Interesting -- that doesn't reproduce for me.  Using tab-complete to select the name:
```
$ ls -l listfiles.py
-rwxrwxrwx 1 root root 14 Aug 21 11:30 listfiles.py
$ python listfiles.py
files
$
```
This machine is currently running 14393.10.

**Comment by rodrymbo** [comment] 2016-08-21 16:54
I saw that sometimes when following a symlink from VolFS to DrvFS. Perhaps something like that happened?

**Comment by cvelten** [comment] 2016-08-21 21:55
> I saw that sometimes when following a symlink from VolFS to DrvFS. Perhaps something like that happened?

I just checked it from the $HOME dir and it looks like that's correct (checked both for root and the user). It also doesn't occur when going to the previously symlinked dir the normal way.

From that I assume this falls in line with #647 and #650 ? May be closed / referenced then.

**Comment by benhillis** [comment] 2017-01-06 16:41
Closing this as a duplicate of #647 and #650.

**Closed by benhillis** 2017-01-06 16:41 UTC
