### ISSUE TITLE
unix `screen` not working

### ISSUE THREAD

**Issue by SiNZeRo** [Microsoft/BashOnWindows#1367] opened 2016-11-15 05:06 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
unix `screen` not working
* Expected results
`screen` shows
* Actual results (with terminal output if applicable)
prompt `Cannot make directory '/var/run/screen': Permission denied`
* Your Windows build number
14393.447
* Steps / All commands required to reproduce the error from a brand new installation 
screen
* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by SiNZeRo** [comment] 2016-11-15 05:09
after attempts to reinstall screen:
'''
sudo apt-get remove screen
sudo apt-get install screen
'''
run `screen`
turn out to be:
`[screen is terminating]`

**Comment by ngokevin** [comment] 2016-11-15 07:45
FWIW, tmux works for me.

**Comment by kossboss** [comment] 2016-11-15 08:26
I recommend to transition from screen to tmux. Screen is awesome if tmux is not available. Tmux seems to be on every system now.

You can run tmux just like screen (it comes with screen keys configuration). In my opinion tmux is much better. Supports plugins as well. You can get mouse support that actually works well with panes. You can get yank support (like vi/vim tank). Its panes (screen splitting), windows (tabs) work so much better,

Everything you ever wanted to know about tmux running with screen keys: 
[Running Tmux with Screen Keys - Tmux compared with Screen, Detach, Byobu, etc...](http://ram.kossboss.com/tmux-look-screen-dtach-byobu-tmux-wins-indepth-tmux/)
Here is my tmux config, the top part is the common screen config part. The bottom part is tpm (tmux plugin manager) so I can get new features (mouse support, tmux yank, etc)... [Tmux config file features screen keys and also TPM plug in for mouse mode, yank, and copy cat](http://ram.kossboss.com/tmux/home-dot-tmux.conf)

Note for better mouse mode you should get tmux 2.4. Typical installation of tmux are version 1.8. WSL bash comes with 1.8. But you can easily compile tmux 2.4 (I have it in the Tmux config file link)

**Comment by aseering** [comment] 2016-11-15 14:44
I believe `screen` support has been fixed in a recent Insider build.  It works for me on build 14965.  I would expect the fix to make it into the next major Windows release.

**Comment by benhillis** [comment] 2016-11-15 16:13
Marking as duplicate of #774.

**Closed by benhillis** 2016-11-15 16:13 UTC

**Comment by jean** [comment] 2018-07-14 06:42
As of Build 17134.165, the issue persists.

**Comment by therealkenc** [comment] 2018-07-14 08:11
Yeah, the fixed/closed status here was because of a nonobvious interpretation of what was broken and what was addressed wrt `screen(1)` (a long time ago `screen` didn't work period). See #774 (in particular [message](https://github.com/Microsoft/WSL/issues/774#issuecomment-313815937)). 

For "WSL doesn't do all the `init` things" landing zone is #2530. n.b. That issue cites `tmux` but really it is lots of _things_ including setting up `/run/screen`.
