### ISSUE TITLE
running fdisk results in not found error

### ISSUE THREAD

**Issue by paladox** [Microsoft/BashOnWindows#1387] opened 2016-11-18 18:29 UTC
* A brief description

Running sudo fdisk -l results in the error below

* Expected results

* Actual results (with terminal output if applicable)

fdisk: cannot open /proc/partitions: No such file or directory

* Your Windows build number
14971

* Steps / All commands required to reproduce the error from a brand new installation 
sudo fdisk -l

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment] 2016-11-18 18:32
fdisk works on block devices.  WSL does not support block devices right now, unless something has changed.

**Comment by stehufntdev** [comment] 2017-01-09 21:52
Thanks for reporting the issue.  Closing this out as a duplicate of #837 so we only have one thread tracking the request.

**Closed by stehufntdev** 2017-01-09 21:52 UTC
