### ISSUE TITLE
vfork failing unless excessively large swap space configured

### ISSUE THREAD

**Issue by chesterm8** [Microsoft/BashOnWindows#1286] opened 2016-10-28 04:52 UTC
Simple java class to reproduce the issue: [Gist](https://gist.github.com/therealkenc/9df8855404fa4d74488a053b0004627b)

Compiled and run using 

At 5000MB the following is seen:

```
[bellchesters@DESKTOP]$ java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
[bellchesters@DESKTOP]$ javac Main.java
[bellchesters@DESKTOP]$ strace -ff java Main 2>&1 | grep vfork
[pid  2398] vfork()                     = -1 ENOMEM (Cannot allocate memory)
```

At 16000MB the operation completes successfully.

**Comment by benhillis** [comment] 2016-12-01 22:26
Marking this as a duplicate of #851 - see my comment about the incoming fix https://github.com/Microsoft/BashOnWindows/issues/851#issuecomment-264314420

**Closed by benhillis** 2016-12-01 22:26 UTC
Labels: bug, duplicate, fixinbound, memory
