### ISSUE TITLE
apt-get upgrade

### ISSUE THREAD

**Issue by paladox** [Microsoft/BashOnWindows#641] opened 2016-07-10 21:41 UTC
When upgrading some packages

I get this error

logger: write failed: Operation not supported
logger: write failed: Operation not supported
logger: write failed: Operation not supported
logger: write failed: Operation not supported
logger: write failed: Operation not supported
logger: write failed: Operation not supported
logger: write failed: Operation not supported

I am using Ubuntu 16.04.

**Comment by benhillis** [comment] 2016-07-11 15:13
If possible could you try to track down what logger is complaining about?  Perhaps by taking an strace of the apt-get upgrade command?

Full disclosure: We've been focused on 14.04 and 16.04 is not fully supported for the Windows 10 anniversary update so some things may not work.

**Comment by benhillis** [comment] 2016-07-11 15:13
Marking as a duplicate of #640.

**Closed by benhillis** 2016-07-11 15:13 UTC
