### ISSUE TITLE
Bash hangs/freezes indefinitely

### ISSUE THREAD

**Issue by Majsvaffla** [Microsoft/BashOnWindows#1719] opened 2017-02-23 14:48 UTC
### Description
Eventually some process started from bash hangs and makes bash completely non responsive. I'm able to launch another bash.exe instance but as soon as I run any command that instance also hangs. At one occasion I was able to do (in a new bash instance) `ls` in ~ but not `ps`. I can also mostly `cd` but as soon as I go into the directory where bash originally hung the new instance hangs as well. I'm not able to `Ctrl + C` out. 

Build version 15025 is the first one where I experienced this issue but it's still there after I updated to 15031. I tried reinstalling WSL (full uninstall) but that didn't solve the problem. It doesn't seem to matter what my current working directory is; both pure WSL paths and paths under /mnt/c has this issue.

I have another Windows user account on the machine. The WSL installation (both have 16.04) under that other user havn't suffered from theese symptoms yet (after some hours of similar usage as in my development user account)

### Build version
```
C:\Users\David>ver
Microsoft Windows [Version 10.0.15031]
```

### Environment
I have read other issues about simliar symptoms due to anti-virus software but I don't have anything other than Windows Defender running on my machine. 

#### Applications running in WSL (almost always when the problem have shown):
- python (along with django and a lot of other python packages)
- sshd

#### Applications running in Windows (when problem arises):
- Windows Defender
- PostgresSQL 9.6
- PyCharm 2016.3 (using Python in WSL virtual python environent as interpreter over SSH on port 2222)
- Some other programs and apps not directly related to my development setup

### Detailed logs
I have run logman (as described [here](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md)) at one time when the issue arised so I have those trace files if anyone would like to take a look at them as I'm not able to interpret them myself.

**Comment by aseering** [comment] 2017-02-23 14:56
Hi @Majsvaffla , thanks for reporting this!  It sounds to me like it may have the same root cause as #1661 .  Could you take a look?

**Comment by Majsvaffla** [comment] 2017-02-23 15:11
@aseering Yeah #1661 sure seems like the problem I have. I have run make occasionally, without it halting though. From reading the comments I think I'll just wait for the next build to be released on the fast ring. Otherwise I could roll back to something pre 15025 I guess.

**Comment by benhillis** [comment] 2017-02-23 16:22
@Majsvaffla - The issue is a deadlock due to multiple threads accessing files in the same directory, I'm going to close this issue out as a duplicate but if you still have issues when the fix for this issue is released please reopen.

Thanks!

**Closed by benhillis** 2017-02-23 16:22 UTC
