### ISSUE TITLE
Color rendering issues

### ISSUE THREAD

**Issue by tycho** [Microsoft/BashOnWindows#76] opened 2016-04-08 18:00 UTC
Most colors don't render properly. Below examples use [this script](https://conemu.github.io/256colors2.pl).

MinTTY (Cygwin):
![colortest on MinTTY](https://i.imgur.com/YkiTNlG.jpg)

Bash on Windows:
![colortest on Bash](http://i.imgur.com/rKMSPrb.png)

**Comment by zadjii-msft** [comment] 2016-04-08 22:03
Right now conhost's color support is limited to the default 16 ASCII colors, but 256 color support is most definitely high on the backlog of things we'd like to support in the near future!

**Comment by jbaribeault** [comment] 2016-04-08 22:04
Great to hear!

**Comment by kilobyte** [comment] 2016-04-11 12:32
256 color support is an addition that is in no way required.

This said, because of a misdesign they do need to be explicitly recognized in order to be ignored, otherwise the result is interpreted as random unrelated codes (example: **printf 'foo\e[38;5;1mbar\e[0m\n'**).  Here's how to detect them: https://github.com/torvalds/linux/commit/3415097ff0529eac264b8ccfa06572871e45c090 (my comment that 24-bit is "extremely rare" is no longer true: https://gist.github.com/XVilka/8346728).

Adding actual support for 256/24-bit color to conhost would require significant API changes -- Windows Console is internally married to the 16 color scheme.  Just like Linux console (VT not some X terminal) -- the most you can do is to try match nearest color.  I did happen to implement that: https://github.com/torvalds/linux/commit/cec5b2a97a11ade56a701e83044d0a2a984c67b4

Microsoft guys: I hereby relicense these two commits, please feel free to use/adapt them.

**Comment by bitcrazed** [comment] 2016-04-28 20:32
Fixed internally. Bubbling up through the build system.

**Comment by retep998** [comment] 2016-05-11 15:23
@bitcrazed Will there also be an equivalent Windows API method to take advantage of the enhanced color support?

**Comment by zadjii-msft** [comment] 2016-05-11 22:43
@retep998 At this time, the API surface isn't changing at all. We're not yet supporting full 256 color or 24 bit RGB yet - we're merely finding the nearest color from the 16-color table and using that to render the color for applications using those sequences. Unfortunately, supporting true 256 color requires a lot more work than was possible to get done for this update.

**Comment by fredrikaverpil** [comment] 2016-05-17 18:38
> Fixed internally. Bubbling up through the build system.

Just curious... when is this supposed to bubble out to insider previews?

**Comment by zerocool4u2** [comment] 2016-05-27 09:34
![sin titulo](https://cloud.githubusercontent.com/assets/1785923/15604111/687e83c2-23cc-11e6-885e-7315d0c1b025.png)

14352

**Comment by dreyks** [comment] 2016-06-09 21:48
@zerocool4u2 how did you get those fancy powerline symbols working? Did you install additional fonts?

**Comment by zerocool4u2** [comment] 2016-06-10 08:35
@dreyks yup i don't remember witch one was that, but there are some repos with patched fonts, https://github.com/gabrielelana/awesome-terminal-fonts https://github.com/ryanoasis/nerd-fonts/ are a couple of them, i'm actually currently working on courier prime code, that was my favorite and i'm trying to get a propper patch on it(most of them are patched with scrips and there aren't the best with most the scenarios, speceally with windows monospaced definition, if that makes sence), let me know if you want it, regards
![boceto](https://cloud.githubusercontent.com/assets/1785923/15958612/a3137dfa-2ec4-11e6-95e8-5c25e329e721.png)

**Comment by musmo** [comment] 2016-06-11 20:15
256 color  support would be  magical

**Comment by JoBrad** [comment] 2016-06-20 23:03
Full color support would be amazing to have!

**Comment by laurensV** [comment] 2016-06-22 09:16
Any estimation of when 256 color support will be available?

**Comment by bitcrazed** [comment] 2016-06-26 20:17
No details just yet - will share once our planning settles-down.

**Comment by benhillis** [comment] 2016-07-15 00:40
![image](https://cloud.githubusercontent.com/assets/17727402/16860142/14580f22-49ea-11e6-8aa6-5b7a5e032ebc.png)

**Closed by benhillis** 2016-07-15 00:40 UTC
Labels: console, fixed

**Comment by cscorley** [comment] 2016-09-07 22:45
I do not think this should be considered as "fixed" yet. Happy to have color mappings, but they're still mapping to incorrect colors.

**Comment by kilobyte** [comment] 2016-09-08 16:04
@cscorley: I'm afraid such a full fix would require so much work that WONTFIXing it for the time being is reasonable.  The problem is, the [CHAR_INFO](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682013(v=vs.85).asp) structure has no room for expansion and gets passed to and from user programs a lot.  Thus, a load of functions and structures would need to receive new versions and a translation layer between such a new internal format and the old API.  Doesn't sound enticing to me to do that just to have more colors on the console.

Other SGR codes such as strikethrough, italic or blink have spotty support and about no use among Unix terminals, so 256/24-bit color would be the sole real gain.

**Comment by zadjii-msft** [comment] 2016-09-08 16:06
This was closed as adding support for processing 256-color sequences, #345 is the current active issue for adding the actual full RGB color support

**Comment by cscorley** [comment] 2016-09-08 16:53
All is very understandable w.r.t work needed for full color support. I was disappointed to find this marked fixed; thought that something was wrong with my environment for a long time. Missed the link to the new issue. Thanks, all!

**Comment by SRGOM** [comment] 2016-09-08 17:03
I would suggest using ConEmu. I ran some tests way back and ConEmu is (was) faster than ConHost in terms of raw throughput. Its much better in almost all respects (except probably startup time) and has a config file that can persist fonts and their size.

**Comment by cscorley** [comment] 2016-09-08 17:05
@SRGOM I've tried both ConEmu and ConsoleZ as of this week.  They both do not add full 256 color support; seem to display the same color mappings as above.  Thanks for the suggestion, though.

**Comment by musm** [comment] 2016-09-08 17:08
+1 to conemu, however it's kind of bloated and snapping doesn't work properly to due win32api bug apparently and does not have proper xterm compatible 256 colors using bash.

The solution I found for 256 colors is to use mintty! Install msys2 http://msys2.github.io/ and use that. It works for cmd and for bash you have 256 colors! They also have some awesome features planned like font fallbacks.  In addition, it only works for powershell -version 2 there's a bug with the readline in powershell 3 in windows 10 that gives it problems when trying to run through mintty.

I'm still trying to configure out how to optimally configure mintty (key mappings are annoying)

![image](https://cloud.githubusercontent.com/assets/4319522/18358894/582e0a92-75c5-11e6-86d3-c05dd94ede56.png)

**Comment by musm** [comment] 2016-09-08 17:26
More pics:
![image](https://cloud.githubusercontent.com/assets/4319522/18359413/d350ef94-75c7-11e6-8fcf-a661eafd0dc0.png)

**Comment by onomatopellan** [comment] 2016-09-09 11:59
So far my favorite way of using WSL with 256 colors is mintty, yes, but better through this great package https://github.com/goreliu/wsl-terminal/releases

**Comment by musm** [comment] 2016-09-09 13:49
wow what a great package, thank you @onomatopellan for linking!

**Comment by SRGOM** [comment] 2016-09-09 17:02
I get a Windows Smartscreen warning for all the binaries in the release- something I've never got before. Is it safe?

**Comment by onomatopellan** [comment] 2016-09-09 18:01
Totally safe. You can see in the source code those .exe are just AutoHotKey scripts. SmartScreen complains because those executables are not signed.

**Comment by SRGOM** [comment] 2016-09-09 19:30
For those who care about this sort of thing, save the following in a script and run `time <script name>`
```
for i in `seq 1 1000000`
do
  echo $i
done

```

wsl-terminal:  2.23s user 33.64s system 77% cpu 46.170 total
ConHost:  3.83s user 20.94s system 33% cpu 1:14.73 total

Its the difference between outputs whizzing past you vs you waiting for them. I prefer the former, of course.

**Comment by cscorley** [comment] 2016-09-10 00:15
Thanks for all the suggestions in the thread.  I actually have been using wsl-terminal at home, but using wslbridge is not something currently possible on my work machines: it is being killed via the Malware software the company uses.  Unfortunately, getting this safelisted is not a simple task.

**Comment by deto** [comment] 2016-09-22 23:37
Just found this out - relevant to this thread.

https://twitter.com/richturn_ms/status/779046431361343490
