### ISSUE TITLE
ReadConsoleInputA returns wrong character in KeyEvent.uChar.AsciiChar

### ISSUE THREAD

**Issue by MGilarde** [Microsoft/BashOnWindows#2215] opened 2017-06-13 17:46 UTC
Microsoft Windows [Version 10.0.14393] : Anniversary Update
Microsoft Windows [Version 10.0.15063] : Creators Update

Our console application uses ReadConsoleInputA to read a character from the input buffer. In Windows 10 Creators Update (CU), some characters are different than they were in Anniversary Update (AU). Enabling the legacy console in CU restores the characters to what they were in AU.

The console program below demonstrates this. Run it with the Spanish (Espana) keyboard and hit the tilde key. You should see different output on AU and CU.

```
AU:
Down: 1 Repeat: 1 KeyCode: 0xdc ScanCode: 0x29 CharW: ║ (0xba) CharA: º (0xffffffa7) KeyState: 0x0
CU (new console):
Down: 1 Repeat: 1 KeyCode: 0xdc ScanCode: 0x29 CharW: ║ (0xba) **CharA: ║ (0xffffffba)** KeyState: 0x0
CU (legacy console):
Down: 1 Repeat: 1 KeyCode: 0xdc ScanCode: 0x29 CharW: ║ (0xba) CharA: º (0xffffffa7) KeyState: 0x0
```

Note that CharA appears to be the Unicode version of the character (same as CharW sign extended) when running on CU with the new console. The behavior is the same on AU and CU with the legacy console. The program shows the console code page, which is IBM437.

```
#include <windows.h>
#include <wchar.h>
#include <stdlib.h>
#include <stdio.h>

int __cdecl wmain(int argc, WCHAR* argv[])
{
    HANDLE hIn = GetStdHandle(STD_INPUT_HANDLE);

    printf("GetConsoleCP: %d\r\n", GetConsoleCP());

    for (;;)
    {
        INPUT_RECORD rc;
        INPUT_RECORD rcA;
        DWORD dwRead = 0;
		
        PeekConsoleInputW(hIn, &rc, 1, &dwRead);

        if (dwRead > 0)
        {
            ReadConsoleInputA(hIn, &rcA, 1, &dwRead);

            if (rcA.EventType == KEY_EVENT)
            {
                printf("Down: %d Repeat: %d KeyCode: 0x%x ScanCode: 0x%x CharW: %c (0x%x) CharA: %c (0x%x) KeyState: 0x%x\r\n",
                    rc.Event.KeyEvent.bKeyDown,
                    rc.Event.KeyEvent.wRepeatCount,
                    rc.Event.KeyEvent.wVirtualKeyCode,
                    rc.Event.KeyEvent.wVirtualScanCode,
                    rc.Event.KeyEvent.uChar.UnicodeChar,
                    rc.Event.KeyEvent.uChar.UnicodeChar,
                    rcA.Event.KeyEvent.uChar.AsciiChar,
                    rcA.Event.KeyEvent.uChar.AsciiChar,
                    rc.Event.KeyEvent.dwControlKeyState);
                }
        }
    }
}
```

**Comment by zadjii-msft** [comment] 2017-06-14 22:09
I'm pretty sure miniksa's already hunting this down :)

**Comment by miniksa** [comment] 2017-06-20 21:30
This is a duplicate of #2049. I've written a fix and it's on its way to insider builds.

**Closed by miniksa** 2017-06-20 21:30 UTC
Labels: bug, console
