### ISSUE TITLE
Bash was hanging after mv, restarted LxssManager and now it won't open

### ISSUE THREAD

**Issue by RobRoseKnows** [Microsoft/BashOnWindows#1261] opened 2016-10-23 18:19 UTC
- A brief description

Yesterday I was attempting to move the contents of a folder from one folder to another using a similar command: `mv Child/FolderA/ FolderB`. I was trying to move FolderA from the Child directory to the current working directory. When I did so, `mv` hung. I tried using Ctrl+C to exit it but that didn't do anything. I ended up closing out of the bash window hoping that would fix it. When I reopened, it was still hanging, nothing was showing up, just a blinking `_`.  I checked task manager and it looked like something related to Bash was opening, but not bash itself. (It was something like "Bash Startup", I forgot to write down the name).

I restarted my computer hoping that would fix it but when I rebooted and reopened bash it was still hanging. So I tried restarting LxssManager by going to Task Manager > Services, right clicking LxssManager and selecting Restart. Now when I try to open Bash it just flashes open and then closes. The program that was showing up in Task Manager is no longer showing up.
- Your Windows build number

14393.321
- Steps / All commands required to reproduce the error from a brand new installation:

I think the initial error can be caused by:

`mv Child/FolderA/` FolderB`
- Strace of the failing command

If I run `sc query LxssManager` this is what shows up:

```
SERVICE_NAME: LxssManager
        TYPE                           : 20  WIN32_SHARE_PROCESS
        STATE                         : 4  RUNNING
                                            (STOPPABLE, NOT_PAUSABLE, ACCEPTS_PRESHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT             : 0x0
        WAIT_HINT                : 0x0
```

I'm not sure how to find the stack trace of the `mv` command now that it isn't opening.
- Required packages and commands to install

I don't think I had any packages that would be relevant and I don't know how to find a list of

**Comment by goreliu** [comment] 2016-10-23 18:31
Build 14901 fixed it.

https://msdn.microsoft.com/en-us/commandline/wsl/release_notes

**Comment by rodrymbo** [comment] 2016-10-23 18:56
@RobRoseKnows 

It sounds like a bit more than the trailing slash issue, or at least I don't remember that issue keeping bash.exe from starting. (It sounds like some system files got messed up when the `mv` failed because of the trailing slash issue.)

At any rate, you [might have to do an uninstall and reinstall](https://msdn.microsoft.com/en-us/commandline/wsl/reference) to get things going again.

**Comment by fpqc** [comment] 2016-10-23 20:15
Were you by any chance in tmux?

**Comment by leonyu** [comment] 2016-10-24 08:31
Having this problem. Initially encountered the bug using `WSL in Mintty` terminal, was able to reproduce with `Bash on Ubuntu` terminal. 

Only solution way to recover is to reboot the machine.

**Comment by fpqc** [comment] 2016-10-24 08:57
@leonyu This is the same as a a few other issues, including #1127 and #1075

It's a deadlock in the kernel coming from the pty implementation, and it is fixinbound.  If you were on OhMyZsh, read 1075 and look which libs to disable.

**Comment by arvindpdmn** [comment] 2016-10-25 11:09
I have the same issue. Installed bash. Ran a `mv` command for moving folders. Arguments had trailing / characters. It just hanged. Did a restart of the machine. Bash won't start now. What shall I do?

**Comment by arvindpdmn** [comment] 2016-10-25 13:45
Here's an update:
https://forum.avast.com/index.php?topic=150894.msg1345198#msg1345198

**Comment by benhillis** [comment] 2016-10-27 15:28
@arvindpdmn You can check your windows build by running "ver" in the command prompt.  Have you tried resetting the WSL filesystem?

```
lxrun.exe /uninstall /full
lxrun.exe /install
```

**Comment by ya790206** [comment] 2017-01-04 06:03
The issue also happened when renaming folder.
Try the command, "mv old_folder_name new_folder_name" will make bash hang

Version: 1607
OS build: 14393.576

**Comment by atbe** [comment] 2017-01-05 21:18
Experiencing this issue as well.

Did a complete removal of the subsystem, reinstalled, still has the same issue.

Microsoft Windows 10 Build number: 14393.576

How do we force the subsystem to update to the latest image? The Windows store does not list it as an item.

**Comment by fpqc** [comment] 2017-01-05 22:15
omg nobody reads things anymore!!!

It's fixed in the insider builds.

Stop doing mv with a trailing / if you don't want to update to insider builds =p....

**Comment by sunilmut** [comment] 2017-01-05 22:26
@atbe 
> How do we force the subsystem to update to the latest image?

If you are running 14393, the subsystem will not update you to Ubuntu 16.04 (if that's what you were asking). You have to be on the insider build or wait for the next major update to Windows.

Can you try a full uninstallation of WSL by following [these steps](https://msdn.microsoft.com/en-us/commandline/wsl/troubleshooting#installation-issues-after-windows-system-restore) and see if that restores the state. It should.

**Comment by benhillis** [comment] 2017-02-14 01:59
This is a duplicate of #1008.

**Closed by benhillis** 2017-02-14 01:59 UTC
