### ISSUE TITLE
dmesg: read kernel buffer failed: Function not implemented

### ISSUE THREAD

**Issue by matevarga** [Microsoft/BashOnWindows#1883] opened 2017-04-11 18:21 UTC
* A brief description

`apt-get install openjdk-9-jdk` fails

* Expected results
`apt-get install openjdk-9-jdk` installs successfully

* Actual results (with terminal output if applicable)
```Unpacking openjdk-9-jdk:amd64 (9~b114-0ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/openjdk-9-jdk_9~b114-0ubuntu1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/jvm/java-9-openjdk-amd64/include/linux/jawt_md.h', which is also in package openjdk-9-jdk-headless:amd64 9~b114-0ubuntu1
dmesg: read kernel buffer failed: Function not implemented
```

* Your Windows build number
15063
* Steps / All commands required to reproduce the error from a brand new installation 
`apt-get install openjdk-8-jdk`
* Strace of the failing command
[strace.txt](https://github.com/Microsoft/BashOnWindows/files/914311/strace.txt)

**Comment by jackchammons** [comment] 2017-04-12 00:24
I am able to reproduce this on 16170.

**Comment by stehufntdev** [comment] 2017-04-13 21:11
Closing this out as a duplicate of #1886 so we can track it in one place.

**Closed by stehufntdev** 2017-04-13 21:11 UTC

**Comment by kenorb** [comment] 2018-09-08 15:51
Follow-up: GH-1321

**Comment by kenorb** [comment] 2018-10-04 16:02
It's fixed now. Please [upgrade WSL](http://wsl-guide.org/en/latest/update.html).

**Comment by Zeushn** [comment] 2018-12-05 03:56
I'm having this issue, in WSL ubuntu 18.04.1 LTS on Windows 10 pro Version 1803 Build 17314.407
HW: Dell Inspiron 5770

**Comment by therealkenc** [comment] 2018-12-05 04:09
> Version 1803 Build 17314.407

You're short of [17655](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-17655-skip-ahead) ([message](https://github.com/Microsoft/WSL/issues/1321#issuecomment-404911012)).

**Comment by Zeushn** [comment] 2019-01-22 06:44
Thanks for the Reply, now running the latest build and the 17763.253 and the command is pushed but no output at all. any ideas?

**Comment by therealkenc** [comment] 2019-01-22 17:46
> grep -i usb" but no output at all. 

Quip answer would be WSL has no USB so that grep is empty (and that would actually be true). Straightforward answer is that the WSL kernel only writes on line to `/dev/kmsg`.
