### ISSUE TITLE
WSL not working after bad mv command

### ISSUE THREAD

**Issue by Imamadmad** [Microsoft/BashOnWindows#1652] opened 2017-02-01 14:41 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
I performed (what I now realise was) a malformed mv command in an attempt rename a folder, but the command never ended.  I ctrl+Ced many times, but the next prompt never reappeared.  I typed in a command for it to perform once it was done, ls, but that was never executed.  I closed the window and then reopened, but no prompt appeared at all.  I restarted my computer, but still couldn't get control of the bash terminal.

* Expected results
The prompt appearing so I can fill in the next command

* Actual results (with terminal output if applicable)
The terminal opens, outputs nothing, and then closes after about a minute.
(The screenshot uploading on this website isn't working and is showing the terminal as blank white instead of the actual blank black, but considering the nothingness of it, I don't think a screenshot is necessary)

* Your Windows build number
![image](https://cloud.githubusercontent.com/assets/12166027/22510944/cf9fa00c-e88b-11e6-9148-aae34d04f811.png)

* Steps / All commands required to reproduce the error from a brand new installation 
Not entirely sure, since I shut the prompt in an attempt to get it to start working again and therefore don't have the exact wording, but the command was something along the lines of:
`mv directory_1/ directory_2`
Where directory_1 is an existing directory and directory_2 is an uncreated directory that I wished the first directory to be renamed to.

* Strace of the failing command
No stack trace.  In fact, no output of any kind.

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by Gander7** [comment] 2017-02-01 16:35
same here, had to reinstall lxrun. Will provide more information if I can pinpoint it.

**Comment by benhillis** [comment] 2017-02-01 16:39
This looks like a duplicate of #1008 where rename fails with a trailing slash. This is fixed for insider builds.

**Comment by Imamadmad** [comment] 2017-02-01 18:03
@benhillis In which insider build ring is it fixed?  I'm in the release preview ring and my device is apparently up to date, according to settings.

**Comment by fpqc** [comment] 2017-02-01 18:31
@Imamadmad Release Preview will probably be moving to RS2/Creator Update in March I would guess (they do a feature freeze and bugfix in the last 2 months/month and a half before release at the end of April).  Before that, RP is going to just be the current branch (Anniversary Update).

I would suggest slow ring right now.  Fast ring broke all of my games this week (after breaking my xbox controller last week!!!!!).

**Comment by benhillis** [comment] 2017-02-01 18:31
@Imamadmad - These updates only go out through Insider Fast and Insider Slow. Release preview you are basically previewing only Windows Updates to the current version of Windows.

More information [here.](https://blogs.windows.com/windowsexperience/2016/02/10/announcing-windows-10-mobile-insider-preview-build-10586-107/#ZdW7Av7scG2d7hU3.97)

**Release Preview** – Best for Insiders who enjoy getting early access to updates for the Current Branch, Microsoft applications, and drivers, with minimal risk to their devices, and still want to provide feedback to make Windows devices great.

**Closed** 2017-02-01 22:15 UTC
Labels: duplicate
