### ISSUE TITLE
Truncated console output.

### ISSUE THREAD

**Issue by Bazalia** [Microsoft/BashOnWindows#2265] opened 2017-06-28 11:02 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Large STDOUT output from commands that exceeds the size of the console gets truncated to show only the last page of output of that command. When scrolling upwards the previous output of that command is not displayed. E.g. say I run "apt search microsoft", after dumping all of this commands output on the console I can only view the last page of the output and nothing before that even if I scroll up.
* What's wrong / what should be happening instead:

I was expecting to be able to view all of the command's output if I scroll up, but I could only view the last page of the output.

**Comment by sunjoong** [comment] 2017-06-28 12:00
@Bazalia - I myself could not reporduce with "apt search microsoft";
![scrollup](https://user-images.githubusercontent.com/2748000/27635763-6570b118-5c43-11e7-920e-3a14ed11bb92.png)
But... what you said looks similar to #1984 (and maybe #2161), so... there might be a certian abnormal or unexpected thing on screen buffer, I'm afraid.

**Comment by zadjii-msft** [comment] 2017-07-05 20:58
@Bazalia @sunjoong is right. What you're describing is a dupe of those issues, the fix should be *coming to an Insider's build near you soon!*

**Closed by zadjii-msft** 2017-07-05 20:58 UTC
Labels: bug, console
