### ISSUE TITLE
get Error 22 when installing local Perl module 

### ISSUE THREAD

**Issue by JINPENG-WANG** [Microsoft/BashOnWindows#1432] opened 2016-11-29 11:36 UTC
* A brief description

   The Perl module (e.g. Finnigan::Scan) was downloaded and saved in the Desktop. I tried to install it from     local directory with

    _perl Makefile.PL
   make
   ..._

but got an error: 
_Can't write-open blib/man3/Finigan::AuditTag.3pm: Invalid argument at        /usr/share/perl/5.22/ExtUtils/Command/MM.pm line147.
    Makefile:643: recipe for target 'manifypods'  failed
     make: *** [manifypods] Error 22_

I have also tried other modules but got the similar error:
 _Can't write-open blib/man3/SelSweepRegion::FindGene.3pm: Invalid argument at        /usr/share/perl/5.22/ExtUtils/Command/MM.pm line147.
    Makefile:418:: recipe for target 'manifypods'  failed
     make: *** [manifypods] Error 22_

* Your Windows build number

   _Windows 10 Home Insider Previewer China
     Build 14971.rs_prerelease.161111-1700_

* Steps / All commands required to reproduce the error from a brand new installation 

    _tar -xvf Finnigan-0.0206d.tar.gz
     cd Finnigan-0.0206
     perl Makefile.PL
     make_

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by stehufntdev** [comment] 2016-11-29 18:46
Thanks for reporting the issue.  Can you please provide an strace of the failing command?

**Comment by JINPENG-WANG** [comment] 2016-11-30 00:38
The strace is attached below.
[strace.out.txt](https://github.com/Microsoft/BashOnWindows/files/620642/strace.out.txt)

**Comment by JINPENG-WANG** [comment] 2016-11-30 06:11
execve("/usr/bin/make", ["make"], [/* 17 vars */]) = 0
brk(NULL)                               = 0x1262000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5b9a890000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=33787, ...}) = 0
mmap(NULL, 33787, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f5b9a887000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240\r\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=14608, ...}) = 0
mmap(NULL, 2109680, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f5b9a3f0000
mprotect(0x7f5b9a3f3000, 2093056, PROT_NONE) = 0
mmap(0x7f5b9a5f2000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f5b9a5f2000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1864888, ...}) = 0
mmap(NULL, 3967392, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f5b9a020000
mprotect(0x7f5b9a1df000, 2097152, PROT_NONE) = 0
mmap(0x7f5b9a3df000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bf000) = 0x7f5b9a3df000
mmap(0x7f5b9a3e5000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f5b9a3e5000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5b9a880000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5b9a870000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5b9a860000
arch_prctl(ARCH_SET_FS, 0x7f5b9a870700) = 0
mprotect(0x7f5b9a3df000, 16384, PROT_READ) = 0
mprotect(0x7f5b9a5f2000, 4096, PROT_READ) = 0
mprotect(0x630000, 4096, PROT_READ)     = 0
mprotect(0x7f5b9a825000, 4096, PROT_READ) = 0
munmap(0x7f5b9a887000, 33787)           = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=8192*1024}) = 0
brk(NULL)                               = 0x1262000
brk(0x1283000)                          = 0x1283000
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1668976, ...}) = 0
mmap(NULL, 1668976, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f5b9a68d000
close(3)                                = 0
rt_sigaction(SIGHUP, {0x409b80, [HUP], SA_RESTORER|SA_RESTART, 0x7f5b9a0554b0}, {SIG_DFL, [], SA_RESTORER, 0x7fcb85a254b0}, 8) = 0
rt_sigaction(SIGQUIT, {0x409b80, [QUIT], SA_RESTORER|SA_RESTART, 0x7f5b9a0554b0}, {SIG_DFL, [], SA_RESTORER, 0x7fcb85a254b0}, 8) = 0
rt_sigaction(SIGINT, {0x409b80, [INT], SA_RESTORER|SA_RESTART, 0x7f5b9a0554b0}, {SIG_DFL, [], SA_RESTORER, 0x7fcb85a254b0}, 8) = 0
rt_sigaction(SIGTERM, {0x409b80, [TERM], SA_RESTORER|SA_RESTART, 0x7f5b9a0554b0}, {SIG_DFL, [], SA_RESTORER, 0x7fcb85a254b0}, 8) = 0
rt_sigaction(SIGXCPU, {0x409b80, [XCPU], SA_RESTORER|SA_RESTART, 0x7f5b9a0554b0}, {SIG_DFL, [], SA_RESTORER, 0x7fcb85a254b0}, 8) = 0
rt_sigaction(SIGXFSZ, {0x409b80, [XFSZ], SA_RESTORER|SA_RESTART, 0x7f5b9a0554b0}, {SIG_DFL, [], SA_RESTORER, 0x7fcb85a254b0}, 8) = 0
rt_sigaction(SIGCHLD, {SIG_DFL, [CHLD], SA_RESTORER|SA_RESTART, 0x7f5b9a0554b0}, {SIG_DFL, [CHLD], SA_RESTORER|SA_RESTART, 0x7f01510654b0}, 8) = 0
fcntl(1, F_GETFL)                       = 0x402 (flags O_RDWR|O_APPEND)
fcntl(1, F_SETFL, O_RDWR|O_APPEND)      = 0
fcntl(2, F_GETFL)                       = 0x402 (flags O_RDWR|O_APPEND)
fcntl(2, F_SETFL, O_RDWR|O_APPEND)      = 0
getcwd("/mnt/c/Users/wjp/Desktop/1/SelSweepRegion-FindGene-0.01", 4096) = 56
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
fstat(1, {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 1), ...}) = 0
readlink("/proc/self/fd/1", "/dev/tty1", 4095) = 9
stat("/dev/tty1", {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 1), ...}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
fstat(2, {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 1), ...}) = 0
readlink("/proc/self/fd/2", "/dev/tty1", 4095) = 9
stat("/dev/tty1", {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 1), ...}) = 0
stat("/usr/include", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
stat("/usr/gnu/include", 0x7fffed03db00) = -1 ENOENT (No such file or directory)
stat("/usr/local/include", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
stat("/usr/include", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
rt_sigaction(SIGCHLD, {0x412dd0, [CHLD], SA_RESTORER|SA_RESTART, 0x7f5b9a0554b0}, {SIG_DFL, [CHLD], SA_RESTORER|SA_RESTART, 0x7f5b9a0554b0}, 8) = 0
rt_sigaction(SIGUSR1, {0x4165c0, [USR1], SA_RESTORER|SA_RESTART, 0x7f5b9a0554b0}, {SIG_DFL, [], SA_RESTORER, 0x7fcb85a254b0}, 8) = 0
brk(0x12a4000)                          = 0x12a4000
stat(".", {st_mode=S_IFDIR|0777, st_size=0, ...}) = 0
open(".", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFDIR|0777, st_size=0, ...}) = 0
getdents(3, /* d_reclen < sizeof(struct dirent) *//* 1 entries */, 32768) = 540
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
open("Makefile", O_RDONLY)              = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fstat(3, {st_mode=S_IFREG|0777, st_size=25933, ...}) = 0
read(3, "# This Makefile is for the SelSw"..., 512) = 512
read(3, "{  }\n#     PREREQ_PM => { Test::"..., 512) = 512
read(3, "\nLD = x86_64-linux-gnu-gcc\nLDDLF"..., 512) = 512
read(3, "SEP)\nNAME = SelSweepRegion::Find"..., 512) = 512
read(3, "RLPREFIX = /usr\nSITEPREFIX = /us"..., 512) = 512
read(3, "CH = $(DESTDIR)$(INSTALLSITEARCH"..., 512) = 512
read(3, "$(INSTALLSITESCRIPT)\nINSTALLVEND"..., 512) = 512
read(3, "ocal/man/man3\nDESTINSTALLSITEMAN"..., 512) = 512
read(3, "ib/x86_64-linux-gnu/perl/5.22/CO"..., 512) = 512
read(3, "SION = 70401\n\n# FULLEXT = Pathna"..., 512) = 512
read(3, "DEP = \n\n# Handy lists of source "..., 512) = 512
read(3, "T_STATIC      = \nINST_DYNAMIC   "..., 512) = 512
read(3, "autosplit section:\n# Usage: $(AU"..., 512) = 512
read(3, "= $(ABSPERLRUN) -MExtUtils::Comm"..., 512) = 512
read(3, "Utils::Command::MM -e 'warn_if_o"..., 512) = 512
read(3, "P)\nCI = ci -u\nRCS_LABEL = rcs -N"..., 512) = 512
read(3, "REFIX)\"\n\n\n# --- MakeMaker specia"..., 512) = 512
read(3, "_MAKEFILE) blibdirs\n\t$(NOECHO) $"..., 512) = 512
read(3, "ile.PL\n\t$(NOECHO) $(MKPATH) $(IN"..., 512) = 512
read(3, "T_ARCHAUTODIR)$(DFSEP).exists ::"..., 512) = 512
read(3, "NST_SCRIPT)$(DFSEP).exists\n\n$(IN"..., 512) = 512
read(3, "- MakeMaker dynamic_bs section:\n"..., 512) = 512
read(3, " \"-MExtUtils::Command::MM\" -e po"..., 512) = 512
read(3, "# Delete temporary files but do "..., 512) = 512
read(3, "e.[0-9][0-9][0-9] core.[0-9][0-9"..., 512) = 512
read(3, " files\nrealclean purge ::  clean"..., 512) = 512
read(3, "Maker: '\\''0'\\''' >> META_new.ym"..., 512) = 512
read(3, "et/META-spec-v1.4.html' >> META_"..., 512) = 512
read(3, "TA_new.yml\n\t-$(NOECHO) $(MV) MET"..., 512) = 512
read(3, "Converter version 2.150001\",' >>"..., 512) = 512
read(3, "FindGene\",' >> META_new.json\n\t$("..., 512) = 512
read(3, "\n\t$(NOECHO) $(ECHO) '           "..., 512) = 512
read(3, ">> META_new.json\n\t$(NOECHO) $(EC"..., 512) = 512
read(3, "\n\n# --- MakeMaker signature sect"..., 512) = 512
read(3, " $(FIRST_MAKEFILE)\n\t$(NOECHO) $("..., 512) = 512
read(3, "istdir\n\t$(PREOP)\n\t$(TO_UNIX)\n\t$("..., 512) = 512
read(3, "CHO) $(ECHO) 'Created $(DISTVNAM"..., 512) = 512
read(3, "tion:\n\nci :\n\t$(PERLRUN) \"-MExtUt"..., 512) = 512
read(3, "' \\\n\t  -e '    or print \"Could n"..., 512) = 512
read(3, "-e 'eval { maniadd({q{SIGNATURE}"..., 512) = 512
read(3, "or_install doc_vendor_install\n\t$"..., 512) = 512
read(3, "CHLIB)\" \"$(DESTINSTALLARCHLIB)\" "..., 512) = 512
read(3, "LIB)\" \"$(DESTINSTALLSITEARCH)\" \\"..., 512) = 512
read(3, "PT)\" \"$(DESTINSTALLVENDORSCRIPT)"..., 512) = 512
read(3, ")\" \\\n\t\t>> \"$(DESTINSTALLSITEARCH"..., 512) = 512
read(3, "proach here, but it's worth it.\n"..., 512) = 512
read(3, "==\"\n\t$(NOECHO) $(ECHO) \"==> Plea"..., 512) = 512
read(3, "=static \\\n\t\tMAKEAPERL=1 NORECURS"..., 512) = 512
read(3, "ic :: pure_all\n\tPERL_DL_NONLAZY="..., 512) = 512
read(3, ").ppd\n\t$(NOECHO) $(ECHO) '    <I"..., 512) = 512
read(3, "T_PM)\n\t$(NOECHO) $(ABSPERLRUN) -"..., 512) = 333
read(3, "", 512)                        = 0
close(3)                                = 0
stat("RCS", 0x7fffed03dab0)             = -1 ENOENT (No such file or directory)
stat("SCCS", 0x7fffed03dab0)            = -1 ENOENT (No such file or directory)
stat("Makefile", {st_mode=S_IFREG|0777, st_size=25933, ...}) = 0
clock_gettime(CLOCK_REALTIME, {1480466050, 738992500}) = 0
stat("Makefile.PL", {st_mode=S_IFREG|0777, st_size=359, ...}) = 0
stat("/usr/lib/x86_64-linux-gnu/perl/5.22/Config.pm", {st_mode=S_IFREG|0644, st_size=3330, ...}) = 0
stat("/usr/lib/x86_64-linux-gnu/perl/5.22", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
open("/usr/lib/x86_64-linux-gnu/perl/5.22", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
getdents(3, /* d_reclen < sizeof(struct dirent) *//* 1 entries */, 32768) = 2126
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
stat("/usr/lib/x86_64-linux-gnu/perl/5.22/RCS", 0x7fffed03c5e0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64-linux-gnu/perl/5.22/SCCS", 0x7fffed03c5e0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64-linux-gnu/perl/5.22/CORE/config.h", {st_mode=S_IFREG|0644, st_size=161245, ...}) = 0
stat("/usr/lib/x86_64-linux-gnu/perl/5.22/CORE", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
open("/usr/lib/x86_64-linux-gnu/perl/5.22/CORE", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
brk(0x12c5000)                          = 0x12c5000
getdents(3, /* d_reclen < sizeof(struct dirent) *//* 1 entries */, 32768) = 2136
getdents(3, /* 0 entries */, 32768)     = 0
brk(0x12bd000)                          = 0x12bd000
close(3)                                = 0
stat("/usr/lib/x86_64-linux-gnu/perl/5.22/CORE/RCS", 0x7fffed03c5e0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64-linux-gnu/perl/5.22/CORE/SCCS", 0x7fffed03c5e0) = -1 ENOENT (No such file or directory)
stat("makemakerdflt", 0x7fffed03b8c0)   = -1 ENOENT (No such file or directory)
stat("pure_all", 0x7fffed03b760)        = -1 ENOENT (No such file or directory)
stat("blib/lib/SelSweepRegion/.exists", {st_mode=S_IFREG|0777, st_size=0, ...}) = 0
stat("blib/arch/.exists", {st_mode=S_IFREG|0777, st_size=0, ...}) = 0
stat("blib/lib/auto/SelSweepRegion/FindGene/.exists", {st_mode=S_IFREG|0777, st_size=0, ...}) = 0
stat("blib/arch/auto/SelSweepRegion/FindGene/.exists", {st_mode=S_IFREG|0777, st_size=0, ...}) = 0
stat("blib/bin/.exists", {st_mode=S_IFREG|0777, st_size=0, ...}) = 0
stat("blib/script/.exists", {st_mode=S_IFREG|0777, st_size=0, ...}) = 0
stat("blib/man1/.exists", {st_mode=S_IFREG|0777, st_size=0, ...}) = 0
stat("blib/man3/.exists", {st_mode=S_IFREG|0777, st_size=0, ...}) = 0
pipe([3, 4])                            = 0
close(4)                                = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f5b9a8709d0) = 167
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 167
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=167, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
rt_sigreturn({mask=[]})                 = 167
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f5b9a8709d0) = 168
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 168
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=168, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
rt_sigreturn({mask=[]})                 = 168
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
stat("pm_to_blib", {st_mode=S_IFREG|0777, st_size=0, ...}) = 0
stat("lib/SelSweepRegion/FindGene.pm", {st_mode=S_IFREG|0777, st_size=7149, ...}) = 0
stat("lib/SelSweepRegion", {st_mode=S_IFDIR|0777, st_size=0, ...}) = 0
open("lib/SelSweepRegion", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 4
fstat(4, {st_mode=S_IFDIR|0777, st_size=0, ...}) = 0
getdents(4, /* d_reclen < sizeof(struct dirent) *//* 1 entries */, 32768) = 74
getdents(4, /* 0 entries */, 32768)     = 0
close(4)                                = 0
stat("lib/SelSweepRegion/RCS", 0x7fffed03c1f0) = -1 ENOENT (No such file or directory)
stat("lib/SelSweepRegion/SCCS", 0x7fffed03c1f0) = -1 ENOENT (No such file or directory)
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f5b9a8709d0) = 169
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 169
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=169, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
rt_sigreturn({mask=[]})                 = 169
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f5b9a8709d0) = 171
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 171
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=171, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
rt_sigreturn({mask=[]})                 = 171
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
stat("pm_to_blib", {st_mode=S_IFREG|0777, st_size=0, ...}) = 0
stat("subdirs", 0x7fffed03b600)         = -1 ENOENT (No such file or directory)
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f5b9a8709d0) = 172
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 172
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=172, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
rt_sigreturn({mask=[]})                 = 172
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
stat("subdirs", 0x7fffed03b580)         = -1 ENOENT (No such file or directory)
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f5b9a8709d0) = 173
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 173
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=173, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
rt_sigreturn({mask=[]})                 = 173
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f5b9a8709d0) = 174
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 174
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=174, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
rt_sigreturn({mask=[]})                 = 174
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f5b9a8709d0) = 175
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 175
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=175, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
rt_sigreturn({mask=[]})                 = 175
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
stat("pure_all", 0x7fffed03b6e0)        = -1 ENOENT (No such file or directory)
stat("manifypods", 0x7fffed03b760)      = -1 ENOENT (No such file or directory)
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f5b9a8709d0) = 176
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 22}], 0, NULL) = 176
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=176, si_uid=1000, si_status=22, si_utime=0, si_stime=0} ---
rt_sigreturn({mask=[]})                 = 176
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=2995, ...}) = 0
read(4, "# Locale name alias data base.\n#"..., 512) = 512
read(4, "See the\n# GNU General Public Lic"..., 512) = 512
read(4, "nd for the time being for\n# back"..., 512) = 512
read(4, "hese lines were removed\n# becaus"..., 512) = 512
read(4, "8859-1\ngalego\t\tgl_ES.ISO-8859-1\n"..., 512) = 512
read(4, "O.ISO-8859-1 nb_NO.ISO-8859-1\nno"..., 512) = 435
read(4, "", 512)                        = 0
close(4)                                = 0
open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF-8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US.UTF-8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US.utf8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en.UTF-8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en.utf8/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en/LC_MESSAGES/make.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
fstat(1, {st_mode=S_IFCHR|0660, st_rdev=makedev(4, 1), ...}) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(1, "Makefile:418: recipe for target "..., 52) = 52
write(2, "make: *** [manifypods] Error 22\n", 32) = 32
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM XCPU XFSZ], NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
chdir("/mnt/c/Users/wjp/Desktop/1/SelSweepRegion-FindGene-0.01") = 0
close(1)                                = 0
exit_group(2)                           = ?
+++ exited with 2 +++

**Comment by stehufntdev** [comment] 2016-11-30 16:40
Thanks for sending out the strace!  It looks like the einval error (22) is coming from the child process but the trace was only collected on the parent process:

wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 22}], 0, NULL) = 176

Can you please rerun the strace with the -f option so the child process is traced as well?

**Comment by JINPENG-WANG** [comment] 2016-12-01 00:32
You are welcome. The strace result is listed below.  

[strace.txt](https://github.com/Microsoft/BashOnWindows/files/623380/strace.txt)

Thank you for your reply.

**Comment by stehufntdev** [comment] 2016-12-01 17:49
Thanks again!  Looks like the failure is coming from an open call, but it's not obvious why it is failing since the file was reported as not existing a few lines above:

44    stat("blib/man3/SelSweepRegion::FindGene.3pm", 0x1a5a298) = -1 ENOENT (No such file or directory)
...
44    open("blib/man3/SelSweepRegion::FindGene.3pm", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 EINVAL (Invalid argument) 44    write(2, "Can't write-open blib/man3/SelSw"..., 131) = 131

I filed a task on our side so we can debug further to see what is going on.

**Comment by JINPENG-WANG** [comment] 2016-12-03 12:40
Thanks for your work.

**Comment by yorickdowne** [comment] 2016-12-05 22:50
Are you installing from somewhere in the /mnt path or from ~ ? I had a similar issue and resolved it by installing from within the Ubuntu file system, not the mounted Windows file system.

Also check out https://github.com/Microsoft/BashOnWindows/issues/186 . If that's not taken care of, perl module installations will fail. The "file not existing" line would hint towards the fact this might be related to the same issue in 186.

**Comment by JINPENG-WANG** [comment] 2016-12-06 01:06
@yorickdowne  You are right. The module was successfully installed from the directory under ~ other than that under /mnt.  Thanks very much.

**Comment by stehufntdev** [comment] 2016-12-06 01:08
@JINPENG-WANG it sounds like the issue is resolved, but wanted to double check with you before closing out the thread.

**Comment by JINPENG-WANG** [comment] 2016-12-06 01:47
@stehufntdev  Yes, the issue is resolved. Thanks for all of you.

**Closed** 2016-12-06 01:47 UTC
Labels: bug
