### ISSUE TITLE
Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed

### ISSUE THREAD

**Issue by kdwycz** [Microsoft/BashOnWindows#2142] opened 2017-05-22 04:34 UTC
I use some command get a problem ``http: ../sysdeps/posix/getaddrinfo.c:2603: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.`` 

![](http://i.imgur.com/7yNFGUR.png)

in some command as ``apt`` or ``pip``, replace command the error miss

i tired search similar issue and reinstall windows and wsl, don't fix this problem

![](http://i.imgur.com/MoiY1xG.png)

My Windows version:  Microsoft Windows [版本 10.0.15063]

i'm sorry about my pool English 😭

**Comment by justid** [comment] 2017-05-22 06:38
You just need to close ipv6 in windows10

**Comment by kdwycz** [comment] 2017-05-22 07:08
@justid  thank you for you advice

but it not work for me

i guess ``eth2`` config cause this problem. bug i can't disable ``eth2`` or modify the priority

**Comment by justid** [comment] 2017-05-22 07:41
@kdwycz please go check your network setting by command ifconfig,see if ipv6 address gone.

**Comment by kdwycz** [comment] 2017-05-22 12:12
@justid i try disable windows ipv6

```
kdwycz@DESKTOP-C974ORK:~$ ifconfig
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Global
          UP LOOPBACK RUNNING  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wifi0     Link encap:UNSPEC  HWaddr B4-AE-2B-C6-00-C8-00-00-00-00-00-00-00-00-00-00
          inet addr:192.168.8.190  Bcast:192.168.8.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

kdwycz@DESKTOP-C974ORK:~$ sudo service ssh restart
sshd: ../sysdeps/posix/getaddrinfo.c:2603: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
Aborted (core dumped)
```

**Comment by sunjoong** [comment] 2017-05-22 12:52
> You just need to close ipv6 in windows10

> i try disable windows ipv6. but i don't know how to disable lo ipv6

@kdwycz - I could not sure this is a solution but... http://www.techunboxed.com/2014/10/how-to-disable-ipv6-in-windows-10.html describes how to disable ipv6 in windows 10.

**Comment by kdwycz** [comment] 2017-05-22 13:14
@sunjoong thank you, but can't effective

sad >_<

**Comment by justid** [comment] 2017-05-22 14:28
@kdwycz
run
`reg add hklm\system\currentcontrolset\services\tcpip6\parameters /v DisabledComponents /t REG_DWORD /d 0xFFFFFFFF`
then reboot

**Comment by kdwycz** [comment] 2017-05-22 15:06
@justid don't work >_<

i start to download recovery Image file to initial my computer

Why should I use Surface instead Mac to coding? Maybe I should wait a year

**Comment by ycecube** [comment] 2017-05-22 15:27
Check the other issue, maybe you have a similar as I had: https://github.com/Microsoft/BashOnWindows/issues/2120#issuecomment-302820507

**Comment by kdwycz** [comment] 2017-05-23 00:37
@ycecube Thank you for providing the idea, not applicable for me. But help me find the final answer

Finally, I found a [huorong antivirus software](http://www.huorong.cn/), After the uninstall the computer repair

**Comment by justid** [comment] 2017-05-23 07:14
@kdwycz
Please close this issues if everything works fine.

**Closed** 2017-05-24 09:15 UTC

**Comment by 599281224** [comment] 2017-06-13 10:17
how do you fix thing problem

**Comment by sunjoong** [comment] 2017-06-13 10:28
> Finally, I found a huorong antivirus software, After the uninstall the computer repair

@599281224 - It looks like Anti-Virus made this problem.

**Comment by kdwycz** [comment] 2017-06-14 08:10
@599281224  uninstall huorong antivirus software

**Comment by noahzark** [comment] 2017-08-09 18:27
I solved the same problem by Disabling VMware virtual network adapters, and didn't turn off IPV6. Don't know if it would be helpful

**Comment by vtroop** [comment] 2017-09-09 07:20
i found where the problem is. it was caused by the third party softwares such as tencent network manager，antivirus software.
to solve the problem, you need to reset the network in the windows And in my windows 10 build 16278, you can find the reset network button in the setting panel

**Comment by razvan-panda** [comment] 2017-11-03 22:51
@noahzark `Disabling VMware virtual network adapters` is also what worked for me.

**Comment by razvan-panda** [comment] 2017-11-03 22:57
Ehm, no, actually it is randomly failing :( Failed on another command

```
neo@wsl-pc:~$ nix-env -i nix
warning: there are multiple derivations named ‘nix-1.11.15’; using the first one
replacing old ‘nix-1.11.15’
installing ‘nix-1.11.15’
download-from-binary-cache.pl: perl: ../sysdeps/posix/getaddrinfo.c:2542: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
error: substituter ‘download-from-binary-cache.pl’ died unexpectedly
```

**Comment by noahzark** [comment] 2017-11-03 23:11
@razvan-panda Hi, Razvan, could you check your network setting by command **ifconfig**, and see if there's some weird adapters?

**Comment by razvan-panda** [comment] 2017-11-03 23:35
@noahzark 

```
neo@wsl-pc:~$ ifconfig
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Global
          UP LOOPBACK RUNNING  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wifi0     Link encap:UNSPEC  HWaddr 20-68-9D-6F-30-C3-00-00-00-00-00-00-00-00-00-00
          inet addr:192.168.0.3  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: 2a02:8084:e82:4880:e85b:3d32:fe7e:5cd8/64 Scope:Global
          inet6 addr: 2a02:8084:e82:4880:fc52:a74d:135b:5120/128 Scope:Global
          inet6 addr: fe80::e85b:3d32:fe7e:5cd8/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

**Comment by razvan-panda** [comment] 2017-11-03 23:36
Another example IPv6 error:

```
neo@wsl-pc:~$ curl https://nixos.org/nix/install | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2358  100  2358    0     0   3485      0 --:--:-- --:--:-- --:--:--  3488
downloading Nix 1.11.15 binary tarball for x86_64-linux from 'https://nixos.org/releases/nix/nix-1.11.15/nix-1.11.15-x86_64-linux.tar.bz2' to '/tmp/nix-binary-tarball-unpack.vvG2VOMkfk'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28.3M  100 28.3M    0     0  9987k      0  0:00:02  0:00:02 --:--:-- 9987k
performing a single-user installation of Nix...
copying Nix to /nix/store.................................
initialising Nix database...
replacing old ‘nix-1.11.15’
installing ‘nix-1.11.15’
curl: ../sysdeps/posix/getaddrinfo.c:2542: getaddrinfo: Assertion `IN6_IS_ADDR_V4MAPPED (sin6->sin6_addr.s6_addr32)' failed.
Aborted (core dumped)
Use of uninitialized value $url in scalar chomp at /nix/store/b4s1gxiis1ryvybnjhdjvgc5sr1nq0ys-nix-1.11.15/bin/nix-channel line 111.
Use of uninitialized value $url in concatenation (.) or string at /nix/store/b4s1gxiis1ryvybnjhdjvgc5sr1nq0ys-nix-1.11.15/bin/nix-channel line 112.
/nix/store/b4s1gxiis1ryvybnjhdjvgc5sr1nq0ys-nix-1.11.15/bin/nix-channel: unable to check ‘’
```

**Comment by smilearric** [comment] 2017-11-23 11:18
Hello,

**Disabling IPV6 or prefer IPV4 on Windows 10 (and restore): https://support.microsoft.com/en-us/help/929852/how-to-disable-ipv6-or-its-components-in-windows**

Works for me pushing git commits to BitBucket from my Ubuntu Bash console on Windows 10 (https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/)

Taken from: https://mobilefish.de/disable-ipv6-ubuntu-linux-and-windows-10 which personal solution did not work for me however.

Hope this helps.

**Comment by therealkenc** [comment] 2017-11-23 23:17
Duping down to #508. Thanks for the good info @smilearric

**Comment by qysnn** [comment] 2017-11-27 06:23
I have tried all the suggested solutions above and nothing works.
But I accidentally find the solution that works for me.
1. Delete the `host` file in `C:\Windows\System32\drivers\etc`.
2. Repeatedly run the command that caused this error.

For example, I encountered this error when trying to run `sudo -H pip install xxxx`. After I deleted `host` file, I run this command 5 times and finally the error is gone and my installation succeeded.
By the way, my Windows version is Windows 10 1709 OS Build 16299.64 and I installed WSL from Microsoft Store.

**Comment by therealkenc** [comment] 2017-11-27 06:55
Unfortunately "trying **all** the suggested solutions" is difficult because there are do many dupes for [`IN6_IS_ADDR_V4MAPPED`](https://github.com/Microsoft/WSL/issues?utf8=%E2%9C%93&q=is%3Aissue+IN6_IS_ADDR_V4MAPPED). For example one suggestion is re-imaging Windows, which _will work_, but I don't suggest it. It works because it isolates the external factor that is causing the problem.

The TDI filter bypass changes made it into 17046, per #1554 ([message](https://github.com/Microsoft/WSL/issues/1554#issuecomment-346442640)). Please give that a try and see if it fixes your case.

**Comment by Diluka** [comment] 2017-12-26 06:30
I disabled windows firewall and system proxy and this issue still remain.

**Comment by kingaj12** [comment] 2018-04-06 00:59
I ran into this issue trying to do `conda install`.  When I switched to `sudo /root/anaconda3/bin/conda install` the problem went away.  No idea why.

**Comment by djangogo** [comment] 2018-04-06 07:42
I find the following solution is effective.
I add the following line to the /etc/ssh/sshd_config  to force sshd to listen on the ipv4 address.
```
ListenAddress 0.0.0.0
```
then  restart the sshd service
sudo service ssh restart

**Comment by kingaj12** [comment] 2018-04-10 01:02
I had this problem running apt-get.  I found [this solution](https://www.vultr.com/docs/force-apt-get-to-ipv4-or-ipv6-on-ubuntu-or-debian) to be helpful.

**Comment by mcrapts** [comment] 2018-06-01 15:58
For me the following solution worked:

1. Uncomment the following line in `/etc/gai.conf`: 
`precedence ::ffff:0:0/96  100`
2. Close your WSL shell prompt by typing "exit"
3. Restart WSL

Credits to [this person](https://www.reddit.com/r/bashonubuntuonwindows/comments/7u1le5/disable_ipv6_or_prefer_ipv4_first/)
