### ISSUE TITLE
Git command line is extremely slow

### ISSUE THREAD

**Issue by KVohra95** [Microsoft/BashOnWindows#1566] opened 2017-01-03 11:35 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
using git commands take an excruciatingly long time

* Expected results
git status should be almost instant

* Actual results (with terminal output if applicable)
It takes almost 30 seconds to run git status

* Your Windows build number
14393.576

* Steps / All commands required to reproduce the error from a brand new installation 
sudo apt-get install git
git status

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment] 2017-01-03 21:02
#1305, #981

**Comment by stehufntdev** [comment] 2017-01-04 17:01
Thanks for reporting the issue, we are tracking this internally.  Closing this out as a duplicate of #1305 so we can track the issue in one place.

**Closed by stehufntdev** 2017-01-04 17:01 UTC
Labels: duplicate, file system
