### ISSUE TITLE
Cannot create SSH Tunnel

### ISSUE THREAD

**Issue by camsteffen** [Microsoft/BashOnWindows#157] opened 2016-04-12 16:45 UTC
```
# ssh -L 3001:localhost:3001 myserver -N
setsockopt IPV6_V6ONLY: Invalid argument
bind: Invalid argument
channel_setup_fwd_listener: cannot listen to port: 3001
Could not request local forwarding.
```

#68 
#128

**Comment by sunilmut** [comment] 2016-04-13 05:48
Yes, I can confirm that the IPV6_V6ONLY socket option is currently not supported. We have opened a bug on our end to track this. Thanks for the feedback.

**Comment by camsteffen** [comment] 2016-04-13 08:33
Is there a workaround to use ipv4?

**Comment by dreyks** [comment] 2016-04-13 14:21
does this work?
```
# ssh -4 -L 3001:localhost:3001 myserver -N
```

**Comment by camsteffen** [comment] 2016-04-13 22:32
yes, thank you!

**Comment by sunilmut** [comment] 2016-09-14 21:36
With the help of the Windows networking team, we were able to fully implement the IPV6_V6ONLY flag. That should resolve the issue here. The fix is still in our dev branch, but should soon hit the release branch.

**Comment by sunilmut** [comment] 2016-09-29 02:23
Just FYI that the IPV6_V6ONLY issue is fixed in 14936 (see [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes))

**Comment by sunilmut** [comment] 2016-10-14 18:44
Closing this out since this should be now resolved in Insider builds 14942+. If it is broken, please let us know. And, thanks for all the feedback.

**Closed by sunilmut** 2016-10-14 18:44 UTC
Labels: fixed
