### ISSUE TITLE
Unlink syscall does not allow file to be reopened after

### ISSUE THREAD

**Issue by kayakyakr** [Microsoft/BashOnWindows#1357] opened 2016-11-13 22:28 UTC
I am trying to debug ember-cli running on WSL. I have it initially building (without Watchman), and receiving file change notifications, but on a file change, which should fire a rebuild, I'm having a failed syscall.

Here are the relevant lines in strace:

```
... start build
[pid  9468] stat("/mnt/c/project/home/tmp/build.lock", 0x7ffffa50f700) = -1 ENOENT (No such file or directory)
[pid  9468] open("/mnt/c/project/home/tmp/build.lock", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 12
... complete build
[pid  9468] stat("/mnt/c/project/home/tmp/build.lock", {st_mode=S_IFREG|0777, st_size=0, ...}) = 0
[pid  9468] unlink("/mnt/c/project/home/tmp/build.lock") = 0
... start rebuild
[pid  9468] stat("/mnt/c/project/home/tmp/build.lock", 0x7ffffa50f8e0) = -1 ENOENT (No such file or directory)
[pid  9468] open("/mnt/c/project/home/tmp/build.lock", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = -1 ENOENT (No such file or directory)
```

I have checked in windows file explorer: that file is definitely there. It's in a very strange state, though. Windows doesn't have any sort of permissions to view, edit, or modify that file. Bash straight-up doesn't see that file. As soon as the `ember build --watch` process is killed, the file is removed, so it's inexorably linked to that process.

I'm about to switch off of Windows again and can't tell you when I'll be able to get back to debug some more, but let me know if you have any suggestions on how to look for more information.

**Comment by aseering** [comment] 2016-11-13 22:35
@kayakyakr -- you mentioned that you found this file in Windows Explorer?  Have you tried to interact with that directory in other ways from Windows?

`/home` is not a Windows directory; it is a WSL/Linux directory.  It's true that WSL maintains a directory under AppData that serves as the raw data storage for that directory.  But that directory is for WSL's private use; if other applications try to modify it, it can cause a variety of exciting problems, including issues like what you're describing.

If a WSL-internal file gets into a bad state due to a Windows program trying to interact with it, the best thing seems to be to somehow remove the file and re-create it within WSL.

If you need to work with a file in both Windows and Linux, you can put it in `/mnt/c/...`.

**Comment by kayakyakr** [comment] 2016-11-13 22:39
Sorry, /home is a directory in my ember-cli project. I removed the rest because it was a long blast of semi-personal, semi-proprietary information embedded in the file string. The project itself is located in my windows documents and symlinked into my ubuntu home directory.

**Comment by kayakyakr** [comment] 2016-11-13 22:44
I'm going to throw out a random guess that it has something to do with the unlink system call which does not error, but may not be doing what it needs to do.

**Comment by aseering** [comment] 2016-11-13 22:52
Hm, interesting...  Thanks for the clarifications.

Is there anything else special about this path?  Is it just a regular directory on a regular NTFS volume?

Also -- is it possible that this particular failure is a red herring?  Specifically, I wonder if this file is a temporary file.  The way "file goes away when the process exits" is often implemented in Linux is for the file to be `unlink()`ed immediately after being opened.  In which case the file shouldn't show up on the Linux side, but I'm not sure that Windows has a native representation for an unlinked file?  In that case, the failing system call could just be the app making really sure that the file is gone, and the actual failure could be triggered by an earlier system call.

**Comment by kayakyakr** [comment] 2016-11-13 23:58
Just a regular on a regular. The file is a temp file, so the immediate unlink does make sense. The second open is happening just before a rebuild is started, so it's not part of it making sure the file it gone, it's part of it trying to re-lock the build.

I am more convinced the failed open is what is preventing the process from continuing. That second open is not succeeding because the file still technically exists after the unlink and since the process couldn't get a lock, it does not continue.

`open -> unlink -> open` should produce a file.

**Comment by therealkenc** [comment] 2016-11-14 09:08
This is a good catch. Unlink doesn't behave on DriveFS (ie, /mnt/c/...) correctly.
```
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>

int main(int argc, const char* argv[]) {
  const char* path = "./foo.lock";
  open(path, O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666);
  unlink(path);
  struct stat st;
  if (stat(path, &st) < 0) 
    perror("stat: ");
  if (open(path, O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) < 0)
    perror("open: ");
}
```

**Comment by kayakyakr** [comment] 2016-11-14 17:20
@therealkenc more like therealmvp

**Comment by benhillis** [comment] 2016-11-14 17:23
@kayakyakr -  Agreed!

**Comment by kayakyakr** [comment] 2016-12-08 17:22
Any update on this issue?

**Comment by aseering** [comment] 2017-02-26 23:15
I recently hit this WSL limitation as well.  (Filed #1730 , which is a dupe of this ticket but has slightly more details.)  It can be reproduced as follows:

```
cd /mnt/c/Users/<me>
echo "Hello" > tmp.txt
strace perl -pi -e 's/Hello/World/' tmp.txt
```

In VolFs, the perl command will successfully update the file.  In DrvFs, it will remove the file entirely, and fail with an error.  Which is kind of an unfortunate failure mode.

**Comment by benhillis** [comment] 2017-03-24 23:23
Marking as a duplicate of #966 which we are currently working on a fix for.

**Closed by benhillis** 2017-03-24 23:23 UTC
Labels: bug

**Comment by therealkenc** [comment] 2017-03-24 23:37
You shouldn't end your sentence with a preposition at. 😉

**Comment by benhillis** [comment] 2017-03-24 23:38
@therealkenc - come on man it's Friday!
