### ISSUE TITLE
BSOD while setting up llvm runtime

### ISSUE THREAD

**Issue by ringosham** [Microsoft/BashOnWindows#1310] opened 2016-11-02 17:05 UTC
As the title says. My laptop suddenly blue screened while setting up one of the dependencies of clang. It does no harm to the machine and the package can continue to install after rebooting.

I managed to reproduce this by fully uninstall the subsystem and install clang again.

Stop code: SECURITY_KERNEL_CHECK_FAILURE
Minidump: https://drive.google.com/open?id=0BwZoVuWgUu3hX0R1R1duSGkwQlU
Later I found out that it blue screened while setting up llvm-3.4-runtime.

Windows build number: 14931.300 (latest slow ring)

**Comment by sunilmut** [comment] 2016-11-02 17:11
@ringosham - Thanks for reporting this. Can you please share the explicit repro steps?

**Comment by ringosham** [comment] 2016-11-02 17:12
@sunilmut 
1. Completely reinstall linux and removed all user data
2. sudo apt install clang
That's all I did.

**Comment by sunilmut** [comment] 2016-11-02 17:55
Thanks for the quick response. I was able to `sudo apt install clang` (also after a complete reinstall) on the 14955 build, which is the latest insider build. If someone else can also confirm the same, then maybe the issue is fixed in the latest build?

**Comment by benhillis** [comment] 2016-11-02 18:08
Thanks for reporting this.  I took a look at your minidump and verified that the fix for this issue is in build 14935 and later.

Marking as duplicate of #1034.

**Closed by benhillis** 2016-11-02 18:08 UTC
Labels: duplicate
