### ISSUE TITLE
Starting Bash results in Error: 0x80070005

### ISSUE THREAD

**Issue by joakime** [Microsoft/BashOnWindows#2095] opened 2017-05-12 19:55 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

Starting Bash

* What's wrong / what should be happening instead:

Bash should start without issues

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

Strace not available.

Per the instructions on Issue #473 I'm submitting the traces as requested.
[wsl-traces.zip](https://github.com/Microsoft/BashOnWindows/files/997786/wsl-traces.zip)

I did perform an `lxrun /uninstall /full /y` today to eliminate my 14.04 system and upgrade to 16.04
Once I had a successful `lxrun /install` I was able to run bash once.

I then unpacked my home directory backup.
My home directory backup has replacements for ...

```
.ssh/    -> (symlink to /mnt/c/Users/joakim/.ssh)
.vim/    -> (symlink to /mnt/c/Users/joakim/vimfiles)
.m2/     -> (symlink to /mnt/c/Users/joakim/.m2)
.bashrc
.bash_aliases
.bash_logout
.gitconfig
.gvimrc
.profile
.vim
.vimrc
java/    -> (symlink to /mnt/c/Users/joakim/java/wsl)
```

After the unpack (in bash on the first run) i exited bash and attempted to restart, when this error occurred.

**Comment by joakime** [comment] 2017-05-12 19:58
I suspect something I did in my home directory caused this, is there a way to start bash in a different home directory?

**Comment by sunjoong** [comment] 2017-05-13 01:14
@joakime - In windows PowerShell, "`lxrun /setdefaultuser root`".

> Once I had a successful lxrun /install I was able to run bash once.

This means you had installed WSL successfully and maden default user, might be joakim?, I think. When you "`lxrun /install /y`", lxrun does not make default user, but only make root user. If you "`lxrun /install`", lxrun makes root user and normal user like joakim. The command "`lxrun /setdefaultuser root`" switch default user to root; of course, you can switch to anoter user like "`lxrun /setdefaultuser joakim`".

> After the unpack (in bash on the first run) i exited bash and attempted to restart, when this error occurred.

After launching bash with root user, you could check why this happens, I think.

**Comment by benhillis** [comment] 2017-07-28 00:05
After looking at the trace I'm fairly certain this is a duplicate of #651.

**Closed** 2017-07-28 00:06 UTC
Labels: duplicate
