### ISSUE TITLE
Most folders under /mnt/c/ missing directory attribute

### ISSUE THREAD

**Issue by will-l-h** [Microsoft/BashOnWindows#2436] opened 2017-08-19 01:12 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Version 10.0.16257.1

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Start Ubuntu (from Windows Store or legacy Bash on Ubuntu on Windows)
cd /mnt/c/test/
try to cd to a sub directory that I know is there
-bash: cd: a: Not a directory
ls -la
total 0
drwxrwxrwx 0 root root 512 Aug 18 20:40 .
drwxrwxrwx 0 root root 512 Aug 18 20:25 ..
-rwxrwxrwx 1 root root   0 Aug 18 20:25 a
-rwxrwxrwx 1 root root   0 Aug 18 20:25 b
-rwxrwxrwx 1 root root   0 Aug 18 20:25 c

a, b, and c are folders

if I navigate into the folder in Windows Explorer and re-run the command, then the directories are recognized until I exit Ubuntu and start it again

total 0
drwxrwxrwx 0 root root 512 Aug 18 20:40 .
drwxrwxrwx 0 root root 512 Aug 18 20:59 ..
drwxrwxrwx 0 root root 512 Aug 18 20:25 a
drwxrwxrwx 0 root root 512 Aug 18 20:25 b
drwxrwxrwx 0 root root 512 Aug 18 20:25 c

* What's wrong / what should be happening instead:
These are normal folders that were created in Windows; I should be able to cd into them in WSL

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)
Run for both the before and after Windows Explorer action mentioned above

https://gist.github.com/will-l-h/72b110ed6d15ec9c146a5673f0895b33

* Other things I've tried that had no effect
Uninstalled / reinstalled Windows Store Ubuntu
Turned Off WSL, rebooted, turned on WSL (under Windows Features)
Used the new drvfs feature to check the behavior on a usb drive

**Comment by wmzy** [comment] 2017-08-19 02:39
I encountered the same problem.

**Comment by will-l-h** [comment] 2017-08-19 15:01
@wmzy Good to hear that I'm not alone in some broken install. 

Are you also running Windows Insider?

**Comment by wmzy** [comment] 2017-08-20 00:55
@will-l-h Yes,the same version.

**Comment by redbaron** [comment] 2017-08-22 10:51
This is a duplicate of https://github.com/Microsoft/BashOnWindows/issues/2392

**Closed** 2017-08-22 17:01 UTC
Labels: duplicate
