### ISSUE TITLE
Hosts file incomplete after reinstall

### ISSUE THREAD

**Issue by patrick330602** [Microsoft/BashOnWindows#666] opened 2016-07-18 15:32 UTC
Description:

Because of the changing of my computer name, I reinstalled the Bash On Windows. However, it start to prompt error message when I run sudo: unable to resolve host PATRICK-SURFACE. When I look into /etc/hosts file,  I realise that the file is incomplete.

Expected results:
The hosts file should look like this:

``` sh
127.0.0.1 localhost
127.0.1.1 PATRICK-SURFACE

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```

Actual results:

``` sh
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```

Windows build number: 14390

Steps / commands required to reproduce the error:
1. Change the computer name;
2. Reinstall bash;
3. this happened.

**Comment by rodrymbo** [comment] 2016-07-18 19:56
Mine is doing that too, and I didn't even change my computer name. (14390).

_resolv.conf_ gets repopulated/recreated EVERY time we start lxss (apparently), but not _/etc/hosts_? 

Is there documentation of the strategy toward networking?  For example, it doesn't look like the lxss environment is using the native Windows tools to resolve DNS names. It is therefore doing its own name resolution using its own _resolv.conf_ (which it populates from Windows networking every time you start lxss)? It can't even talk to the Windows nameserver on the Windows localhost ( don't think). Yet it seems like it might share the Windows IP address?

_ifconfig_ doesn't appear to work, because _/proc/net/dev_ isn't working (yet?). 

_netstat_ doesn't appear to show which ports are in use. Does that mean we have to jump out to the Windows desktop and check there before selecting a port to listen on? 

If an lxss program is listening on an unused port, will it be using the Windows IP address and firewall rules? How does one open (or block) the lxss using the Windows Firewall? Can we open a particular app, like sshd (if we can ever get it to run) and block others in lxss?

It looks like the lxss environment is using the Windows routing table, which includes VPN settings, so that's good. It might be good to be able to specify a network device to open (e.g. my "real" network interface, or the TAP interface). What do we call the device if a program needs that, e.g. _eth0_? 

Those are probably off-topic to the OP's question, and an off-the-cuff answer here might not be a good use of someone's time compared to a documentation article ... unless the answer is "be patient, it's coming".

**Comment by benhillis** [comment] 2016-07-18 20:02
@rodrymbo - If you'd like /etc/hosts to be regenerated each boot youcan "sudo rm /etc/hosts" and restart bash.exe.  That will generate a new /etc/hosts with your machine's name.

**Comment by rodrymbo** [comment] 2016-07-19 14:13
@benhillis - Thanks, good to know. 

So _/etc/hosts_ gets regenerated now to include the _hostname_. But it doesn't include any of the lines manually added to the Windows hosts file (apparently), whereas _/etc/resolv.conf_ is regenerated depending on what the Windows network interface properties have been set to ... apparently. 

I guess it is good to know how to stop the auto-regeneration of _/etc/hosts_, and that I can manually make changes there to reflect the hosts file in Windows (or custom hosts entries needed for a linux environment) and that they won't be overwritten the next time I restart lxss.

At least I can change the DNS lookup servers in Windows and have them reflected in lxss. But if someone changes them in Windows (e.g. the VPN gets started/restarted and tries to change the DNS resolution servers) it won't get reflected in lxss until it restarts, right?

**Comment by benhillis** [comment] 2016-07-19 15:24
There are two networking related files that we generate at various times:
1. /etc/hosts - We will auto-generate this file only if it contains our special header that you probably saw after you deleted the default /etc/hosts.  This is generated once per instance (after closing all bash.exe windows the instance is torn down).
2. /etc/resolv.conf - This file is always auto-generated by us.  This file will also get updated while an instance is running when networking information changes on your system, for example joining a VPN or a different wifi hotspot.

The above is unlikely to change significantly in the near future.  #149 tracks a request for the WSL version of the hosts file to match the Windows version, which seems like a good idea to me and might be something we investigate post Anniversary Update.

On a related note: Part of what has been so valuable about this GitHub forum has been our users having a say in the design of WSL.  I'd suggest if something isn't working the way you expect, or if you have a suggestion on how something should work let us know. We love getting feedback.

**Comment by rodrymbo** [comment] 2016-07-19 18:06
@benhillis - ooh ... if you are autogenerating files, you could add additional explanation or a link to such in the comments! That way nosey people like me could just read the comments.

**Comment by fpqc** [comment] 2016-07-20 15:51
@benhillis I can confirm this is a bug since 14382 at least.  The old autogenerated /etc/hosts also included the line

127.0.1.1 FPQC-PC

However, now that line is no longer generated by default.  I compared my home and office PCs (I did an lxrun /uninstall at home but not at work) and the office one includes that line while the home one doesn't, which produces weird errors with apt-get.

**Comment by benhillis** [comment] 2016-07-20 15:53
@fpqc - you are correct.  As a workaround if you remove /etc/hosts a new one will be generated that contains the PC name.

**Comment by fpqc** [comment] 2016-07-20 15:59
My workaround was just to add the line, but that works too!

**Comment by kasper93** [comment] 2016-08-03 18:17
> As a workaround if you remove /etc/hosts a new one will be generated that contains the PC name.

@benhillis: Indeed this is the case. But I think this is still bug, because it should be populated after reinstalling bash. So we doesn't need manually rm the file... 
```
lxrun /uninstall
lxrun /install
```

**Comment by sunilmut** [comment] 2016-11-19 00:22
I am closing this issue out. If anyone feels that this needs more work, please let us know and we can reopen it.

**Closed by sunilmut** 2016-11-19 00:22 UTC
Labels: network, workaround-available
