### ISSUE TITLE
IPV6_V6ONLY socket option should fail if the socket is bound

### ISSUE THREAD

**Issue by ericeil** [Microsoft/BashOnWindows#982] opened 2016-08-24 22:37 UTC
On build 14905:

Run the following C++ code:

```cpp
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <err.h>
#include <errno.h>
#include <stdio.h>

int main(void)
{
    printf("Creating socket\n");
    int s = socket(AF_INET6, SOCK_STREAM, 0);
    if (s < 0)
        err(1, "%d", errno);

    printf("Seting V6ONLY=false\n");
    int v6only = 0;
    if (setsockopt(s, IPPROTO_IPV6, IPV6_V6ONLY, &v6only, sizeof(v6only)) != 0)
        err(1, "%d", errno);

    printf("Binding socket\n");
    sockaddr_in6 addr;
    addr.sin6_family = AF_INET6;
    addr.sin6_addr = in6addr_any;
    addr.sin6_port = 0;
    addr.sin6_scope_id = 0;
    if (bind(s, (sockaddr*)&addr, sizeof(addr)) != 0)
        err(1, "%d", errno);

    printf("Setting V6ONLY=true.  We expect this to fail with EINVAL\n");
    v6only = 1;
    if (setsockopt(s, IPPROTO_IPV6, IPV6_V6ONLY, &v6only, sizeof(v6only)) == 0 || errno != EINVAL)
    {
        err(1, "Should have failed with EINVAL, but got %d", errno);
    }

    printf("Success!\n");
    return 0;
}
```

On Linux, attempting to change IPV6_V6ONLY after the socket is bound results in an EINVAL error.  On Windows, this call returns success.

**Comment by sunilmut** [comment] 2016-08-25 17:16
@ericeil - Thanks for reporting the issue. In essence, this is a dupe of #393 . There are some limitations in the IPV6_V6ONLY WSL implementation and we are working with the networking team to resolve them.

**Comment by sunilmut** [comment] 2016-09-14 21:08
With the help of the Windows networking team, we were able to fully implement the IPV6_V6ONLY flag. That resolves this issue. The fix is still in our dev branch, but should soon hit the release branch.

**Comment by sunilmut** [comment] 2016-09-29 02:16
Just FYI that this is fixed in 14936 (see [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes))

**Comment by ericeil** [comment] 2016-09-30 20:08
> this is fixed in 14936

Great!  I tried validating this with our tests, but running those tests on 14936 seems to result in a BSOD.  I assume this is the same probablem as #1138 (and as mentioned in the release notes for this build).  When that issue is resolved, I will try again.

**Comment by sunilmut** [comment] 2016-10-13 05:15
@ericeil Just a note that 14942 is now available.

**Comment by sunilmut** [comment] 2016-10-14 18:46
Closing this out since this should be now resolved in 14942+.

**Closed by sunilmut** 2016-10-14 18:46 UTC
Labels: bug, fixed, network
