### ISSUE TITLE
Console support for 24-bit color escape sequences

### ISSUE THREAD

**Issue by fpqc** [Microsoft/BashOnWindows#417] opened 2016-05-23 17:59 UTC
I know that quite a few people have asked for the console to support things like xterm's 256 color palette and mouse input, but in order to avoid having the BashOnWindows team go to all of that trouble supporting 256-color-mode just to have it be obsolete, I thought it was worth noting that almost all of the linux terminal emulators except xterm now support 24-bit truecolor escape sequences. ConEMU for Windows can enable displaying 24-bit color in console applications (almost exclusively used so FAR manager can display thumbnails), but it is not compatible with the Linux side of things, which probably would have to be handled on Microsoft's end. 

https://gist.github.com/XVilka/8346728

**Comment by cgull** [comment] 2016-05-23 19:32
xterm actually does support the relevant escape sequences, but renders via its 256-color palette.

**Comment by zadjii-msft** [comment] 2016-05-23 20:23
This is already something we're working on, for the anniversary update the full RGB (as well as the 256 color) sequences will be interpreted, but they'll be mapped to the nearest color in the already existent 16-color table in conhost. True RGB color support is on the backlog, but certainly not for this update unfortunately.

I'm closing this as a dupe of #76

**Closed by zadjii-msft** 2016-05-23 20:23 UTC
Labels: console, duplicate, fixinbound

**Comment by Maximus5** [comment] 2016-05-24 13:21
@zadjii-msft This issue is not actually forces msft to implement truecolor in conhost. In fact, and instead, topic starter asked you to bypass ANSI to [ConEmu](http://conemu.github.io/en/Xterm256Colors.html), which already supports true-color in console.
Current implementation of console output in WSL prohibits ConEmu from processing any ANSI written by linux applications. That tight integration with kernel(?) is rather bad.
I believe, the issue have to be reopened, ConEmu doesn't limit user to 16-colors palette. And proposed approximation would look awful...

**Comment by Maximus5** [comment] 2016-05-24 13:22
Actually, issue gh-406 is about bypassing ANSI to ConEmu.

**Comment by zerocool4u2** [comment] 2016-05-25 20:23
i was wondering about that, before the feature of mapping colors to 16-table, conemu and other emulators where able to display the actual colors? i didn't do a colortest before the patch on conemu, but right know it looks like the picture on #76, in the case that it was working it would be really nice to have an option to toggle this functionality on cmd to get it to work on other alternatives, anyone can confirm?, regards.

**Comment by Maximus5** [comment] 2016-05-26 00:27
From **conhost-based** emulators only ConEmu is able to display "actual" colors (24bit colors actually).
ConEmu stores actual color information in its own color buffer and do some magic to "synchronize" changes with conhost.

However, implementation is not perfect and in the current version true-color is available only at the bottom of the buffer. That's so because the mode was initially implemented for Far Manager.

Screenshot below is from cmd.exe started under ConEmu

~~~
type "%ConEmuBaseDir%\Addons\AnsiColors256.ans"
~~~

![2016-05-26_03-21-48](https://cloud.githubusercontent.com/assets/1222388/15560132/357e7d8c-22f1-11e6-8247-e8e981dfdffe.png)
