### ISSUE TITLE
scrollback buffer corrupted when using 'tree'

### ISSUE THREAD

**Issue by raymod2** [Microsoft/BashOnWindows#2005] opened 2017-04-25 19:07 UTC
using Microsoft Windows [Version 10.0.15063]
from bash:

> sudo apt install tree
> tree /sys

The filesystem hierarchy is displayed correctly.  However, when you scroll back to see the parts you missed they are not present in the scrollback buffer.  Furthermore, previous content in your scrollback buffer appears to be overwritten and is no longer accessible.

**Comment by raymod2** [comment] 2017-04-25 19:28
After closing and reopening my bash window I can no longer reproduce this.  I must have done something earlier that corrupted the scrollback buffer.  I'll update this issue when I have more information.

**Comment by zadjii-msft** [comment] 2017-04-25 21:55
> `sudo apt install tree`

Yep that'll do it. #1984, and others.

`tree` isn't teh problem here, `apt install` is. I thought I fixed it last release, but apparently not. Maybe t missed the release train. I'll investigate.

Closing this one as a dupe of that one.

**Closed by zadjii-msft** 2017-04-25 21:55 UTC
Labels: bug, console, duplicate
