### ISSUE TITLE
Bash install hangs at "Extracting Filesystem"

### ISSUE THREAD

**Issue by tigerhawkvok** [Microsoft/BashOnWindows#565] opened 2016-06-22 20:12 UTC
It's been sitting on this for over 30 minutes

![image](https://cloud.githubusercontent.com/assets/165937/16281793/c27f0410-387a-11e6-9463-cc1b229ac681.png)

It sat there for a few hours the other day, and via [this post](https://insights.ubuntu.com/2016/04/14/howto-ubuntu-on-windows-2/) I restarted and ran `lxrun /uninstall /full` before running `bash` again, which has repeated.

**Comment by benhillis** [comment] 2016-06-22 20:15
Could you try to run this command and share the output?

`bash.exe -c "ps auxf"`

**Comment by tigerhawkvok** [comment] 2016-06-22 20:43
21 minutes later ...

![image](https://cloud.githubusercontent.com/assets/165937/16282833/4ef87148-387f-11e6-92a8-51f5b0479f22.png)

**Comment by tigerhawkvok** [comment] 2016-06-22 20:48
Bash is apparently trying to do something, but not much?

![image](https://cloud.githubusercontent.com/assets/165937/16283002/d824b2f6-387f-11e6-92a1-7c9a8db1997b.png)

Would a dump file of either `bash` or `bash.exe` be helpful?

Build 14367

![image](https://cloud.githubusercontent.com/assets/165937/16283033/ee1cfe56-387f-11e6-8796-b08cf460c6ae.png)

**Comment by benhillis** [comment] 2016-06-22 21:10
Something looks hung, could you try the command I suggested?

`bash.exe -c "ps auxf"`

Also, I noticed you're not using cmd.exe.  Which terminal are you using?  It's possible something is going wrong because of that.  I can give it a try locally and see if I can reproduce your issue.

**Comment by tigerhawkvok** [comment] 2016-06-22 21:14
I did run the command if you check the screenshot.

It's also cmd.exe, it's just in a terminal wrapper to give it tabs with an extension for line-completion

![bashhang](https://cloud.githubusercontent.com/assets/165937/16283884/8bc30d5a-3883-11e6-80df-46a961cc6a51.png)


Could Cygwin conflict?

**Comment by benhillis** [comment] 2016-06-22 22:04
@tigerhawkvok I don't think Cygwin is conflicting.  I'd like to try to reproduce your issue using the terminal wrapper, what is it called?  Have you tried installing without the wrapper?

What would be useful is a trace of the install.  Tracing instructions below

1. Download the below two .txt files and rename them .cmd
2. Run start_lxcore_trace.cmd from an admin command prompt
3. Launch the install
4. Wait ~10 minutes.
5. Run stop_lxcore_trace.cmd from an admin command prompt
6. You should now see three .etl files in the directory you ran the script from.
7. Email the logs to: InsiderSupport@microsoft.com. Include in the subject / message to forward to the WSL team. In the body of the email mention it is for russalex. 

https://github.com/Microsoft/BashOnWindows/files/288621/start_lxcore_trace.txt 
https://github.com/Microsoft/BashOnWindows/files/288622/stop_lxcore_trace.txt

**Comment by tigerhawkvok** [comment] 2016-06-22 22:43
Also attaching here for ease of tracking. I use the ConEmu terminal wrapper: https://conemu.github.io/

[lxcore_trace_dumps.zip](https://github.com/Microsoft/BashOnWindows/files/328894/lxcore_trace_dumps.zip)

I doubt there's anything I'd consider sensitive in there that I haven't put in a public profile. Email has been sent!

I haven't tried without the wrapper, but I can disable auto-attach (eg, spawned windows are brought into the wrapper) and try again.

**Comment by benhillis** [comment] 2016-06-22 22:47
@tigerhawkvok Thanks I'll take a look.  Agreed our tracing is unlikely to have anything personally identifiable in it, it's really more of a [chain of custody](https://en.wikipedia.org/wiki/Chain_of_custody) precaution which applies much more to full memory dumps.

**Comment by tigerhawkvok** [comment] 2016-06-22 23:24
Here's another without Clink or ConEmu running

![image](https://cloud.githubusercontent.com/assets/165937/16287128/b33d4d16-3895-11e6-934d-11e35770eefe.png)


[lxcore_no_conemu.zip](https://github.com/Microsoft/BashOnWindows/files/328937/lxcore_no_conemu.zip)

**Comment by benhillis** [comment] 2016-06-23 23:05
@tigerhawkvok Thanks for providing the traces.  Unfortunately the only thing I've been able to determine is the following:

1. Our service is successfully creating an instance and our init process is launching.
2. The init process successfully forks and execs /bin/bash

After this there are no breadcrumbs, /bin/bash is clearly hanging on something but I'm at a loss as to what.  I will check with some other developers on the team to see if they have any ideas how we can further diagnose this.

**Comment by tigerhawkvok** [comment] 2016-06-26 03:57
FWIW, on 14371 I renamed my Cygwin folders (to break their paths) then tried this again, to the same result.

**Comment by carolynvs** [comment] 2016-06-27 19:11
I ran into this same problem today (build 14366) and after waiting 30 minutes I pressed `ENTER` in desperation. 😄 That immediately caused what appeared to unflushed output to print and everything was installed successfully.

**Comment by benhillis** [comment] 2016-07-01 23:33
After much effort I was able to debug this. We have a bug in our driver if you have more than 2 NT pagefiles on your system.  Any of you that are experiencing this issue could you please try disabling all but one of your pagefiles and trying to launch bash?

See #358 and #538 for more info.

**Comment by tigerhawkvok** [comment] 2016-07-06 00:09
That worked, **but** creating a user initially threw an error:

![screenshot 2016-07-05 17 05 02](https://cloud.githubusercontent.com/assets/165937/16603696/0253a994-42d3-11e6-9efa-cce096c467e9.png)


This was fixed by renaming `F:/TempFolder/temp` to `F:/TempFolder/Temp`. The creation script should check for the case of the actual temp folder before trying to write to it in a case-sensitive manner.

**Comment by benhillis** [comment] 2016-07-06 00:12
WSL is in kind of a strange place because it's case sensitive and the rest of NT sometimes doesn't play nicely.  I have a change locally that will fix this.

**Comment by gerardog** [comment] 2016-07-13 23:14
I confirm this issue installing Bash on build 14388, and disabling all pagefiles but one, fixed the problem.

**Comment by sysrage** [comment] 2016-08-03 03:21
I just encountered this but only have a single pagefile. In fact, I have 'Automatically manage paging file size for all drives' checked. Build 14393.10.

Pressing Enter like @carolynvs suggested had no effect.

**Comment by gerardog** [comment] 2016-08-03 06:35
@sysrage, please double check that the page file is set to 'none' on all drives except one and reboot.  Leaving it as 'Managed by the system' one more than 1 drive caused this issue on my pc.

**Comment by srcastro** [comment] 2016-08-03 13:17
I seem to have the same problem with version 14393, only have one drive and one pagefile.

I've noticed however that if I close the windows and run bash for windows it seems to work fine, however the default user is root and has no defined password.

Could this be related with the creation of users after install?

**Comment by freightrunner** [comment] 2016-08-03 17:08
Are you running Avast?  I had the same problem, uninstalled Avast (disabling wont work) and now everything works perfectly.

**Comment by papnikol** [comment] 2016-08-03 17:51
I have the same problem (ver.1607), only one pagefile, still getting stuck at filesystem extraction

**Comment by sysrage** [comment] 2016-08-03 18:01
I definitely only have one pagefile. I am running Avast. Not about to uninstall it just to mess with bash. I'll use cygwin or other options until a proper fix is available. Thanks.

**Comment by grhomesupport** [comment] 2016-08-04 14:40
I also have win10, one page file (system administered) and avast.      I am also stuck at "extracting file system, this will take a few minutes...."    

Is there any way to see the output from the file system extraction that seems to be stopped?  Can it output be verbose so we can see?

**Comment by srcastro** [comment] 2016-08-04 14:46
@freightrunner I do not have Avast, only windows defender (or whatever it's called now).

**Comment by ragvri** [comment] 2016-08-04 16:07
How do I check if I have two or more pagefiles and how do I disable them

**Comment by prasantakp** [comment] 2016-08-05 08:19
I had this issue today. it appears apt is trying to get updated in the background and as I am behind corporate proxy, it is unable to do so. Ideally it should timeout but here the deployment process keeps on wafting. Killed apt in task manager and it got to create default username task immediately

**Comment by srcastro** [comment] 2016-08-05 17:31
@prasantakp yup that's it.

**Comment by sryze** [comment] 2016-08-06 03:58
This happened to me too, then I tried to copy the error text in attempt to google it and it suddenly started working. 

I think it might have something to do with pressing enter like somebody already mentioned (for some reason when I copy something with right mouse click it gets pasted right back in, and the text had newlines).

**Comment by nicrulz** [comment] 2016-08-07 13:31
Had the same issue caused by Avast. Didn't have to remove it though. Went to Avast Settings > Active Protection > Web Shield, Customize > Exclusions. Checked the Processes to Exclude check box and added C:\Windows\System32\bash.exe. After that I ran a full uninstall with lxrun /uninstall /full Then tried the install again and it worked,

**Comment by Daniel15** [comment] 2016-08-08 06:23
I'm encountering this too. It seems like it's stuck on installing `language-pack-en`, @benhillis' command shows:
```
C:\Users\Daniel>bash.exe -c "ps auxf"
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0      0     0 ?        Ss    2432   0:00 /init
root        28  0.0  0.0      0     0 ?        Ss    2432   0:00 /bin/bash -c /usr/bin/apt install -y language-pack-en &> /dev/null
root        29  0.0  0.0      0     0 ?        S     2432   0:00  \_ /usr/bin/apt install -y language-pack-en
root        34  0.0  0.0      0     0 ?        S     2432   0:00      \_ /usr/lib/apt/methods/http
root        40  0.0  0.0      0     0 ?        Rs    2432   0:00 ps auxf
```

**Comment by aseering** [comment] 2016-08-08 12:51
Interesting -- I'm surprised that the installation is doing any `apt install`'s.  Would it be possible for packages to be rolled into the initial filesystem download?

It looks to me like it's not actually stuck *installing* `language-pack-en; it looks like it's stuck *downloading* it.

@Daniel15 -- is it possible that apt might have trouble connecting to the Internet in your environment?  Note that apt is pretty aggressive about using IPv6 if it's available (the official mirrors support IPv6 and IIRC apt defaults to using it if it appears to be available); that can cause problems in some environments.

**Comment by benhillis** [comment] 2016-08-08 15:32
@Daniel15 as @aseering menitone,d do you happen to have a third party firewall installed?  We've seen lots of issues with them (Avast, Bitdefender, Kaspersky) blocking internet access to Linux processes in WSL.

**Comment by Daniel15** [comment] 2016-08-08 15:52
It does seem like an IPv6 issue; I tried using `apt-get` within Bash and it
just hangs when trying to connect. I guess Comcast (or my router) isn't
very IPv6 friendly. I'll try it on my work laptop when I get a chance - All
of our internal systems and dev servers are IPv6-only so I suspect it'll
work fine there.

If the installation really needs to install some packages, can you modify
the installer to display the installation progress rather than having no
output?

Sent from my phone.

On Aug 8, 2016 8:32 AM, "Ben Hillis" <notifications@github.com> wrote:

@Daniel15 <https://github.com/Daniel15> as @aseering
<https://github.com/aseering> menitone,d do you happen to have a third
party firewall installed? We've seen lots of issues with them (Avast,
Bitdefender, Kaspersky) blocking internet access to Linux processes in WSL.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/BashOnWindows/issues/565#issuecomment-238274834>,
or mute the thread

**Comment by aseering** [comment] 2016-08-08 16:40
For what it's worth, I've had good experiences with Comcast and IPv6, but it really does depend on the router.

**Comment by Daniel15** [comment] 2016-08-08 17:39
I've got an Asus RT-N66U. I might just have to change some configuration or something.

I tried it on my work laptop and it worked fine, so I do think it's IPv6 causing issues.

**Comment by manuoren** [comment] 2016-08-09 08:01
Hello,
I have the same problem this topic is about, bash hangs while extracting files.
I changed the pagefile to be sure to have only one pagefile. but it didn't help.
I launched the tracefiles as asked by @benhillis at the begining of the topic but the lxcore_kernel.etl is 21GB after 10 minutes, a little hard to transfer...
May I try something else ?
Emmanuel
PS : here is the used versions
![image](https://cloud.githubusercontent.com/assets/20922582/17509012/22b77d68-5e18-11e6-9405-bb9deeb49b70.png)

**Comment by Efreak** [comment] 2016-08-11 07:43
I'm having the same issue on build 104393.51, repeatedly (three separate attempts, with reboots in between). Bash.exe is taking up ~24.8% cpu (99% of 1 core) fairly consistently. I am not using any command host replacement software, and I do not have multiple pagefiles. Pressing enter has no effect. Pressing Ctrl+C has no effect. *Last edit before submitting: Pressing Ctrl+Pause kills the lxrun process, but not the bash or init processes; typing exit leaves me with [a blank prompt](http://i.imgur.com/cMzl0K0.png). I plan to reboot, uninstall, and try again tomorrow.* The lxss folder is [528mb](http://i.imgur.com/i8Au4gA.png).

[![screenshot](http://i.imgur.com/XTt9noMs.png)](http://i.imgur.com/XTt9noM.png)

Since there seems to be some issues regarding networking/security software:

- I do not have any 3rd-party antivirus or firewall (I use the built-in tools); the only third-party security-related programs are Secunia and Malware Bytes (inactive/free version).
- I *do* use Hyper-V, however there are no virtual switches configured presently, and there were no VMs running at the time.
- XFast Lan/cfosspeed is the only 3rd party network filter installed.
- I use a pci-e wifi adapter for networking, and am unable to use ethernet for internet access*.
- I noticed [this issue](https://github.com/Microsoft/BashOnWindows/issues/565#issuecomment-238281214) before the current attempt, and [disabled](http://i.imgur.com/jFu18T9.png) ipv6 in my network adapter (my ISP doesn't provide ipv6 anyways).
- I do occasionally use hosted wifi, however it is currently disabled.
- [Here](http://i.imgur.com/febM1do.png) is [some](http://i.imgur.com/V5lvqyN.png) more process/[system](http://i.imgur.com/KQCcUg7.png) info, if it helps.

<sup>\*this makes for an *interesting* problems with Hyper-V, hosted wifi, and network adapter priorities</sup>

<sup>The connection losses were due to fighting netflix for limited bandwidth, however the last command was run with the router's bandwidth controls enabled to prevent such drops. It would be nice if the downloaded data was cached somewhere, so it doesn't have to be downloaded again each time to fully reinstall.</sup>

If there is any more information I should provide, please let me know. I'm not sure if you still need logfiles, however my internet connection speed would preclude sending massive logfiles as described above. However, on my next attempt I will try the batch file provided, and I can certainly send files that are relatively small (or that compress to a relatively small size).

**Comment by tradstone** [comment] 2016-08-20 13:14
Same issue here on build 14393.10, and it's happening to two of my separate machines.

**Comment by Efreak** [comment] 2016-08-25 00:46
I'm on build 14393.82 now, I'll try it again, but I don't really expect any changes.

**Comment by reijin90** [comment] 2016-08-29 19:57
I uninstalled, and will re install once this bug in regard to multiple pagefiles is fixed. Any news?

**Comment by muhsli** [comment] 2016-09-12 20:06
I was digging around to see if this problem have been fixed yet, and it seems that Avast have acknowledged and fixed it in their beta.
https://forum.avast.com/index.php?topic=185328.msg1332345#msg1332345

**Comment by reijin90** [comment] 2016-09-13 07:20
While Avast may have fixed the incompatibilities, this problem still may not be fixed. I never had Avast installed and faced the issue as well, probably due to having several pagefiles.

**Comment by Felk** [comment] 2016-09-14 13:37
It was fixed for me as well after updating Avast

**Comment by richkatz** [comment] 2016-10-20 19:51
Hi,

Is this fixed yet?  Where do we go to look at how many "page files" we have?  What I read online indicates that we have to run a

**Comment by richkatz** [comment] 2016-10-20 20:44
Hi,

I am getting the same problem. Is there a fix for this yet?    Is this just  a pagefile.sys - is it?  And are there instructions as to what exactly should be done with this file?

Microsoft has been talking about this feature for several months.  Is there a release date yet?  

Thanks.

Cheers,

Rich

**Comment by russalex** [comment] 2016-11-16 17:55
@richkatz, The pagefile.sys error has been fixed on the Insider branch.  Which Windows build are you running?

Additionally, you're asking about the release date.  We are keeping WSL in beta for a little longer as we make certain our main scenarios are covered.  We will continue to be in the release and the next Windows release will have all the goodness insiders get today.

I am tempted to close this thread simply due to the original issue being resolved.  Marking as fixed for that reason and will close at a later date.

**Comment by richkatz** [comment] 2016-11-16 19:16
Hi Russ,

Eventually it loaded up it just took a long time.   I'm using Windows 10. 14393.447.

So far it's been fun to play with.   I did get ssh to work.  That was a big plus.



Great work. 
 
Thanks!

Rich

**Comment by Efreak** [comment] 2016-11-18 21:25
I've finally gotten Bash working on 10.14393.447. My initial guess was cfosspeed (I don't have any other low-level/driver/etc non-microsoft, non-oem software), but I'm not sure. I disabled most non-microsoft services in msconfig and it worked after that--but I'm a bit confused, as it continued working even after I re-enabled them all. So it's working now, but I have absolutely no idea why.

**Comment by splus1** [comment] 2016-12-01 14:52
I was having the same problem (install hanging) but I had pagefiles on three drives (I have four drives total). Reduce the pagefile to one drive and set it to automatically manage. I rebooted, then ran "lxrun /uninstall /full". Then I ran "bash.exe -c "ps auxf", after which BASH was installed successfully. Thanks to the info in this thread.

**Comment by luohancfd** [comment] 2016-12-14 19:44
I also met the same issue. I'm using Symantec Endpoint Protection. The SEP blocks the connection to ubuntu server. What I did now is add a Firewall rule and allow traffic to the ip address:
 91.189.88.162,91.189.88.149,91.189.88.152,91.189.88.149
These correspond to two server: archive.ubuntu.com and security.ubuntu.com.
Hope it helps

**Closed** 2017-02-14 23:44 UTC
Labels: bug, fixed

**Comment by Bluesman74** [comment] 2017-02-27 12:56
I have Bullguard on my new PC install, what ports should I specify with those addresses?

**Comment by LusciousPear** [comment] 2017-04-01 01:11
Pressing "enter" also worked for me.

**Comment by staneslevski** [comment] 2017-04-05 13:11
I am laughing so hard that the solution was just to hit enter. I've been going crazy all day trying to fix/reinstall my bash on ubuntu on windows installation. Finally read all through this and just hit enter on the hanging prompt and it works perfectly. Thanks everyone. Keep up the good work, this software is making my windows laptop a thousand times more applicable as a development machine.

**Comment by xenonius** [comment] 2017-05-24 18:24
Many thanks to all the good souls that contributed to the solution of this issue.
My windows 10, build 14393 , kept hanging in spite of hitting <enter>.
The solution that worked for me was:
1. Reduce the number of pagefiles to 1.
2. Uninstall using >>lxrun /uninstall /full.
3. Reboot.
4 Install using >>lxrun /install.

**Comment by WillemPR** [comment] 2017-06-12 06:06
Was just trying to get this up and running.  Hitting "enter" seems to work for me after the "Extracting filesystem, this will take a few minutes..." prompt hangs for 10 to 15 minutes.

**Comment by xenonius** [comment] 2017-06-12 06:40
I believe my comment should remain displayed as it might help others.

 


                           ======================

                           Haim Nissani

            生命

**Comment by jcollum-cambia** [comment] 2017-06-27 23:45
Same issue here. This issue has been open for a year!??! And that "Hit Enter" bug is still in place? 

Anywayyyyy: 

1. Don't have Avast. 
1. Pressing Enter did nothing.
1. Only have one drive and pagefile is automatic. 
1.  bash.exe -c "ps auxf" produces: 

```
PS C:\WINDOWS\system32> bash.exe -c "ps auxf"
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0      0     0 ?        Ss    2433   0:00 /init
root         7  0.0  0.0      0     0 ?        Ss    2433   0:00 /bin/bash -c /usr/bin/apt update &> /dev/null
root         8  0.0  0.0      0     0 ?        S     2433   0:00  \_ /usr/bin/apt update
```

So it's updating, but not doing anything? Also, Ctrl C doesn't do anything, had to kill the window. 

At a loss for what to do next...

**Comment by budkin76** [comment] 2017-07-01 19:48
I don't have Avast, and pressing enter didn't do anything. Posting this in case it helps anyone:

I opened task manager, right clicked on "bash," and selected "end process." 

All of a sudden I was at the prompt asking for the username, and the rest of the install went fine. I'm not sure if it was just a coincidence but I'd been waiting for over 30 minutes.

**Comment by niemda** [comment] 2017-07-05 17:40
Tried installing Linux subsystem today, also ran in the issue with stuck installation (at apt-get update). My solution was to switch from corporate network to internet-only network because of the proxy. Probably, installation can check the connectivity and report this to the end user.

**Comment by jcollum-cambia** [comment] 2017-07-05 20:45
Tried completely disconnecting from work network and using my cell phone's wifi hotspot. 

1. Wifi on
1. Cat5 unplugged
1. connected to cell phone wifi, not work wifi

Then ran: 

```
$ lxrun /uninstall /full
This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications, new applications, and user data.
Type "y" to continue: y
Uninstalling...
````

Result (after several minutes of nothing): `Error: 0x80080005`

Nice cryptic error message. Thanks for nothing. Looking up that error message (I've tried this before) I got me nowhere, just some vague guesses that Avast was the issue (which I am not using).

**Comment by kumarradmin** [comment] 2017-07-16 10:51
I had the same issue of installation hanging for long time. I pressed Ctrl_C to cancel the installation. It prompted me to set up default username and password. Once I have setup the default username and password I received the message that installation was successful. It appears that installation was indeed hanging on the auto update after installation. I was able to get the apt-get updates afterwards.
All good.

**Comment by KodjoSuprem** [comment] 2017-07-19 16:42
In my case, my corporate proxy blocked supposed requests. disabling the proxy unlocked the installation process

**Comment by peijiandong** [comment] 2017-09-13 07:38
I faced the same issue. My case is my network is behind a proxy server. Connect the internet directly, everything works fine.

**Comment by jcollum-cambia** [comment] 2017-09-13 16:28
Update for me: completely gave up on WSL and use Cmder + Bash for Windows Node development. Current setup works okay enough.

**Comment by CyberTech** [comment] 2017-09-15 06:44
Just ran into this tonight -- apt was hanging in corporate environment. Killed apt task, and it dropped down to create user prompt and completed successfully.

**Comment by timrae** [comment] 2017-09-22 09:58
I'm having the same problem still... 

* Brand-new install of Windows 10 1607 (14393.0) running in virtual box 5.1.10 (with guest additions installed)
* Set virtual memory config to: "No paging file" 
* After the error occurred, I ran `lxrun /uninstall /full` in cmd and rebooted just in case
* Run bash command
* Press y to continue
* It downloads from the store successfully
* Displays `Extracting filesystem, this will take a few minutes...`
* CPU goes up to 100% for a few minutes, RAM never reaches 100%
* CPU eventually drops down to idle
* The `Extracting filesystem, this will take a few minutes...` message is still shown, and never disappears

**Comment by pani6me** [comment] 2017-10-22 19:14
This worked for me. 
1. launched another windows command prompt. 
2. typed lxrun /setdefaultuser 
3. entered uid/passwd

the bash came out of the hung state saying unix user <xyz> found.

**Comment by timothywisdom** [comment] 2017-11-13 23:58
I get as far as 
> Extracting filesystem, this will take a few minutes...

and a 2nd window opens with the title `AptPackageIndexUpdate`

This new window appears to HTTP GET 27 packages from https://archive.ubuntu.com and hangs with the lines:
> Fetched 3,945 kB in 23s (167 kN/s)
> Reading package lists... Done

Both the "Extracting..." and "AptPackageIndexUpdate" windows are hanging.

running `bash.exe -c "ps auxf"` from another powershell window produces:
> Cannot launch bash because the LX subsystem has an install, uninstall, or servicing operation pending.

There are two bash processes in my Task Manager. Both are at 17% CPU and using 180K of memory.

**Comment by Romout** [comment] 2018-02-16 14:53
I am encountering the same issue and tried to use SysInternals Process Explorer to see which processes are currently active.
![image](https://user-images.githubusercontent.com/4593052/36313210-2ab52bd0-1331-11e8-84a4-35a05e062ff3.png)

All devices are how ever showing no problems at all and the PC is connected to the internet as I type but I should note that it's behind a firewall. Is there some proxy configuration required to get it working?
